import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import {mainFunction} from './helpers/main-source.ts';
const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');
test('town guidance re-enables real legacy buttons after a blocked regional objective',()=>{
 const nodes:Record<string,any>=Object.fromEntries(['quest-title','quest-copy','quest-progress','quest-actions','quest-inspect','quest-map'].map(k=>[k,{disabled:true,hidden:true,textContent:'',onclick:null}])),opened:string[]=[];
 const deps={labActive:false,state:{regional:true,zone:'valley',player:{x:0,z:0},townLife:null},townReserved:()=>true,$:(id:string)=>nodes[id],document:{querySelector:()=>({textContent:''})},openPanel:(id:string)=>opened.push(id)};
 new Function(...Object.keys(deps),stripTypeScriptTypes('let selectedTownResident;'+mainFunction(main,'syncTownGuidance'))+';syncTownGuidance();')(...Object.values(deps));assert.equal(nodes['quest-actions'].hidden,false);assert.equal(nodes['quest-inspect'].disabled,false);assert.equal(nodes['quest-map'].disabled,false);nodes['quest-inspect'].onclick();nodes['quest-map'].onclick();assert.deepEqual(opened,['town-life','map']);
});
import {campaignGuidanceMapTarget} from '../src/campaign-guidance-map.ts';
import {CAMPAIGN_GUIDANCE_ENGINE} from '../src/campaign-guidance.ts';
import {loadCampaignGuidance,storeCampaignGuidance,campaignGuidanceStorageKey} from '../src/campaign-guidance-storage.ts';
import {createRegionalState,enableStartingTown,enableRestoration,serializeSave,worldTownSupplySources,worldRestorationPlan} from '../src/world.ts';
function trackingHarness(){
 const initial=enableRestoration(enableStartingTown(createRegionalState(73129))),nodes:Record<string,any>=Object.fromEntries(['quest-title','quest-copy','quest-progress','quest-actions','quest-inspect','quest-map'].map(k=>[k,{disabled:true,hidden:true,textContent:'',onclick:null,setAttribute(){}}])),stored=new Map<string,string>(),writes:string[]=[],opened:string[]=[],toasts:string[]=[];let denied=false;
 const deps={initial,nodes,stored,writes,opened,toasts,campaignGuidanceMapTarget,CAMPAIGN_GUIDANCE_ENGINE,loadCampaignGuidance,storeCampaignGuidance,campaignGuidanceStorageKey,worldTownSupplySources,worldRestorationPlan,localStorage:{getItem:(k:string)=>stored.get(k)??null,setItem:(k:string,v:string)=>{if(denied)throw Error('Storage blocked');writes.push(k);stored.set(k,v);}},toast:(s:string)=>toasts.push(s),campaignGuidanceMarkerId:(g:string,id:string)=>`guidance/${g}/${encodeURIComponent(id)}`};
 const names=['campaignGuidanceIdentity','getCampaignGuidanceSelection','setCampaignGuidanceSelection','campaignGuidanceHost','campaignGuidanceOptions','campaignGuidanceReady','syncCampaignGuidance','inspectCampaignGuidanceTarget','mapCampaignGuidanceTarget'];
 const setup=`let state=initial,labActive=false,sessionReloading=false,transitioning=false,coopPending=false,coopBoot=null,selectedTownResident;const coop={active:false,status:'idle',snapshot:null},startup={playing:true},campaignGuidanceMemory=new Map();let campaignGuidanceIdentityKey='',campaignGuidanceSelection={goalId:null},campaignGuidanceRender=0,guidanceMapSelection,guidanceMapTarget=null,guidanceMapTargetMarkerId;const $=id=>nodes[id],openPanel=id=>opened.push(id),showRegionalFood=id=>opened.push('food:'+id),showRegionalSupply=id=>opened.push('supply:'+id),showRegionalTrade=id=>opened.push('trade:'+id);function sync(){nodes['quest-title'].textContent='Legacy automatic town guidance';nodes['quest-copy'].textContent='Legacy';syncCampaignGuidance();}`;
 const api=new Function(...Object.keys(deps),stripTypeScriptTypes('function body(){'+setup+names.map(n=>mainFunction(main,n)).join('\n')+`;return {get:getCampaignGuidanceSelection,set:setCampaignGuidanceSelection,sync,host:campaignGuidanceHost,inspect:inspectCampaignGuidanceTarget,map:mapCampaignGuidanceTarget,read:()=>({state,selection:campaignGuidanceSelection,map:guidanceMapSelection,mapTarget:guidanceMapTarget}),flags:v=>{if('lab'in v)labActive=v.lab;if('pending'in v)coopPending=v.pending;if('boot'in v)coopBoot=v.boot;if('active'in v)coop.active=v.active;if('snapshot'in v)coop.snapshot=v.snapshot;if('status'in v)coop.status=v.status;if('transition'in v)transitioning=v.transition;if('state'in v)state=v.state;}};}`)+';return body();')(...Object.values(deps));
 return {api,initial,nodes,stored,writes,opened,toasts,deny:()=>{denied=true;}};
}
test('explicit guidance owns the final HUD across competing legacy writers and untracking restores automatic guidance',()=>{
 const h=trackingHarness(),before=serializeSave(h.initial);h.api.set({goalId:'supply'});const card=CAMPAIGN_GUIDANCE_ENGINE.project(h.initial).find(c=>c.id==='supply')!;assert.equal(h.nodes['quest-title'].textContent,card.title);assert.match(h.nodes['quest-progress'].textContent,/TRACKED/);assert.match(h.nodes['quest-progress'].textContent,/ m /);assert.equal(h.nodes['quest-inspect'].disabled,false);const stale=h.nodes['quest-inspect'].onclick;
 h.api.set({goalId:'construction'});stale();assert.deepEqual(h.opened,[]);assert.equal(h.nodes['quest-title'].textContent,CAMPAIGN_GUIDANCE_ENGINE.project(h.initial).find(c=>c.id==='construction')!.title);
 h.api.set({goalId:'town'});assert.equal(h.nodes['quest-title'].textContent,CAMPAIGN_GUIDANCE_ENGINE.project(h.initial).find(c=>c.id==='town')!.title);h.api.set({goalId:'regional'});assert.equal(h.nodes['quest-title'].textContent,CAMPAIGN_GUIDANCE_ENGINE.project(h.initial).find(c=>c.id==='regional')!.title);
 h.api.flags({transition:true});h.api.sync();assert.equal(h.nodes['quest-map'].disabled,true);h.nodes['quest-map'].onclick();assert.deepEqual(h.opened,[]);h.api.flags({transition:false});h.api.set({goalId:null});assert.equal(h.nodes['quest-title'].textContent,'Legacy automatic town guidance');assert.equal(serializeSave(h.initial),before);
 assert.match(mainFunction(main,'sync'),/syncRegionalObjective\(\);syncTownGuidance\(\);syncCampaignGuidance\(\);/);
});
test('main tracking isolates world and online-room preferences, keeps untracked cursors memory-only, and survives storage denial',()=>{
 const h=trackingHarness();h.api.set({goalId:null,sourceId:'scrap-a'});assert.equal(h.writes.length,0);assert.equal(h.toasts.length,0);h.api.set({goalId:'supply',sourceId:'scrap-a'});const soloKey=h.writes.at(-1)!;assert.match(soloKey,/:solo$/);
 h.api.flags({state:enableStartingTown(createRegionalState(12))});assert.deepEqual(h.api.get(),{goalId:null});h.api.set({goalId:'town'});h.api.flags({state:h.initial});assert.equal(h.api.get().goalId,'supply');
 const roomId='12345678-1234-4123-8123-123456789abc';h.api.flags({pending:true,boot:{roomId},snapshot:null});assert.deepEqual(h.api.get(),{goalId:null});assert.equal(h.api.host(),false);h.api.set({goalId:'care'});assert.match(h.writes.at(-1)!,new RegExp(':room:'+roomId+'$'));assert.notEqual(h.writes.at(-1),soloKey);
 h.deny();h.api.set({goalId:'restoration'});assert.equal(h.api.get().goalId,'restoration');assert.match(h.toasts.at(-1)!,/kept for this session/);const count=h.writes.length;h.api.flags({lab:true});h.api.set({goalId:'construction'});assert.equal(h.api.get().goalId,'restoration');assert.equal(h.writes.length,count);h.api.flags({lab:false,pending:false,boot:null,active:false});assert.equal(h.api.get().goalId,'supply');
});
test('tracked map and inspector retain exact source selection without collecting or teleporting',()=>{
 const h=trackingHarness(),source=worldTownSupplySources(h.initial)[1]!,before=serializeSave(h.initial);h.api.set({goalId:'supply',sourceId:source.id});const card=CAMPAIGN_GUIDANCE_ENGINE.project(h.initial,{sourceId:source.id}).find(c=>c.id==='supply')!;assert.ok(card.target);h.api.map(card.target);assert.equal(h.opened.at(-1),'map');const marker=h.api.read().map;assert.ok(marker.includes(encodeURIComponent(source.id)));h.api.inspect(card.target);assert.equal(h.opened.at(-1),'town-supply');assert.equal(h.api.get().sourceId,source.id);assert.equal(h.api.read().map,marker);assert.equal(serializeSave(h.initial),before);
});

test('untracked nondefault source and habitat map drafts select their exact canonical markers without pinning a goal',()=>{
 const h=trackingHarness(),source=worldTownSupplySources(h.initial).at(-1)!,site=worldRestorationPlan(h.initial.seed).sites.at(-1)!;for(const goalId of ['supply','restoration'] as const){const card=CAMPAIGN_GUIDANCE_ENGINE.project(h.initial,{sourceId:source.id,siteId:site.id}).find(c=>c.id===goalId)!;assert.ok(card.target);h.api.map(card.target);assert.equal(h.opened.at(-1),'map');assert.ok(h.api.read().map.includes(encodeURIComponent(card.target!.id)));assert.equal(h.api.get().goalId,null);assert.equal(h.writes.length,0);}
});

test('stale collected-source guidance callbacks cannot reopen or map a spent cache',()=>{
 const h=trackingHarness(),source=worldTownSupplySources(h.initial)[0]!,target=CAMPAIGN_GUIDANCE_ENGINE.project(h.initial,{sourceId:source.id}).find(c=>c.id==='supply')!.target!;h.api.flags({state:{...h.initial,collected:[...h.initial.collected,source.id]}});h.api.inspect(target);h.api.map(target);assert.deepEqual(h.opened,[]);assert.equal(h.api.get().goalId,null);
});

test('actual atlas inspector discards expired guidance markers while preserving ordinary regional routes',()=>{
 const opened:string[]=[],target={id:'live',panel:'town-supply'},state={frontierTrade:{},seed:73129},deps={state,panel:{},getCampaignGuidanceSelection:()=>({goalId:null}),guidanceMapSelection:undefined,guidanceMapTarget:null,guidanceMapTargetMarkerId:undefined,coop:{active:false},coopPending:false,mountWorldMapPanel:(_p:unknown,options:unknown)=>options,closePanel:()=>{},openPanel:(id:string)=>opened.push(id),campaignGuidanceOptions:()=>({}),campaignGuidanceMapTarget:(_s:unknown,id:string)=>id==='guidance/live'?target:undefined,inspectCampaignGuidanceTarget:(t:any)=>opened.push(t.panel),regionalFoodPlan:()=>({farms:[{id:'farm-1'}]}),showRegionalFood:(id:string)=>opened.push('food:'+id),showRegionalTrade:(id:string)=>opened.push('trade:'+id)};
 const options=new Function(...Object.keys(deps),stripTypeScriptTypes(mainFunction(main,'mountRegionalAtlas'))+';return mountRegionalAtlas();')(...Object.values(deps));options.inspectOverlay('guidance/supply/expired-source');assert.deepEqual(opened,[]);options.inspectOverlay('guidance/live');options.inspectOverlay('farm-1');options.inspectOverlay('freight-1');assert.deepEqual(opened,['town-supply','food:farm-1','trade:freight-1']);
});
