import {mainFunction} from './helpers/main-source.ts';
import * as guardModel from '../src/guard.ts';import * as guardView from '../src/guard-view.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import * as THREE from 'three/webgpu';
import * as world from '../src/world.ts';import * as session from '../src/coop-session.ts';import {sameWorld} from '../src/session.ts';import {createComboState} from '../src/combat.ts';import {worldHeight} from '../src/generation.ts';
const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');
class Storage{data=new Map<string,string>();getItem(k:string){return this.data.get(k)??null}setItem(k:string,v:string){this.data.set(k,v)}removeItem(k:string){this.data.delete(k)}}
function harness(boot=false){const storage=new Storage(),solo=world.createState(1),room=world.enableEconomy(world.enableEncounters(world.createConnectedState(73129)));const tail=main.slice(main.indexOf('function sendWorldAction(')),persist=main.slice(main.indexOf('function persist('),main.indexOf('/** Changing foundations'));
const source=`const townView=null;${mainFunction(main,'acceptTownLifeSnapshot')}let sessionReloading=false,sessionLoadFailed=false,persistedSessionRevision=0;function ensureSessionRevision(){return true}let state=initial,coopBoot=boot?{version:1,roomId:'room_12345678',world:initial,solo}:null,coopPending=boot,coopAccepted=false,coopLeaving=false,labActive=false,transitioning=false,combo=createComboState(),guard=createGuardState(),guardSnapshotAt=0,objects=[];const gameAudio={cue(){}};let impactAge=0,impactStrength=0;const sent=[],saved=[],saveCalls=[],moves=[],reloads=[],coop={active:true,canAct:true,pendingJumpIntent:null,send(a){sent.push(a);return true},disconnect(){this.active=false}},location={reload(){reloads.push(true)}},localStorage={},document={getElementById(){return null}},panel={hidden:true,dataset:{}},targetPosition=new THREE.Vector3(initial.player.x,0,initial.player.z);let commits=0;function toast(){}function clearInput(){}function animateAction(){}function sync(){}function syncCavePhysics(){}function closePanel(){}function restoreWorld(s){state=s}function storeSession(_store,s,activate,revision){saved.push(serializeSave(s));saveCalls.push({activate,revision})}function sendPhysics(m){moves.push(m)}function commit(s){state=s;commits++}${persist}${tail};return {sendWorldAction,receiveCoopSnapshot,leaveCoopSession,persist,read(){return {state,sent,saved,saveCalls,moves,reloads,commits,coopPending}},pending(id){coop.pendingJumpIntent=id},offline(){coop.active=false;coopPending=false}};`;
const deps={THREE,...guardModel,...guardView,...world,...session,sameWorld,worldHeight,createComboState,sessionStorage:storage};const h=new Function('initial','solo','boot',...Object.keys(deps),stripTypeScriptTypes('function body(){const startup={playing:true,initialized:true,failed:false,detail(){},fail(){},cleanup(){},report(){return String();},show(){}};'+source+'}',{mode:'strip'})+';return body();')(boot?room:solo,solo,boot,...Object.values(deps));return {h,storage,solo,room};}
test('online world intents and save button never commit a local campaign mutation',()=>{const {h}=harness();const bytes=world.serializeSave(h.read().state);h.sendWorldAction({type:'collect',id:'scrap-1'},'gather');h.sendWorldAction({type:'cave-water',command:{type:'clear-drain'}});assert.equal(h.read().commits,0);assert.equal(h.read().sent.length,2);assert.equal(world.serializeSave(h.read().state),bytes);assert.equal(h.persist(),false);assert.equal(h.read().saved.length,0);});
test('joining another foundation checkpoints solo and reconstructs exact room seed before accepting authority',()=>{const {h,storage,solo,room}=harness();h.receiveCoopSnapshot({roomId:'room_12345678',world:room,combo:createComboState(),notices:[]});assert.equal(h.read().reloads.length,1);assert.equal(h.read().saved[0],world.serializeSave(solo));assert.deepEqual(h.read().saveCalls,[{activate:true,revision:0}]);assert.equal(session.readCoopBoot(storage)!.soloRevision,0);assert.equal(session.readCoopBoot(storage)!.world.seed,73129);assert.equal(h.read().state.seed,1,'no mixed-seed live geometry');assert.equal(h.read().coopPending,true);});
test('matching boot accepts server world only, leaving restores original solo through isolated return route',()=>{const {h,storage,solo,room}=harness(true);session.writeCoopBoot(storage,'room_12345678',room,solo);const authoritative={...room,revision:room.revision+3};h.receiveCoopSnapshot({roomId:'room_12345678',world:authoritative,combo:createComboState(),notices:[]});assert.equal(h.read().state,authoritative);assert.equal(h.read().saved.length,0);assert.equal(h.read().coopPending,false);h.leaveCoopSession();assert.equal(world.serializeSave(session.consumeSoloReturn(storage)!),world.serializeSave(solo));assert.equal(session.readCoopBoot(storage),null);});
test('real physics snapshot handler has a separate online branch without world ticks or local hits',()=>{const online=main.slice(main.indexOf('else if(coop.active||coopPending){'),main.indexOf("else{if(!activeConversation)state=applyAction(state,{type:'move'",main.indexOf('else if(coop.active||coopPending){')));assert.ok(online.includes('coop.move('));assert.ok(!online.includes('applyAction'));assert.ok(!online.includes('stepWorldEncounters'));assert.ok(main.includes("if(event.type!=='hit'||coop.active)continue"));assert.ok(main.includes("if(coop.active)return coop.send({type:'refit-equipment',seed})"));});

test('incoming pre-jump snapshots cannot cancel a pending request; processed authority is sent to the real worker channel',()=>{const {h,room}=harness(true),motion={feetY:0,vy:6.6,grounded:false,crouched:false,jumpId:1,landingId:0,jumpQueued:false,lastJumpIntent:'jump-1',jumpStatus:'launched'};h.pending('jump-1');h.receiveCoopSnapshot({roomId:'room_12345678',world:room,combo:createComboState(),revision:5,notices:[],motion:{...motion,jumpId:0,vy:0,grounded:true,lastJumpIntent:null}});assert.equal(h.read().moves.filter(m=>m.type==='online-motion').length,0);h.pending(null);h.receiveCoopSnapshot({roomId:'room_12345678',world:room,combo:createComboState(),revision:6,notices:[],motion});const command=h.read().moves.find(m=>m.type==='online-motion');assert.equal(command.revision,6);assert.equal(command.motion.vy,6.6);assert.equal(command.motion.jumpId,1);});
