import test from 'node:test';import assert from 'node:assert/strict';import {Worker} from 'node:worker_threads';
import * as THREE from 'three/webgpu';
import {LAB_CASES,LAB_OBSTACLES,newMetrics,sampleMetrics,frameSummary,modelChecks,createReport,type LabSample} from '../src/dev-lab.ts';
import {DEFAULT_TUNING,sanitizeTuning,TUNING_FIELDS} from '../src/tuning.ts';
import {createComboState,requestComboAttack,stepCombo,cancelCombo,comboBufferOpen,type ComboSnapshot,type ComboResult} from '../src/combat.ts';
import {createAvatar,attackPose} from '../src/avatar.ts';import {idleAnimation} from '../src/locomotion.ts';

async function workerHarness(t:any){const worker=new Worker(`const {parentPort}=require('node:worker_threads');globalThis.self=globalThis;self.postMessage=m=>parentPort.postMessage(m);globalThis.setInterval=fn=>{globalThis.tick=fn;return 1};parentPort.on('message',async m=>{if(m.type==='advance'){for(let i=0;i<m.ticks;i++)globalThis.tick();parentPort.postMessage({type:'advanced'});}else await self.onmessage({data:m});});import(${JSON.stringify(new URL('../src/physics.worker.ts',import.meta.url).href)}).then(()=>parentPort.postMessage({type:'boot'}));`,{eval:true,execArgv:['--experimental-strip-types']});t.after(()=>worker.terminate());let epoch=0,error:unknown;const messages:any[]=[],snapshots:any[]=[];worker.on('error',e=>error=e);worker.on('message',m=>{messages.push(m);if(m.type==='error')error=new Error(m.message);if(m.type==='snapshot')snapshots.push(m);});async function take(type:string){const end=Date.now()+4000;while(true){if(error)throw error;const index=messages.findIndex(m=>m.type===type);if(index>=0)return messages.splice(index,1)[0];assert.ok(Date.now()<end,'waiting '+type);await new Promise(r=>setTimeout(r,1));}}const send=(m:Record<string,unknown>)=>worker.postMessage({epoch,...m});async function tick(n=1){const i=snapshots.length;send({type:'advance',ticks:n});await take('advanced');return snapshots.slice(i);}await take('boot');send({type:'init',x:0,z:0,obstacles:[]});await take('ready');return {send,take,tick,async zone(extra:Record<string,unknown>={}){epoch++;send({type:'zone',x:0,z:0,obstacles:[],...extra});await take('ready');},get latest(){return snapshots.at(-1);},get epoch(){return epoch;}};}

test('all nine published lab scenarios execute against the real worker and combo engine, identically across three resets',{timeout:30000},async t=>{
 const w=await workerHarness(t),baseline:unknown[]=[];
 for(let run=0;run<3;run++)for(const [caseIndex,c] of LAB_CASES.entries()){
  await w.zone({...c.spawn,obstacles:LAB_OBSTACLES,bound:18,sandbox:true});w.send({type:'tuning',value:DEFAULT_TUNING});await w.take('tuning-ack');w.send({type:'input',x:0,z:0,analog:true});await w.tick(60);let combo=createComboState(),targets=c.targets.map(t=>({...t}));const metrics=newMetrics(w.latest);const snapshot=():ComboSnapshot=>({player:{x:w.latest.x,z:w.latest.z,y:w.latest.feetY,facing:c.facing,hp:w.latest.crouched||!w.latest.grounded?0:100},targets:targets.map(t=>({...t,alive:t.hp>0})),obstacles:LAB_OBSTACLES});
  const consume=(r:ComboResult)=>{combo=r.state;for(const e of r.events){if(e.type==='stage')metrics.combat.stages.push(e.stage);if(e.type==='whiff')metrics.combat.whiffs++;if(e.type==='cancel'&&e.reason==='stun')metrics.combat.stuns++;if(e.type==='cancel'&&e.reason==='dodge')metrics.combat.cancelled++;if(e.type==='hit'){metrics.combat.hits++;metrics.combat.damage+=e.damage;const target=targets.find(t=>t.id===e.targetId)!;target.hp=Math.max(0,target.hp-e.damage);metrics.combat.hp=target.hp;}}};
  for(let tick=0;tick<Math.round(c.seconds*60);tick++){const i=c.input(tick);w.send({type:'input',...i,analog:true});await w.tick();if(i.attack&&(combo.phase==='idle'||comboBufferOpen(combo)))consume(requestComboAttack(combo,snapshot(),undefined,'auto'));if(i.cancel)consume(cancelCombo(combo,'dodge'));if(i.stun)consume(cancelCombo(combo,'stun'));consume(stepCombo(combo,1/60,snapshot()));sampleMetrics(metrics,w.latest);}
  const checks=c.checks(metrics,DEFAULT_TUNING);assert.deepEqual(checks.filter(c=>!c.pass),[],`${c.id}: ${JSON.stringify(checks)}`);if(run===0)baseline[caseIndex]=metrics;else assert.deepEqual(metrics,baseline[caseIndex],`${c.id} repeat ${run+1}`);
 }
});

test('worker captures and restores airborne and low-ceiling pose; lab tuning is ignored outside sandbox',async t=>{
 const w=await workerHarness(t);w.send({type:'input',x:0,z:0,jump:true});await w.tick(9);w.send({type:'input',x:0,z:0,paused:true});w.send({type:'capture',requestId:'air'});const air=(await w.take('captured')).checkpoint;assert.ok(air.feetY>.5&&air.vy>0&&!air.grounded);
 await w.zone({sandbox:true});w.send({type:'tuning',value:{jumpSpeed:9,gravity:12}});await w.take('tuning-ack');w.send({type:'input',x:0,z:0,jump:true});await w.tick(20);assert.ok(w.latest.feetY>1.5);
 await w.zone({checkpoint:air});await w.tick(20);assert.ok(Math.abs(w.latest.feetY-air.feetY)<1e-6);assert.equal(w.latest.grounded,false);w.send({type:'input',x:0,z:0});await w.tick();assert.ok(w.latest.feetY>air.feetY,'captured vertical momentum resumes');
 await w.zone({obstacles:LAB_OBSTACLES,x:-6,z:8});w.send({type:'input',x:1,z:0,crouch:true,analog:true});await w.tick(110);w.send({type:'input',x:0,z:0,paused:true});w.send({type:'capture',requestId:'low'});const low=(await w.take('captured')).checkpoint;assert.equal(low.crouched,true);await w.zone({sandbox:true});await w.tick(3);await w.zone({obstacles:LAB_OBSTACLES,checkpoint:low});await w.tick(3);assert.equal(w.latest.crouched,true);assert.equal(w.latest.stance,1);assert.ok(Math.abs(w.latest.feetY-low.feetY)<1e-6);w.send({type:'input',x:0,z:0});await w.tick(30);assert.equal(w.latest.crouched,true,'roof keeps restored pose low');
 await w.zone();w.send({type:'tuning',value:{jumpSpeed:9,gravity:12}});w.send({type:'input',x:0,z:0,jump:true});const samples=await w.tick(100);assert.ok(Math.max(...samples.map(s=>s.feetY))<1.3,'campaign ignores lab tuning');
 const before=w.latest.x;w.send({type:'teleport',epoch:w.epoch-1,x:100,z:100});await w.tick();assert.equal(w.latest.x,before,'late lab epoch cannot move restored campaign');
});

test('lab values and quantiles are bounded and reports contain measured samples only',()=>{
 const t=sanitizeTuning({speedScale:Infinity,gravity:999,jumpSpeed:-100});assert.equal(t.speedScale,1);assert.equal(t.gravity,28);assert.equal(t.jumpSpeed,4);for(const [key,d] of Object.entries(TUNING_FIELDS)){assert.ok(t[key as keyof typeof t]>=d.min&&t[key as keyof typeof t]<=d.max);}
 assert.deepEqual(frameSummary([]),{sampleCount:0,p50Ms:null,p95Ms:null,p99Ms:null,maxMs:null,over33ms:0});const f=frameSummary([10,20,30,40,50,NaN,-1]);assert.equal(f.sampleCount,5);assert.equal(f.p50Ms,30);assert.equal(f.p95Ms,50);assert.equal(f.p99Ms,50);assert.equal(f.over33ms,2);
 const report=createReport(73129,DEFAULT_TUNING,3,{backend:'unmeasured-test'});assert.equal(report.runs.length,0);assert.ok(Object.values(report.manual).every(x=>x==='not-reviewed'));assert.equal(report.status,'running');assert.equal(report.warmupStepsPerCase,60);
 assert.deepEqual(modelChecks(73129).filter(c=>!c.pass),[]);
});

test('staff combo has distinct anticipatory, contact and recovery poses without root/collider drift',()=>{
 const avatar=createAvatar(),initial=avatar.root.position.clone();const yaws=new Set<number>();for(const stage of [1,2,3] as const)for(const phase of ['prep','active','recovery'])for(const progress of [0,.25,.5,.75,1]){
  const pose={stage,phase,progress};avatar.update(idleAnimation(),null,0,pose);avatar.root.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(avatar.root,true);assert.ok(bounds.min.y>=-.002,JSON.stringify({pose,min:bounds.min.y}));assert.ok(bounds.max.y<=2.16,JSON.stringify({pose,max:bounds.max.y}));assert.deepEqual(avatar.root.position,initial);yaws.add(attackPose(pose).yaw);}
 assert.ok(yaws.size>10,'weapon arc is not a single pulse envelope');assert.ok(attackPose({stage:1,phase:'prep',progress:1}).yaw<0);assert.ok(attackPose({stage:2,phase:'prep',progress:1}).yaw>0);assert.ok(attackPose({stage:3,phase:'active',progress:.5}).reach>.9);
});

test('worker-clock course ignores delayed ready handling and 40-snapshot delivery backlog; stopping restores manual input',async t=>{
 const w=await workerHarness(t);let baseline:LabSample|undefined;
 for(const batch of [1,40]){await w.zone({x:-12,z:-13,obstacles:LAB_OBSTACLES,bound:18,sandbox:true});const before=await w.tick(40);assert.ok(before.every(s=>s.x===-12&&s.step===before[0].step),'sandbox stays paused while ready is delayed');w.send({type:'lab-script',id:'run-brake'});w.send({type:'input',x:-1,z:1,paused:false});let values:any[]=[];for(let n=0;n<210;n+=batch)values.push(...await w.tick(Math.min(batch,210-n)));const last=values.at(-1);assert.equal(values[60].playback.tick,0);assert.equal(values[60].playback.warmup,0);assert.equal(values[0].playback.warmup,60);const plain={x:last.x,z:last.z,feetY:last.feetY,vx:last.vx,vz:last.vz,vy:last.vy,grounded:last.grounded,crouched:last.crouched,stance:last.stance,sliding:last.sliding};if(!baseline)baseline=plain;else assert.deepEqual(plain,baseline,'physical result is independent of main-message batching');}
 w.send({type:'lab-script',id:'run-brake'});w.send({type:'input',x:0,z:0,paused:false});await w.tick(70);w.send({type:'lab-stop'});await w.tick(10);const stop=w.latest.x;w.send({type:'input',x:-1,z:0,analog:true,paused:false});const manual=await w.tick(40);assert.equal(manual.at(-1).playback,null);assert.ok(w.latest.x<stop-1,'manual movement works after cancelled script');
});

import {staffSectorPoints} from '../src/combat-view.ts';import {DEFAULT_COMBO_TUNING} from '../src/combat.ts';import {stepFacing} from '../src/locomotion.ts';import {matchingPose} from '../src/dev-lab.ts';
test('energy-sector rendering matches combat range/arc and the dominant grip remains on the staff',()=>{
 for(const attack of DEFAULT_COMBO_TUNING.attacks){const points=staffSectorPoints(attack);assert.ok(points.every(p=>Math.abs(Math.hypot(p.x,p.z)-attack.range)<1e-10));assert.ok(Math.abs(Math.atan2(points[0]!.x,points[0]!.z)+attack.arc/2)<1e-10);assert.ok(Math.abs(Math.atan2(points.at(-1)!.x,points.at(-1)!.z)-attack.arc/2)<1e-10);}
 const avatar=createAvatar();for(const stage of [1,2,3] as const)for(const phase of ['prep','active','recovery'])for(const progress of [0,.25,.5,.75,1]){avatar.update({...idleAnimation(),speed:6,lean:.15,turn:.1},null,0,{stage,phase,progress});avatar.root.updateMatrixWorld(true);const tool=avatar.root.getObjectByName('surveyStaff')!,hand=avatar.root.getObjectByName('rightHand')!.getWorldPosition(new THREE.Vector3()),line=new THREE.Line3(tool.localToWorld(new THREE.Vector3(0,-.475,0)),tool.localToWorld(new THREE.Vector3(0,.475,0)));assert.ok(hand.distanceTo(line.closestPointToPoint(hand,true,new THREE.Vector3()))<.001,`${stage} ${phase} ${progress} grip detached`);}
 let facing=0;for(let i=0;i<30;i++)facing=stepFacing(facing,8,0,1/60,18);assert.ok(Math.abs(facing-Math.PI/2)<1e-9);const p={x:1,z:2,feetY:1.3,vy:3,crouched:false,grounded:false,stance:0};assert.equal(matchingPose(p,{...p}),true);assert.equal(matchingPose({...p,feetY:2},p),false);assert.equal(matchingPose(null,p),false);
});
