import test from 'node:test';import assert from 'node:assert/strict';
import {createEncounters,advanceEncounters,hitEncounter,validEncounters,encounterClear,ENEMY_RULES,type EncounterContext} from '../src/encounters.ts';
const seeds=[{id:'guard',x:0,z:0,zone:'valley'}];const context=(x=0,z=2):EncounterContext=>({zone:'valley',players:[{id:'solo',x,y:0,z,hp:100}],height:()=>0,obstacles:[],defeated:[]});
test('enemy has readable locked windup, one contact, recovery and dodge counterplay',()=>{let s=createEncounters(seeds),events=[];for(let i=0;i<43;i++){const r=advanceEncounters(s,1/60,context());s=r.state;events.push(...r.events);}assert.equal(events.filter(e=>e.type==='damage').length,0);assert.equal(s.enemies[0]!.phase,'prepare');for(let i=0;i<20;i++){const r=advanceEncounters(s,1/60,context());s=r.state;events.push(...r.events);}assert.equal(events.filter(e=>e.type==='damage').length,1);assert.equal(s.enemies[0]!.phase,'recover');let d=createEncounters(seeds);d=advanceEncounters(d,.5,context()).state;const r=advanceEncounters(d,.6,context(3,0));assert.equal(r.events.filter(e=>e.type==='damage').length,0);assert.equal(r.state.enemies[0]!.heading,0,'windup does not track dodging player');});
test('pursuit moves the real target, respects solids and never crosses its home leash',()=>{let s=createEncounters(seeds);s=advanceEncounters(s,1,context(0,7)).state;assert.ok(s.enemies[0]!.z>2);let blocked=createEncounters(seeds);const c={...context(0,7),obstacles:[{x:0,y:1,z:1,hx:3,hz:.1,hy:1}]};blocked=advanceEncounters(blocked,1,c).state;assert.equal(blocked.enemies[0]!.z,0);for(let i=0;i<40;i++)s=advanceEncounters(s,1,context(0,9)).state;assert.ok(Math.hypot(s.enemies[0]!.x,s.enemies[0]!.z)<=ENEMY_RULES.leash);assert.equal(encounterClear({x:0,y:0,z:0},{x:0,y:0,z:2},c.obstacles),false);});
test('jump evades low bite, occlusion rejects strike, and co-op target ordering is stable',()=>{let s=advanceEncounters(createEncounters(seeds),.76,context()).state;assert.equal(s.enemies[0]!.phase,'strike');const jumping={...context(),players:[{id:'solo',x:0,y:1,z:2,hp:100}]};assert.equal(advanceEncounters(s,.2,jumping).events.filter(e=>e.type==='damage').length,0);const hidden={...context(),obstacles:[{x:0,z:1,hx:2,hz:.1,hy:2}]};assert.equal(advanceEncounters(s,.2,hidden).events.filter(e=>e.type==='damage').length,0);const c=context();c.players=[{id:'z',x:0,y:0,z:2,hp:100},{id:'a',x:0,y:0,z:2,hp:100}];assert.equal(advanceEncounters(createEncounters(seeds),1/60,c).state.enemies[0]!.targetId,'a');});
test('accepted staff hit staggers then persistent death is validated exactly once',()=>{let s=advanceEncounters(createEncounters(seeds),.3,context()).state;s=hitEncounter(s,'guard',24).state;assert.equal(s.enemies[0]!.hp,76);assert.equal(s.enemies[0]!.phase,'stagger');assert.equal(advanceEncounters(s,.3,context()).events.filter(e=>e.type==='damage').length,0);s=hitEncounter(s,'guard',100).state;assert.equal(validEncounters(s,seeds,['guard']),true);assert.equal(validEncounters(s,seeds,[]),false);assert.equal(hitEncounter(s,'guard',24).state,s);assert.equal(advanceEncounters(s,1,{...context(),defeated:['guard']}).events.length,0);});
test('fixed-step subdivision, zone pause, save identity, and hostile data boundaries',()=>{const a=advanceEncounters(createEncounters(seeds),1,context(0,7)).state;let b=createEncounters(seeds);for(let i=0;i<60;i++)b=advanceEncounters(b,1/60,context(0,7)).state;assert.deepEqual(a,b);assert.deepEqual(advanceEncounters(b,1,{...context(),zone:'dungeon'}).state.enemies,b.enemies);assert.equal(validEncounters(JSON.parse(JSON.stringify(b)),seeds,[]),true);assert.equal(validEncounters({...b,enemies:[b.enemies[0],b.enemies[0]]},seeds,[]),false);for(const dt of [NaN,Infinity,-1,100])assert.equal(advanceEncounters(b,dt,context()).state,b);assert.equal(hitEncounter(b,'guard',NaN).state,b);});

import {createConnectedState,enableEncounters,encounterObjects,commitEncounterHit,stepWorldEncounters,applyAction,parseSave,serializeSave,validateSave} from '../src/world.ts';
test('world optional encounter pack preserves foundations, survives saves and replaces passive contact damage',()=>{const base=createConnectedState(73129);let s=enableEncounters(base);assert.equal(s.generationManifest,base.generationManifest);const enemy=encounterObjects(s).find(o=>o.kind==='enemy')!;s=applyAction(s,{type:'move',x:enemy.x,z:enemy.z-2});const hp=s.player.hp;s=applyAction(s,{type:'tick',dt:.5});assert.equal(s.player.hp,hp,'passive radius damage is removed');s=commitEncounterHit(s,enemy.id,24);assert.equal(s.encounters!.enemies.find(e=>e.id===enemy.id)!.hp,76);assert.ok(validateSave(s));let saved=parseSave(serializeSave(s))!;assert.equal(saved.encounters!.enemies.find(e=>e.id===enemy.id)!.hp,76);saved=commitEncounterHit(saved,enemy.id,100);assert.ok(saved.defeated.includes(enemy.id));assert.ok(validateSave(saved));const n=saved.defeated.length;saved=commitEncounterHit(saved,enemy.id,100);assert.equal(saved.defeated.length,n);const r=stepWorldEncounters(saved,1/60,{obstacles:[]});assert.ok(validateSave(r.state));});
test('full standing movement proxy rejects low obstacles below the sight line',()=>{const c={...context(0,7),obstacles:[{x:0,y:.2,z:1,hx:3,hz:.1,hy:.2}]};assert.equal(encounterClear({x:0,y:0,z:0},{x:0,y:0,z:2},c.obstacles),true,'eye line stays distinct from body clearance');const s=advanceEncounters(createEncounters(seeds),1,c).state;assert.ok(s.enemies[0]!.z<.2,'standing proxy cannot step through ankle-high solid');});
test('saved encounter phase durations and authoritative ground elevations are verified',()=>{const s=enableEncounters(createConnectedState(73129));const e=s.encounters!.enemies[0]!;for(const patch of [{y:e.y+11},{phase:'strike',remaining:1.1},{phase:'idle',remaining:.1}]){const bad={...s,encounters:{...s.encounters!,enemies:s.encounters!.enemies.map(v=>v.id===e.id?{...v,...patch}:v)}};assert.equal(validateSave(bad),false);}});
test('movement slope never exceeds the declared family limit',()=>{const c={...context(0,7),height:(_x:number,z:number)=>1.29*z};const s=advanceEncounters(createEncounters(seeds),1,c).state;assert.equal(s.enemies[0]!.z,0);});
test('one strike stays valid through repeated co-op roster replacements and resets contact budget next attack',()=>{const players=['a','b','c','d'].map(id=>({id,x:0,y:0,z:2,hp:100})),ctx={...context(),players};let s=advanceEncounters(createEncounters(seeds),.76,ctx).state;s=advanceEncounters(s,1/60,ctx).state;assert.deepEqual(s.enemies[0]!.hitIds,['a','b','c','d']);for(const id of ['e','f','g','h']){const result=advanceEncounters(s,1/60,{...ctx,players:[...players.slice(1),{id,x:0,y:0,z:2,hp:100}]});s=result.state;assert.equal(result.events.filter(e=>e.type==='damage').length,0);assert.deepEqual(s.enemies[0]!.hitIds,['a','b','c','d']);assert.ok(validEncounters(s,seeds,[]));}const replacement={...ctx,players:[...players.slice(1),{id:'newcomer',x:0,y:0,z:2,hp:100}]},events=[];for(let i=0;i<160;i++){const result=advanceEncounters(s,1/60,replacement);s=result.state;events.push(...result.events);assert.ok(validEncounters(s,seeds,[]));}assert.ok(events.some(e=>e.type==='damage'&&e.playerId==='newcomer'&&e.attackId===2));assert.equal(events.filter(e=>e.type==='damage'&&e.attackId===2).length,4);});
