import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {handleCoop} from '../server/coop-api.ts';
import {createState,createConnectedState,applyAction,validateSave,serializeSave,worldEndpoints,worldObjects,activeObjects} from '../src/world.ts';
import {causalPlan} from '../src/causal.ts';
import {worldHeight} from '../src/generation.ts';
import type {D1Database,D1Statement} from '../server/coop-store.ts';
import type {CoopSnapshot,CoopAction,CoopMove} from '../src/coop-protocol.ts';
import {CoopClient} from '../src/coop.ts';
import {createRoom,advanceRoom,joinRoom,syncRoom,snapshot} from '../server/coop-authority.ts';
import {CoopStore} from '../server/coop-store.ts';

/** Real SQLite + real TCP HTTP clients; production code has no test-auth bypass. */
function sqliteD1(db:DatabaseSync):D1Database{
  return {prepare(sql:string):D1Statement{
    let values:unknown[]=[];
    return {bind(...args:unknown[]){values=args;return this;},
      async first<T>(){return (db.prepare(sql).get(...values as never[])??null) as T|null;},
      async all<T>(){return {results:db.prepare(sql).all(...values as never[]) as T[]};},
      async run(){const result=db.prepare(sql).run(...values as never[]);return {success:true,meta:{changes:Number(result.changes)}};}};
  }};
}
async function fixture(){
  const sqlite=new DatabaseSync(':memory:');
  for(const file of readdirSync(new URL('../drizzle',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL(`../drizzle/${file}`,import.meta.url),'utf8'));
  const DB=sqliteD1(sqlite);let now=1_800_000_000_000;let origin='';
  const server=createServer(async(req,res)=>{
    try{const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(chunk as Buffer);
      const headers=new Headers();for(const [k,v]of Object.entries(req.headers))if(v!==undefined)headers.set(k,Array.isArray(v)?v.join(','):v);
      const body=Buffer.concat(chunks).toString('utf8');const request=new Request(`${origin}${req.url}`,{method:req.method,headers,...(body?{body}:{})});
      const response=await handleCoop(request,{DB},now);res.writeHead(response?.status??404,Object.fromEntries(response?.headers??[]));res.end(await response?.text());
    }catch(e){res.writeHead(500);res.end(String(e));}
  });
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  const address=server.address();assert(address&&typeof address==='object');origin=`http://127.0.0.1:${address.port}`;
  async function raw(user:string,path:string,body?:unknown,extra:Record<string,string>={}){
    const response=await fetch(`${origin}/api/coop${path}`,{method:body===undefined?'GET':'POST',headers:{'oai-authenticated-user-id':user,Origin:origin,...(body===undefined?{}:{'Content-Type':'application/json'}),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});
    return {status:response.status,body:await response.json(),headers:response.headers};
  }
  return {raw,origin,sqlite,DB,time:()=>now,advance:(ms:number)=>{now+=ms;},stop:async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));sqlite.close();}};
}
async function expedition(f:Awaited<ReturnType<typeof fixture>>,world=createState(73129),count=4){
  const created=await f.raw('host','/rooms',{name:'Host',world});assert.equal(created.status,201,JSON.stringify(created.body));
  const players=[{user:'host',s:created.body as CoopSnapshot}];
  for(let i=1;i<count;i++){const joined=await f.raw(`guest-${i}`,'/join',{name:`Guest ${i}`,code:created.body.code});assert.equal(joined.status,200,JSON.stringify(joined.body));players.push({user:`guest-${i}`,s:joined.body});}
  return players;
}
async function input(f:Awaited<ReturnType<typeof fixture>>,p:{user:string;s:CoopSnapshot},actions:CoopAction[]=[],move?:CoopMove){
  const response=await f.raw(p.user,`/rooms/${p.s.roomId}/sync`,{seq:p.s.ack+1,sessionId:p.s.sessionId,actions,...(move?{move}:{})});
  assert.equal(response.status,200,JSON.stringify(response.body));p.s=response.body;return p.s;
}


import {compileCustomEquipment,equipmentCost,equipmentFor,type EquipmentRecipeInput} from '../src/equipment.ts';
import {equipmentCombat} from '../src/equipment-combat.ts';
const light:EquipmentRecipeInput={version:2,seed:0,parts:{grip:'linen',shaft:'ash',head:'fork'}},heavy:EquipmentRecipeInput={version:2,seed:0,parts:{grip:'braced',shaft:'ironwood',head:'crown'}};
function salvaged(){let s=createConnectedState(73129);for(const o of activeObjects(s))if(o.kind==='scrap'||o.kind==='core'){s=applyAction(s,{type:'move',x:o.x,z:o.z});s=applyAction(s,{type:'collect',id:o.id});}return applyAction(s,{type:'move',...worldEndpoints(s).spawn});}
function conserved(s:CoopSnapshot,total:{scrap:number;core:number}){assert.equal(s.world.inventory.scrap+equipmentCost(s.world.equipment).scrap,total.scrap);assert.equal(s.world.inventory.core+equipmentCost(s.world.equipment).core,total.core);assert(validateSave(s.world));}
test('real HTTP custom and legacy staff actions are host-owned, durable, exactly recycled and idempotent',async()=>{const f=await fixture();try{const world=salvaged(),total={...world.inventory},solo=serializeSave(world),[host,guest]=await expedition(f,world,2);assert(host&&guest);for(const command of [{type:'assemble-equipment',recipe:heavy},{type:'refit-equipment',seed:1}] as CoopAction[]){await input(f,guest,[command]);assert.equal(guest.s.world.equipment?.active,null);assert.match(guest.s.notices.join(' '),/host/);}for(const recipe of [light,heavy,light]){const request={seq:host.s.ack+1,sessionId:host.s.sessionId,actions:[{type:'assemble-equipment',recipe}]};const first=await f.raw('host',`/rooms/${host.s.roomId}/sync`,request);assert.equal(first.status,200);host.s=first.body;assert.deepEqual(host.s.world.equipment!.active,compileCustomEquipment(recipe).ref);conserved(host.s,total);const again=await f.raw('host',`/rooms/${host.s.roomId}/sync`,request);assert.equal(again.status,200);assert.deepEqual(again.body.world,host.s.world);host.s=again.body;await input(f,host,[{type:'assemble-equipment',recipe}]);conserved(host.s,total);}await input(f,host,[{type:'refit-equipment',seed:1}]);assert.equal(host.s.world.equipment?.active?.version,1);conserved(host.s,total);await input(f,host,[{type:'refit-equipment',seed:null}]);assert.deepEqual(host.s.world.inventory,total);const persisted=await f.raw('host',`/rooms/${host.s.roomId}`);assert.deepEqual(persisted.body.world,host.s.world);assert.equal(serializeSave(world),solo);}finally{await f.stop();}});
test('HTTP fails closed for unknown parts, sockets, malformed versions and all client authority claims',async()=>{const f=await fixture();try{const [host]=await expedition(f,salvaged(),1);assert(host);const original=host.s.world;for(const recipe of [{...light,version:1},{...light,seed:-1},{...light,seed:1.5},{...light,stats:{damage:999}},{...light,recipeHash:'deadbeef'},{...light,cost:{scrap:-100}},{...light,parts:{...light.parts,head:'maul'}},{...light,parts:{...light.parts,head:'<svg onload=alert(1)>'}},JSON.parse('{"version":2,"seed":0,"parts":{"grip":"linen","shaft":"ash","head":"fork"},"__proto__":{}}')]){const r=await f.raw('host',`/rooms/${host.s.roomId}/sync`,{seq:1,sessionId:host.s.sessionId,actions:[{type:'assemble-equipment',recipe}]});assert.equal(r.status,400);}const stored=await f.raw('host',`/rooms/${host.s.roomId}`);assert.deepEqual(stored.body.world,original);assert.equal(stored.body.ack,0);const [poor]=await expedition(f,createState(12),1);assert(poor);await input(f,poor,[{type:'assemble-equipment',recipe:heavy}]);assert.equal(poor.s.world.equipment?.active,null);assert.equal(poor.s.world.inventory.scrap,0);}finally{await f.stop();}});
test('shared kit cannot change any connected player’s committed staff/guard, including same-request ordering',async()=>{const f=await fixture();try{const [host,guest]=await expedition(f,salvaged(),2);assert(host&&guest);await input(f,host,[{type:'assemble-equipment',recipe:light},{type:'attack-press'},{type:'assemble-equipment',recipe:heavy},{type:'refit-equipment',seed:null}]);assert.deepEqual(host.s.world.equipment!.active,compileCustomEquipment(light).ref);assert.deepEqual(host.s.combo.attack,equipmentCombat(equipmentFor(host.s.world.equipment!.active!)).attacks[0]);const stamina=host.s.combo.stamina;assert(host.s.notices.every(n=>/commitment/.test(n)));f.advance(1000);await input(f,host);await input(f,guest,[{type:'attack-press'}]);await input(f,host,[{type:'assemble-equipment',recipe:heavy}]);assert.equal(host.s.world.equipment!.active!.recipeHash,compileCustomEquipment(light).ref.recipeHash);assert(host.s.notices.some(n=>/commitment/.test(n)));f.advance(1000);await input(f,host);await input(f,guest,[{type:'guard-press',intentId:'guest-kit-lock'}]);assert.equal(guest.s.guard.phase,'windup');await input(f,host,[{type:'refit-equipment',seed:null}]);assert(host.s.notices.some(n=>/commitment/.test(n)));await input(f,guest,[{type:'guard-cancel'}]);await input(f,host,[{type:'assemble-equipment',recipe:heavy}]);assert(host.s.notices.some(n=>/commitment/.test(n)));f.advance(1000);await input(f,host,[{type:'assemble-equipment',recipe:heavy},{type:'guard-press',intentId:'host-kit-lock'},{type:'assemble-equipment',recipe:light}]);assert.deepEqual(host.s.world.equipment!.active,compileCustomEquipment(heavy).ref);assert.equal(host.s.guard.phase,'windup');assert.equal(host.s.combo.attackId,1);assert(host.s.combo.stamina<=100-22);assert(stamina<100);conserved(host.s,salvaged().inventory);}finally{await f.stop();}});
test('long host-only resume retires absent attacks without refunds and does not let absent records deadlock reassembly',async()=>{const f=await fixture();try{const [host,guest,guardGuest]=await expedition(f,salvaged(),3);assert(host&&guest&&guardGuest);await input(f,guest,[{type:'attack-press'}]);const attack=guest.s.combo.attack!,stamina=guest.s.combo.stamina,regen=guest.s.combo.regenDelay;await input(f,guardGuest,[{type:'guard-press',intentId:'absent-guard'}]);const guardStamina=guardGuest.s.combo.stamina,cooldown=guardGuest.s.guard.cooldownRemaining;f.advance(120000);const resumed=await f.raw('host',`/rooms/${host.s.roomId}/resume`,{});assert.equal(resumed.status,200);host.s=resumed.body;await input(f,host,[{type:'assemble-equipment',recipe:heavy}]);assert.deepEqual(host.s.world.equipment!.active,compileCustomEquipment(heavy).ref);const parked=host.s.peers.find(p=>p.id===guest.s.selfId)!;assert.equal(parked.combo.phase,'idle');assert.equal(parked.combo.attack,null);assert.equal(parked.combo.buffered,false);assert.equal(parked.combo.stamina,stamina);assert.equal(parked.combo.regenDelay,regen);assert(Math.abs(parked.combo.cancelLockRemaining-(attack.prep+attack.active+attack.recovery))<1e-9);const back=await f.raw(guest.user,`/rooms/${guest.s.roomId}/resume`,{});assert.equal(back.status,200);guest.s=back.body;await input(f,guest,[{type:'attack-press'}]);assert.equal(guest.s.combo.attackId,1);assert.equal(guest.s.combo.attack,null);assert.equal(guest.s.combo.stamina,stamina);assert.equal(guest.s.combo.regenDelay,regen);assert(guest.s.combo.cancelLockRemaining>0);const guardBack=await f.raw(guardGuest.user,`/rooms/${guardGuest.s.roomId}/resume`,{});assert.equal(guardBack.status,200);guardGuest.s=guardBack.body;assert.equal(guardGuest.s.guard.phase,'idle');assert.equal(guardGuest.s.guard.cooldownRemaining,cooldown);assert.equal(guardGuest.s.combo.stamina,guardStamina);assert(guardGuest.s.combo.cancelLockRemaining>0);f.advance(1000);await input(f,host);await input(f,guest,[{type:'attack-press'}]);assert.equal(guest.s.combo.attackId,2);assert.deepEqual(guest.s.combo.attack,equipmentCombat(compileCustomEquipment(heavy)).attacks[0]);conserved(guest.s,salvaged().inventory);}finally{await f.stop();}});
test('lost successful custom assembly reply retries identical serialized recipe with one material transaction',async()=>{const f=await fixture();let client:CoopClient|undefined;try{const requests:any[]=[],world=salvaged();let lost=false;const fetcher:typeof fetch=async(url,init)=>{const response=await fetch(url,{...init,headers:{...init?.headers,'oai-authenticated-user-id':'host',Origin:f.origin}});if(String(url).endsWith('/sync')){requests.push(JSON.parse(String(init?.body)));if(!lost&&response.ok){lost=true;client!.setSuspended(true);throw new Error('Lost saved custom assembly reply');}}return response;};client=new CoopClient({baseURL:f.origin,fetch:fetcher,onSnapshot:()=>{}});await client.create({name:'Host',world});const recipe=structuredClone(heavy);assert(client.send({type:'assemble-equipment',recipe}));recipe.parts.head='maul';const deadline=Date.now()+4000;while(!lost&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));assert(lost);assert.equal(client.snapshot!.world.equipment!.active,null);client.setSuspended(false);while(client.snapshot!.world.equipment!.active?.version!==2&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));assert.deepEqual(client.snapshot!.world.equipment!.active,compileCustomEquipment(heavy).ref);assert.deepEqual(requests[0],requests[1]);conserved(client.snapshot!,world.inventory);const stored=await f.raw('host',`/rooms/${client.snapshot!.roomId}`);conserved(stored.body,world.inventory);assert.equal(stored.body.world.events.filter((e:string)=>e.includes('Edited staff assembled')).length,1);}finally{client?.disconnect();await f.stop();}});
test('CAS retry rechecks connected peer commitment instead of committing an outdated affordable edit',async()=>{const f=await fixture();try{const [host,guest]=await expedition(f,salvaged(),2);assert(host&&guest);let unblock!:()=>void,reached!:()=>void,block=true;const gate=new Promise<void>(r=>unblock=r),waiting=new Promise<void>(r=>reached=r);const delayed:D1Database={prepare(sql){const original=f.DB.prepare(sql);const proxy:D1Statement={bind(...values){original.bind(...values);return proxy;},first:()=>original.first(),all:()=>original.all(),async run(){if(block&&sql.startsWith('UPDATE axiom_coop_rooms')){block=false;reached();await gate;}return original.run();}};return proxy;}};const request=(p:typeof host,actions:CoopAction[])=>new Request(`${f.origin}/api/coop/rooms/${p.s.roomId}/sync`,{method:'POST',headers:{'oai-authenticated-user-id':p.user,Origin:f.origin,'Content-Type':'application/json'},body:JSON.stringify({seq:1,sessionId:p.s.sessionId,actions})});const pending=handleCoop(request(host,[{type:'assemble-equipment',recipe:heavy}]),{DB:delayed},f.time());await waiting;const cast=await handleCoop(request(guest,[{type:'attack-press'}]),{DB:f.DB},f.time());assert.equal(cast!.status,200);unblock();const late=await pending;assert.equal(late!.status,200);const body=await late!.json() as CoopSnapshot;assert.equal(body.world.equipment!.active,null);assert(body.notices.some(n=>/commitment/.test(n)));assert.deepEqual(body.world.inventory,salvaged().inventory);assert.equal(body.peers.find(p=>p.id===guest.s.selfId)!.combo.attackId,1);conserved(body,salvaged().inventory);}finally{await f.stop();}});
test('explicit guest leave and room close preserve staff deadlines through immediate resume',async()=>{for(const operation of ['leave','close'] as const){const f=await fixture();try{const [host,guest]=await expedition(f,salvaged(),2);assert(host&&guest);const actor=operation==='leave'?guest:host;await input(f,actor,[{type:'attack-press'}]);const before=actor.s.combo,remaining=before.attack!.prep+before.attack!.active+before.attack!.recovery-before.elapsed;const exited=await f.raw(actor.user,`/rooms/${actor.s.roomId}/${operation}`,{sessionId:actor.s.sessionId});assert.equal(exited.status,200);const parked=exited.body.combo;assert.equal(parked.phase,'idle');assert.equal(parked.attack,null);assert.equal(parked.buffered,false);assert.equal(parked.stamina,before.stamina);assert.equal(parked.regenDelay,before.regenDelay);assert(Math.abs(parked.cancelLockRemaining-remaining)<1e-9);if(operation==='leave'){await input(f,host,[{type:'assemble-equipment',recipe:heavy}]);assert.deepEqual(host.s.world.equipment!.active,compileCustomEquipment(heavy).ref);}const resumed=await f.raw(actor.user,`/rooms/${actor.s.roomId}/resume`,{});assert.equal(resumed.status,200);actor.s=resumed.body;await input(f,actor,[{type:'attack-press'},{type:'guard-press',intentId:'resume-no-free-action'}]);assert.equal(actor.s.combo.attackId,before.attackId);assert.equal(actor.s.combo.attack,null);assert.equal(actor.s.combo.stamina,before.stamina);assert.equal(actor.s.combo.regenDelay,before.regenDelay);assert.equal(actor.s.guard.receipt?.reason,'cooldown');assert(Math.abs(actor.s.combo.cancelLockRemaining-remaining)<1e-9);}finally{await f.stop();}}});
test('attack → enter → exit → refit cannot erase the paid recovery deadline in a single HTTP batch',async()=>{const f=await fixture();try{let world=salvaged();world=applyAction(world,{type:'move',...worldEndpoints(world).entrance});const [host]=await expedition(f,world,1);assert(host);await input(f,host,[{type:'attack-press'},{type:'enter'},{type:'exit'},{type:'assemble-equipment',recipe:heavy},{type:'refit-equipment',seed:1}]);assert.equal(host.s.world.zone,'valley');assert.equal(host.s.combo.attackId,1);assert.equal(host.s.combo.attack,null);assert.equal(host.s.combo.phase,'idle');assert.equal(host.s.combo.stamina,86);assert(host.s.combo.cancelLockRemaining>0);assert.equal(host.s.world.equipment!.active,null);assert.equal(host.s.notices.filter(n=>/commitment/.test(n)).length,2);f.advance(1000);await input(f,host,[{type:'assemble-equipment',recipe:heavy}]);assert.deepEqual(host.s.world.equipment!.active,compileCustomEquipment(heavy).ref);}finally{await f.stop();}});
