import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import * as THREE from 'three/webgpu';
import {compileEquipment,compileCustomEquipment,equipmentFor,equipmentRecipeInput,parseEquipmentRecipe,validEquipmentRecipeInput,validEquipment,emptyEquipment,equipmentCost,EQUIPMENT_MANIFEST,EQUIPMENT_PARTS,type EquipmentRecipeInput} from '../src/equipment.ts';
import {createState,createConnectedState,applyAction,activeObjects,serializeSave,parseSave,validateSave,causalContext} from '../src/world.ts';import {compareEquipmentRefs} from '../src/equipment-lab.ts';import {equipmentCombat} from '../src/equipment-combat.ts';import {createAvatar} from '../src/avatar.ts';import {idleAnimation} from '../src/locomotion.ts';import {comboEligibleTargets,createComboState,requestComboAttack,stepCombo} from '../src/combat.ts';import {action} from '../server/coop-validation.ts';
export const light:EquipmentRecipeInput={version:2,seed:0,parts:{grip:'linen',shaft:'ash',head:'fork'}},heavy:EquipmentRecipeInput={version:2,seed:0,parts:{grip:'braced',shaft:'ironwood',head:'crown'}};
const plans=[...EQUIPMENT_PARTS.grip].flatMap(grip=>EQUIPMENT_PARTS.shaft.flatMap(shaft=>EQUIPMENT_PARTS.head.flatMap(head=>{try{return [compileCustomEquipment({version:2,seed:0,parts:{grip,shaft,head}})];}catch{return [];}})));
export function salvaged(connected=false){let s=connected?createConnectedState(73129):createState(73129);for(const o of activeObjects(s))if(o.kind==='scrap'||o.kind==='core'){s=applyAction(s,{type:'move',x:o.x,z:o.z});s=applyAction(s,{type:'collect',id:o.id});}return s;}
test('v1 compiler remains byte-identical for all 128 golden seed plans and content identity',()=>{assert.deepEqual(EQUIPMENT_MANIFEST,{framework:1,domain:'equipment',version:1,recipe:'resonant-staff@1',contentHash:'2c932107'});assert.equal(createHash('sha256').update(JSON.stringify(Array.from({length:128},(_,seed)=>compileEquipment(seed)))).digest('hex'),'d0a29e38c06833ea2fd16d73199b0fc2b23af79cbc5ebfba79e3a66e845fd211');for(let seed=0;seed<128;seed++)assert.deepEqual(equipmentFor(compileEquipment(seed).ref),compileEquipment(seed));});
test('same seed supports eight explicit physical recipes, recompiled custom identities and bounded JSON round trips',()=>{assert.equal(plans.length,8);assert.equal(new Set(plans.map(p=>p.ref.recipeHash)).size,8);for(const p of plans){assert.equal(p.ref.version,2);assert.deepEqual(p.spec,equipmentRecipeInput(p).parts);assert.deepEqual(equipmentFor(p.ref),p);assert.deepEqual(parseEquipmentRecipe(JSON.stringify(equipmentRecipeInput(p))),equipmentRecipeInput(p));assert.deepEqual(p.stats,compileEquipment(0,p.spec).stats);assert.deepEqual(p.recipe,compileEquipment(0,p.spec).recipe);assert.deepEqual(p.plan,compileEquipment(0,p.spec).plan);assert.ok(validEquipment({manifest:EQUIPMENT_MANIFEST,active:p.ref}));}});
test('authoring rejects unknown, prototype, accessor, oversized, nested and client-derived claims without execution',()=>{let calls=0;const accessor=Object.defineProperty({...light},'parts',{get(){calls++;return light.parts;}});const attacks:any[]=[null,[],{}, {...light,version:1},{...light,seed:'0'},{...light,seed:-1},{...light,seed:1.5},{...light,seed:2**32},{...light,parts:{...light.parts,head:'<img onerror=alert(1)>'}},{...light,stats:{damage:999}},{...light,cost:{scrap:-999}},{...light,recipeHash:'ffffffff'},{...light,parts:{...light.parts,extra:1}},Object.assign(Object.create({stolen:true}),light),accessor,JSON.parse('{"version":2,"seed":0,"parts":{"grip":"linen","shaft":"ash","head":"fork","__proto__":{}}}'),JSON.parse('{"version":2,"seed":0,"parts":{"grip":"linen","shaft":"ash","head":"fork"},"constructor":{}}')];for(const input of attacks){assert.equal(validEquipmentRecipeInput(input),false);assert.throws(()=>compileCustomEquipment(input));assert.equal(action({type:'assemble-equipment',recipe:input}),null);}assert.equal(calls,0);for(const raw of ['{',JSON.stringify(light)+' '.repeat(1024),JSON.stringify({...light,extra:'α'.repeat(500)})])assert.throws(()=>parseEquipmentRecipe(raw));assert.throws(()=>parseEquipmentRecipe(JSON.stringify({...light,parts:{...light.parts,head:'maul'}})),/rejected/);assert.equal(action({...light,type:'assemble-equipment',recipe:light,damage:999}),null);assert.equal(action(Object.assign(Object.create({bad:true}),{type:'assemble-equipment',recipe:light})),null);const ref=compileCustomEquipment(light).ref;for(const bad of [{...ref,recipeHash:'00000000'},{...ref,parts:heavy.parts},{...ref,stats:{}},{...ref,version:3}])assert.equal(validEquipment({manifest:EQUIPMENT_MANIFEST,active:bad}),false);assert.equal(({} as any).stolen,undefined);});
test('custom refit ledger conserves resources across seeds, edits, old refs, restore, save and legacy migration boundaries',()=>{for(const connected of [false,true]){let s=salvaged(connected);const total={...s.inventory},historical=causalContext(s).historicalPumpRepaired,manifest=JSON.stringify(s.generationManifest);for(const p of [...plans,...plans]){const input=equipmentRecipeInput(p),next=applyAction(s,{type:'assemble-equipment',recipe:input});s=next;assert.deepEqual(s.equipment?.active,p.ref);assert.equal(applyAction(s,{type:'assemble-equipment',recipe:input}),s);assert.equal(s.inventory.scrap+equipmentCost(s.equipment).scrap,total.scrap);assert.equal(s.inventory.core+equipmentCost(s.equipment).core,total.core);assert.ok(validateSave(s));assert.deepEqual(parseSave(serializeSave(s)),s);assert.equal(causalContext(s).historicalPumpRepaired,historical);assert.equal(JSON.stringify(s.generationManifest),manifest);}s=applyAction(s,{type:'refit-equipment',seed:5});assert.equal(s.equipment?.active?.version,1);assert.ok(validateSave(s));s=applyAction(s,{type:'assemble-equipment',recipe:light});s=applyAction(s,{type:'refit-equipment',seed:null});assert.deepEqual(s.inventory,total);assert.deepEqual(s.equipment,emptyEquipment());assert.ok(validateSave(s));const legacy=salvaged(connected);delete legacy.equipment;const bytes=serializeSave(legacy);assert.equal(serializeSave(parseSave(bytes)!),bytes);}for(const state of [createState(),{...salvaged(),zone:'cave' as const},{...salvaged(),player:{...salvaged().player,hp:0}}])assert.equal(applyAction(state,{type:'assemble-equipment',recipe:heavy}),state);});
test('edited builds compare actual distinct parts on identical reset conditions without campaign writes',()=>{const before=serializeSave(salvaged(true)),a=compileCustomEquipment(light),b=compileCustomEquipment(heavy),r=compareEquipmentRefs(a.ref,b.ref);assert.equal(r.version,2);assert.notEqual(r.a.equipment.recipeHash,r.b.equipment.recipeHash);assert.deepEqual(r.a.runs.map(r=>r.conditions),r.b.runs.map(r=>r.conditions));for(const side of [r.a,r.b]){assert.equal(side.runs.length,12);assert.ok(Object.values(side.checks).every(Boolean));assert.equal(side.runs[0]!.endState.attackId,3);}assert.deepEqual(compareEquipmentRefs(a.ref,b.ref),r);assert.equal(serializeSave(salvaged(true)),before);});
test('all edited production rigs use exact compiler meshes, real two-hand sockets, and authoritative projected reach',()=>{for(const p of plans){const avatar=createAvatar();avatar.setEquipment(equipmentFor(p.ref));for(const stage of [1,2,3] as const)for(const phase of ['prep','active','recovery'])for(const progress of [0,.5,1]){avatar.update({...idleAnimation(),speed:6,lean:.15,turn:.1},null,0,{stage,phase,progress});avatar.root.updateMatrixWorld(true);const staff=avatar.root.getObjectByName('surveyStaff')!;for(const [hand,socket]of [['rightHand','grip-dominant'],['leftHand','grip-support']]){const h=avatar.root.getObjectByName(hand!)!.getWorldPosition(new THREE.Vector3()),g=staff.getObjectByName(socket!)!.getWorldPosition(new THREE.Vector3());const side=hand==='rightHand'?'right':'left';if(avatar.getPoseEvidence().combat?.grips[side].loaded)assert.ok(h.distanceTo(g)<.001);if(phase==='active')assert.equal(avatar.getPoseEvidence().combat?.grips[side].loaded,true);}for(const shape of p.plan.shapes){const mesh=staff.getObjectByName(shape.id)! as THREE.Mesh;assert.deepEqual(mesh.position.toArray(),[shape.center.x,shape.center.y,shape.center.z]);}const box=new THREE.Box3().setFromObject(avatar.root,true);assert.ok(box.min.y>=-.002);assert.ok(box.max.y<=2.16);}const tuning=equipmentCombat(p),attack=tuning.attacks[0],snapshot={player:{x:0,y:0,z:0,facing:0,hp:100},targets:[{id:'target',x:0,y:0,z:attack.range}],obstacles:[]};assert.equal(comboEligibleTargets(snapshot,attack).length,1);assert.equal(comboEligibleTargets({...snapshot,targets:[{id:'far',x:0,y:0,z:attack.range+.001}]},attack).length,0);assert.equal(comboEligibleTargets({...snapshot,obstacles:[{x:0,z:1,hx:2,hz:.2}]},attack).length,0);const start=requestComboAttack(createComboState(tuning),snapshot,tuning).state;assert.equal(stepCombo(start,10,snapshot,tuning).events.filter(e=>e.type==='hit').length,1);}});

import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import * as guardModel from '../src/guard.ts';import * as equipmentModel from '../src/equipment.ts';
test('production custom handler keeps previews/local authority/lab isolation distinct and retains personal commitment',()=>{
 const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),handler=main.slice(main.indexOf('function assembleLoadout('),main.indexOf('function renderCaveMouth('));
 const deps={...guardModel,...equipmentModel,applyAction};const initial=salvaged(true);
 const source=`let livePractice=null,liveResumeRequested=false;function stopLivePractice(){}function pauseLivePractice(){}let state=initial,labActive=false,labRunning=false,labEquipment,transitioning=false,physicsReady=true,guard=createGuardState(),combo={phase:'idle',buffered:false,cancelLockRemaining:0,stunRemaining:0,stamina:37,regenDelay:.4},saves=0,visual=null;const requests=[];const coop={active:false,send(action){requests.push(structuredClone(action));return true}};const character={setEquipment(p){visual=p}},sync=()=>{},persist=()=>{saves++};function currentEquipment(){return equipmentFor(labActive?labEquipment:state.equipment?.active)}${handler};return {assembleLoadout,read(){return {state,labEquipment,combo,guard,saves,visual,requests}},set(k,v){if(k==='lab')labActive=v;if(k==='running')labRunning=v;if(k==='phase')combo.phase=v;if(k==='lock')combo.cancelLockRemaining=v;if(k==='transition')transitioning=v;if(k==='online')coop.active=v;if(k==='guard')guard.phase=v;}};`;
 const h=new Function('initial',...Object.keys(deps),stripTypeScriptTypes('function body(){const activeConversation=null;function closeConversation(){}const startup={playing:true,initialized:true,failed:false,detail(){},fail(){},cleanup(){},report(){return String();},show(){}};'+source+'}',{mode:'strip'})+';return body();')(initial,...Object.values(deps));
 for(const [k,v]of [['phase','active'],['lock',.2],['guard','active'],['transition',true],['running',true]]){h.set(k,v);h.assembleLoadout(heavy);assert.equal(h.read().state,initial);assert.equal(h.read().saves,0);h.set(k,k==='phase'||k==='guard'?'idle':k==='lock'?0:false);}h.assembleLoadout({...heavy,stats:{damage:999}});assert.equal(h.read().saves,0);h.assembleLoadout(light);assert.equal(h.read().saves,1);assert.deepEqual(h.read().state.equipment.active,compileCustomEquipment(light).ref);assert.equal(h.read().combo.stamina,37);assert.equal(h.read().combo.regenDelay,.4);const campaign=h.read().state,bytes=serializeSave(campaign);h.set('lab',true);h.assembleLoadout(heavy);assert.equal(h.read().state,campaign);assert.equal(serializeSave(h.read().state),bytes);assert.deepEqual(h.read().labEquipment,compileCustomEquipment(heavy).ref);assert.deepEqual(h.read().visual.spec,heavy.parts);assert.equal(h.read().saves,1);h.set('lab',false);h.set('online',true);h.assembleLoadout(heavy);assert.equal(h.read().state,campaign);assert.equal(h.read().saves,1);assert.deepEqual(h.read().requests,[{type:'assemble-equipment',recipe:heavy}]);assert.equal(h.read().combo.stamina,37);
});
import {retireComboCommitment,cancelCombo,comboAttackDuration} from '../src/combat.ts';
test('shared solo/online lifecycle retirement retains recovery, stun, stamina, regen and forbids later old-geometry contact',()=>{const tuning=equipmentCombat(compileCustomEquipment(heavy)),snapshot={player:{x:0,y:0,z:0,facing:0,hp:100},targets:[{id:'target',x:0,y:0,z:2}],obstacles:[]};let combo=requestComboAttack(createComboState(tuning),snapshot,tuning).state;combo=stepCombo(combo,.05,snapshot,tuning).state;const retired=retireComboCommitment({...combo,buffered:true});assert.equal(retired.attack,null);assert.equal(retired.buffered,false);assert.equal(retired.stamina,combo.stamina);assert.equal(retired.regenDelay,combo.regenDelay);assert.equal(retired.cancelLockRemaining,comboAttackDuration(combo.attack!)-combo.elapsed);assert.equal(stepCombo(retired,2,snapshot,equipmentCombat(compileCustomEquipment(light))).events.filter(e=>e.type==='hit').length,0);assert.deepEqual(retireComboCommitment(retired),retired);const stunned=cancelCombo(combo,'stun',tuning,.22).state,retiredStun=retireComboCommitment(stunned);assert.equal(retiredStun.phase,'stunned');assert.equal(retiredStun.stunRemaining,stunned.stunRemaining);assert.equal(retiredStun.cancelLockRemaining,stunned.cancelLockRemaining);assert.equal(retiredStun.stamina,stunned.stamina);const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');assert.match(main.slice(main.indexOf('function restoreWorld('),main.indexOf('physics.onmessage')),/combo=retireComboCommitment\(combo\)/);});

function productionFunction(source:string,name:string){
 const start=source.indexOf('function '+name+'(');assert(start>=0,`production function ${name}`);
 for(let end=source.indexOf('\n',start);end>=0;end=source.indexOf('\n',end+1)){
  const text=source.slice(start,end);try{new Function(stripTypeScriptTypes(text));return text;}catch{}
 }
 throw Error('Unterminated production function '+name);
}

test('forbidden lab/online panel navigation leaves the still-visible equipment workbench usable',()=>{const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),handler=productionFunction(main,'openPanel');const source=`let livePractice=null,liveResumeRequested=false;function stopLivePractice(){}function pauseLivePractice(){}let disposed=0;const sessionReloading=false,panelNavigation={blocked:false};const messages=[],cancelLabEntry=()=>{},toast=m=>messages.push(m),coop={active:config.online},coopPending=false,labActive=config.lab;let coopPanelDispose=null,equipmentPanelDispose=()=>disposed++;${handler};openPanel(config.type);return {disposed,messages};`;for(const config of [{online:false,lab:true,type:'journal'},{online:true,lab:false,type:'dev'}]){const result=new Function('config',stripTypeScriptTypes('function body(){const activeConversation=null;function closeConversation(){}const startup={playing:true,initialized:true,failed:false,detail(){},fail(){},cleanup(){},report(){return String();},show(){}};'+source+'}',{mode:'strip'})+';return body();')(config);assert.equal(result.disposed,0);assert.equal(result.messages.length,1);}});
