import {mainFunction} from './helpers/main-source.ts';
import * as guardModel from '../src/guard.ts';
import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three/webgpu';import {readFileSync} from 'node:fs';
import {compileEquipment,seededEquipmentSpec,equipmentRecipe,equipmentRegistry,EQUIPMENT_MANIFEST,equipmentCost,emptyEquipment,validEquipment,canSwapEquipment} from '../src/equipment.ts';
import {compileRecipe,seedSample} from '../src/procedural.ts';import {equipmentCombat} from '../src/equipment-combat.ts';import {compareEquipment} from '../src/equipment-lab.ts';import {createAvatar} from '../src/avatar.ts';import {idleAnimation} from '../src/locomotion.ts';import {createState,createConnectedState,applyAction,serializeSave,parseSave,validateSave,activeObjects,causalContext} from '../src/world.ts';import {createComboState,requestComboAttack,stepCombo,comboEligibleTargets,comboAttackDuration,cancelCombo} from '../src/combat.ts';import {staffSectorPoints} from '../src/combat-view.ts';
const unique=new Map<string,ReturnType<typeof compileEquipment>>();for(let seed=0;seed<128;seed++){const p=compileEquipment(seed);unique.set(JSON.stringify(p.spec),p);}const builds=[...unique.values()];
test('seeded equipment creates eight genuine compatible assemblies, stable across unrelated streams',()=>{assert.equal(builds.length,8);for(const p of builds){seedSample(p.ref.seed,1,'decorations','color','glow');assert.deepEqual(compileEquipment(p.ref.seed),p);assert.ok(p.plan.valid);assert.equal(p.plan.nodes.length,3);assert.equal(p.plan.connections.length,2);assert.equal(p.plan.exposed.length,2);assert.ok(p.plan.operations<=p.recipe.limits.operations);assert.ok(Object.values(p.plan.manifest).every(v=>v===1));}assert.equal(new Set(builds.map(p=>JSON.stringify(p.plan.shapes.map(s=>[s.center,s.half])))).size,8);assert.ok(new Set(builds.map(p=>p.stats.tempo)).size>=4);});
test('typed sockets reject incompatible head, shaft and grip, and finite assembly budgets reject overspend',()=>{for(const spec of [{grip:'linen',shaft:'alloy',head:'maul'},{grip:'braced',shaft:'ironwood',head:'prism'}]){const p=compileRecipe(equipmentRegistry,equipmentRecipe(spec),{seed:1,owner:'equipment/staff'});assert.equal(p.valid,false);assert.throws(()=>compileEquipment(1,spec));}assert.throws(()=>compileEquipment(1,seededEquipmentSpec(1),{scrap:0,core:0}));for(const seed of [-1,1.2,Infinity,0x100000000])assert.throws(()=>compileEquipment(seed));});
test('mass, center of mass, inertia, bounds, costs and attack stats are derived from the same compiled physical shapes',()=>{for(const p of builds){let mass=0,moment=0,inertia=0;for(const n of p.plan.nodes)for(const s of n.shapes){const m=8*s.half.x*s.half.y*s.half.z*Number(n.properties.density);mass+=m;moment+=m*s.center.y;inertia+=m*(s.center.x*s.center.x+s.center.y*s.center.y+(s.half.x**2+s.half.y**2)/3);}assert.equal(p.stats.mass,mass);assert.equal(p.stats.balance,moment/mass);assert.equal(p.stats.inertia,inertia);assert.equal(p.stats.length,p.bounds.maxY-p.bounds.minY);assert.ok(p.stats.mass>.3&&p.stats.mass<6);assert.deepEqual(p.cost,{scrap:p.plan.costs.scrap,core:p.plan.costs.core??0});const t=equipmentCombat(p);for(const [i,a] of t.attacks.entries()){assert.equal(a.range,p.stats.reach-[.45,.3,0][i]!);assert.equal(a.damage,Math.round([24,32,48][i]!*p.stats.damageScale));assert.ok(staffSectorPoints(a).every(v=>Math.abs(Math.hypot(v.x,v.z)-a.range)<1e-10));}}});
function salvaged(connected=false){let s=connected?createConnectedState():createState();for(const o of activeObjects(s))if(o.kind==='scrap'||o.kind==='core'){s=applyAction(s,{type:'move',x:o.x,z:o.z});s=applyAction(s,{type:'collect',id:o.id});}return s;}
test('refitting conserves finite campaign salvage exactly, recycles rather than duplicating stock, and persists recipe identity',()=>{for(const connected of [false,true]){let s=salvaged(connected);const total={...s.inventory},manifest=s.generationManifest,before=causalContext(s);for(const p of [...builds,...builds]){s=applyAction(s,{type:'refit-equipment',seed:p.ref.seed});assert.equal(s.equipment?.active?.recipeHash,p.ref.recipeHash);assert.equal(s.inventory.scrap+equipmentCost(s.equipment).scrap,total.scrap);assert.equal(s.inventory.core+equipmentCost(s.equipment).core,total.core);assert.ok(validateSave(s));assert.deepEqual(parseSave(serializeSave(s)),s);assert.equal(s.generationManifest,manifest);assert.equal(causalContext(s).historicalPumpRepaired,before.historicalPumpRepaired);const same=applyAction(s,{type:'refit-equipment',seed:p.ref.seed});assert.equal(same,s);}s=applyAction(s,{type:'refit-equipment',seed:null});assert.deepEqual(s.inventory,total);assert.ok(validateSave(s));}});
test('legacy saves retain survey staff, pinned world manifest and byte-identical historical fields; invalid gear cannot mint resources',()=>{const old=salvaged();delete old.equipment;const bytes=serializeSave(old),loaded=parseSave(bytes)!;assert.equal(loaded.equipment,undefined);assert.equal(serializeSave(loaded),bytes);assert.deepEqual(equipmentCombat(null).attacks.map(a=>a.range),[2.85,3,3.4]);const fresh=createState();assert.equal(applyAction(fresh,{type:'refit-equipment',seed:0}),fresh);const s=applyAction(salvaged(),{type:'refit-equipment',seed:0});for(const patch of [{manifest:{...EQUIPMENT_MANIFEST,version:2},active:s.equipment!.active},{...s.equipment,active:{...s.equipment!.active,recipeHash:'bad'}},{...s.equipment,active:{...s.equipment!.active,seed:-1}}])assert.equal(validateSave({...s,equipment:patch}),false);assert.equal(validateSave({...s,equipment:emptyEquipment()}),false);assert.equal(validEquipment(emptyEquipment()),true);});
test('generated meshes match compiler shapes and loaded combat hands grip actual sockets',()=>{for(const p of builds){const a=createAvatar();a.setEquipment(p);for(const stage of [1,2,3] as const)for(const phase of ['prep','active','recovery'])for(const progress of [0,.25,.5,.75,1]){a.update({...idleAnimation(),speed:6,lean:.15,turn:.1},null,0,{stage,phase,progress});a.root.updateMatrixWorld(true);const tool=a.root.getObjectByName('surveyStaff')!;for(const shape of p.plan.shapes){const mesh=tool.getObjectByName(shape.id)! as THREE.Mesh;assert.deepEqual(mesh.position.toArray(),[shape.center.x,shape.center.y,shape.center.z]);const box=(mesh.geometry as THREE.BoxGeometry).parameters;assert.deepEqual([box.width,box.height,box.depth],[shape.half.x*2,shape.half.y*2,shape.half.z*2]);}for(const [hand,socket]of [['rightHand','grip-dominant'],['leftHand','grip-support']]){const h=a.root.getObjectByName(hand!)!.getWorldPosition(new THREE.Vector3()),g=tool.getObjectByName(socket!)!.getWorldPosition(new THREE.Vector3());const side=hand==='rightHand'?'right':'left',grip=a.getPoseEvidence().combat?.grips[side];if(grip?.loaded)assert.ok(h.distanceTo(g)<.001,`${p.name} ${stage} ${phase} ${progress} ${hand} ${h.distanceTo(g)}`);if(phase==='active')assert.equal(grip?.loaded,true,'both hands carry the staff during the active beat');}const b=new THREE.Box3().setFromObject(a.root,true);assert.ok(b.min.y>=-.002,`${p.name} strikes floor ${b.min.y}`);assert.ok(b.max.y<=2.16,`${p.name} strikes ceiling ${b.max.y}`);}}});
test('whole generated weapons stay inside standing and low vertical movement envelopes including jump, slide and stance transitions',()=>{for(const p of builds){const a=createAvatar();a.setEquipment(p);for(const crouch of [0,.5,.75,1])for(const airborne of [false,true])for(const slide of [0,1])for(const speed of [0,1.45,4,8])for(const phase of [0,.25,.5,.75]){a.update({...idleAnimation(),speed,phase,crouch,slide,airborne,vertical:6,lean:.28,turn:.13},null,0);a.root.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(a.root,true);assert.ok(b.min.y>=-.002,`${p.name} floor ${b.min.y} ${JSON.stringify({crouch,airborne,slide,speed,phase})}`);assert.ok(b.max.y<=(crouch===1?1.06:2.16),`${p.name} ceiling ${b.max.y} ${JSON.stringify({crouch,airborne,slide,speed,phase})}`);assert.ok(b.max.x-b.min.x<2.1,'bounded full weapon envelope');}}});
test('all generated attack volumes hit exactly once, reject walls/outside range, and latch timing across changes',()=>{for(const p of builds){const tuning=equipmentCombat(p),attack=tuning.attacks[0],snapshot={player:{x:0,y:0,z:0,facing:0,hp:100},targets:[{id:'target',x:0,y:0,z:attack.range}],obstacles:[]};assert.equal(comboEligibleTargets(snapshot,attack).length,1);let s=requestComboAttack(createComboState(tuning),snapshot,tuning).state;assert.equal(canSwapEquipment(s),false);const result=stepCombo(s,10,snapshot,tuning);assert.equal(result.events.filter(e=>e.type==='hit').length,1);assert.equal(canSwapEquipment(result.state),true);assert.equal(comboEligibleTargets({...snapshot,targets:[{id:'far',x:0,z:attack.range+.001}]},attack).length,0);assert.equal(comboEligibleTargets({...snapshot,obstacles:[{x:0,z:1,hx:2,hz:.2}]},attack).length,0);const changed=stepCombo(s,attack.prep/2,snapshot,equipmentCombat(null));assert.equal(changed.state.phase,'prep');assert.equal(changed.state.attack?.recovery,attack.recovery);assert.equal(canSwapEquipment(cancelCombo(s,'dodge',tuning).state),false);assert.equal(canSwapEquipment(cancelCombo(s,'stun',tuning).state),false);assert.ok(comboAttackDuration(attack)>0);}});
test('matched seeded build reports reset every case, preserve full identity/state, and leave campaign bytes untouched',()=>{const campaign=salvaged(true),bytes=serializeSave(campaign);const r=compareEquipment(0,1);assert.equal(r.kind,'deterministic-combat-model');for(const side of [r.a,r.b]){assert.equal(side.runs.length,12);assert.ok(Object.values(side.checks).every(Boolean));assert.equal(side.runs[0]!.stages.join(','),'1,2,3');assert.equal(side.runs[0]!.endState.attackId,3);assert.equal(side.runs[0]!.endState.phase,'idle');assert.ok(side.equipment.recipeHash);}assert.deepEqual(r.a.runs.map(r=>r.conditions),r.b.runs.map(r=>r.conditions));assert.equal(serializeSave(campaign),bytes);assert.deepEqual(compareEquipment(0,1),r);});
test('equipment entry stays in settings/lab, full lab uses baseline, swaps preserve stamina and save-write isolation',()=>{const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');assert.ok(main.includes('id="equipment-settings"'));assert.ok(main.includes('id="lab-equipment"'));assert.ok(main.includes('labRunning?undefined:labEquipment'));assert.ok(main.includes('if(!canSwapEquipment(combo))'));const equip=mainFunction(main,'equipLoadout');assert.ok(equip.indexOf('if(labActive)')<equip.indexOf("applyAction(state,{type:'refit-equipment'"));assert.equal(equip.includes('combo=createComboState'),false);assert.equal((main.match(/data-slot=/g)||[]).length,4);});

import {stripTypeScriptTypes} from 'node:module';
test('actual equip handler forbids mid-action changes and swaps lab loadout without touching campaign state, stamina or saves',()=>{
 const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),handler=mainFunction(main,'equipLoadout');
 const deps={...guardModel,compileEquipment,equipmentFor:(ref:any)=>ref?compileEquipment(ref.seed):null,canSwapEquipment,applyAction};const initial=salvaged(true);
 const source=`let livePractice=null,liveResumeRequested=false;function stopLivePractice(){}function pauseLivePractice(){}const coop={active:false};let state=initial,labActive=false,labRunning=false,labEquipment,transitioning=false,physicsReady=true,guard=createGuardState(),combo={phase:'idle',buffered:false,cancelLockRemaining:0,stunRemaining:0,stamina:37},saves=0,visual=null;const character={setEquipment(p){visual=p}},sync=()=>{},persist=()=>{saves++};function currentEquipment(){return equipmentFor(labActive?labEquipment:state.equipment?.active)}${handler};return {equipLoadout,read(){return {state,labEquipment,combo,saves,visual}},set(k,v){if(k==='lab')labActive=v;if(k==='running')labRunning=v;if(k==='phase')combo.phase=v;if(k==='lock')combo.cancelLockRemaining=v;if(k==='transition')transitioning=v;}};`;
 const h=new Function('initial',...Object.keys(deps),stripTypeScriptTypes('function body(){'+source+'}',{mode:'strip'})+';return body();')(initial,...Object.values(deps));
 h.set('phase','active');h.equipLoadout(0);assert.equal(h.read().state,initial);assert.equal(h.read().saves,0);h.set('phase','idle');h.set('lock',.2);h.equipLoadout(0);assert.equal(h.read().state,initial);h.set('lock',0);h.equipLoadout(0);assert.equal(h.read().saves,1);assert.equal(h.read().combo.stamina,37);const campaign=h.read().state,bytes=serializeSave(campaign);h.set('lab',true);h.equipLoadout(1);assert.equal(h.read().state,campaign);assert.equal(serializeSave(h.read().state),bytes);assert.equal(h.read().labEquipment.seed,1);assert.equal(h.read().visual.ref.seed,1);assert.equal(h.read().saves,1);h.set('lab',false);h.equipLoadout(null);assert.deepEqual(h.read().state.inventory,initial.inventory);assert.equal(h.read().combo.stamina,37);
});

 test('fork prong rotational inertia includes its off-axis parallel-axis term',()=>{const p=compileEquipment(5),prongs=p.plan.nodes.find(n=>n.key==='head')!,onAxis=p.plan.nodes.reduce((sum,n)=>sum+n.shapes.reduce((v,s)=>v+8*s.half.x*s.half.y*s.half.z*Number(n.properties.density)*(s.center.y**2+(s.half.x**2+s.half.y**2)/3),0),0),lateral=prongs.shapes.reduce((sum,s)=>sum+8*s.half.x*s.half.y*s.half.z*Number(prongs.properties.density)*s.center.x**2,0);assert.ok(lateral>0);assert.ok(Math.abs(p.stats.inertia-onAxis-lateral)<1e-12);});
import {createReport,DEFAULT_TUNING} from '../src/dev-lab.ts';import {sanitizeComboTuning} from '../src/combat.ts';
test('starting and interrupting a measured suite retains coherent baseline equipment even with a generated practice loadout selected',()=>{
 const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),between=(a:string,b:string)=>main.slice(main.indexOf(a),main.indexOf(b,main.indexOf(a)));
 const defs=between('function currentEquipment()','function combatObstacles()')+between('function interruptLab(','function downloadJSON(');
 const deps={...guardModel,equipmentFor:(ref:any)=>ref?compileEquipment(ref.seed):null,equipmentCombat,sanitizeComboTuning,createReport,DEFAULT_TUNING,createComboState,requestComboAttack,stepCombo};
 const source=`let livePractice=null,liveResumeRequested=false;function stopLivePractice(){}function pauseLivePractice(){}const visualCapture={cancel(){}};let labCaptureOnly=false;let labActive=true,labRunning=false,labEquipment=gear.ref,transitioning=false,physicsReady=true,labTuning={...DEFAULT_TUNING},labIterations=3,labUnlimitedStamina=false,labInfiniteTargets=false,labReport=null,labCaseIndex=0,labIteration=0,combo=createComboState(),guard=createGuardState(),state={seed:1},backend='test',preset='pixel',reducedMotion=false;const innerWidth=800,innerHeight=600,navigator={maxTouchPoints:0},renderer={getPixelRatio:()=>1},document={getElementById:()=>({value:3})},nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,{textContent:''});return nodes.get(id)};function sendPhysics(){}function closePanel(){}function resetLabCase(){combo=createComboState(combatTuning());} ${defs}return {startLabSuite,interruptLab,currentEquipment,read(){return {labEquipment,labRunning,combo,report:labReport}},attack(){const snapshot={player:{x:0,z:0,facing:0,hp:100},targets:[],obstacles:[]};combo=requestComboAttack(combo,snapshot,combatTuning()).state;combo=stepCombo(combo,.17,snapshot,combatTuning()).state;}};`;
 const h=new Function('gear',...Object.keys(deps),stripTypeScriptTypes('function body(){'+source+'}',{mode:'strip'})+';return body();')(compileEquipment(1),...Object.values(deps));assert.ok(h.currentEquipment());h.startLabSuite();assert.equal(h.read().labEquipment,undefined);h.attack();assert.equal(h.read().combo.phase,'active');const attack=h.read().combo.attack;h.interruptLab('A menu opened');assert.equal(h.currentEquipment(),null);assert.equal(h.read().combo.attack,attack);assert.equal(h.read().report.status,'interrupted');assert.equal(h.read().report.capabilities.equipment.recipeHash,'survey-staff-v12');
});
