import test from 'node:test';import assert from 'node:assert/strict';
import {createState,createConnectedState,applyAction,activeObjects,enableEncounters,serializeSave,parseSave} from '../src/world.ts';
import {storeSession,preEditedEquipmentKey,preEditedEquipmentSave,preUpgradeKey,preUpgradeSave,saveKey,ACTIVE_WORLD_KEY,LEGACY_SAVE_KEY} from '../src/session.ts';
class Store{data=new Map<string,string>();getItem(k:string){return this.data.get(k)??null;}setItem(k:string,v:string){this.data.set(k,v);}}
const recipe={version:2 as const,seed:0,parts:{grip:'linen',shaft:'ash',head:'fork'}};
function salvaged(connected=true,seed=73129){let s=connected?createConnectedState(seed):createState(seed);for(const o of activeObjects(s))if(o.kind==='scrap'||o.kind==='core'){s=applyAction(s,{type:'move',x:o.x,z:o.z});s=applyAction(s,{type:'collect',id:o.id});}return s;}
test('pre-v2 checkpoint preserves exact latest compatible bytes through repeated autosaves and does not replace pre-overnight history',()=>{const store=new Store(),old=salvaged(),oldRaw=JSON.stringify(old,null,3)+'\n';store.setItem(saveKey(old),oldRaw);const first=enableEncounters(old);storeSession(store,first,true);assert.equal(preUpgradeSave(store,old),oldRaw);const last=applyAction(first,{type:'refit-equipment',seed:5}),lastRaw=JSON.stringify(last,null,1)+'\n\n';store.setItem(saveKey(last),lastRaw);assert.equal(preEditedEquipmentSave(store,last),null);let custom=applyAction(last,{type:'assemble-equipment',recipe});assert.equal(custom.equipment!.active!.version,2);storeSession(store,custom,true);assert.equal(preEditedEquipmentSave(store,custom),lastRaw);assert.equal(preUpgradeSave(store,custom),oldRaw);for(let i=0;i<12;i++){custom=applyAction(custom,{type:'tick',dt:.25});storeSession(store,custom,true);}assert.equal(preEditedEquipmentSave(store,custom),lastRaw);assert.equal(preUpgradeSave(store,custom),oldRaw);assert.notEqual(store.getItem(saveKey(custom)),lastRaw);assert.equal(parseSave(preEditedEquipmentSave(store,custom)!)!.equipment!.active!.version,1);const survey=applyAction(custom,{type:'refit-equipment',seed:null});storeSession(store,survey,true);storeSession(store,applyAction(survey,{type:'assemble-equipment',recipe}),true);assert.equal(preEditedEquipmentSave(store,custom),lastRaw);});
test('new v2 worlds never fabricate an older save; incompatible or other-world candidates never become a rollback',()=>{for(const invalid of [null,'{bad',serializeSave(salvaged(true,5)),serializeSave(applyAction(salvaged(),{type:'assemble-equipment',recipe}))]){const store=new Store(),custom=applyAction(salvaged(),{type:'assemble-equipment',recipe});if(invalid)store.setItem(saveKey(custom)+'-backup',invalid);storeSession(store,custom,true);assert.equal(preEditedEquipmentSave(store,custom),null);assert.equal(store.getItem(preEditedEquipmentKey(custom)),null);assert.equal(parseSave(store.getItem(saveKey(custom))!)!.equipment!.active!.version,2);}});
test('pre-v2 checkpoint quota failure aborts before active, rolling or pre-overnight slots can be overwritten',()=>{const store=new Store(),old=salvaged(),raw=JSON.stringify(old,null,2)+'\n';store.setItem(saveKey(old),raw);store.setItem(saveKey(old)+'-backup',raw);store.setItem(ACTIVE_WORLD_KEY,saveKey(old));const before=new Map(store.data),custom=applyAction(enableEncounters(old),{type:'assemble-equipment',recipe});const blocked={getItem:(k:string)=>store.getItem(k),setItem(k:string,v:string){if(k===preEditedEquipmentKey(old))throw Error('Quota exceeded');store.setItem(k,v);}};assert.throws(()=>storeSession(blocked,custom,true),/Quota/);assert.deepEqual(store.data,before);assert.equal(store.getItem(preUpgradeKey(old)),null);});
test('primary-slot quota failure still retains both old slot and successful immutable pre-v2 checkpoint',()=>{const store=new Store(),old=salvaged(),raw=serializeSave(old);storeSession(store,old,true);const custom=applyAction(old,{type:'assemble-equipment',recipe});const blocked={getItem:(k:string)=>store.getItem(k),setItem(k:string,v:string){if(k===saveKey(old))throw Error('Quota exceeded');store.setItem(k,v);}};assert.throws(()=>storeSession(blocked,custom,true),/Quota/);assert.equal(store.getItem(saveKey(old)),raw);assert.equal(preEditedEquipmentSave(store,old),raw);assert.equal(store.getItem(ACTIVE_WORLD_KEY),saveKey(old));});
test('valid fallback backup and original legacy aliases retain same-world exact bytes without being consumed',()=>{for(const target of ['backup','legacy','legacy-backup'] as const){const store=new Store(),old=salvaged(false),raw=JSON.stringify(old,null,2)+'\n',key=target==='backup'?saveKey(old)+'-backup':target==='legacy'?LEGACY_SAVE_KEY:'axiom-save-backup-v1';store.setItem(key,raw);store.setItem(saveKey(old),'{broken');storeSession(store,applyAction(old,{type:'assemble-equipment',recipe}));assert.equal(preEditedEquipmentSave(store,old),raw);if(target!=='backup')assert.equal(store.getItem(key),raw);}});
test('an occupied malformed checkpoint is never overwritten or falsely exported and prevents losing a compatible current slot',()=>{for(const raw of ['{bad',serializeSave(salvaged(true,7)),serializeSave(applyAction(salvaged(),{type:'assemble-equipment',recipe}))]){const store=new Store(),old=salvaged();storeSession(store,old);store.setItem(preEditedEquipmentKey(old),raw);const before=new Map(store.data);assert.equal(preEditedEquipmentSave(store,old),null);assert.throws(()=>storeSession(store,applyAction(old,{type:'assemble-equipment',recipe})),/checkpoint is invalid/);assert.deepEqual(store.data,before);}});

test('actual Settings rollback export handlers preserve raw bytes and handle unavailable checkpoints',async()=>{
 const {readFileSync}=await import('node:fs'),{stripTypeScriptTypes}=await import('node:module');const source=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');
 const download=source.slice(source.indexOf('function downloadSaveText('),source.indexOf('function updateLabVisuals('));
 for(const [id,reader,filename] of [['export-pre-equipment','preEditedEquipmentSave','axiom-pre-edited-equipment-rollback.json'],['export-preupgrade','preUpgradeSave','axiom-pre-upgrade-rollback.json'],['export-pre-barter','preCommonsTradeSave','axiom-pre-barter-rollback.json'],['export-pre-requests','preWaterRequestsSave','axiom-pre-recurring-request-rollback.json']]){
  const marker=`$('${id}').onclick=`,start=source.indexOf(marker),end=source.indexOf(";$('",start);assert.ok(start>=0&&end>start);const handler=source.slice(start,end+1),button:{onclick?:()=>void}={},blobs:Blob[]=[],links:{href:string;download:string;click:()=>void}[]=[],messages:string[]=[],raw=' {"schema":6,"precise":1.00}\n\n';let available:string|null=raw,throws=false;
  const fn=new Function('$',reader,'localStorage','state','toast','Blob','URL','document','setTimeout',stripTypeScriptTypes(download+handler));
  fn(()=>button,()=>{if(throws)throw Error('unavailable');return available;},{},{},(s:string)=>messages.push(s),Blob,{createObjectURL:(b:Blob)=>{blobs.push(b);return 'blob:test';},revokeObjectURL:()=>{}},{createElement:()=>{const a={href:'',download:'',click:()=>{}};links.push(a);return a;}},()=>{});
  button.onclick!();assert.equal(await blobs[0]!.text(),raw);assert.equal(links[0]!.download,filename);available=null;button.onclick!();assert.equal(blobs.length,1);assert.match(messages.at(-1)!,/No .*save exists/);throws=true;button.onclick!();assert.equal(blobs.length,1);assert.match(messages.at(-1)!,/storage is unavailable/);
 }
});
