import {createPanelNavigation} from '../src/panel-navigation.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
import {mountRegionWorkbench} from '../src/region-workbench.ts';import {mountWorkbench} from '../src/workbench.ts';import {disposeGeneration} from '../src/generation.ts';import {nodeGenerationWorker} from './helpers/generation-node-worker.ts';import {emptyWaterworks} from '../src/waterworks.ts';
const source=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),line=(prefix:string)=>{const start=source.indexOf(prefix);assert(start>=0);return source.slice(start,source.indexOf('\n',start));};

function productionFunction(source:string,name:string){
 const start=source.indexOf('function '+name+'(');assert(start>=0,`production function ${name}`);
 for(let end=source.indexOf('\n',start);end>=0;end=source.indexOf('\n',end+1)){
  const text=source.slice(start,end);try{new Function(stripTypeScriptTypes(text));return text;}catch{}
 }
 throw Error('Unterminated production function '+name);
}

class Element {hidden=true;dataset:Record<string,string>={};value='';textContent='';className='';children:Element[]=[];nodes=new Map<string,Element>();draws=0;onclick?:()=>void;onsubmit?:(e:{preventDefault:()=>void})=>void;focus(){};classList={add(){},remove(){}};
 set innerHTML(html:string){this.nodes.clear();for(const m of html.matchAll(/<(\w+)([^>]*?\bid="([^"]+)"[^>]*)>/g)){const n=new Element();if(m[3]==='region-kind')n.value='valley';if(m[3]==='workbench-recipe')n.value='workshop';this.nodes.set('#'+m[3],n);}this.nodes.set('.close',new Element());}
 querySelector(key:string){return this.nodes.get(key)??null;}replaceChildren(...nodes:Element[]){this.children=nodes;}getContext(){return new Proxy({},{get:()=>()=>this.draws++,set:()=>true});}}
async function waitFor(check:()=>boolean){const deadline=performance.now()+4000;while(!check()){assert(performance.now()<deadline,'Worker-backed preview did not complete');await new Promise(r=>setTimeout(r,5));}}
test('actual main preview navigation owns real Worker cancellation, page lifecycle remount and forbidden-destination safety',async t=>{
 const priorWorker=globalThis.Worker,priorDocument=globalThis.document,priorHTMLElement=globalThis.HTMLElement;let workers=0;globalThis.Worker=class{constructor(){workers++;return nodeGenerationWorker();}} as unknown as typeof Worker;const panel=new Element(),settings=new Element(),listeners=new Map<string,()=>void>(),document={activeElement:null,documentElement:{classList:{add(){},remove(){}}},createElement:()=>new Element(),getElementById:(id:string)=>id==='settings'?settings:panel.querySelector('#'+id)};globalThis.document=document as unknown as Document;globalThis.HTMLElement=Element as unknown as typeof HTMLElement;
 t.after(()=>{disposeGeneration();globalThis.Worker=priorWorker;globalThis.document=priorDocument;globalThis.HTMLElement=priorHTMLElement;});
 const lifecycle=[line("addEventListener('pagehide',()=>{generationStartupController"),line("addEventListener('pageshow',()=>{if(panel.hidden)")].join('\n');
 const body=`let sessionReloading=false,mapPanelDispose=null,generationPanelDispose=null,equipmentPanelDispose=null,coopPanelDispose=null,panelReturnFocus=null,labActive=false,labRunning=false,coopPending=false;const coop={active:false},generationStartupController=new AbortController(),messages=[],cancelLabEntry=()=>{},clearInput=()=>{},toast=s=>messages.push(s),interruptLab=()=>{};const history={state:null,pushState(value){this.state=value},replaceState(value){this.state=value},back(){this.state=null;panelNavigation.popped()}};const panelNavigation=createPanelNavigation(history,()=>closePanel(false));${productionFunction(source,'closePanel')}${productionFunction(source,'openPanel')}${lifecycle};return {open:openPanel,close:closePanel,get handle(){return generationPanelDispose},setOnline(v){coop.active=v},setLab(v){labActive=v},messages};`;
 const api=new Function('createPanelNavigation','panel','state','mountRegionWorkbench','mountWorkbench','disposeGeneration','document','HTMLElement','$','addEventListener',stripTypeScriptTypes('function run(){const activeConversation=null;function closeConversation(){}const startup={playing:true,failed:false,detail(){},fail(){},cleanup(){}};'+body+'}')+';return run();')(createPanelNavigation,panel,{seed:73129,waterworks:emptyWaterworks()},mountRegionWorkbench,mountWorkbench,disposeGeneration,document,Element,(id:string)=>document.getElementById(id),(event:string,fn:()=>void)=>listeners.set(event,fn));
 api.open('region-plan');const detached=panel.querySelector('#region-map')!;assert(api.handle);api.open('workbench');await waitFor(()=>panel.querySelector('#workbench-status')!.textContent.includes('worker compilation'));assert.equal(detached.draws,0,'canceled region completion cannot repaint detached canvas');assert(panel.querySelector('#workbench-plan')!.draws>0);
 const handle=api.handle;api.setOnline(true);api.open('dev');assert.equal(api.handle,handle);assert.equal(panel.dataset.type,'workbench');assert.equal(api.messages.length,1);api.setOnline(false);api.setLab(true);api.open('journal');assert.equal(api.handle,handle);api.setLab(false);
 const before=workers;listeners.get('pagehide')!();assert.equal(api.handle,null);listeners.get('pageshow')!();assert(api.handle);await waitFor(()=>panel.querySelector('#workbench-status')!.textContent.includes('worker compilation'));assert(workers>before,'BFCache-style return constructs a fresh owned preview Worker');api.close();assert.equal(api.handle,null);assert.equal(panel.hidden,true);const closedWorkers=workers;listeners.get('pageshow')!();await new Promise(r=>setTimeout(r,10));assert.equal(workers,closedWorkers);
});
test('actual startup boundary awaits only bounded preparation and retains the ordinary source-of-truth loaders afterward',()=>{const warming=source.indexOf('const generationStartup=await warmGenerationStartup('),create=source.indexOf('let state=createRegionalState(73129)'),load=source.indexOf('state=loadSession(localStorage)'),coop=source.indexOf('coopBoot=readCoopBoot(sessionStorage)');assert(warming>0&&warming<create&&create<load&&load<coop);assert.match(source.slice(warming,create),/budgetMs:1500/);assert.match(source,/generationPreparation:structuredClone\(generationStartup\)/);assert.match(source,/generationBootSummary\(generationStartup\)/);});
test('regional streaming survives persisted pagehide instead of being permanently disposed on BFCache pause',()=>{assert.match(source,/pagehide',\(event:PageTransitionEvent\)=>\{if\(!event\.persisted\)\{regionalStreamer\?\.dispose\(\)/);});
