import test from 'node:test';import assert from 'node:assert/strict';
import {mountRegionWorkbench} from '../src/region-workbench.ts';import {mountWorkbench} from '../src/workbench.ts';import {emptyWaterworks} from '../src/waterworks.ts';import {compileGeneration} from '../src/generation-compile.ts';import type {GenerationResult} from '../src/generation-client.ts';import type {GenerationInput} from '../src/generation-protocol.ts';
/** Actual production DOM handlers, with a tiny non-rendering DOM. No browser/pixel evidence. */
class Node {value='';textContent='';className='';children:Node[]=[];nodes=new Map<string,Node>();draws:any[][]=[];html='';onclick?:()=>void;oninput?:()=>void;onchange?:()=>void;onsubmit?:(e:{preventDefault:()=>void})=>void;
 set innerHTML(html:string){this.html=html;this.nodes.clear();for(const m of html.matchAll(/<(\w+)([^>]*?\bid="([^"]+)"[^>]*)>/g)){const n=new Node();if(m[3]==='region-kind')n.value='valley';if(m[3]==='workbench-recipe')n.value='workshop';this.nodes.set('#'+m[3],n);}this.nodes.set('.close',new Node());}
 querySelector(key:string){return this.nodes.get(key)??null;}replaceChildren(...nodes:Node[]){this.children=nodes;}
 getContext(){return new Proxy({},{get:(_t,key)=>(...args:unknown[])=>this.draws.push([key,...args]),set:()=>true});}
}
const pause=()=>new Promise(r=>setTimeout(r,0));
function harness(kind:'region'|'workbench'){
 (globalThis as any).document={createElement:()=>new Node()};const panel=new Node(),jobs:{input:GenerationInput;signal?:AbortSignal;resolve:(r:GenerationResult)=>void;reject:(e:Error)=>void}[]=[];let closed=0;
 const generate=(input:GenerationInput,signal?:AbortSignal)=>new Promise<GenerationResult>((resolve,reject)=>jobs.push({input,...(signal?{signal}:{}),resolve,reject}));
 const mount=()=>kind==='region'?mountRegionWorkbench(panel as any,73129,()=>closed++,generate):mountWorkbench(panel as any,emptyWaterworks(),73129,()=>closed++,generate);
 const dispose=mount(),get=(id:string)=>{const n=panel.querySelector('#'+id);assert.ok(n,id);return n;};
 return {panel,jobs,mount,dispose,get,get closed(){return closed;},edit(value:string){get(kind==='region'?'region-seed':'workbench-seed').value=value;get(kind==='region'?'region-seed':'workbench-seed').oninput?.();},submit(){get(kind==='region'?'region-preview':'workbench-form').onsubmit!({preventDefault(){}});},complete(index:number,backend:'worker'|'synchronous'='worker'){const job=jobs[index]!;job.resolve({plan:compileGeneration(job.input),backend,fallback:backend==='synchronous'?'timeout':null,timings:{totalMs:1,compileMs:1,validationMs:0,bootMs:0}});}};
}
for(const kind of ['region','workbench'] as const){
 const status=kind==='region'?'region-status':'workbench-status',canvas=kind==='region'?'region-map':'workbench-plan';
 test(`${kind} real preview handlers use compiled output, report fallback, and reject invalid input`,async()=>{const h=harness(kind);assert.equal(h.jobs.length,1);h.complete(0);await pause();assert.match(h.get(status).textContent,/VALID.*worker compilation/);assert.ok(h.get(canvas).draws.length>10);for(const seed of ['', '-1','1.5','4294967296']){h.edit(seed);h.submit();assert.match(h.get(status).textContent,/whole seed/);}assert.equal(h.jobs.length,1);h.edit('0001');h.submit();h.complete(1,'synchronous');await pause();assert.match(h.get(status).textContent,/synchronous fallback \(timeout\)/);assert.equal(h.jobs[1]!.input.seed,1);h.dispose();});
 test(`${kind} late seed/view/close/remount completions never repaint stale panels`,async()=>{const h=harness(kind),oldCanvas=h.get(canvas);h.edit('2');assert.ok(h.jobs[0]!.signal?.aborted);h.submit();h.complete(0);await pause();assert.equal(oldCanvas.draws.length,0);h.complete(1);await pause();const count=oldCanvas.draws.length;assert.ok(count>0);
  h.edit('3');h.submit();h.panel.querySelector('.close')!.onclick!();assert.equal(h.closed,1);assert.ok(h.jobs[2]!.signal?.aborted);h.complete(2);await pause();assert.equal(oldCanvas.draws.length,count);
  const dispose=h.mount();h.complete(3);await pause();h.edit('4');h.submit();const detached=h.get(canvas);const detachedCount=detached.draws.length;h.panel.innerHTML='<p>Replacement</p>';h.complete(4);await pause();assert.equal(detached.draws.length,detachedCount);dispose();
 });
 test(`${kind} changing domain cancels in-flight work and disposed handlers cannot start more`,async()=>{const h=harness(kind);const select=h.get(kind==='region'?'region-kind':'workbench-recipe');select.value=kind==='region'?'dungeon':'waterworks';select.onchange!();assert.ok(h.jobs[0]!.signal?.aborted);if(kind==='region'){assert.equal(h.jobs.length,2);h.complete(1);}h.complete(0);await pause();if(kind==='region')assert.match(h.get(status).textContent,/VAULT GRAPH/);else assert.match(h.get(status).textContent,/VALID PLAN/);const count=h.jobs.length;h.dispose();h.submit();select.onchange!();assert.equal(h.jobs.length,count);});
}
test('the production regional handler reaches the real owned Node Worker and draws its completed plan',async t=>{
 const {nodeGenerationWorker}=await import('./helpers/generation-node-worker.ts');const {disposeGeneration}=await import('../src/generation.ts');const prior=(globalThis as any).Worker;(globalThis as any).Worker=class{constructor(){return nodeGenerationWorker();}};(globalThis as any).document={createElement:()=>new Node()};const panel=new Node();const dispose=mountRegionWorkbench(panel as any,4294967295,()=>{});t.after(()=>{dispose();disposeGeneration();if(prior===undefined)delete (globalThis as any).Worker;else (globalThis as any).Worker=prior;});
 const deadline=performance.now()+3000;while(!panel.querySelector('#region-status')!.textContent.includes('worker compilation')){assert.ok(performance.now()<deadline,panel.querySelector('#region-status')!.textContent);await new Promise(r=>setTimeout(r,5));}assert.ok(panel.querySelector('#region-map')!.draws.length>6561);assert.match(panel.querySelector('#region-summary')!.textContent,/4 compiled workshops/);
});
