import {mainFunction,restorationInitialState} from './helpers/main-source.ts';
import * as contactModel from '../src/player-contact.ts';
import test from 'node:test';
import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import {Worker} from 'node:worker_threads';
const base=new URL('../',import.meta.url).pathname;const THREE=await import(base+'node_modules/three/build/three.webgpu.js'),combat=await import(base+'src/combat.ts'),lab=await import(base+'src/dev-lab.ts'),tuning=await import(base+'src/tuning.ts'),motion=await import(base+'src/locomotion.ts'),gear=await import(base+'src/equipment.ts'),gearCombat=await import(base+'src/equipment-combat.ts'),world=await import(base+'src/world.ts'),guards=await import(base+'src/guard.ts'),guardView=await import(base+'src/guard-view.ts'),guardResolution=await import(base+'src/guard-resolution.ts');
const main=readFileSync(base+'src/main.ts','utf8');const between=(a,b)=>main.slice(main.indexOf(a),main.indexOf(b,main.indexOf(a)));
async function run(batch){
 const w=new Worker(`const {parentPort}=require('node:worker_threads');globalThis.self=globalThis;self.postMessage=m=>parentPort.postMessage(m);globalThis.setInterval=f=>{globalThis.tick=f};parentPort.on('message',async m=>{if(m.type==='advance'){for(let i=0;i<m.n;i++)tick();parentPort.postMessage({type:'done'});}else await self.onmessage({data:m})});import(${JSON.stringify('file://'+base+'src/physics.worker.ts')}).then(()=>parentPort.postMessage({type:'boot'}))`,{eval:true,execArgv:['--experimental-strip-types']});
 let error;const q=[];const worker={postMessage:m=>w.postMessage(m),onmessage:null};w.on('error',e=>error=e);w.on('message',m=>{q.push(m);if(m.type==='error')error=new Error(m.message);try{worker.onmessage?.({data:m})}catch(e){error=e}});const take=async type=>{const end=Date.now()+5000;while(!q.some(m=>m.type===type)){if(error)throw error;assert.ok(Date.now()<end,type+' timed out');await new Promise(r=>setTimeout(r,1))}return q.splice(q.findIndex(m=>m.type===type),1)[0]};
 const source=`${restorationInitialState(main)}let townView=null;${mainFunction(main,'acceptTownLifeSnapshot')}let contactRequestId=null,playerContact=emptyPlayerContact(),movableBodies=[];function contactBusy(){return false;}function contactEnabled(){return false;}let livePractice=null,liveResumeRequested=false;function stopLivePractice(){}function pauseLivePractice(){}let state=createConnectedState(73129),labActive=true,labRunning=true,labEntering=false,labAutoCombo=false,labUnlimitedStamina=false,labInfiniteTargets=false,labTuning={...DEFAULT_TUNING},labWarmup=60,labTicks=0,lastLabStep=-1,labCaseIndex=0,labIteration=1,labIterations=3,labFrames=[],labMetrics=null,labReport=createReport(state.seed,labTuning,3,{source:'independent production-handler harness'}),labTargets=[],physicsReady=false,transitioning=true,zoneEpoch=0,lastPhysicsStep=-1,pendingLabRestore=null,labCaptureToken=0,windowActive=true,machineSignature='',reducedMotion=false,inputMode='desktop',mobileAutoPulse=false,crouch=false,jump=false,heldCrouch=false,heldJump=false;const document={hidden:false},panel={hidden:true},nodes=new Map();const $=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',style:{}});return nodes.get(id)};let animation=idleAnimation(),physicsMotion={vx:0,vz:0,vy:0,landing:0,grounded:true,crouched:false,stance:0,sliding:false},avatarAction=null,actionAge=0,actionDuration=.55,orbit=.5,zoom=23,pulseTime=0;const targetPosition=new THREE.Vector3(-12,0,-13),player={position:targetPosition.clone()},cameraTarget=targetPosition.clone(),character={update(){}},pulse={visible:false,position:{set(){}},scale:{setScalar(){}},material:{opacity:0}};const keys=new Set(),stick={value:{x:0,z:0}};
 const coop={active:false,canAct:true,setSuspended(){}},coopPending=false;let coopCancelAttack=-1,coopJumpHeld=false;const scene={add(){}};const gameAudio={cue(){}},visualCapture={cancel(){},arm(){}};let labCaptureOnly=false;function resetLabTargets(){}function sync(){}function toast(){}function resolvePhysics(){}function rejectPhysics(e){throw e}function updateBackend(){}function syncMachine(){}function streamWorld(){}function openPanel(){panel.hidden=false}function clearInput(){sendPhysics({type:'input',x:0,z:0,paused:true})}function persist(){throw Error('unexpected campaign save')}function beginLab(){throw Error('unexpected capture')}function restoreWorld(){throw Error('unexpected campaign restore')}function machineWorldObstacles(){return []}const pendingCells=new Map();function confirmCell(){return false}function initialCellPacket(){return {initialCells:[]}}const objects=[],obstacles=[],streamer={active:new Map()},cellObstacles=new Map(),dungeon={walls:[]};
 ${between('function sendPhysics(', 'function showZone()')}
 ${between('function sendMovement()', 'function clearInput()')}
 ${between('let combo=createComboState()', 'function updateContextControls()')}
 ${between('function resetLabCase()', 'function exitLab()')}
 ${between('function labInput()', 'function interruptLab(')}
 ${between('function interruptLab(', 'function startLabSuite(')}
 ${between('worker.onmessage=(e)=>', 'worker.onerror=')}
 ${main.slice(main.indexOf('function guardContext()'))}
 return {getReport:()=>structuredClone(labReport),getStatus:()=>({labRunning,labCaseIndex,labTicks,labWarmup,zoneEpoch}),init(){sendPhysics({type:'init',...LAB_CASES[0].spawn,obstacles:LAB_OBSTACLES,bound:18,sandbox:true})}};`;
 const deps={...contactModel,THREE,worker,...combat,...lab,...tuning,...motion,...gear,...gearCombat,...world,...guards,...guardView,...guardResolution};let api;try{api=new Function(...Object.keys(deps),stripTypeScriptTypes('function body(){const activeConversation=null;function closeConversation(){}const startup={playing:true,failed:false,detail(){},fail(){},cleanup(){}};'+source+'}',{mode:'strip'})+';return body();')(...Object.values(deps));
 await take('boot');api.init();await take('ready');for(let step=0;api.getStatus().labRunning&&step<20000;step+=batch){worker.postMessage({type:'advance',n:batch});await take('done');if(error)throw error;}const report=api.getReport();assert.equal(report.status,'completed',JSON.stringify(api.getStatus()));assert.equal(report.runs.length,27);assert.deepEqual(report.runs.flatMap(r=>r.checks.filter(x=>!x.pass)),[]);assert.equal(report.runs.reduce((n,r)=>n+r.metrics.samples,0),4950);assert.ok(Object.values(report.manual).every(v=>v==='not-reviewed'));assert.ok(report.runs.every(r=>r.frames.sampleCount===0));return report.runs.map(({metrics,...r})=>({caseId:r.caseId,iteration:r.iteration,metrics}));}finally{await w.terminate()}
}
test('production lab orchestration repeats all 27 case-runs identically with immediate and batched worker delivery',{timeout:30000},async()=>{const a=await run(1),b=await run(40);assert.deepEqual(a,b);});
