import test from 'node:test';import assert from 'node:assert/strict';
import {createConversationOverlay,conversationPage} from '../src/npc-conversation-ui.ts';
class Element {
 tagName:string;className='';id='';textContent='';hidden=false;tabIndex=0;type='';disabled=false;children:Element[]=[];parent:Element|null=null;dataset:Record<string,string>={};style:Record<string,string>={};attributes:Record<string,string>={};onclick?: (e:{detail:number})=>void;
 constructor(tag='div'){this.tagName=tag.toUpperCase();}get classList(){return {add:(_c:string)=>{},remove:(_c:string)=>{}};}
 append(...children:Element[]){for(const child of children){child.parent=this;this.children.push(child);}}
 replaceChildren(...children:Element[]){for(const child of this.children)child.parent=null;this.children=[];this.append(...children);}
 setAttribute(k:string,v:string){this.attributes[k]=v;}getAttribute(k:string){return this.attributes[k]??null;}
 matches(s:string){if(s.startsWith('.'))return this.className.split(' ').includes(s.slice(1));if(s==='button:not(:disabled)')return this.tagName==='BUTTON'&&!this.disabled;return this.tagName===s.toUpperCase();}
 querySelectorAll(s:string):Element[]{return this.children.flatMap(c=>[...(c.matches(s)?[c]:[]),...c.querySelectorAll(s)]);}querySelector(s:string){return this.querySelectorAll(s)[0]??null;}
 contains(e:Element|null):boolean{return e===this||this.children.some(c=>c.contains(e));}focus(){(globalThis.document as any).activeElement=this;}click(){this.onclick?.({detail:0});}remove(){if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);this.parent=null;}
}
function harness(fn:(host:Element)=>void){const d=globalThis.document,p=globalThis.performance;let now=1000;const doc={activeElement:null,documentElement:new Element(),createElement:(tag:string)=>new Element(tag)};Object.defineProperty(globalThis,'document',{value:doc,configurable:true});Object.defineProperty(globalThis,'performance',{value:{now:()=>now+=1000},configurable:true});try{fn(new Element());}finally{Object.defineProperty(globalThis,'document',{value:d,configurable:true});Object.defineProperty(globalThis,'performance',{value:p,configurable:true});}}
const view=(topic:string|null=null)=>({name:'Ada Reed',role:'gardener',subtitle:'Thoughtful · 1 Orchard Row',line:'I have been tending the seed bed.',topic,canBack:!!topic,choices:Array.from({length:8},(_,i)=>({id:`${topic??'topic'}:${i}`,text:`What would you say about idea ${i}?`,kind:'topic'}))});
const key=(code:string,shiftKey=false)=>({code,shiftKey,repeat:false,ctrlKey:false,metaKey:false,altKey:false,preventDefault(){}} as KeyboardEvent);
test('conversation reply pages are bounded and never lose any available topic',()=>{const choices=Array.from({length:8},(_,i)=>i);assert.deepEqual(conversationPage(choices,0).choices,[0,1,2,3]);assert.deepEqual(conversationPage(choices,1).choices,[4,5,6,7]);for(const page of [-10,Infinity,NaN])assert.equal(conversationPage(choices,page).page,0);assert.equal(conversationPage(choices,99).page,1);assert.equal(conversationPage([],2).pages,1);});
test('transparent conversation surface selects full utterances, changes pages and resets page on a new subject',()=>harness(host=>{const selected:string[]=[];let backs=0;const ui=createConversationOverlay(host as any,{choose:id=>selected.push(id),back:()=>backs++,close(){}});ui.show(view());const root=ui.root as unknown as Element;assert.equal(root.hidden,false);assert.equal(root.attributes['aria-modal'],'true');assert.equal(root.querySelectorAll('.conversation-choice').length,4);ui.keydown(key('ArrowRight'));ui.keydown(key('Digit1'));assert.deepEqual(selected,['topic:4']);ui.show(view('home'));ui.keydown(key('Digit1'));assert.deepEqual(selected,['topic:4','home:0']);assert(root.querySelector('.conversation-player-line')?.textContent.includes('idea 4'));root.querySelectorAll('.conversation-nav')[0]!.click();assert.equal(backs,1);ui.position(300,120,true);assert.equal(host.querySelector('.conversation-speaker-marker')!.style.left,'300px');ui.hide();assert(root.hidden);assert(host.querySelector('.conversation-speaker-marker')!.hidden);ui.dispose();assert.equal(host.children.length,0);}));
test('conversation keyboard traps focus and movement, hands menu navigation its history, and rejects stale clicks',()=>harness(host=>{const close:(boolean|undefined)[]=[],selected:string[]=[];const ui=createConversationOverlay(host as any,{choose:id=>selected.push(id),back(){},close:keep=>close.push(keep)});ui.show(view());const root=ui.root as unknown as Element,old=root.querySelector('.conversation-choice')!;ui.keydown(key('Tab',true));assert.equal((document as any).activeElement,root.querySelectorAll('button:not(:disabled)')[0]);for(const code of ['KeyW','KeyA','KeyC','KeyF','KeyE','KeyG','Space'])assert(ui.keydown(key(code)));ui.show({...view(),line:'A new line.'});old.click();assert.equal(selected.length,0);assert.equal(ui.keydown(key('KeyM')),false);assert.equal(close.at(-1),true);ui.keydown(key('Escape'));assert.equal(close.at(-1),undefined);ui.hide();assert.equal(ui.keydown(key('Digit1')),false);}));
