import test from 'node:test';
import assert from 'node:assert/strict';
import {createRegionalTrade,enableRegionalTrade,advanceRegionalTrade,applyRegionalTradeCommand,regionalTradeCommandPosition,regionalTradePlan,regionalTradeSummary,regionalTradeActorPoses,regionalTradeConservation,regionalTradeDrainTicks,regionalTradeCanonical,regionalTradeReplayTimeline,validRegionalTrade,immutableRegionalTrade,REGIONAL_TRADE_MAX_TICKS,type RegionalTradeState,type RegionalTradeCommand} from '../src/regional-trade.ts';
import {regionalTradeRoadWeather,regionalTradeWeatherMetres,regionalTradeWeatherArrival} from '../src/regional-trade-weather.ts';
import {regionalWeatherAt,REGIONAL_WEATHER_PERIOD_TICKS} from '../src/regional-weather.ts';
const seed=73129,identity={generation:2 as const,seed,regional:{version:1 as const}},clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
function command(state:RegionalTradeState,type:RegionalTradeCommand['type'],i=0){const p=regionalTradePlan(state.seed),targetId=type==='start-source'?p.sources[i]!.id:type==='clear-route'?p.routes[i]!.id:p.projects[i]!.id,c={type,targetId,expectedRevision:state.revision},at=regionalTradeCommandPosition(state.seed,c)!;return applyRegionalTradeCommand(state,{...identity,seed:state.seed,zone:'valley',player:{x:at.x,z:at.z,hp:100},feetY:at.y,grounded:true},c).state;}
function run(state:RegionalTradeState,seconds:number,dt=.25){for(let i=0;i<Math.round(seconds/dt);i++)state=advanceRegionalTrade(state,dt);return state;}
function until(state:RegionalTradeState,condition:(state:RegionalTradeState)=>boolean,limit=16000){for(let i=0;i<limit;i++){if(condition(state))return state;state=advanceRegionalTrade(state,1);}assert.fail('Bounded freight scenario did not complete');}
function verify(state:RegionalTradeState){assert(validRegionalTrade(clone(state),{...identity,seed:state.seed}));assert(regionalTradeConservation(state).every(r=>r.balanced));return state;}
test('fresh freight uses explicit v2 without relabeling existing v1 histories',()=>{
 assert.equal(createRegionalTrade(seed).version,2);const old={...identity,frontierTrade:createRegionalTrade(seed,1)};assert.equal(enableRegionalTrade(old),old);assert.equal(enableRegionalTrade(old,2),old);assert.equal((enableRegionalTrade(identity) as typeof old).frontierTrade.version,2);assert.equal((enableRegionalTrade(identity,1) as typeof old).frontierTrade.version,1);assert.throws(()=>createRegionalTrade(seed,3 as 1));
 for(const version of [1,2] as const){let state=run(command(command(createRegionalTrade(seed,version),'start-source'),'clear-route'),60);verify(state);const bad=clone(state);bad.version=version===1?2:1;assert.equal(validRegionalTrade(bad,identity),false);assert.equal(advanceRegionalTrade(bad,.25),bad);}
});
test('shared seed weather drives bounded wetness, 30-second drying and exact corridor integrals',()=>{
 const signatures=new Set<string>();for(const seed of [0,1,42,991,73129,4294967295]){const p=regionalTradePlan(seed);for(const route of p.routes){let micro=0;const samples:number[]=[];for(let tick=0;tick<10000;tick++){const road=regionalTradeRoadWeather(seed,route,tick);assert(road.speed>=.9&&road.speed<=1.8);assert(road.nextChangeTick>tick);assert(road.wetness>=0&&road.wetness<=1);micro+=Math.round(road.speed*.25*1e6);if(tick%100===0)samples.push(road.speed);const rain=regionalWeatherAt(seed,road.exposure.x,road.exposure.z,tick);if(rain.intensity>0){assert.equal(road.condition,'wet');assert.equal(road.wetness,rain.intensity/2);}else if(rain.drySeconds>=120){assert.equal(road.condition,'dry');assert.equal(road.speed,1.8);}}
 assert.equal(regionalTradeWeatherMetres(seed,route,0,10000),micro/1e6);assert.equal(regionalTradeWeatherMetres(seed,route,0,1_000_000_000),micro*100000/1e6);for(const [a,b,c]of [[0,743,11000],[9910,10000,10500],[999_900_000,999_987_654,1_000_000_000]])assert.equal(Math.round(regionalTradeWeatherMetres(seed,route,a!,c!)*1e6),Math.round(regionalTradeWeatherMetres(seed,route,a!,b!)*1e6)+Math.round(regionalTradeWeatherMetres(seed,route,b!,c!)*1e6));signatures.add(samples.join(','));}}
 assert(signatures.size>3);
});
test('weather arrival is the first sufficient integer tick through front and season boundaries',()=>{
 for(const seed of [1,73129,4294967295])for(const route of regionalTradePlan(seed).routes)for(const start of [0,747,8849,9999,999_980_000])for(const metres of [.1,1,route.obstruction.distance,route.surfaceMetres,7000]){const end=regionalTradeWeatherArrival(seed,route,start,metres);assert(end>start);assert(regionalTradeWeatherMetres(seed,route,start,end)>=metres-1e-7);assert(end===start+1||regionalTradeWeatherMetres(seed,route,start,end-1)<metres-1e-7);}
});
test('rain slows real loaded movement and dry recovery restores actual speed without cargo changes',()=>{
 const base=command(command(createRegionalTrade(seed),'start-source'),'clear-route'),legacy=run(command(command(createRegionalTrade(seed,1),'start-source'),'clear-route'),60);let wet=run(base,60);assert(wet.routes[0]!.distance<legacy.routes[0]!.distance);assert.equal(wet.routes[0]!.cargo,4);const route=regionalTradePlan(seed).routes[0]!;
 for(const seconds of [60,200,230,260,300]){const state=run(base,seconds),before=state.routes[0]!,summary=regionalTradeSummary(state,seed,route.id)!;assert.equal(before.activity,'outbound');const after=advanceRegionalTrade(state,.25).routes[0]!;assert(Math.abs((after.distance-before.distance)/.25-summary.travelSpeed)<1e-6);assert.equal(regionalTradeActorPoses(seed,state).find(a=>a.id===route.carrierId)!.speed,summary.travelSpeed);assert.equal(after.cargo,4);assert.equal(after.delivered,0);}
 const dry=regionalTradeSummary(run(base,310),seed,route.id)!;assert.equal(dry.travelCondition,'dry');assert.equal(dry.travelSpeed,1.8);verify(wet);
});
test('forecast ETA predicts real unload delivery across drying; blocked cargo never promises arrival',()=>{
 let state=run(command(createRegionalTrade(seed),'start-source'),60);assert.equal(regionalTradeSummary(state,seed,state.routes[0]!.id)!.etaKind,'repair-required');assert.equal(regionalTradeSummary(state,seed,state.routes[0]!.id)!.etaSeconds,null);state=command(state,'clear-route');state=run(state,12);state=advanceRegionalTrade(state,.1);const s=regionalTradeSummary(state,seed,state.routes[0]!.id)!;assert.equal(s.etaKind,'arrival');const arrival=state.ticks*.25+state.remainder+s.etaSeconds!;assert.equal(arrival,(state.routes[0]!.nextEventAt!+12)*.25);
 while(state.routes[0]!.delivered===0){const old=state;state=advanceRegionalTrade(state,.25);if(state.routes[0]!.delivered){assert.equal(state.ticks*.25,arrival);assert.equal(old.routes[0]!.delivered,0);}}assert.equal(state.routes[0]!.delivered,4);assert.equal(state.routes[0]!.shipments,1);verify(state);
});
test('same seed split steps and reloads are identical mid-rain, drying, outbound, blocked and return',()=>{
 for(const version of [1,2] as const){const base=command(command(createRegionalTrade(seed,version),'start-source'),'clear-route');for(const seconds of [60,200,230,310,550,1000]){const coarse=run(base,seconds,1);assert.deepEqual(coarse,run(base,seconds,.25));assert.deepEqual(coarse,run(base,seconds,.1));const restored=immutableRegionalTrade(clone(coarse),identity);assert.deepEqual(run(restored,27,1),run(base,seconds+27,1));verify(restored);}}
});
test('every freight route remains finite with monotone legs and exactly three deliveries',()=>{
 let state=createRegionalTrade(seed);for(let i=0;i<3;i++){state=command(state,'start-source',i);state=command(state,'clear-route',i);}let ticks=0;while(!state.routes.every(r=>r.activity==='finished')&&ticks<65000){for(let i=0;i<3;i++)if(state.routes[i]!.destinationStock>=4&&state.routes[i]!.buildStartedAt===null)state=command(state,'build-store',i);const old=state;state=advanceRegionalTrade(state,.25);ticks++;for(let i=0;i<3;i++){const a=old.routes[i]!,b=state.routes[i]!;assert(b.distance>=0&&b.distance<=regionalTradePlan(seed).routes[i]!.surfaceMetres);assert(Math.abs(b.distance-a.distance)<=.45+1e-6);if(a.activity===b.activity&&a.activity==='outbound')assert(b.distance>=a.distance);if(a.activity===b.activity&&a.activity==='returning')assert(b.distance<=a.distance);assert(b.delivered-a.delivered===0||b.delivered-a.delivered===4);assert(b.shipments<=3);}if(ticks%5000===0)verify(state);}
 assert(state.routes.every(r=>r.activity==='finished'));assert.equal(state.routes.reduce((sum,r)=>sum+r.delivered,0),36);for(let i=0;i<3;i++){assert.equal(state.routes[i]!.embodied,4);assert.equal(state.routes[i]!.destinationStock,8);state=command(state,'withdraw-reserve',i);const after=command(state,'withdraw-reserve',i);assert.equal(after,state);}verify(state);assert.equal(state.routes.reduce((sum,r)=>sum+r.withdrawn,0),24);
});
test('weather-aware quiescent-gap rebase preserves weather phase and pending movement',()=>{
 let early=run(command(command(createRegionalTrade(seed),'start-source'),'clear-route'),80);const late=clone(early),shift=Math.floor((REGIONAL_TRADE_MAX_TICKS-late.ticks)/REGIONAL_WEATHER_PERIOD_TICKS)*REGIONAL_WEATHER_PERIOD_TICKS;late.ticks+=shift;for(const receipt of late.receipts)receipt.tick+=shift;for(const r of late.routes)if(r.sourceStartedAt!==null)for(const key of ['sourceStartedAt','productionNextAt','activityStartedAt','nextEventAt','repairStartedAt','clearedAt','buildStartedAt','builtAt'] as const)if(r[key]!==null)r[key]!+=shift;
 verify(late);let rebased=regionalTradeCanonical(late)!;assert.equal(rebased.ticks%10000,late.ticks%10000);assert(rebased.ticks<=16*(regionalTradeDrainTicks(seed,2)+10000));assert.equal(rebased.routes[0]!.distance,late.routes[0]!.distance);for(let i=0;i<700;i++){early=advanceRegionalTrade(early,.25);rebased=advanceRegionalTrade(rebased,.25);assert.equal(rebased.routes[0]!.distance,early.routes[0]!.distance);assert.equal(rebased.routes[0]!.activity,early.routes[0]!.activity);assert.deepEqual(regionalTradeConservation(rebased),regionalTradeConservation(early));}verify(rebased);
 const blocked=until(command(createRegionalTrade(seed),'start-source'),s=>s.routes[0]!.activity==='blocked'),huge=clone(blocked);huge.ticks=REGIONAL_TRADE_MAX_TICKS;verify(huge);const resumed=command(immutableRegionalTrade(huge,identity),'clear-route');assert.equal(resumed.ticks%10000,huge.ticks%10000);assert.equal(resumed.routes[0]!.distance,huge.routes[0]!.distance);verify(until(resumed,s=>s.routes[0]!.delivered===4));
});
test('billion-tick cold replay integrates finite v2 events without per-tick or seasonal loops',async t=>{
 let state=command(command(createRegionalTrade(seed),'start-source'),'clear-route');const start=performance.now();const replay=regionalTradeReplayTimeline(state,[],{ticks:REGIONAL_TRADE_MAX_TICKS,remainder:0})!;verify(replay);assert.equal(replay.routes[0]!.delivered,4);assert.equal(replay.routes[0]!.activity,'idle');assert(performance.now()-start<1000);t.diagnostic(`Billion-tick v2 reconstruction ${ (performance.now()-start).toFixed(2)} ms`);
});
