import test from 'node:test';
import assert from 'node:assert/strict';
import {createRegionalTrade,advanceRegionalTrade,applyRegionalTradeCommand,regionalTradeCommandPosition,regionalTradePlan,regionalTradeDrainTicks,regionalTradeReplayTimeline,regionalTradeCanonical,validRegionalTrade,REGIONAL_TRADE_MAX_TICKS,type RegionalTradeState,type RegionalTradeCommand,type RegionalTradeTimelineEvent,type RegionalTradeTimelinePoint} from '../src/regional-trade.ts';
import {regionalClockAdvance} from '../src/regional-clock.ts';
const seed=42,identity={generation:2,seed,regional:{version:1 as const}},clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
function act(state:RegionalTradeState,type:RegionalTradeCommand['type'],targetId:string){const command={type,targetId,expectedRevision:state.revision},p=regionalTradeCommandPosition(seed,command)!;return applyRegionalTradeCommand(state,{...identity,zone:'valley',player:{x:p.x,z:p.z,hp:100},feetY:p.y,grounded:true},command).state;}
function same(actual:RegionalTradeState|undefined,expected:RegionalTradeState,label=''){assert(actual,label);assert.equal(actual.ticks,expected.ticks,label+' ticks');assert(Math.abs(actual.remainder-expected.remainder)<=1e-12,label+' phase');assert.deepEqual(actual.routes,expected.routes,label+' goods/work');assert.deepEqual(actual.receipts,expected.receipts,label+' receipts');assert.equal(actual.revision,expected.revision);assert(validRegionalTrade(clone(actual),identity));}
function tickPoint(p:RegionalTradeTimelinePoint,dt:number){return regionalClockAdvance(p,dt);}

test('split freight witnesses replay real commands and construction only at their accepted post-baseline time',()=>{
 const plan=regionalTradePlan(seed),base=advanceRegionalTrade(createRegionalTrade(seed),.13);let state=base,point={ticks:0,remainder:0};const events:RegionalTradeTimelineEvent[]=[];
 const command=(type:RegionalTradeCommand['type'],targetId:string)=>{const next=act(state,type,targetId);assert.notEqual(next,state);state=next;events.push({type:'command',...point,command:{type,targetId}});same(regionalTradeReplayTimeline(base,events,point),state,type);};
 command('start-source',plan.sources[0]!.id);command('clear-route',plan.routes[0]!.id);for(let i=0;i<4000&&state.routes[0]!.destinationStock<4;i++){state=advanceRegionalTrade(state,.25);point=tickPoint(point,.25);}assert.equal(state.routes[0]!.destinationStock,4);command('build-store',plan.projects[0]!.id);const started={...point};assert.equal(regionalTradeReplayTimeline(base,events,started)!.routes[0]!.builtAt,null);
 for(let i=0;i<63;i++){state=advanceRegionalTrade(state,.25);point=tickPoint(point,.25);}assert.equal(state.routes[0]!.builtAt,null);same(regionalTradeReplayTimeline(base,events,point),state);state=advanceRegionalTrade(state,.25);point=tickPoint(point,.25);assert.notEqual(state.routes[0]!.builtAt,null);same(regionalTradeReplayTimeline(base,events,point),state);
 const impossible=events.map(e=>e.type==='command'&&e.command.type==='build-store'?{...e,ticks:0,remainder:0}:e);assert.equal(regionalTradeReplayTimeline(base,impossible,point),undefined);assert(Object.isFrozen(regionalTradeReplayTimeline(base,events,point)));assert.equal(JSON.stringify(base),JSON.stringify(advanceRegionalTrade(createRegionalTrade(seed),.13)));
});
test('repeated near-quarter fractions keep exact whole ticks and small phase error for differing legacy remainder baselines',()=>{
 let frames=0;for(const baseline of [0,.13,.2499999995])for(const dt of [.2500000005,.25000000005,.2499999995,.2499999999,1/60]){const base=advanceRegionalTrade(createRegionalTrade(seed),baseline);let state=base,point={ticks:0,remainder:0};for(let i=0;i<2401;i++){state=advanceRegionalTrade(state,dt);point=tickPoint(point,dt);if(i%100===0||i===2400)same(regionalTradeReplayTimeline(base,[],point),state,`baseline ${baseline} dt ${dt} frame ${i}`);frames++;}}console.log(JSON.stringify({regionalTradeTimelineRepeatedFractions:1,frames,baselines:3,dtPatterns:5,maximumComparedPhaseError:1e-12}));
});
test('only explicit eligible freight rebases translate time and preserve pending finite work',()=>{
 const plan=regionalTradePlan(seed),event:RegionalTradeTimelineEvent={type:'command',ticks:0,remainder:0,command:{type:'start-source',targetId:plan.sources[0]!.id}},base=regionalTradeReplayTimeline(createRegionalTrade(seed),[event],{ticks:REGIONAL_TRADE_MAX_TICKS,remainder:0})!;assert(base);assert(validRegionalTrade(clone(base),identity));const rebased=advanceRegionalTrade(base,.125),events:RegionalTradeTimelineEvent[]=[{type:'rebase',ticks:0,remainder:0}];same(regionalTradeReplayTimeline(base,events,{ticks:0,remainder:.125}),rebased);assert.equal(regionalTradeReplayTimeline(base,[],{ticks:0,remainder:.125}),undefined);
 const command=act(base,'clear-route',plan.routes[0]!.id);same(regionalTradeReplayTimeline(base,[...events,{type:'command',ticks:0,remainder:0,command:{type:'clear-route',targetId:plan.routes[0]!.id}}],{ticks:0,remainder:0}),command);assert.equal(regionalTradeReplayTimeline(createRegionalTrade(seed),events,{ticks:0,remainder:0}),undefined);
 const eligible={...clone(createRegionalTrade(seed)),ticks:REGIONAL_TRADE_MAX_TICKS-regionalTradeDrainTicks(seed)};assert(validRegionalTrade(eligible,identity));assert(regionalTradeReplayTimeline(eligible,events,{ticks:0,remainder:0}));assert.equal(regionalTradeReplayTimeline(eligible,[...events,...events],{ticks:0,remainder:0}),undefined,'a spare witness budget cannot create an ineligible second rebase');
});
test('timeline rejects malformed, future, reordered, illegal and accessor witnesses without certifying supplied data',()=>{
 const base=createRegionalTrade(seed),id=regionalTradePlan(seed).sources[0]!.id,event:RegionalTradeTimelineEvent={type:'command',ticks:0,remainder:0,command:{type:'start-source',targetId:id}},end={ticks:0,remainder:0};
 for(const events of [[{...event,ticks:1}],[{...event,remainder:.25}],[{...event,remainder:-1}],[{...event,extra:1}],[{...event,command:{...event.command,cargo:4}}],[event,event],[{type:'rebase',ticks:0,remainder:0}],[{...event,command:{type:'build-store',targetId:id}}],Array(19).fill(event)])assert.equal(regionalTradeReplayTimeline(base,events as RegionalTradeTimelineEvent[],end),undefined);
 for(const invalid of [{ticks:-1,remainder:0},{ticks:1.5,remainder:0},{ticks:0,remainder:.25},{ticks:0,remainder:NaN},{ticks:1_000_000_001,remainder:0},{...end,extra:true}])assert.equal(regionalTradeReplayTimeline(base,[],invalid),undefined);
 let read=0;const accessor=clone(event);Object.defineProperty(accessor,'type',{get(){read++;return 'command';},enumerable:true});assert.equal(regionalTradeReplayTimeline(base,[accessor],end),undefined);assert.equal(read,0);assert.equal(regionalTradeReplayTimeline({...clone(base),routes:[]} as RegionalTradeState,[],end),undefined);
});

test('read-only canonical freight compression preserves finite goods and rejects malformed input',()=>{
 const initial=createRegionalTrade(seed),id=regionalTradePlan(seed).sources[0]!.id,base=regionalTradeReplayTimeline(initial,[{type:'command',ticks:0,remainder:0,command:{type:'start-source',targetId:id}}],{ticks:REGIONAL_TRADE_MAX_TICKS,remainder:0})!,before=JSON.stringify(base),canonical=regionalTradeCanonical(base),expected=regionalTradeReplayTimeline(base,[{type:'rebase',ticks:0,remainder:0}],{ticks:0,remainder:0});assert(canonical);assert.deepEqual(canonical,expected);assert.equal(JSON.stringify(base),before);assert.deepEqual(Object.keys(canonical),Object.keys(base));assert(Object.isFrozen(canonical));assert(Object.isFrozen(canonical.routes));assert.deepEqual(regionalTradeCanonical(canonical),canonical);assert.equal(regionalTradeCanonical({...clone(base),routes:[]}),undefined);let read=0;const accessor=clone(base);Object.defineProperty(accessor,'seed',{get(){read++;return seed;},enumerable:true});assert.equal(regionalTradeCanonical(accessor),undefined);assert.equal(read,0);
});
