import test from 'node:test';
import assert from 'node:assert/strict';
import {applyAction,createRegionalState,enableRegionalSupply,enableRegionalTrade,enableRegionalFood,validateSave,serializeSave,parseSave,type State} from '../src/world.ts';
import {createRegionalTrade,regionalTradePlan,regionalTradeCommandPosition,regionalTradeReplayTimeline,regionalTradeDrainTicks,REGIONAL_TRADE_MAX_TICKS,type RegionalTradeCommand} from '../src/regional-trade.ts';
import {regionalFoodPlan} from '../src/regional-food.ts';
import {createVertical} from '../server/coop-vertical.ts';
import {worldHeight} from '../src/generation.ts';
import {CoopClient} from '../src/coop.ts';
import {foodHttpFixture,foodExpedition,foodInput,foodCurrent,type FoodFixture,type FoodPeer} from './helpers/regional-food-http.ts';
import {foodCommand} from './helpers/regional-food-campaign.ts';
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
function tradeCommand(state:State,type:RegionalTradeCommand['type']='start-source'){const p=regionalTradePlan(state.seed),targetId=(type==='start-source'?p.sources:type==='clear-route'?p.routes:p.projects)[0]!.id;return {type:'regional-trade' as const,command:{type,targetId,expectedRevision:state.frontierTrade!.revision}};}
function atTrade(state:State,type:RegionalTradeCommand['type']='start-source'){const p=regionalTradeCommandPosition(state.seed,tradeCommand(state,type).command)!;return {...state,player:{...state.player,x:p.x,z:p.z}};}
const fresh=()=>atTrade(enableRegionalFood(enableRegionalTrade(enableRegionalSupply(createRegionalState(42)),1)));
const valid=(state:State)=>{assert(validateSave(state));assert.deepEqual(parseSave(serializeSave(state)),state);};
async function relocate(f:FoodFixture,p:FoodPeer,position:{x:number;z:number}){const room=f.stored(p.s.roomId),member=room.players.find(q=>q.userId===p.user)!;member.player={...member.player,...position};member.motion=createVertical(worldHeight({...room.world,player:member.player},position.x,position.z));delete member.wildernessCollisionVersion;if(member.id===room.hostId)room.world={...room.world,player:{...member.player}};f.replace(room);await foodCurrent(f,p);}
function beforeStoreBuild(){let s=fresh();for(const type of ['start-source','clear-route'] as const){s=atTrade(s,type);s=applyAction(s,tradeCommand(s,type));}for(let i=0;i<3000&&s.frontierTrade!.routes[0]!.destinationStock<4;i++)s=applyAction(s,{type:'tick',dt:1});assert.equal(s.frontierTrade!.routes[0]!.destinationStock,4);s=atTrade(s,'build-store');valid(s);return s;}

test('four HTTP trade commands atomically witness exactly one accepted action without advancing food or changing food goods',async()=>{
 const f=await foodHttpFixture();try{const peers=await foodExpedition(f,fresh()),host=peers[0]!,before=clone(host.s.world.frontierFood!),command=tradeCommand(host.s.world),expected=applyAction(host.s.world,command),hold=f.hold(),pending=foodInput(f,peers[1]!,[command]);assert.notEqual(expected.frontierTrade,host.s.world.frontierTrade);await hold.waiting;try{await foodInput(f,host,[command]);}finally{hold.release();}await pending;await Promise.all(peers.slice(2).map(p=>foodInput(f,p,[command])));await Promise.all(peers.map(p=>foodCurrent(f,p)));
 assert(f.conflicts()>0);for(const p of peers){const food=p.s.world.frontierFood!;assert.deepEqual(food,expected.frontierFood);assert.equal(food.tradeEvents.length,1);assert.equal(food.tradeEvents[0]!.type,'command');assert.deepEqual(food.tradeSnapshot,p.s.world.frontierTrade);assert.deepEqual(food.tradeBaseline,before.tradeBaseline);assert.equal(food.ticks,before.ticks);assert.equal(food.remainder,before.remainder);assert.equal(food.revision,before.revision);assert.deepEqual(food.farms,before.farms);valid(p.s.world);}
 const committed=clone(host.s.world.frontierFood);await foodInput(f,host,[command]);const replay=await f.raw(host.user,`/rooms/${host.s.roomId}/sync`,{seq:host.s.ack,sessionId:host.s.sessionId,actions:[command]});assert.equal(replay.status,200);assert.deepEqual(replay.body.world.frontierFood,committed);
 }finally{await f.stop();}
});
test('lost HTTP trade response replays one temporal witness and one freight commitment',async()=>{
 const f=await foodHttpFixture();let client:CoopClient|undefined;try{const sent:string[]=[];let lost=false;const fetcher:typeof fetch=async(url,init)=>{const response=await fetch(url,{...init,headers:{...init?.headers,'oai-authenticated-user-id':'host',Origin:f.origin}});if(String(url).endsWith('/sync')&&JSON.parse(String(init?.body)).actions.some((a:{type:string})=>a.type==='regional-trade')){sent.push(String(init?.body));if(!lost&&response.ok){lost=true;throw Error('Response lost after atomic witness commit');}}return response;};client=new CoopClient({baseURL:f.origin,fetch:fetcher,onSnapshot:()=>{}});await client.create({name:'Host',world:fresh()});const before=clone(client.snapshot!.world.frontierFood),expected=applyAction(client.snapshot!.world,tradeCommand(client.snapshot!.world));assert(client.send(tradeCommand(client.snapshot!.world)));const limit=Date.now()+5000;while(client.snapshot!.world.frontierTrade!.revision!==1&&Date.now()<limit)await new Promise(r=>setTimeout(r,10));assert(lost);assert.equal(sent.length,2);assert.equal(sent[0],sent[1]);assert.deepEqual(client.snapshot!.world.frontierFood,expected.frontierFood);assert.equal(client.snapshot!.world.frontierFood!.tradeEvents.length,1);assert.deepEqual(client.snapshot!.world.frontierFood!.farms,before!.farms);valid(f.stored(client.snapshot!.roomId).world);
 }finally{client?.disconnect();await f.stop();}
});
test('post-rollout store construction becomes food-eligible only after real active work; forged backdated trade witnesses cannot import',async()=>{
 const f=await foodHttpFixture();try{const world=beforeStoreBuild(),peers=await foodExpedition(f,world),host=peers[0]!,command=tradeCommand(host.s.world,'build-store'),before=clone(host.s.world.frontierFood!);await Promise.all(peers.map(p=>foodInput(f,p,[command])));await foodCurrent(f,host);assert.equal(host.s.world.frontierFood!.tradeEvents.length,before.tradeEvents.length+1);assert.deepEqual(host.s.world.frontierFood!.farms,before.farms);assert.equal(host.s.world.frontierTrade!.routes[0]!.builtAt,null);
 const farm=regionalFoodPlan(world.seed).farms[0]!;await relocate(f,host,farm.interactionPosition);await foodInput(f,host,[foodCommand(host.s.world)]);assert.equal(host.s.world.frontierFood!.revision,0);for(let i=0;i<15;i++){f.advance(1000);await foodInput(f,host);}assert.equal(host.s.world.frontierTrade!.routes[0]!.builtAt,null);await foodInput(f,host,[foodCommand(host.s.world)]);assert.equal(host.s.world.frontierFood!.revision,0);f.advance(1000);await foodInput(f,host);assert.notEqual(host.s.world.frontierTrade!.routes[0]!.builtAt,null);await foodInput(f,host,[foodCommand(host.s.world)]);assert.equal(host.s.world.frontierFood!.revision,1);assert.equal(host.s.world.frontierFood!.farms[0]!.starterGranted,4);valid(host.s.world);
 const bad=clone(host.s.world),build=bad.frontierFood!.tradeEvents.find(e=>e.type==='command'&&e.command.type==='build-store')!;build.ticks=0;build.remainder=0;assert.equal(validateSave(bad),false);assert.equal(parseSave(JSON.stringify(bad)),null);assert.equal((await f.raw('bad-import','/rooms',{name:'Backdated',world:bad})).status,400);
 const backdated=clone(host.s.world);backdated.frontierFood!.receipts[0]!.tick=0;backdated.frontierFood!.farms[0]!.startedAt=0;assert.equal(validateSave(backdated),false);assert.equal((await f.raw('bad-import','/rooms',{name:'Future proof',world:backdated})).status,400);
 }finally{await f.stop();}
});
test('a legacy near-cap trade baseline can rebase on an accepted tick or command without losing temporal authority',async()=>{
 for(const mode of ['tick','command'] as const){const raw=createRegionalState(42),plan=regionalTradePlan(42),base=regionalTradeReplayTimeline(createRegionalTrade(42,1),[{type:'command',ticks:0,remainder:0,command:{type:'start-source',targetId:plan.sources[0]!.id}}],{ticks:REGIONAL_TRADE_MAX_TICKS,remainder:0})!;assert(base);const state=atTrade(enableRegionalFood(enableRegionalSupply({...raw,frontierTrade:base})),'clear-route'),f=await foodHttpFixture();try{const peers=await foodExpedition(f,state),host=peers[0]!,initial=clone(host.s.world.frontierFood!);if(mode==='tick'){f.advance(1000);await Promise.all(peers.map(p=>foodInput(f,p)));}else await Promise.all(peers.map(p=>foodInput(f,p,[tradeCommand(p.s.world,'clear-route')])));await foodCurrent(f,host);const food=host.s.world.frontierFood!;assert.equal(food.tradeEvents.filter(e=>e.type==='rebase').length,1);assert.equal(food.tradeEvents.filter(e=>e.type==='command').length,mode==='command'?1:0);assert.deepEqual(food.tradeSnapshot,host.s.world.frontierTrade);assert.deepEqual(food.tradeBaseline,initial.tradeBaseline);assert(host.s.world.frontierTrade!.ticks<REGIONAL_TRADE_MAX_TICKS);valid(host.s.world);
 }finally{await f.stop();}}
});

test('a controlled incompatible coupled tick rolls back the complete valid world instead of saving stale food dependencies',()=>{
 const original=fresh(),before=serializeSave(original);let reads=0;
 // Deliberately adversarial local test input gives different dt values to the
 // independent model steps. Real network clients cannot submit tick actions.
 const inconsistent={type:'tick' as const,get dt(){return ++reads%2?.25:.5;}};
 const result=applyAction(original,inconsistent);assert(reads>3);assert.equal(result,original);assert.equal(serializeSave(result),before);valid(result);
});

test('terminal food stays frozen and saveable while ordinary authoritative freight commands and active ticks continue',async()=>{
 let state=enableRegionalTrade(enableRegionalSupply(createRegionalState(42)),1),supply=clone(state.frontierSupply!);supply.ticks=REGIONAL_TRADE_MAX_TICKS;for(const o of supply.outposts)for(const r of o.residents){r.thirst=100;r.thirstOverflow=60+supply.ticks*.03-100;}state=parseSave(JSON.stringify({...state,frontierSupply:supply}))!;assert(state);state=enableRegionalFood(state);const food=clone(state.frontierFood!);food.ticks=REGIONAL_TRADE_MAX_TICKS;for(const f of food.farms)for(const resident of [f.farmer,f.carrier]){resident.hunger=100;resident.hungerOverflow=Math.floor(food.ticks/12)-40;}food.tradeEvents=[{type:'rebase',ticks:REGIONAL_TRADE_MAX_TICKS-regionalTradeDrainTicks(42),remainder:0}];food.tradeSnapshot=regionalTradeReplayTimeline(food.tradeBaseline,food.tradeEvents,{ticks:food.ticks,remainder:0})!;assert(food.tradeSnapshot);state=parseSave(JSON.stringify({...state,frontierTrade:food.tradeSnapshot,frontierFood:food}))!;assert(state);state=atTrade(state);valid(state);
 const before=clone(state.frontierFood),f=await foodHttpFixture();try{const [host]=await foodExpedition(f,state,1);assert(host);await foodInput(f,host,[tradeCommand(host.s.world)]);assert.equal(host.s.world.frontierTrade!.revision,1);assert.deepEqual(host.s.world.frontierFood,before);f.advance(1000);await foodInput(f,host);assert.deepEqual(host.s.world.frontierFood,before);assert(host.s.world.frontierTrade!.ticks>food.tradeSnapshot.ticks);valid(host.s.world);const resumed=await f.raw(host.user,`/rooms/${host.s.roomId}/resume`,{});assert.equal(resumed.status,200);assert.deepEqual(resumed.body.world.frontierFood,before);
 }finally{await f.stop();}
});
