import test from 'node:test';
import assert from 'node:assert/strict';
import {action} from '../server/coop-validation.ts';
import {createRoom,syncRoom,type CoopRoom} from '../server/coop-authority.ts';
import {createVertical} from '../server/coop-vertical.ts';
import {applyAction,createState,createConnectedState,enableRegionalFood,validateSave,serializeSave,parseSave,type State} from '../src/world.ts';
import {worldHeight} from '../src/generation.ts';
import {regionalFoodPlan,regionalFoodCommandPosition} from '../src/regional-food.ts';
import {CoopClient} from '../src/coop.ts';
import type {CoopAction} from '../src/coop-protocol.ts';
import {foodHttpFixture,foodExpedition,foodInput,foodCurrent} from './helpers/regional-food-http.ts';
import {oldFoodCampaign,readyFoodCampaign,foodCommand,atFoodCommand} from './helpers/regional-food-campaign.ts';
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
const valid=(state:State)=>{assert(validateSave(state));assert.deepEqual(parseSave(serializeSave(state)),state);};
function tending(){let state=readyFoodCampaign();state=applyAction(state,foodCommand(state));for(let i=0;i<1800;i++){const c=foodCommand(state,'tend-crop'),next=applyAction(state,c);if(next!==state)return state;state=applyAction(state,{type:'tick',dt:.25});}throw Error('No useful tending job appeared');}

test('food HTTP command allowlist rejects ownership, stock, meal, reward, water and clock injection',{timeout:120_000},async()=>{
 const state=readyFoodCampaign(),c=foodCommand(state);assert(action(c));
 const invalid=[null,{},[],...[-1,.5,NaN,Infinity,'0',undefined].map(expectedRevision=>({...c.command,expectedRevision})),{...c.command,type:'eat'},{...c.command,targetId:''},{...c.command,targetId:'bad\n'},{...c.command,targetId:'x'.repeat(181)},...['stock','cargo','meals','water','reward','ticks','playerId','userId','storeProof','position','frontierFood'].map(key=>({...c.command,[key]:100}))];
 const f=await foodHttpFixture();try{const [host]=await foodExpedition(f,state,1);assert(host);const before=f.stored(host.s.roomId);for(const command of invalid){assert.equal(action({type:'regional-food',command}),null);const r=await f.raw(host.user,`/rooms/${host.s.roomId}/sync`,{seq:1,sessionId:host.s.sessionId,actions:[{type:'regional-food',command}]});assert.equal(r.status,400);}
 for(const extra of [{world:state},{userId:'host'},{playerId:host.s.selfId}])assert.equal((await f.raw(host.user,`/rooms/${host.s.roomId}/sync`,{seq:1,sessionId:host.s.sessionId,actions:[c],...extra})).status,400);
 assert.equal((await f.raw('outsider',`/rooms/${host.s.roomId}`)).status,404);assert.equal((await f.raw('',`/rooms/${host.s.roomId}`)).status,401);assert.equal((await f.raw(host.user,`/rooms/${host.s.roomId}/sync`,{seq:1,sessionId:host.s.sessionId,actions:[c]},{Origin:'https://evil.invalid'})).status,403);assert.deepEqual(f.stored(host.s.roomId),before);
 }finally{await f.stop();}
});
for(const type of ['start-farm','tend-crop'] as const)test(`four real HTTP actors race one ${type} through SQLite CAS and replay cannot duplicate farm goods or stewardship`,{timeout:120_000},async()=>{
 const f=await foodHttpFixture();try{const source=type==='start-farm'?readyFoodCampaign():tending(),peers=await foodExpedition(f,source),host=peers[0]!,c=foodCommand(host.s.world,type),expected=applyAction(host.s.world,c),hold=f.hold();assert.notEqual(expected.frontierFood,host.s.world.frontierFood);
 const pending=foodInput(f,peers[1]!,[c]);await hold.waiting;try{await foodInput(f,host,[c]);}finally{hold.release();}await pending;await Promise.all(peers.slice(2).map(p=>foodInput(f,p,[c])));await Promise.all(peers.map(p=>foodCurrent(f,p)));assert(f.conflicts()>0);
 for(const p of peers){assert.deepEqual(p.s.world.frontierFood,expected.frontierFood);assert.deepEqual(p.s.world.frontierSupply,source.frontierSupply);assert.deepEqual(p.s.world.frontierTrade,source.frontierTrade);assert.deepEqual(p.s.world.wilderness,source.wilderness);assert.deepEqual(p.s.world.inventory,source.inventory);valid(p.s.world);}
 const before=clone(host.s.world.frontierFood);await foodInput(f,host,[c]);await foodInput(f,host,[foodCommand(host.s.world,type)]);assert.deepEqual(host.s.world.frontierFood,before);const replay=await f.raw(host.user,`/rooms/${host.s.roomId}/sync`,{seq:host.s.ack,sessionId:host.s.sessionId,actions:[c]});assert.equal(replay.status,200);assert.deepEqual(replay.body.world.frontierFood,before);valid(f.stored(host.s.roomId).world);
 }finally{await f.stop();}
});
test('food commands use accepted grounded physical reach and reject forged client pose, remote actor, guard and attack commitments',{timeout:120_000},()=>{
 for(const condition of ['jump','crouch','high','attack','guard','remote'] as const){const source=readyFoodCampaign(),room=createRoom('host','Host',source,1000),p=room.players[0]!,before=clone(room.world.frontierFood);if(condition==='high')p.motion!.feetY+=10;if(condition==='remote'){p.player={...p.player,x:p.player.x+20};p.motion=createVertical(worldHeight(source,p.player.x,p.player.z));}
 const actions:CoopAction[]=[...(condition==='jump'?[{type:'jump-press' as const,intentId:'food-air'}]:condition==='attack'?[{type:'attack-press' as const}]:condition==='guard'?[{type:'guard-press' as const,intentId:'food-guard'}]:[]),foodCommand(room.world)];
 syncRoom(room,'host',{seq:1,sessionId:p.sessionId,actions,move:{x:source.player.x,z:source.player.z,y:worldHeight(source,source.player.x,source.player.z),grounded:true,crouched:condition==='crouch',facing:0}},1000);assert.deepEqual(room.world.frontierFood,before,condition);valid(room.world);}
});
test('distant food work uses each platform member accepted position and latest revision instead of a caller supplied identity',{timeout:120_000},async()=>{
 const f=await foodHttpFixture();try{const source=readyFoodCampaign(),peers=await foodExpedition(f,source),room=f.stored(peers[0]!.s.roomId);for(let i=0;i<3;i++){const p=room.players[i]!,position=regionalFoodPlan(source.seed).farms[i]!.interactionPosition;p.player={...p.player,x:position.x,z:position.z};p.motion=createVertical(worldHeight(source,position.x,position.z));delete p.wildernessCollisionVersion;}room.world={...room.world,player:{...room.players[0]!.player}};f.replace(room);await Promise.all(peers.map(p=>foodCurrent(f,p)));
 for(let i=0;i<3;i++){await foodCurrent(f,peers[i]!);await foodInput(f,peers[i]!,[foodCommand(peers[i]!.s.world,'start-farm',i)]);}
 await foodCurrent(f,peers[0]!);assert.equal(peers[0]!.s.world.frontierFood!.revision,3);assert.equal(peers[0]!.s.world.frontierFood!.receipts.length,3);valid(peers[0]!.s.world);
 }finally{await f.stop();}
});
test('accepted active room dt advances food once across four polls and host absence close resume never refills or catches up',{timeout:120_000},async()=>{
 const f=await foodHttpFixture();try{let source=readyFoodCampaign();source=applyAction(source,foodCommand(source));const peers=await foodExpedition(f,source),host=peers[0]!,expected=applyAction(host.s.world,{type:'tick',dt:1});f.advance(1000);await Promise.all(peers.map(p=>foodInput(f,p)));await Promise.all(peers.map(p=>foodCurrent(f,p)));for(const p of peers){assert.deepEqual(p.s.world.frontierFood,expected.frontierFood);assert.deepEqual(p.s.world.frontierSupply,expected.frontierSupply);valid(p.s.world);}
 const food=clone(host.s.world.frontierFood),supply=clone(host.s.world.frontierSupply),session=host.s.sessionId;await f.raw(host.user,`/rooms/${host.s.roomId}/leave`,{sessionId:session});f.advance(3_600_000);await foodInput(f,peers[1]!);assert(peers[1]!.s.paused);assert.deepEqual(peers[1]!.s.world.frontierFood,food);assert.deepEqual(peers[1]!.s.world.frontierSupply,supply);
 const resume=await f.raw(host.user,`/rooms/${host.s.roomId}/resume`,{});assert.equal(resume.status,200);host.s=resume.body;assert.notEqual(host.s.sessionId,session);assert.deepEqual(host.s.world.frontierFood,food);assert.equal((await f.raw(host.user,`/rooms/${host.s.roomId}/sync`,{seq:1,sessionId:session,actions:[foodCommand(host.s.world)]})).status,409);
 f.advance(1000);await foodInput(f,host);const progressed=clone(host.s.world.frontierFood);await f.raw(host.user,`/rooms/${host.s.roomId}/close`,{sessionId:host.s.sessionId});f.advance(3_600_000);const reopened=await f.raw(host.user,`/rooms/${host.s.roomId}/resume`,{});assert.equal(reopened.status,200);assert.deepEqual(reopened.body.world.frontierFood,progressed);valid(f.stored(host.s.roomId).world);
 }finally{await f.stop();}
});
test('absent optional food upgrades once; malformed present food and external water/store references never reset on import read or resume',{timeout:120_000},async()=>{
 const f=await foodHttpFixture();try{const source=oldFoodCampaign(),[host]=await foodExpedition(f,source,1);assert(host);assert(host.s.world.frontierFood);assert.deepEqual(host.s.world.frontierSupply,source.frontierSupply);const food=clone(host.s.world.frontierFood),old=f.stored(host.s.roomId);delete old.world.frontierFood;f.replace(old);await foodInput(f,host);assert.deepEqual(host.s.world.frontierFood,food);
 const good=f.stored(host.s.roomId),forgeries:((r:CoopRoom)=>void)[]=[r=>{delete r.world.frontierSupply;},r=>{delete r.world.frontierTrade;},r=>{r.world.frontierSupply!.outposts[0]!.spilled++;},r=>{r.world.frontierTrade!.routes[0]!.builtAt=null;},...([null,{},[],{...food,revision:-1},{...food,ticks:999999999999},{...food,farms:[]},{...food,meals:20}].map(value=>(r:CoopRoom)=>{(r.world as unknown as {frontierFood:unknown}).frontierFood=value;}))];
 for(const change of forgeries){const invalid=clone(good);change(invalid);f.replace(invalid);assert.equal((await f.raw(host.user,`/rooms/${host.s.roomId}`)).status,503);assert.equal((await f.raw(host.user,`/rooms/${host.s.roomId}/resume`,{})).status,503);assert.deepEqual(f.stored(host.s.roomId),invalid);assert.equal((await f.raw('other','/rooms',{name:'Other',world:invalid.world})).status,400);}f.replace(good);
 for(const legacy of [createState(73129),createConnectedState(73129)]){const [p]=await foodExpedition(f,legacy,1);assert(p);assert.equal(p.s.world.frontierFood,undefined);}
 }finally{await f.stop();}
});
for(const failure of ['lost-response','invalid-overlay'] as const)test(`client ${failure} retries identical committed food input without duplicate resources, cargo, water or rewards`,{timeout:120_000},async()=>{
 const f=await foodHttpFixture();let client:CoopClient|undefined;try{const requests:string[]=[];let failed=false;const fetcher:typeof fetch=async(url,init)=>{const response=await fetch(url,{...init,headers:{...init?.headers,'oai-authenticated-user-id':'host',Origin:f.origin}});if(String(url).endsWith('/sync')&&JSON.parse(String(init?.body)).actions.some((a:{type:string})=>a.type==='regional-food')){requests.push(String(init?.body));if(!failed&&response.ok){failed=true;if(failure==='lost-response')throw Error('Response lost after SQLite commit');const payload=await response.json();payload.world.frontierSupply.outposts[0].spilled++;return new Response(JSON.stringify(payload),{status:200,headers:{'Content-Type':'application/json'}});}}return response;};
 client=new CoopClient({baseURL:f.origin,fetch:fetcher,onSnapshot:()=>{}});await client.create({name:'Host',world:tending()});const before=client.snapshot!.world,expected=applyAction(before,foodCommand(before,'tend-crop'));assert(client.send(foodCommand(before,'tend-crop')));const deadline=Date.now()+8000;while(client.snapshot!.world.frontierFood!.revision!==expected.frontierFood!.revision&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));
 assert(failed);assert.equal(requests.length,2);assert.equal(requests[0],requests[1]);assert(client.canAct);assert.deepEqual(client.snapshot!.world.frontierFood,expected.frontierFood);assert.deepEqual(client.snapshot!.world.frontierSupply,before.frontierSupply);assert.deepEqual(client.snapshot!.world.frontierTrade,before.frontierTrade);assert.deepEqual(client.snapshot!.world.inventory,before.inventory);assert(Object.isFrozen(client.snapshot!.world.frontierFood));assert(Object.isFrozen(client.snapshot!.world.frontierSupply));valid(f.stored(client.snapshot!.roomId).world);
 }finally{client?.disconnect();await f.stop();}
});
test('background suspension drops only unsent food commands and resumes without offline food or water production',{timeout:120_000},async()=>{
 const f=await foodHttpFixture();let client:CoopClient|undefined;try{const sent:string[]=[],fetcher:typeof fetch=async(url,init)=>{if(String(url).endsWith('/sync'))sent.push(String(init?.body));return fetch(url,{...init,headers:{...init?.headers,'oai-authenticated-user-id':'host',Origin:f.origin}});};client=new CoopClient({baseURL:f.origin,fetch:fetcher,onSnapshot:()=>{}});await client.create({name:'Host',world:readyFoodCampaign()});const food=clone(client.snapshot!.world.frontierFood),supply=clone(client.snapshot!.world.frontierSupply);assert(client.send(foodCommand(client.snapshot!.world)));client.setSuspended(true);f.advance(3_600_000);await new Promise(r=>setTimeout(r,300));assert.equal(sent.length,0);assert.equal(client.canAct,false);client.setSuspended(false);const deadline=Date.now()+5000;while(client.snapshot!.serverTime!==f.time()&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));assert.equal(client.snapshot!.serverTime,f.time());assert(sent.length>=1);assert(sent.every(body=>JSON.parse(body).actions.length===0));assert.deepEqual(client.snapshot!.world.frontierFood,food);assert.deepEqual(client.snapshot!.world.frontierSupply,supply);assert(client.canAct);valid(f.stored(client.snapshot!.roomId).world);
 }finally{client?.disconnect();await f.stop();}
});
