import test from 'node:test';
import assert from 'node:assert/strict';
import {createRegionalTrade,enableRegionalTrade,regionalTradePlan,advanceRegionalTrade,applyRegionalTradeCommand,regionalTradeCommandPosition,regionalTradeConservation,regionalTradeWithdrawn,regionalTradeDrainTicks,regionalTradeSummary,regionalTradeInteractions,regionalTradeActorPoses,validRegionalTrade,immutableRegionalTrade,validRegionalTradeCommand,regionalTradeConstructionBoxes,regionalTradeProjectBoxes,regionalTradeSiteBoxes,regionalTradeObstacles,regionalTradeProjectSignature,regionalTradeTargetSignature,REGIONAL_TRADE_MAX_TICKS,REGIONAL_TRADE_REPAIR_TICKS,REGIONAL_TRADE_BUILD_TICKS,type RegionalTradeState,type RegionalTradeCommand,type RegionalTradeContext} from '../src/regional-trade.ts';
import {regionalPlan,regionalHeight,regionalCacheStats,generateRegionalChunk} from '../src/regional-world.ts';
import {regionalSupplyPlan,createRegionalSupply,regionalSupplyConstructionBoxes} from '../src/regional-supply.ts';
import {obstacleSegmentIntersects} from '../src/wilderness-geometry.ts';
const seed=73129,identity={generation:2 as const,seed,regional:{version:1 as const}},clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
function cmd(s:RegionalTradeState,type:RegionalTradeCommand['type'],i=0):RegionalTradeCommand {const p=regionalTradePlan(s.seed);return {type,targetId:type==='start-source'?p.sources[i]!.id:type==='clear-route'?p.routes[i]!.id:p.projects[i]!.id,expectedRevision:s.revision};}
function ctx(s:RegionalTradeState,c:RegionalTradeCommand):RegionalTradeContext {const p=regionalTradeCommandPosition(s.seed,c)!;return {generation:2,seed:s.seed,regional:{version:1},zone:'valley',player:{x:p.x,z:p.z,hp:100},feetY:p.y,grounded:true};}
function command(s:RegionalTradeState,type:RegionalTradeCommand['type'],i=0){const c=cmd(s,type,i);return applyRegionalTradeCommand(s,ctx(s,c),c).state;}
function run(s:RegionalTradeState,seconds:number,dt=1){for(let i=0;i<Math.round(seconds/dt);i++)s=advanceRegionalTrade(s,dt);return s;}
function until(s:RegionalTradeState,condition:(s:RegionalTradeState)=>boolean,seconds=12000){for(let n=0;n<seconds;n++){if(condition(s))return s;s=advanceRegionalTrade(s,1);}assert.fail(`Condition not reached at ${s.ticks}: ${JSON.stringify(s.routes)}`);}
function check(s:RegionalTradeState){assert.ok(validRegionalTrade(clone(s),{...identity,seed:s.seed}),`invalid at ${s.ticks}`);assert.ok(regionalTradeConservation(s).every(r=>r.balanced));assert.ok(Object.isFrozen(s));return s;}
function blocked(i=0){return check(until(command(createRegionalTrade(seed,1),'start-source',i),s=>s.routes[i]!.activity==='blocked'));}
function delivered(i=0){return check(until(command(blocked(i),'clear-route',i),s=>s.routes[i]!.delivered===4));}

test('deterministic macro overlay preserves old terrain/roads/supply and advertises distinct finite sources',()=>{
 const raw=JSON.stringify(regionalPlan(seed)),supply=JSON.stringify(regionalSupplyPlan(seed)),features=regionalCacheStats().featureCompilations,p=regionalTradePlan(seed);assert.equal(regionalCacheStats().featureCompilations,features);assert.equal(p.sources.length,3);assert.equal(p.routes.length,3);assert.equal(p.projects.length,3);assert.equal(p.sources[0]!.name,'Alder Quarry');assert.equal(p.sources[1]!.kind,'forestry');assert.equal(p.sources[2]!.biome,'redstone-uplands');assert.equal(JSON.stringify(regionalPlan(seed)),raw);assert.equal(JSON.stringify(regionalSupplyPlan(seed)),supply);assert.ok(Object.isFrozen(p));assert.ok(p.sources.every(s=>s.deposit===12));assert.deepEqual(p.routes.map(r=>r.material),['quarry-stone','deadwood-timber','quarry-stone']);for(const r of p.routes){assert.ok(r.from!==r.to);assert.deepEqual(r.roadIds,r.canonicalRoute.roadIds);assert.ok(r.surfaceMetres>r.canonicalRoute.surfaceMetres);assert.equal(r.speed,1.8);assert.equal(r.travelSeconds,r.surfaceMetres/r.speed);assert.ok(r.maxGrade<=.3);}
});
test('optional upgrade is idempotent, does not erase malformed present data or mutate supply and wilderness',()=>{
 const old={...identity,frontierSupply:createRegionalSupply(seed),wilderness:{harvested:['leave-alone'],wood:4,stone:3},player:{x:77,z:55}},fresh=enableRegionalTrade(old);assert.ok('frontierTrade' in fresh);assert.equal(fresh.frontierSupply,old.frontierSupply);assert.equal(fresh.wilderness,old.wilderness);assert.equal(fresh.player,old.player);assert.equal(enableRegionalTrade(fresh),fresh);for(const frontierTrade of [null,false,undefined,{},0]){const bad={...old,frontierTrade} as any;assert.equal(enableRegionalTrade(bad),bad);}for(const original of [{generation:1 as const,seed},{generation:2 as const,seed}])assert.equal(enableRegionalTrade(original),original);
});
test('finite production physically reserves loads, blocks on route, repairs once and delivers no free reward',()=>{
 let s=createRegionalTrade(seed,1);const initial=s,source=regionalTradePlan(seed).sources[0]!,c=cmd(s,'start-source');s=applyRegionalTradeCommand(s,ctx(s,c),c).state;assert.equal(s.revision,1);assert.equal(applyRegionalTradeCommand(s,ctx(s,c),c).state,s);assert.equal(command(s,'start-source'),s);assert.equal(s.routes[0]!.remaining,12);assert.equal(regionalTradeProjectBoxes(seed,s).length,1);assert.equal(regionalTradeProjectBoxes(seed,initial).length,0);
 s=run(s,15);assert.equal(s.routes[0]!.stock,3);assert.equal(s.routes[0]!.reserved,0);s=run(s,1);assert.equal(s.routes[0]!.stock,0);assert.equal(s.routes[0]!.reserved,4);assert.equal(s.routes[0]!.cargo,0);assert.equal(s.routes[0]!.activity,'loading');s=run(s,3);assert.equal(s.routes[0]!.reserved,0);assert.equal(s.routes[0]!.cargo,4);assert.equal(s.routes[0]!.distance,0);
 s=check(until(s,s=>s.routes[0]!.activity==='blocked'));assert.equal(s.routes[0]!.delivered,0);assert.equal(s.routes[0]!.cargo,4);assert.equal(s.routes[0]!.distance,regionalTradePlan(seed).routes[0]!.obstruction.distance);const waiting=run(s,400);assert.equal(waiting.routes[0]!.distance,s.routes[0]!.distance);assert.equal(waiting.routes[0]!.delivered,0);assert.equal(waiting.routes[0]!.remaining,0);assert.equal(waiting.routes[0]!.stock,8);s=command(waiting,'clear-route');assert.equal(s.routes[0]!.clearedAt,null);assert.equal(command(s,'clear-route'),s);s=run(s,REGIONAL_TRADE_REPAIR_TICKS*.25-1);assert.equal(s.routes[0]!.activity,'blocked');s=run(s,1);assert.equal(s.routes[0]!.activity,'outbound');s=check(until(s,s=>s.routes[0]!.delivered===4));assert.equal(s.routes[0]!.destinationStock,4);assert.equal(s.routes[0]!.cargo,0);assert.equal(s.routes[0]!.shipments,1);assert.equal(s.revision,2);assert.equal(regionalTradeSummary(s,seed,s.routes[0]!.id)!.phase,'ready');
});
test('store completion unlocks real receiving capacity and leaves finite embodied plus stored reserve',()=>{
 let s=delivered();s=until(s,s=>s.routes[0]!.activity==='idle');const old=clone(s.routes[0]!);s=run(s,300);assert.deepEqual(s.routes[0],old);assert.equal(regionalTradeSummary(s,seed,s.routes[0]!.id)!.capacity,4);assert.equal(s.routes[0]!.stock,8);s=command(s,'build-store');assert.equal(s.routes[0]!.embodied,4);assert.equal(s.routes[0]!.destinationStock,0);assert.equal(s.routes[0]!.activity,'idle');const signature=regionalTradeProjectSignature(s),target=regionalTradePlan(seed).projects[0]!.id,geometry=regionalTradeTargetSignature(seed,s,target);s=run(s,15);assert.equal(s.routes[0]!.reserved,0);assert.equal(s.routes[0]!.builtAt,null);s=run(s,1);assert.notEqual(s.routes[0]!.builtAt,null);assert.equal(s.routes[0]!.reserved,4);assert.equal(regionalTradeSummary(s,seed,s.routes[0]!.id)!.capacity,12);assert.equal(regionalTradeProjectSignature(s),signature);assert.equal(regionalTradeTargetSignature(seed,s,target),geometry);s=check(until(s,s=>s.routes[0]!.activity==='finished'));assert.equal(s.routes[0]!.destinationStock,8);assert.equal(s.routes[0]!.embodied,4);assert.equal(s.routes[0]!.remaining,0);assert.equal(s.routes[0]!.stock,0);assert.equal(s.routes[0]!.delivered,12);assert.equal(s.routes[0]!.shipments,3);assert.equal(s.routes[0]!.distance,0);assert.equal(s.revision,3);assert.equal(command(s,'build-store'),s);assert.equal(regionalTradeSummary(s,seed,s.routes[0]!.id)!.phase,'exhausted');assert.equal(JSON.stringify(s).length<18000,true);
});
test('early and enroute repairs retarget actual remaining trail without teleporting or speeding up',()=>{
 const route=regionalTradePlan(seed).routes[0]!;
 for(const repairAt of [0,20,60]){let s=command(createRegionalTrade(seed,1),'start-source');s=run(s,repairAt);s=command(s,'clear-route');let old=s.routes[0]!.distance,firstDelivery:number|undefined;for(let i=0;i<500;i++){s=advanceRegionalTrade(s,.25);const r=s.routes[0]!;assert.ok(Math.abs(r.distance-old)<=1.8*.25+1e-6,`repair ${repairAt} tick${s.ticks} moved ${r.distance-old}`);old=r.distance;if(r.delivered){firstDelivery=s.ticks*.25;break;}}if(!firstDelivery)s=until(s,s=>s.routes[0]!.delivered===4);const deliveryTime=(firstDelivery??s.ticks*.25);assert.ok(deliveryTime>=16+3+route.travelSeconds+3-1e-6,`${repairAt}: premature ${deliveryTime}`);check(s);}
});
test('clock partitioning, reload/revisit and huge dt never give offline time',()=>{
 const a=command(createRegionalTrade(seed,1),'start-source');assert.deepEqual(run(a,180,.25),run(a,180,1));assert.deepEqual(run(a,180,.1),run(a,180,1));let sixty=a;for(let i=0;i<3600;i++)sixty=advanceRegionalTrade(sixty,1/60);assert.equal(sixty.ticks,240);assert(sixty.remainder<=3600*.5e-12);assert.deepEqual({...sixty,remainder:0},run(a,60));assert.deepEqual(advanceRegionalTrade(a,1e12),advanceRegionalTrade(a,1));for(const dt of [0,-1,Infinity,NaN])assert.equal(advanceRegionalTrade(a,dt),a);const live=run(a,90),reloaded=immutableRegionalTrade(clone(live),identity);assert.deepEqual(run(reloaded,33),run(a,123));assert.equal(reloaded.revision,1);
});
test('strict save boundary and revision replay reject invented atoms, jobs, getters and malformed commands',()=>{
 const s=delivered();const cases:((s:any)=>void)[]=[s=>s.extra=0,s=>s.seed++,s=>s.version=2,s=>s.revision++,s=>s.ticks--,s=>s.remainder=.25,s=>s.receipts[0].tick=-1,s=>s.receipts.push(s.receipts[0]),s=>s.receipts[1].targetId=s.receipts[0].targetId,s=>s.receipts[1].type='start-source',s=>s.routes.reverse(),s=>s.routes[0].remaining++,s=>s.routes[0].stock++,s=>s.routes[0].reserved++,s=>s.routes[0].cargo++,s=>s.routes[0].destinationStock++,s=>s.routes[0].embodied++,s=>s.routes[0].withdrawn++,s=>s.routes[0].builtAt=1,s=>s.routes[0].clearedAt=1,s=>s.routes[0].distance=0,s=>s.routes[0].legStartDistance=0,s=>s.routes[0].activity='finished',s=>s.routes[0].nextEventAt=1,s=>Object.defineProperty(s.routes[0],'stock',{get(){throw Error('getter');}})];for(const f of cases){const bad=clone(s);f(bad);assert.equal(validRegionalTrade(bad,identity),false);assert.equal(advanceRegionalTrade(bad,.01),bad);assert.throws(()=>immutableRegionalTrade(bad,identity));}
 assert.equal(validRegionalTrade(s,{...identity,generation:1}),false);assert.equal(validRegionalTrade(s,{...identity,seed:1}),false);assert.equal(validRegionalTrade(s,{...identity,regional:undefined} as any),false);const c=cmd(s,'build-store');assert.ok(validRegionalTradeCommand(c));for(const patch of [{expectedRevision:16},{expectedRevision:-1},{expectedRevision:NaN},{type:'grant'},{targetId:''},{targetId:'\n'},{targetId:'x'.repeat(121)},{bonus:1}])assert.equal(validRegionalTradeCommand({...c,...patch}),false);
});
test('only living grounded actors at exact contextual target can operate with current revision',()=>{
 const s=createRegionalTrade(seed,1),c=cmd(s,'start-source'),context=ctx(s,c);for(const patch of [{zone:'dungeon'},{grounded:false},{grounded:undefined},{feetY:undefined},{feetY:NaN},{feetY:context.feetY!+.5},{player:{...context.player,hp:0}},{player:{...context.player,x:0,z:0}},{seed:12}])assert.equal(applyRegionalTradeCommand(s,{...context,...patch} as RegionalTradeContext,c).state,s);for(const wrong of [{...c,expectedRevision:1},{...c,targetId:'wrong'},{...c,type:'build-store' as const}])assert.equal(applyRegionalTradeCommand(s,context,wrong).state,s);assert.equal(command(s,'clear-route'),s);assert.equal(command(s,'build-store'),s);
});
test('stable workers and carrier scalar persist through blocked, return and completion presentation',()=>{
 const initial=createRegionalTrade(seed,1),ids=regionalTradeActorPoses(seed,initial).map(a=>a.id);assert.equal(ids.length,12);assert.equal(new Set(ids).size,12);let s=delivered();assert.deepEqual(regionalTradeActorPoses(seed,s).map(a=>a.id),ids);let previous=s.routes[0]!.distance;while(s.routes[0]!.activity==='returning'){s=advanceRegionalTrade(s,.25);const pose=regionalTradeActorPoses(seed,s).find(a=>a.kind==='carrier'&&a.routeId===s.routes[0]!.id)!;assert.equal(pose.distance,s.routes[0]!.distance);assert.ok(previous-pose.distance<=.45+1e-6);assert.ok(pose.distance<=previous);previous=pose.distance;}assert.equal(previous,0);assert.deepEqual(regionalTradeActorPoses(seed,s).map(a=>a.id),ids);assert.ok(regionalTradeSiteBoxes(seed,initial).every(b=>!b.solid));assert.equal(regionalTradeObstacles(seed,initial).length,0);assert.ok(regionalTradeInteractions(seed,s).some(i=>i.kind==='build-store'&&i.enabled));
});
test('reserved pads and complete canonical routes clear legacy structures, V31 collectors and new solids',()=>{
 for(const seed of [0,1,42,73129,4294967295]){const p=regionalTradePlan(seed),base=regionalPlan(seed),solids=base.sites.flatMap(site=>generateRegionalChunk(seed,...site.ownerChunk.split(':').map(Number) as [number,number]).structures.filter(b=>b.id.startsWith(site.id+'/'))),supply=base.sites.filter(s=>s.kind==='outpost').flatMap(s=>regionalSupplyConstructionBoxes(seed,s.id)),newSolids=[...p.sources,...p.projects].flatMap(s=>regionalTradeConstructionBoxes(seed,s.id)),all=[...solids,...supply,...newSolids].map(b=>({featureId:b.id,x:b.center.x,y:b.center.y,z:b.center.z,hx:b.half.x,hy:b.half.y,hz:b.half.z}));
  for(const target of [...p.sources,...p.projects]){const site=base.sites.find(s=>s.id===target.siteId)!;for(const box of regionalTradeConstructionBoxes(seed,target.id)){for(const dx of [-box.half.x,box.half.x])for(const dz of [-box.half.z,box.half.z]){assert.ok(Math.abs(regionalHeight(seed,box.center.x+dx,box.center.z+dz)-site.position.y)<1e-5);assert.ok(Math.hypot(box.center.x+dx-site.position.x,box.center.z+dz-site.position.z)<site.radius);}}const a={...target.interactionPosition,y:target.interactionPosition.y+.85};assert.ok(all.every(o=>!obstacleSegmentIntersects(o,a,a,.5)),`${seed} ${target.id} blocked interaction`);}
  for(const route of p.routes){assert.ok(route.maxGrade<=.3);for(let i=1;i<route.points.length;i++){const a={...route.points[i-1]!,y:route.points[i-1]!.y+.85},b={...route.points[i]!,y:route.points[i]!.y+.85};assert.ok(all.every(o=>!obstacleSegmentIntersects(o,a,b,.5)),`${seed} ${route.id} blocked point ${i}`);}}
 }
});
test('all routes finish with 36 conserved finite units; cold maximum clocks replay bounded event work',async(t)=>{
 let s=createRegionalTrade(seed,1);for(let i=0;i<3;i++){s=command(s,'start-source',i);s=command(s,'clear-route',i);}s=until(s,s=>s.routes.every(r=>r.delivered===4));for(let i=0;i<3;i++)s=command(s,'build-store',i);s=check(until(s,s=>s.routes.every(r=>r.activity==='finished')));assert.equal(s.revision,9);assert.equal(s.routes.reduce((n,r)=>n+r.delivered,0),36);const stalled=blocked();for(const source of [s,stalled,createRegionalTrade(seed,1)]){const huge=clone(source);huge.ticks=REGIONAL_TRADE_MAX_TICKS;huge.remainder=0;const cold=await import(`../src/regional-trade.ts?cold=${source.revision}`),start=performance.now();assert.ok(cold.validRegionalTrade(huge,identity));const ms=performance.now()-start;t.diagnostic(`revision ${source.revision}, clock ${huge.ticks}: ${ms.toFixed(2)} ms, ${JSON.stringify(huge).length} bytes`);assert.ok(ms<1000);const immutable=cold.immutableRegionalTrade(huge,identity);const resumed=cold.advanceRegionalTrade(immutable,1);assert.ok(resumed.ticks<REGIONAL_TRADE_MAX_TICKS);assert.ok(cold.validRegionalTrade(clone(resumed),identity));assert.deepEqual(cold.regionalTradeConservation(resumed),cold.regionalTradeConservation(immutable));}
});


test('reserve withdrawals are exact one-time lifetime raw credits, leaving source and wilderness ledgers alone',()=>{
 let s=createRegionalTrade(seed,1);for(let i=0;i<3;i++){assert.equal(command(s,'withdraw-reserve',i),s);s=command(s,'start-source',i);s=command(s,'clear-route',i);}s=until(s,s=>s.routes.every(r=>r.delivered===4));for(let i=0;i<3;i++){assert.equal(command(s,'withdraw-reserve',i),s);s=command(s,'build-store',i);}
 for(let i=0;i<3;i++){s=until(s,s=>s.routes[i]!.destinationStock===4);const before=s,c=cmd(s,'withdraw-reserve',i);s=applyRegionalTradeCommand(s,ctx(s,c),c).state;assert.equal(s.routes[i]!.withdrawn,4);assert.equal(s.routes[i]!.destinationStock,0);assert.equal(applyRegionalTradeCommand(s,ctx(s,c),c).state,s);assert.equal(command(s,'withdraw-reserve',i),s);assert.equal(s.routes[i]!.embodied,before.routes[i]!.embodied);check(s);}
 s=until(s,s=>s.routes.every(r=>r.activity==='finished'));for(let i=0;i<3;i++){assert.equal(s.routes[i]!.destinationStock,4);s=command(s,'withdraw-reserve',i);assert.equal(s.routes[i]!.withdrawn,8);assert.equal(s.routes[i]!.destinationStock,0);assert.equal(command(s,'withdraw-reserve',i),s);}check(s);assert.equal(s.revision,15);assert.deepEqual(regionalTradeWithdrawn(s),{wood:8,stone:16});assert.deepEqual(regionalTradeWithdrawn(undefined),{wood:0,stone:0});assert.ok(regionalTradeConservation(s).every(r=>r.embodied===4&&r.withdrawn===8&&r.total===12));assert.equal(regionalTradeSummary(s,seed,s.routes[0]!.id)!.withdrawn,8);const huge=clone(s);huge.ticks=REGIONAL_TRADE_MAX_TICKS;assert.ok(validRegionalTrade(huge,identity));
});
test('direct producer apron approach stays clear of the activated stock footprint',()=>{
 for(const seed of [0,1,42,991,73129,4294967295]){const plan=regionalTradePlan(seed);for(const p of [...plan.sources,...plan.projects]){const all=[...plan.sources,...plan.projects].flatMap(p=>regionalTradeConstructionBoxes(seed,p.id)).map(b=>({featureId:b.id,x:b.center.x,y:b.center.y,z:b.center.z,hx:b.half.x,hy:b.half.y,hz:b.half.z})),from={...p.interactionPosition,y:p.interactionPosition.y+.85},to={...p.workerPosition,y:p.workerPosition.y+.85};assert.ok(all.every(b=>!obstacleSegmentIntersects(b,from,to,.55)),`${seed} ${p.id} source work approach`);}}
});
test('advance rejects top-level accessors without invoking them',()=>{let accessed=false;const s=clone(createRegionalTrade(seed,1));Object.defineProperty(s,'seed',{get(){accessed=true;throw Error('seed getter');}});assert.equal(advanceRegionalTrade(s,.01),s);assert.equal(validRegionalTrade(s,identity),false);assert.equal(accessed,false);});


test('max-clock blocked import rebases idle gaps, permits repair and finishes without material or movement reset',()=>{
 const ordinary=blocked(),huge=clone(ordinary);huge.ticks=REGIONAL_TRADE_MAX_TICKS;let s=immutableRegionalTrade(huge,identity);const distance=s.routes[0]!.distance,balance=regionalTradeConservation(s);s=command(s,'clear-route');assert.ok(s.ticks<REGIONAL_TRADE_MAX_TICKS);assert.ok(s.ticks<=16*regionalTradeDrainTicks(seed));assert.equal(s.routes[0]!.distance,distance);assert.deepEqual(regionalTradeConservation(s),balance);assert.equal(s.routes[0]!.repairStartedAt,s.ticks);s=check(run(s,12));assert.equal(s.routes[0]!.activity,'outbound');s=until(s,s=>s.routes[0]!.delivered===4);s=command(s,'build-store');s=check(until(s,s=>s.routes[0]!.activity==='finished'));s=check(command(s,'withdraw-reserve'));assert.equal(s.routes[0]!.withdrawn,8);assert.equal(s.routes[0]!.embodied,4);assert.ok(validRegionalTrade(clone(s),identity));
});
test('idle-gap compression preserves multi-route phases, finite withdrawals and exact pending timing',()=>{
 let s=createRegionalTrade(seed,1);for(let i=0;i<3;i++){s=command(s,'start-source',i);s=command(s,'clear-route',i);}s=until(s,s=>s.routes.every(r=>r.delivered===4));for(let i=0;i<3;i++)s=command(s,'build-store',i);s=until(s,s=>s.routes.every(r=>r.activity==='finished'));for(let i=0;i<3;i++)s=command(s,'withdraw-reserve',i);const full=clone(s);full.ticks=REGIONAL_TRADE_MAX_TICKS;const resumed=advanceRegionalTrade(immutableRegionalTrade(full,identity),.25);check(resumed);assert.deepEqual(regionalTradeConservation(resumed),regionalTradeConservation(s));assert.deepEqual(regionalTradeWithdrawn(resumed),regionalTradeWithdrawn(s));assert.deepEqual(resumed.receipts.map(({tick,...r})=>r),s.receipts.map(({tick,...r})=>r));
 // A late start is legal and equivalent to an early start; the active 7-tick tail cannot be shortened.
 const early=run(command(createRegionalTrade(seed,1),'start-source'),1.75,.25),late=clone(early),shift=REGIONAL_TRADE_MAX_TICKS-early.ticks;late.ticks+=shift;late.receipts[0]!.tick+=shift;for(const r of late.routes)if(r.sourceStartedAt!==null){r.sourceStartedAt+=shift;if(r.productionNextAt!==null)r.productionNextAt+=shift;}assert.ok(validRegionalTrade(late,identity));let lateActive=advanceRegionalTrade(immutableRegionalTrade(late,identity),.25),earlyActive=advanceRegionalTrade(early,.25);assert.deepEqual(regionalTradeConservation(lateActive),regionalTradeConservation(earlyActive));assert.equal(lateActive.routes[0]!.productionNextAt!-lateActive.ticks,earlyActive.routes[0]!.productionNextAt!-earlyActive.ticks);for(let i=0;i<200;i++){lateActive=advanceRegionalTrade(lateActive,.25);earlyActive=advanceRegionalTrade(earlyActive,.25);assert.equal(lateActive.routes[0]!.distance,earlyActive.routes[0]!.distance);assert.equal(lateActive.routes[0]!.activity,earlyActive.routes[0]!.activity);}check(lateActive);
});

test('rebasing a long internal receipt gap preserves simultaneous producer and repaired-carrier timing',()=>{
 let early=blocked();const lateRaw=clone(early),horizon=regionalTradeDrainTicks(seed);lateRaw.ticks=REGIONAL_TRADE_MAX_TICKS-horizon-50;let late=immutableRegionalTrade(lateRaw,identity);early=command(early,'start-source',1);late=command(late,'start-source',1);early=run(early,7);late=run(late,7);early=command(early,'clear-route');late=command(late,'clear-route');
 for(let i=0;i<800;i++){early=advanceRegionalTrade(early,.25);late=advanceRegionalTrade(late,.25);assert.deepEqual(regionalTradeConservation(late),regionalTradeConservation(early));for(let r=0;r<3;r++){const a=early.routes[r]!,b=late.routes[r]!;assert.equal(a.activity,b.activity);assert.equal(a.distance,b.distance);if(a.nextEventAt!==null)assert.equal(a.nextEventAt-early.ticks,b.nextEventAt!-late.ticks);if(a.productionNextAt!==null)assert.equal(a.productionNextAt-early.ticks,b.productionNextAt!-late.ticks);}}
 assert.ok(late.ticks<16*horizon);check(late);assert.deepEqual(late.receipts.map(({tick,...r})=>r),early.receipts.map(({tick,...r})=>r));
});

test('rebased tiny-dt early return remains deeply immutable and replay-valid',()=>{
 const seed=73129,ctx={generation:2 as const,seed,regional:{version:1 as const}},old=JSON.parse(JSON.stringify(createRegionalTrade(seed,1)));old.ticks=REGIONAL_TRADE_MAX_TICKS;
 const resumed=advanceRegionalTrade(immutableRegionalTrade(old,ctx),Number.MIN_VALUE);assert(Object.isFrozen(resumed));assert(Object.isFrozen(resumed.routes));assert(Object.isFrozen(resumed.routes[0]));assert(validRegionalTrade(JSON.parse(JSON.stringify(resumed)),ctx));
});
