import test from 'node:test';import assert from 'node:assert/strict';
import {RegionalStreamer,createRegionalGenerator,regionalCellKey,type RegionalGenerator,type RegionalEntry} from '../src/regional-stream.ts';
import {regionalChunkBounds,REGION_BOUND,type RegionalChunk} from '../src/regional-world.ts';
const chunk=(seed:number,cx:number,cz:number):RegionalChunk=>({version:1,seed,cx,cz,key:`${cx}:${cz}`,bounds:regionalChunkBounds(cx,cz),terrain:{vertices:[cx*64,0,cz*64,cx*64+1,0,cz*64,cx*64,0,cz*64+1],indices:[0,2,1],bound:REGION_BOUND,step:2},biomes:['meadow'],roads:[],water:[],structures:[],features:[],sites:[],budget:{candidates:0,vertices:3,triangles:1}});
function fixture(){let calls=0;const staged:{e:RegionalEntry;initial:boolean}[]=[],unloads:{key:string;revision:number}[]=[];let signature='0';const gen:RegionalGenerator={async request(seed,cx,cz,signal){calls++;if(signal?.aborted)throw Object.assign(Error(),{name:'AbortError'});return chunk(seed,cx,cz);},dispose(){},backend:'test'};const stream=new RegionalStreamer(42,gen,(e,initial)=>staged.push({e,initial}),(key,revision)=>unloads.push({key,revision}),()=>signature);return {stream,staged,unloads,setSignature:(s:string)=>signature=s,get calls(){return calls;}};}
const settle=()=>new Promise(r=>setTimeout(r,0));
test('regional startup prioritizes nine surrounding chunks and requires matching receipts',async()=>{const f=fixture();await f.stream.initial(100,100);assert.equal(f.stream.entries.size,9);assert.equal(f.staged[0]!.e.key,'region:1:1');assert(f.staged.every(s=>s.initial));assert.equal(f.stream.stats.confirmed,0);const e=f.staged[0]!.e;assert.equal(f.stream.acknowledge(e.key,e.revision+1,true),false);assert(f.stream.acknowledge(e.key,e.revision,true));assert.equal(f.stream.stats.confirmed,1);});
test('out-and-back stream remains bounded and unload receipts protect ownership',async()=>{const f=fixture();await f.stream.initial(0,0);f.stream.initialReady();for(const x of [...Array.from({length:45},(_,i)=>i*64),...Array.from({length:45},(_,i)=>(44-i)*64)].map(x=>Math.min(1500,x))){f.stream.update(x,0);await settle();for(const s of f.staged.splice(0))f.stream.acknowledge(s.e.key,s.e.revision,true);for(const u of f.unloads.splice(0))f.stream.acknowledge(u.key,u.revision,false);f.stream.update(x,0);await settle();assert(f.stream.entries.size<=49);assert(f.stream.stats.queued<=49);assert(f.stream.stats.inFlight<=1);}assert(f.stream.stats.generated>100);assert(f.stream.stats.peakResident<=49);});
test('harvest revision restages resident content, stale unload cannot remove replacement',async()=>{const f=fixture();await f.stream.initial(0,0);f.stream.initialReady();const old=f.stream.entries.get('region:0:0')!;const oldRevision=old.revision;f.setSignature('1');f.stream.update(0,0);assert(old.revision>oldRevision);assert(!f.stream.acknowledge(old.key,oldRevision,true));f.stream.acknowledge(old.key,old.revision,true);f.stream.update(600,0);const unload=f.unloads.find(u=>u.key===old.key)!;assert(unload);f.stream.update(0,0);assert(old.revision>unload.revision);assert.equal(f.stream.acknowledge(old.key,unload.revision,false),false);assert(f.stream.entries.has(old.key));});
test('reset ignores stale in-flight worker result and closes queue',async()=>{let complete:(v:RegionalChunk)=>void=()=>{};const generator:RegionalGenerator={request(seed,cx,cz){return new Promise(resolve=>complete=resolve);},dispose(){},backend:'fake'};const staged:RegionalEntry[]=[];const s=new RegionalStreamer(42,generator,e=>staged.push(e),()=>{},()=>''),initial=s.initial(0,0);s.reset();complete(chunk(42,0,0));await assert.rejects(initial,{name:'AbortError'});assert.equal(staged.length,0);assert.equal(s.entries.size,0);});
test('outer clipped bounds never queue nonexistent coordinates',async()=>{const f=fixture();await f.stream.initial(REGION_BOUND-.5,REGION_BOUND-.5);f.stream.initialReady();f.stream.update(REGION_BOUND-.5,REGION_BOUND-.5);await settle();assert([...f.stream.entries.values()].every(e=>e.cx<=24&&e.cz<=24));});
test('worker client validates response identity and cancellation terminates old port',async()=>{let port:any,terminated=0;const c=createRegionalGenerator(()=>port={postMessage(){},terminate(){terminated++;},onmessage:null,onerror:null,onmessageerror:null});const controller=new AbortController();const p=c.request(42,0,0,controller.signal);controller.abort();await assert.rejects(p,{name:'AbortError'});assert.equal(terminated,1);const p2=c.request(42,0,0);port.onmessage({data:{type:'chunk',id:2,seed:43,cx:0,cz:0,chunk:chunk(42,0,0)}});await assert.rejects(p2,/Invalid regional/);assert.equal(terminated,2);c.dispose();});
test('stale rejection cannot delete newer load; rejected replacement retains old ownership until unload',async()=>{const f=fixture();await f.stream.initial(0,0);f.stream.initialReady();const e=f.stream.entries.get('region:0:0')!,first=e.revision;f.setSignature('1');f.stream.update(0,0);const replacement=e.revision;assert(replacement>first);assert.equal(f.stream.reject(e.key,first,true),false);assert.equal(e.revision,replacement);assert.equal(f.stream.reject(e.key,replacement,true),true);assert.equal(e.revision,first);assert.equal(e.confirmed,true);assert(f.stream.entries.has(e.key));f.stream.update(1000,1000);const removal=f.unloads.find(u=>u.key===e.key)!;assert(removal);assert(f.stream.acknowledge(e.key,removal.revision,false));assert(!f.stream.entries.has(e.key));});
test('retained stream resumes after a non-disposing page pause and dispose permanently cancels generation',async()=>{const f=fixture();await f.stream.initial(0,0);f.stream.initialReady();const before=f.calls;await settle();f.stream.update(64,0);await settle();assert(f.calls>before);f.stream.dispose();const stopped=f.calls;f.stream.update(640,0);await settle();assert.equal(f.calls,stopped);assert.equal(f.stream.entries.size,0);});
test('worker acceptance validates immutable address and bounded render attributes',async()=>{const {validRegionalChunk}=await import('../src/regional-stream.ts'),{generateRegionalChunk}=await import('../src/regional-world.ts');for(const [x,z]of [[0,0],[24,24],[-25,-25],[-11,9]]){const c=generateRegionalChunk(42,x!,z!);assert(validRegionalChunk(c,42,x!,z!));assert(!validRegionalChunk({...c,seed:43},42,x!,z!));assert(!validRegionalChunk({...c,terrain:{...c.terrain,normals:[]}},42,x!,z!));assert(!validRegionalChunk({...c,features:Array(45).fill(c.features[0])},42,x!,z!));}});
test('same-zone authority relocation restarts near-edge initial preloads before safety coverage is lost',async()=>{const {regionalRelocationNeeded}=await import('../src/regional-stream.ts');assert(regionalRelocationNeeded({x:63.9,z:32},{x:1000,z:1000},{x:127.8,z:32}));assert(!regionalRelocationNeeded({x:63.9,z:32},{x:1000,z:1000},{x:90,z:32}));assert(!regionalRelocationNeeded(null,{x:63.9,z:32},{x:127.8,z:32}));assert(regionalRelocationNeeded(null,{x:1000,z:1000},{x:-40,z:32}));});
