import test,{type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {Worker} from 'node:worker_threads';
import {mkdtempSync,readdirSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {build} from 'vite';
import {regionalPhysics,type PhysicsSnapshot} from './helpers/regional-physics.ts';
import {generateRegionalChunk,regionalPlan,regionalHeight,regionalObstaclesNear,type RegionalBox} from '../src/regional-world.ts';
import {regionalTradePlan,regionalTradeConstructionBoxes,regionalTradeProjectBoxes,regionalTradeObstacles,regionalTradeCommandPosition,applyRegionalTradeCommand,createRegionalTrade,advanceRegionalTrade,type RegionalTradeState,type RegionalTradeCommand} from '../src/regional-trade.ts';
import {createRegionalState,parseSave,serializeSave,type State} from '../src/world.ts';
import {regionalSupplyPlan,regionalSupplyConstructionBoxes} from '../src/regional-supply.ts';
import {wildernessCapsuleClearance} from '../src/wilderness-lab.ts';
import type {WildernessObstacle} from '../src/wilderness-geometry.ts';
import type {Vec3} from '../src/procedural.ts';
const asSolid=(b:RegionalBox):WildernessObstacle=>({featureId:b.id,x:b.center.x,y:b.center.y,z:b.center.z,hx:b.half.x,hy:b.half.y,hz:b.half.z});
const neighborhood=(x:number,z:number)=>{const cx=Math.floor(x/64),cz=Math.floor(z/64);return [-1,0,1].flatMap(dx=>[-1,0,1].map(dz=>({cx:cx+dx,cz:cz+dz})));};
const near=(o:WildernessObstacle,p:{x:number;z:number})=>Math.abs(o.x-p.x)<o.hx+1&&Math.abs(o.z-p.z)<o.hz+1;
function clearance(seed:number,p:Vec3,solids:WildernessObstacle[]){return Math.min(...solids.filter(o=>near(o,p)).map(o=>wildernessCapsuleClearance({x:p.x,z:p.z,feetY:regionalHeight(seed,p.x,p.z),grounded:true,crouched:false,step:0},o)));}
function segment(a:Vec3,b:Vec3,step=.25){const n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/step));return Array.from({length:n+1},(_,i)=>({x:a.x+(b.x-a.x)*i/n,y:a.y+(b.y-a.y)*i/n,z:a.z+(b.z-a.z)*i/n}));}
function activate(s:RegionalTradeState,type:RegionalTradeCommand['type'],targetId:string){const command={type,targetId,expectedRevision:s.revision},p=regionalTradeCommandPosition(s.seed,command)!;const result=applyRegionalTradeCommand(s,{...createRegionalState(s.seed),player:{x:p.x,z:p.z,hp:100},feetY:p.y,grounded:true},command).state;assert.notEqual(result,s,`accepted ${type} ${targetId}`);return result;}
function scenarios(seed:number){const p=regionalTradePlan(seed);let s=createRegionalTrade(seed,1);for(const r of p.routes){s=activate(s,'start-source',r.sourceId);s=activate(s,'clear-route',r.id);}for(let i=0;i<Math.ceil(Math.max(...p.routes.map(r=>r.travelSeconds))+100)&&s.routes.some(r=>r.delivered<4);i++)s=advanceRegionalTrade(s,1);assert(s.routes.every(r=>r.delivered===4));for(const project of p.projects)s=activate(s,'build-store',project.id);const scaffold=s;for(let i=0;i<16;i++)s=advanceRegionalTrade(s,1);assert(s.routes.every(r=>r.builtAt!==null));return {scaffold,completed:s};}
function makeCell(seed:number,cx:number,cz:number,trade:RegionalTradeState,revision=1,collectorPhase:'scaffold'|'completed'='completed'){
 const chunk=generateRegionalChunk(seed,cx,cz),supply=regionalSupplyPlan(seed).outposts.filter(p=>p.ownerChunk===chunk.key).flatMap(p=>regionalSupplyConstructionBoxes(seed,p.id)),tradeBoxes=regionalTradeProjectBoxes(seed,trade).filter(b=>Math.floor(b.center.x/64)===cx&&Math.floor(b.center.z/64)===cz);
 // Both V31 collector phases use their real unchanged authorized envelope.
 return {key:`region:${cx}:${cz}`,revision,bounds:chunk.bounds,terrain:chunk.terrain,obstacles:[...chunk.features.flatMap(f=>f.solids),...chunk.structures.filter(b=>b.solid).map(asSolid),...supply.map(b=>asSolid({...b,material:collectorPhase==='scaffold'?'regional-supply-scaffold':b.material})),...tradeBoxes.filter(b=>b.solid).map(asSolid)]};
}

test('seed sweep keeps every freight centerline, endpoint and work approach supported and clear with both V31 collector phases and all new solids',{timeout:120_000},()=>{
 const seeds=[73129,0,1,42,12345,0xffffffff],records=[],failures:unknown[]=[];let minimum=Infinity,samples=0,maxSupportError=0,maxGrade=0;
 for(const seed of seeds){const plan=regionalTradePlan(seed),all=[...plan.sources,...plan.projects].flatMap(p=>regionalTradeConstructionBoxes(seed,p.id)).map(asSolid),collectors=regionalSupplyPlan(seed).outposts.flatMap(p=>regionalSupplyConstructionBoxes(seed,p.id)).map(asSolid);let localMinimum=Infinity,routeSamples=0;
  const cache=new Map<string,WildernessObstacle[]>(),solids=(p:Vec3)=>{const key=`${Math.floor(p.x/64)}:${Math.floor(p.z/64)}`;let s=cache.get(key);if(!s){s=regionalObstaclesNear(seed,p.x,p.z);cache.set(key,s);}return [...s,...collectors,...all];};
  const probe=(p:Vec3,label:string)=>{const value=clearance(seed,p,solids(p));minimum=Math.min(minimum,value);localMinimum=Math.min(localMinimum,value);samples++;if(value<-.015&&failures.length<100)failures.push({seed,label,point:p,clearance:value});maxSupportError=Math.max(maxSupportError,Math.abs(p.y-regionalHeight(seed,p.x,p.z)));};
  for(const route of plan.routes){maxGrade=Math.max(maxGrade,route.maxGrade);assert(route.maxGrade<=.301,`${seed} ${route.id} grade ${route.maxGrade}`);assert(route.roadIds.length>0);assert.deepEqual(route.roadIds,route.canonicalRoute.roadIds);for(const p of route.points){probe(p,route.id);routeSamples++;}probe(route.obstruction.interactionPosition,route.id+'/repair');}
  for(const s of plan.sources){probe(s.interactionPosition,s.id+'/dock');probe(s.workerPosition,s.id+'/worker');for(const p of segment(s.interactionPosition,s.workerPosition))probe(p,s.id+'/work-approach');}
  for(const p of plan.projects){probe(p.interactionPosition,p.id+'/build');probe(p.workerPosition,p.id+'/worker');for(const point of segment(p.interactionPosition,p.workerPosition))probe(point,p.id+'/builder-approach');}
  // Preserve original resident work paths beside old rain-collector scaffold/tank.
  for(const c of regionalSupplyPlan(seed).outposts)for(const resident of c.residents)for(let i=1;i<resident.path.length;i++)for(const p of segment(resident.path[i-1]!,resident.path[i]!))probe(p,resident.id+'/collector-work');
  for(const box of [...plan.sources,...plan.projects].flatMap(p=>regionalTradeConstructionBoxes(seed,p.id)))for(const x of [box.center.x-box.half.x,box.center.x+box.half.x])for(const z of [box.center.z-box.half.z,box.center.z+box.half.z])assert(Math.abs(regionalHeight(seed,x,z)-(box.center.y-box.half.y))<.015,'footprint rests on existing pad');
  records.push({seed,routes:plan.routes.map(r=>({id:r.id,surfaceMetres:r.surfaceMetres,maxGrade:r.maxGrade,roadCount:r.roadIds.length})),routeSamples,generatedNeighborhoods:cache.size,minimumClearance:Number.isFinite(localMinimum)?localMinimum:null});
 }
 assert.deepEqual(failures,[],JSON.stringify(failures));assert(maxSupportError<.02);console.log(JSON.stringify({regionalTradeGeometry:1,scope:'Independent standing-capsule geometry and existing generated-terrain checks; includes new sources/stores and unchanged V31 scaffold/tank envelope. Not a controller traversal or browser visual.',seeds:records,samples,minimumClearance:minimum,maxTerrainSupportError:maxSupportError,maxRouteGrade:maxGrade}));
});

/** Build the actual browser client and import its emitted production physics-worker
 * asset for ordinary movement tests. No browser/network or standalone WASM diagnostic. */
async function compiledPhysics(t:TestContext,config:Record<string,unknown>){
 const folder=mkdtempSync(join(tmpdir(),'axiom-regional-trade-physics-'));t.after(()=>rmSync(folder,{recursive:true,force:true}));
 await build({configFile:resolve('vite.client.config.ts'),logLevel:'silent',build:{outDir:folder,emptyOutDir:true}});
 const asset=readdirSync(join(folder,'assets')).find(n=>/^physics\.worker-.*\.js$/.test(n));assert(asset,'production client emits its physics worker');writeFileSync(join(folder,'package.json'),'{"type":"module"}');
 const file=join(folder,'assets',asset),sha256=createHash('sha256').update(readFileSync(file)).digest('hex'),worker=new Worker(`const {parentPort}=require('node:worker_threads');globalThis.self=globalThis;self.postMessage=m=>parentPort.postMessage(m);parentPort.on('message',m=>self.onmessage({data:m}));import(${JSON.stringify(pathToFileURL(file).href)}).then(()=>parentPort.postMessage({type:'boot'}));`,{eval:true});t.after(()=>worker.terminate());
 let epoch=0,error:Error|undefined,latest:PhysicsSnapshot|undefined;const messages:any[]=[],snapshots:PhysicsSnapshot[]=[];worker.on('error',e=>error=e);worker.on('message',m=>{if(m.type==='error')error=new Error(m.message);if(m.type==='snapshot'){latest=m;snapshots.push(m);}else messages.push(m);});
 async function take(type:string,match:(m:any)=>boolean=()=>true){const deadline=Date.now()+20000;for(;;){if(error)throw error;const i=messages.findIndex(m=>m.type===type&&match(m));if(i>=0)return messages.splice(i,1)[0];assert(Date.now()<deadline,`Compiled worker timed out on ${type}: ${JSON.stringify({latest,messages})}`);await new Promise(r=>setTimeout(r,1));}}
 const send=(m:Record<string,unknown>)=>worker.postMessage({epoch,...m});async function tick(n=1){const result:PhysicsSnapshot[]=[];for(let left=n;left>0;left-=120){snapshots.length=0;send({type:'step',ticks:Math.min(left,120)});await take('stepped');result.push(...snapshots);}return result;}
 const input=(values:Record<string,unknown>={})=>send({type:'input',x:0,z:0,...values});await take('boot');send({type:'init',manual:true,streamedTerrain:true,bound:Math.sqrt(10_000_000)/2,obstacles:[],...config});await take('ready');await tick(5);
 return {send,tick,input,take,sha256,get latest(){return latest!;},async zone(config:Record<string,unknown>){epoch++;send({type:'zone',manual:true,streamedTerrain:true,bound:Math.sqrt(10_000_000)/2,obstacles:[],...config});await take('ready');await tick(5);}};
}
type Controller=Pick<Awaited<ReturnType<typeof regionalPhysics>>,'send'|'tick'|'input'|'take'|'latest'>;
function stream(p:Controller,seed:number,trade:RegionalTradeState,initial:ReturnType<typeof makeCell>[]){const active=new Map(initial.map(c=>[c.key,c])),visited=new Set(active.keys());let revision=20,peak=active.size,peakColliders=0;return {async update(){const next=neighborhood(p.latest.x,p.latest.z),keys=new Set(next.map(c=>`region:${c.cx}:${c.cz}`));for(const key of active.keys())if(!keys.has(key)){p.send({type:'cell-unload',key,revision:++revision});await p.take('cell-ack',m=>m.key===key&&!m.loaded);active.delete(key);}for(const c of next){const key=`region:${c.cx}:${c.cz}`;if(!active.has(key)){const cell=makeCell(seed,c.cx,c.cz,trade,++revision);p.send({type:'cell-load',...cell});await p.take('cell-ack',m=>m.key===key&&m.revision===cell.revision&&m.loaded);active.set(key,cell);visited.add(key);}}peak=Math.max(peak,active.size);peakColliders=Math.max(peakColliders,p.latest.streaming?.cellColliders??0);},get stats(){return {visitedCells:visited.size,peakResidentCells:peak,peakCellColliders:peakColliders};}};}
async function walk(p:Controller,seed:number,points:Vec3[],streaming?:ReturnType<typeof stream>){let samples=0,grounded=0,metres=0,maxGroundError=0,blocked=0,previous=p.latest;const began=p.latest.step;
 for(const target of points){let attempts=0;while(Math.hypot(target.x-p.latest.x,target.z-p.latest.z)>.14){assert(attempts++<1000,`route stalled at ${JSON.stringify(p.latest)} toward ${JSON.stringify(target)}`);await streaming?.update();const dx=target.x-p.latest.x,dz=target.z-p.latest.z,d=Math.hypot(dx,dz),strength=d<.5?.22:.33037037037;p.input({x:dx/d*strength,z:dz/d*strength,analog:true});const batch=await p.tick(Math.max(1,Math.min(120,Math.floor(d/(d<.5?1.05:1.8)*60*.8))));for(const s of batch){samples++;grounded+=+s.grounded;metres+=Math.hypot(s.x-previous.x,s.z-previous.z);maxGroundError=Math.max(maxGroundError,Math.abs(s.feetY-regionalHeight(seed,s.x,s.z)));blocked+=+(s.streaming?.blocked??false);previous=s;}assert(samples<500000,'bounded route samples');}}
 p.input();return {samples,groundedFraction:grounded/Math.max(samples,1),metres,simulationSeconds:(p.latest.step-began)/60,maxGroundError,blocked,...(streaming?.stats??{})};
}

test('compiled production controller traverses all three complete freight centerlines at walking pace with real terrain and bounded streaming',{timeout:240_000},async t=>{
 const seed=73129,plan=regionalTradePlan(seed),{completed}=scenarios(seed),first=plan.routes[0]!.points[0]!,initial=neighborhood(first.x,first.z).map(c=>makeCell(seed,c.cx,c.cz,completed)),p=await compiledPhysics(t,{x:first.x,z:first.z,initialCells:initial}),records=[];
 for(const route of plan.routes){const start=route.points[0]!,cells=neighborhood(start.x,start.z).map(c=>makeCell(seed,c.cx,c.cz,completed));await p.zone({x:start.x,z:start.z,initialCells:cells});const streaming=stream(p,seed,completed,cells),result=await walk(p,seed,route.points.slice(1),streaming);assert(result.groundedFraction>.999);assert(result.maxGroundError<.06,JSON.stringify(result));assert.equal(result.blocked,0);assert(result.peakResidentCells!<=9);assert(result.peakCellColliders!<600);assert(Math.abs(result.metres-route.horizontalMetres)<route.points.length*.15,'physical route agrees with geographical length within waypoint acceptance radii');assert(result.simulationSeconds>=route.horizontalMetres/1.8,'controller uses a real walking pace, not a speed cheat');records.push({id:route.id,plannedSurfaceMetres:route.surfaceMetres,...result});}
 console.log(JSON.stringify({regionalTradeCompiledPhysics:1,scope:'Actual client-build emitted production Rapier physics worker, walking all three complete routes on generated terrain with trees/rocks/shelters/V31 collectors/new source and store solids; no browser or device benchmark.',workerSha256:p.sha256,seed,routes:records}));
});

test('actual source/work docks, both collector phases and freight store solids retain support and collisions through replacement, unload and saved revisit',{timeout:120_000},async t=>{
 const seed=73129,plan=regionalTradePlan(seed),{scaffold,completed}=scenarios(seed),first=plan.sources[0]!,initial=neighborhood(first.interactionPosition.x,first.interactionPosition.z).map(c=>makeCell(seed,c.cx,c.cz,scaffold,1,'scaffold')),p=await regionalPhysics(t,{x:first.interactionPosition.x,z:first.interactionPosition.z,initialCells:initial}),records=[];
 for(const phase of ['scaffold','completed'] as const){const trade=phase==='scaffold'?scaffold:completed;
  for(const s of plan.sources){const cells=neighborhood(s.interactionPosition.x,s.interactionPosition.z).map(c=>makeCell(seed,c.cx,c.cz,trade,1,phase));await p.zone({x:s.interactionPosition.x,z:s.interactionPosition.z,initialCells:cells});const rest=await p.tick(30);assert(rest.every(s=>s.grounded));const result=await walk(p,seed,[s.workerPosition]);assert(result.groundedFraction>.999);assert(result.maxGroundError<.04);records.push({phase,source:s.id,...result});}
  for(const project of plan.projects){const at=project.interactionPosition,cells=neighborhood(at.x,at.z).map(c=>makeCell(seed,c.cx,c.cz,trade,1,phase));await p.zone({x:at.x,z:at.z,initialCells:cells});const result=await walk(p,seed,[project.workerPosition]);assert(result.groundedFraction>.999);assert(result.maxGroundError<.04);records.push({phase,builder:project.id,...result});}
  for(const c of regionalSupplyPlan(seed).outposts){const cells=neighborhood(c.deliveryPosition.x,c.deliveryPosition.z).map(v=>makeCell(seed,v.cx,v.cz,trade,1,phase));await p.zone({x:c.deliveryPosition.x,z:c.deliveryPosition.z,initialCells:cells});const result=await walk(p,seed,[{x:c.position.x+1.25,y:c.position.y,z:c.position.z+2},c.residents[0]!.workPosition]);assert(result.groundedFraction>.999);assert(result.maxGroundError<.04);records.push({phase,collector:c.id,...result});}
 }
 // Every actual new store, during scaffold and completion, stops an approaching body.
 for(const phase of ['scaffold','completed'] as const)for(const project of plan.projects){const trade=phase==='scaffold'?scaffold:completed,box=regionalTradeConstructionBoxes(seed,project.id)[0]!,at={x:box.center.x-box.half.x-2,z:box.center.z},cells=neighborhood(at.x,at.z).map(c=>makeCell(seed,c.cx,c.cz,trade,1,phase));await p.zone({...at,initialCells:cells});p.input({x:1,analog:true});const samples=await p.tick(90);p.input();const minimum=Math.min(...samples.map(s=>wildernessCapsuleClearance(s,asSolid(box))));assert(samples.every(s=>s.grounded));assert(p.latest.x<box.center.x-box.half.x-.25&&p.latest.x>at.x+.5);assert(minimum>=-.04);records.push({phase,store:project.id,samples:samples.length,minimumClearance:minimum});}
 // A real body must stop at the new store rather than merely pass a geometry check.
 const project=plan.projects[0]!,box=regionalTradeConstructionBoxes(seed,project.id)[0]!,approach={x:box.center.x-box.half.x-2,z:box.center.z},local=neighborhood(approach.x,approach.z).map(c=>makeCell(seed,c.cx,c.cz,scaffold));await p.zone({...approach,initialCells:local});p.input({x:1,analog:true});const hit=await p.tick(90);p.input();assert(p.latest.x<box.center.x-box.half.x-.25);assert(p.latest.x>approach.x+.5);const stopped=p.latest.x,minimum=Math.min(...hit.map(s=>wildernessCapsuleClearance(s,asSolid(box))));assert(minimum>=-.04);
 const campaign:State={...createRegionalState(seed),frontierTrade:completed},saved=parseSave(serializeSave(campaign))!;assert(saved);assert.deepEqual(regionalTradeObstacles(seed,saved.frontierTrade),regionalTradeObstacles(seed,completed));
 // Replace the exact local collision cells, leave them, unload, then recreate from save.
 for(const c of local){const [cx,cz]=c.key.slice(7).split(':').map(Number),replacement=makeCell(seed,cx!,cz!,completed,2);p.send({type:'cell-load',...replacement});await p.take('cell-ack',m=>m.key===c.key&&m.revision===2&&m.loaded);}
 const remote=neighborhood(1000,-1000).map(c=>makeCell(seed,c.cx,c.cz,completed,3));for(const c of remote){p.send({type:'cell-load',...c});await p.take('cell-ack',m=>m.key===c.key&&m.loaded);}p.send({type:'teleport',x:1000,z:-1000});await p.tick(10);for(const c of local){p.send({type:'cell-unload',key:c.key,revision:4});await p.take('cell-ack',m=>m.key===c.key&&!m.loaded);}await p.tick(5);assert.equal(p.latest.streaming!.terrainCells,9);
 for(const c of local){const [cx,cz]=c.key.slice(7).split(':').map(Number),restored=makeCell(seed,cx!,cz!,saved.frontierTrade!,5);p.send({type:'cell-load',...restored});await p.take('cell-ack',m=>m.key===c.key&&m.revision===5&&m.loaded);}p.send({type:'teleport',...approach});await p.tick(5);for(const c of remote){p.send({type:'cell-unload',key:c.key,revision:4});await p.take('cell-ack',m=>m.key===c.key&&!m.loaded);}p.input({x:1,analog:true});const returned=await p.tick(90);assert(returned.every(s=>s.grounded));assert(Math.abs(p.latest.x-stopped)<.005);assert.equal(p.latest.streaming!.terrainCells,9);
 console.log(JSON.stringify({regionalTradeTerrainPhysics:1,scope:'Production controller at actual generated source/work/collector/store positions, V31 scaffold and completed envelope, atomic collider replacement and true unload/saved reload. No browser visual or device benchmark.',seed,probes:records,minimumStoreClearance:minimum,storeColliderReloadExact:true,residentTerrainCells:p.latest.streaming!.terrainCells}));
});
