import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three/webgpu';
import {generateRegionalChunk,regionalPlan} from '../src/regional-world.ts';import {createRegionalView} from '../src/regional-view.ts';
test('regional wilderness batches rather than rendering one mesh per branch, and disposes evicted GPU buffers',()=>{const chunk=generateRegionalChunk(73129,-11,9),view=createRegionalView();let released=0,created=0,maxMeshes=0;for(let i=0;i<60;i++){const group=view.make(chunk);let meshes=0;group.traverse(o=>{if(o instanceof THREE.Mesh){created++;meshes++;o.geometry.addEventListener('dispose',()=>released++);}});maxMeshes=Math.max(maxMeshes,meshes);view.commit('region:-11:9',group);assert.equal(view.count,1);assert.equal(view.root.children.length,1);assert.equal(view.featureCount,chunk.features.length);}view.unload('region:-11:9');assert.equal(view.count,0);assert.equal(view.root.children.length,0);assert.equal(view.featureCount,0);assert.equal(released,created);assert(maxMeshes<chunk.features.length*2+chunk.structures.length+5);});
test('regional debug collision geometry is opt-in and is disposed on eviction',()=>{const chunk=generateRegionalChunk(42,10,-10),view=createRegionalView(),group=view.make(chunk);view.commit('test',group);assert.equal(group.getObjectByName('regional-collision-debug'),undefined);view.setDebug(true);const outline=group.getObjectByName('regional-collision-debug')!;assert(outline);let disposed=0;outline.traverse(o=>{if(o instanceof THREE.LineSegments)o.geometry.addEventListener('dispose',()=>disposed++);});view.setDebug(false);assert.equal(outline.visible,false);view.unload('test');assert(disposed>0);});
test('regional harvest removes only removable rocks and keeps depleted tree and large-rock instances',()=>{const chunk=Array.from({length:12},(_,i)=>generateRegionalChunk(73129,i+4,-10)).find(c=>c.features.some(f=>f.removable)&&c.features.some(f=>!f.removable&&f.harvestable))!,view=createRegionalView(),removable=chunk.features.find(f=>f.removable),standing=chunk.features.find(f=>!f.removable&&f.harvestable);assert(removable&&standing);const state={version:1 as const,generation:2 as const,seed:73129,harvested:[removable.id,standing.id],wood:0,stone:0};view.commit('test',view.make(chunk,state));assert.equal(view.featureCount,chunk.features.length-1);view.clear();assert.equal(view.featureCount,0);});


test('nearby shelter roof cutaway reveals interior without changing any physical shape and restores above or away',()=>{
 const seed=73129,site=regionalPlan(seed).sites.find(s=>s.kind==='outpost')!,[cx,cz]=site.ownerChunk.split(':').map(Number),chunk=generateRegionalChunk(seed,cx!,cz!),view=createRegionalView();
 const original=JSON.stringify(chunk.structures),group=view.make(chunk);view.commit(chunk.key,group);
 const roof=group.getObjectByName(site.id+'/structure/roof')!;assert(roof);const shape=chunk.structures.find(s=>s.id===roof.name)!;
 assert.equal(roof.visible,true);view.update(0,false,{x:shape.center.x,y:site.position.y,z:shape.center.z+2.2});assert.equal(roof.visible,false);
 assert.equal(JSON.stringify(chunk.structures),original);assert.equal(group.userData.solids.length,chunk.structures.filter(s=>s.solid).length+chunk.features.flatMap(f=>f.solids).length);
 view.update(0,false,{x:shape.center.x,y:shape.center.y+shape.half.y,z:shape.center.z});assert.equal(roof.visible,true);
 view.update(0,false,{x:shape.center.x+30,y:site.position.y,z:shape.center.z});assert.equal(roof.visible,true);
 view.update(0,false,{x:shape.center.x,y:site.position.y,z:shape.center.z});assert.equal(roof.visible,false);view.update(0,false);assert.equal(roof.visible,true);view.clear();
});
