import test from 'node:test';
import assert from 'node:assert/strict';
import {createRegionalFood,enableRegionalFood,advanceRegionalFood,applyRegionalFoodCommand,observeRegionalFoodTrade,regionalFoodPlan,regionalFoodInteractions,regionalFoodActorPoses,regionalFoodConservation,regionalFoodSummary,validRegionalFood,validRegionalFoodCommand,immutableRegionalFood,REGIONAL_FOOD_MAX_TICKS,type RegionalFoodContext,type RegionalFoodState,type RegionalFoodCommand} from '../src/regional-food.ts';
import {createRegionalSupply,advanceRegionalSupply,applyRegionalSupplyCommand,regionalSupplyPlan,regionalSupplyLocalSources,regionalSupplyOutpostAt,immutableRegionalSupply,type RegionalSupplyState} from '../src/regional-supply.ts';
import {createRegionalTrade,advanceRegionalTrade,applyRegionalTradeCommand,regionalTradePlan,regionalTradeCommandPosition,regionalTradeDrainTicks,regionalTradeReplayTimeline,regionalTradeCanonical,immutableRegionalTrade,type RegionalTradeState,type RegionalTradeCommand} from '../src/regional-trade.ts';
import {immutableWildernessState,type WildernessState} from '../src/wilderness-state.ts';
const seed=73129,identity={generation:2 as const,seed,regional:{version:1 as const}},clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
let fixture:{supply:RegionalSupplyState;trade:RegionalTradeState;wilderness:WildernessState}|undefined;
function earned(){
 if(fixture)return fixture;
 const ids=new Set<string>(),totals={wood:0,stone:0};for(const p of regionalSupplyPlan(seed).outposts){const local=regionalSupplyLocalSources(seed,p.id);for(const material of ['wood','stone'] as const)for(const id of local[material])if(!ids.has(id)){ids.add(id);totals[material]++;}}
 const wilderness=immutableWildernessState({version:1,generation:2,seed,harvested:[...ids],...totals},identity);let supply=createRegionalSupply(seed),trade=createRegionalTrade(seed,1);
 for(const p of regionalSupplyPlan(seed).outposts){const ctx={...identity,zone:'valley',player:{x:p.deliveryPosition.x,z:p.deliveryPosition.z,hp:100},feetY:p.position.y,grounded:true,wilderness};for(const type of ['deliver','build'] as const)supply=applyRegionalSupplyCommand(supply,ctx,{type,outpostId:p.id,expectedRevision:supply.revision}).state;}
 for(let i=0;i<600;i++)supply=advanceRegionalSupply(supply,1);
 const plan=regionalTradePlan(seed),issue=(type:RegionalTradeCommand['type'],i:number)=>{const targetId=(type==='start-source'?plan.sources:type==='clear-route'?plan.routes:plan.projects)[i]!.id,command={type,targetId,expectedRevision:trade.revision},p=regionalTradeCommandPosition(seed,command)!;trade=applyRegionalTradeCommand(trade,{...identity,zone:'valley',player:{x:p.x,z:p.z,hp:100},feetY:p.y,grounded:true},command).state;};
 for(let i=0;i<3;i++){issue('start-source',i);issue('clear-route',i);}
 for(let n=0;n<20_000&&!trade.routes.every(r=>r.activity==='finished');n++){for(let i=0;i<3;i++)if(trade.routes[i]!.buildStartedAt===null&&trade.routes[i]!.destinationStock>=4)issue('build-store',i);trade=advanceRegionalTrade(trade,1);}
 assert(trade.routes.every(r=>r.activity==='finished'));assert(supply.outposts.every(o=>o.spilled>0));return fixture={supply,trade,wilderness};
}
function ready(build=true){const e=earned(),supply=build?e.supply:createRegionalSupply(seed),p=regionalFoodPlan(seed).farms[0]!.interactionPosition,ctx:RegionalFoodContext={...identity,zone:'valley',player:{x:p.x,z:p.z,hp:100},feetY:p.y,grounded:true,wilderness:e.wilderness,frontierSupply:supply,frontierTrade:e.trade};return {food:createRegionalFood(seed,supply,earned().trade),ctx};}
function command(food:RegionalFoodState,ctx:RegionalFoodContext,type:RegionalFoodCommand['type']='start-farm',i=0){const p=regionalFoodPlan(seed).farms[i]!,c={type,targetId:p.id,expectedRevision:food.revision};return applyRegionalFoodCommand(food,{...ctx,player:{x:p.interactionPosition.x,z:p.interactionPosition.z,hp:100},feetY:p.interactionPosition.y},c).state;}
function step(food:RegionalFoodState,ctx:RegionalFoodContext,dt=1){const next={...ctx,frontierSupply:advanceRegionalSupply(ctx.frontierSupply!,dt),frontierTrade:advanceRegionalTrade(ctx.frontierTrade!,dt)};return {food:advanceRegionalFood(food,dt,next),ctx:next};}
function run(food:RegionalFoodState,ctx:RegionalFoodContext,seconds:number,dt=1){for(let i=0;i<seconds/dt;i++)({food,ctx}=step(food,ctx,dt));return {food,ctx};}
function check(food:RegionalFoodState,ctx:RegionalFoodContext){assert(validRegionalFood(food,ctx));assert(validRegionalFood(clone(food),ctx));assert(regionalFoodConservation(food).every(f=>f.balanced));return immutableRegionalFood(clone(food),ctx);}

test('migration preserves mature source clocks but historical overflow is not food inventory',()=>{
 const {food,ctx}=ready();assert.equal(food.ticks,0);assert.equal(food.remainder,0);assert.equal(food.supplyStartTick,ctx.frontierSupply!.ticks);for(const f of food.farms){assert(f.sourceSpilled>0);assert.equal(f.water,0);assert.equal(f.waterCaptured,0);assert.equal(f.starterGranted,0);assert.equal(f.seeds,2);}check(food,ctx);
 const enabled=enableRegionalFood(ctx);assert('frontierFood' in enabled);assert.equal(enabled.frontierSupply,ctx.frontierSupply);assert.equal(enabled.frontierTrade,ctx.frontierTrade);assert.equal(enableRegionalFood(enabled),enabled);for(const frontierFood of [null,false,undefined,{}]){const old={...ctx,frontierFood} as any;assert.equal(enableRegionalFood(old),old);}
});
test('starter meals are allocated exactly once at a completed store and require a real local retrieval',()=>{
 let {food,ctx}=ready(false);const base=food;food=command(food,ctx);assert.equal(food.revision,1);assert.equal(food.farms[0]!.store,4);assert.equal(food.farms[0]!.starterGranted,4);assert.equal(food.farms[0]!.meals,0);assert.equal(command(food,ctx),food);assert.equal(command(base,{...ctx,frontierTrade:createRegionalTrade(seed,1)}),base);
 const phases=new Set<string>();for(let i=0;i<220;i++){({food,ctx}=step(food,ctx,.25));phases.add(food.farms[0]!.activity);assert(regionalFoodConservation(food).every(r=>r.balanced));}
 const f=food.farms[0]!;assert.equal(f.harvested,0);assert.equal(f.waterCaptured,0);assert.equal(f.meals,2);assert(f.farmer.meals===1&&f.carrier.meals===1);assert(f.farmer.hunger<75);assert(phases.has('outbound')&&phases.has('eating')&&phases.has('returning'));check(food,ctx);
});
test('new overflow grows real yield then reserves loads, travels, unloads and feeds hungry workers',()=>{
 let {food,ctx}=ready();for(let i=0;i<3;i++)food=command(food,ctx,'start-farm',i);const phases=new Set<string>();let firstHarvest=0,firstDelivery=0;const initialSupply=ctx.frontierSupply;
 for(let i=0;i<2400;i++){const before=food;({food,ctx}=step(food,ctx,.25));for(let n=0;n<3;n++){const f=food.farms[n]!,p=regionalFoodPlan(seed).farms[n]!;phases.add(f.activity);assert(Math.abs(f.distance-before.farms[n]!.distance)<=p.speed*.25+1e-6);assert(f.water<=6);assert(f.store<=8);assert.equal(f.seeds+(f.crop==='empty'?0:1),2);}assert(regionalFoodConservation(food).every(f=>f.balanced));if(!firstHarvest&&food.farms[0]!.harvested)firstHarvest=food.ticks;if(!firstDelivery&&food.farms[0]!.delivered)firstDelivery=food.ticks;}
 assert.notEqual(ctx.frontierSupply,initialSupply);assert(firstDelivery>firstHarvest);assert(['loading','outbound','unloading','eating','returning','idle'].every(a=>phases.has(a)));for(const f of food.farms){assert(f.harvests>4);assert(f.delivered>12);assert(f.meals>5);assert(f.waterUsed===f.seedsSown*2);assert.equal(f.harvested,f.harvests*4);assert.equal(f.seedsReturned,f.harvests);assert(f.farmer.service>0&&f.carrier.service>0);}check(food,ctx);assert(JSON.stringify(food).length<45000);
});
test('distinct crop help earns finite exactly-once stewardship while crops renew without player spam',()=>{
 let {food,ctx}=ready();for(let i=0;i<3;i++)food=command(food,ctx,'start-farm',i);const seen=new Set<string>();
 for(let t=0;t<2400&&food.farms.some(f=>f.tended<4);t++){for(let i=0;i<3;i++){const f=food.farms[i]!,p=regionalFoodPlan(seed).farms[i]!,job=regionalFoodInteractions(seed,food,ctx).find(j=>j.farmId===p.id&&j.kind==='tend-crop')!;if(job.enabled){const key=`${p.id}:${f.harvests}`;assert(!seen.has(key));seen.add(key);const old=food;food=command(food,ctx,'tend-crop',i);assert.equal(food.revision,old.revision+1);assert.equal(food.farms[i]!.growth,old.farms[i]!.growth+16);assert.equal(command(food,ctx,'tend-crop',i),food);}}({food,ctx}=step(food,ctx));}
 assert.equal(food.revision,15);assert.equal(food.farms.reduce((n,f)=>n+f.stewardship,0),12);assert.equal(food.receipts.length,15);check(food,ctx);const old=food.farms.map(f=>f.harvests);({food,ctx}=run(food,ctx,300));for(let i=0;i<3;i++){assert(food.farms[i]!.harvests>old[i]!);assert.equal(food.farms[i]!.stewardship,4);}check(food,ctx);
});
test('exact active clocks, fractional rollout, pause, dt clamp and reload cannot mint source time',()=>{
 let {food,ctx}=ready();ctx={...ctx,frontierSupply:advanceRegionalSupply(ctx.frontierSupply!,.13)};food=createRegionalFood(seed,ctx.frontierSupply!,ctx.frontierTrade!);food=command(food,ctx);
 let a={food,ctx},b={food,ctx};a=run(a.food,a.ctx,60,1);b=run(b.food,b.ctx,60,.1);assert.deepEqual(a.food,b.food);assert.deepEqual(a.ctx.frontierSupply!.outposts,b.ctx.frontierSupply!.outposts);assert(Math.abs(a.ctx.frontierSupply!.remainder-b.ctx.frontierSupply!.remainder)<1e-12);check(a.food,a.ctx);
 for(const dt of [0,-1,NaN,Infinity])assert.equal(advanceRegionalFood(food,dt,ctx),food);assert.equal(advanceRegionalFood(food,1,ctx),food);const huge=step(food,ctx,1e8),one=step(food,ctx,1);assert.deepEqual(huge.food,one.food);const lag=clone(a.food);lag.ticks--;assert(!validRegionalFood(lag,a.ctx));assert(!validRegionalFood(food,a.ctx));
 const reload=check(a.food,a.ctx);assert.deepEqual(run(reload,a.ctx,12),run(a.food,a.ctx,12));
});
test('strict replay rejects forged water, food, seeds, hunger, rewards, clocks and accessor laundering',()=>{
 let {food,ctx}=ready();food=command(food,ctx);({food,ctx}=run(food,ctx,200));check(food,ctx);
 const mutate:((s:any)=>void)[]=[s=>s.extra=1,s=>s.seed++,s=>s.ticks++,s=>s.remainder=.25,s=>s.supplyStartTick--,s=>s.farms[0].water++,s=>s.farms[0].waterCaptured++,s=>s.farms[0].waterUsed++,s=>s.farms[0].sourceSpilled++,s=>s.farms[0].seeds++,s=>s.farms[0].stock++,s=>s.farms[0].reserved++,s=>s.farms[0].cargo++,s=>s.farms[0].store++,s=>s.farms[0].meals++,s=>s.farms[0].farmer.hunger=0,s=>s.farms[0].farmer.service++,s=>s.farms[0].starterGranted++,s=>s.farms[0].stewardship++,s=>s.farms.reverse(),s=>s.tradeBaseline.routes[0].builtAt=1,s=>s.receipts.push(s.receipts[0])];
 for(const m of mutate){const bad=clone(food);m(bad);assert.equal(validRegionalFood(bad,ctx),false);assert.equal(advanceRegionalFood(bad,.01,ctx),bad);assert.throws(()=>immutableRegionalFood(bad,ctx));}
 let called=false;const bad=clone(food);Object.defineProperty(bad.receipts[0],'type',{get(){called=true;throw Error('getter');}});assert.equal(validRegionalFood(bad,ctx),false);assert.equal(called,false);const cmd={type:'start-farm',targetId:food.farms[0]!.id,expectedRevision:0};assert(validRegionalFoodCommand(cmd));assert(!validRegionalFoodCommand({...cmd,bonus:1}));
});
test('late collector build after long hungry garden idle is valid and never skipped across a source event',()=>{
 let {food,ctx}=ready(false);food=command(food,ctx);({food,ctx}=run(food,ctx,750));const p=regionalSupplyPlan(seed).outposts.find(p=>p.id===regionalFoodPlan(seed).farms[0]!.siteId)!;
 const local={...ctx,player:{x:p.deliveryPosition.x,z:p.deliveryPosition.z,hp:100},feetY:p.deliveryPosition.y};let supply=ctx.frontierSupply!;for(const type of ['deliver','build'] as const)supply=applyRegionalSupplyCommand(supply,local,{type,outpostId:p.id,expectedRevision:supply.revision}).state;ctx={...ctx,frontierSupply:supply};assert(validRegionalFood(food,ctx),'same-tick supply build');assert(validRegionalFood(clone(food),ctx),'same-tick raw build');
 ({food,ctx}=run(food,ctx,500));assert(food.farms[0]!.harvested>0);check(food,ctx);
});
test('saturated old supply allows only finite pantry use; cold maximum food clocks replay in bounded work',()=>{
 const e=earned(),raw=clone(createRegionalSupply(seed));raw.ticks=REGIONAL_FOOD_MAX_TICKS;for(const o of raw.outposts)for(const r of o.residents){r.thirst=100;r.thirstOverflow=60+raw.ticks*.03-100;}const supply=immutableRegionalSupply(raw,{...identity,wilderness:e.wilderness,frontierTrade:e.trade});let {ctx}=ready(false);ctx={...ctx,frontierSupply:supply};let food=createRegionalFood(seed,supply,earned().trade);food=command(food,ctx);({food,ctx}=run(food,ctx,500));assert.equal(food.farms[0]!.harvested,0);assert.equal(food.farms[0]!.waterCaptured,0);assert.equal(food.farms[0]!.meals,4);check(food,ctx);
 const huge=clone(createRegionalFood(seed,supply,earned().trade));huge.ticks=REGIONAL_FOOD_MAX_TICKS;for(const f of huge.farms)for(const a of [f.farmer,f.carrier]){a.hunger=100;a.hungerOverflow=Math.floor(huge.ticks/12)-40;}
 huge.tradeEvents=[{type:'rebase',ticks:REGIONAL_FOOD_MAX_TICKS-regionalTradeDrainTicks(seed)-huge.tradeBaseline.ticks,remainder:0}];huge.tradeSnapshot=regionalTradeReplayTimeline(huge.tradeBaseline,huge.tradeEvents,{ticks:huge.ticks,remainder:0})!;const hugeCtx={...ctx,frontierTrade:huge.tradeSnapshot};const at=performance.now();assert(validRegionalFood(huge,hugeCtx));assert(performance.now()-at<1500);assert(JSON.stringify(huge).length<9000);
 const frozen=immutableRegionalFood(huge,hugeCtx);assert(!validRegionalFood(frozen,{...hugeCtx,frontierTrade:frozen.tradeBaseline}),'terminal trade clock cannot roll back before its reachable canonical checkpoint');const laterTrade=advanceRegionalTrade(huge.tradeSnapshot,1),laterCtx={...hugeCtx,frontierTrade:laterTrade};assert.equal(advanceRegionalFood(frozen,1,laterCtx),frozen);assert(validRegionalFood(frozen,laterCtx));assert.equal(command(frozen,laterCtx),frozen);assert.equal(regionalFoodSummary(frozen,seed,frozen.farms[0]!.id)!.phase,'paused');assert(regionalFoodActorPoses(seed,frozen).every(a=>a.speed===0&&a.activity==='paused'));const target=regionalTradePlan(seed).projects[0]!.id,c={type:'withdraw-reserve' as const,targetId:target,expectedRevision:laterTrade.revision},position=regionalTradeCommandPosition(seed,c)!,withdrawn=applyRegionalTradeCommand(laterTrade,{...laterCtx,player:{x:position.x,z:position.z,hp:100},feetY:position.y},c).state;assert.notEqual(withdrawn,laterTrade);const observed=observeRegionalFoodTrade(frozen,{...laterCtx,frontierTrade:withdrawn},c)!;assert(observed);assert.deepEqual(observed.farms,frozen.farms);assert.deepEqual(observed.tradeEvents,frozen.tradeEvents);assert(validRegionalFood(observed,{...laterCtx,frontierTrade:withdrawn}));const earlyCommand={...c,expectedRevision:frozen.tradeBaseline.revision},early=applyRegionalTradeCommand(frozen.tradeBaseline,{...laterCtx,player:{x:position.x,z:position.z,hp:100},feetY:position.y},earlyCommand).state,lateRaw=clone(early);lateRaw.ticks=huge.tradeSnapshot.ticks+10000;const impossible=immutableRegionalTrade(lateRaw,identity);assert(!validRegionalFood(frozen,{...hugeCtx,frontierTrade:impossible}),'a post-checkpoint command cannot be backdated before the canonical checkpoint');
});
test('stable six actor identities expose the exact carrier path scalar and true meal cargo',()=>{
 let {food,ctx}=ready();const original=regionalFoodActorPoses(seed,food);assert.equal(new Set(original.map(a=>a.id)).size,6);food=command(food,ctx);({food,ctx}=run(food,ctx,120));const poses=regionalFoodActorPoses(seed,food);assert.deepEqual(poses.map(a=>a.id),original.map(a=>a.id));const carrier=poses[1]!;assert.equal(carrier.distance,food.farms[0]!.distance);assert.equal(carrier.carrying,food.farms[0]!.cargo+food.farms[0]!.returnMeal+food.farms[0]!.carrierMeal);assert.equal(carrier.pathId,food.farms[0]!.id+'/delivery');assert(regionalFoodSummary(food,seed,food.farms[0]!.id)!.meals>0);
});


test('cold 1e9 active-tick replay is bounded for all started farms and never crosses the source ceiling',{timeout:120_000},async(t)=>{
 const {mkdtemp,writeFile,readFile,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{pathToFileURL}=await import('node:url');
 const e=earned();
 // Supply helper rejects invented present snapshots; derive future source with its existing
 // deterministic replay from a test-only module seam instead of trusting invented totals.
 const dir=await mkdtemp(join(tmpdir(),'axiom-food-replay-'));
 try{
  const supplyText=await readFile(new URL('../src/regional-supply.ts',import.meta.url),'utf8');
  const rewrite=(text:string,source:string)=>text.replace(/from '(.\/[^']+)'/g,(_m,relative)=>`from '${new URL(relative,new URL(source,import.meta.url)).href}'`);
  const supplyModule=join(dir,'supply.ts');await writeFile(supplyModule,rewrite(supplyText,'../src/regional-supply.ts')+"\nexport function testFuture(source,end){return {...source,ticks:end,remainder:0,outposts:source.outposts.map(o=>replayOutpost(regionalSupplyPlan(source.seed).outposts.find(p=>p.id===o.id),o.buildStartedAt,end,o.delivered))};}\n");
  const future=(await import(pathToFileURL(supplyModule).href)).testFuture(e.supply,REGIONAL_FOOD_MAX_TICKS);const supply=immutableRegionalSupply(future,{...identity,wilderness:e.wilderness,frontierTrade:e.trade});
  let {food,ctx}=ready();for(let i=0;i<3;i++)food=command(food,ctx,'start-farm',i);food=clone(food);food.tradeEvents=[{type:'rebase',ticks:REGIONAL_FOOD_MAX_TICKS-regionalTradeDrainTicks(seed)-food.tradeBaseline.ticks,remainder:0}];ctx={...ctx,frontierSupply:supply};
  const text=await readFile(new URL('../src/regional-food.ts',import.meta.url),'utf8'),module=join(dir,'food.ts');await writeFile(module,rewrite(text,'../src/regional-food.ts')+"\nexport function testFuture(template,supply,end){const s=pristine(template.seed,supply,template.tradeBaseline,template.supplyStartTick,template.supplyStartRemainder),p=regionalFoodPlan(s.seed);for(const r of template.receipts){runTo(s,supply,r.tick);const i=p.farms.findIndex(f=>f.id===r.targetId);execute(s.farms[i],p.farms[i],r.tick,r.type);}runTo(s,supply,end);s.revision=template.revision;s.receipts=copy(template.receipts);s.tradeEvents=copy(template.tradeEvents);s.tradeSnapshot=regionalTradeReplayTimeline(s.tradeBaseline,s.tradeEvents,{ticks:end,remainder:0});return s;}\n");
  const at=performance.now(),huge=(await import(pathToFileURL(module).href)).testFuture(food,supply,REGIONAL_FOOD_MAX_TICKS);ctx={...ctx,frontierTrade:huge.tradeSnapshot};t.diagnostic(`Generated billion-tick active snapshot in ${(performance.now()-at).toFixed(1)} ms`);assert(huge.farms.every((f:any)=>f.harvested>1_000_000));assert(regionalFoodConservation(huge).every(f=>f.balanced));for(const f of huge.farms){const p=regionalFoodPlan(seed).farms.find(p=>p.id===f.id)!;assert.equal(f.sourceSpilled,supply.outposts.find(o=>o.id===p.siteId)!.spilled);}
  const coldModule=await import(`../src/regional-food.ts?cold=${Date.now()}`),cold=performance.now();assert(coldModule.validRegionalFood(huge,ctx));t.diagnostic(`Cold replay ${(performance.now()-cold).toFixed(1)} ms; ${JSON.stringify(huge).length} saved bytes`);assert(performance.now()-cold<30_000);assert(JSON.stringify(huge).length<45000);const repeat=performance.now();for(let i=0;i<10;i++)assert(coldModule.validRegionalFood(clone(huge),ctx));t.diagnostic(`Ten cached raw JSON validations ${(performance.now()-repeat).toFixed(1)} ms`);const forged=clone(huge);forged.farms[0].waterUsed++;assert(!coldModule.validRegionalFood(forged,ctx));
 }finally{await rm(dir,{recursive:true,force:true});}
});


test('post-rollout freight witnesses prove late store completion and survive later unrelated trade commands',()=>{
 let {ctx}=ready();ctx={...ctx,frontierTrade:createRegionalTrade(seed,1)};let food=createRegionalFood(seed,ctx.frontierSupply!,ctx.frontierTrade!);assert.equal(command(food,ctx),food);
 const issue=(type:RegionalTradeCommand['type'],i:number)=>{const plan=regionalTradePlan(seed),targetId=(type==='start-source'?plan.sources:type==='clear-route'?plan.routes:plan.projects)[i]!.id,c={type,targetId,expectedRevision:ctx.frontierTrade!.revision},p=regionalTradeCommandPosition(seed,c)!,trade=applyRegionalTradeCommand(ctx.frontierTrade!,{...ctx,player:{x:p.x,z:p.z,hp:100},feetY:p.y},c).state;assert.notEqual(trade,ctx.frontierTrade);ctx={...ctx,frontierTrade:trade};const next=observeRegionalFoodTrade(food,ctx,c);assert(next);food=next;};
 issue('start-source',0);issue('clear-route',0);for(let i=0;i<6000&&ctx.frontierTrade!.routes[0]!.destinationStock<4;i++)({food,ctx}=step(food,ctx));assert.equal(ctx.frontierTrade!.routes[0]!.destinationStock,4);issue('build-store',0);assert.equal(command(food,ctx),food);({food,ctx}=run(food,ctx,16));food=command(food,ctx);assert.equal(food.revision,1);check(food,ctx);const start=food.receipts[0]!.tick;assert(start>0);
 issue('start-source',1);check(food,ctx);assert.equal(food.tradeEvents.length,4);({food,ctx}=run(food,ctx,150));check(food,ctx);
 const backdated=clone(food);backdated.receipts[0]!.tick=0;backdated.receipts[0]!.remainder=0;backdated.farms[0]!.startedAt=0;assert(!validRegionalFood(backdated,ctx));const futureBaseline=clone(food);futureBaseline.tradeBaseline=clone(ctx.frontierTrade!);futureBaseline.tradeEvents=[];assert(!validRegionalFood(futureBaseline,ctx));
});
test('eligible live and zero-elapsed freight rebases have exact bounded chronology witnesses',()=>{
 for(const tiny of [false,true]){const e=earned(),raw=clone(e.trade);raw.ticks=REGIONAL_FOOD_MAX_TICKS-regionalTradeDrainTicks(seed)-(tiny?0:4);const trade=immutableRegionalTrade(raw,identity);let {ctx}=ready();ctx={...ctx,frontierTrade:trade};let food=createRegionalFood(seed,ctx.frontierSupply!,trade);food=command(food,ctx);
 if(tiny)({food,ctx}=step(food,ctx,1e-14));else ({food,ctx}=run(food,ctx,2));assert.equal(food.tradeEvents.filter(e=>e.type==='rebase').length,1);assert(ctx.frontierTrade!.ticks<1_000_000);check(food,ctx);if(tiny)assert.equal(food.ticks,0);
 const invented=clone(food);invented.tradeEvents.unshift({type:'rebase',ticks:0,remainder:0});assert(!validRegionalFood(invented,ctx));}
});
test('shared split clocks do not drift across twenty thousand quarter-boundary frames with unequal rollout phases',{timeout:120_000},()=>{
 for(const dt of [.25000000005,.24999999995]){const baseSeed=42,p=regionalFoodPlan(baseSeed).farms[0]!.interactionPosition;let ctx:RegionalFoodContext={generation:2,seed:baseSeed,regional:{version:1},zone:'valley',player:{x:p.x,z:p.z,hp:100},feetY:p.y,grounded:true,frontierSupply:advanceRegionalSupply(createRegionalSupply(baseSeed),.13),frontierTrade:createRegionalTrade(baseSeed,1)};let food=createRegionalFood(baseSeed,ctx.frontierSupply!,ctx.frontierTrade!);for(let i=0;i<20_000;i++)({food,ctx}=step(food,ctx,dt));assert(food.ticks>19_990);check(food,ctx);}
});


test('terminal continuation cannot prematurely canonicalize pending work before an eligible future rebase',()=>{
 const raw=clone(createRegionalSupply(seed));raw.ticks=REGIONAL_FOOD_MAX_TICKS;for(const o of raw.outposts)for(const r of o.residents){r.thirst=100;r.thirstOverflow=60+raw.ticks*.03-100;}const trade=createRegionalTrade(seed,1),ctxBase={...identity,frontierTrade:trade},supply=immutableRegionalSupply(raw,ctxBase),food=clone(createRegionalFood(seed,supply,trade)),horizon=regionalTradeDrainTicks(seed),plan=regionalTradePlan(seed);
 food.ticks=REGIONAL_FOOD_MAX_TICKS;food.tradeEvents=[{type:'rebase',ticks:REGIONAL_FOOD_MAX_TICKS-horizon,remainder:0},{type:'command',ticks:REGIONAL_FOOD_MAX_TICKS-1,remainder:0,command:{type:'start-source',targetId:plan.sources[0]!.id}}];food.tradeSnapshot=regionalTradeReplayTimeline(trade,food.tradeEvents,{ticks:food.ticks,remainder:0})!;for(const f of food.farms)for(const a of [f.farmer,f.carrier]){a.hunger=100;a.hungerOverflow=Math.floor(food.ticks/12)-40;}
 const ctx={...ctxBase,frontierSupply:supply,frontierTrade:food.tradeSnapshot};assert(validRegionalFood(food,ctx));assert.equal(food.tradeSnapshot.routes[0]!.remaining,12);const prematurelyRebased=regionalTradeCanonical(food.tradeSnapshot)!;assert.equal(prematurelyRebased.routes[0]!.remaining,12);assert(!validRegionalFood(food,{...ctx,frontierTrade:prematurelyRebased}));
 const direct=advanceRegionalTrade(food.tradeSnapshot,1);assert(validRegionalFood(food,{...ctx,frontierTrade:direct}));const wait={ticks:REGIONAL_FOOD_MAX_TICKS-horizon-food.tradeSnapshot.ticks,remainder:0},future=regionalTradeReplayTimeline(food.tradeSnapshot,[{type:'rebase',...wait}],wait)!;assert.equal(future.routes[0]!.remaining,0);assert(validRegionalFood(food,{...ctx,frontierTrade:future}));
 const c={type:'clear-route' as const,targetId:plan.routes[0]!.id,expectedRevision:food.tradeSnapshot.revision},p=regionalTradeCommandPosition(seed,c)!,clearing=applyRegionalTradeCommand(food.tradeSnapshot,{...identity,zone:'valley',player:{x:p.x,z:p.z,hp:100},feetY:p.y,grounded:true},c).state,afterClear=regionalTradeReplayTimeline(clearing,[{type:'rebase',...wait}],wait)!;assert(afterClear.routes[0]!.delivered>0);assert(validRegionalFood(food,{...ctx,frontierTrade:afterClear}));
});
