import test from 'node:test';
import assert from 'node:assert/strict';
import {AxiomRegistry} from '../src/procedural.ts';
import {compileRestorationBody,compileRestorationDock,DEFAULT_RESTORATION_RECIPE,RESTORATION_BODY_LIMITS,RESTORATION_BODY_MANIFEST,RESTORATION_PARTS,RESTORATION_STAT_DESCRIPTORS,parseRestorationBodyRecipe,registerRestorationBody,restorationBodyRegistry,restorationRefitLedger,validRestorationBodyRecipe,type RestorationBodyRecipe} from '../src/restoration-body.ts';
const input=(patch:Partial<RestorationBodyRecipe>={}):RestorationBodyRecipe=>({...DEFAULT_RESTORATION_RECIPE,...patch});
const variants=RESTORATION_PARTS.support.flatMap(support=>RESTORATION_PARTS.shell.flatMap(shell=>RESTORATION_PARTS.organ.map(organ=>input({support,shell,organ}))));
test('all body parts and edge seeds compile bounded deterministic data-only graphs',()=>{
 for(const recipe of variants)for(const seed of [0,1,17,73129,0xffffffff]){
  const p=compileRestorationBody({...recipe,seed});assert.deepEqual(p,compileRestorationBody({...recipe,seed}));assert.ok(p.plan.valid);assert.ok(p.plan.constraints.every(c=>c.ok));assert.equal(p.plan.nodes.length,16);assert.ok(p.plan.shapes.length<=80);assert.ok(p.budget.nodes<=RESTORATION_BODY_LIMITS.nodes);assert.equal(p.budget.shapes,p.plan.shapes.length);assert.deepEqual(p,JSON.parse(JSON.stringify(p)));assert.equal(Object.isFrozen(p),true);assert.equal(Object.isFrozen(p.legs[0]!.hip),true);assert.equal(p.plan.recipe.version,1);assert.equal(p.bounds.minY,0);assert.ok(p.bounds.radius<1.3);
 }
});
test('seed changes physical geometry and sensor stats, not just IDs',()=>{
 const a=compileRestorationBody(input({seed:1})),b=compileRestorationBody(input({seed:2}));assert.notDeepEqual(a.body,b.body);assert.notEqual(a.stats.sensorRange,b.stats.sensorRange);assert.notDeepEqual(a.plan.shapes.map(s=>[s.key,s.center,s.half]),b.plan.shapes.map(s=>[s.key,s.center,s.half]));assert.notEqual(a.ref.recipeHash,b.ref.recipeHash);assert.notEqual(compileRestorationBody(input({shell:'alloy'})).ref.recipeHash,a.ref.recipeHash);
});
test('four named two-link supports have grounded contacts and paired alternating phases',()=>{
 for(const recipe of variants){const p=compileRestorationBody(recipe);assert.deepEqual(p.legs.map(l=>l.id),['front-left','front-right','back-left','back-right']);assert.equal(p.legs.filter(l=>l.phase===0).length,2);assert.equal(p.legs.filter(l=>l.phase===.5).length,2);for(const leg of p.legs){assert.ok(Math.abs(leg.hip.y-leg.knee.y-leg.upper)<1e-12);assert.ok(Math.abs(leg.knee.y-leg.foot.y-leg.lower)<1e-12);assert.equal(leg.foot.y,.04);for(const node of Object.values(leg.nodes))assert.ok(p.plan.nodes.some(n=>n.key===node));const exposure=p.plan.exposed.find(e=>e.key===`${leg.id}-contact`)!;assert.equal(exposure.port.type,'spatial');assert.equal(exposure.port.position.y,0);}}
});
test('every required attachment/work socket joins safely; support protocol is typed',()=>{
 for(const recipe of variants){const p=compileRestorationBody(recipe),ports=p.plan.nodes.flatMap(n=>n.ports),used=new Set<string>();for(const edge of p.plan.connections){const a=ports.find(p=>p.id===edge.from)!,b=ports.find(p=>p.id===edge.to)!;assert.ok(!used.has(a.id)&&!used.has(b.id));used.add(a.id);used.add(b.id);assert.equal(a.type,b.type);assert.equal(a.protocol,b.protocol);assert.equal(a.unit,b.unit);if(edge.type==='attachment'){for(const key of ['x','y','z'] as const){assert.ok(Math.abs(a.position[key]-b.position[key])<1e-12);assert.ok(Math.abs(a.facing[key]+b.facing[key])<1e-12);}}}for(const port of ports.filter(p=>p.required))assert.ok(used.has(port.id));assert.equal(p.plan.connections.filter(c=>c.adapter==='restoration/support').length,12);for(const type of ['attachment','fluid','work'])assert.ok(ports.some(p=>p.type===type));assert.deepEqual(p.sockets.emitter,p.plan.exposed.find(e=>e.key==='emitter')!.port.position);}
});
test('stationary dock reuses exact mobile organ primitives, not waterworks geometry',()=>{
 for(const organ of RESTORATION_PARTS.organ){const recipe=input({organ}),body=compileRestorationBody(recipe),dock=compileRestorationDock(recipe),a=body.plan.nodes.find(n=>n.key==='organ')!,b=dock.plan.nodes.find(n=>n.key==='organ')!;assert.equal(a.axiom,b.axiom);assert.deepEqual(a.properties,b.properties);assert.deepEqual(a.costs,b.costs);assert.deepEqual(a.ports.map(p=>[p.key,p.type,p.protocol,p.direction,p.unit]),b.ports.map(p=>[p.key,p.type,p.protocol,p.direction,p.unit]));assert.equal(dock.plan.valid,true);assert.equal(dock.budget.nodes,3);assert.ok(dock.budget.shapes<=80);assert.ok(!dock.plan.nodes.some(n=>n.axiom.includes('waterworks')));if(organ==='pump')assert.equal(a.properties.primitive,'mobile-impeller/v1');}
});
test('registry/manifest exposes versioned bodies and real finite stats in declared bounds',()=>{
 assert.deepEqual(registerRestorationBody(new AxiomRegistry()).list(),restorationBodyRegistry.list());assert.equal(RESTORATION_BODY_MANIFEST.domain,'restoration-body');assert.match(RESTORATION_BODY_MANIFEST.contentHash,/^[0-9a-f]{8}$/);for(const recipe of variants){const stats=compileRestorationBody(recipe).stats;for(const d of RESTORATION_STAT_DESCRIPTORS){assert.ok(stats[d.key]>=d.min&&stats[d.key]<=d.max,`${d.key} out of bounds`);assert.ok(d.consumer.length&&d.unit.length&&d.effect.length);}}
 const nimble=compileRestorationBody(input()),sturdy=compileRestorationBody(input({support:'sturdy'})),alloy=compileRestorationBody(input({shell:'alloy'}));assert.ok(nimble.stats.speedSteps>sturdy.stats.speedSteps);assert.ok(nimble.stats.workSpeed<sturdy.stats.workSpeed);assert.ok(alloy.stats.heatTolerance>nimble.stats.heatTolerance);
});
test('structural cost is exact, affordable at entry and reversible without replenishing resources',()=>{
 assert.deepEqual(compileRestorationBody(input()).cost,{scrap:2,core:0});let inventory={scrap:30,core:3},current:RestorationBodyRecipe|null=null;const resources=Object.freeze({waterMl:2345,charge:17,waste:293,filter:234});
 for(let n=0;n<5;n++)for(const recipe of variants){const previous={...inventory},old=current?compileRestorationBody(current).cost:{scrap:0,core:0},p=compileRestorationBody(recipe),r=restorationRefitLedger(current,recipe,inventory)!;assert.deepEqual(p.cost,{scrap:p.plan.costs.scrap??0,core:p.plan.costs.core??0});assert.equal(r.inventory.scrap,previous.scrap+old.scrap-p.cost.scrap);assert.equal(r.inventory.core,previous.core+old.core-p.cost.core);assert.deepEqual(inventory,previous);inventory=r.inventory;current=recipe;}
 const removed=restorationRefitLedger(current,null,inventory)!;assert.deepEqual(removed.inventory,{scrap:30,core:3});assert.deepEqual(resources,{waterMl:2345,charge:17,waste:293,filter:234});assert.deepEqual(Object.keys(removed).sort(),['cost','inventory','refund']);assert.equal(restorationRefitLedger(null,input(),{scrap:1,core:0}),null);assert.equal(restorationRefitLedger(null,input({shell:'alloy'}),{scrap:100,core:0}),null);
});
test('strict recipe parser rejects unknown versions/fields/prototypes/symbols/accessors without invoking code',()=>{
 let invoked=0;const bad:unknown[]=[null,[],{},input({seed:NaN}),input({seed:Infinity}),input({seed:-1}),input({seed:0x100000000}),input({seed:1.5}),{...input(),version:2},{...input(),organ:'waterworks'},{...input(),support:'biped'},{...input(),shell:'plastic'},{...input(),script:'alert(1)'},Object.assign(Object.create({hello:true}),input()),{...input(),[Symbol('x')]:1},JSON.parse('{"version":1,"seed":0,"support":"nimble","shell":"reed","organ":"pump","__proto__":{}}')];const getter={...input()};Object.defineProperty(getter,'seed',{enumerable:true,get(){invoked++;return 1;}});bad.push(getter);for(const b of bad){assert.equal(validRestorationBodyRecipe(b),false);assert.throws(()=>compileRestorationBody(b as RestorationBodyRecipe));}assert.equal(invoked,0);assert.deepEqual(parseRestorationBodyRecipe(JSON.stringify(input())),input());assert.throws(()=>parseRestorationBodyRecipe('x'));assert.throws(()=>parseRestorationBodyRecipe(' '.repeat(1025)));assert.equal(validRestorationBodyRecipe(Object.assign(Object.create(null),input())),true);
});
test('structural ledger fails closed for invalid inventory and cannot overflow a safe integer',()=>{
 for(const inventory of [{scrap:NaN,core:0},{scrap:-1,core:0},{scrap:.5,core:0},{scrap:2,core:Infinity},{scrap:2,core:0,charge:100}])assert.equal(restorationRefitLedger(null,input(),inventory),null);assert.equal(restorationRefitLedger(input(),null,{scrap:Number.MAX_SAFE_INTEGER,core:0}),null);let calls=0;const inventory={scrap:2,core:0};Object.defineProperty(inventory,'scrap',{get(){calls++;return 2;}});assert.equal(restorationRefitLedger(null,input(),inventory),null);assert.equal(calls,0);
});
