import test from 'node:test';import assert from 'node:assert/strict';
import {parseRestorationCarePreset,serializeRestorationCarePreset,createRestorationCarePreset,mountRestorationCareLab} from '../src/restoration-care-lab.ts';
import {validTownLife} from '../src/town-life.ts';
import {validRestorationCare} from '../src/restoration-care.ts';
import {RESTORATION_DEFAULTS,RESTORATION_TUNING_REGISTRY} from '../src/restoration-plan.ts';
class Element {value='';textContent='';disabled=false;files:any[]=[];nodes=new Map<string,Element>();onclick?:()=>void;oninput?:()=>void;onchange?:()=>Promise<void>;set innerHTML(html:string){this.nodes.clear();for(const m of html.matchAll(/\bid="([^"]+)"/g))this.nodes.set('#'+m[1],new Element());}querySelector(s:string){return this.nodes.get(s)??null;}}
test('care preset is exact, finite and independent of existing restoration settings',()=>{const p=createRestorationCarePreset(42,'test-source');assert.deepEqual(parseRestorationCarePreset(serializeRestorationCarePreset(p)),p);for(const bad of [{...p,version:2},{...p,extra:true},{...p,tuning:{...p.tuning,growthIntervalTicks:0}},{...p,seed:-1}])assert.throws(()=>parseRestorationCarePreset(JSON.stringify(bad)));for(const edge of ['min','max'] as const){const tuned={...p,tuning:Object.fromEntries(RESTORATION_TUNING_REGISTRY.map(f=>[f.key,f[edge]]))};assert.deepEqual(parseRestorationCarePreset(JSON.stringify(tuned)).tuning,tuned.tuning);}assert.throws(()=>parseRestorationCarePreset(serializeRestorationCarePreset(p).replace('\"version\": 1','\"version\": 1, \"version\": 1')),/Duplicate/);assert.deepEqual(RESTORATION_DEFAULTS,{waterConductance:20,airConductance:6,growthIntervalTicks:12,machineSpeedPercent:100,scentWeight:4});});
test('care lab starts unopened, stages tuning, bounds steps and prevents stale asynchronous preset replacement',async()=>{const panel=new Element(),lab=mountRestorationCareLab(panel as any,{seed:42,source:'test-source',onClose:()=>{}}),q=(id:string)=>panel.querySelector('#rcl-'+id)!;assert.equal(lab.getPreset().scenario,'unopened');q('growthIntervalTicks').value='4';q('growthIntervalTicks').oninput!();assert.equal(lab.getPreset().tuning.growthIntervalTicks,12);q('apply').onclick!();assert.equal(lab.getPreset().tuning.growthIntervalTicks,4);let finish!:(s:string)=>void;q('file').files=[{size:100,text:()=>new Promise(r=>finish=r)}];const pending=q('file').onchange!();q('seed').value='99';q('seed').oninput!();finish(serializeRestorationCarePreset(createRestorationCarePreset(7,'test-source')));await pending;assert.equal(q('seed').value,'99');assert.equal(lab.getPreset().seed,42);for(const seconds of [0,61,NaN,.5])assert.throws(()=>lab.step(seconds));lab.step(1);assert.equal(lab.report().elapsed,1);q('reset').onclick!();assert.equal(lab.report().elapsed,0);lab.dispose();lab.step(1);assert.equal(lab.report().elapsed,0);});

test('care lab earns delivered stock, preserves ledgers through resident arrival and repeats the same preparation',()=>{const panel=new Element(),lab=mountRestorationCareLab(panel as any,{seed:42,source:'test-source',onClose:()=>{}}),q=(id:string)=>panel.querySelector('#rcl-'+id)!;q('scenario').value='delivered';q('reset-draft').onclick!();const initial=lab.getState();assert.equal(initial.restorationCare!.delivered,5);assert.equal(initial.townLife!.habitatCare!.stock,5);assert(initial.restoration!.sites[0]!.completedAtTick!==null);const prep=JSON.stringify(lab.report().preparationActions);for(let i=0;i<3;i++)lab.step(60);const actual=lab.getState();assert(validTownLife(actual.townLife,42));assert(validRestorationCare(actual.restorationCare,actual.restoration!,actual.townLife!));assert.equal(actual.townLife!.habitatCare!.stock+actual.townLife!.habitatCare!.used,5);assert(actual.townLife!.habitatCare!.used>0,'real resident recovery consumes a delivered portion');q('reset').onclick!();assert.equal(lab.getState().townLife!.habitatCare!.stock,5);assert.equal(JSON.stringify(lab.report().preparationActions),prep);assert.equal(lab.report().initialInventory.scrap,16);lab.dispose();});

test('care low default and high settings produce distinct earned restoration timings with conserved preparation',async()=>{const {createRestorationCareScenario}=await import('../src/restoration-care-scenarios.ts'),{restorationBalances,validRestoration}=await import('../src/restoration.ts');const ticks:number[]=[];for(const edge of ['min','default','max'] as const){const tuning=Object.fromEntries(RESTORATION_TUNING_REGISTRY.map(f=>[f.key,f[edge]])) as unknown as typeof RESTORATION_DEFAULTS;const fixture=createRestorationCareScenario(73129,'delivered',tuning);assert(validRestoration(fixture.restoration,fixture.plan));assert(Object.values(restorationBalances(fixture.restoration,fixture.plan)).every(n=>n===0));assert.equal(fixture.care!.delivered,5);assert.equal(fixture.life.habitatCare!.stock,5);assert.equal(fixture.initialInventory.scrap,16);assert(fixture.inventory.scrap<fixture.initialInventory.scrap);ticks.push(fixture.preparationTicks);}assert.equal(new Set(ticks).size,3,'Settings must change actual achieved preparation, not only exported labels');});
