import assert from 'node:assert/strict';
import {test} from 'node:test';
import {habitatMixture,habitatFieldTotals,stepHabitatFields} from '../src/habitat-fields.ts';
import {advanceHabitatMotion,chooseHabitatScentTarget,createHabitatMotion,habitatMotionPosition,targetHabitatMotion} from '../src/habitat-motion.ts';
import {advanceRestoration,applyRestorationCommand,createRestoration,immutableRestoration,restorationBalances,restorationMachinePosition,restorationPlan,restorationPlayerCost,RESTORATION_DEFAULTS,RESTORATION_TUNING_REGISTRY,validRestoration,validRestorationCommand,type RestorationState,type RestorationCommand} from '../src/restoration.ts';
import {createRestorationScenario,restorationScenarioDescriptors,restorationEvidence} from '../src/restoration-scenarios.ts';
const plan=restorationPlan(7,restorationScenarioDescriptors());
const balance=(s:RestorationState)=>assert.deepEqual(restorationBalances(s,plan),{waterMl:0,contaminant:0,energy:0,smoke:0,scent:0,organic:0,filter:0});
function run(s:RestorationState,n:number){for(let i=0;i<n;i++)s=advanceRestoration(s,plan,.25);return s;}
function fixture(organ:'pump'|'filter'|'vent'|'beacon'='filter'){const sc=createRestorationScenario(7,({'pump':'pump-mixture','filter':'filter-mass','vent':'vent-heat','beacon':'beacon-route'} as const)[organ]);return {s:sc.state,ctx:sc.context};}
function command(s:RestorationState,ctx:ReturnType<typeof fixture>['ctx'],c:Omit<RestorationCommand,'expectedRevision'>|Record<string,unknown>){return applyRestorationCommand(s,plan,ctx,{...c,expectedRevision:s.revision} as RestorationCommand);}
function prepared(){let state=createRestoration(plan);let inventory={scrap:20,core:2,water:0};for(const site of plan.sites){const result=command(state,{seed:7,zone:'valley',player:{x:site.x,z:site.z,hp:70},inventory},{kind:'refit',targetId:site.id,recipe:{version:1,seed:7,support:'nimble',shell:'reed',organ:'pump'},ability:{version:1,organ:'pump',strength:1,tempo:'steady'}});state=result.state;inventory=result.inventory;}const s=structuredClone(state);for(const site of s.sites)for(const c of site.cells){s.sinks.heat+=c.heat;c.heat=0;s.sinks.smoke+=c.smoke;c.smoke=0;site.sealedWaste+=c.contaminant;site.filterReserve-=c.contaminant;s.sinks.filter+=c.contaminant;c.contaminant=0;}assert(validRestoration(s,plan));return immutableRestoration(s,plan);}
test('mixture removes actual proportional mass including all remaining water',()=>{assert.equal(habitatMixture(100,17,25),4);assert.equal(habitatMixture(100,17,100),17);assert.throws(()=>habitatMixture(10,1,11));});
test('simultaneous branching transfers conserve all fields without negative or overflow',()=>{let cells=[{waterMl:100,contaminant:17,heat:900,smoke:50,scent:70},...Array.from({length:3},()=>({waterMl:0,contaminant:0,heat:0,smoke:0,scent:0}))];const totals=habitatFieldTotals(cells),edges=[{a:0,b:1},{a:0,b:2},{a:0,b:3}];for(let i=0;i<100;i++){cells=stepHabitatFields(cells,edges,{waterConductance:100,airConductance:30,cellCapacityMl:100}).cells;assert.deepEqual(habitatFieldTotals(cells),totals);assert(cells.every(c=>Object.values(c).every(n=>Number.isSafeInteger(n)&&n>=0)));assert(cells.every(c=>c.waterMl<=100));}});
test('field transport canonicalizes edge ordering and rejects duplicate reverse edges',()=>{const c=[{waterMl:7,contaminant:3,heat:9,smoke:10,scent:3},{waterMl:0,contaminant:0,heat:0,smoke:0,scent:0},{waterMl:0,contaminant:0,heat:0,smoke:0,scent:0}],e=[{a:0,b:1},{a:0,b:2}],o={waterConductance:10,airConductance:5,cellCapacityMl:10};assert.deepEqual(stepHabitatFields(c,e,o),stepHabitatFields(c,[{a:2,b:0},{a:1,b:0}],o));assert.throws(()=>stepHabitatFields(c,[{a:0,b:1},{a:1,b:0}],o));});
test('plans are immutable, geometry-bounded, seed-variable and cached',()=>{assert.equal(restorationPlan(7,restorationScenarioDescriptors()),plan);assert(Object.isFrozen(plan.sites[0]!.cells[0]!.initial));assert.notDeepEqual(plan.totals,restorationPlan(8,restorationScenarioDescriptors()).totals);const bad=structuredClone(restorationScenarioDescriptors());bad[0]!.edges[0]!.path[0]!.x+=1;assert.throws(()=>restorationPlan(7,bad));});
test('fresh state and 2000 active steps preserve every finite mass and energy ledger',()=>{let s=createRestoration(plan);for(let i=0;i<2000;i++){s=advanceRestoration(s,plan,.25);if(i%100===0){balance(s);assert(validRestoration(JSON.parse(JSON.stringify(s)),plan));}}balance(s);assert.equal(s.revision,0);});
test('60Hz, quarter-second and uneven partitions produce identical canonical states',()=>{let a=createRestoration(plan),b=createRestoration(plan),c=createRestoration(plan);for(let i=0;i<600;i++)a=advanceRestoration(a,plan,1/60);for(let i=0;i<40;i++)b=advanceRestoration(b,plan,.25);for(let i=0;i<100;i++){c=advanceRestoration(c,plan,.03);c=advanceRestoration(c,plan,.07);}assert.deepEqual(a,b);assert.deepEqual(b,c);});
test('large frames are bounded and nonfinite/nonpositive time is inert',()=>{const s=createRestoration(plan);assert.equal(advanceRestoration(s,plan,NaN),s);assert.equal(advanceRestoration(s,plan,-1),s);assert.equal(advanceRestoration(s,plan,Infinity),s);assert.equal(advanceRestoration(s,plan,10000).tick,4);});
test('canonical structural costs are paid; refits preserve finite contents and do not duplicate inventory',()=>{const sc=createRestorationScenario(7),p=plan.sites[0]!,f=fixture();let s=f.s,ctx=f.ctx;s=command(s,ctx,{kind:'recall',targetId:p.id}).state;s=run(s,1);const before={charge:s.machine!.charge,filter:s.machine!.filter,waste:s.machine!.waste,tank:s.machine!.tank},inventory={...ctx.inventory};for(let i=0;i<20;i++){const result=command(s,ctx,{kind:'refit',targetId:p.id,recipe:{version:1,seed:7,support:'nimble',shell:'reed',organ:'filter'},ability:{version:1,organ:'filter',strength:1,tempo:'steady'}});s=result.state;ctx={...ctx,inventory:result.inventory};}assert.deepEqual(ctx.inventory,inventory);assert.deepEqual({charge:s.machine!.charge,filter:s.machine!.filter,waste:s.machine!.waste,tank:s.machine!.tank},before);assert.equal(restorationPlayerCost(s).scrap,3);assert.equal(ctx.inventory.scrap+restorationPlayerCost(s).scrap,sc.authorizedFixtureInventory.scrap);balance(s);});
test('stale revisions, dead actors, remote actors, malformed commands and zero inventory are inert',()=>{const f=fixture(),c={kind:'stop',targetId:plan.sites[0]!.id,expectedRevision:f.s.revision};assert.equal(applyRestorationCommand(f.s,plan,f.ctx,{...c,expectedRevision:0} as RestorationCommand).state,f.s);assert.equal(applyRestorationCommand(f.s,plan,{...f.ctx,player:{...f.ctx.player,hp:0}},c as RestorationCommand).state,f.s);assert.equal(applyRestorationCommand(f.s,plan,{...f.ctx,player:{x:900,z:900,hp:100}},c as RestorationCommand).state,f.s);assert(!validRestorationCommand({...c,extra:true}));const empty=createRestoration(plan);assert.equal(command(empty,{...f.ctx,inventory:{scrap:0,core:0,water:0}},{kind:'refit',targetId:plan.sites[0]!.id,recipe:{version:1,seed:7,support:'nimble',shell:'reed',organ:'pump'},ability:{version:1,organ:'pump',strength:1,tempo:'steady'}}).state,empty);});
test('filter captures real contaminant once and consumes exactly captured cartridge mass',()=>{const f=fixture('filter'),id=plan.sites[0]!.dockCellId;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:id}).state;s=run(s,10);assert(s.machine!.waste>0);assert.equal(s.sinks.filter,s.machine!.waste);assert.equal(s.machine!.filter+s.machine!.waste,f.s.machine!.filter);balance(s);assert(validRestoration(JSON.parse(JSON.stringify(s)),plan));});
test('pump moves water and contaminant to a persistent onboard tank',()=>{const f=fixture('pump'),id=plan.sites[0]!.dockCellId;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:'tank'}).state;s=run(s,7);assert(s.machine!.tank.waterMl>0);assert(s.machine!.tank.contaminant>0);balance(s);const stopped=command(s,f.ctx,{kind:'stop',targetId:plan.sites[0]!.id}).state;assert.deepEqual(stopped.machine!.tank,s.machine!.tank);});
test('vent clears actual heat and smoke into explicit sinks',()=>{const f=fixture('vent'),id=plan.sites[0]!.dockCellId;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:id}).state;s=run(s,7);const baseline=run(f.s,7);assert(s.sinks.heat>baseline.sinks.heat+70);assert(s.sinks.smoke>=baseline.sinks.smoke+8);assert(s.machine!.charge<baseline.machine!.charge);balance(s);});
test('beacon spends finite scent and induces stable routed pollinator movement',()=>{const f=fixture('beacon'),id=plan.sites[0]!.cells[3]!.id;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:id}).state;s=run(s,100);assert(s.machine!.scentCharge<f.s.machine!.scentCharge);assert(s.sites[0]!.pollinatorVisits>0);assert(s.sites[0]!.pollinator.targetId!==plan.sites[0]!.dockCellId);balance(s);});
test('explicit occluded graph edges block physical travel and resume after release',()=>{const p=plan.sites[0]!,f=fixture('filter'),id=p.cells[1]!.id;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:id}).state;const before=restorationMachinePosition(s,plan);s=advanceRestoration(s,plan,.25,{blockedEdgeIds:p.edges.map(e=>e.id)});assert.deepEqual(restorationMachinePosition(s,plan),before);assert(s.machine!.blocked);s=advanceRestoration(s,plan,.25);assert.notDeepEqual(restorationMachinePosition(s,plan),before);});
test('swept actors prevent robot crossing and release does not teleport',()=>{const p=plan.sites[0]!,m=targetHabitatMotion(p,createHabitatMotion(p),p.cells[1]!.id),blocked=advanceHabitatMotion(p,m,2,RESTORATION_DEFAULTS,{actors:[{x:.5,z:0,radius:.4}]});assert.equal(blocked.motion,m);const moved=advanceHabitatMotion(p,m,2,RESTORATION_DEFAULTS,{});assert.equal(habitatMotionPosition(p,moved.motion).x,.5);});
test('depleted recall requires nearby live player tow and traverses the same route',()=>{const f=fixture(),p=plan.sites[0]!,raw=structuredClone(f.s);raw.machine!.motion=createHabitatMotion(p,p.cells[1]!.id);raw.sinks.heat+=raw.machine!.charge;raw.machine!.charge=0;let s=immutableRestoration(raw,plan),ctx={...f.ctx,player:{x:2,z:0,hp:70}};s=command(s,ctx,{kind:'recall',targetId:p.id}).state;const pos=restorationMachinePosition(s,plan);assert.deepEqual(restorationMachinePosition(advanceRestoration(s,plan,.25),plan),pos);const moved=advanceRestoration(s,plan,.25,{player:ctx.player});assert.notDeepEqual(restorationMachinePosition(moved,plan),pos);for(let i=0;i<20&&s.machine!.status!=='packed';i++)s=advanceRestoration(s,plan,.25,{player:ctx.player});assert.equal(s.machine!.status,'packed');assert.equal(s.machine!.charge,0);balance(s);});
test('smoke reduces genuine sensor reach and clears with the vent/natural sink',()=>{const f=fixture('filter'),id=plan.sites[0]!.cells[3]!.id,raw=structuredClone(f.s),site=raw.sites[0]!,dock=site.cells[0]!;for(let i=1;i<site.cells.length;i++){dock.smoke+=site.cells[i]!.smoke;site.cells[i]!.smoke=0;}const smoky=immutableRestoration(raw,plan);assert.equal(command(smoky,f.ctx,{kind:'start',sourceId:id,targetId:id}).state,smoky);for(const c of site.cells){raw.sinks.smoke+=c.smoke;c.smoke=0;}const clear=immutableRestoration(raw,plan);assert.notEqual(command(clear,f.ctx,{kind:'start',sourceId:id,targetId:id}).state,clear);});
test('restoration persists and finite biomass repair cannot be duplicated',()=>{let s=run(prepared(),500);assert(s.sites.every(site=>site.completedAtTick!==null));const p=plan.sites[0]!,ctx={seed:7,zone:'valley',player:{x:p.x,z:p.z,hp:70},inventory:{scrap:0,core:0,water:0}},initialOrganic=s.sites[0]!.cells.reduce((n,c)=>n+c.biomass,0);let repaired=0;for(let i=0;i<100;i++){const result=command(s,ctx,{kind:'repair',targetId:p.id});repaired+=result.hp-ctx.player.hp;s=result.state;}assert(repaired>0);assert.equal(s.sites[0]!.repairUsed,initialOrganic-p.cells.length*2);assert(s.sites[0]!.completedAtTick!==null);balance(s);assert(validRestoration(JSON.parse(JSON.stringify(s)),plan));});
test('growth consumes water and nutrient to real biomass; poor field cannot restore',()=>{const good=run(prepared(),100),bad=run(createRestoration(plan),100);assert(good.sinks.waterMl>bad.sinks.waterMl);assert(good.sites[0]!.cells[0]!.biomass>bad.sites[0]!.cells[0]!.biomass);balance(good);});
test('strict validators reject invented mass, unknown keys, nonfinite fields and mutable malformed saves',()=>{const s=createRestoration(plan);for(const mutate of [(x:RestorationState)=>x.sites[0]!.cells[0]!.waterMl++,(x:RestorationState)=>x.sites[0]!.cells[0]!.heat=NaN,(x:RestorationState)=>(x as any).extra=1,(x:RestorationState)=>x.sites[0]!.pollinator.progressMm=-1]){const raw=structuredClone(s);mutate(raw);assert(!validRestoration(raw,plan));}const clone=JSON.parse(JSON.stringify(s)),immutable=immutableRestoration(clone,plan);assert(Object.isFrozen(immutable.sites[0]!.cells[0]));assert.equal(immutableRestoration(clone,plan),immutable);});
test('disposable scenario reset and evidence remain isolated and conserve authorized fixture stock',()=>{const a=createRestorationScenario(7,'vent-heat'),b=createRestorationScenario(7,'vent-heat');const changed=run(a.state,40);assert.notDeepEqual(changed,a.state);assert.deepEqual(a,b);assert.equal(restorationEvidence(a).mode,'disposable-model');assert.equal(a.context.inventory.scrap+restorationPlayerCost(a.state).scrap,a.authorizedFixtureInventory.scrap);assert.equal(a.state.tick,0);});
test('every tuning setting has real low/default/high outcomes',()=>{for(const def of RESTORATION_TUNING_REGISTRY){const values=[def.min,def.default,def.max],outcomes=values.map(value=>{const tuning={...RESTORATION_DEFAULTS,[def.key]:value};if(def.key==='scentWeight'){const p=plan.sites[0]!,fields=p.cells.map((c,i)=>({id:c.id,scent:i===1?5:i===3?7:0}));return chooseHabitatScentTarget(p,fields,createHabitatMotion(p),value);}if(def.key==='machineSpeedPercent'){const p=plan.sites[0]!,m=targetHabitatMotion(p,createHabitatMotion(p),p.cells[1]!.id);return advanceHabitatMotion(p,m,2,tuning,{}).motion.progressMm;}let s=def.key==='growthIntervalTicks'?prepared():fixture('pump').s;if(def.key==='airConductance'){const raw=structuredClone(s),cells=raw.sites[0]!.cells;cells[0]!.heat+=cells[1]!.heat;cells[1]!.heat=0;s=immutableRestoration(raw,plan);}for(let i=0;i<40;i++)s=advanceRestoration(s,plan,.25,{},tuning);return def.key==='growthIntervalTicks'?s.sinks.waterMl:def.key==='waterConductance'?s.sites[0]!.cells[0]!.waterMl:s.sites[0]!.cells[1]!.heat;});assert(new Set(outcomes).size>=2,`${def.key}: ${outcomes}`);}});
test('actual command-only treatment restores a site and spends finite earned repair biomass',()=>{const f=fixture('filter'),p=plan.sites[0]!;let s=f.s,ctx=f.ctx;for(const cell of p.cells){const machine=restorationMachinePosition(s,plan)!;ctx={...ctx,player:{x:machine.x,z:machine.z,hp:70}};const start=command(s,ctx,{kind:'start',sourceId:cell.id,targetId:cell.id});assert.notEqual(start.state,s,start.message);s=start.state;for(let i=0;i<100&&s.machine!.status==='working';i++)s=advanceRestoration(s,plan,.25);assert.equal(s.machine!.status,'idle');balance(s);}s=run(s,1000);assert(s.sites[0]!.completedAtTick!==null);ctx={...ctx,player:{x:p.x,z:p.z,hp:70}};const repair=command(s,ctx,{kind:'repair',targetId:p.id});assert(repair.hp>70);assert(repair.state.sites[0]!.repairUsed>0);assert(validRestoration(JSON.parse(JSON.stringify(repair.state)),plan));balance(repair.state);});
test('dry zero-volume transfer carries no dust and save cache does not return stale mutable imports',()=>{assert.equal(habitatMixture(0,8,0),0);const raw=structuredClone(createRestoration(plan)),first=immutableRestoration(raw,plan);raw.remainder=.125;const second=immutableRestoration(raw,plan);assert.notEqual(first,second);assert.equal(second.remainder,.125);assert.equal(first.remainder,0);});
test('stopped windup has no delayed resource pulse; overheat interrupts safely',()=>{const f=fixture('pump'),id=plan.sites[0]!.dockCellId;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:'tank'}).state;s=run(s,2);s=command(s,f.ctx,{kind:'stop',targetId:plan.sites[0]!.id}).state;s=run(s,30);assert.equal(s.machine!.tank.waterMl,0);assert.equal(s.machine!.charge,100);const raw=structuredClone(f.s);raw.machine!.heat=80;raw.machine!.charge-=80;let hot=immutableRestoration(raw,plan);hot=command(hot,f.ctx,{kind:'start',sourceId:id,targetId:'tank'}).state;hot=run(hot,1);assert.equal(hot.machine!.status,'idle');assert.equal(hot.machine!.tank.waterMl,0);balance(hot);});
test('low finite energy and empty cartridge never refill through stop, service or depleted restart',()=>{const f=fixture('beacon'),p=plan.sites[0]!,id=p.dockCellId;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:id}).state;s=run(s,150);assert.equal(s.machine!.scentCharge,0);const charge=s.machine!.charge;const restart=command(s,f.ctx,{kind:'start',sourceId:id,targetId:id}).state;const exhausted=run(restart,100);assert.equal(exhausted.machine!.scentCharge,0);assert.equal(exhausted.machine!.charge,charge);assert.equal(command(exhausted,f.ctx,{kind:'service',targetId:p.id}).state,exhausted);balance(exhausted);});
test('serialized active replay and original produce identical utility effects and ledgers',()=>{const f=fixture('filter'),id=plan.sites[0]!.dockCellId;let a=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:id}).state;a=run(a,3);let b=immutableRestoration(JSON.parse(JSON.stringify(a)),plan);for(let i=0;i<80;i++){a=advanceRestoration(a,plan,.25);b=advanceRestoration(b,plan,.25);}assert.deepEqual(a,b);balance(b);});
test('active utility recipe and body work speed must match the configured machine',async()=>{const {createUtilityState,requestUtility}=await import('../src/utility-ability.ts');const f=fixture('pump'),id=plan.sites[0]!.dockCellId;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:'tank'}).state;s=run(s,1);for(const patch of [{strength:3,tempo:'steady',workSpeed:.8},{strength:1,tempo:'brisk',workSpeed:.8},{strength:1,tempo:'steady',workSpeed:1.2}] as const){const raw=structuredClone(s);raw.machine!.utility=requestUtility(createUtilityState(),{version:1,organ:'pump',strength:patch.strength,tempo:patch.tempo},{intentId:1,sourceId:id,targetId:'tank'},{energyAvailable:100,filtrationAvailable:100,workSpeed:patch.workSpeed}).state;assert(!validRestoration(raw,plan));}assert(validRestoration(JSON.parse(JSON.stringify(s)),plan));});
test('completed habitat requires actual historical growth and feasible active time',()=>{const f=fixture('filter'),fresh=structuredClone(f.s);fresh.tick=16;fresh.sites[0]!.completedAtTick=16;assert(!validRestoration(fresh,plan));const grown=run(prepared(),500),tooEarly=structuredClone(grown);tooEarly.sites[0]!.completedAtTick=16;assert(!validRestoration(tooEarly,plan));const tooLateActivation=structuredClone(grown);tooLateActivation.sites[0]!.activatedAtTick=tooLateActivation.sites[0]!.completedAtTick!-1;assert(!validRestoration(tooLateActivation,plan));assert(validRestoration(JSON.parse(JSON.stringify(grown)),plan));});
test('strict save and descriptor arrays reject extras, symbols, sparse slots and custom prototypes',()=>{for(const mutation of [(s:any)=>s.sites.extra=1,(s:any)=>s.sites[0].cells.extra=1,(s:any)=>s.records.extra=1,(s:any)=>s.sites[0].pollinator.route.extra=1,(s:any)=>s.sites[Symbol('extra')]=1,(s:any)=>delete s.sites[1],(s:any)=>Object.setPrototypeOf(s.sites,{}),(s:any)=>Object.defineProperty(s.sites[0].cells,'0',{get(){throw new Error('Never read');}})]){const raw=structuredClone(createRestoration(plan));mutation(raw);assert(!validRestoration(raw,plan));}for(const mutate of [(d:any)=>d.extra=1,(d:any)=>d[0].cells.extra=1,(d:any)=>d[0].edges.extra=1,(d:any)=>d[0].edges[0].path.extra=1]){const raw=structuredClone(restorationScenarioDescriptors());mutate(raw);assert.throws(()=>restorationPlan(7,raw));}});
test('actual machine sweep covers protruding organ and supports rather than trunk width',()=>{const f=fixture('filter'),p=plan.sites[0]!,id=p.cells[1]!.id;let s=command(f.s,f.ctx,{kind:'start',sourceId:id,targetId:id}).state;const before=restorationMachinePosition(s,plan);s=advanceRestoration(s,plan,.25,{actors:[{x:.5,z:1.1,radius:.2}]});assert.deepEqual(restorationMachinePosition(s,plan),before);assert.equal(s.machine!.blocked,true);s=advanceRestoration(s,plan,.25);assert.notDeepEqual(restorationMachinePosition(s,plan),before);});
test('remote active time leaves dormant sites pristine until a successful local action',()=>{const initial=createRestoration(plan);let s=run(initial,4000);assert.deepEqual(s.sites,initial.sites);assert(s.sites.every(site=>site.activatedAtTick===null));const f=fixture('pump'),ctx={...f.ctx,inventory:{scrap:20,core:2,water:0}},p=plan.sites[0]!;const rejected=command(s,{...ctx,player:{x:1000,z:1000,hp:70}},{kind:'refit',targetId:p.id,recipe:{version:1,seed:7,support:'nimble',shell:'reed',organ:'pump'},ability:{version:1,organ:'pump',strength:1,tempo:'steady'}});assert.equal(rejected.state,s);s=command(s,ctx,{kind:'refit',targetId:p.id,recipe:{version:1,seed:7,support:'nimble',shell:'reed',organ:'pump'},ability:{version:1,organ:'pump',strength:1,tempo:'steady'}}).state;assert.equal(s.sites[0]!.activatedAtTick,4000);assert(s.records.some(r=>r.kind==='activate'&&r.targetId===p.id&&r.tick===4000));s=run(s,1);assert(s.sites[0]!.cells[0]!.heat<initial.sites[0]!.cells[0]!.heat);assert.deepEqual(s.sites.slice(1),initial.sites.slice(1));assert(validRestoration(JSON.parse(JSON.stringify(s)),plan));balance(s);});
test('dormant baseline cannot carry cooled fields, captured resources, growth or prior visits',()=>{for(const mutation of [(s:RestorationState)=>{s.sites[0]!.cells[0]!.heat--;s.sinks.heat++;},(s:RestorationState)=>{s.sites[0]!.pollinatorVisits=1;},(s:RestorationState)=>{s.sites[0]!.activatedAtTick=s.tick+1;},(s:RestorationState)=>{s.sites[0]!.chargeReserve--;s.sinks.heat++;}]){const raw=structuredClone(run(createRestoration(plan),100));mutation(raw);assert(!validRestoration(raw,plan));}});
test('deployment rejects the player and peers inside the true compiled body footprint',()=>{const f=fixture('filter'),p=plan.sites[0]!;let s=command(f.s,f.ctx,{kind:'recall',targetId:p.id}).state;s=run(s,1);assert.equal(s.machine!.status,'packed');const own={...f.ctx,player:{x:p.x,z:p.z,hp:70}};assert.equal(command(s,own,{kind:'deploy',targetId:p.id}).state,s);const peer={...f.ctx,actors:[{x:p.x+.9,y:p.y,z:p.z,radius:.34}]};assert.equal(command(s,peer,{kind:'deploy',targetId:p.id}).state,s);const highPeer={...f.ctx,actors:[{x:p.x,y:p.y+5,z:p.z,radius:.34}]};assert.notEqual(command(s,highPeer,{kind:'deploy',targetId:p.id}).state,s);const clear={...f.ctx,actors:[{x:p.x+2,y:p.y,z:p.z,radius:.34}]};const deployed=command(s,clear,{kind:'deploy',targetId:p.id});assert.notEqual(deployed.state,s);assert.equal(deployed.state.machine!.status,'idle');balance(deployed.state);});

test('canonical hot habitat makes the real alloy shell useful while reed can wait for passive cooling',()=>{
 const plan=restorationPlan(73129,restorationScenarioDescriptors()),dock=plan.sites[2]!;
 const run=(shell:'reed'|'alloy')=>{let s=createRestoration(plan);let context={seed:plan.seed,zone:'valley',player:{x:dock.x,z:dock.z-2.5,hp:100},inventory:{scrap:20,core:2,water:0}};const commands=[{kind:'refit',targetId:dock.id,recipe:{version:1,seed:plan.seed,support:'nimble',shell,organ:'filter'},ability:{version:1,organ:'filter',strength:1,tempo:'steady'}},{kind:'service',targetId:dock.id},{kind:'deploy',targetId:dock.id},{kind:'start',targetId:dock.cells[0]!.id,sourceId:dock.cells[0]!.id}];for(const command of commands){const r=applyRestorationCommand(s,plan,context,{...command,expectedRevision:s.revision} as RestorationCommand);assert.notEqual(r.state,s,r.message);s=r.state;context={...context,inventory:r.inventory};}for(let n=0;n<32;n++)s=advanceRestoration(s,plan,.25);return {s,context};};
 const reed=run('reed'),alloy=run('alloy');assert.equal(reed.s.machine!.waste,0);assert(alloy.s.machine!.waste>0);assert.equal(reed.s.machine!.status,'idle');assert(reed.s.records.some(r=>r.kind==='interrupt'));
 let cooled=reed.s;for(let n=0;n<240;n++)cooled=advanceRestoration(cooled,plan,.25);const restarted=applyRestorationCommand(cooled,plan,reed.context,{kind:'start',targetId:dock.cells[0]!.id,sourceId:dock.cells[0]!.id,expectedRevision:cooled.revision});assert.notEqual(restarted.state,cooled);cooled=restarted.state;for(let n=0;n<32;n++)cooled=advanceRestoration(cooled,plan,.25);assert(cooled.machine!.waste>0);assert.deepEqual(restorationBalances(cooled,plan),{waterMl:0,contaminant:0,energy:0,smoke:0,scent:0,organic:0,filter:0});assert(validRestoration(JSON.parse(JSON.stringify(cooled)),plan));
});

test('substep and fully dormant updates reuse immutable field arrays without changing fixed-step outcomes',()=>{
 const fresh=createRestoration(plan),sub=advanceRestoration(fresh,plan,.01),dormant=advanceRestoration(fresh,plan,1);assert.equal(sub.sites,fresh.sites);assert.equal(sub.records,fresh.records);assert.equal(dormant.sites,fresh.sites);assert.equal(dormant.tick,4);assert.deepEqual(restorationBalances(dormant,plan),restorationBalances(fresh,plan));let split=fresh;for(let n=0;n<60;n++)split=advanceRestoration(split,plan,1/60);assert.deepEqual(split,dormant);assert(validRestoration(JSON.parse(JSON.stringify(split)),plan));
});
