import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import * as THREE from 'three/webgpu';import {initializeStartupRenderer} from '../src/startup-renderer.ts';import {startupHarness} from './helpers/startup-harness.ts';
const source=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');const start=source.slice(source.indexOf('async function start(){'),source.indexOf('// Read-only inspection hook'));
function harness(failAt=''){
 const h=startupHarness();h.boot.end('module');h.boot.begin('world','World');const log:string[]=[],scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(),shadow=new THREE.Mesh(new THREE.CircleGeometry(.5),new THREE.MeshBasicMaterial()),player=new THREE.Group(),targetPosition=new THREE.Vector3(6,2,7),cameraTarget=new THREE.Vector3();scene.add(shadow,player);
 const state={zone:'valley',regional:false,player:{x:3,z:4},clock:{tick:99}};let moved:any,frame:any;const renderer={backend:{isWebGPUBackend:true,init:async()=>{}},shadowMap:{},debug:{},onError(){},onDeviceLost(){},init:async()=>{log.push('renderer');if(failAt==='renderer')throw Error('GPU test failure');},dispose:async()=>log.push('dispose'),setAnimationLoop:async(callback:any)=>{if(callback){frame=callback;log.push('loop');}},compileAsync:async()=>{log.push('compile');assert.equal(player.position.x,6);assert.equal(shadow.position.x,6);assert.equal(cameraTarget.x,6);assert.equal(moved.player.x,6);if(failAt==='compile')throw Error('Pipeline test failure');},render(){log.push('render');if(failAt==='render')throw Error('First render failure');}};
 const dependencies={startup:h.boot,THREE:{...THREE,WebGPURenderer:class{constructor(){return renderer}}},location:{search:''},URLSearchParams,initializeStartupRenderer,prepareOptionalFonts:async()=>{},canvas:{addEventListener(){}},scene,camera,shadow,player,targetPosition,cameraTarget,state,document:{getElementById:()=>null,querySelector:()=>null},showSessionRecovery(){},sendWorldPacket(){h.boot.end('spawn','one cell');h.boot.begin('physics','Physics');},clearInput(){log.push('clear');},resize(){},sync(){assert.equal(moved.player.x,6);},updateBackend(){},updateCameraVisibility(){},character:{setEquipment(){},update(){log.push('pose');}},currentEquipment:()=>null,syncContactProps(){},syncFrontierVisuals(dt:number){assert.equal(dt,0);},regionalView:null,regionalSupplyView:null,regionalTradeView:null,regionalFoodView:null,regionalConfirmedProjects:new Map(),regionalConfirmedTrade:new Map(),regionalConfirmedObstacles:new Map(),regionalFoodTerrainConfirmed:()=>false,creatureVisuals:new Map(),objects:[],visuals:new Map(),dungeonVisuals:new Map(),caveView:{objects:new Map()},generatedRoofs:[],workshopRoof:[],residentGroups:new Map(),inWorkshopClearance:()=>false,worldHeight:()=>0,DEFAULT_TUNING:{},CAMERA_VISIBILITY:{elevation:.7},stepAnimation:(a:any,...args:any[])=>{assert.equal(args[5],0);return a;},stepGroundSupport:(a:any,_b:any,_p:any,_mode:any,dt:number)=>{assert.equal(dt,0);return a;},applyAction(s:any,action:any){assert.equal(action.type,'move');log.push('resolved-move');moved={...s,player:{...s.player,x:action.x,z:action.z}};assert.equal(moved.clock.tick,99);return moved;},updateContextControls(){log.push('ui');},drawMap(){log.push('map');},toast(){},frame(){log.push('tick');},$:()=>({remove(){log.push('remove old loading');}}),performance,setTimeout};
 const preamble=`let sessionLoadFailed=false,sessionReloading=false,physicsReady=true,transitioning=false,renderer,backend='',orbit=.6,zoom=36,reducedMotion=false,animation={},physicsMotion={grounded:true,crouched:false,sliding:false,stance:0,vy:0},playerContact={mode:'none'},last=0,lastMachineHud=0,lastMachineSave=0,frames=0,measure=0,elapsed=0;const physicsReadyPromise=Promise.resolve(),startupPosePromise=Promise.resolve();`;
 const api=new Function(...Object.keys(dependencies),stripTypeScriptTypes('async function run(){'+preamble+start+';return start();}')+';return run();');return {h,log,run:()=>api(...Object.values(dependencies)),get frame(){return frame;}};
}
test('actual start function projects resolved spawn, compiles then submits one frame before entering gameplay',async()=>{const h=harness();assert.equal(await h.run(),true);assert(h.h.boot.playing);assert(h.log.indexOf('resolved-move')<h.log.indexOf('compile'));assert(h.log.indexOf('compile')<h.log.indexOf('render'));assert(h.log.indexOf('render')<h.log.indexOf('loop'));assert.equal(h.log.filter(s=>s==='render').length,1);assert(!h.log.includes('tick'));assert.equal(typeof h.frame,'function');});
for(const stage of ['renderer','compile','render'])test(`actual start keeps failure readable and never starts gameplay after ${stage} error`,async()=>{const h=harness(stage);assert.equal(await h.run(),false);assert(h.h.boot.failed);assert.equal(h.h.root.hidden,false);assert(!h.log.includes('loop'));assert(!h.log.includes('tick'));});
