import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {startupHarness,flush} from './helpers/startup-harness.ts';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),shell=readFileSync(new URL('../src/startup-shell.js',import.meta.url),'utf8'),main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');
test('literal shell is standalone, readable before game UI, with static script-disabled fallback and scrollable errors',()=>{assert(html.indexOf('id="startup"')<html.indexOf('id="app"'));assert(html.indexOf('AXIOM_STARTUP_SCRIPT')<html.indexOf('/src/boot.ts'));assert.match(html,/<div id="app" inert>/);assert.match(html,/html:not\(\[data-boot-state="ready"\]\) #app\{visibility:hidden/);assert.match(html,/<noscript>/);assert.match(html,/max-height:32vh;overflow:auto/);assert.doesNotMatch(shell,/\bimport\s|\bfetch\(|localStorage|sessionStorage/);});
test('bootstrap records honest capabilities, stage elapsed and real work-unit progress without fake percent',()=>{const h=startupHarness();assert.equal(h.boot.playing,false);assert.equal(h.root.hidden,false);assert.match(h.boot.report(),/WebGPU API|webgpuAPI: true/);h.advance(750);h.boot.detail('module','Test progress',2,3);assert.match(h.boot.report(),/750 ms/);assert.match(h.boot.report(),/2\/3/);assert.match(h.nodes.get('startup-capability')!.textContent,/not proof of support/);h.boot.end('module','Loaded');h.boot.ready();assert.equal(h.boot.playing,true);assert.equal(h.root.hidden,true);h.boot.show();assert.equal(h.root.hidden,false);assert.equal(h.nodes.get('startup-close')!.hidden,false);});
test('fatal errors persist, retain first cause, and clean up exactly once',()=>{const h=startupHarness();let clean=0;h.boot.cleanup(()=>clean++);h.boot.fail('Renderer',Error('No device'));h.boot.fail('Later',Error('Second cause'));h.advance(100000);assert.equal(clean,1);assert.equal(h.boot.failed,true);assert.equal(h.root.hidden,false);assert.match(h.boot.report(),/ERROR · Renderer\nNo device/);assert.equal(h.document.documentElement.dataset.bootState,'failed');assert.equal(h.nodes.get('app')!.inert,true);assert.equal(h.timerCount,0);});
test('resource 404 / module CSS failure is readable and optional font failure does not block',()=>{const h=startupHarness();h.emit('error',{target:{tagName:'LINK',dataset:{startupOptional:'true'},href:'https://fonts.example/font.css'}});assert.equal(h.boot.failed,false);h.emit('error',{target:{tagName:'SCRIPT',src:'https://private.example/assets/game-abc.js?token=SECRET'}});assert.equal(h.boot.failed,true);assert.match(h.boot.report(),/Required SCRIPT failed to load/);assert.match(h.boot.report(),/\[asset\]\/game-abc.js/);assert.doesNotMatch(h.boot.report(),/SECRET|private.example/);});
test('unhandled rejection and runtime errors reopen the persistent diagnostic screen',()=>{for(const type of ['unhandledrejection','error']){const h=startupHarness();h.boot.end('module');h.boot.ready();h.emit(type,type==='error'?{target:h.window,error:Error('Runtime shader fault'),filename:'https://private.example/assets/main.js',lineno:8,colno:2}:{reason:Error('Runtime shader fault')});assert(h.boot.failed);assert.equal(h.root.hidden,false);assert.match(h.boot.report(),/Runtime shader fault/);if(type==='error')assert.match(h.boot.report(),/main.js:8:2/);}});
test('fatal report sanitizes private URLs, emails, credentials, payloads and long identifiers',()=>{const h=startupHarness();const value=Error('person@example.com https://private.example/room/ABCD?token=SECRET Bearer verysecret token=secret42 roomId=ROOM123 password="pass123" {"savedWorld":"private"}');value.stack='stack https://private.example/assets/game.js?token=abc sk-'+ 'a'.repeat(60);h.boot.fail('Failure',value);const report=h.boot.report();assert.doesNotMatch(report,/person@|private\.example|SECRET|verysecret|secret42|ROOM123|pass123|savedWorld|sk-a/);assert.match(report,/asset.*game.js/);assert(report.length<=18000);});
test('hostile error objects cannot break failure rendering',()=>{const h=startupHarness();h.boot.fail('Rejected',{get stack(){throw Error('getter');},toString(){throw Error('toString');}});assert.equal(h.boot.failed,true);assert.match(h.boot.report(),/Non-text error/);});
test('module deadline stops workers and blocks late readiness',()=>{const h=startupHarness();let disposed=0;h.boot.cleanup(()=>disposed++);h.advance(60001);assert(h.boot.failed);assert.equal(disposed,1);assert.match(h.boot.report(),/Timeout · Game modules/);assert.throws(()=>h.boot.ready(),/stopped/);});
test('required async deadline aborts run and ignores late completion',async()=>{const h=startupHarness();h.boot.end('module');let resolve:any;const pending=h.boot.run('gpu','GPU',()=>new Promise(r=>resolve=r),50).catch((e:Error)=>e);await flush();h.advance(51);await pending;resolve('late');await flush();assert(h.boot.failed);assert.match(h.boot.report(),/Timeout · GPU/);assert.doesNotMatch(h.boot.report(),/GPU: done/);});
test('optional async failures are degraded and do not prevent the critical gate',async()=>{const h=startupHarness();h.boot.end('module');await h.boot.run('fonts','Fonts',()=>Promise.reject(Error('Optional unavailable')),30,true);assert.equal(h.boot.failed,false);assert.match(h.boot.report(),/Fonts: degraded/);h.boot.ready();assert(h.boot.playing);});
test('navigation interruption cancels startup and back-forward restoration cannot resume it',()=>{const h=startupHarness();h.emit('pagehide',{persisted:true});assert(h.boot.failed);h.root.hidden=true;h.emit('pageshow',{persisted:true});assert.equal(h.root.hidden,false);assert.equal(h.boot.playing,false);});
test('resize and offline status stay visible without claiming download progress',()=>{const h=startupHarness();h.window.innerWidth=844;h.window.innerHeight=390;h.emit('resize');assert.match(h.boot.report(),/844 × 390/);h.context.navigator.onLine=false;h.emit('offline');assert.match(h.nodes.get('startup-capability')!.textContent,/offline/);assert.equal(h.boot.failed,false);});
test('repeat reload clicks create one whole-document retry and retain no test setting',()=>{const h=startupHarness('?startupTest=renderer-fail&backend=webgl');assert.equal(h.boot.test,'renderer-fail');assert.doesNotMatch(h.context.location.href,/startupTest/);h.boot.fail('Test','Failure');h.nodes.get('startup-webgl')!.onclick();h.nodes.get('startup-reload')!.onclick();assert.equal(h.reloads,1);assert.match(h.context.location.href,/backend=webgl/);assert.doesNotMatch(h.context.location.href,/startupTest/);});
test('copy failure supplies selectable plaintext and unknown simulation parameters are ignored',async()=>{const h=startupHarness('?startupTest=anything');assert.equal(h.boot.test,'none');await h.nodes.get('startup-copy')!.onclick();assert.equal(h.nodes.get('startup-report')!.selected,true);assert.equal(h.nodes.get('startup-details')!.open,true);assert.match(h.nodes.get('startup-action-status')!.textContent,/blocked/);});
test('capture-phase input blocks gameplay before ready but leaves diagnostics usable',()=>{const h=startupHarness();let stopped=0;h.emit('keydown',{target:{id:'world'},cancelable:true,stopImmediatePropagation(){stopped++;},preventDefault(){}});assert.equal(stopped,1);h.emit('keydown',{target:h.nodes.get('startup-copy'),cancelable:true,stopImmediatePropagation(){stopped++;},preventDefault(){}});assert.equal(stopped,2);});
test('actual module loader catches import rejection before any game entry',async()=>{const source=readFileSync(new URL('../src/boot.ts',import.meta.url),'utf8').replace("import type {} from './startup';",'').replace("import('./main')",'importGame()');const h=startupHarness();const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;await new AsyncFunction('window','importGame',source)(h.window,()=>Promise.reject(Error('Simulated 404 import')));assert(h.boot.failed);assert.match(h.boot.report(),/Simulated 404 import/);});
test('game integration uses paused worker, pose gate and direct shader/first-frame work before gameplay',()=>{const a=main.indexOf('async function start()'),b=main.indexOf('// Read-only inspection hook',a),start=main.slice(a,b);assert.match(main,/startPaused:type==='init'/);assert.match(main,/if\(!startup.playing\)\{lastPhysicsStep=m.step\?\?-1;resolveStartupPose\(\);return;/);assert.match(main,/const blocked=!startup.playing\|\|/);assert.match(main,/function persist\(notify=true\)\{if\(!startup.playing\)return false/);assert.match(start,/Promise.all\(\[physicsReadyPromise,startupPosePromise\]\)/);assert(start.indexOf('await collision')<start.indexOf('renderer.compileAsync'));assert(start.indexOf('renderer.compileAsync')<start.indexOf('renderer.render'));assert(start.indexOf('renderer.render')<start.indexOf('startup.ready()'));assert(start.indexOf('startup.ready()')<start.indexOf('renderer.setAnimationLoop(frame)'));assert.doesNotMatch(start,/frame\(\)|type:'tick'|storeSession\(/);assert.match(start,/state=applyAction\(state,\{type:'move'/);assert.match(main,/if\(ready&&startup.playing&&coopBoot/);});

test('report modal focuses keyboard entry, pauses gameplay and restores its own scope',()=>{const h=startupHarness();assert.equal(h.nodes.get('startup-status')!.focused,true);h.boot.end('module');h.boot.ready();let clears=0;h.boot.setOverlayHandler(()=>clears++);h.boot.show();assert.equal(h.boot.playing,false);assert.equal(h.nodes.get('app')!.inert,true);h.nodes.get('startup-close')!.onclick();assert.equal(h.boot.playing,true);assert.equal(clears,2);});
test('relative private URLs and common credential/room aliases are redacted',()=>{const h=startupHarness();for(const privateText of ['Fetch failed: /api/rooms/private-room-24','access_token=privateToken123','Could not join room code AB12-CD34']){const safe=h.boot.safe(privateText);assert.doesNotMatch(safe,/private-room-24|privateToken123|AB12-CD34/);}});

test('synchronous over-budget work cannot clear an overdue deadline as success',()=>{const h=startupHarness();h.block(60001);assert.throws(()=>h.boot.end('module','Late success'),/stopped/);assert.match(h.boot.report(),/including synchronous work/);assert(h.boot.failed);});
