import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import {regionalPhysics,terrainCell} from './helpers/regional-physics.ts';
test('real Rapier startup remains at simulation step zero through preload and paused teleport',async t=>{const h=await regionalPhysics(t,{startPaused:true});const initial={...h.latest};assert.equal(initial.step,0);assert.equal(initial.grounded,true,'read-only initial support probe presents a grounded avatar');const snapshots=await h.tick(120);assert(snapshots.every(s=>s.step===0&&s.x===initial.x&&s.z===initial.z&&s.feetY===initial.feetY));h.send({type:'teleport',x:34,z:34,y:0});const after=await h.tick(90);assert(after.every(s=>s.step===0));assert.equal(h.latest.x,34);h.input({x:1,analog:true,paused:false});await h.tick(1);assert.equal(h.latest.step,1);assert(h.latest.x>34);});
test('initial dynamic colliders participate in overlap recovery before the zero-tick pose is returned',async t=>{const h=await regionalPhysics(t,{startPaused:true,initialCells:[terrainCell(0,0),{key:'waterworks',revision:1,obstacles:[{x:32,y:1.5,z:32,hx:1.2,hy:1.5,hz:1.2}]}]});assert.equal(h.latest.step,0);assert(Math.hypot(h.latest.x-32,h.latest.z-32)>1.2||h.latest.feetY>=3,'resolved spawn clears the initial dynamic blocker');const before={...h.latest};await h.tick(90);assert.equal(h.latest.step,0);assert.equal(h.latest.x,before.x);assert.equal(h.latest.feetY,before.feetY);});
test('actual main snapshot handler does not tick, move, save or consume controls during renderer warmup',()=>{
 const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');const handler=main.slice(main.indexOf('worker.onmessage=(e)=>'),main.indexOf('worker.onmessageerror=',main.indexOf('worker.onmessage=(e)=>')));
 const body=`const activeConversation=null;const startup={playing:false,failed:false},worker={},state={generation:1,zone:'valley',regional:false,player:{x:3,z:4},clock:{tick:99}},before=JSON.stringify(state);let contactPractice=false,contactEvidence=[],contactDiagnostic='Ready',zoneEpoch=0,transitioning=false,lastPhysicsStep=-1,playerContact=null,movableBodies=[],contactRequestId=null,physicsMotion={},poses=0,reducerCalls=0,saves=0;const targetPosition={x:0,y:0,z:0,set(x,y,z){this.x=x;this.y=y;this.z=z;}};const validPlayerContact=()=>false,emptyPlayerContact=()=>({mode:'none'}),validMovableBodies=()=>false,contactEnabled=()=>false,resolveStartupPose=()=>poses++,applyAction=()=>{reducerCalls++;},persist=()=>{saves++;};${handler};return {snapshot(m){worker.onmessage({data:{type:'snapshot',epoch:0,step:0,x:6,z:7,feetY:2,grounded:true,...m}})},read(){return {poses,reducerCalls,saves,unchanged:JSON.stringify(state)===before,targetPosition}}};`;
 const api=new Function(stripTypeScriptTypes('function run(){'+body+'}')+';return run();')();for(let i=0;i<20;i++)api.snapshot({step:i});const result=api.read();assert.equal(result.poses,20);assert.equal(result.reducerCalls,0);assert.equal(result.saves,0);assert.equal(result.unchanged,true);assert.equal(result.targetPosition.x,6);
});

test('read-only initial support query preserves genuinely airborne spawn and zero step count',async t=>{const h=await regionalPhysics(t,{startPaused:true,y:4});assert.equal(h.latest.step,0);assert.equal(h.latest.grounded,false);assert(Math.abs(h.latest.feetY-4)<.001);await h.tick(30);assert.equal(h.latest.step,0);assert(Math.abs(h.latest.feetY-4)<.001);});
