import test from 'node:test';import assert from 'node:assert/strict';import {initializeStartupRenderer} from '../src/startup-renderer.ts';import {startupHarness,flush} from './helpers/startup-harness.ts';
function renderer(primary:()=>Promise<unknown>,fallback:()=>Promise<unknown>=async()=>{}){let disposed=0,fallbacks=0,loops=0;const gpu={isWebGPUBackend:true,init:primary,dispose:async()=>{disposed++;}},gl={isWebGLBackend:true,init:fallback,dispose:async()=>{disposed++;}};const result={backend:gpu as any,_getFallback:(_e:unknown)=>{fallbacks++;return gl;},async init(){try{await this.backend.init(this);}catch(e){this.backend=this._getFallback(e);await this.backend.init(this);}},dispose:async()=>{disposed++;},setAnimationLoop:async(_cb:null)=>{loops++;},onDeviceLost(_info:any){},counts:()=>({disposed,fallbacks,loops})};return result;}
test('real primary success is reported as WebGPU with no claimed fallback',async()=>{const h=startupHarness(),r=renderer(async()=>{});await initializeStartupRenderer(r,h.boot,false);assert.match(h.boot.report(),/WebGPU: selected/);assert.equal(r.counts().fallbacks,0);});
test('actual rejected primary preserves its precise reason and selected WebGL2 backend',async()=>{const h=startupHarness(),r=renderer(async()=>{throw Error('Adapter returned null');});await initializeStartupRenderer(r,h.boot,false);assert.match(h.boot.report(),/Adapter returned null/);assert.match(h.boot.report(),/WebGL2: selected/);assert.equal(r.counts().fallbacks,1);});
test('both backend failures remain available and selection is never invented',async()=>{const h=startupHarness(),r=renderer(async()=>{throw Error('GPU unavailable');},async()=>{throw Error('WebGL context unavailable');});await assert.rejects(initializeStartupRenderer(r,h.boot,false),/WebGL/);assert.match(h.boot.report(),/GPU unavailable/);assert.match(h.boot.report(),/WebGL context unavailable/);assert.doesNotMatch(h.boot.report(),/: selected/);assert.equal(r.counts().loops,0);});
test('late successful primary after cancel disposes once and never attempts fallback',async()=>{const h=startupHarness();let resolve:any;const r=renderer(()=>new Promise(ok=>resolve=ok));const promise=initializeStartupRenderer(r,h.boot,false);await flush();h.boot.fail('Timeout','Wait ended');assert.equal(r.counts().disposed,0);resolve();await assert.rejects(promise,/completed after/);await flush();assert.equal(r.counts().disposed,1);assert.equal(r.counts().fallbacks,0);assert.equal(h.boot.playing,false);});
test('late rejected primary after cancel cannot create a fallback backend',async()=>{const h=startupHarness();let reject:any;const r=renderer(()=>new Promise((_ok,no)=>reject=no));const promise=initializeStartupRenderer(r,h.boot,false);await flush();h.boot.fail('Cancelled','Navigation');reject(Error('Late device failure'));await assert.rejects(promise,/stopped/);assert.equal(r.counts().fallbacks,0);});
test('forced WebGL identifies an explicit choice and does not claim a WebGPU attempt',async()=>{const h=startupHarness(),r=renderer(async()=>{});r.backend={isWebGLBackend:true,init:async()=>{}};await initializeStartupRenderer(r,h.boot,true);assert.match(h.boot.report(),/Explicit backend=webgl/);assert.doesNotMatch(h.boot.report(),/WebGPU: attempted/);assert.match(h.boot.report(),/WebGL2: selected/);});
test('post-boot graphics loss raises a persistent fatal diagnostic and cleanup',async()=>{const h=startupHarness(),r=renderer(async()=>{});await initializeStartupRenderer(r,h.boot,false);h.boot.end('module');h.boot.ready();r.onDeviceLost({api:'WebGPU',message:'Driver reset',reason:'unknown',originalEvent:{}});assert(h.boot.failed);assert.equal(h.root.hidden,false);assert.match(h.boot.report(),/Driver reset/);assert.equal(r.counts().disposed,1);});
