import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {startingTown,TOWN_LAYOUT_VERSION,TOWN_LEDGER_HASH,TOWN_CENTER,TOWN_SPAWN,TOWN_OFFERS,townBalance,townStock,createTownState,validTownState,validTownCommand,purchaseTown,townReserved,safeTownPosition} from '../src/starting-town.ts';
import {createRegionalState,createConnectedState,createState,applyAction,serializeSave,parseSave,validateSave,enableStartingTown,activeObjects,type State} from '../src/world.ts';
import {generateRegionalChunk,regionalHeight,legacyRegionalHeight,regionalPlan,regionalFeatureById,regionalFeaturesNear,regionalObstaclesNear} from '../src/regional-world.ts';
import {validRegionalChunk} from '../src/regional-stream.ts';
import {worldHeight} from '../src/generation.ts';
import {TownPopulation,DEFAULT_TOWN_TUNING,validateTownTuning} from '../src/town-population.ts';
import {action} from '../server/coop-validation.ts';
import {createRoom,syncRoom,snapshot,makePlayer,playerMotion,roomObstacles} from '../server/coop-authority.ts';
import {createVertical} from '../server/coop-vertical.ts';
import {townResidents,townResidentPose} from '../src/town-residents.ts';
import {canGatherWilderness,createWildernessState,immutableWildernessState} from '../src/wilderness-state.ts';
import {loadSession,storeSession,selectRegionalSeed,type SaveStorage} from '../src/session.ts';
const seed=73129;
const atOffer=(s:State,id:string)=>({...s,player:{...s.player,...startingTown(s.seed).shops[TOWN_OFFERS.find(o=>o.id===id)!.shopIndex]!.entry}});
const buy=(s:State,id:string)=>applyAction(atOffer(s,id),{type:'town-purchase',command:{offerId:id,expectedRevision:s.town!.revision}});
const valid=(s:State)=>{assert(validateSave(s));assert.deepEqual(parseSave(serializeSave(s)),s);};

test('fresh regional player starts in Hearthmere; old valley slots remain separate',()=>{const fresh=createRegionalState(seed);assert.deepEqual(fresh.player,{x:TOWN_SPAWN.x,z:TOWN_SPAWN.z,hp:100});valid(fresh);assert(!createConnectedState(seed).town);assert(!createState(seed).town);const saved=createConnectedState(seed),data=new Map<string,string>();const storage:SaveStorage={getItem:k=>data.get(k)??null,setItem:(k,v)=>{data.set(k,v);},get length(){return data.size;},key:i=>[...data.keys()][i]??null};storeSession(storage,saved,true);assert.deepEqual(loadSession(storage),saved);const copy=[...data];assert(selectRegionalSeed(storage,seed).town);assert.deepEqual([...data],copy);});

test('finite town material exchanges and healing conserve the world through exact save/reload',()=>{let s=buy(createRegionalState(seed),'arrival-kit');assert.deepEqual(s.inventory,{scrap:3,core:0,water:1});valid(s);s=buy(s,'power-core');assert.deepEqual(s.inventory,{scrap:0,core:1,water:1});valid(s);s=buy(s,'salvage-bundle');assert.deepEqual(s.inventory,{scrap:2,core:0,water:1});valid(s);s=buy(s,'water-canister');valid(s);s={...s,player:{...s.player,hp:35}};s=buy(s,'hot-meal');assert.equal(s.player.hp,55);valid(s);assert.deepEqual(townBalance(s.town).net,{scrap:-1,core:0,water:-1});const same=atOffer(s,'arrival-kit');assert.equal(applyAction(same,{type:'town-purchase',command:{offerId:'arrival-kit',expectedRevision:0}}),same);});

test('every offer uses canonical price, finite stock, health effect and stale rejection',()=>{for(const offer of TOWN_OFFERS){let ledger=createTownState(),inventory={scrap:500,core:500,water:500};for(let n=0;n<offer.stock;n++){const context={seed,zone:'valley',player:{...startingTown(seed).shops[offer.shopIndex]!.entry,hp:10},inventory},command={offerId:offer.id,expectedRevision:ledger.revision},result=purchaseTown(ledger,context,command);assert(result);assert.equal(result.hp,Math.min(100,10+offer.heal));for(const k of ['scrap','core','water'] as const)assert.equal(result.inventory[k],inventory[k]-offer.cost[k]+offer.gain[k]);assert.equal(purchaseTown(result.town,context,command),null);ledger=result.town;inventory=result.inventory;assert(validTownState(ledger));}assert.equal(townStock(ledger,offer.id),0);assert.equal(purchaseTown(ledger,{seed,zone:'valley',player:{...startingTown(seed).shops[offer.shopIndex]!.entry,hp:10},inventory},{offerId:offer.id,expectedRevision:ledger.revision}),null);}});

test('town contracts reject malformed state, command injection, full HP treatment and invisible purchases',()=>{assert(validTownState(createTownState()));for(const value of [null,{},undefined,{...createTownState(),revision:1},{...createTownState(),extra:1},{...createTownState(),manifestHash:'bad'}])assert(!validTownState(value));for(const value of [{offerId:'arrival-kit',expectedRevision:-1},{offerId:'arrival-kit',expectedRevision:0,cost:0},{offerId:'invalid',expectedRevision:0},{offerId:'arrival-kit',expectedRevision:NaN}]){assert(!validTownCommand(value));assert.equal(action({type:'town-purchase',command:value}),null);}const s=createRegionalState(seed);for(const town of [null,{},undefined])assert(!validateSave({...s,town}));assert.equal(purchaseTown(s.town!,{...s,player:{...startingTown(seed).shops[3]!.entry,hp:100}},{offerId:'hot-meal',expectedRevision:0}),null);assert.equal(applyAction(s,{type:'town-purchase',command:{offerId:'arrival-kit',expectedRevision:0}}),s);});

test('layout has 47 usable entrances and bounded, valid terrain/collider chunks',()=>{const plan=startingTown(seed);assert.equal(plan.homes.length,40);assert.equal(plan.shops.length,7);for(const b of [...plan.homes,...plan.shops])assert.deepEqual(safeTownPosition(seed,b.entry),b.entry);let max=0;for(let cz=-4;cz<=-2;cz++)for(let cx=-4;cx<=-2;cx++){const c=generateRegionalChunk(seed,cx,cz);assert(validRegionalChunk(c,seed,cx,cz));max=Math.max(max,c.structures.length);for(let i=0;i<c.terrain.vertices.length;i+=3){const [x,y,z]=c.terrain.vertices.slice(i,i+3);assert(Math.abs(y!-regionalHeight(seed,x!,z!))<1e-5);}for(const b of c.structures){assert.equal(Math.floor(b.center.x/64),cx);assert.equal(Math.floor(b.center.z/64),cz);}}
 assert(max<=128);assert.equal(regionalHeight(seed,TOWN_SPAWN.x,TOWN_SPAWN.z),6);for(let x=-80;x<=80;x+=8)for(let z=-80;z<=80;z+=8)assert.equal(regionalHeight(seed,x,z),legacyRegionalHeight(seed,x,z));assert.equal(regionalPlan(seed).sites.length,12);assert.equal(regionalPlan(seed).roads.length,16);});

test('historical developed-land resource IDs validate, but cannot be newly gathered',()=>{let f;for(let cx=-4;cx<=-2&&!f;cx++)for(let cz=-4;cz<=-2&&!f;cz++)for(let i=0;i<44;i++){const candidate=regionalFeatureById(seed,`region:1:${seed}/chunk:${cx}:${cz}/feature:${i}`);if(candidate&&townReserved(candidate.x,candidate.z)){f=candidate;break;}}assert(f);const s=createRegionalState(seed),identity={generation:2 as const,seed,regional:{version:1 as const}},harvested={...createWildernessState(identity),harvested:[f.id],wood:f.kind==='tree'?1:0,stone:f.kind==='rock'?1:0};const ledger=immutableWildernessState(harvested,identity);valid({...s,wilderness:ledger});assert(!regionalFeaturesNear(seed,f.x,f.z).some(p=>p.id===f.id));assert(!canGatherWilderness({...s,player:{...s.player,x:f.x,z:f.z},feetY:regionalHeight(seed,f.x,f.z),obstacles:[],grounded:true},f.id));});

test('100 stable residents retain identities across projection eviction; tuning changes real population budgets',()=>{const a=townResidents(seed),b=townResidents(seed+1);assert.equal(a.length,100);assert.equal(new Set(a.map(r=>r.id)).size,100);assert.equal(new Set(a.map(r=>r.name)).size,100);assert.notDeepEqual(a,b);const p=new TownPopulation(seed);p.update(10,TOWN_CENTER,DEFAULT_TOWN_TUNING,true);assert(p.activeCount<=24);assert.equal(p.poses.length,100);const old=structuredClone(p.poses);p.update(10,{x:1000,z:1000},DEFAULT_TOWN_TUNING,true);assert.equal(p.visibleCount,0);p.update(10,TOWN_CENTER,DEFAULT_TOWN_TUNING,true);assert.deepEqual(p.poses,old);p.update(10,TOWN_CENTER,{population:7,activeBudget:8,activityScale:0},true);assert.equal(p.visibleCount,7);assert(p.activeCount<=8);assert.throws(()=>validateTownTuning({...DEFAULT_TOWN_TUNING,population:101}));});

test('co-op stale simultaneous purchase is once-only, travel only moves requester, old wall poses recover',()=>{const s=atOffer(createRegionalState(seed),'arrival-kit'),room=createRoom('host','Host',s,1000);for(let i=1;i<4;i++)room.players.push(makePlayer(`guest-${i}`,`Guest ${i}`,i,s,1000));const command={type:'town-purchase' as const,command:{offerId:'arrival-kit',expectedRevision:0}};for(const p of room.players){p.player={...s.player};p.motion=createVertical(6);syncRoom(room,p.userId,{seq:1,sessionId:p.sessionId,actions:[command]},1000);}assert.equal(room.world.town!.revision,1);assert.deepEqual(room.world.inventory,{scrap:3,core:0,water:1});valid(room.world);const host=room.players[0]!;syncRoom(room,'host',{seq:1,sessionId:host.sessionId,actions:[command]},1000);assert.equal(room.world.town!.revision,1);const others=room.players.slice(1).map(p=>({...p.player}));syncRoom(room,'host',{seq:2,sessionId:host.sessionId,actions:[{type:'visit-town'}]},1000);assert.deepEqual(room.players.slice(1).map(p=>p.player),others);assert.equal(host.player.x,TOWN_SPAWN.x);const wall=startingTown(seed).homes[0]!.boxes[0]!;host.player={x:wall.center.x,z:wall.center.z,hp:100};host.motion=createVertical(6);host.wildernessCollisionVersion=1;delete host.townCollisionVersion;playerMotion(room,host);assert.deepEqual({x:host.player.x,z:host.player.z},{x:TOWN_SPAWN.x,z:TOWN_SPAWN.z});assert.equal(host.townCollisionVersion,TOWN_LAYOUT_VERSION);});

test('town receipt arrays reject getters and holes without executing untrusted accessors',()=>{let called=0;const receipts:unknown[]=[];Object.defineProperty(receipts,'0',{get(){called++;return {offerId:'arrival-kit',hpBefore:100,hpAfter:100};},enumerable:true});assert(!validTownState({...createTownState(),revision:1,receipts}));assert.equal(called,0);assert(!validTownState({...createTownState(),revision:1,receipts:new Array(1)}));});

test('town migration preserves unchanged legacy roof support and guest purchases heal only that guest',()=>{const s=atOffer(createRegionalState(seed),'arrival-kit'),room=createRoom('host','Host',s,1000),host=room.players[0]!;host.player={x:-49,z:-21,hp:80};host.motion=createVertical(4.9708);host.wildernessCollisionVersion=1;delete host.townCollisionVersion;playerMotion(room,host);assert.equal(host.motion.feetY,4.9708);assert.equal(host.player.x,-49);assert.equal(host.player.z,-21);const guest=makePlayer('guest','Guest',1,room.world,1000);room.players.push(guest);guest.player={...s.player,hp:30};guest.motion=createVertical(6);syncRoom(room,'guest',{seq:1,sessionId:guest.sessionId,actions:[{type:'town-purchase',command:{offerId:'arrival-kit',expectedRevision:0}}]},1000);guest.player={...guest.player,...startingTown(seed).shops[3]!.entry};guest.motion=createVertical(6);syncRoom(room,'guest',{seq:2,sessionId:guest.sessionId,actions:[{type:'town-purchase',command:{offerId:'hot-meal',expectedRevision:1}}]},1000);assert.equal(guest.player.hp,50);assert.equal(host.player.hp,80);const before={...host.player};syncRoom(room,'guest',{seq:3,sessionId:guest.sessionId,actions:[{type:'visit-town'}]},1000);assert.deepEqual(host.player,before);guest.motion={...guest.motion!,grounded:false,feetY:8};const pose={...guest.player};syncRoom(room,'guest',{seq:4,sessionId:guest.sessionId,actions:[{type:'visit-town'}]},1000);assert.deepEqual(guest.player,pose);});


test('expanded housing preserves the original twenty homes, seven shops and finite ledger identity',()=>{
 const plan=startingTown(seed);
 assert.equal(plan.layoutVersion,2);assert.equal(plan.version,1);assert.equal(plan.id,`town:1:${seed}`);
 assert.equal(createHash('sha256').update(JSON.stringify({shops:plan.shops,homes:plan.homes.slice(0,20)})).digest('hex'),'3420ab064b4a8c5b5b7b182d43b6310f3e30895cc3ae48805555aa0f490742e5');
 assert.equal(TOWN_LEDGER_HASH,'f045ee5b');
 for(const home of plan.homes){assert.equal(regionalHeight(seed,home.center.x,home.center.z),6);assert.equal(regionalHeight(seed,home.entry.x,home.entry.z),6);assert.ok(townReserved(home.center.x,home.center.z));}
});
