import test from 'node:test';import assert from 'node:assert/strict';
import {WorkbenchSession,DEFAULT_WORKBENCH_CONFIG} from '../src/system-workbench-model.ts';
import {mountSystemWorkbench} from '../src/system-workbench-ui.ts';import {createWorkbenchHandler,type WorkbenchRequest,type WorkbenchResponse} from '../src/system-workbench-protocol.ts';import type {WorkbenchWorker} from '../src/system-workbench-client.ts';
/** Actual production UI handlers in a non-rendering DOM contract. No browser pixels or phone claim. */
class Element {
 tagName:string;children:Element[]=[];nodes=new Map<string,Element>();dataset:Record<string,string>={};value='';className='';hidden=false;disabled=false;title='';src='';href='';width=960;height=540;files:any[]=[];_text='';html='';draws:number=0;attributes=new Map<string,string>();onclick?:()=>void;oninput?:()=>void;onchange?:()=>unknown;onsubmit?:(e:{preventDefault:()=>void})=>void;
 constructor(tag='div'){this.tagName=tag;}get textContent():string{return this._text+this.children.map(c=>c.textContent).join('');}set textContent(v:string){this._text=String(v);this.children=[];}set innerHTML(html:string){this.html=html;this.nodes.clear();for(const match of html.matchAll(/<(\w+)([^>]*?\bid="([^"]+)"[^>]*)>/g)){const element=new Element(match[1]);element.disabled=match[2]!.includes('disabled');element.hidden=match[2]!.includes('hidden');this.nodes.set('#'+match[3],element);}}
 append(...nodes:Element[]){this.children.push(...nodes);if(this.tagName==='select'&&!this.value&&nodes[0])this.value=nodes[0].value;}replaceChildren(...nodes:Element[]){this.children=nodes;this._text='';if(this.tagName==='select')this.value=nodes[0]?.value??'';}get options(){return this.children;}
 querySelector(selector:string){return this.nodes.get(selector)??this.querySelectorAll(selector)[0]??null;}querySelectorAll(selector:string):Element[]{return this.children.flatMap(c=>[...(selector===c.tagName?[c]:[]),...c.querySelectorAll(selector)]);}setAttribute(k:string,v:string){this.attributes.set(k,v);}focus(){doc.activeElement=this;}
 getContext(){const self=this;return new Proxy({},{get:()=>()=>{self.draws++;},set:()=>true});}
}
const doc={hidden:false,activeElement:null as Element|null,createElement:(tag:string)=>new Element(tag),listeners:new Map<string,Set<()=>void>>(),addEventListener(name:string,fn:()=>void){const set=this.listeners.get(name)??new Set();set.add(fn);this.listeners.set(name,set);},removeEventListener(name:string,fn:()=>void){this.listeners.get(name)?.delete(fn);}};
class WorkerFake implements WorkbenchWorker {onmessage:WorkbenchWorker['onmessage']=null;onerror:WorkbenchWorker['onerror']=null;requests:WorkbenchRequest[]=[];terminated=false;handle=createWorkbenchHandler();postMessage(r:WorkbenchRequest){this.requests.push(r);}terminate(){this.terminated=true;}flush(index=this.requests.length-1){const response=this.handle(this.requests[index]!);this.onmessage?.({data:response} as MessageEvent<WorkbenchResponse>);}}
const settle=async()=>{await Promise.resolve();await Promise.resolve();await Promise.resolve();};
function harness(t:any,initial:Partial<import('../src/system-workbench-ui.ts').WorkbenchUIOptions>={}){const original=Object.getOwnPropertyDescriptor(globalThis,'document');Object.defineProperty(globalThis,'document',{configurable:true,value:doc});doc.hidden=false;doc.activeElement=null;doc.listeners.clear();const root=new Element(),workers:WorkerFake[]=[],downloads:{name:string;text:string}[]=[],frames=new Map<number,FrameRequestCallback>();let next=0;const ui=mountSystemWorkbench(root as any,{revision:'test',...initial,makeWorker:()=>{const w=new WorkerFake();workers.push(w);return w;},download:(name,text)=>downloads.push({name,text}),requestFrame:fn=>{frames.set(++next,fn);return next;},cancelFrame:id=>frames.delete(id)});const get=(id:string)=>{const e=root.querySelector('#'+id);assert(e,id);return e;};t.after(()=>{ui.dispose();if(original)Object.defineProperty(globalThis,'document',original);else delete (globalThis as any).document;});return {root,workers,downloads,frames,ui,get,worker:()=>workers.at(-1)!,submit:()=>get('wb-form').onsubmit!({preventDefault(){}}),frame(now:number){const entry=[...frames.entries()][0];assert(entry);frames.delete(entry[0]);entry[1](now);}};}
test('real standalone controls display actual model results, step once under repeated clicks and export',async t=>{const h=harness(t);assert.equal(h.worker().requests[0]!.kind,'create');assert(h.get('wb-step').disabled);h.worker().flush();await settle();assert.match(h.get('wb-name').textContent,/Alder/);assert(h.get('wb-map').draws>0);assert.equal(h.ui.getSnapshot()!.tick,0);h.get('wb-step').onclick!();h.get('wb-step').onclick!();assert.equal(h.worker().requests.length,2);assert(h.get('wb-step').disabled);h.worker().flush();await settle();assert.equal(h.ui.getSnapshot()!.tick,1);h.get('wb-export').onclick!();h.worker().flush();await settle();assert.equal(h.downloads.length,1);const report=JSON.parse(h.downloads[0]!.text);assert.equal(report.finalTick,1);assert.equal(report.visualReview,'not-reviewed');assert.equal(report.config.seed,73129);assert(!('state' in report));});
test('Pause remains available while a run batch is pending and background time does not resume it',async t=>{const h=harness(t);h.worker().flush();await settle();h.get('wb-play').onclick!();h.frame(0);h.frame(250);assert.equal(h.worker().requests.length,2);assert.equal(h.get('wb-play').textContent,'Pause');assert.equal(h.get('wb-play').disabled,false);h.get('wb-play').onclick!();h.worker().flush();await settle();h.frame(1000);assert.equal(h.worker().requests.length,2);assert.equal(h.get('wb-play').textContent,'Run');h.get('wb-play').onclick!();h.frame(1250);doc.hidden=true;for(const fn of doc.listeners.get('visibilitychange')??[])fn();h.frame(100000);doc.hidden=false;h.frame(200000);assert.equal(h.worker().requests.length,2);assert.equal(h.get('wb-play').textContent,'Run');});
test('reset cancels pending work and stale old replies cannot overwrite the new seed',async t=>{const h=harness(t);h.worker().flush();await settle();h.get('wb-minute').onclick!();const old=h.worker(),late=old.onmessage!;h.get('wb-seed').value='42';h.get('wb-seed').oninput!();h.submit();assert(old.terminated);assert.equal(h.workers.length,2);late({data:old.handle(old.requests[1]!)} as MessageEvent<WorkbenchResponse>);await settle();assert.equal(h.ui.getSnapshot(),undefined);h.worker().flush();await settle();assert.equal(h.get('wb-seed').value,'42');assert.equal(h.ui.getSnapshot()!.tick,0);h.get('wb-seed').value='-1';h.get('wb-seed').oninput!();h.submit();assert.match(h.get('wb-status').textContent,/valid unsigned seed/);assert.equal(h.workers.length,2);assert(h.get('wb-step').disabled);});
test('editing during generation keeps staged input and marks the older visible result',async t=>{const h=harness(t);h.get('wb-system').value='water';h.get('wb-system').onchange!();assert.equal(h.get('wb-target').options.length,6);h.worker().flush();await settle();assert.equal(h.get('wb-system').value,'water');assert.equal(h.get('wb-target').options.length,6);assert.match(h.get('wb-status').textContent,/Inputs changed/);assert(h.get('wb-play').disabled);h.submit();h.worker().flush();await settle();assert.equal(h.ui.getSnapshot()!.actors.length,2);assert.equal(h.get('wb-play').disabled,false);});
test('strict round-trip feedback expires on a step; import replays and reports matching evidence',async t=>{const h=harness(t);h.worker().flush();await settle();h.get('wb-reload').onclick!();h.worker().flush();await settle();assert.match(h.get('wb-replay-status').textContent,/ROUND-TRIP MATCH/);h.get('wb-second').onclick!();h.worker().flush();await settle();assert.match(h.get('wb-replay-status').textContent,/State changed/);h.get('wb-export').onclick!();h.worker().flush();await settle();const text=h.downloads[0]!.text;h.get('wb-import').files=[{size:text.length,text:async()=>text}];await h.get('wb-import').onchange!();assert.equal(h.workers.length,2);h.worker().flush();await settle();assert.match(h.get('wb-replay-status').textContent,/REPLAY MATCH/);assert.equal(h.ui.getSnapshot()!.tick,4);});
test('a late file read cannot replace newer edited inputs and malformed imports do not destroy the session',async t=>{const h=harness(t);h.worker().flush();await settle();h.get('wb-export').onclick!();h.worker().flush();await settle();const text=h.downloads[0]!.text;let resolve!:(text:string)=>void;h.get('wb-import').files=[{size:10,text:()=>new Promise(r=>resolve=r)}];const pending=h.get('wb-import').onchange!();h.get('wb-seed').value='7';h.get('wb-seed').oninput!();resolve(text);await pending;assert.equal(h.workers.length,1);assert.equal(h.get('wb-seed').value,'7');h.get('wb-import').files=[{size:10,text:async()=>'{'}];await h.get('wb-import').onchange!();assert.match(h.get('wb-replay-status').textContent,/JSON report/);assert.equal(h.workers.length,1);});
test('graphics loads lazily, repeated tabs do not reload the scene, and leaving the stage releases it',async t=>{const h=harness(t);h.worker().flush();await settle();h.get('wb-subject').value='animation';assert.equal(h.get('wb-visual-host').children.length,0);h.get('wb-visual-tab').onclick!();const child=h.get('wb-visual-host').children[0]!;assert.equal(child.src,'./visual-review.html?subject=animation');h.get('wb-visual-tab').onclick!();assert.equal(h.get('wb-visual-host').children[0],child);assert(h.get('wb-simulation').hidden);h.get('wb-subject').value='cave';h.get('wb-subject').onchange!();assert.match(h.get('wb-visual-host').children[0]!.src,/subject=cave/);h.get('wb-simulation-tab').onclick!();assert.equal(h.get('wb-visual-host').children.length,0);assert.equal(h.get('wb-simulation').hidden,false);});
test('BFCache suspend and resume retain exact paused model state; disposal rejects new work',async t=>{const h=harness(t);h.worker().flush();await settle();h.get('wb-second').onclick!();h.worker().flush();await settle();const fingerprint=h.ui.getSnapshot()!.fingerprint;h.get('wb-play').onclick!();h.ui.suspend();assert.equal(h.frames.size,0);assert.equal(h.get('wb-play').textContent,'Run');assert(!h.worker().terminated);h.ui.resume();assert.equal(h.frames.size,1);assert.equal(h.ui.getSnapshot()!.fingerprint,fingerprint);h.frame(100000);assert.equal(h.ui.getSnapshot()!.tick,4);h.ui.dispose();assert(h.worker().terminated);const count=h.workers.length;h.submit();h.get('wb-visual-tab').onclick!();assert.equal(h.workers.length,count);assert.equal(h.get('wb-visual-host').children.length,0);});
test('worker failure surfaces a reset instruction without an indefinitely busy retry',async t=>{const h=harness(t);h.worker().flush();await settle();h.get('wb-step').onclick!();h.worker().onerror?.({message:'worker crashed'} as ErrorEvent);await settle();assert.match(h.get('wb-status').textContent,/reset/);assert(h.worker().terminated);h.get('wb-step').onclick!();await settle();assert.match(h.get('wb-status').textContent,/reset/);assert.equal(h.get('wb-step').disabled,false);h.submit();h.worker().flush();await settle();assert.equal(h.ui.getSnapshot()!.tick,0);});

test('fresh browser scenarios use regional rainfall and water weather is a read-only projection',async t=>{
 const h=harness(t),first=h.worker().requests[0]!;assert.equal(first.kind,'create');if(first.kind==='create')assert.equal(first.config.rainfall,'regional');assert.equal(h.get('wb-rainfall').value,'regional');h.worker().flush();await settle();assert(h.get('wb-weather').hidden,'trade has no weather card');
 h.get('wb-system').value='water';h.get('wb-system').onchange!();h.submit();h.worker().flush();await settle();assert.equal(h.get('wb-weather').hidden,false);assert.match(h.get('wb-weather-phase').textContent,/Regional/);assert.equal(h.get('wb-weather-description').textContent,h.ui.getSnapshot()!.weather!.description);assert.match(h.get('wb-weather-time').textContent,/Drought time.*Expected rainfall change/);assert.equal(h.get('wb-weather').querySelectorAll('button').length,0);
 assert.match(h.root.html,/Existing campaigns keep their original rainfall/);assert.match(h.root.html,/Choose Water \+ Regional to observe drought/);
});
test('rainfall edits made during pending work stay staged and disable stale controls',async t=>{
 const h=harness(t);h.get('wb-rainfall').value='legacy';h.get('wb-rainfall').onchange!();h.worker().flush();await settle();assert.equal(h.get('wb-rainfall').value,'legacy');assert.match(h.get('wb-status').textContent,/Inputs changed/);assert(h.get('wb-step').disabled);
 h.submit();const reset=h.worker().requests[0]!;assert.equal(reset.kind,'create');if(reset.kind==='create')assert(!Object.hasOwn(reset.config,'rainfall'));h.worker().flush();await settle();assert.equal(h.get('wb-step').disabled,false);
 h.get('wb-minute').onclick!();const old=h.worker(),late=old.onmessage!;h.get('wb-rainfall').value='regional';h.get('wb-rainfall').onchange!();h.submit();late({data:old.handle(old.requests.at(-1)!)} as MessageEvent<WorkbenchResponse>);await settle();assert.equal(h.get('wb-rainfall').value,'regional');assert.equal(h.ui.getSnapshot(),undefined);h.worker().flush();await settle();assert.equal(h.get('wb-rainfall').value,'regional');assert.equal(h.ui.getSnapshot()!.tick,0);
});
test('replay restores the report rainfall choice including absent historical config',async t=>{
 const h=harness(t);h.worker().flush();await settle();
 for(const rainfall of [undefined,'regional'] as const){const s=new WorkbenchSession({...DEFAULT_WORKBENCH_CONFIG,system:'water',...(rainfall?{rainfall}:{})},'test');s.advance(4);const report=s.report();if(!rainfall)delete report.snapshot.weather;const text=JSON.stringify(report);h.get('wb-import').files=[{size:text.length,text:async()=>text}];await h.get('wb-import').onchange!();assert.equal(h.get('wb-rainfall').value,rainfall??'legacy');h.worker().flush();await settle();assert.match(h.get('wb-replay-status').textContent,/REPLAY MATCH/);assert.equal(h.ui.getSnapshot()!.weather!.model,rainfall??'legacy');assert.equal(h.ui.getSnapshot()!.tick,4);}
});
test('a late replay file cannot replace a newer staged rainfall choice',async t=>{
 const h=harness(t);h.worker().flush();await settle();const text=JSON.stringify(new WorkbenchSession(DEFAULT_WORKBENCH_CONFIG,'test').report());let resolve!:(value:string)=>void;h.get('wb-import').files=[{size:text.length,text:()=>new Promise(r=>resolve=r)}];const pending=h.get('wb-import').onchange!();h.get('wb-rainfall').value='legacy';h.get('wb-rainfall').onchange!();resolve(text);await pending;assert.equal(h.workers.length,1);assert.equal(h.get('wb-rainfall').value,'legacy');assert.match(h.get('wb-status').textContent,/Inputs changed/);
});

test('settlement selection has one target and renders the empty zero-clock integrated state',async t=>{
 const h=harness(t);assert.match(h.root.html,/<option value="settlement">Settlement · freight, water and farming/);
 h.get('wb-target').value='2';h.get('wb-system').value='settlement';h.get('wb-system').onchange!();assert.equal(h.get('wb-target').options.length,1);assert.equal(h.get('wb-target').value,'0');
 h.worker().flush();await settle();assert.equal(h.get('wb-target').options.length,1);assert(h.get('wb-step').disabled);assert(h.get('wb-causes-card').hidden,'the old trade result has no integrated causes');
 h.submit();h.worker().flush();await settle();const snapshot=h.ui.getSnapshot()!;
 assert.equal(snapshot.name,'Alder–Pine settlement');assert.equal(snapshot.tick,0);assert.equal(snapshot.setupSeconds,0);assert.equal(h.get('wb-target').options.length,1);assert.equal(h.get('wb-target').options[0]!.textContent,snapshot.name);
 assert.match(h.get('wb-setup').textContent,/Starts empty at 0 s/);assert.match(h.get('wb-setup').textContent,/No setup time or fixture material, water or food grants/);
 assert.equal(snapshot.causes?.length,4);assert.equal(h.get('wb-causes-card').hidden,false);assert.equal(h.get('wb-causes').children.length,4);
 for(const [i,cause]of snapshot.causes!.entries()){const row=h.get('wb-causes').children[i]!;assert.equal(row.dataset.target,cause.id);assert.equal(row.children[0]!.textContent,`${cause.name} · ${cause.phase}`);assert.equal(row.children[1]!.textContent,cause.cause);}
 assert.equal(h.get('wb-causes').querySelectorAll('button').length,0);assert.equal(h.get('wb-weather').hidden,false);assert.equal(h.get('wb-weather-description').textContent,snapshot.weather!.description);
 assert.equal(h.get('wb-actors').children.length,snapshot.actors.length);assert.equal(h.get('wb-inventory').children.length,Object.keys(snapshot.inventory).length);assert.equal(h.get('wb-ledger').textContent,JSON.stringify(snapshot.ledger,null,2));
});
test('settlement action IDs pass unchanged and repeated clicks record one replayable command',async t=>{
 const h=harness(t);h.get('wb-system').value='settlement';h.get('wb-system').onchange!();h.submit();h.worker().flush();await settle();
 const initial=h.ui.getSnapshot()!,actions=initial.actions;assert.equal(new Set(actions.map(a=>a.id)).size,actions.length);const action=actions.find(a=>a.enabled)!;assert(action);
 const button=h.get('wb-actions').querySelectorAll('button').find(b=>b.dataset.action===action.id)!;assert(button);const before=h.worker().requests.length;button.onclick!();button.onclick!();assert.equal(h.worker().requests.length,before+1);
 const request=h.worker().requests.at(-1)!;assert.equal(request.kind,'action');if(request.kind==='action')assert.equal(request.action,action.id);assert(button.disabled);h.worker().flush();await settle();
 h.get('wb-export').onclick!();h.worker().flush();await settle();const text=h.downloads[0]!.text,report=JSON.parse(text);assert.equal(report.version,2);assert.equal(report.config.system,'settlement');assert.equal(report.events.length,1);assert.equal(report.events[0].accepted,true);assert.deepEqual(Object.keys(report.events[0]).sort(),['accepted','action','domain','targetId','tick']);assert.equal(`${report.events[0].domain}/${report.events[0].targetId}/${report.events[0].action}`,action.id);
 const fingerprint=h.ui.getSnapshot()!.fingerprint;h.get('wb-import').files=[{size:text.length,text:async()=>text}];await h.get('wb-import').onchange!();assert.equal(h.get('wb-system').value,'settlement');assert.equal(h.get('wb-target').options.length,1);h.worker().flush();await settle();assert.match(h.get('wb-replay-status').textContent,/REPLAY MATCH/);assert.equal(h.ui.getSnapshot()!.fingerprint,fingerprint);
});
test('settlement causes are cleared on reset and stay absent for legacy system reports',async t=>{
 const h=harness(t);h.get('wb-system').value='settlement';h.get('wb-system').onchange!();h.submit();h.worker().flush();await settle();assert.equal(h.get('wb-causes').children.length,4);
 const action=h.get('wb-actions').querySelectorAll('button').find(b=>!b.disabled)!;h.get('wb-system').value='trade';h.get('wb-system').onchange!();assert(action.disabled,'staged inputs disable old target actions');h.submit();assert(h.get('wb-causes-card').hidden);assert.equal(h.get('wb-causes').children.length,0);h.worker().flush();await settle();
 assert(h.get('wb-causes-card').hidden);assert.equal(h.get('wb-target').options.length,3);assert.equal(h.ui.getSnapshot()!.causes,undefined);assert.doesNotMatch(h.get('wb-setup').textContent,/Starts empty/);
 h.get('wb-export').onclick!();h.worker().flush();await settle();const report=JSON.parse(h.downloads[0]!.text);assert.equal(report.version,1);assert(!Object.hasOwn(report.snapshot,'causes'));
});


test('fresh scenarios select regional freight and display production road conditions and repair-aware ETA',async t=>{
 const h=harness(t),create=h.worker().requests[0]!;assert.equal(create.kind,'create');if(create.kind==='create')assert.equal(create.config.travel,'regional');assert.equal(h.get('wb-travel').value,'regional');h.worker().flush();await settle();
 assert.equal(h.get('wb-freight-card').hidden,false);assert.equal(h.get('wb-freight').children.length,1);assert.match(h.get('wb-freight').textContent,/Regional/);assert.match(h.get('wb-freight').textContent,/Road wetness.*Travel speed/);assert.equal(h.get('wb-freight').querySelectorAll('button').length,0);
 for(let i=0;i<5;i++){h.get('wb-minute').onclick!();h.worker().flush();await settle();}assert.equal(h.ui.getSnapshot()!.phase,'blocked');assert.match(h.get('wb-freight').textContent,/Repair required before delivery ETA/);
 h.get('wb-system').value='settlement';h.get('wb-system').onchange!();h.submit();assert(h.get('wb-freight-card').hidden);h.worker().flush();await settle();assert.equal(h.get('wb-freight').children.length,2);assert.equal(h.ui.getSnapshot()!.freight!.length,2);
});
test('travel edits pause stale results, ignore replaced work and restore imported report choice',async t=>{
 const h=harness(t);h.get('wb-travel').value='legacy';h.get('wb-travel').onchange!();h.worker().flush();await settle();assert.equal(h.get('wb-travel').value,'legacy');assert(h.get('wb-step').disabled);assert.match(h.get('wb-status').textContent,/Inputs changed/);
 h.submit();const create=h.worker().requests[0]!;if(create.kind==='create')assert(!Object.hasOwn(create.config,'travel'));h.worker().flush();await settle();assert(h.get('wb-freight-card').hidden);assert.equal(h.get('wb-step').disabled,false);
 h.get('wb-minute').onclick!();const old=h.worker(),late=old.onmessage!;h.get('wb-travel').value='regional';h.get('wb-travel').onchange!();h.submit();late({data:old.handle(old.requests.at(-1)!)} as MessageEvent<WorkbenchResponse>);await settle();assert.equal(h.ui.getSnapshot(),undefined);h.worker().flush();await settle();assert.equal(h.get('wb-travel').value,'regional');
 for(const travel of [undefined,'regional'] as const){const s=new WorkbenchSession({...DEFAULT_WORKBENCH_CONFIG,...(travel?{travel}:{})},'test');s.advance(4);const text=JSON.stringify(s.report());h.get('wb-import').files=[{size:text.length,text:async()=>text}];await h.get('wb-import').onchange!();assert.equal(h.get('wb-travel').value,travel??'legacy');h.worker().flush();await settle();assert.match(h.get('wb-replay-status').textContent,/REPLAY MATCH/);assert.equal(h.get('wb-freight-card').hidden,!travel);}
 let finish!:(text:string)=>void;const text=JSON.stringify(new WorkbenchSession(DEFAULT_WORKBENCH_CONFIG,'test').report()),count=h.workers.length;h.get('wb-import').files=[{size:text.length,text:()=>new Promise(resolve=>finish=resolve)}];const pending=h.get('wb-import').onchange!();h.get('wb-travel').value='regional';h.get('wb-travel').onchange!();finish(text);await pending;assert.equal(h.workers.length,count);assert.equal(h.get('wb-travel').value,'regional');assert(h.get('wb-step').disabled);
});


test('developer hub opens each requested runnable disposable scenario with exact seed and optional canister setup',async t=>{
 for(const system of ['water','trade','food','settlement'] as const){const h=harness(t,{initialSeed:42,initialSystem:system});const request=h.worker().requests[0]!;assert.equal(request.kind,'create');if(request.kind==='create'){assert.equal(request.config.seed,42);assert.equal(request.config.system,system);assert.equal(request.config.rainfall,'regional');assert.equal(request.config.travel,'regional');}h.worker().flush();await settle();assert(h.ui.getSnapshot());assert.equal(h.ui.getSnapshot()!.tick,0);assert.equal(h.get('wb-step').disabled,false);h.ui.dispose();}
 const h=harness(t,{initialSystem:'food',initialIrrigation:'canister'});h.worker().flush();await settle();assert.equal(h.ui.getSnapshot()!.irrigation!.canisters,1);assert(h.ui.getSnapshot()!.actions.some(a=>a.id==='irrigate-farm'&&a.enabled));
});
