import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import {WorkbenchSession,DEFAULT_WORKBENCH_CONFIG,validateWorkbenchConfig,workbenchGeometry,workbenchTargets,parseWorkbenchReport,replayWorkbench,WORKBENCH_MAX_EVENTS} from '../src/system-workbench-model.ts';
import {createSettlementWorkbench,settlementPlan,settlementInteractions,settlementActionId} from '../src/regional-settlement-workbench.ts';
import {serializeSave} from '../src/world.ts';import {createWorkbenchHandler} from '../src/system-workbench-protocol.ts';
const config={...DEFAULT_WORKBENCH_CONFIG,system:'settlement' as const,rainfall:'regional' as const};
test('integrated setup starts every production clock and ownership bucket genuinely empty',()=>{
 const original=createSettlementWorkbench(config.seed,config.rainfall),before=serializeSave(original),s=new WorkbenchSession(config,'test'),snap=s.snapshot(),p=settlementPlan(config.seed);
 assert.equal(s.setupSeconds,0);for(const clock of [original.frontierTrade!,original.frontierSupply!,original.frontierFood!]){assert.equal(clock.ticks,0);assert.equal(clock.revision,0);assert.deepEqual(clock.receipts,[]);}
 assert(original.frontierTrade!.routes.every(r=>r.sourceStartedAt===null&&r.builtAt===null&&r.remaining===12&&r.stock+r.reserved+r.cargo+r.destinationStock+r.embodied+r.withdrawn===0));
 assert(original.frontierSupply!.outposts.every(o=>o.buildStartedAt===null&&o.captured+o.water+o.spilled+o.consumed+o.delivered.wood+o.delivered.stone===0));
 assert(original.frontierFood!.farms.every(f=>f.startedAt===null&&f.starterGranted+f.harvested+f.meals+f.waterCaptured+f.waterLost+f.sourceSpilled===0&&f.seeds===2));
 assert.deepEqual(original.inventory,{scrap:0,core:0,water:0});assert.equal(original.wilderness,undefined);assert.equal(snap.actors.length,12);assert.equal(snap.causes!.length,4);assert(snap.checks.every(c=>c.pass));assert.equal(snap.actions.filter(a=>a.enabled).length,2);assert.equal(snap.inventory.productionStarterMeals,0);assert.equal(snap.inventory.harvestedMealsMinimum,0);assert.equal(serializeSave(original),before);
 assert.equal(p.collector.cost.wood,4);assert.equal(p.collector.cost.stone,3);assert.equal(p.farm.siteId,p.collector.id);assert.deepEqual(workbenchTargets(config.seed,'settlement'),['Alder–Pine settlement']);assert.throws(()=>validateWorkbenchConfig({...config,index:1}));
});
test('target-specific actions cannot dispatch to another route or a bare legacy action kind',()=>{
 const s=new WorkbenchSession(config,'test'),p=settlementPlan(config.seed),before=s.digest(),id=settlementActionId('trade',p.sources[0]!.id,'start-source');assert.throws(()=>s.action('start-source'));assert.throws(()=>s.action(id.replace('/trade/0/','/trade/2/')));assert.equal(s.digest(),before);assert(s.action(id));assert(!s.action(id));
 const ledger=s.snapshot().ledger as any;assert.equal(ledger.trade[0].sourceStartedAt,0);assert.equal(ledger.trade[1].sourceStartedAt,null);assert.equal(ledger.collector.buildStartedAt,null);assert.equal(ledger.farm.startedAt,null);assert(s.verifyReload().pass);s.advance(80);assert.equal(s.report().reload.checked,false);assert(replayWorkbench(s.report(),'test').result.match);
});
test('v2 target journals are explicit and never reinterpret old or unknown target encodings',()=>{
 const s=new WorkbenchSession(config,'test');s.assist();s.advance(40);const r=s.report();assert.equal(r.version,2);assert.equal(r.eventEncoding,'target-v1');assert.equal(r.events.length,2);for(const e of r.events)assert.deepEqual(Object.keys(e).sort(),['accepted','action','domain','targetId','tick']);assert(replayWorkbench(r,'test').result.match);
 for(const mutate of [(v:any)=>v.version=1,(v:any)=>delete v.eventEncoding,(v:any)=>v.eventEncoding='future',(v:any)=>delete v.events[0].targetId,(v:any)=>v.events[0].domain='food',(v:any)=>v.events[0].targetId='region:1:73129/trade/2/source',(v:any)=>v.events[0].extra='ignored',(v:any)=>v.events[0].action='build',(v:any)=>v.events[0].targetId='region:1:42/trade/0/source']){const bad=structuredClone(r);mutate(bad);assert.throws(()=>parseWorkbenchReport(JSON.stringify(bad)));}
 const old=new WorkbenchSession(DEFAULT_WORKBENCH_CONFIG,'test');old.action('clear-route');const v1=old.report();assert.equal(v1.version,1);assert(!('eventEncoding' in v1));assert(!('targetId' in v1.events[0]!));const ambiguous=structuredClone(v1);ambiguous.events[0]!.targetId=r.events[0]!.targetId;assert.throws(()=>parseWorkbenchReport(JSON.stringify(ambiguous)));
 const changed=structuredClone(r);changed.events[0]!.accepted=false;assert.match(replayWorkbench(changed,'test').result.firstDifference!,/acceptance at tick 0/);
});
test('integrated geometry keeps bounded chunks while retaining both actual freight paths and local routes',()=>{
 for(const seed of [0,73129,0xffffffff]){const p=settlementPlan(seed),route=workbenchGeometry({...config,seed}),local=workbenchGeometry({...config,seed,view:'settlement'}),chunk=workbenchGeometry({...config,seed,view:'chunk'});assert.equal(route.chunks.length,0);assert.equal(route.paths.length,5);assert.equal(route.markers.length,6);assert.deepEqual(route.paths[0]!.points,p.routes[0]!.points);assert.deepEqual(route.paths[1]!.points,p.routes[1]!.points);assert.equal(local.bounds.maxX-local.bounds.minX,64);assert(local.chunks.length<=4);assert.equal(chunk.chunks.length,1);}
});
test('target journal caps and worker failed-target responses leave real production state unchanged',()=>{
 const h=createWorkbenchHandler();assert(h({id:1,kind:'create',config,revision:'test'}).ok);assert(!h({id:2,kind:'action',action:'build-store'}).ok);assert.equal(h({id:3,kind:'report'}).report!.events.length,0);
 const s=new WorkbenchSession(config,'test'),blocked=settlementInteractions(createSettlementWorkbench(config.seed)).find(a=>a.kind==='build-store')!;for(let i=0;i<WORKBENCH_MAX_EVENTS;i++)assert.equal(s.action(blocked.id),false);const before=s.digest();assert.throws(()=>s.action(blocked.id),/full/);assert.equal(s.digest(),before);assert(s.snapshot().actions.every(a=>!a.enabled));assert(replayWorkbench(s.report(),'test').result.match);
});
test('historical one-hour settlement chain proves drought recovery, fifteen reload stages and harvested meals',{timeout:180000},()=>{
 const dir=mkdtempSync(join(tmpdir(),'axiom-settlement-'));try{const run=spawnSync(process.execPath,['--experimental-strip-types','scripts/verify-settlement-workbench.mts',dir,'--travel','legacy'],{cwd:new URL('..',import.meta.url),encoding:'utf8',timeout:175000});assert.equal(run.status,0,run.stderr||run.stdout);const e=JSON.parse(readFileSync(join(dir,'settlement-measurements.json'),'utf8')),r=JSON.parse(readFileSync(join(dir,'settlement-report.json'),'utf8'));assert.equal(e.finalFingerprint,'b3960d09');assert.equal(e.setupSeconds,0);assert(e.dryShortage);assert(e.recovery.drinkingBeforeOverflow);assert.equal(e.reloads.length,15);assert.equal(e.finalInventory.harvested,36);assert.equal(e.finalInventory.meals,30);assert.equal(e.finalInventory.harvestedMealsMinimum,26);assert.equal(r.finalTick,14400);assert(e.exactReplay);assert.equal(e.earliestDifferenceProbe,'State first differs at sampled tick 160');assert(e.footprint.saveBytes<80000);assert(e.footprint.reportBytes<100000);}finally{rmSync(dir,{recursive:true,force:true});}
});


test('regional travel settlement keeps empty clocks, actual weather freight and an exact harvested-food loop',{timeout:180000},()=>{
 const fresh=createSettlementWorkbench(config.seed,config.rainfall,'regional');assert.equal(fresh.frontierTrade!.version,2);assert.equal(fresh.frontierTrade!.ticks,0);assert.equal(fresh.frontierSupply!.ticks,0);assert.equal(fresh.frontierFood!.ticks,0);
 const s=new WorkbenchSession({...config,travel:'regional'},'test'),old=new WorkbenchSession(config,'test');assert.equal(s.setupSeconds,0);assert.equal(s.snapshot().freight!.length,2);assert.equal(old.snapshot().freight,undefined);assert.deepEqual(s.geometry(),old.geometry());assert.notEqual(s.digest(),old.digest());
 const dir=mkdtempSync(join(tmpdir(),'axiom-settlement-regional-travel-'));try{const run=spawnSync(process.execPath,['--experimental-strip-types','scripts/verify-settlement-workbench.mts',dir],{cwd:new URL('..',import.meta.url),encoding:'utf8',timeout:175000});assert.equal(run.status,0,run.stderr||run.stdout);const e=JSON.parse(readFileSync(join(dir,'settlement-measurements.json'),'utf8')),r=JSON.parse(readFileSync(join(dir,'settlement-report.json'),'utf8'));assert.equal(e.travel,'regional');assert.equal(r.config.travel,'regional');assert.equal(e.setupSeconds,0);assert.equal(e.reloads.length,15);assert.deepEqual([...e.travelConditions].sort(),['dry','drying','wet']);assert.equal(e.travelReloads.length,3);assert(e.routeTravel.every((road:any)=>road.maxWetness>0&&road.minSpeed<road.baseSpeed));assert(e.finalInventory.harvested>0);assert(e.finalInventory.harvestedMealsMinimum>0);assert.equal(r.finalTick,14400);assert(e.exactReplay);assert.equal(e.earliestDifferenceProbe,'State first differs at sampled tick 160');assert(e.maxBalanceError<.00001);}finally{rmSync(dir,{recursive:true,force:true});}
});
