import test from 'node:test';import assert from 'node:assert/strict';
import {WorkbenchSession,DEFAULT_WORKBENCH_CONFIG,validateWorkbenchConfig,parseWorkbenchReport,replayWorkbench} from '../src/system-workbench-model.ts';
import {worldObjects} from '../src/world.ts';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import {mountSystemWorkbench} from '../src/system-workbench-ui.ts';import {createWorkbenchHandler,type WorkbenchRequest,type WorkbenchResponse} from '../src/system-workbench-protocol.ts';import type {WorkbenchWorker} from '../src/system-workbench-client.ts';
/** Actual production UI handlers in a non-rendering DOM contract. No browser pixels or phone claim. */
class Element {
 tagName:string;children:Element[]=[];nodes=new Map<string,Element>();dataset:Record<string,string>={};value='';className='';hidden=false;disabled=false;title='';src='';href='';width=960;height=540;files:any[]=[];_text='';html='';draws:number=0;attributes=new Map<string,string>();onclick?:()=>void;oninput?:()=>void;onchange?:()=>unknown;onsubmit?:(e:{preventDefault:()=>void})=>void;
 constructor(tag='div'){this.tagName=tag;}get textContent():string{return this._text+this.children.map(c=>c.textContent).join('');}set textContent(v:string){this._text=String(v);this.children=[];}set innerHTML(html:string){this.html=html;this.nodes.clear();for(const match of html.matchAll(/<(\w+)([^>]*?\bid="([^"]+)"[^>]*)>/g)){const element=new Element(match[1]);element.disabled=match[2]!.includes('disabled');element.hidden=match[2]!.includes('hidden');this.nodes.set('#'+match[3],element);}}
 append(...nodes:Element[]){this.children.push(...nodes);if(this.tagName==='select'&&!this.value&&nodes[0])this.value=nodes[0].value;}replaceChildren(...nodes:Element[]){this.children=nodes;this._text='';if(this.tagName==='select')this.value=nodes[0]?.value??'';}get options(){return this.children;}
 querySelector(selector:string){return this.nodes.get(selector)??this.querySelectorAll(selector)[0]??null;}querySelectorAll(selector:string):Element[]{return this.children.flatMap(c=>[...(selector===c.tagName?[c]:[]),...c.querySelectorAll(selector)]);}setAttribute(k:string,v:string){this.attributes.set(k,v);}focus(){doc.activeElement=this;}
 getContext(){const self=this;return new Proxy({},{get:()=>()=>{self.draws++;},set:()=>true});}
}
const doc={hidden:false,activeElement:null as Element|null,createElement:(tag:string)=>new Element(tag),listeners:new Map<string,Set<()=>void>>(),addEventListener(name:string,fn:()=>void){const set=this.listeners.get(name)??new Set();set.add(fn);this.listeners.set(name,set);},removeEventListener(name:string,fn:()=>void){this.listeners.get(name)?.delete(fn);}};
class WorkerFake implements WorkbenchWorker {onmessage:WorkbenchWorker['onmessage']=null;onerror:WorkbenchWorker['onerror']=null;requests:WorkbenchRequest[]=[];terminated=false;handle=createWorkbenchHandler();postMessage(r:WorkbenchRequest){this.requests.push(r);}terminate(){this.terminated=true;}flush(index=this.requests.length-1){const response=this.handle(this.requests[index]!);this.onmessage?.({data:response} as MessageEvent<WorkbenchResponse>);}}
const settle=async()=>{await Promise.resolve();await Promise.resolve();await Promise.resolve();};
function harness(t:any){const original=Object.getOwnPropertyDescriptor(globalThis,'document');Object.defineProperty(globalThis,'document',{configurable:true,value:doc});doc.hidden=false;doc.activeElement=null;doc.listeners.clear();const root=new Element(),workers:WorkerFake[]=[],downloads:{name:string;text:string}[]=[],frames=new Map<number,FrameRequestCallback>();let next=0;const ui=mountSystemWorkbench(root as any,{revision:'test',makeWorker:()=>{const w=new WorkerFake();workers.push(w);return w;},download:(name,text)=>downloads.push({name,text}),requestFrame:fn=>{frames.set(++next,fn);return next;},cancelFrame:id=>frames.delete(id)});const get=(id:string)=>{const e=root.querySelector('#'+id);assert(e,id);return e;};t.after(()=>{ui.dispose();if(original)Object.defineProperty(globalThis,'document',original);else delete (globalThis as any).document;});return {root,workers,downloads,frames,ui,get,worker:()=>workers.at(-1)!,submit:()=>get('wb-form').onsubmit!({preventDefault(){}}),frame(now:number){const entry=[...frames.entries()][0];assert(entry);frames.delete(entry[0]);entry[1](now);}};}
const optional=()=>({...DEFAULT_WORKBENCH_CONFIG,system:'food' as const,index:1,rainfall:'regional' as const,travel:'regional' as const,irrigation:'canister' as const});
test('canister config is explicit, Food-only, and cannot be smuggled into historical reports',()=>{
 assert(!Object.hasOwn(validateWorkbenchConfig(DEFAULT_WORKBENCH_CONFIG),'irrigation'));
 assert.equal(validateWorkbenchConfig(optional()).irrigation,'canister');
 for(const system of ['water','trade','settlement'])assert.throws(()=>validateWorkbenchConfig({...optional(),system,index:0}),/Food only/);
 for(const irrigation of ['none','automatic','legacy',false,0,null,{}])assert.throws(()=>validateWorkbenchConfig({...optional(),irrigation}),/Food only/);
 const legacy=new WorkbenchSession(DEFAULT_WORKBENCH_CONFIG,'test').report();
 for(const version of [1,2] as const){const bad=structuredClone(legacy);bad.version=version;bad.config={...optional()};assert.throws(()=>parseWorkbenchReport(JSON.stringify(bad)),/version/);}const bad=structuredClone(legacy);bad.version=3;assert.throws(()=>parseWorkbenchReport(JSON.stringify(bad)),/version/);
});
test('optional Food earns one actual source canister and conserves its single manual import through reload and replay',{timeout:60000},()=>{
 const s=new WorkbenchSession(optional(),'test'),snap=s.snapshot(),i=snap.irrigation!;
 const real=worldObjects({generation:2,seed:s.config.seed}).find(o=>o.kind==='water')!;
 assert.deepEqual(i.setupCanister,{id:real.id,x:real.x,z:real.z});assert(s.setupSeconds>0);assert.equal(snap.tick,0);assert.equal(i.canisters,1);assert.equal(i.importedLitres,0);assert.equal(i.used,false);assert.equal(snap.inventory.water,0);
 assert.match(i.description,/ordinary collect action/);assert.match(i.description,/Assist never spends/);assert.equal(s.report().version,3);
 const before=s.digest();s.assist();assert.equal(s.digest(),before,'assist cannot use the eligible canister');assert.equal(s.report().events.length,0);
 assert(s.action('irrigate-farm'));const watered=s.snapshot();assert.equal(watered.irrigation!.canisters,0);assert.equal(watered.irrigation!.importedLitres,4);assert.equal(watered.irrigation!.used,true);assert.equal(watered.inventory.water,4);assert.equal(watered.irrigation!.capturedLitres,i.capturedLitres);assert.equal(watered.irrigation!.lostOverflowLitres,i.lostOverflowLitres);assert(watered.checks.every(c=>c.pass));
 const used=s.digest();assert.equal(s.action('irrigate-farm'),false);assert.equal(s.digest(),used);assert(s.verifyReload().pass);s.advance(240);assert(s.snapshot().checks.every(c=>c.pass));assert(s.verifyReload().pass);
 const report=s.report();assert.deepEqual(report.events.map(e=>[e.action,e.accepted]),[['irrigate-farm',true],['irrigate-farm',false]]);assert.equal(replayWorkbench(report,'test').result.match,true);
 for(const mutate of [(r:any)=>r.version=1,(r:any)=>r.version=2,(r:any)=>delete r.config.irrigation,(r:any)=>r.config.system='water',(r:any)=>r.eventEncoding='target-v1',(r:any)=>r.events[0].targetId='fake']){const invalid=structuredClone(report);mutate(invalid);assert.throws(()=>parseWorkbenchReport(JSON.stringify(invalid)));}
 const noSpend=structuredClone(report);noSpend.events[0]!.accepted=false;assert.equal(replayWorkbench(noSpend,'test').result.match,false);
 const projection=structuredClone(report);projection.snapshot.irrigation!.importedLitres=999;assert(replayWorkbench(projection,'test').result.match,'projection is derived, never imported as state');
});
test('opt-in selector renders prerequisite disclosure and lifetime status, forwards one click, and restores reports',async t=>{
 const h=harness(t);assert(h.get('wb-irrigation-controls').hidden);h.worker().flush();await settle();assert(h.get('wb-irrigation-card').hidden);
 h.get('wb-system').value='food';h.get('wb-system').onchange!();assert.equal(h.get('wb-irrigation').value,'none');assert.equal(h.get('wb-irrigation-controls').hidden,false);
 h.get('wb-irrigation').value='canister';h.get('wb-irrigation').onchange!();h.submit();const create=h.worker().requests[0]!;assert.equal(create.kind,'create');if(create.kind==='create')assert.equal(create.config.irrigation,'canister');h.worker().flush();await settle();
 assert.equal(h.get('wb-irrigation-card').hidden,false);assert.match(h.get('wb-setup').textContent,/Optional Food v2 prerequisite setup/);assert.match(h.get('wb-irrigation-status').textContent,/one lifetime application/);assert.match(h.get('wb-irrigation-balance').textContent,/Pack canisters 1 · Imported canister water 0 L · Rain overflow captured 0 L/);assert.match(h.get('wb-irrigation-description').textContent,/Mossbank/);assert.match(h.get('wb-irrigation-source').textContent,/ordinary collect action/);
 const button=h.get('wb-actions').querySelectorAll('button').find(b=>b.dataset.action==='irrigate-farm')!,count=h.worker().requests.length;assert(button&&!button.disabled);button.onclick!();button.onclick!();assert.equal(h.worker().requests.length,count+1);h.worker().flush();await settle();assert.match(h.get('wb-irrigation-status').textContent,/Used permanently/);assert.match(h.get('wb-irrigation-balance').textContent,/Pack canisters 0 · Imported canister water 4 L/);
 h.get('wb-export').onclick!();h.worker().flush();await settle();const text=h.downloads[0]!.text,report=JSON.parse(text);assert.equal(report.version,3);assert.equal(report.events.length,1);
 h.get('wb-import').files=[{size:text.length,text:async()=>text}];await h.get('wb-import').onchange!();assert.equal(h.get('wb-irrigation').value,'canister');h.worker().flush();await settle();assert.match(h.get('wb-replay-status').textContent,/REPLAY MATCH/);assert.match(h.get('wb-irrigation-status').textContent,/Used permanently/);
 h.get('wb-system').value='settlement';h.get('wb-system').onchange!();assert(h.get('wb-irrigation-controls').hidden);assert.equal(h.get('wb-irrigation').value,'none');h.submit();assert(h.get('wb-irrigation-card').hidden);h.worker().flush();await settle();assert.match(h.get('wb-setup').textContent,/Starts empty at 0 s/);assert.equal(h.ui.getSnapshot()!.irrigation,undefined);
});
test('staged canister changes survive old responses and late import reads cannot replace them',async t=>{
 const h=harness(t);h.get('wb-system').value='food';h.get('wb-system').onchange!();h.submit();const old=h.worker(),late=old.onmessage!;h.get('wb-irrigation').value='canister';h.get('wb-irrigation').onchange!();old.flush();await settle();assert.equal(h.get('wb-irrigation').value,'canister');assert(h.get('wb-step').disabled);assert(h.get('wb-irrigation-card').hidden);
 h.submit();late({data:old.handle(old.requests[0]!)} as MessageEvent<WorkbenchResponse>);await settle();assert.equal(h.ui.getSnapshot(),undefined);h.worker().flush();await settle();assert.equal(h.ui.getSnapshot()!.irrigation!.canisters,1);
 const text=JSON.stringify(new WorkbenchSession(DEFAULT_WORKBENCH_CONFIG,'test').report());let finish!:(text:string)=>void;h.get('wb-import').files=[{size:text.length,text:()=>new Promise(resolve=>finish=resolve)}];const count=h.workers.length,pending=h.get('wb-import').onchange!();h.get('wb-irrigation').value='none';h.get('wb-irrigation').onchange!();finish(text);await pending;assert.equal(h.workers.length,count);assert.equal(h.get('wb-irrigation').value,'none');assert(h.get('wb-step').disabled);
});
test('CLI canister opt-in is explicit, assist never spends, and report replays without setup grants',{timeout:60000},()=>{
 const dir=mkdtempSync(join(tmpdir(),'axiom-irrigation-'));try{const output=join(dir,'optional.json'),run=(args:string[])=>spawnSync(process.execPath,['--experimental-strip-types','scripts/system-workbench.mts',...args],{cwd:new URL('..',import.meta.url),encoding:'utf8'});
 const result=run(['--system','food','--irrigation','canister','--seconds','1','--assist','--reload','--output',output]);assert.equal(result.status,0,result.stderr);const report=JSON.parse(readFileSync(output,'utf8'));assert.equal(report.version,3);assert.equal(report.snapshot.irrigation.canisters,1);assert.equal(report.snapshot.irrigation.importedLitres,0);assert(report.reload.pass);assert(!report.events.some((e:any)=>e.action==='irrigate-farm'));assert.equal(run(['--replay',output]).status,0);
 for(const args of [['--irrigation','canister'],['--system','food','--irrigation','automatic'],['--replay',output,'--irrigation','canister']])assert.equal(run(args).status,2);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
