import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import {WorkbenchSession,DEFAULT_WORKBENCH_CONFIG,validateWorkbenchConfig,workbenchGeometry,parseWorkbenchReport,replayWorkbench,WORKBENCH_MAX_TICKS,WORKBENCH_MAX_EVENTS} from '../src/system-workbench-model.ts';
import {regionalTradePlan,regionalTradeActorPoses} from '../src/regional-trade.ts';import {regionalFoodPlan,type RegionalFoodFarm} from '../src/regional-food.ts';import {regionalWeatherAt} from '../src/regional-weather.ts';import {regionalSupplyPlan} from '../src/regional-supply.ts';import {generateRegionalChunk} from '../src/regional-world.ts';import {createWorkbenchHandler,type WorkbenchRequest,type WorkbenchResponse} from '../src/system-workbench-protocol.ts';import {WorkbenchClient,WorkbenchPlayback,type WorkbenchWorker} from '../src/system-workbench-client.ts';
const config=(patch={})=>({...DEFAULT_WORKBENCH_CONFIG,...patch});
function advance(s:WorkbenchSession,ticks:number,assist=false){while(ticks>0){if(assist)s.assist();const n=Math.min(assist?4:240,ticks),before=s.tick;s.advance(n);ticks-=n;if(s.tick===before)break;}}
test('bounded config rejects unsafe seeds, indexes, chunk coordinates and unknown systems',()=>{for(const patch of [{seed:-1},{seed:1.5},{seed:Infinity},{seed:4294967296},{index:3},{cx:25},{cz:-26},{view:'all'},{system:'other'},{rainfall:'storm'},{rainfall:null},{rainfall:2},{rainfall:{}},{travel:'storm'},{travel:null},{travel:2},{travel:{}}])assert.throws(()=>validateWorkbenchConfig(config(patch)));assert.equal(validateWorkbenchConfig(config({seed:0})).seed,0);assert.equal(validateWorkbenchConfig(config({seed:0xffffffff,system:'water',index:5,cx:-25,cz:24})).index,5);});
test('rainfall config keeps historical shape while accepting an explicit regional model',()=>{
 assert(!Object.hasOwn(DEFAULT_WORKBENCH_CONFIG,'rainfall'));assert(!Object.hasOwn(DEFAULT_WORKBENCH_CONFIG,'travel'));
 assert.equal(JSON.stringify(validateWorkbenchConfig(config())),JSON.stringify(DEFAULT_WORKBENCH_CONFIG));
 assert.equal(JSON.stringify(validateWorkbenchConfig(config({rainfall:'legacy'}))),JSON.stringify(DEFAULT_WORKBENCH_CONFIG));
 assert.equal(validateWorkbenchConfig(config({rainfall:'regional'})).rainfall,'regional');
 assert.equal(JSON.stringify(validateWorkbenchConfig(config({travel:'legacy'}))),JSON.stringify(DEFAULT_WORKBENCH_CONFIG));assert.equal(validateWorkbenchConfig(config({travel:'regional'})).travel,'regional');
});
test('historical v1 reports without rainfall retain their original sampled fingerprints',{timeout:60000},()=>{
 // Captured before regional rainfall integration at seed 73129 and 60 active seconds.
 const historical={trade:['4f8ad76e','cd5fbbe9','fb19be04','c7ea3898','51638405','061a1ea1','65ef30c3'],water:['17e49833','5b663d55','397661f6','4ee8ff45','da98d877','faf24eda','60e0b4be'],food:['0d903801','272768d2','9060ec72','dd287c5f','aacf023c','e8bf5eb4','1ed3f49f']};
 for(const system of ['trade','water','food'] as const){
  const s=new WorkbenchSession(config({system}),'historical');s.advance(240);const report=s.report();
  assert.deepEqual(report.checkpoints.map(p=>p.fingerprint),historical[system],system);
  assert.equal(report.finalFingerprint,historical[system].at(-1));assert(!Object.hasOwn(report.config,'rainfall'));assert(!Object.hasOwn(report.config,'travel'));assert(!Object.hasOwn(report.snapshot,'freight'));
  delete report.snapshot.weather;const parsed=parseWorkbenchReport(JSON.stringify(report));
  assert(!Object.hasOwn(parsed.config,'rainfall'));assert(!Object.hasOwn(parsed.snapshot,'weather'));assert(replayWorkbench(parsed,'historical').result.match,system);
 }
});
test('single chunk and bounded settlement views use exact production generation; route needs no chunk meshes',()=>{for(const seed of [0,73129,0xffffffff]){const chunk=workbenchGeometry(config({seed,view:'chunk',cx:-8,cz:0}));assert.equal(chunk.chunks.length,1);assert.deepEqual(chunk.chunks[0],generateRegionalChunk(seed,-8,0));const route=workbenchGeometry(config({seed,view:'route'}));assert.equal(route.chunks.length,0);assert.deepEqual(route.paths[0]!.points,regionalTradePlan(seed).routes[0]!.points);const settlement=workbenchGeometry(config({seed,view:'settlement'}));assert(settlement.chunks.length>=1&&settlement.chunks.length<=4);assert.equal(settlement.bounds.maxX-settlement.bounds.minX,64);}});
test('same seed, fixed steps and differently partitioned batches are byte-deterministic',()=>{for(const seed of [0,73129]){const a=new WorkbenchSession(config({seed}),'test'),b=new WorkbenchSession(config({seed}),'test');a.advance(240);for(let i=0;i<60;i++)b.advance(4);assert.deepEqual(a.report(),b.report());assert.notEqual(a.snapshot().actors[0]!.position.x,regionalTradePlan(seed).sources[0]!.position.x);assert(a.snapshot().checks.every(c=>c.pass));assert.throws(()=>a.advance(241));assert.throws(()=>a.advance(-1));assert.throws(()=>a.advance(.5));}});
test('trade action journal carries real reserves across blocked travel, repair, construction and withdrawal',()=>{const s=new WorkbenchSession(config(),'test');assert.equal(s.action('build-store'),false);advance(s,800);assert.equal(s.snapshot().phase,'blocked');assert.equal(s.snapshot().inventory.cargo,4);assert.equal(s.action('clear-route'),true);assert.equal(s.action('clear-route'),false);advance(s,14000,true);assert(s.snapshot().inventory.delivered!>=8);assert.equal(s.action('withdraw-reserve'),false,'actions stop at declared scenario limit');assert(s.snapshot().checks.every(c=>c.pass));assert(s.snapshot().atLimit);assert.equal(s.tick,WORKBENCH_MAX_TICKS);const before=s.digest();s.advance(240);assert.equal(s.digest(),before);assert(s.verifyReload().pass);assert(replayWorkbench(s.report(),'test').result.match);});
test('manual early withdrawal changes only the actual finite destination reserve and replays',()=>{const s=new WorkbenchSession(config(),'test');advance(s,9000,true);assert(s.snapshot().inventory.destination!>0);assert(s.action('withdraw-reserve'));const r=s.report();assert(r.snapshot.inventory.withdrawn!>0);assert(replayWorkbench(r,'test').result.match);const changed=structuredClone(r);changed.finalFingerprint='00000000';assert.equal(replayWorkbench(changed,'other').result.match,false);assert(replayWorkbench(changed,'other').result.sourceChanged);});
test('water workers consume real collected water and retain exact state through production save parsing',()=>{for(const seed of [42,73129]){const s=new WorkbenchSession(config({seed,system:'water',view:'settlement'}),'test');advance(s,2400);const snap=s.snapshot();assert.equal(snap.name,regionalSupplyPlan(seed).outposts[0]!.name);assert.equal(snap.phase,'operational');assert(snap.inventory.captured!>0);assert(snap.inventory.consumed!>0);assert(snap.actors.some(a=>a.needLabel==='thirst'));assert(snap.checks.every(c=>c.pass));assert(s.verifyReload().pass);assert(replayWorkbench(s.report(),'test').result.match);}});
test('farming setup earns old prerequisites, starts only the selected farm and replays food and held meals',{timeout:60000},()=>{const s=new WorkbenchSession(config({system:'food',index:1}),'test');assert(s.setupSeconds>0);const before=s.snapshot();assert.equal(before.inventory.starter,4);assert.equal(before.inventory.water,0);advance(s,2400,true);const snap=s.snapshot();assert(snap.inventory.harvested!>=12);assert(snap.inventory.meals!>4);assert.equal(snap.inventory.stewardship,4);assert(snap.checks.every(c=>c.pass));assert(s.verifyReload().pass);const report=s.report();assert.equal(report.visualReview,'not-reviewed');assert.equal(replayWorkbench(report,'test').result.match,true);assert.equal(report.snapshot.actors.length,2);});
test('regional water exposes deterministic read-only rainfall and survives reload and replay',()=>{
 const a=new WorkbenchSession(config({system:'water',rainfall:'regional'}),'test'),b=new WorkbenchSession(config({system:'water',rainfall:'regional'}),'test');
 assert.equal(a.snapshot().weather?.model,'regional');const phases=new Set<string>();let sawDry=false,sawRain=false;
 for(let second=0;second<1200;second+=60){a.advance(240);for(let i=0;i<60;i++)b.advance(4);assert.equal(a.digest(),b.digest());const weather=a.snapshot().weather!;phases.add(weather.phase);sawDry||=weather.intensity===0;sawRain||=weather.intensity>0;assert(weather.drySeconds>=0);assert(weather.secondsUntilChange>=0);assert(weather.description.length>0);assert(a.snapshot().checks.every(c=>c.pass));}
 assert(sawDry&&sawRain,'bounded seeded weather includes both dry and rainy intervals');assert(phases.size>1);assert(a.verifyReload().pass);assert.equal(a.digest(),b.digest());
 const report=a.report(),fingerprint=a.digest();report.snapshot.weather!.intensity=999;assert.equal(a.digest(),fingerprint);assert(replayWorkbench(report,'test').result.match,'weather projection is not fingerprinted or trusted during replay');
 const legacy=new WorkbenchSession(config({system:'water'}),'test');assert.equal(legacy.snapshot().weather?.model,'legacy');assert.notEqual(legacy.digest(),new WorkbenchSession(config({system:'water',rainfall:'regional'}),'test').digest());
 assert(!Object.hasOwn(new WorkbenchSession(config({rainfall:'regional'}),'test').snapshot(),'weather'));
});
test('regional food projects weather from its source collector and conserves production',{timeout:60000},()=>{
 const s=new WorkbenchSession(config({system:'food',index:1,rainfall:'regional'}),'test'),farm=regionalFoodPlan(s.config.seed).farms[1]!,source=regionalSupplyPlan(s.config.seed).outposts.find(p=>p.id===farm.siteId)!;
 assert.equal(s.snapshot().weather!.model,'regional');assert(s.setupSeconds>0);assert.equal(s.snapshot().name,farm.name);let settledDryChecks=0;
 for(let second=0;second<1200;second++){
  const before=s.snapshot(),weather=before.weather!,expected=regionalWeatherAt(s.config.seed,source.position.x,source.position.z,s.setupSeconds*4+s.tick);
  assert.equal(weather.phase,expected.phase);assert.equal(weather.intensity,expected.intensity);assert.equal(weather.drySeconds,expected.drySeconds);assert.equal(weather.secondsUntilChange,expected.secondsUntilChange);
  s.assist();s.advance(4);const after=s.snapshot();assert(after.checks.every(c=>c.pass));
  if(weather.intensity===0&&weather.drySeconds>=1&&weather.secondsUntilChange>1){assert.equal((after.ledger as RegionalFoodFarm).waterCaptured,(before.ledger as RegionalFoodFarm).waterCaptured,'settled drought cannot add farm water');settledDryChecks++;}
 }
 assert(settledDryChecks>0);assert(s.snapshot().inventory.harvested!>0);assert(s.verifyReload().pass);assert(replayWorkbench(s.report(),'test').result.match);
});
test('returned reports and geometry cannot mutate the session and exports never contain campaign saves',()=>{const s=new WorkbenchSession(config(),'test'),fingerprint=s.digest(),report=s.report();report.snapshot.inventory.cargo=999;report.config.seed=3;assert.equal(s.digest(),fingerprint);assert.equal(s.config.seed,73129);assert(!('state' in report));assert(!('save' in report));assert.throws(()=>s.action('arbitrary-command'));assert.equal(s.digest(),fingerprint);});
test('replay input rejects campaigns, excessive work, event spoofing, out-of-order and forged checkpoints',()=>{const s=new WorkbenchSession(config(),'test');s.advance(40);s.action('clear-route');const r=s.report();for(const mutation of [(v:any)=>v.kind='campaign',(v:any)=>v.version=2,(v:any)=>v.finalTick=WORKBENCH_MAX_TICKS+1,(v:any)=>v.events=[{tick:-1,action:'clear-route',accepted:true}],(v:any)=>v.events=[{tick:0,action:'save',accepted:true}],(v:any)=>v.events=Array(WORKBENCH_MAX_EVENTS+1).fill({tick:0,action:'clear-route',accepted:true}),(v:any)=>v.checkpoints=[{tick:1,fingerprint:'00000000'}]]){const bad=structuredClone(r);mutation(bad);assert.throws(()=>parseWorkbenchReport(JSON.stringify(bad)));}assert.throws(()=>parseWorkbenchReport(' '.repeat(2_000_001)));assert.throws(()=>parseWorkbenchReport('{'));const forged=structuredClone(r);forged.checkpoints[0]!.fingerprint='00000000';const replay=replayWorkbench(forged,'test').result;assert.equal(replay.match,false);assert.match(replay.firstDifference!,/tick 0/);});
test('request handler has no old-session fallback after failed creation, and reports structured errors',()=>{const handle=createWorkbenchHandler();assert.equal(handle({id:1,kind:'report'}).ok,false);assert.equal(handle({id:2,kind:'create',config:config(),revision:'test'}).ok,true);assert.equal(handle({id:3,kind:'advance',ticks:4}).snapshot!.tick,4);assert(handle({id:4,kind:'reload'}).reload?.pass);assert.equal(handle({id:5,kind:'create',config:config({seed:-1}),revision:'test'}).ok,false);assert.equal(handle({id:6,kind:'advance',ticks:4}).ok,false);assert.equal(handle({id:-1,kind:'report'}).id,-1);});
class WorkerFake implements WorkbenchWorker {onmessage:WorkbenchWorker['onmessage']=null;onerror:WorkbenchWorker['onerror']=null;terminated=false;requests:WorkbenchRequest[]=[];postMessage(r:WorkbenchRequest){this.requests.push(r);}terminate(){this.terminated=true;}respond(r:WorkbenchResponse){this.onmessage?.({data:r} as MessageEvent<WorkbenchResponse>);}}
test('client permits one request and ignores mismatched replies, rejects pending work on disposal',async()=>{const worker=new WorkerFake(),client=new WorkbenchClient(worker),first=client.request({kind:'report'});await assert.rejects(client.request({kind:'report'}),/current/);worker.respond({id:999,ok:true});worker.respond({id:1,ok:true});assert.equal((await first).id,1);const late=client.request({kind:'report'});client.dispose();await assert.rejects(late,/replaced/);assert(worker.terminated);assert.equal(worker.onmessage,null);await assert.rejects(client.request({kind:'report'}),/closed/);client.dispose();});
test('client worker errors and request failures are surfaced without fabricated snapshots',async()=>{const worker=new WorkerFake(),client=new WorkbenchClient(worker);const p=client.request({kind:'report'});worker.onerror?.({message:'stopped'} as ErrorEvent);await assert.rejects(p,/stopped/);await assert.rejects(client.request({kind:'report'}),/reset/);assert(worker.terminated);const otherWorker=new WorkerFake(),otherClient=new WorkbenchClient(otherWorker),second=otherClient.request({kind:'report'});otherWorker.respond({id:1,ok:false,error:'bad replay'});await assert.rejects(second,/bad replay/);otherClient.dispose();client.dispose();});
test('playback pauses and discards hidden time, limits stalled frames and does not queue busy catch-up',()=>{const p=new WorkbenchPlayback();assert.equal(p.take(100),0);p.play();assert.equal(p.take(100),0);assert.equal(p.take(225),0);assert.equal(p.take(350),1);p.speed=60;assert.equal(p.take(600),60);assert.equal(p.take(10000),60);assert.equal(p.take(10500,false,true),0);assert.equal(p.take(10750),60);assert.equal(p.take(100000,true),0);assert.equal(p.playing,false);p.play();assert.equal(p.take(200000),0);p.pause();assert.equal(p.take(200250),0);});
test('CLI report/replay works offline with correct failing exit codes',()=>{const dir=mkdtempSync(join(tmpdir(),'axiom-workbench-'));try{const output=join(dir,'run.json'),run=(args:string[])=>spawnSync(process.execPath,['--experimental-strip-types','scripts/system-workbench.mts',...args],{cwd:new URL('..',import.meta.url),encoding:'utf8'});const first=run(['--seconds','10','--output',output]);assert.equal(first.status,0,first.stderr);const repeat=run(['--replay',output]);assert.equal(repeat.status,0,repeat.stderr);assert.match(repeat.stdout,/MATCH/);const bad=JSON.parse(readFileSync(output,'utf8'));bad.finalFingerprint='00000000';writeFileSync(output,JSON.stringify(bad));assert.equal(run(['--replay',output]).status,1);assert.equal(run(['--seconds','-1']).status,2);assert.equal(run(['--system','other']).status,2);assert.equal(run(['--replay',output,'--seed','3']).status,2);}finally{rmSync(dir,{recursive:true,force:true});}});
test('standalone entry and Settings link do not boot the game or access campaign persistence',()=>{const html=readFileSync(new URL('../system-workbench.html',import.meta.url),'utf8'),entry=readFileSync(new URL('../src/system-workbench.ts',import.meta.url),'utf8'),ui=readFileSync(new URL('../src/system-workbench-ui.ts',import.meta.url),'utf8'),main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),vite=readFileSync(new URL('../vite.client.config.ts',import.meta.url),'utf8');assert.match(html,/system-workbench\.ts/);assert.doesNotMatch(html,/main\.ts/);assert.match(vite,/systemWorkbench:'system-workbench.html'/);assert.match(main,/href="\.\/system-workbench.html\?seed=\$\{state.seed\}" target="_blank" rel="noopener"/);assert.match(ui,/visual-review\.html\?subject=/);for(const text of [entry,ui])assert.doesNotMatch(text,/localStorage|sessionStorage|indexedDB|fetch\(|from ['"]\.\/main/);assert.match(entry,/pagehide/);assert.match(entry,/pageshow/);});

test('round-trip evidence expires when the verified state advances or receives an accepted command',()=>{const s=new WorkbenchSession(config(),'test');assert(s.verifyReload().pass);s.advance(1);assert.deepEqual(s.report().reload,{checked:false,pass:null});assert(s.verifyReload().pass);assert(s.action('clear-route'));assert.deepEqual(s.report().reload,{checked:false,pass:null});});
test('replay diagnoses the earliest sampled difference and requires complete generation evidence',()=>{const s=new WorkbenchSession(config(),'test');s.advance(100);s.action('clear-route');const report=s.report(),bad=structuredClone(report);bad.checkpoints[1]!.fingerprint='00000000';bad.events[0]!.accepted=false;assert.match(replayWorkbench(bad,'test').result.firstDifference!,/sampled tick 40/);const missing=structuredClone(report);missing.checkpoints=[];assert.throws(()=>parseWorkbenchReport(JSON.stringify(missing)),/Missing replay checkpoints/);const geometry=structuredClone(report);geometry.geometryFingerprint='00000000';assert.match(replayWorkbench(geometry,'test').result.firstDifference!,/generation geometry/);const before=s.digest(),returned=s.geometry();returned.paths[0]!.points[0]!.x+=999;assert.equal(s.digest(),before);assert.notEqual(s.geometry().paths[0]!.points[0]!.x,returned.paths[0]!.points[0]!.x);});

test('CLI defaults to regional rainfall, exports legacy explicitly and rejects invalid weather options',()=>{const dir=mkdtempSync(join(tmpdir(),'axiom-workbench-rainfall-'));try{const output=join(dir,'run.json'),run=(args:string[])=>spawnSync(process.execPath,['--experimental-strip-types','scripts/system-workbench.mts',...args],{cwd:new URL('..',import.meta.url),encoding:'utf8'});const regional=run(['--system','water','--seconds','60','--reload','--output',output]);assert.equal(regional.status,0,regional.stderr);const report=JSON.parse(readFileSync(output,'utf8'));assert.equal(report.config.rainfall,'regional');assert.equal(report.snapshot.weather.model,'regional');assert.equal(JSON.parse(regional.stdout).weather.model,'regional');assert.equal(run(['--replay',output]).status,0);const legacy=run(['--system','water','--rainfall','legacy','--travel','legacy','--seconds','60','--output',output]);assert.equal(legacy.status,0,legacy.stderr);const old=JSON.parse(readFileSync(output,'utf8'));assert(!Object.hasOwn(old.config,'rainfall'));assert.equal(old.finalFingerprint,'60e0b4be');assert.equal(old.snapshot.weather.model,'legacy');assert.equal(run(['--rainfall','storm']).status,2);assert.equal(run(['--rainfall']).status,2);assert.equal(run(['--replay',output,'--rainfall','regional']).status,2);}finally{rmSync(dir,{recursive:true,force:true});}});


test('regional freight is selected explicitly, preserves geometry and replays partitioned weather travel',()=>{
 const regional=config({travel:'regional' as const}),a=new WorkbenchSession(regional,'test'),b=new WorkbenchSession(regional,'test'),old=new WorkbenchSession(config(),'test');
 assert.equal(a.config.travel,'regional');assert.equal(a.snapshot().freight!.length,1);assert.equal(a.snapshot().freight![0]!.travelRule,'regional');assert.equal(old.snapshot().freight,undefined);assert.notEqual(a.digest(),old.digest());assert.deepEqual(a.geometry(),old.geometry());
 assert(a.action('clear-route'));assert(b.action('clear-route'));const conditions=new Set<string>();let minSpeed=Infinity,maxWetness=0;
 for(let second=0;second<1200;second+=60){a.advance(240);for(let i=0;i<60;i++)b.advance(4);assert.equal(a.digest(),b.digest());const travel=a.snapshot().freight![0]!;conditions.add(travel.travelCondition);assert(travel.roadWetness>=0&&travel.roadWetness<=1);assert(travel.travelSpeed>0&&travel.travelSpeed<=regionalTradePlan(a.config.seed).routes[0]!.speed);minSpeed=Math.min(minSpeed,travel.travelSpeed);maxWetness=Math.max(maxWetness,travel.roadWetness);assert(a.snapshot().checks.every(c=>c.pass));}
 assert(maxWetness>0);assert(minSpeed<regionalTradePlan(a.config.seed).routes[0]!.speed);assert(conditions.size>1);assert(a.verifyReload().pass);assert.equal(a.digest(),b.digest());
 const report=a.report(),fingerprint=a.digest();report.snapshot.freight![0]!.travelSpeed=999;report.snapshot.freight![0]!.etaSeconds=0;assert.equal(a.digest(),fingerprint);assert(replayWorkbench(report,'test').result.match,'derived freight projection is never trusted on import');
 const changed=structuredClone(report);delete changed.config.travel;assert(!replayWorkbench(changed,'test').result.match,'travel choice is part of deterministic replay');
});
test('regional freight reports repair-required instead of a fabricated delivery time',()=>{
 const s=new WorkbenchSession(config({travel:'regional'}),'test');advance(s,2000);const snap=s.snapshot();assert.equal(snap.phase,'blocked');assert.equal(snap.freight![0]!.etaKind,'repair-required');assert.equal(snap.freight![0]!.etaSeconds,null);const distance=snap.inventory.distance,cargo=snap.inventory.cargo;s.advance(240);assert.equal(s.snapshot().inventory.distance,distance);assert.equal(s.snapshot().inventory.cargo,cargo);assert(s.action('clear-route'));s.advance(60);const repaired=s.snapshot().freight![0]!;assert.equal(repaired.etaKind,'arrival');assert(repaired.etaSeconds!>0);assert(s.verifyReload().pass);assert(replayWorkbench(s.report(),'test').result.match);
});
test('CLI defaults to regional freight and keeps explicit legacy report compatibility',()=>{
 const dir=mkdtempSync(join(tmpdir(),'axiom-workbench-travel-'));try{const output=join(dir,'run.json'),run=(args:string[])=>spawnSync(process.execPath,['--experimental-strip-types','scripts/system-workbench.mts',...args],{cwd:new URL('..',import.meta.url),encoding:'utf8'});
 const regional=run(['--seconds','60','--reload','--output',output]);assert.equal(regional.status,0,regional.stderr);const report=JSON.parse(readFileSync(output,'utf8')),consoleResult=JSON.parse(regional.stdout);assert.equal(report.config.travel,'regional');assert.equal(consoleResult.travel,'regional');assert.equal(consoleResult.freight[0].travelRule,'regional');assert(report.reload.pass);assert.equal(run(['--replay',output]).status,0);
 const legacy=run(['--rainfall','legacy','--travel','legacy','--seconds','60','--output',output]);assert.equal(legacy.status,0,legacy.stderr);const old=JSON.parse(readFileSync(output,'utf8'));assert(!Object.hasOwn(old.config,'travel'));assert(!Object.hasOwn(old.snapshot,'freight'));assert.equal(old.finalFingerprint,'65ef30c3');assert.equal(JSON.parse(legacy.stdout).travel,'legacy');assert.equal(run(['--travel','storm']).status,2);assert.equal(run(['--travel']).status,2);assert.equal(run(['--replay',output,'--travel','regional']).status,2);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
test('collector rainfall selection does not silently change freight travel rules',()=>{
 const regionalTravel=new WorkbenchSession(config({travel:'regional'}),'test'),bothRegional=new WorkbenchSession(config({travel:'regional',rainfall:'regional'}),'test');regionalTravel.action('clear-route');bothRegional.action('clear-route');regionalTravel.advance(240);bothRegional.advance(240);assert.deepEqual(regionalTravel.snapshot().ledger,bothRegional.snapshot().ledger);assert.deepEqual(regionalTravel.snapshot().freight,bothRegional.snapshot().freight);assert.notEqual(regionalTravel.digest(),bothRegional.digest());
 const regionalRainfall=new WorkbenchSession(config({rainfall:'regional'}),'test');assert.equal(regionalRainfall.config.travel,undefined);assert.equal(regionalRainfall.snapshot().freight,undefined);
});
