import test from 'node:test';import assert from 'node:assert/strict';
import {TownCrowd,TownPresentationClock,TownRenderMotion,slideTownCrowd,townClock,townPathClear,clearTownBody,TOWN_NEIGHBOR_LIMIT} from '../src/town-crowd.ts';
import {TownPopulation,DEFAULT_TOWN_TUNING,validateTownTuning} from '../src/town-population.ts';
import {townResidents,townResidentPose} from '../src/town-residents.ts';import {startingTown,TOWN_CENTER} from '../src/starting-town.ts';import {townGait} from '../src/town-gait.ts';import {createTownView} from '../src/town-view.ts';
const distance=(a:{x:number;z:number},b:{x:number;z:number})=>Math.hypot(a.x-b.x,a.z-b.z);
test('fine shared town clock includes fractional accumulator without changing the causal ledger',()=>{const s={elapsed:12.25,accumulator:.137};assert.equal(townClock(s),12.387);assert.deepEqual(s,{elapsed:12.25,accumulator:.137});assert.equal(townClock(),0);});
test('canonical crowd positions agree at common timestamps across 30 60 and 120 Hz and query order',()=>{const expected=new TownCrowd(73129).sample(101.5);for(const hz of [30,60,120]){const c=new TownCrowd(73129);for(let n=0;n<=hz;n++)c.sample(100.5+n/hz);assert.deepEqual(c.sample(101.5),expected);c.sample(320);assert.deepEqual(c.sample(101.5),expected);}});
test('presentation clock interpolates 60 Hz and 4 Hz anchors at 120 Hz then bounds stalls and pauses',()=>{for(const rate of [4,60]){const c=new TownPresentationClock();let prior=0;for(let n=0;n<240;n++){const authority=Math.floor(n/120*rate+1e-8)/rate,t=c.sample(authority,1/120,n===0,rate===4?.3:.05);if(n>0)assert(t>prior,'every render frame advances');assert(t-authority<=(rate===4?.300001:.050001));prior=t;}for(let i=0;i<60;i++)assert.equal(c.sample(1.75,0),prior);const stalled=c.sample(1.75,1/120);for(let i=0;i<240;i++)c.sample(1.75,1/120);assert(c.sample(1.75,1/120)<=2.050001);assert.equal(c.sample(500,1/120,true),500);assert.equal(c.sample(2,1/120),2);}});
test('all 100 canonical bodies stay finite and clear town solids for ordinary full-cycle samples',()=>{for(const seed of [0,73129,0xffffffff]){const c=new TownCrowd(seed);for(let tick=0;tick<=240;tick++){const poses=c.sample(tick*2);for(const p of poses){assert([p.x,p.z,p.facing,p.speed].every(Number.isFinite));assert(distance(p,clearTownBody(c.plan,p))<1e-8);}for(let i=0;i<100;i++)for(let j=i+1;j<100;j++)assert(distance(poses[i]!,poses[j]!)>.60,`seed ${seed} t${tick*2} pair${i}/${j}`);}assert(c.maxNeighbors<=TOWN_NEIGHBOR_LIMIT);}});
test('crowd actors are deterministic in peer order, yield within bounded offsets and retain open door corridors',()=>{const c=new TownCrowd(73129),raw=c.sample(102),actors=[{id:'a',x:raw[0]!.x,z:raw[0]!.z,feetY:6},{id:'b',x:TOWN_CENTER.x,z:TOWN_CENTER.z,feetY:6}];const a=c.sample(102,100,1,actors),b=c.sample(102,100,1,[...actors].reverse());assert.deepEqual(a,b);for(const p of a)assert(distance(p,clearTownBody(c.plan,p))<1e-8);assert(distance(a[0]!,actors[0]!)>.64);for(let i=0;i<100;i++)assert(distance(a[i]!,raw[i]!)<1.7);const high=c.sample(102,100,1,[{...actors[0]!,feetY:10}]);assert.deepEqual(high.map(p=>[p.x,p.z]),raw.map(p=>[p.x,p.z]));});
test('swept body contacts block long crossing, preserve tangential movement, allow overlap escape and ignore roof height',()=>{const bodies=[{x:0,z:0}];const hit=slideTownCrowd({x:0,z:3},{x:0,z:-6},bodies);assert(hit.z>.65&&hit.z<.66);const slide=slideTownCrowd({x:.5,z:2},{x:1.8,z:-2},bodies);assert(slide.z<1.9&&slide.x>.5);assert.deepEqual(slideTownCrowd({x:.3,z:0},{x:1,z:0},bodies),{x:1,z:0});assert(slideTownCrowd({x:.3,z:0},{x:-1,z:0},bodies).x>=.2999);assert.deepEqual(slideTownCrowd({x:0,z:3},{x:0,z:-6},bodies,9),{x:0,z:-6});});
test('bounded render correction is smooth at 30 60 and 120 Hz, freezes paused poses and resets teleports',()=>{for(const hz of [30,60,120]){const c=new TownCrowd(73129),motion=new TownRenderMotion();let prior=motion.update(c.sample(100),0,c.plan,true),moved=0;const walker=prior.findIndex(p=>p.moving);assert(walker>=0);for(let n=1;n<=hz*2;n++){const next=motion.update(c.sample(100+n/hz),1/hz,c.plan);for(let i=0;i<100;i++){assert(distance(prior[i]!,next[i]!)<=(next[i]!.yielding?10:3)/hz+1e-8);assert(townPathClear(c.plan,prior[i]!,next[i]!));const angle=Math.atan2(Math.sin(next[i]!.facing-prior[i]!.facing),Math.cos(next[i]!.facing-prior[i]!.facing));assert(Math.abs(angle)<=4/hz+1e-8);}if(distance(prior[walker]!,next[walker]!)>1e-5)moved++;prior=next;}assert(moved>hz);assert.deepEqual(motion.update(c.sample(103),0,c.plan),prior);assert.deepEqual(motion.update(c.sample(400),0,c.plan,true),c.sample(400));}});
test('appearance has seeded legible silhouette diversity and immutable stable identity across seed cache eviction',()=>{const roster=townResidents(73129),ids=roster.map(r=>[r.id,r.name,r.dialogue]);assert(new Set(roster.map(r=>JSON.stringify(r.appearance))).size===100);assert(new Set(roster.map(r=>r.appearance.coat)).size===4);assert(new Set(roster.map(r=>r.appearance.accessory)).size===4);for(const r of roster)assert(Object.isFrozen(r.appearance));for(let n=1;n<=6;n++)townResidents(n);assert.deepEqual(townResidents(73129).map(r=>[r.id,r.name,r.dialogue]),ids);});
test('articulated gait alternates planted and lifted soles with connected equal-length leg segments',()=>{for(const r of townResidents(73129)){const pose={...townResidentPose(r,100,startingTown(73129)),moving:true,speed:1,distance:0,yielding:false};let lifted=false;for(let n=0;n<128;n++){const g=townGait(r,{...pose,distance:n/128*2},100);for(const foot of [g.left,g.right]){assert(foot.ankle.y>=.12-1e-9);if(foot.planted)assert(Math.abs(foot.ankle.y-.12)<1e-8);else if(foot.ankle.y>.20)lifted=true;const a=Math.hypot(foot.hip.y-foot.knee.y,foot.hip.z-foot.knee.z),b=Math.hypot(foot.ankle.y-foot.knee.y,foot.ankle.z-foot.knee.z);assert(Math.abs(a-b)<1e-9);assert(a<.4);}}assert(lifted);}});
test('default stance foot is world-stationary on straight constant-speed travel and diagnostic gait knob really changes output',()=>{const r=townResidents(73129)[20]!,pose={x:0,z:0,facing:0,moving:true,activity:'walking to work' as const,speed:1,distance:0,yielding:false};let checked=0;for(let n=0;n<200;n++){const t=n/1000,a=townGait(r,{...pose,distance:t},100),b=townGait(r,{...pose,distance:t+.001},100.001);for(const side of ['left','right'] as const)if(a[side].planted&&b[side].planted){assert(Math.abs((t+a[side].ankle.z*r.height)-(t+.001+b[side].ankle.z*r.height))<1e-8);checked++;}}assert(checked>100);assert.notDeepEqual(townGait(r,{...pose,distance:.25},100,0),townGait(r,{...pose,distance:.25},100,1));});
test('view updates every frame while retaining 10/2 Hz activity budgets and bounded instance resources',()=>{const v=createTownView(73129),p=new TownPopulation(73129);try{for(let n=0;n<121;n++){v.update(100+n/120,TOWN_CENTER,()=>true,true,DEFAULT_TOWN_TUNING,n===0,1/120);p.update(100+n/120,TOWN_CENTER,DEFAULT_TOWN_TUNING,n===0);}assert.equal(v.stats.renderFrames,121);assert(v.stats.sampledUpdates<1500);assert.equal(v.stats.sampledUpdates,p.updates);assert.equal(v.stats.meshes,6);assert(v.stats.instances<2000);assert(v.stats.triangles<30000);assert.equal(v.stats.fullPhysicsBrains,0);const matrices=v.root.children.map((m:any)=>Array.from(m.instanceMatrix.array));v.update(101,TOWN_CENTER,()=>true,true,DEFAULT_TOWN_TUNING,false,0);assert.deepEqual(v.root.children.map((m:any)=>Array.from(m.instanceMatrix.array)),matrices);v.update(101,{x:1000,z:1000},()=>true,true,DEFAULT_TOWN_TUNING,false,0);assert.equal(v.stats.visible,0);v.update(101,TOWN_CENTER,()=>false,true,DEFAULT_TOWN_TUNING,false,0);assert.equal(v.stats.visible,0);v.update(101,TOWN_CENTER,()=>true,true,DEFAULT_TOWN_TUNING,false,1/120);assert.equal(v.stats.visible,100);}finally{v.dispose();}});
test('version-two registry validates low default and high values; unknown legacy settings fail explicitly',()=>{assert.deepEqual(validateTownTuning(DEFAULT_TOWN_TUNING),DEFAULT_TOWN_TUNING);assert.throws(()=>validateTownTuning({population:100,activeBudget:24,activityScale:1}));for(const patch of [{gaitScale:0,gestures:0,appearanceVariety:0,avoidance:0},{gaitScale:1.25,activeBudget:48,activityScale:2}])assert(validateTownTuning({...DEFAULT_TOWN_TUNING,...patch}));});

test('two-peer pinch points retain NPC spacing as well as player and wall exclusion',()=>{const c=new TownCrowd(73129);for(const gap of [1.3,1.6]){const x=-163.9800000213,actors=[{id:'a',x:x-gap/2,z:-142.6,feetY:6},{id:'b',x:x+gap/2,z:-142.6,feetY:6}],p=c.sample(180,100,1,actors);for(let i=0;i<p.length;i++){for(const a of actors)assert(distance(p[i]!,a)>=.685-1e-8);for(let j=i+1;j<p.length;j++)assert(distance(p[i]!,p[j]!)>=.605-1e-8);assert(distance(p[i]!,clearTownBody(c.plan,p[i]!))<1e-8);}assert.equal(c.unresolvedActorContacts,0);}});

test('interpolated crossing roots stay separated without a packing teleport in presentation',()=>{const c=new TownCrowd(73129),m=new TownRenderMotion();let prior;for(let n=0;n<121;n++){const raw=c.sample(203+n/60),shown=m.update(raw,1/60,c.plan,n===0);for(let i=0;i<100;i++){if(prior)assert(distance(shown[i]!,prior[i]!)<.168);for(let j=i+1;j<100;j++){assert(distance(raw[i]!,raw[j]!)>=.605-1e-7);assert(distance(shown[i]!,shown[j]!)>=.62-1e-7);}}prior=shown.map(p=>({...p}));}});
test('synthetic corrected player approach never triggers ordinary render teleports',()=>{const v=createTownView(73129);try{let prior;for(let n=0;n<=240;n++){const actor={id:'approach',x:-208-n/60*2,z:-142.6,feetY:6};v.update(30+n/60,TOWN_CENTER,()=>true,true,undefined,n===0,1/60,[actor]);if(prior)for(let i=0;i<100;i++)assert(distance(v.poses[i]!,prior[i]!)<=10/60+1e-7);prior=v.poses.map(p=>({...p}));}}finally{v.dispose();}});

test('detailed activity budget and appearance switches change production matrices with identical collision poses',()=>{const low=createTownView(73129),high=createTownView(73129);try{const a={...DEFAULT_TOWN_TUNING,activeBudget:8},b={...DEFAULT_TOWN_TUNING,activeBudget:48};low.update(200,TOWN_CENTER,()=>true,true,a,true);high.update(200,TOWN_CENTER,()=>true,true,b,true);assert.deepEqual(low.poses,high.poses);assert(low.stats.active<high.stats.active);const matrices=(v:ReturnType<typeof createTownView>)=>v.root.children.map((m:any)=>Array.from(m.instanceMatrix.array));assert.notDeepEqual(matrices(low),matrices(high));low.update(200,TOWN_CENTER,()=>true,true,{...a,appearanceVariety:0},true);assert(low.stats.instances<high.stats.instances);}finally{low.dispose();high.dispose();}});
