import test from 'node:test';import assert from 'node:assert/strict';
import {townFrameSeconds,TownSnapshotContinuity} from '../src/town-life-runtime.ts';
import {TownLifeRenderBuffer,TOWN_RENDER_TIMING} from '../src/town-crowd.ts';
import {createTownView} from '../src/town-view.ts';
import {startingTown} from '../src/starting-town.ts';
import {assertMainFrameContract,steadyCase,worldCase,assertSteadyCase,assertWorldCase} from './helpers/town-frame-cases.ts';
test('actual main crowd frame boundary keeps low-rate elapsed time and original pause and worker tick gates',()=>{assertMainFrameContract();for(const [raw,expected]of [[-1,0],[0,0],[100,.1],[200,.2],[500,.5],[2000,.5],[Infinity,0],[NaN,0]])assert.equal(townFrameSeconds(raw!),expected);assert.equal(TOWN_RENDER_TIMING.maxStepSeconds,.05);});
for(const cadence of ['fps15','fps10','fps5','variable'] as const)for(const online of [false,true])test(`actual timestamped body matrices keep steady speed ${cadence} ${online?'jittered online':'solo'}`,()=>assertSteadyCase(steadyCase(createTownView,townFrameSeconds,{cadence,online})));
for(const fixture of ['15','150'] as const)for(const cadence of ['fps10','fps5','variable','gap500','gap1000','gap2000','gap5000'] as const)for(const online of [false,true])test(`main-boundary saved world ${fixture} preserves motion pause and walls ${cadence} ${online?'jittered online':'solo'}`,()=>assertWorldCase(worldCase(createTownView,townFrameSeconds,{fixture,cadence,online})));
test('timestamped buffer accepts same-tick action metadata without restarting its trajectory',()=>{const b=new TownLifeRenderBuffer(),plan=startingTown(73129),pose={x:-188,z:-134,facing:Math.PI/2,speed:1.8,distance:0,moving:true,yielding:false,activity:'walking to work' as const};b.accept([pose],[pose],0,true);const next={...pose,x:pose.x+.9,distance:.9};b.accept([next],[next],.5);const before=b.sample(.75,plan)[0]!;b.accept([{...next,activity:'meeting neighbors'}],[{...next,activity:'meeting neighbors'}],.5);const after=b.sample(.75,plan)[0]!;assert.equal(after.x,before.x);assert.equal(after.z,before.z);assert.equal(after.activity,'meeting neighbors');assert(Math.abs(b.sample(.8,plan)[0]!.x-(pose.x+.54))<1e-8);});

test('town snapshot continuity resets exactly once after a verified connection resume',()=>{const c=new TownSnapshotContinuity();for(let n=0;n<10;n++){c.note('connected');assert.equal(c.take(30),false);}c.note('reconnecting');assert.equal(c.take(30),false);c.note('connected');assert.equal(c.take(30),true);assert.equal(c.take(30),false);c.note('paused');c.note('connected');assert.equal(c.take(30),true);c.note('reconnecting');c.note('connected');assert.equal(c.take(.5),false);assert.equal(c.take(30),false);c.note('reconnecting');c.note('offline');c.note('connected');assert.equal(c.take(30),false);});

test('actual main visual handler distinguishes slow frames from verified long connection resumption',async()=>{const {readFileSync}=await import('node:fs'),{stripTypeScriptTypes}=await import('node:module'),{mainFunction}=await import('./helpers/main-source.ts'),{createTownLifeOpening,advanceTownLife}=await import('../src/town-life.ts'),{townLifeClock,townLifePoses}=await import('../src/town-life-runtime.ts'),{townClock}=await import('../src/town-crowd.ts'),{TOWN_SPAWN}=await import('../src/starting-town.ts');const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),view=createTownView(73129),fresh=createTownView(73129),continuity=new TownSnapshotContinuity(),state={seed:73129,townLife:createTownLifeOpening(73129),zone:'valley',player:TOWN_SPAWN,causal:undefined},actor={id:'solo',...TOWN_SPAWN,feetY:6};let pauses=0;const deps={townView:view,townLifeView:null,townSnapshotContinuity:continuity,townActivity:{pause(){pauses++;}},performance:{now:()=>1000},state,labActive:false,townLifeClock,townLifePoses,townClock,regionalConfirmedObstacles:{has:()=>true},townActors:()=>[actor],coop:{active:true},startup:{note(){}},frontierRoot:{visible:false}};const sync=new Function(...Object.keys(deps),stripTypeScriptTypes(mainFunction(main,'syncFrontierVisuals'))+';return syncFrontierVisuals;')(...Object.values(deps));try{sync(0,true);const previous=view.poses.map(p=>({...p}));state.townLife=advanceTownLife(state.townLife,2);sync(.5);assert(Math.max(...view.poses.map((p,i)=>Math.hypot(p.x-previous[i]!.x,p.z-previous[i]!.z)))<2);assert.equal(pauses,0);continuity.note('reconnecting');continuity.note('connected');state.townLife=advanceTownLife(state.townLife,30);sync(0);fresh.update(townLifeClock(state.townLife),state.player,()=>true,true,undefined,true,0,[actor],true,townLifePoses(state.townLife));assert.deepEqual(view.poses,fresh.poses);assert.equal(pauses,1);const roots=view.poses.map(p=>[p.x,p.z]);continuity.note('paused');continuity.note('connected');state.townLife=advanceTownLife(state.townLife,.5);sync(0);assert.deepEqual(view.poses.map(p=>[p.x,p.z]),roots);assert.equal(pauses,1,'short resume is not a forced replacement');}finally{view.dispose();fresh.dispose();}});

for(const online of [false,true])test(`real retained world rejoins after deliberately omitted five-second transport history without a discontinuity ${online?'online':'solo'}`,()=>{const r=worldCase(createTownView,townFrameSeconds,{fixture:'15',cadence:'gap5000',online,seconds:60,omitAcceptedHistory:true});assertWorldCase(r);});
