import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {createTownLifeOpening,createTownLife,advanceTownLife,validTownLife,immutableTownLife,TOWN_LIFE_ENGINE,townLifePhaseOffset} from '../src/town-life.ts';
import {createRegionalState,enableStartingTown,serializeSave,parseSave,applyAction} from '../src/world.ts';
import {townLifeClock} from '../src/town-life-runtime.ts';import {townResidents} from '../src/town-residents.ts';import {townPersonDetail} from '../src/town-ui.ts';
import {createRoom,syncRoom} from '../server/coop-authority.ts';
import {startupMatrixCase} from './helpers/town-startup-cases.ts';
const legacy=(name='15')=>JSON.parse(readFileSync(new URL('./fixtures/town-motion-v11/'+name+'.json',import.meta.url),'utf8'));
for(const seed of [0,7,42,73129,0xffffffff])test(`inhabited opening seed ${seed} has real mixed goals at tick zero and finite charged inputs`,()=>{const life=createTownLifeOpening(seed),cold=createTownLife(seed);assert(validTownLife(life,seed));assert.deepEqual(TOWN_LIFE_ENGINE.create(seed),life);assert.deepEqual(createTownLifeOpening(seed),life);assert.equal(life.tick,0);assert.equal(life.cycleTick,0);assert.equal(life.accumulator,0);assert.deepEqual(life.sourceLedger,cold.sourceLedger);assert.deepEqual(life.playerSpent,cold.playerSpent);assert(life.residents.filter(r=>r.status==='traveling'&&r.speed>1).length>=20);assert(life.residents.filter(r=>r.status==='acting'&&!r.facilityId!.startsWith('home-')).length>=20);assert(life.residents.filter(r=>r.facilityId?.startsWith('home-')).length<=40);for(const r of life.residents){assert.equal(r.completed,0);assert.equal(r.distance,0);assert.equal(r.desire.progress,0);}for(const k of ['pantry','water','materials','harvest']as const){assert.equal(life.ledger.produced[k],0);assert(Math.abs(life.ledger.initial[k]-life.ledger.consumed[k]-life.resources[k])<1e-5);}let frames=life;for(let n=0;n<900;n++)frames=advanceTownLife(frames,1/60);assert.deepEqual(frames,advanceTownLife(life,15));assert.deepEqual(immutableTownLife(JSON.parse(JSON.stringify(life)),seed),life);});
test('fresh world uses shared inhabited authority without advancing campaign time and existing life loads exactly',()=>{const before=createRegionalState(73129),fresh=enableStartingTown(before);assert.equal(fresh.causal,before.causal);assert.equal(fresh.player,before.player);assert.equal(fresh.inventory,before.inventory);assert(fresh.townLife!.residents.filter(r=>r.status==='traveling').length>=20);const old={...fresh,townLife:immutableTownLife(legacy(),73129)},enabled=enableStartingTown(old);assert.equal(enabled,old);assert.deepEqual(parseSave(serializeSave(old)),old);});
test('retained V11 synchronized home save recovers by bounded genuine movement without resetting ledgers or awarding interrupted work',()=>{const old=immutableTownLife(legacy(),73129),bytes=JSON.stringify(old);let life=old;for(let n=0;n<30;n++){const before=life;life=advanceTownLife(life,.5);assert(validTownLife(life,73129));for(const r of life.residents){const p=before.residents[r.index]!;assert(Math.hypot(r.x-p.x,r.z-p.z)<=.900001);if(r.interruptions>p.interruptions){assert(['rest','leisure'].includes(p.action!));assert(p.facilityId!.startsWith('home-'));assert.equal(r.completed,p.completed);assert.equal(r.desire.completed,p.desire.completed);assert.equal(r.desire.progress,p.desire.progress);}}}assert.equal(JSON.stringify(old),bytes);assert(life.residents.filter(r=>r.status==='traveling'&&r.speed>0).length>=40);assert(life.residents.filter(r=>r.facilityId?.startsWith('home-')).length<=50);assert.deepEqual(life.playerSpent,old.playerSpent);});
for(const seed of [0,7,42,73129,0xffffffff])test(`actual first-15-second matrices and landscape portrait wide cameras bustle for seed ${seed}`,()=>startupMatrixCase(undefined,seed,30));
for(const hz of [30,60,120])test(`production startup body matrices at ${hz} Hz shared snapshots`,()=>startupMatrixCase(undefined,73129,hz,true));
test('retained V11 save progresses actual matrices for all 100 bodies while residents walk out naturally',()=>startupMatrixCase(undefined,73129,30,false,legacy()));
test('life presentation clock and autonomous timetable belong to life authority rather than regional time',()=>{const life=advanceTownLife(createTownLifeOpening(73129),15.25);assert.equal(townLifeClock(life),15.25);const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');assert.match(main,/townView\?\.update\(state\.townLife\?townLifeClock\(state\.townLife\):townClock\(state\.causal\)/);const r=townResidents(73129)[17]!;assert.notEqual(townLifePhaseOffset(r),r.phaseOffset);assert.notEqual(townPersonDetail(r,townResidents(73129),15,true),townPersonDetail(r,townResidents(73129),15,false));});

for(const saved of [false,true])test(`actual world ticks and co-op authority retain the same 15-second life progression ${saved?'saved':'fresh'}`,()=>{let solo=enableStartingTown(createRegionalState(73129));if(saved)solo={...solo,townLife:immutableTownLife(legacy(),73129)};const room=createRoom('startup-host','Host',solo,1000),host=room.players[0]!,initial=solo.townLife!;for(let frame=1;frame<=900;frame++){solo=applyAction(solo,{type:'tick',dt:1/60});if(frame%15===0)syncRoom(room,'startup-host',{seq:frame/15,sessionId:host.sessionId,actions:[]},1000+frame*1000/60);}assert.equal(solo.townLife!.tick,initial.tick+30);assert.equal(room.world.townLife!.tick,initial.tick+30);assert.deepEqual(room.world.townLife,solo.townLife);assert.deepEqual(solo.townLife,advanceTownLife(initial,15,undefined,[{id:'world-actor-0',x:solo.player.x,z:solo.player.z,feetY:6}]));});
