import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {handleCoop} from '../server/coop-api.ts';
import {createRegionalState,validateSave,serializeSave,parseSave} from '../src/world.ts';
import {startingTown} from '../src/starting-town.ts';
import {createVertical} from '../server/coop-vertical.ts';
import type {CoopRoom} from '../server/coop-authority.ts';
import type {D1Database,D1Statement} from '../server/coop-store.ts';
function fixture(){const db=new DatabaseSync(':memory:');for(const name of readdirSync(new URL('../drizzle',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())db.exec(readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8'));let now=1800000000000,conflicts=0,pause:undefined|{arrived:()=>void;gate:Promise<void>};const DB:D1Database={prepare(sql){let values:unknown[]=[];const statement:D1Statement={bind(...args){values=args;return statement;},async first<T>(){return (db.prepare(sql).get(...values as never[])??null) as T|null;},async all<T>(){return {results:db.prepare(sql).all(...values as never[]) as T[]};},async run(){if(sql.startsWith('UPDATE axiom_coop_rooms')&&pause){const p=pause;pause=undefined;p.arrived();await p.gate;}const result=db.prepare(sql).run(...values as never[]),changes=Number(result.changes);if(sql.startsWith('UPDATE axiom_coop_rooms')&&!changes)conflicts++;return {success:true,meta:{changes}};}};return statement;}};return {async request(user:string,path:string,body?:unknown){const r=await handleCoop(new Request('https://town-tests.invalid/api/coop'+path,{method:body===undefined?'GET':'POST',headers:{'oai-authenticated-user-id':user,Origin:'https://town-tests.invalid',...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})}),{DB},now);assert(r);return {status:r.status,body:await r.json() as any};},stored(id:string):CoopRoom{return JSON.parse(String(db.prepare('SELECT body FROM axiom_coop_rooms WHERE id = ?').get(id)!.body));},replace(room:CoopRoom){db.prepare('UPDATE axiom_coop_rooms SET body = ? WHERE id = ?').run(JSON.stringify(room),room.id);},hold(){let release=()=>{},arrived=()=>{};const gate=new Promise<void>(r=>release=r),waiting=new Promise<void>(r=>arrived=r);pause={gate,arrived};return {waiting,release};},conflicts:()=>conflicts,close:()=>db.close()};}

test('four HTTP actors race finite arrival stock through SQLite CAS; lost-response replay is idempotent and durable',async()=>{const f=fixture();try{const s=createRegionalState(73129),entry=startingTown(s.seed).shops[0]!.entry;s.player={...s.player,...entry};const created=await f.request('host','/rooms',{name:'Host',world:s});assert.equal(created.status,201,JSON.stringify(created.body));const peers=[{user:'host',s:created.body}];for(let i=1;i<4;i++){const r=await f.request('guest'+i,'/join',{name:'Guest '+i,code:created.body.code});assert.equal(r.status,200);peers.push({user:'guest'+i,s:r.body});}const room=f.stored(created.body.roomId);for(const p of room.players){p.player={...p.player,...entry};p.motion=createVertical(6);}f.replace(room);const command={type:'town-purchase',command:{offerId:'arrival-kit',expectedRevision:0}},send=async(p:typeof peers[number])=>{const r=await f.request(p.user,`/rooms/${p.s.roomId}/sync`,{seq:1,sessionId:p.s.sessionId,actions:[command]});assert.equal(r.status,200,JSON.stringify(r.body));p.s=r.body;};const held=f.hold(),pending=send(peers[1]!);await held.waiting;try{await send(peers[0]!);}finally{held.release();}await pending;await Promise.all(peers.slice(2).map(send));assert(f.conflicts()>=1);for(const p of peers){const r=await f.request(p.user,`/rooms/${p.s.roomId}`);assert.equal(r.body.world.town.revision,1);assert.deepEqual(r.body.world.inventory,{scrap:3,core:0,water:1});assert(validateSave(r.body.world));}const replay=await f.request('host',`/rooms/${created.body.roomId}/sync`,{seq:1,sessionId:created.body.sessionId,actions:[command]});assert.equal(replay.status,200);assert.equal(replay.body.world.town.receipts.length,1);const stored=f.stored(created.body.roomId).world;assert.deepEqual(parseSave(serializeSave(stored)),stored);
 // A forged present ledger must fail on read/resume, never be replaced by empty stock.
 const bad=f.stored(created.body.roomId);bad.world.town={...bad.world.town!,revision:99};f.replace(bad);assert.equal((await f.request('host',`/rooms/${created.body.roomId}`)).status,503);
 }finally{f.close();}});
