import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {TownActivityMonitor,summarizeTownActivity,type TownActivityInput} from '../src/town-activity.ts';
import {createTownLifeOpening,advanceTownLife} from '../src/town-life.ts';
import {createTownView} from '../src/town-view.ts';import {townLifePoses,townLifeClock} from '../src/town-life-runtime.ts';import {TOWN_SPAWN} from '../src/starting-town.ts';
function fixture(){const monitor=new TownActivityMonitor();let life=createTownLifeOpening(73129);for(let f=0;f<=60;f++){if(f)life=advanceTownLife(life,.25);const input:TownActivityInput={now:f*250,seed:73129,life,matrices:life.residents.map(r=>({index:r.index,x:r.x,z:r.z,matrixHash:f*101+r.index,instances:17,inFrustum:true,screenX:0,screenY:0})),expectedDrawn:100,physicsStep:f*15,renderFrames:f*15+1,renderTime:f*.25,paused:false,mode:'solo',camera:Array(16).fill(0)};monitor.sample(input,'test');}return monitor.report();}
test('watchdog observes all 100 residents with bounded opening and rolling windows and detached reports',()=>{const report=fixture();assert.equal(report.opening.length,61);assert.equal(report.opening[0]!.residents.length,100);assert.equal(report.recent.length,61);assert.equal(report.openingSummary!.modelProgressed,100);assert.equal(report.openingSummary!.residentsAnimated,100);assert.equal(report.openingSummary!.warnings.length,0);assert.doesNotMatch(JSON.stringify(report),/"(?:inventory|account|token|roomId|playerSpent)":/);});
test('trailing three-second authority freeze is detected after twelve healthy seconds',()=>{const r=fixture(),freeze=r.recent[48]!.tick;for(const s of r.recent.slice(48))s.tick=freeze;const sum=summarizeTownActivity(r.recent)!;assert(sum.warnings.some(s=>s.includes('town authority is stalled')));});
test('actual occupied action stagnation and reserved-route stall are independently detected',()=>{const r=fixture();for(const s of r.recent.slice(36)){const a=s.residents[0]!;a.status='acting';a.taskMoving=false;a.blockedSeconds=0;a.remaining=12;a.completed=0;const b=s.residents[1]!;b.status='traveling';b.distance=12;}const sum=summarizeTownActivity(r.recent)!;assert(sum.modelStalled.includes(0));assert(sum.routeStalled.includes(1));});
test('missing draw evidence and frozen render-frame counters cannot report healthy',()=>{const r=fixture();for(const s of r.recent.slice(36)){s.counts.drawn=0;s.counts.expectedDrawn=100;s.renderFrames=10;for(const p of s.residents)p.drawn=false;}const sum=summarizeTownActivity(r.recent)!;assert(sum.warnings.some(s=>s.includes('missing from emitted matrices')));assert(sum.warnings.some(s=>s.includes('Render-frame counter')));});
test('frozen articulated matrices and lagging displayed travelers raise separate render alarms',()=>{const r=fixture();for(const s of r.recent.slice(36)){s.residents[0]!.matrixHash=7;s.residents[0]!.modelChanged=true;const p=s.residents[1]!;p.status='traveling';p.lag=4;p.displayX=0;p.displayZ=0;p.distance=s.seconds*1.8;}const sum=summarizeTownActivity(r.recent)!;assert(sum.renderStalled.includes(0));assert(sum.renderStalled.includes(1));});
test('legacy frozen-door cohort fails bustle even when the authority and some animation remain healthy',()=>{const r=fixture();for(const s of r.recent){s.counts.atHome=97;s.counts.traveling=3;s.counts.frustumTravelers=0;}const sum=summarizeTownActivity(r.recent)!;assert(sum.warnings.some(s=>s.includes('Synchronized home cohort')));assert(sum.warnings.some(s=>s.includes('fewer than two travelers')));});
test('healthy stationary activity is not misclassified as a frozen resident',()=>{const r=fixture();for(const s of r.recent){const p=s.residents[0]!;p.status='acting';p.taskMoving=false;p.blockedSeconds=0;p.remaining=30-s.seconds;p.completed=0;p.displayX=0;p.displayZ=0;p.distance=0;p.matrixHash=Math.floor(s.seconds*100);p.modelChanged=true;}const sum=summarizeTownActivity(r.recent)!;assert(!sum.modelStalled.includes(0));assert(!sum.routeStalled.includes(0));assert(!sum.renderStalled.includes(0));});
test('pauses do not consume activity windows; reset clears evidence and callback gaps remain observable',()=>{const m=new TownActivityMonitor(),life=createTownLifeOpening(73129),base={seed:73129,life,matrices:[],physicsStep:0,renderFrames:1,renderTime:0,paused:false,mode:'solo' as const,camera:[]};m.sample({...base,now:0});m.sample({...base,now:250,paused:true});m.sample({...base,now:15000,paused:true});assert.equal(m.report().opening.length,1);m.sample({...base,now:15250});assert.deepEqual(m.report().callbackGaps,[]);m.sample({...base,now:19000});assert.deepEqual(m.report().callbackGaps,[3.75]);assert.equal(m.report(21000).callbackAgeSeconds,2);m.reset();assert.equal(m.report().status,'waiting');assert.equal(m.report().opening.length,0);});
test('view evidence reads real per-resident instance arrays and remains distinct from model poses',()=>{const life=createTownLifeOpening(73129),view=createTownView(73129);try{view.update(townLifeClock(life),TOWN_SPAWN,()=>true,true,undefined,true,0,[],false,townLifePoses(life));const before=view.matrixEvidence(),torso=(view.root.children[1] as any).instanceMatrix.array;torso[12]+=3;const after=view.matrixEvidence();assert.equal(after[0]!.x,before[0]!.x+3);assert.notEqual(after[0]!.matrixHash,before[0]!.matrixHash);assert.equal(after[1]!.matrixHash,before[1]!.matrixHash);assert.notEqual(after[0]!.x,view.poses[0]!.x);view.update(0,TOWN_SPAWN,()=>false,true,undefined,true);assert.equal(view.matrixEvidence().length,0);}finally{view.dispose();}});
test('population capture is post-render, bounded and read-only with explicit export and text fallback',()=>{const main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),monitor=readFileSync(new URL('../src/town-activity.ts',import.meta.url),'utf8'),panel=readFileSync(new URL('../src/town-motion-diagnostics.ts',import.meta.url),'utf8');assert.match(main,/renderer\.render\(scene,camera\);recordTownMotion\(now,rawFrameMs\/1000,blocked\);recordTownActivity\(now,blocked\)/);assert.match(main,/expectedDrawn:townView.stats.visible,physicsStep:lastPhysicsStep/);assert.match(main,/townActivity.reset\(\)/);assert.match(panel,/motion-activity-export/);assert.match(panel,/Copy the JSON text below/);assert.doesNotMatch(monitor,/fetch\(|localStorage|sessionStorage|setInterval|advanceTownLife|applyAction|sendBeacon/);});

test('draw health honors actual instance counts and bucket visibility rather than planned ranges',()=>{const life=createTownLifeOpening(73129),view=createTownView(73129);try{view.update(0,TOWN_SPAWN,()=>true,true,undefined,true,0,[],false,townLifePoses(life));assert.equal(view.matrixEvidence().length,100);const torso=view.root.children[1] as any;torso.count=0;assert.equal(view.matrixEvidence().length,0);view.update(0,TOWN_SPAWN,()=>true,true,undefined,true,0,[],false,townLifePoses(life));for(const mesh of view.root.children)mesh.visible=false;assert.equal(view.matrixEvidence().length,0);}finally{view.dispose();}});

test('intentional lab or town absence suspends the callback anchor without discarding startup evidence',()=>{const m=new TownActivityMonitor(),life=createTownLifeOpening(73129),base={seed:73129,life,matrices:[],physicsStep:0,renderFrames:1,renderTime:0,paused:false,mode:'solo' as const,camera:[]};m.sample({...base,now:0});m.pause(60000);m.sample({...base,now:60250});assert.deepEqual(m.report().callbackGaps,[]);assert(m.report().openingSummary!.duration<.5);assert.equal(m.report().opening.length,2);});

test('slowly advancing roots with persistent multi-metre lag warn even when every body matrix changes',()=>{const r=fixture();for(const s of r.recent){const p=s.residents[0]!;p.status='traveling';p.lag=4;p.displayX=s.seconds*1.2;p.displayZ=0;p.distance=s.seconds*1.8;}const sum=summarizeTownActivity(r.recent)!;assert(sum.lagging.includes(0));assert(!sum.renderStalled.includes(0));assert.equal(sum.bodyMatricesChanged,100);assert(sum.warnings.some(w=>w.includes('still moving')));});
test('brief arrival corrections remain distinct from sustained display lag',()=>{const r=fixture();for(const s of r.recent.slice(-4))s.residents[0]!.lag=4;const sum=summarizeTownActivity(r.recent)!;assert(!sum.lagging.includes(0));assert.equal(sum.maxLag,4);});
test('low town render cadence is reported separately from healthy authority and intentional absent draws',()=>{const r=fixture();for(const s of r.recent){s.renderFrames=s.seconds*5+1;s.activeCounters.renderFrames=s.seconds*5;}let sum=summarizeTownActivity(r.recent)!;assert.equal(sum.renderFps,5);assert.equal(sum.authorityHz,2);assert.equal(sum.physicsHz,60);assert(sum.warnings.some(w=>w.includes('Low render cadence')));for(const s of r.recent){s.counts.expectedDrawn=0;s.counts.drawn=0;s.renderFrames=1;s.activeCounters.renderFrames=0;}sum=summarizeTownActivity(r.recent)!;assert(!sum.warnings.some(w=>w.includes('Low render cadence')));});
test('active callback stalls count as elapsed wall time instead of overstating render cadence',()=>{const m=new TownActivityMonitor();let life=createTownLifeOpening(73129);for(let n=0;n<4;n++){if(n)life=advanceTownLife(life,2);m.sample({now:n*2000,seed:73129,life,matrices:[],expectedDrawn:100,physicsStep:n*120,renderFrames:n+1,renderTime:n*2,paused:false,mode:'solo',camera:[]});}const r=m.report(),s=r.recentSummary!;assert.equal(s.duration,6);assert.equal(s.renderFps,.5);assert.equal(s.authorityHz,2);assert.deepEqual(r.callbackGaps,[2,2,2]);});
test('rolling activity evidence remains bounded by time as well as sample count after active stalls',()=>{const m=new TownActivityMonitor();let life=createTownLifeOpening(73129);for(let n=0;n<40;n++){if(n)life=advanceTownLife(life,1);m.sample({now:n*1000,seed:73129,life,matrices:[],physicsStep:n*60,renderFrames:n*30,renderTime:n,paused:false,mode:'solo',camera:[]});}const r=m.report();assert(r.recent.length<=16);assert.equal(r.recentSummary!.duration,15);assert.equal(r.status,'ready');});
test('tiny breathing matrix changes are not labeled sustained root walking',()=>{const r=fixture();for(const s of r.recent)for(const p of s.residents){p.displayX=p.index;p.displayZ=0;p.matrixChanged=true;}const sum=summarizeTownActivity(r.recent)!;assert.equal(sum.bodyMatricesChanged,100);assert.equal(sum.residentsMoved,0);assert.equal(sum.residentsWalking,0);assert.match(r.scope,/tiny breathing/);});
test('unmeasurable first sample is excluded from camera root-movement extrema',()=>{const r=fixture();for(const s of r.recent)s.counts.frustumMoving=s.seconds?3:0;assert.equal(summarizeTownActivity(r.recent)!.frustumMovingMin,3);assert.equal(summarizeTownActivity(r.recent.slice(0,1))!.frustumMovingMin,null);});
test('coarse sample cadence still catches persistent lag across a three-second boundary',()=>{const r=fixture(),samples=r.recent.filter((_,i)=>i%4===0);for(const s of samples)s.residents[0]!.lag=4;assert(summarizeTownActivity(samples)!.lagging.includes(0));});

test('known menu pauses cannot inflate render rates and erase an observed slow-frame warning',()=>{const m=new TownActivityMonitor();let life=createTownLifeOpening(73129);const sample=(now:number,renderFrames:number,physicsStep:number,paused:boolean)=>m.sample({now,seed:73129,life,matrices:life.residents.map(r=>({index:r.index,x:r.x,z:r.z,matrixHash:renderFrames+r.index,instances:17,inFrustum:true,screenX:0,screenY:0})),expectedDrawn:100,physicsStep,renderFrames,renderTime:life.tick*.5,paused,mode:'solo',camera:[]});for(let n=0;n<=20;n++){if(n)life=advanceTownLife(life,.25);sample(n*250,n*2,n*15,false);}assert.equal(m.report().recentSummary!.renderFps,8);for(let n=1;n<=120;n++)sample(5000+n*250,40+n*15,300,true);life=advanceTownLife(life,.25);sample(35250,1842,315,false);const report=m.report(),summary=report.recentSummary!;assert.equal(summary.renderFps,8);assert.equal(summary.authorityHz,2);assert(summary.warnings.some(w=>w.includes('Low render cadence')));assert.equal(report.recent.at(-1)!.renderFrames,1842,'retain raw diagnostic counter');assert.equal(report.recent.at(-1)!.activeCounters.renderFrames,40,'exclude paused draws');});
test('dormant rebase and hidden online progress never count as observed walking or active time',()=>{const m=new TownActivityMonitor();let life=createTownLifeOpening(73129);const matrices=(x:number)=>life.residents.map(r=>({index:r.index,x:r.x+x,z:r.z,matrixHash:x+r.index,instances:17,inFrustum:true,screenX:0,screenY:0}));const sample=(now:number,x:number,renderFrames:number)=>m.sample({now,seed:73129,life,matrices:matrices(x),expectedDrawn:100,physicsStep:life.tick*30,renderFrames,renderTime:life.tick*.5,paused:false,mode:'online',camera:[]});sample(0,0,1);sample(250,0,16);m.pause(30000);life=advanceTownLife(life,30);sample(30250,40,1000);let report=m.report();assert.equal(report.recent.at(-1)!.counts.frustumMoving,0);assert.equal(report.recent.at(-1)!.motionMeasured,false);assert.equal(report.recentSummary!.residentsMoved,0);assert.equal(report.recentSummary!.residentsWalking,0);assert.equal(report.recentSummary!.authoritySteps,0);assert.equal(report.recentSummary!.duration,.25);sample(30500,40,1015);report=m.report();assert.equal(report.recent.at(-1)!.motionMeasured,true);assert.equal(report.recentSummary!.residentsMoved,0);});
test('undrawn model positions never count as observed resident walking',()=>{const m=new TownActivityMonitor();let life=createTownLifeOpening(73129);for(let n=0;n<=10;n++){if(n)life=advanceTownLife(life,.5);m.sample({now:n*500,seed:73129,life,matrices:[],expectedDrawn:100,physicsStep:n*30,renderFrames:n*30,renderTime:n*.5,paused:false,mode:'solo',camera:[]});}const s=m.report().recentSummary!;assert.equal(s.residentsWalking,0);assert.equal(s.residentsMoved,0);assert.equal(s.bodyMatricesChanged,0);assert(s.warnings.some(w=>w.includes('missing')));});
