import test from 'node:test';import assert from 'node:assert/strict';import {createTownView}from'../src/town-view.ts';import{createTownLifeOpening,advanceTownLife}from'../src/town-life.ts';import{townLifePoses,townLifeClock}from'../src/town-life-runtime.ts';import{copyTownLifePoses}from'../src/town-life-projection.ts';import{TOWN_CENTER}from'../src/starting-town.ts';
test('coupled town scene displays a completed physics pose frame while preparing the next contact frame',()=>{let life=createTownLifeOpening(73129);const view=createTownView(life.seed);view.couplePhysics();try{view.update(0,TOWN_CENTER,()=>true,true,undefined,true,0,[],false,townLifePoses(life));const first=copyTownLifePoses(view.contactPoses);assert(view.acceptPhysicsPoses(first));for(let i=0;i<60;i++){life=advanceTownLife(life,1/30);view.acceptLife(townLifeClock(life),townLifePoses(life));view.update(townLifeClock(life),TOWN_CENTER,()=>true,true,undefined,false,1/30,[],false,townLifePoses(life));}assert.deepEqual(view.poses.map(p=>[p.x,p.z]),first.map(p=>[p.x,p.z]));assert(view.contactPoses.some((p,i)=>Math.hypot(p.x-first[i]!.x,p.z-first[i]!.z)>.5));const candidate=copyTownLifePoses(view.contactPoses);assert(view.acceptPhysicsPoses(candidate));view.update(townLifeClock(life),TOWN_CENTER,()=>true,true,undefined,false,0,[],false,townLifePoses(life));assert.deepEqual(view.poses.map(p=>[p.x,p.z]),candidate.map(p=>[p.x,p.z]));for(const m of view.matrixEvidence())assert(Math.hypot(m.x-candidate[m.index]!.x,m.z-candidate[m.index]!.z)<.00003);assert.equal(view.stats.physicsPresentationReady,true);}finally{view.dispose();}});
test('physics-presentation acknowledgement is copied validated and reset without mutating life state',()=>{const life=createTownLifeOpening(73129),bytes=JSON.stringify(life),v=createTownView(life.seed);v.couplePhysics();try{const p=copyTownLifePoses(townLifePoses(life)!);assert(v.acceptPhysicsPoses(p));p[0]!.x+=20;v.update(0,TOWN_CENTER,()=>true,true,undefined,true,0,[],false,townLifePoses(life));assert.equal(v.poses[0]!.x,life.residents[0]!.x);assert.equal(v.acceptPhysicsPoses([]),false);assert.equal(v.acceptPhysicsPoses([{x:Infinity}]),false);v.clearPhysicsPoses();assert.equal(v.stats.physicsPresentationReady,false);assert.equal(v.contactPoses.length,0);assert.equal(JSON.stringify(life),bytes);}finally{v.dispose();}});
test('actual worker acknowledges town contact frames outside its near-collision box while town remains visible',{timeout:15_000},async t=>{
 const {townLifePhysics,terrainCell}=await import('./helpers/town-life-physics.ts');
 let life=createTownLifeOpening(73129);const observer={x:TOWN_CENTER.x+61,z:TOWN_CENTER.z},cx=Math.floor(observer.x/64),cz=Math.floor(observer.z/64),cells=[];for(let z=cz-1;z<=cz+1;z++)for(let x=cx-1;x<=cx+1;x++)cells.push(terrainCell(x,z,()=>6));
 const worker=await townLifePhysics(t,{x:observer.x,z:observer.z,y:6,town:{seed:life.seed,time:0,selfId:'viewer',actors:[{id:'viewer',...observer,feetY:6}],lifePoses:townLifePoses(life)},initialCells:cells});const view=createTownView(life.seed);view.couplePhysics();try{
  const first=(worker.latest as any).town.contactPoses;assert(first);view.acceptPhysicsPoses(first);view.update(0,observer,()=>true,true,undefined,true,0,[],false,townLifePoses(life));assert(view.root.visible);assert(view.stats.visible>0);const roots=view.poses.map(p=>({x:p.x,z:p.z}));
  life=advanceTownLife(life,2);worker.input({townLifePoses:townLifePoses(life),townTime:2});await worker.tick();const accepted=(worker.latest as any).town.contactPoses;assert(accepted,'a far observer still receives an explicit current scene frame');assert.deepEqual(accepted,copyTownLifePoses(townLifePoses(life)!));view.acceptPhysicsPoses(accepted);view.update(2,observer,()=>true,true,undefined,false,.5,[],false,townLifePoses(life));assert(view.poses.some((p,i)=>Math.hypot(p.x-roots[i]!.x,p.z-roots[i]!.z)>1));
 }finally{view.dispose();}
});
