import test from 'node:test';
import assert from 'node:assert/strict';
import {townLifePhaseOffset,createTownLifeOpening,createTownLife,advanceTownLife,validTownLife,immutableTownLife,townLifeFacilities,townLifePose,townLifeSummary,createTownLifeScenario,TOWN_LIFE_DEFAULTS,TOWN_LIFE_NEEDS,TOWN_LIFE_COUNTER_LIMIT,validTownLifeCommand,validTownLifeTuning,applyTownLifeCommand,townLifeCommandPosition,townLifePlayerCost,type TownLifeState,type TownLifeCommand,type TownLifeTuning} from '../src/town-life.ts';
import {townResidents} from '../src/town-residents.ts';
import {townPathClear} from '../src/town-crowd.ts';
import {startingTown} from '../src/starting-town.ts';
const clone=<T>(v:T):T=>structuredClone(v);
function run(s:TownLifeState,seconds:number,t:TownLifeTuning=TOWN_LIFE_DEFAULTS){while(seconds>0){const dt=Math.min(60,seconds);s=advanceTownLife(s,dt,t);seconds-=dt;}return s;}
function contribution(s:TownLifeState,kind:TownLifeCommand['kind'],targetId:string,inventory={scrap:100,core:0,water:100}){const command={kind,targetId,expectedRevision:s.revision},p=townLifeCommandPosition(s,command)!;return applyTownLifeCommand(s,{seed:s.seed,zone:'valley',player:{...p,hp:100},inventory},command);}
function ledger(s:TownLifeState){for(const k of ['pantry','water','materials','harvest']as const)assert.ok(Math.abs(s.ledger.initial[k]+s.ledger.produced[k]+s.ledger.donated[k]-s.ledger.consumed[k]-s.ledger.overflow[k]-s.resources[k])<1e-4,`${k} balance`);for(const k of ['field','aquifer','salvage']as const)assert.ok(Math.abs(s.sourceLedger.initial[k]+s.sourceLedger.recharged[k]-s.sourceLedger.extracted[k]-s.sourceLedger.overflow[k]-s.sources[k])<1e-4,`${k} source balance`);}

test('100 stable identities, 40 household stations and bounded immutable state',()=>{for(const seed of [0,7,0xffffffff]){const s=createTownLife(seed);assert.ok(validTownLife(s,seed));assert.deepEqual(s.residents.map(r=>r.id),townResidents(seed).map(r=>r.id));assert.equal(new Set(s.residents.map(r=>r.householdId)).size,40);assert.equal(townLifeFacilities(seed).length,48);assert.equal(townLifeFacilities(seed),townLifeFacilities(seed));assert.ok(Object.isFrozen(s.residents[0]!.needs));assert.equal(s.residents.length,100);ledger(s);}});

test('fixed step segmentation and save/resume are identical; hot remainders share immutable arrays',()=>{const base=createTownLife(42);const small=advanceTownLife(base,1/60);assert.equal(small.residents,base.residents);let frame=base;for(let i=0;i<120;i++)frame=advanceTownLife(frame,1/60);assert.deepEqual(frame,advanceTownLife(base,2));let quarter=base;for(let i=0;i<120;i++)quarter=advanceTownLife(quarter,.25);const whole=advanceTownLife(base,30);assert.deepEqual(quarter,whole);assert.deepEqual(run(immutableTownLife(JSON.parse(JSON.stringify(whole)),42),90),run(base,120));assert.deepEqual(base,createTownLife(42));});

test('mutable external states cannot alias immutable advance outputs, even shallow-frozen roots',()=>{const external=clone(createTownLife(4));Object.freeze(external);const next=advanceTownLife(external,1/60);external.residents[0]!.needs.energy=0;assert.notEqual(next.residents[0]!.needs.energy,0);assert.ok(Object.isFrozen(next.residents[0]!.needs));});

test('strict inert validators reject unknown keys, unsafe numbers, accessors and malformed identities',()=>{const base=createTownLife(12);const bads:unknown[]=[];const edit=(f:(s:any)=>void)=>{const s=clone(base);f(s);bads.push(s);};edit(s=>s.extra=1);edit(s=>s.tick=NaN);edit(s=>s.accumulator=-1);edit(s=>s.residents.reverse());edit(s=>s.residents[0].needs.energy=101);edit(s=>s.residents[0].traits.energy=1);edit(s=>s.residents[0].x=Infinity);edit(s=>s.residents[0].relationships.push({residentId:s.residents[0].id,affinity:1,shared:0}));edit(s=>s.facilities[0].occupants.push(0));edit(s=>s.residents[0].path=[{x:0,z:0}]);edit(s=>s.resources.water++);edit(s=>s.sources.field++);edit(s=>s.events=Array.from({length:33},()=>({tick:0,residentId:null,kind:'aid',text:'x'})));edit(s=>Object.defineProperty(s.residents[0],'reason',{get(){throw Error('must not execute');}}));edit(s=>s.residents[Symbol('extra')]=1);edit(s=>delete s.residents[3]);edit(s=>Object.setPrototypeOf(s.residents[0],{extra:1}));for(const bad of bads)assert.equal(validTownLife(bad,12),false);assert.equal(validTownLife(base,13),false);assert.throws(()=>immutableTownLife(bads[0],12));for(const dt of [-1,NaN,Infinity,60.01])assert.throws(()=>advanceTownLife(base,dt));assert.equal(validTownLifeCommand({kind:'donate-water',targetId:'well',expectedRevision:0,position:{x:0,z:0}}),false);assert.equal(validTownLifeTuning({...TOWN_LIFE_DEFAULTS,needRate:NaN}),false);});

test('real action times, occupied slots and safe road motion persist without replay',()=>{let s=createTownLife(19);let moving=0,occupied=0;const plan=startingTown(19);for(let tick=0;tick<500;tick++){const old=s;s=advanceTownLife(s,.5);for(let i=0;i<100;i++){const r=s.residents[i]!,p=townLifePose(s,i),before=old.residents[i]!;assert.equal(p.x,r.x);assert.equal(p.z,r.z);assert.ok(Math.hypot(r.x-before.x,r.z-before.z)<=1.800001);assert.ok(townPathClear(plan,before,r,.34));if(r.status==='traveling')moving++;if(r.status==='acting'){occupied++;assert.ok(r.remaining>0);}}if(tick%50===0)assert.ok(validTownLife(s,19));}assert.ok(moving>1000);assert.ok(occupied>1000);assert.ok(s.residents.every(r=>r.completed>0));});

test('60 town days stay bounded, supplied and productive without physiological starvation or deadlock',(context)=>{let s=createTownLife(7),minPhys=100,peakUnmet=0,maxSerializedBytes=0;const minStocks={pantry:Infinity,water:Infinity,materials:Infinity,harvest:Infinity},maxStocks={pantry:0,water:0,materials:0,harvest:0};for(let day=0;day<60;day++){for(let sample=0;sample<48;sample++){s=run(s,10);for(const r of s.residents){minPhys=Math.min(minPhys,r.needs.nourishment,r.needs.energy,r.needs.hygiene);peakUnmet=Math.max(peakUnmet,r.unmetSeconds);}maxSerializedBytes=Math.max(maxSerializedBytes,new TextEncoder().encode(JSON.stringify(s)).length);for(const k of ['pantry','water','materials','harvest'] as const){minStocks[k]=Math.min(minStocks[k],s.resources[k]);maxStocks[k]=Math.max(maxStocks[k],s.resources[k]);}}assert.ok(validTownLife(s,7),`day ${day}`);ledger(s);assert.ok(s.resources.water>0);assert.ok(s.resources.pantry>0);}assert.ok(minPhys>10,`min physiological ${minPhys}`);assert.ok(s.residents.every(r=>r.completed>300));assert.ok(s.residents.every(r=>r.desire.completed>0));assert.ok(s.residents.every(r=>r.relationships.length>0));assert.ok(s.residents.every(r=>r.unmetSeconds<60));assert.ok(JSON.stringify(s).length<170_000);assert.ok(s.events.length<=32);assert.ok(peakUnmet<1500);context.diagnostic(JSON.stringify({seed:7,townDays:60,samplingSeconds:10,minPhys,peakUnmet,minCompletedActions:Math.min(...s.residents.map(r=>r.completed)),minCompletedDesires:Math.min(...s.residents.map(r=>r.desire.completed)),finalStocks:s.resources,minStocks,maxStocks,maxSerializedBytes,finalMaxUnmet:Math.max(...s.residents.map(r=>r.unmetSeconds))}));});

test('lean stores and simultaneous critical needs recover through real prerequisite production',()=>{let s=clone(createTownLifeScenario(5,'lean-stores'));s.resources={pantry:0,water:0,materials:0,harvest:0};s.ledger.initial={...s.resources};for(const r of s.residents){r.needs.nourishment=5;r.needs.energy=8;r.needs.hygiene=8;}assert.ok(validTownLife(s,5));s=run(s,1440);assert.ok(validTownLife(s,5));ledger(s);assert.ok(s.resources.pantry>0);assert.ok(s.resources.water>0);assert.ok(s.ledger.produced.harvest>0&&s.ledger.produced.pantry>0&&s.ledger.produced.water>0);assert.ok(s.residents.every(r=>r.completed>0));assert.ok(s.residents.filter(r=>r.needs.nourishment>25&&r.needs.energy>25).length>=90);});

test('unavailable facilities release reservations and occupied actions, then recover',()=>{let s=run(createTownLife(11),160),candidate=s.facilities.slice(40).find(f=>f.reservations.length+f.occupants.length>0)!;assert.ok(candidate);const before=[...candidate.occupants,...candidate.reservations];const m=clone(s),out=m.facilities.find(f=>f.id===candidate.id)!;out.closedFor=90;out.condition=0;s=advanceTownLife(m,.5);assert.ok(before.every(i=>s.residents[i]!.facilityId!==candidate.id));assert.ok(validTownLife(s,11));s=run(s,960);assert.ok(validTownLife(s,11));assert.ok(s.facilities.find(f=>f.id===candidate.id)!.condition>=15);assert.ok(s.residents.every(r=>r.completed>5));});

test('FIFO queue fairness and lease expiry give every waiting resident another chance',()=>{let s=createTownLife(9);s=run(s,960,{...TOWN_LIFE_DEFAULTS,actionSpeed:.5,walkSpeed:.5});assert.ok(validTownLife(s,9));assert.ok(s.residents.every(r=>r.completed>=4));assert.ok(s.residents.every(r=>r.waited<90));assert.ok(s.facilities.every(f=>f.queue.length<=100));const initial=run(createTownLife(9),1);const m=clone(initial),r=m.residents.find(r=>r.status==='traveling')!;r.lease=.1;const interrupted=r.interruptions;s=advanceTownLife(m,.5);assert.ok(s.residents[r.index]!.interruptions>interrupted);assert.ok(validTownLife(s,9));});

test('finite interventions enforce targets, physical range, revision, costs, cooldowns and ledger consistency',()=>{const base=createTownLife(8),donation=contribution(base,'donate-water','well')!;assert.ok(donation);assert.equal(donation.inventory.water,99);assert.equal(donation.life.resources.water,base.resources.water+12);assert.equal(donation.life.revision,1);assert.deepEqual(townLifePlayerCost(donation.life),{scrap:0,core:0,water:1});assert.equal(contribution(donation.life,'donate-water','well'),null);assert.equal(contribution(base,'donate-water','square'),null);assert.equal(contribution(base,'donate-water','well',{scrap:0,core:0,water:0}),null);const cmd={kind:'donate-water' as const,targetId:'well',expectedRevision:0},point=townLifeCommandPosition(base,cmd)!;assert.equal(applyTownLifeCommand(base,{seed:8,zone:'valley',player:{x:point.x+4,z:point.z,hp:100},inventory:{scrap:2,core:0,water:2}},cmd),null);assert.equal(applyTownLifeCommand(donation.life,{seed:8,zone:'valley',player:{...point,hp:100},inventory:donation.inventory},cmd),null);const later=run(donation.life,11);assert.ok(contribution(later,'donate-water','well'));for(const edit of [(s:TownLifeState)=>s.playerSpent.water=0,(s:TownLifeState)=>s.playerSpent.core=1,(s:TownLifeState)=>s.playerSpent.scrap=1,(s:TownLifeState)=>s.contributions['donate-water']=0,(s:TownLifeState)=>s.revision=0,(s:TownLifeState)=>s.ledger.donated.water=0]){const m=clone(donation.life);edit(m);assert.equal(validTownLife(m,8),false);}assert.deepEqual(townLifePlayerCost(undefined),{scrap:0,core:0,water:0});});

test('encouragement and gathering alter real needs, ambitions and choices without repeat-click gains',()=>{const s=createTownLife(17),r=s.residents[0]!,a=contribution(s,'encourage-resident',r.id)!;assert.ok(a.life.residents[0]!.stress<r.stress);assert.ok(a.life.residents[0]!.desire.progress>r.desire.progress);assert.equal(contribution(a.life,'encourage-resident',r.id),null);assert.equal(a.inventory.scrap,100);const g=contribution(s,'host-gathering','square')!;assert.equal(g.inventory.scrap,98);assert.equal(g.inventory.water,99);assert.equal(g.life.gathering,60);assert.equal(contribution(g.life,'host-gathering','square'),null);assert.notDeepEqual(run(g.life,60).residents.map(r=>r.facilityId),run(s,60).residents.map(r=>r.facilityId));});

test('tuning has bounded real consumers and production batch is latched at input consumption',()=>{const s=createTownLife(6),low=run(s,120,{...TOWN_LIFE_DEFAULTS,needRate:.25,actionSpeed:.5,walkSpeed:.5,productionRate:.5,socialWeight:0,desireWeight:0}),high=run(s,120,{needRate:2,actionSpeed:2,walkSpeed:2,productionRate:2,socialWeight:2,desireWeight:2});assert.notDeepEqual(low.residents,high.residents);assert.ok(validTownLife(low,6));assert.ok(validTownLife(high,6));let active=run(s,20),cook=active.residents.find(r=>r.status==='acting'&&r.action==='cook');for(let i=0;!cook&&i<20;i++){active=run(active,5);cook=active.residents.find(r=>r.status==='acting'&&r.action==='cook');}assert.ok(cook);const index=cook.index,oldBatch=cook.batch,m=clone(active);m.residents[index]!.remaining=.1;const expected=m.residents.filter(r=>r.status==='acting'&&r.action==='cook'&&r.remaining<=.5).reduce((n,r)=>n+6*r.batch,0);const next=advanceTownLife(m,.5,{...TOWN_LIFE_DEFAULTS,productionRate:2});assert.equal(next.residents[index]!.completed,m.residents[index]!.completed+1);assert.equal(next.ledger.produced.pantry-m.ledger.produced.pantry,expected);assert.equal(oldBatch,1);assert.ok(validTownLife(next,6));});

test('scenario resets and selected starting needs are explicit, bounded and isolated',()=>{const base=createTownLifeOpening(3);for(const id of ['balanced','lean-stores','service-outage','social-strain','urgent-needs','overwork'])assert.ok(validTownLife(createTownLifeScenario(3,id),3));const needs=Object.fromEntries(TOWN_LIFE_NEEDS.map(k=>[k,35])) as typeof base.residents[0]['needs'];const changed=createTownLifeScenario(3,'balanced',{residentIndex:12,needs});assert.deepEqual(changed.residents[12]!.needs,needs);assert.deepEqual(changed.residents[11]!.needs,base.residents[11]!.needs);assert.throws(()=>createTownLifeScenario(3,'unknown'));assert.throws(()=>createTownLifeScenario(3,'balanced',{residentIndex:100,needs}));assert.throws(()=>createTownLifeScenario(3,'balanced',{residentIndex:12,needs:{...needs,energy:NaN}}));assert.match(townLifeSummary(changed,12).desire,/%/);});

test('counter saturation does not freeze ordinary movement or accounting; command capacity fails closed',()=>{const s=clone(createTownLife(13));s.tick=TOWN_LIFE_COUNTER_LIMIT;s.residents[0]!.completed=TOWN_LIFE_COUNTER_LIMIT;s.residents[0]!.distance=TOWN_LIFE_COUNTER_LIMIT;s.ledger.produced.water=TOWN_LIFE_COUNTER_LIMIT-1;s.ledger.consumed.water=TOWN_LIFE_COUNTER_LIMIT-1;assert.ok(validTownLife(s,13));const next=run(s,90);assert.equal(next.tick,TOWN_LIFE_COUNTER_LIMIT);assert.notEqual(next.cycleTick,s.cycleTick);assert.ok(next.residents[0]!.completed===TOWN_LIFE_COUNTER_LIMIT);assert.ok(validTownLife(next,13));ledger(next);assert.ok(next.ledger.epochs>0);const capped=clone(createTownLife(13));capped.contributions['encourage-resident']=TOWN_LIFE_COUNTER_LIMIT;capped.revision=TOWN_LIFE_COUNTER_LIMIT;assert.ok(validTownLife(capped,13));assert.equal(contribution(capped,'encourage-resident',capped.residents[0]!.id),null);});

test('the same FIFO queue admits its earliest 24 residents, never a younger arrival',()=>{const s=clone(createTownLife(9));for(const r of s.residents){r.status='queued';r.action='leisure';r.facilityId='square';}s.facilities.find(f=>f.id==='square')!.queue=Array.from({length:100},(_,i)=>i);assert.ok(validTownLife(s,9));const next=advanceTownLife(s,.5),square=next.facilities.find(f=>f.id==='square')!;assert.deepEqual(square.reservations,Array.from({length:24},(_,i)=>i));assert.deepEqual(square.queue,Array.from({length:76},(_,i)=>i+24));assert.ok(validTownLife(next,9));});

test('stressed shared encounters produce signed friction and affinity changes actual future choices',()=>{const s=clone(createTownLife(23)),f=townLifeFacilities(23).find(f=>f.id==='square')!;for(const i of [0,1]){const r=s.residents[i]!;Object.assign(r,{status:'acting',action:'socialize',facilityId:'square',slot:i,remaining:.25,committed:0,x:f.x+(i-3.5)*.74,z:f.z,stress:100});r.needs.connection=5;r.relationships=[{residentId:s.residents[1-i]!.id,affinity:-12,shared:0}];}s.facilities.find(f=>f.id==='square')!.occupants=[0,1];assert.ok(validTownLife(s,23));const next=advanceTownLife(s,.5);assert.ok(next.residents[0]!.relationships.find(r=>r.residentId===s.residents[1]!.id)!.affinity<-15);assert.ok(next.residents[0]!.desire.progress>0);assert.ok(validTownLife(next,23));const choices=clone(createTownLife(23)),chooser=choices.residents[0]!;for(const key of TOWN_LIFE_NEEDS)chooser.needs[key]=100;chooser.needs.connection=0;chooser.x=f.x+15;chooser.z=f.z+3;for(const [index,id]of [[1,'garden-east'],[2,'square']] as const){const facility=townLifeFacilities(23).find(f=>f.id===id)!,actor=choices.residents[index]!;Object.assign(actor,{status:'acting',action:'socialize',facilityId:id,slot:0,remaining:20,committed:0,x:facility.x-(id==='square'?3.5:2)*.74,z:facility.z});choices.facilities.find(f=>f.id===id)!.occupants=[index];}chooser.relationships=[{residentId:choices.residents[1]!.id,affinity:100,shared:0}];const negative=clone(choices);negative.residents[0]!.relationships[0]!.affinity=-100;const positiveNext=advanceTownLife(choices,.5),negativeNext=advanceTownLife(negative,.5);assert.equal(positiveNext.residents[0]!.facilityId,'garden-east');assert.equal(negativeNext.residents[0]!.facilityId,'square');});

test('material donations do not create food; repairs reopen real facilities and conserve costs',()=>{const s=createTownLife(31),donated=contribution(s,'donate-supplies','workshop')!;assert.equal(donated.life.resources.pantry,s.resources.pantry);assert.equal(donated.life.resources.materials,s.resources.materials+12);assert.deepEqual(townLifePlayerCost(donated.life),{scrap:2,core:0,water:0});const m=clone(s),f=m.facilities.find(f=>f.id==='cookshop')!;f.condition=5;f.closedFor=100;const repaired=contribution(m,'repair-service','cookshop')!;assert.equal(repaired.life.facilities.find(f=>f.id==='cookshop')!.condition,45);assert.equal(repaired.life.facilities.find(f=>f.id==='cookshop')!.closedFor,0);assert.deepEqual(townLifePlayerCost(repaired.life),{scrap:2,core:0,water:0});assert.ok(validTownLife(repaired.life,31));assert.equal(contribution(repaired.life,'repair-service','cookshop'),null);});

test('trade specialization competes with schedules but critical hunger still interrupts it',()=>{const s=clone(createTownLife(15)),identity=townResidents(15).find(r=>r.role==='cook')!,r=s.residents[identity.index]!,f=townLifeFacilities(15).find(f=>f.id==='cookshop')!;for(const key of TOWN_LIFE_NEEDS)r.needs[key]=100;r.desire.kind='settle-in';r.desire.progress=0;r.x=f.x;r.z=f.z;s.tick=Math.round(((identity.routine[2]!.start+10-townLifePhaseOffset(identity)+480)%480)/.5);s.cycleTick=s.tick%960;const working=advanceTownLife(s,.5,{...TOWN_LIFE_DEFAULTS,desireWeight:0,socialWeight:0});assert.equal(working.residents[identity.index]!.action,'cook');assert.match(working.residents[identity.index]!.reason,/cook/);const hungry=clone(s);hungry.residents[identity.index]!.needs.nourishment=1;const urgent=advanceTownLife(hungry,.5);assert.equal(urgent.residents[identity.index]!.action,'eat');});
