import test from 'node:test';
import assert from 'node:assert/strict';
import {compileRestorationBody,DEFAULT_RESTORATION_RECIPE} from '../src/restoration-body.ts';
import {compileUtilityAbility,createUtilityState,DEFAULT_UTILITY_RECIPE,interruptUtility,parseUtilityRecipe,requestUtility,stepUtility,UTILITY_TICK_SECONDS,UTILITY_TUNING_DESCRIPTORS,validUtilityAbilityPlan,validUtilityRecipeInput,validUtilityState,type UtilityRecipeInput,type UtilityState,type UtilityStepContext} from '../src/utility-ability.ts';
const recipe=(patch:Partial<UtilityRecipeInput>={}):UtilityRecipeInput=>({...DEFAULT_UTILITY_RECIPE,...patch});
const requestContext={energyAvailable:1000,filtrationAvailable:12000,workSpeed:1};
const context:UtilityStepContext={energyAvailable:1000,filtrationAvailable:12000,interrupted:false,occluded:false,overheated:false};
const intent=(intentId=1)=>({intentId,sourceId:'site/source',targetId:'site/target'});
const start=(input=recipe(),workSpeed=1)=>requestUtility(createUtilityState(),input,intent(),{...requestContext,workSpeed}).state;
function run(state:UtilityState,c:UtilityStepContext=context){const outputs=[];for(let ticks=0;state.phase!=='idle'&&ticks<100;ticks++){const r=stepUtility(state,c);assert.ok(validUtilityState(r.state),JSON.stringify(r.state));outputs.push(r);state=r.state;}assert.equal(state.phase,'idle');return {state,outputs};}
test('all finite utility recipe tiers/cadences have canonical serializable plans and strict real costs',()=>{
 assert.equal(UTILITY_TICK_SECONDS,.25);for(const organ of ['pump','filter','vent','beacon'] as const)for(const strength of [1,2,3] as const)for(const tempo of ['careful','steady','brisk'] as const){const input=recipe({organ,strength,tempo}),p=compileUtilityAbility(input);assert.deepEqual(p,compileUtilityAbility(input));assert.deepEqual(p,JSON.parse(JSON.stringify(p)));assert.ok(validUtilityAbilityPlan(p));assert.ok(Object.isFrozen(p.recipe));assert.ok(p.energyCost>0&&Number.isInteger(p.energyCost));assert.ok(p.strengthUnits>0&&Number.isInteger(p.strengthUnits));for(const key of ['prepTicks','activeTicks','recoveryTicks','cooldownTicks'] as const)assert.ok(Number.isInteger(p[key])&&p[key]>0&&p[key]<16);assert.equal(p.delivery,organ==='pump'?'jet':organ==='filter'?'contact':'local-field');assert.equal(p.filtrationCost,organ==='filter'?p.strengthUnits:0);}
 assert.ok(UTILITY_TUNING_DESCRIPTORS.every(d=>d.consumer&&d.unit&&d.effect));
});
test('low/default/high strength and cadence change actual pulse and timing outcomes',()=>{
 for(const organ of ['pump','filter','vent','beacon'] as const){const low=compileUtilityAbility(recipe({organ,strength:1})),high=compileUtilityAbility(recipe({organ,strength:3}));assert.equal(high.strengthUnits,3*low.strengthUnits);assert.equal(high.energyCost,3*low.energyCost);const careful=compileUtilityAbility(recipe({organ,tempo:'careful'})),brisk=compileUtilityAbility(recipe({organ,tempo:'brisk'}));assert.ok(careful.prepTicks>low.prepTicks&&low.prepTicks>brisk.prepTicks);assert.ok(careful.energyCost<low.energyCost&&low.energyCost<brisk.energyCost);}
});
test('phase timeline has exact prep, active, recovery and cooldown with one pulse at active entry',()=>{
 for(const organ of ['pump','filter','vent','beacon'] as const)for(const tempo of ['careful','steady','brisk'] as const)for(const workSpeed of [.8,1,1.2]){const input=recipe({organ,tempo}),p=compileUtilityAbility(input),s=start(input,workSpeed),r=run(s),prep=Math.ceil(p.prepTicks/workSpeed);assert.equal(r.outputs.length,prep+p.activeTicks+p.recoveryTicks+p.cooldownTicks);const pulses=r.outputs.filter(r=>r.pulse);assert.equal(pulses.length,1);assert.equal(pulses[0]!.state.timeTicks,prep);assert.equal(pulses[0]!.state.phase,'active');assert.equal(pulses[0]!.pulse!.consumedEnergy,p.energyCost);assert.deepEqual(pulses[0]!.pulse!.sourceId,'site/source');assert.equal(pulses[0]!.pulse!.targetId,'site/target');assert.equal(r.state.recipe,null);assert.equal(r.state.target,null);assert.equal(r.state.intentId,null);assert.ok(validUtilityState(JSON.parse(JSON.stringify(r.state))));}
});
test('accepted recipe, intent, targets and support work rate remain latched across edits/refits',()=>{
 const input=recipe(),id=intent(),ctx={...requestContext},accepted=requestUtility(createUtilityState(),input,id,ctx);input.organ='beacon';input.strength=3;id.sourceId='changed';id.targetId='changed';ctx.workSpeed=.8;const changedBody=compileRestorationBody({...DEFAULT_RESTORATION_RECIPE,support:'sturdy',organ:'beacon'});assert.equal(changedBody.recipe.organ,'beacon');assert.equal(accepted.state.recipe!.recipe.organ,'pump');assert.equal(accepted.state.recipe!.recipe.strength,1);assert.equal(accepted.state.workSpeed,1);const pulse=run(accepted.state).outputs.find(r=>r.pulse)!.pulse!;assert.equal(pulse.organ,'pump');assert.equal(pulse.effectUnits,1000);assert.equal(pulse.sourceId,'site/source');assert.equal(pulse.targetId,'site/target');assert.throws(()=>{accepted.state.recipe!.recipe.strength=3;});
});
test('monotonic accepted/rejected intent receipts prevent immediate and delayed A/B/A replays',()=>{
 let state=start();const duplicate=requestUtility(state,recipe(),intent(),requestContext);assert.equal(duplicate.state,state);assert.equal(duplicate.events[0]!.type,'rejected');const busy=requestUtility(state,recipe({organ:'beacon'}),intent(2),requestContext);assert.equal(busy.state.castId,1);assert.equal(busy.state.lastIntentId,2);assert.equal(busy.state.intentId,1);assert.ok(validUtilityState(busy.state));state=run(busy.state).state;for(const i of [1,2]){const r=requestUtility(state,recipe(),intent(i),requestContext);assert.equal(r.state,state);assert.equal(r.pulse,null);}const fresh=requestUtility(state,recipe(),intent(3),requestContext);assert.equal(fresh.state.castId,2);assert.equal(fresh.state.intentId,3);assert.equal(run(fresh.state).outputs.filter(r=>r.pulse).length,1);
});
test('energy and cartridge guards reject safely, recheck at active entry, cap real filter capture',()=>{
 assert.equal(requestUtility(createUtilityState(),recipe(),intent(),{...requestContext,energyAvailable:0}).state.receipt!.reason,'energy');assert.equal(requestUtility(createUtilityState(),recipe({organ:'filter'}),intent(),{...requestContext,filtrationAvailable:0}).state.receipt!.reason,'filtration');
 const depleted=run(start(),{...context,energyAvailable:0});assert.equal(depleted.outputs.filter(r=>r.pulse).length,0);assert.ok(depleted.outputs.flatMap(r=>r.events).some(e=>e.type==='interrupted'&&e.reason==='depleted'));
 const filter=run(start(recipe({organ:'filter',strength:3})),{...context,filtrationAvailable:17}),pulse=filter.outputs.find(r=>r.pulse)!.pulse!;assert.equal(pulse.effectUnits,17);assert.equal(pulse.consumedFiltration,17);assert.equal(pulse.consumedEnergy,15);
});
test('finite ledger integration consumes once and never restores energy/filter on recompile',()=>{
 let energy=100,filter=1200,waste=0,state=createUtilityState();for(let i=1;i<=4;i++){state=requestUtility(state,recipe({organ:'filter'}),intent(i),{energyAvailable:energy,filtrationAvailable:filter,workSpeed:1}).state;for(let t=0;state.phase!=='idle'&&t<80;t++){const r=stepUtility(state,{...context,energyAvailable:energy,filtrationAvailable:filter});state=r.state;if(r.pulse){const actual=Math.min(150,r.pulse.effectUnits);energy-=r.pulse.consumedEnergy;filter-=actual;waste+=actual;}}compileUtilityAbility(recipe({organ:'filter',strength:3}));compileRestorationBody({...DEFAULT_RESTORATION_RECIPE,organ:'filter'});assert.equal(filter+waste,1200);}assert.equal(energy,80);assert.equal(waste,600);assert.equal(filter,600);
});
test('interruption before or after effect preserves cooldown, cannot replay or refund',()=>{
 for(const reason of ['stop','refit','blocked','heat','depleted','invalid'] as const){let s=start(),r=interruptUtility(s,reason);assert.equal(r.state.phase,'cooldown');assert.equal(r.state.remainingTicks,s.recipe!.cooldownTicks);assert.equal(r.pulse,null);assert.ok(validUtilityState(r.state));assert.equal(run(r.state).outputs.filter(r=>r.pulse).length,0);for(let i=0;i<4;i++)s=stepUtility(s,context).state;assert.equal(s.phase,'active');r=interruptUtility(s,reason);assert.equal(r.state.pulsed,true);assert.equal(run(r.state).outputs.filter(r=>r.pulse).length,0);}
 let s=interruptUtility(start(),'stop').state;const n=s.remainingTicks;s=stepUtility(s,{...context,interrupted:true}).state;assert.equal(s.remainingTicks,n-1);assert.equal(interruptUtility(s,'refit').state,s);
});
test('actual obstructions and unsafe heat interrupt pending effects, invalid contexts never advance',()=>{
 for(const flag of ['interrupted','occluded','overheated'] as const){const s=start(),r=stepUtility(s,{...context,[flag]:true});assert.equal(r.state.phase,'cooldown');assert.equal(r.pulse,null);assert.equal(r.state.timeTicks,1);}const s=start();for(const c of [{...context,energyAvailable:NaN},{...context,filtrationAvailable:-1},{...context,interrupted:1},{...context,script:true}])assert.equal(stepUtility(s,c as UtilityStepContext).state,s);
});
test('strict utility recipe input blocks executable or unsafe data and bounded parser input',()=>{
 let calls=0;const getter={...recipe()};Object.defineProperty(getter,'organ',{get(){calls++;return 'pump';}});for(const value of [null,[],{},getter,{...recipe(),version:2},{...recipe(),strength:0},{...recipe(),strength:NaN},{...recipe(),strength:4},{...recipe(),strength:1.5},{...recipe(),tempo:'instant'},{...recipe(),organ:'weapon'},{...recipe(),extra:0},{...recipe(),[Symbol()]:1},Object.assign(Object.create({inherited:true}),recipe())]){assert.equal(validUtilityRecipeInput(value),false);assert.throws(()=>compileUtilityAbility(value as UtilityRecipeInput));}assert.equal(calls,0);assert.deepEqual(parseUtilityRecipe(JSON.stringify(recipe())),recipe());assert.throws(()=>parseUtilityRecipe(' '.repeat(513)));assert.throws(()=>parseUtilityRecipe('{'));
});
test('strict save state rejects forged plans, unknown fields, impossible clock bounds and nested accessors',()=>{
 const s=start(),invalid:unknown[]=[{...s,version:2},{...s,extra:1},{...s,remainingTicks:0},{...s,remainingTicks:99},{...s,prepTicks:0},{...s,pulsed:true},{...s,workSpeed:NaN},{...s,lastIntentId:0},{...s,recipe:{...s.recipe,energyCost:0}},{...s,target:{sourceId:'../unsafe',targetId:'target'}},{...s,receipt:{...s.receipt,intentId:0}},Object.assign(Object.create({inherited:true}),s)];let invoked=0;const evil={toString(){invoked++;return 'prep';}};invalid.push({...s,phase:evil});const nested={...s.recipe!};Object.defineProperty(nested,'energyCost',{get(){invoked++;return 0;}});invalid.push({...s,recipe:nested});for(const value of invalid)assert.equal(validUtilityState(value),false);assert.equal(invoked,0);assert.ok(validUtilityState(JSON.parse(JSON.stringify(s))));
 const initial=createUtilityState();assert.ok(validUtilityState(initial));assert.equal(validUtilityState({...initial,recipe:compileUtilityAbility(recipe())}),false);assert.equal(validUtilityState({...initial,castId:1}),false);
});
