import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import * as THREE from 'three';
import {CellStreamer,ownerOf} from '../src/streaming.ts';import {wildernessFeatures,wildernessFeatureRemaining,wildernessFeatureDepleted} from '../src/wilderness.ts';import {createWildernessView} from '../src/wilderness-view.ts';import {createState} from '../src/world.ts';
const main=fs.readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');
function harness(){
 const state=createState(1),feature=wildernessFeatures(state).find(f=>f.removable)!;state.player.x=feature.x;state.player.z=feature.z;
 const source=main.slice(main.indexOf('let streamer=new CellStreamer'),main.indexOf('let resolvePhysics:'));
 const receipt=main.slice(main.indexOf('worker.onmessage=(e)=>'),main.indexOf(" if(m.type==='online-motion-ack')"))+'};';
 const prefix=`const startup={playing:true,failed:false};let zoneEpoch=0,physicsReady=false,labActive=false;const streamObjects=wildernessCatalog.map(f=>({id:f.id,kind:'rock',x:f.x,y:f.y,z:f.z,label:'stone'})),cellPositions=[...wildernessCatalog],valleyObjects=[],objects=[],cellFactories=new Map(),cellObstacles=new Map(),visuals=new Map(),creatureVisuals=new Map(),valleyRoot=new THREE.Group(),messages=[],worker={};const wildernessView=createWildernessView();function sendPhysics(m){messages.push({...m,epoch:zoneEpoch});}`;
 const suffix=`const disposed=[];let nextRoot=0;return {disposed,addDisposable(key){cellFactories.set(key,[()=>{const root=new THREE.Group(),id=++nextRoot;root.userData.disposeOwned=()=>disposed.push(id);return root;}]);},initial(){return initialCellPacket();},ready(){physicsReady=true;},accept(m){worker.onmessage({data:m});},groups:residentGroups,pending:pendingCells,solids:cellObstacles,messages,root:valleyRoot,harvest(id){state={...state,wilderness:{version:1,generation:1,seed:1,harvested:[id],wood:0,stone:1}};streamWorld();},visit(x,z){state={...state,player:{...state.player,x,z}};streamWorld();},replace(){for(const key of new Set([...residentGroups.keys(),...pendingCells.keys()]))disposeCell(key);streamer=new CellStreamer(streamObjects,cellPositions);zoneEpoch++;return initialCellPacket();}};`;
 const js=stripTypeScriptTypes('function createHarness(){'+prefix+source+receipt+suffix+'}',{mode:'transform'})+';return createHarness();';
 const api=new Function('THREE','CellStreamer','ownerOf','state','wildernessCatalog','wildernessFeatureRemaining','wildernessFeatureDepleted','createWildernessView',js)(THREE,CellStreamer,ownerOf,state,[feature],wildernessFeatureRemaining,wildernessFeatureDepleted,createWildernessView);return {api,feature,key:ownerOf(feature)};
}
test('actual main cell projection waits for exact collision receipts and atomically removes gathered rock',()=>{
 const {api,feature,key}=harness(),packet=api.initial(),cell=packet.initialCells[0];assert.equal(cell.key,key);assert(cell.obstacles.some((o:any)=>o.featureId===feature.id));assert.equal(api.groups.size,0,'No rendered obstacle is admitted before its worker collision');api.ready();api.accept({type:'cell-ack',epoch:0,key,revision:cell.revision,loaded:true});const original=api.groups.get(key);assert(original.getObjectByName(feature.id));
 api.harvest(feature.id);const remove=api.messages.at(-1);assert.equal(remove.type,'cell-load');assert.equal(remove.obstacles.length,0);assert.equal(api.groups.get(key),original,'Old physical projection remains until replacement receipt');assert(api.solids.get(key).length);
 api.accept({type:'cell-ack',epoch:0,key,revision:cell.revision,loaded:true});assert.equal(api.groups.get(key),original,'Delayed old acknowledgment cannot replace pending newer state');api.accept({type:'cell-ack',epoch:0,key,revision:remove.revision,loaded:true});assert.equal(api.groups.get(key).getObjectByName(feature.id),undefined);assert.equal(api.solids.get(key).length,0);assert.equal(original.parent,null);
});
test('actual main eviction/reload and new zone epoch cannot resurrect depleted stones from stale acknowledgments',()=>{
 const {api,feature,key}=harness(),first=api.initial().initialCells[0];api.ready();api.accept({type:'cell-ack',epoch:0,key,revision:first.revision,loaded:true});api.harvest(feature.id);const removal=api.messages.at(-1);api.accept({type:'cell-ack',epoch:0,key,revision:removal.revision,loaded:true});api.visit(1000,1000);assert.equal(api.groups.size,0);api.accept({type:'cell-ack',epoch:0,key,revision:first.revision,loaded:true});assert.equal(api.groups.size,0);api.visit(feature.x,feature.z);const reload=api.messages.at(-1);assert.equal(reload.obstacles.length,0);
 const next=api.replace().initialCells[0];api.accept({type:'cell-ack',epoch:0,key,revision:next.revision,loaded:true});assert.equal(api.groups.size,0,'Old epoch rejected even if revision number coincides');api.accept({type:'cell-ack',epoch:1,key,revision:next.revision,loaded:true});assert.equal(api.groups.get(key).getObjectByName(feature.id),undefined);assert.equal(api.pending.size,0);
});

test('actual cell replacement disposes old per-instance resources while preserving the new pending root',()=>{const {api,key,feature}=harness();api.addDisposable(key);const first=api.initial().initialCells[0];api.ready();api.accept({type:'cell-ack',epoch:0,key,revision:first.revision,loaded:true});api.harvest(feature.id);assert.deepEqual(api.disposed,[]);const pending=api.messages.at(-1);api.accept({type:'cell-ack',epoch:0,key,revision:pending.revision,loaded:true});assert.deepEqual(api.disposed,[1]);api.visit(1000,1000);assert.deepEqual(api.disposed,[1,2]);});
