import test from 'node:test';
import assert from 'node:assert/strict';
import {mountWorkshopConstruction} from '../src/workshop-construction-ui.ts';
import {mountWorkshopConstructionLab} from '../src/workshop-construction-lab.ts';
import {createTownLife} from '../src/town-life.ts';
import {WORKSHOP_BOARD,applyWorkshopConstruction,type WorkshopConstructionState} from '../src/workshop-construction.ts';
class Element {value='';textContent='';disabled=false;hidden=false;dataset:Record<string,string>={};files:any[]=[];nodes=new Map<string,Element>();onclick?:()=>void;oninput?:()=>void;onchange?:()=>Promise<void>;html='';set innerHTML(html:string){this.html=html;this.nodes.clear();for(const m of html.matchAll(/\bid="([^"]+)"/g))this.nodes.set('#'+m[1],new Element());}get innerHTML(){return this.html;}querySelector(s:string){return this.nodes.get(s)??null;}getContext(){return null;}}
test('workshop board shows honest funded stage, achieved labor, remaining work and precise unavailable repair reason',()=>{
 const panel=new Element();let state={seed:42,zone:'valley',player:{...WORKSHOP_BOARD,hp:50},townLife:createTownLife(42),workshopConstruction:undefined as WorkshopConstructionState|undefined};const ui=mountWorkshopConstruction(panel as any,{getState:()=>state,onClose(){},send:c=>{const result=applyWorkshopConstruction(state.workshopConstruction,state.townLife,state,c);if(result)state={...state,townLife:result.life,workshopConstruction:result.construction};}}),q=(id:string)=>panel.querySelector('#wc-'+id)!;
 assert.ok(q('stage'),'Board must expose explicit construction stage');assert.match(q('stage').textContent,/unfunded/i);q('build').onclick!();assert.equal(state.workshopConstruction?.work,0);assert.match(q('stage').textContent,/funded/i);assert.match(q('current').textContent,/remaining/i);assert.match(q('stage-detail').textContent,/protective|cover/i);assert.match(q('worker-detail').textContent,/Second Life Salvage/);assert.match(q('repair-reason').textContent,/finish|complete/i);assert(q('repair').disabled);assert(q('build').disabled);assert.match(panel.innerHTML,/Close it to let residents/);ui.dispose();
});
test('rejected visit keeps workshop board controls and Close alive until navigation actually leaves',()=>{
 const panel=new Element(),state={seed:42,zone:'cave',player:{...WORKSHOP_BOARD,hp:50},townLife:createTownLife(42)};let visits=0,closed=0;const ui=mountWorkshopConstruction(panel as any,{getState:()=>state,onClose:()=>closed++,visit:()=>visits++,send(){}}),q=(id:string)=>panel.querySelector('#wc-'+id)!;q('visit').onclick!();assert.equal(visits,1);q('width').value='8.4';q('apply').onclick!();assert.equal(ui.getApplied().width,8.4);q('close').onclick!();assert.equal(closed,1);ui.dispose();
});
test('construction lab records only earned stage transitions and repeats finite paid progress after reset',()=>{
 const panel=new Element(),lab=mountWorkshopConstructionLab(panel as any,{seed:42,source:'staging-test',onClose(){}}),q=(id:string)=>panel.querySelector('#wcl-'+id)!,board=(id:string)=>q('board').querySelector('#wc-'+id)!;
 assert.ok(q('stage'),'Lab must expose stage inspection');board('build').onclick!();const paid=lab.getState().workshopConstruction!;assert.ok(paid);assert.equal((lab.report() as any).stage.id,'funded');assert.equal(paid.work,0);
 for(let i=0;i<20&&lab.getState().workshopConstruction?.status!=='complete';i++)lab.step(60);
 const report=lab.report() as any;assert.equal(report.construction.status,'complete');assert.equal(report.stage.id,'complete');assert.deepEqual(report.stageHistory.map((s:any)=>s.id),['unfunded','funded','frame','panels','finishing','complete']);assert.ok(report.stageHistory.slice(2).every((s:any)=>s.work>0));assert.equal(report.stageHistory.at(-1).work,report.construction.workRequired);assert.equal(report.visualReview,'not-reviewed');assert.match(q('stage').textContent,/complete/i);assert.equal(report.actions.filter((a:any)=>a.kind==='advance').reduce((n:number,a:any)=>n+a.achievedWork,0)>=report.construction.workRequired,true);
 q('reset').onclick!();assert.equal(lab.getState().workshopConstruction,undefined);assert.equal((lab.report() as any).stage.id,'unfunded');assert.deepEqual((lab.report() as any).stageHistory.map((s:any)=>s.id),['unfunded']);board('build').onclick!();assert.equal(lab.getState().workshopConstruction!.materialsPaid,paid.materialsPaid);assert.equal(lab.getState().workshopConstruction!.work,0);lab.dispose();
});
