import test from 'node:test';import assert from 'node:assert/strict';
import {mountWorkshopConstruction} from '../src/workshop-construction-ui.ts';
import {createTownLife} from '../src/town-life.ts';
import {WORKSHOP_BOARD} from '../src/workshop-construction.ts';
import {DEFAULT_WORKSHOP_DRAFT,exportWorkshopPreset} from '../src/workshop-authoring.ts';
class Element {value='';textContent='';disabled=false;files:any[]=[];nodes=new Map<string,Element>();onclick?:()=>void;oninput?:()=>void;onchange?:()=>Promise<void>;set innerHTML(html:string){this.nodes.clear();for(const m of html.matchAll(/\bid="([^"]+)"/g))this.nodes.set('#'+m[1],new Element());}querySelector(s:string){return this.nodes.get(s)??null;}getContext(){return null;}}
function harness(){const panel=new Element(),sent:any[]=[],state={seed:42,zone:'valley',player:{...WORKSHOP_BOARD,hp:50},townLife:createTownLife(42)};const ui=mountWorkshopConstruction(panel as any,{getState:()=>state,send:c=>sent.push(c),onClose:()=>{}});return {ui,sent,panel,get:(id:string)=>panel.querySelector('#wc-'+id)!};}
test('construction UI stages dimensions and sends only explicit paid build from applied plan',()=>{const h=harness();h.get('width').value='9.6';h.get('width').oninput!();assert.equal(h.ui.getApplied().width,9);assert.equal(h.sent.length,0);h.get('apply').onclick!();assert.equal(h.ui.getApplied().width,9.6);h.get('build').onclick!();assert.equal(h.sent.length,1);assert.equal(h.sent[0].parameters.width,9.6);assert.equal(h.sent[0].expectedRevision,0);h.ui.dispose();h.get('build').onclick!();assert.equal(h.sent.length,1);});
test('construction imports exact bounded recipes and ignores stale file reads after edit/close',async()=>{const h=harness();let finish!:(s:string)=>void;h.get('file').files=[{size:100,text:()=>new Promise(r=>finish=r)}];const pending=h.get('file').onchange!();h.get('width').value='8.4';h.get('width').oninput!();finish(exportWorkshopPreset(DEFAULT_WORKSHOP_DRAFT));await pending;assert.equal(h.get('width').value,'8.4');h.get('width').value='100';h.get('apply').onclick!();assert.equal(h.ui.getApplied().width,9);assert.match(h.get('status').textContent,/Width/);h.get('text').value=exportWorkshopPreset({...DEFAULT_WORKSHOP_DRAFT,rearRooms:3});h.get('import').onclick!();assert.equal(h.ui.getApplied().rearRooms,2);h.get('apply').onclick!();assert.equal(h.ui.getApplied().rearRooms,3);h.ui.dispose();});
