import test from 'node:test';import assert from 'node:assert/strict';
import {mountWorkshopAuthoring} from '../src/workshop-authoring-ui.ts';
import {compileWorkshopDraft,DEFAULT_WORKSHOP_DRAFT,exportWorkshopPreset,type WorkshopDraft,type WorkshopAuthoringResult} from '../src/workshop-authoring.ts';
class Element {value='';textContent='';files:any[]=[];nodes=new Map<string,Element>();html='';onclick?:()=>void;oninput?:()=>void;onchange?:()=>Promise<void>;onsubmit?:(e:any)=>void;
 set innerHTML(html:string){this.html=html;this.nodes.clear();for(const m of html.matchAll(/\bid="([^"]+)"/g))this.nodes.set('#'+m[1],new Element());}querySelector(s:string){return this.nodes.get(s)??null;}getContext(){return new Proxy({},{get:()=>()=>{},set:()=>true});}}
const settle=async()=>{await Promise.resolve();await Promise.resolve();};
function harness(t:any){const panel=new Element(),jobs:{draft:WorkshopDraft;signal:AbortSignal;resolve:(r:WorkshopAuthoringResult)=>void}[]=[],downloads:{name:string;text:string}[]=[];let closed=0;
 const ui=mountWorkshopAuthoring(panel as any,{seed:42,onClose:()=>closed++,download:(name,text)=>downloads.push({name,text}),generate:(draft,signal)=>new Promise(resolve=>jobs.push({draft,signal,resolve}))});const get=(id:string)=>panel.querySelector('#'+id)!;t.after(()=>ui.dispose());
 return {ui,panel,jobs,downloads,get,closed:()=>closed,flush(index=jobs.length-1){jobs[index]!.resolve(compileWorkshopDraft(jobs[index]!.draft));},submit(){get('wa-form').onsubmit!({preventDefault(){}});}};}
test('explicit Apply stages real dimensions; discard/default/reset preserve exact applied boundary',async t=>{const h=harness(t);h.flush();await settle();assert.equal(h.ui.getApplied()!.parameters.seed,42);h.get('wa-width').value='9.6';h.get('wa-width').oninput!();assert.equal(h.ui.getApplied()!.parameters.width,9);assert.equal(h.jobs.length,1);h.submit();h.flush();await settle();assert.equal(h.ui.getApplied()!.parameters.width,9.6);h.get('wa-defaults').onclick!();assert.equal(h.get('wa-width').value,'9');assert.equal(h.ui.getApplied()!.parameters.width,9.6);h.get('wa-discard').onclick!();assert.equal(h.get('wa-width').value,'9.6');h.get('wa-reset').onclick!();assert.deepEqual(h.jobs.at(-1)!.draft,h.ui.getApplied()!.parameters);h.flush();await settle();assert.match(h.get('wa-status').textContent,/Applied/);});
test('repeat Apply, newer edits, close and host replacement cancel or ignore stale results',async t=>{const h=harness(t);h.submit();assert(h.jobs[0]!.signal.aborted);h.flush(0);await settle();assert.equal(h.ui.getApplied(),undefined);h.get('wa-depth').value='8.2';h.get('wa-depth').oninput!();assert(h.jobs[1]!.signal.aborted);h.flush(1);await settle();assert.equal(h.ui.getApplied(),undefined);h.submit();h.flush();await settle();assert.equal(h.ui.getApplied()!.parameters.depth,8.2);h.submit();h.get('wa-close').onclick!();assert(h.jobs.at(-1)!.signal.aborted);h.flush();await settle();assert.equal(h.closed(),1);h.submit();assert.equal(h.jobs.length,4);
 const other=harness(t);other.panel.innerHTML='<div id="another"></div>';other.flush();await settle();assert.equal(other.ui.getApplied(),undefined);
});
test('imports are staged, exact and stale reads cannot replace newer edits or reset',async t=>{const h=harness(t);h.flush();await settle();const text=exportWorkshopPreset({...DEFAULT_WORKSHOP_DRAFT,rearRooms:3});let finish!:(text:string)=>void;h.get('wa-file').files=[{size:text.length,text:()=>new Promise(resolve=>finish=resolve)}];const pending=h.get('wa-file').onchange!();h.get('wa-width').value='8.4';h.get('wa-width').oninput!();finish(text);await pending;assert.equal(h.get('wa-width').value,'8.4');assert.equal(h.get('wa-rearRooms').value,'2');h.get('wa-text').value=text;h.get('wa-import-text').onclick!();assert.equal(h.get('wa-rearRooms').value,'3');assert.equal(h.ui.getApplied()!.parameters.rearRooms,2);assert.equal(h.jobs.length,1);h.get('wa-text').value='{"version":9}';h.get('wa-import-text').onclick!();assert.match(h.get('wa-status').textContent,/fields|version/);assert.equal(h.get('wa-rearRooms').value,'3');h.get('wa-export').onclick!();assert.equal(JSON.parse(h.downloads[0]!.text).parameters.rearRooms,2);assert.equal(h.get('wa-text').value,h.downloads[0]!.text);
});
test('bad numbers preserve visible plan and async file errors stay scoped',async t=>{const h=harness(t);h.flush();await settle();const before=h.ui.getApplied();h.get('wa-width').value='';h.submit();assert.equal(h.jobs.length,1);assert.equal(h.ui.getApplied(),before);assert.match(h.get('wa-status').textContent,/Width/);h.get('wa-file').files=[{size:4097,text:()=>{throw Error('must not read');}}];await h.get('wa-file').onchange!();assert.match(h.get('wa-status').textContent,/4 KB/);});
