import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three/webgpu';
import {createWorkshopConstructionView,WorkshopConstructionProjection,workshopConstructionObstacles} from '../src/workshop-construction-view.ts';
import {workshopConstructionQuote,workshopConstructionBoxes,WORKSHOP_BOARD,WORKSHOP_PARCEL,type WorkshopConstructionState} from '../src/workshop-construction.ts';
import {DEFAULT_WORKSHOP_DRAFT} from '../src/workshop-authoring.ts';
const quote=workshopConstructionQuote(DEFAULT_WORKSHOP_DRAFT),base:WorkshopConstructionState={version:1,revision:1,parcelId:WORKSHOP_PARCEL.id,parameters:{...DEFAULT_WORKSHOP_DRAFT},workerId:'test-worker',materialsPaid:quote.materials,work:0,workRequired:quote.workSeconds,status:'building',repairs:0};
const progress=(ratio:number):WorkshopConstructionState=>({...base,work:base.workRequired*ratio,status:ratio===1?'complete':'building'});
const outside={x:WORKSHOP_PARCEL.x+20,z:WORKSHOP_PARCEL.z};
test('earned workshop stages change structural presentation at exact work boundaries without extra collision packets',()=>{const view=createWorkshopConstructionView(),projection=new WorkshopConstructionProjection(),packet=projection.stage(base,0)!;projection.acknowledge(packet.revision,true);const obstacles=workshopConstructionObstacles(base),seen=new Set<string>(),presentations=new Map<string,string>();try{for(const [ratio,id] of [[0,'funded'],[.0001,'frame'],[1/3-1e-9,'frame'],[1/3,'panels'],[2/3-1e-9,'panels'],[2/3,'finishing'],[1,'complete']] as const){const state=progress(ratio);view.update(state,projection.confirmed,outside,true,true);assert.equal(view.root.userData.constructionStage,id);assert.equal(projection.stage(state,100+ratio),null);assert.deepEqual(workshopConstructionObstacles(state),obstacles);const signature:string[]=[];view.root.traverse(o=>{if(o instanceof THREE.Mesh)signature.push(`${o.name}:${(o.material as THREE.MeshStandardMaterial).color.getHexString()}`);});if(!seen.has(id)){seen.add(id);presentations.set(id,signature.filter(s=>s.startsWith('stage-detail/')||s.startsWith('campaign-workshop/')).join('|'));assert(signature.some(s=>s.includes('stage-detail'))||id==='complete');}}assert.equal(seen.size,5);assert.equal(new Set(presentations.values()).size,5,'Each earned stage changes actual geometry/material presentation');}finally{view.dispose();}});
test('every unfinished solid keeps its exact occupied envelope and all decorative geometry stays within it',()=>{const view=createWorkshopConstructionView();try{for(const ratio of [0,.1,.4,.8,1]){view.update(progress(ratio),base,outside,true,true);for(const b of workshopConstructionBoxes(base)){const mesh=view.root.getObjectByName(b.id)!;assert(mesh.visible);assert.deepEqual(mesh.position.toArray(),[b.center.x,b.center.y,b.center.z]);assert.deepEqual(mesh.scale.toArray(),[b.half.x*2,b.half.y*2,b.half.z*2]);mesh.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const extent=new THREE.Box3().setFromObject(o);assert(extent.min.x>=b.center.x-b.half.x-1e-6&&extent.max.x<=b.center.x+b.half.x+1e-6);assert(extent.min.y>=b.center.y-b.half.y-1e-6&&extent.max.y<=b.center.y+b.half.y+1e-6);assert(extent.min.z>=b.center.z-b.half.z-1e-6&&extent.max.z<=b.center.z+b.half.z+1e-6);});}}}finally{view.dispose();}});

test('staging keeps ACK cutaway and save boundaries while reusing and disposing bounded graphics resources',()=>{const view=createWorkshopConstructionView(),parent=new THREE.Group();parent.add(view.root);const before=JSON.stringify(base),materials=new Set<THREE.Material>(),geometries=new Set<THREE.BufferGeometry>(),counts=new Map<object,number>();function capture(){let decorations=0;view.root.traverse(o=>{if(o.userData.nonSolid)decorations++;if(o instanceof THREE.Mesh){geometries.add(o.geometry);for(const material of Array.isArray(o.material)?o.material:[o.material])materials.add(material);}});assert(decorations<=256,'Decorative population stays bounded by the compiled shapes');}view.update(progress(.8),undefined,outside,true,true);assert.equal(view.root.userData.constructionStage,'unfunded');for(const ratio of [0,.1,.4,.8,1]){view.update(progress(ratio),base,outside,true,true);capture();}assert.equal(geometries.size,1,'All decorations reuse the one box geometry');for(const resource of [...materials,...geometries]){counts.set(resource,0);resource.addEventListener('dispose',()=>counts.set(resource,counts.get(resource)!+1));}view.update(progress(.4),base,WORKSHOP_PARCEL,true,true);for(const b of workshopConstructionBoxes(base).filter(b=>b.material==='workshop-roof'))assert.equal(view.root.getObjectByName(b.id)!.visible,false);view.update(progress(.4),{...base,parameters:{...base.parameters,width:9.6}},outside,true,true);assert.equal(view.root.userData.constructionStage,'unfunded');assert.equal(view.root.getObjectByName(workshopConstructionBoxes(base)[0]!.id),undefined);assert.equal(JSON.stringify(base),before);assert([...counts.values()].every(n=>n===0));view.dispose();assert([...counts.values()].every(n=>n===1));assert.equal(parent.children.length,0);assert.equal(view.root.children.length,0);view.dispose();view.update(base,base,outside,true,true);assert([...counts.values()].every(n=>n===1));assert.equal(view.root.children.length,0);});
