import {spawnSync} from 'node:child_process';
import {writeFileSync,mkdirSync,renameSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
import {runRegionalTradeLab} from '../src/regional-trade-lab.ts';
/** Ordinary deterministic production-model, actual generated-terrain and compiled
 * physics-worker game tests only. No live campaign, browser/network, standalone
 * WASM diagnostic, publication or device performance claims. */
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const files=['tests/regional-trade-integration.test.ts','tests/regional-trade-terrain-physics.test.ts'];
const sources=['src/main.ts','src/regional-trade-view.ts','src/regional-trade-ui.ts','src/world-map-view.ts','src/regional-supply-ui.ts','src/session.ts','src/coop-protocol.ts','server/coop-api.ts','server/coop-authority.ts','server/coop-validation.ts','tests/regional-trade-main.test.ts','tests/regional-trade.test.ts','tests/regional-trade-view.test.ts','tests/regional-trade-ui.test.ts','tests/regional-trade-coop.test.ts','tests/regional-trade-recovery.test.ts','src/regional-trade.ts','src/regional-trade-lab.ts','src/world.ts','src/regional-world.ts','src/regional-routes.ts','src/regional-supply.ts','src/regional-supply-lab.ts','src/wilderness-state.ts','src/wilderness.ts','src/wilderness-geometry.ts','src/physics.worker.ts','src/tuning.ts','src/contact-physics.ts','src/player-contact.ts','src/locomotion.ts','src/ledge-mantle.ts','tests/helpers/regional-physics.ts',...files,'scripts/measure-regional-trade.mts','vite.client.config.ts','package.json','package-lock.json'];
const fingerprints=()=>Object.fromEntries(sources.map(file=>[file,createHash('sha256').update(readFileSync(resolve(root,file))).digest('hex')]));
const measuredSources=fingerprints(),command=[process.execPath,'--experimental-strip-types','--test','--test-reporter=spec',...files],started=performance.now();
const result=spawnSync(command[0]!,command.slice(1),{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024,timeout:360_000});
process.stdout.write(result.stdout??'');process.stderr.write(result.stderr??'');
const records=(result.stdout??'').split('\n').flatMap(line=>{const at=line.indexOf('{');if(at<0)return [];try{const value=JSON.parse(line.slice(at));return Object.keys(value).some(k=>k.startsWith('regionalTrade'))?[value]:[];}catch{return [];}});
const coverage={scenario:records.find(r=>r.regionalTradeScenario)??null,replay:records.find(r=>r.regionalTradeReplay)??null,legacy:records.find(r=>r.regionalTradeLegacy)??null,reserveUse:records.find(r=>r.regionalTradeReserveUse)??null,geometry:records.find(r=>r.regionalTradeGeometry)??null,compiledPhysics:records.find(r=>r.regionalTradeCompiledPhysics)??null,terrainPhysics:records.find(r=>r.regionalTradeTerrainPhysics)??null};
const git=spawnSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}),dirty=spawnSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}),sourceRevision=git.status===0?git.stdout.trim():'isolated-stage';
const lab=runRegionalTradeLab(73129,3,{sourceRevision}),seeds=[0,1,42,444,899,12345,73129,0xffffffff];
const seedSweep=seeds.map(seed=>{const run=runRegionalTradeLab(seed,1,{sourceRevision});return {seed,status:run.status,error:run.error??null,passed:run.status==='complete'&&run.runs.every(r=>r.checks.every(c=>c.pass)),failedChecks:run.runs.flatMap(r=>r.checks.filter(c=>!c.pass)),routes:run.runs.flatMap(r=>r.routes.map(p=>({id:p.id,templateId:p.templateId,surfaceMetres:p.surfaceMetres,maxGrade:p.maxGrade,firstDeliveryAtSeconds:p.firstDeliveryAtSeconds,finishedAtSeconds:p.finishedAtSeconds,maxMovingMetresPerSecond:p.maxMovingMetresPerSecond,maxBalanceErrorUnits:p.maxBalanceErrorUnits,final:p.final}))),metrics:run.runs.map(r=>r.metrics)};});
const sourceUnchanged=JSON.stringify(measuredSources)===JSON.stringify(fingerprints()),verified=result.status===0&&lab.status==='complete'&&lab.runs.length===3&&lab.runs.every(run=>run.checks.length>0&&run.checks.every(check=>check.pass))&&sourceUnchanged&&Object.values(coverage).every(Boolean)&&seedSweep.every(r=>r.passed);
const report={version:1,status:verified?'verified':'failed',measuredAt:new Date().toISOString(),source:{head:git.status===0?git.stdout.trim():null,workingTreeDirty:dirty.status===0?Boolean(dirty.stdout.trim()):null,sha256:measuredSources,runtime:process.version},scope:'Isolated production-model regional trade, conservation/replay/legacy tests, six-seed terrain/solid sweep, eight-seed complete-loop sweep, actual compiled production physics-worker route walking, source/work/collector/store collisions and stream/unload/reload. This is neither a browser visual review nor a device frame-rate benchmark; it does not access or mutate a live campaign.',command:command.map(p=>p===process.execPath?'node':p).join(' '),testFiles:files,lab,seedSweep,coverage,checks:{exitCode:result.status,sourceUnchangedDuringRun:sourceUnchanged,elapsedMilliseconds:performance.now()-started,...(!verified?{error:result.error?.message??lab.error??'A scenario assertion, required coverage record or test failed'}:{})}};
mkdirSync(resolve(root,'evidence'),{recursive:true});const target=process.argv[2]?resolve(process.argv[2]):resolve(root,'evidence/regional-trade-report.json'),temporary=target+'.tmp';writeFileSync(temporary,JSON.stringify(report,null,2)+'\n');renameSync(temporary,target);process.stdout.write(`\n${verified?'Verified':'Failed'} regional trade evidence: ${target}\n`);if(!verified)process.exitCode=1;
