import {spawnSync,execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,renameSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve,dirname,relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {REGION_BOUND} from '../src/regional-world.ts';
import {regionalCenterBound} from '../src/regional-bounds.ts';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),tests=['tests/regional-boundary-physics.test.ts','tests/regional-boundary-long-physics.test.ts','tests/regional-prop-residency.test.ts'];
const dependencies=new Set<string>();
function collect(file:string){if(dependencies.has(file))return;dependencies.add(file);if(!/\.(ts|mts)$/.test(file))return;const source=readFileSync(resolve(root,file),'utf8');for(const match of source.matchAll(/(?:from\s*|import\(\s*)['"](\.[^'"]+\.(?:ts|mts))['"]/g)){const path=relative(root,resolve(dirname(resolve(root,file)),match[1]!));if(!path.startsWith('..'))collect(path);}}
for(const file of [...tests,'src/physics.worker.ts','scripts/measure-regional-boundary.mts','package.json','package-lock.json'])collect(file);
const fingerprints=()=>Object.fromEntries([...dependencies].sort().map(file=>[file,createHash('sha256').update(readFileSync(resolve(root,file))).digest('hex')])),before=fingerprints();
const args=['--experimental-strip-types','--test','--test-reporter=spec',...tests],run=spawnSync(process.execPath,args,{cwd:root,encoding:'utf8',maxBuffer:12*1024*1024});process.stdout.write(run.stdout??'');process.stderr.write(run.stderr??'');
const records=(run.stdout??'').split('\n').flatMap(line=>{const i=line.indexOf('{');if(i<0)return [];try{const value=JSON.parse(line.slice(i));return value.scope?[value]:[];}catch{return [];}}),sourceUnchanged=JSON.stringify(before)===JSON.stringify(fingerprints());
const boundaryRuns=records.filter(r=>r.corners||r.edges),cases=boundaryRuns.flatMap(r=>r.corners??r.edges),longRuns=boundaryRuns.filter(r=>r.boundaryTicks===1800),tangential=records.find(r=>r.scope.startsWith('Full analog tangent1'));
const verified=run.status===0&&sourceUnchanged&&cases.length===16&&longRuns.length===2&&tangential?.measurements?.length===4;
const report={version:2,status:verified?'verified':'failed',measuredAt:new Date().toISOString(),source:{head:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),workingTreeDirty:!!execFileSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}).trim(),sha256:before,runtime:process.version},command:'node '+args.join(' '),scope:'Corrected production Rapier regional outer-domain constraint, actual generated clipped terrain/solids,30-second boundary behavior, crouch/jump/tangent/receipt/restore paths, finite movable-prop dormancy and future-footprint readiness. Legacy behavior remains independently tested. Simulation evidence only; not browser visual or device FPS approval.',hz:60,seed:42,boundary:{worldHalfExtentMetres:REGION_BOUND,playerRadiusMetres:.32,skinMetres:.02,acceptedFloat32CenterLimit:regionalCenterBound(REGION_BOUND),strictCenterLimitToleranceMetres:1e-7,capsuleEnvelopePenetrationAllowedMetres:0,minimumMeasuredCapsuleEnvelopeClearanceMetres:cases.length?-Math.max(...cases.map(c=>c.maxCapsuleEnvelopeBeyondBoundary)):null,maximumLateNormalMotionEnvelopeMetres:cases.length?Math.max(...cases.map(c=>c.steadyBoundaryRange)):null,maximumFeetTerrainErrorMetres:cases.length?Math.max(...cases.map(c=>c.maxFeetError)):null},boundaryRuns,tangential,additionalRecords:records.filter(r=>!boundaryRuns.includes(r)&&r!==tangential),memory:{meaning:'collisionInputBufferBytes records are exact Float32 vertex plus Uint32 index buffer lengths from actual resident arrays; they exclude JS overhead, native/WASM memory, renderer and GPU memory.',runtimeRamOrGpuMeasured:false},priorFailures:{preFixBoundaryEvidence:'evidence/regional-boundary-pre-fix-report.json',preFix30SecondDiagnosis:'evidence/regional-boundary-30s-diagnostic.json',v8Disclosure:'A prior auxiliary30-second probe had a native Node/V8 jit_page.has_value assertion in WebAssembly code reclamation/tiering. The isolated pre-fix reruns did not reproduce that engine fatal, but exposed a separate46.160150mm boundary tolerance failure. These are historical failures, not omitted passing results; no specific engine-crash cause or engine fix is claimed.'},checks:{tests:Number((run.stdout??'').match(/ℹ tests (\d+)/)?.[1]??0),pass:Number((run.stdout??'').match(/ℹ pass (\d+)/)?.[1]??0),fail:Number((run.stdout??'').match(/ℹ fail (\d+)/)?.[1]??0),exitCode:run.status,sourceUnchangedDuringRun:sourceUnchanged}};
const target=resolve(root,'evidence/regional-boundary-report.json');writeFileSync(target+'.tmp',JSON.stringify(report,null,2)+'\n');renameSync(target+'.tmp',target);console.log(`\n${verified?'Verified':'Failed'} corrected boundary evidence: evidence/regional-boundary-report.json`);if(!verified)process.exitCode=1;
