import {spawnSync} from 'node:child_process';
import {writeFileSync,mkdirSync,renameSync,readFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
import {runRegionalFoodLab} from '../src/regional-food-lab.ts';
/** Bounded disposable production game checks. No live state/storage, browser,
 * standalone WASM diagnostic, publication or device-performance claims. */
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const files=['tests/regional-food-integration.test.ts','tests/regional-food-terrain-physics.test.ts'];
const sources=['src/regional-food.ts','src/regional-clock.ts','src/regional-food-lab.ts','src/world.ts','src/regional-trade.ts','src/regional-supply.ts','src/regional-supply-lab.ts','src/regional-world.ts','src/regional-routes.ts','src/wilderness-state.ts','src/wilderness.ts','src/wilderness-geometry.ts','src/physics.worker.ts','src/tuning.ts','src/contact-physics.ts','src/player-contact.ts','src/locomotion.ts','src/ledge-mantle.ts','tests/helpers/regional-physics.ts',...files,'scripts/measure-regional-food.mts','vite.client.config.ts','package.json','package-lock.json'];
const optional=['src/main.ts','src/regional-food-view.ts','src/regional-food-ui.ts','src/world-map-view.ts','src/session.ts','src/coop-protocol.ts','server/coop-api.ts','server/coop-authority.ts','server/coop-validation.ts','tests/regional-food-main.test.ts','tests/regional-food.test.ts','tests/regional-food-view.test.ts','tests/regional-food-ui.test.ts','tests/regional-food-coop.test.ts','tests/regional-food-recovery.test.ts','src/coop.ts','src/regional-view.ts','src/regional-supply-ui.ts','src/regional-trade-ui.ts','tests/regional-clock-precision.test.ts','tests/regional-food-trade-witness.test.ts','tests/regional-trade-timeline.test.ts','tests/regional-food-world-authority.test.ts','tests/regional-food-supply-history.test.ts','tests/regional-food-map.test.ts','tests/helpers/regional-food-campaign.ts','tests/helpers/regional-food-http.ts','scripts/verify-regional-food-build.mts'];
const measuredFiles=[...sources,...optional.filter(file=>existsSync(resolve(root,file)))],fingerprints=()=>Object.fromEntries(measuredFiles.map(file=>[file,createHash('sha256').update(readFileSync(resolve(root,file))).digest('hex')]));
const measuredSources=fingerprints(),command=[process.execPath,'--experimental-strip-types','--test','--test-concurrency=1','--test-reporter=spec',...files],started=performance.now();
const result=spawnSync(command[0]!,command.slice(1),{cwd:root,encoding:'utf8',maxBuffer:32*1024*1024,timeout:900_000});
process.stdout.write(result.stdout??'');process.stderr.write(result.stderr??'');
const records=(result.stdout??'').split('\n').flatMap(line=>{const at=line.indexOf('{');if(at<0)return [];try{const value=JSON.parse(line.slice(at));return Object.keys(value).some(k=>k.startsWith('regionalFood'))?[value]:[];}catch{return [];}});
const coverage={scenario:records.find(r=>r.regionalFoodScenario)??null,cycles:records.find(r=>r.regionalFoodCycles)??null,shortage:records.find(r=>r.regionalFoodShortage)??null,coldReplay:records.find(r=>r.regionalFoodColdReplay)??null,geometry:records.find(r=>r.regionalFoodGeometry)??null,compiledPhysics:records.find(r=>r.regionalFoodCompiledPhysics)??null};
const git=spawnSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}),dirty=spawnSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}),sourceRevision=git.status===0?git.stdout.trim():'isolated-stage';
// Run sequentially after physics; never compete with an aggregate suite.
const lab=runRegionalFoodLab(73129,3,{sourceRevision}),seeds=[0,1,42,12345,73129,0xffffffff];
const seedSweep=seeds.map(seed=>{const run=runRegionalFoodLab(seed,1,{sourceRevision});return {seed,status:run.status,error:run.error??null,passed:run.status==='complete'&&run.runs.length===1&&run.runs.every(r=>r.checks.length>0&&r.checks.every(c=>c.pass)),failedChecks:run.runs.flatMap(r=>r.checks.filter(c=>!c.pass)),farms:run.runs.flatMap(r=>r.farms),metrics:run.runs.map(r=>r.metrics)};});
const sourceUnchanged=JSON.stringify(measuredSources)===JSON.stringify(fingerprints()),verified=result.status===0&&lab.status==='complete'&&lab.runs.length===3&&lab.runs.every(run=>run.checks.length>0&&run.checks.every(check=>check.pass))&&sourceUnchanged&&Object.values(coverage).every(Boolean)&&seedSweep.every(r=>r.passed);
const report={version:1,status:verified?'verified':'failed',measuredAt:new Date().toISOString(),source:{head:git.status===0?git.stdout.trim():null,workingTreeDirty:dirty.status===0?Boolean(dirty.stdout.trim()):null,sha256:measuredSources,runtime:process.version,runtimeSha256:createHash('sha256').update(readFileSync(process.execPath)).digest('hex')},scope:'Disposable three-farm production cycles using actual inputs, conservative overflow/seed/food accounting, bounded save stages and old-ledger invariants; six-seed supported-clearance sweep and actual Vite-emitted production physics worker on all three local paths, approaches, streaming boundary and unload/revisit. No browser/device visual review, live-campaign operation or device frame-rate benchmark.',command:command.map(p=>p===process.execPath?'node':p).join(' '),testFiles:files,lab,seedSweep,coverage,checks:{exitCode:result.status,sourceUnchangedDuringRun:sourceUnchanged,elapsedMilliseconds:performance.now()-started,...(!verified?{error:result.error?.message??lab.error??'A required game assertion, evidence record or source stability check failed'}:{})}};
const target=process.argv[2]?resolve(process.argv[2]):resolve(root,'evidence/regional-food-report.json');mkdirSync(dirname(target),{recursive:true});const temporary=target+'.tmp';writeFileSync(temporary,JSON.stringify(report,null,2)+'\n');renameSync(temporary,target);process.stdout.write(`\n${verified?'Verified':'Failed'} regional food evidence: ${target}\n`);if(!verified)process.exitCode=1;
