import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {WorkbenchSession,DEFAULT_WORKBENCH_CONFIG,validateWorkbenchConfig,parseWorkbenchReport,replayWorkbench,WORKBENCH_MAX_TICKS,WORKBENCH_STEP} from '../src/system-workbench-model.ts';
const args=process.argv.slice(2),usage=`AXIOM standalone production workbench\n\nnode --experimental-strip-types scripts/system-workbench.mts [options]\n  --system water|trade|food|settlement  --seed 73129  --index 0\n                           settlement has one target: index 0\n  --rainfall regional|legacy  seeded regional weather by default\n  --travel regional|legacy   weather-aware regional freight by default\n  --irrigation canister      optional Food v2: collect one real canister in setup\n                           manual spending only; --assist never irrigates\n  --view chunk|settlement|route  --cx -8  --cz 0\n  --seconds 600             0–3600 active seconds, in 0.25 s increments\n  --assist                 issue eligible production actions once per second\n                           settlement: start freight, repair, build stores,\n                           withdraw/deliver materials, build collector, farm/tend\n  --reload                 verify the strict production save round-trip\n  --output report.json     export report and deterministic replay recipe\n  --geometry plan.json     export actual selected generation geometry\n  --replay report.json     reproduce and compare an exported scenario\n\nNo browser, server, campaign save or network access. Exit 1 for failed balances,\nround-trip failure or replay mismatch; exit 2 for invalid arguments.\n`;
try{
 if(args.includes('--help')){console.log(usage);process.exit(0);}
 const flags=new Map<string,string|boolean>(),valued=new Set(['--system','--seed','--index','--rainfall','--travel','--irrigation','--view','--cx','--cz','--seconds','--output','--geometry','--replay']);
 for(let i=0;i<args.length;i++){const key=args[i]!;if(flags.has(key))throw Error('Duplicate argument '+key);if(key==='--assist'||key==='--reload'){flags.set(key,true);continue;}if(!valued.has(key))throw Error('Unknown argument '+key);const value=args[++i];if(value===undefined||value.startsWith('--'))throw Error('Missing value for '+key);flags.set(key,value);}
 let revision='not-recorded';try{revision=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();if(execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim())revision+='-working';}catch{}
 const get=(key:string,fallback:string|number)=>flags.has(key)?String(flags.get(key)):String(fallback);
 let session:WorkbenchSession,replayMatch=true,replayMessage='';
 if(flags.has('--replay')){
  if([...flags.keys()].some(k=>!['--replay','--output','--reload','--geometry'].includes(k)))throw Error('Replay takes its seed, system and timeline from the report; do not combine with simulation options');
  const run=replayWorkbench(parseWorkbenchReport(readFileSync(String(flags.get('--replay')),'utf8')),revision);session=run.session;replayMatch=run.result.match;replayMessage=`Replay ${run.result.match?'MATCH':'DIFFERS'}${run.result.firstDifference?': '+run.result.firstDifference:''}${run.result.sourceChanged?' (source revision changed)':''}`;
 }else{
  const seconds=Number(get('--seconds',60));if(!Number.isFinite(seconds)||seconds<0||seconds>WORKBENCH_MAX_TICKS*WORKBENCH_STEP||!Number.isInteger(seconds/WORKBENCH_STEP))throw Error('Seconds must be 0–3600 in 0.25-second increments');
  const config=validateWorkbenchConfig({seed:Number(get('--seed',DEFAULT_WORKBENCH_CONFIG.seed)),system:get('--system','trade'),rainfall:get('--rainfall','regional'),travel:get('--travel','regional'),...(flags.has('--irrigation')?{irrigation:get('--irrigation','canister')}:{}),index:Number(get('--index',0)),view:get('--view','route'),cx:Number(get('--cx',-8)),cz:Number(get('--cz',0))});session=new WorkbenchSession(config,revision);
  const end=seconds/WORKBENCH_STEP;while(session.tick<end){if(flags.has('--assist'))session.assist();const before=session.tick;session.advance(Math.min(flags.has('--assist')?4:240,end-session.tick));if(session.tick===before)break;}
 }
 if(flags.has('--reload'))session.verifyReload();const report=session.report();
 if(flags.has('--output'))writeFileSync(String(flags.get('--output')),JSON.stringify(report,null,2)+'\n');
 if(flags.has('--geometry'))writeFileSync(String(flags.get('--geometry')),JSON.stringify(session.geometry())+'\n');
 console.log(JSON.stringify({system:report.config.system,rainfall:report.config.rainfall??'legacy',travel:report.config.travel??'legacy',seed:report.config.seed,target:report.snapshot.name,seconds:report.snapshot.seconds,phase:report.snapshot.phase,fingerprint:report.finalFingerprint,balances:report.snapshot.checks.every(c=>c.pass)?'conserved':'FAILED',replay:replayMessage||'not requested',reload:report.reload,inventory:report.snapshot.inventory,...(report.snapshot.irrigation?{irrigation:report.snapshot.irrigation}:{}),...(report.snapshot.weather?{weather:report.snapshot.weather}:{}),...(report.snapshot.freight?{freight:report.snapshot.freight}:{}),...(report.snapshot.causes?{causes:report.snapshot.causes}:{}),sourceRevision:revision},null,2));
 if(!replayMatch||report.snapshot.firstFailure||report.snapshot.checks.some(c=>!c.pass)||report.reload.pass===false)process.exitCode=1;
}catch(error){console.error(error instanceof Error?error.message:String(error));process.exitCode=2;}
