import assert from 'node:assert/strict';import {readdirSync,readFileSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {Worker} from 'node:worker_threads';import {DatabaseSync} from 'node:sqlite';
import {TownCrowd,slideTownCrowd,townPathClear} from '../src/town-crowd.ts';
import {generateRegionalChunk} from '../src/regional-world.ts';import {startingTown,TOWN_SPAWN} from '../src/starting-town.ts';import {createRegionalState,validateSave} from '../src/world.ts';import {handleCoop} from '../server/coop-api.ts';
const root=resolve(import.meta.dirname,'..'),assets=resolve(root,'dist/client/assets'),regionalFile=readdirSync(assets).find(f=>/^regional\.worker-.*\.js$/.test(f))!,physicsFile=readdirSync(assets).find(f=>/^physics\.worker-.*\.js$/.test(f))!;assert(regionalFile&&physicsFile);
async function workerBridge(file:string){const w=new Worker(`const {parentPort}=require('node:worker_threads');globalThis.self=globalThis;globalThis.setInterval=()=>0;self.postMessage=m=>parentPort.postMessage(m);parentPort.on('message',m=>self.onmessage({data:m}));import(${JSON.stringify(pathToFileURL(file).href)}).then(()=>parentPort.postMessage({type:'boot'}));`,{eval:true,execArgv:['--experimental-strip-types']});const q:any[]=[];let error:Error|undefined;w.on('error',e=>error=e);w.on('message',m=>{q.push(m);if(m.type==='error')error=Error(m.message);});const take=async(type:string)=>{const end=Date.now()+20000;for(;;){if(error)throw error;const i=q.findIndex(m=>m.type===type);if(i>=0)return q.splice(i,1)[0];assert(Date.now()<end,'Timeout '+type);await new Promise(r=>setTimeout(r,1));}};await take('boot');return {w,take,q,send:(m:unknown)=>w.postMessage(m)};}
const regional=await workerBridge(resolve(assets,regionalFile)),chunks=[];try{for(let cz=-4;cz<=-2;cz++)for(let cx=-4;cx<=-2;cx++){regional.send({type:'generate',id:chunks.length+1,seed:73129,cx,cz});const m=await regional.take('chunk');assert.deepEqual(m.chunk,generateRegionalChunk(73129,cx,cz));chunks.push(m.chunk);}}finally{await regional.w.terminate();}
const cells=chunks.map(c=>({key:'region:'+c.key,revision:1,bounds:c.bounds,terrain:c.terrain,obstacles:[...c.structures.filter((s:any)=>s.solid).map((s:any)=>({x:s.center.x,y:s.center.y,z:s.center.z,hx:s.half.x,hy:s.half.y,hz:s.half.z})),...c.features.flatMap((f:any)=>f.solids)]}));
async function physics(file:string){const b=await workerBridge(file);try{b.send({type:'init',epoch:0,x:TOWN_SPAWN.x,z:TOWN_SPAWN.z,y:6,obstacles:[],initialCells:cells,streamedTerrain:true,bound:Math.sqrt(10000000)/2,startPaused:true,manual:true,town:{seed:73129,time:0,selfId:'solo',actors:[]}});await b.take('ready');b.send({type:'step',epoch:0,ticks:30});await b.take('stepped');const paused=b.q.filter(m=>m.type==='snapshot').at(-1);assert.equal(paused.step,0);assert(Math.abs(paused.feetY-6)<.05);b.send({type:'input',epoch:0,x:1,z:0,paused:false});b.send({type:'step',epoch:0,ticks:90});await b.take('stepped');const final=b.q.filter(m=>m.type==='snapshot').at(-1);assert(final.x>TOWN_SPAWN.x+3);const keeper=new TownCrowd(73129).sample(0)[0]!;b.send({type:'zone',epoch:1,x:keeper.x,z:keeper.z+2,y:6,obstacles:[],initialCells:cells,streamedTerrain:true,bound:Math.sqrt(10000000)/2,startPaused:true,manual:true,town:{seed:73129,time:0,selfId:'solo',actors:[]}});await b.take('ready');b.send({type:'input',epoch:1,x:0,z:-1,paused:false});b.send({type:'step',epoch:1,ticks:120});await b.take('stepped');const crossing=b.q.filter(m=>m.type==='snapshot'&&m.epoch===1).map(({step,x,z,feetY,town})=>({step,x,z,feetY,town}));assert(crossing.length>100);
 const outer=[];let epoch=1;const crowd=new TownCrowd(73129),homePoses=crowd.sample(30);
 for(const side of [-1,1]){
  const pose=homePoses.find((p,i)=>crowd.residents[i]!.homeIndex>=20&&Math.sign(p.z-crowd.plan.center.z)===side&&p.activity==='at home'&&Math.abs(p.z-crowd.plan.center.z)>36)!;assert(pose);
  epoch++;b.send({type:'zone',epoch,x:pose.x-2,z:pose.z,y:6,obstacles:[],initialCells:cells,streamedTerrain:true,bound:Math.sqrt(10000000)/2,startPaused:true,manual:true,town:{seed:73129,time:30,selfId:'solo',actors:[]}});await b.take('ready');b.send({type:'step',epoch,ticks:1});await b.take('stepped');
  const start=b.q.filter(m=>m.type==='snapshot'&&m.epoch===epoch).at(-1);assert(start);assert.equal(start.step,0);
  b.send({type:'input',epoch,x:1,z:0,paused:false});b.send({type:'step',epoch,ticks:120});await b.take('stepped');
  const trace=b.q.filter(m=>m.type==='snapshot'&&m.epoch===epoch).map(({step,x,z,feetY,town})=>({step,x,z,feetY,town}));assert(trace.length>100);
  let prior=start;for(const point of trace){const poses=crowd.sample(point.town.time,100,1,[{id:'solo',x:prior.x,z:prior.z,feetY:prior.feetY}]),resolved=slideTownCrowd(prior,point,poses,prior.feetY);assert(Math.hypot(resolved.x-point.x,resolved.z-point.z)<.002);assert(townPathClear(crowd.plan,prior,point,.31));prior=point;}
  assert(trace.at(-1)!.x>start.x+.8);outer.push({side,trace});
 }
 const recoveries=[];for(const homeIndex of [20,39]){
  const wall=crowd.plan.homes[homeIndex]!.boxes.find(b=>b.id.endsWith('/back'))!;epoch++;
  b.send({type:'zone',epoch,x:wall.center.x,z:wall.center.z,y:6,obstacles:[],initialCells:cells,streamedTerrain:true,bound:Math.sqrt(10000000)/2,startPaused:true,manual:true});await b.take('ready');b.send({type:'step',epoch,ticks:30});await b.take('stepped');
  const {x,z,feetY,step}=b.q.filter(m=>m.type==='snapshot'&&m.epoch===epoch).at(-1);assert.equal(step,0);assert(Math.hypot(x-wall.center.x,z-wall.center.z)>.35);recoveries.push({homeIndex,x,z,feetY,step});
 }
 return {crossing,outer,recoveries,paused:{x:paused.x,z:paused.z,feetY:paused.feetY,step:paused.step},final:{x:final.x,z:final.z,feetY:final.feetY,step:final.step},colliders:final.streaming.totalColliders};}finally{await b.w.terminate();}}
const sourcePhysics=await physics(resolve(root,'src/physics.worker.ts')),emittedPhysics=await physics(resolve(assets,physicsFile));assert.deepEqual(emittedPhysics,sourcePhysics);
const built=(await import(pathToFileURL(resolve(root,'dist/server/index.js')).href)).default;
async function authority(emitted:boolean){const db=new DatabaseSync(':memory:');for(const file of readdirSync(resolve(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(resolve(root,'drizzle',file),'utf8'));const DB={prepare(sql:string){let values:any[]=[];return {bind(...next:any[]){values=next;return this;},async first(){return db.prepare(sql).get(...values)??null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){const result=db.prepare(sql).run(...values);return {success:true,meta:{changes:Number(result.changes)}};}};}};async function req(path:string,body?:unknown){const r=new Request('https://fixture.invalid/api/coop'+path,{method:body?'POST':'GET',headers:{Origin:'https://fixture.invalid','oai-authenticated-user-id':'town-build-host',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})}),response=emitted?await built.fetch(r,{AXIOM_PREVIEW_DB:DB}):await handleCoop(r,{DB},1800000000000);assert(response);assert(response.ok);return await response.json() as any;}
try{const s=createRegionalState(73129);s.player={...s.player,...startingTown(s.seed).shops[0]!.entry};const first=await req('/rooms',{name:'Town build',world:s}),command={type:'town-purchase',command:{offerId:'arrival-kit',expectedRevision:0}},next=await req(`/rooms/${first.roomId}/sync`,{seq:1,sessionId:first.sessionId,actions:[command]}),retry=await req(`/rooms/${first.roomId}/sync`,{seq:1,sessionId:first.sessionId,actions:[command]});assert(validateSave(next.world));assert.deepEqual(retry.world.town,next.world.town);assert.deepEqual(next.world.inventory,{scrap:3,core:0,water:1});return {town:next.world.town,inventory:next.world.inventory};}finally{db.close();}}
const sourceAuthority=await authority(false),emittedAuthority=await authority(true);assert.deepEqual(emittedAuthority,sourceAuthority);
const result={kind:'axiom-town-build-verification',scope:'Local source/emitted regional worker, real Rapier WASM and ESM server with in-memory SQLite. No browser/GPU/production probes.',seed:73129,matchingTownChunks:chunks.length,sourceEmittedPhysics:sourcePhysics,matchingAuthority:sourceAuthority,checks:['Nine source/emitted expanded-town chunks match exactly','Paused town preload remains at step zero','Source/emitted real controller walks identically on actual town geometry','Both added household streets enforce source/emitted crowd sweeps','Both added-house wall overlaps recover while paused at step zero','Built preview DB binding performs one valid arrival purchase','Same-sequence retry creates no duplicate receipt']};const output=process.argv.find(a=>a.endsWith('.json'));if(output)writeFileSync(output,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
