import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {applyAction,enableRegionalFood,parseSave,serializeSave,worldObjects,type State} from '../src/world.ts';
import {createRegionalFoodLabCampaign} from '../src/regional-food-lab.ts';
import {regionalFoodPlan,regionalFoodConservation,regionalFoodCost,type RegionalFoodCommand} from '../src/regional-food.ts';
import {regionalSupplyWeather} from '../src/regional-supply.ts';
// Disposable, ordinary active clocks only. Accepts an output directory, never a save.
const out=resolve(process.argv[2]??'/tmp/axiom-irrigation-evidence');mkdirSync(out,{recursive:true});
let source=enableRegionalFood(createRegionalFoodLabCampaign(73129,true,2,1),2),p=regionalFoodPlan(source.seed).farms[0]!;
const canister=worldObjects(source).find(o=>o.kind==='water')!;source=applyAction(source,{type:'move',x:canister.x,z:canister.z});source=applyAction(source,{type:'collect',id:canister.id});assert.equal(source.inventory.water,1);assert(source.collected.includes(canister.id));
function issue(s:State,type:RegionalFoodCommand['type']){s=applyAction(s,{type:'move',x:p.interactionPosition.x,z:p.interactionPosition.z});return applyAction(s,{type:'regional-food',command:{type,targetId:p.id,expectedRevision:s.frontierFood!.revision}});}
source=issue(source,'start-farm');const initial=serializeSave(source);let control=source,treated=issue(source,'irrigate-farm');assert.equal(treated.inventory.water,0);const startSeconds=source.frontierSupply!.ticks/4,weather=regionalSupplyWeather(source.frontierSupply!,p.siteId),events:{tick:number;seconds:number;kind:string}[]=[],seen=new Set<string>(),checkpoints:{tick:number;bytes:number;sha256:string}[]=[];
assert.equal(weather.phase,'dry');assert(weather.secondsUntilChange>=400);
for(let tick=0;tick<=1600;tick++){
 const f=treated.frontierFood!.farms[0]!;for(const [kind,happened] of [['plant',f.seedsSown>0],['harvest',f.harvested>0],['load',f.reserved>0],['carry',f.cargo>0&&f.activity==='outbound'],['unload',f.cargo>0&&f.activity==='unloading'],['delivered',f.delivered>0],['harvested-meal',f.meals>4],['second-harvest',f.harvests===2]] as const)if(happened&&!seen.has(kind)){events.push({tick,seconds:tick/4,kind});seen.add(kind);}
 assert.deepEqual(treated.frontierSupply,control.frontierSupply);assert.deepEqual(treated.frontierTrade,control.frontierTrade);assert.deepEqual(regionalSupplyWeather(treated.frontierSupply!,p.siteId),regionalSupplyWeather(control.frontierSupply!,p.siteId));assert.equal(f.sourceSpilled,control.frontierFood!.farms[0]!.sourceSpilled);assert.equal(f.waterCaptured,0);assert.equal(f.waterLost,0);assert(regionalFoodConservation(treated.frontierFood!).every(r=>r.balanced));
 if(tick%200===0){const bytes=serializeSave(treated);treated=parseSave(bytes)!;assert(treated);assert.equal(serializeSave(treated),bytes);checkpoints.push({tick,bytes:Buffer.byteLength(bytes),sha256:createHash('sha256').update(bytes).digest('hex')});}
 if(tick<1600){control=applyAction(control,{type:'tick',dt:.25});treated=applyAction(treated,{type:'tick',dt:.25});}
}
const f=treated.frontierFood!.farms[0]!,untreated=control.frontierFood!.farms[0]!;assert.equal(f.harvested,8);assert.equal(f.waterUsed,4);assert.equal(f.delivered,8);assert(f.meals>4);assert.equal(untreated.harvested,0);assert.equal(untreated.seedsSown,0);assert.equal(regionalFoodCost(treated.frontierFood).water,1);
const saved=serializeSave(treated);writeFileSync(resolve(out,'irrigation-final-save.json'),saved+'\n');writeFileSync(resolve(out,'irrigation-control-save.json'),serializeSave(control)+'\n');writeFileSync(resolve(out,'irrigation-start-save.json'),initial+'\n');
const world=new URL('../src/world.ts',import.meta.url).href,cold=JSON.parse(execFileSync(process.execPath,['--experimental-strip-types','--input-type=module','-e',`import {readFileSync} from 'node:fs';import {parseSave,serializeSave} from ${JSON.stringify(world)};const raw=readFileSync(0,'utf8'),start=performance.now(),s=parseSave(raw);if(!s||serializeSave(s)!==raw)throw Error('Cold saved state differs');const invented=JSON.parse(raw);invented.inventory.water++;if(parseSave(JSON.stringify(invented)))throw Error('Unpaid water accepted');console.log(JSON.stringify({exact:true,unpaidCanisterRejected:true,milliseconds:performance.now()-start,runtime:process.version}));`],{input:saved,encoding:'utf8'}));
const report={kind:'axiom-emergency-irrigation-verification',version:1,sourceRevision:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty:!!execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),runtime:process.version,scope:'Separate disposable earned-prerequisite scenario; all clocks ordinary. No live campaign, terminal review, browser, device, deployment or release clearance.',seed:source.seed,farmId:p.id,foodVersion:2,supplyVersion:source.frontierSupply!.version,tradeVersion:source.frontierTrade!.version,setupActiveSeconds:startSeconds,scenarioSeconds:400,canister:{id:canister.id,earnedBy:'production collect',countBefore:1,countAfter:0,cost:1,litres:4,oncePerFarm:true},weather,sourceHistoryExactlyMatchesControl:true,tradeHistoryExactlyMatchesControl:true,initialExcludedRainSpill:source.frontierFood!.farms[0]!.sourceSpilled,treated:{water:f.water,imported:f.waterIrrigated,captured:f.waterCaptured,lost:f.waterLost,used:f.waterUsed,harvests:f.harvests,harvested:f.harvested,delivered:f.delivered,starter:f.starterGranted,meals:f.meals,harvestedMealsMinimum:Math.max(0,f.meals-f.starterGranted)},untreated:{water:untreated.water,harvested:untreated.harvested,meals:untreated.meals,canisters:control.inventory.water},conservation:regionalFoodConservation(treated.frontierFood!),events,checkpoints,cold,foodBytes:Buffer.byteLength(JSON.stringify(treated.frontierFood)),saveBytes:Buffer.byteLength(saved)};
writeFileSync(resolve(out,'irrigation-measurements.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
