import assert from 'node:assert/strict';import {readFileSync,readdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {Worker} from 'node:worker_threads';
import {WorkbenchSession,DEFAULT_WORKBENCH_CONFIG} from '../src/system-workbench-model.ts';import {settlementActionId} from '../src/regional-settlement-workbench.ts';import type {WorkbenchResponse} from '../src/system-workbench-protocol.ts';import type {WorkbenchCommand} from '../src/system-workbench-client.ts';
/** Executes built assets and the emitted model worker locally. No HTTP server,
 * browser, production URL, network request or rendering is involved. */
const root=resolve(import.meta.dirname,'..'),serverPath=resolve(root,'dist/server/index.js'),server=(await import(pathToFileURL(serverPath).href)).default,client=resolve(root,'dist/client'),checks:string[]=[],assets:{path:string;bytes:number;sha256:string}[]=[];
async function verifyAssets(folder:string,prefix=''){for(const entry of readdirSync(folder,{withFileTypes:true})){const file=resolve(folder,entry.name),url=prefix+'/'+entry.name;if(entry.isDirectory())await verifyAssets(file,url);else{const bytes=readFileSync(file),response=await server.fetch(new Request('https://fixture.invalid'+url),{});assert.equal(response.status,200,url);assert.deepEqual(Buffer.from(await response.arrayBuffer()),bytes,url);assets.push({path:url,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}}}
await verifyAssets(client);assert(assets.some(a=>a.path==='/system-workbench.html'));const html=readFileSync(resolve(client,'system-workbench.html'),'utf8');assert(!/src="[^\"]*\/game-/.test(html));checks.push('Compiled server serves every emitted asset byte-for-byte, including standalone workbench');
const emitted=readdirSync(resolve(client,'assets')).filter(f=>/^system-workbench\.worker-.*\.js$/.test(f));assert.equal(emitted.length,1);const file=resolve(client,'assets',emitted[0]!),url=pathToFileURL(file).href;
const worker=new Worker(`const {parentPort}=require('node:worker_threads');globalThis.self={postMessage:value=>parentPort.postMessage(value)};parentPort.on('message',data=>self.onmessage({data}));import(${JSON.stringify(url)}).then(()=>parentPort.postMessage({ready:true}));`,{eval:true});
let next=0;const waiting=new Map<number,{resolve:(r:WorkbenchResponse)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
const ready=new Promise<void>((resolveReady,reject)=>{worker.once('error',reject);worker.on('message',(r:WorkbenchResponse&{ready?:boolean})=>{if(r.ready){resolveReady();return;}const pending=waiting.get(r.id);if(!pending)return;clearTimeout(pending.timer);waiting.delete(r.id);r.ok?pending.resolve(r):pending.reject(Error(r.error));});});
const send=(message:WorkbenchCommand)=>{const id=++next;return new Promise<WorkbenchResponse>((resolveResponse,reject)=>{const timer=setTimeout(()=>{waiting.delete(id);reject(Error('Emitted workbench request timed out'));},60000);waiting.set(id,{resolve:resolveResponse,reject,timer});worker.postMessage({...message,id});});};
try{await ready;for(const [system,rainfall,travel,irrigation] of [['trade',undefined,undefined],['water',undefined,undefined],['food',undefined,undefined],['water','regional',undefined],['food','regional',undefined],['settlement','regional',undefined],['trade','regional','regional'],['water','regional','regional'],['food','regional','regional'],['settlement','regional','regional'],['food','regional','regional','canister']] as const){const config={...DEFAULT_WORKBENCH_CONFIG,system,...(rainfall?{rainfall}:{}),...(travel?{travel}:{}),...(irrigation?{irrigation}:{})},source=new WorkbenchSession(config,'compiled-check'),created=await send({kind:'create',config,revision:'compiled-check'});assert.deepEqual(created.snapshot,source.snapshot());assert.deepEqual(created.geometry,source.geometry());if(irrigation){assert.equal(source.report().version,3);assert.equal(source.snapshot().irrigation!.canisters,1);assert(source.action('irrigate-farm'));const watered=await send({kind:'action',action:'irrigate-farm'});assert.deepEqual(watered.snapshot,source.snapshot());assert.equal(watered.snapshot!.irrigation!.importedLitres,4);assert.equal(watered.snapshot!.irrigation!.canisters,0);assert.equal(source.action('irrigate-farm'),false);assert.deepEqual((await send({kind:'action',action:'irrigate-farm'})).snapshot,source.snapshot());}const batches=system==='water'&&rainfall==='regional'?42:3;for(let i=0;i<batches;i++){source.advance(240);const advanced=await send({kind:'advance',ticks:240});assert.deepEqual(advanced.snapshot,source.snapshot());}source.verifyReload();assert((await send({kind:'reload'})).reload?.pass);assert.deepEqual((await send({kind:'report'})).report,source.report());const text=JSON.stringify(source.report()),replayed=await send({kind:'replay',text,revision:'compiled-check'});assert(replayed.replay?.match);assert.deepEqual(replayed.snapshot,source.snapshot());checks.push(`${system} / rainfall ${rainfall??'legacy'} / travel ${travel??'legacy'}${irrigation?' / manual one-use canister irrigation':''}: emitted worker create, geometry, ${batches*60} s stepping, strict save check, report and replay match source production model`);}
 const integrated=new WorkbenchSession({...DEFAULT_WORKBENCH_CONFIG,system:'settlement',rainfall:'regional',travel:'regional'},'compiled-check');
 for(let second=0;second<3600;second++){integrated.assist();integrated.advance(4);}assert(integrated.snapshot().inventory.harvestedMealsMinimum!>0);const recipe=integrated.report();
 await send({kind:'create',config:recipe.config,revision:'compiled-check'});for(const event of recipe.events.filter(e=>e.tick===0))await send({kind:'action',action:settlementActionId(event.domain!,event.targetId!,event.action)});
 const replayedSettlement=await send({kind:'replay',text:JSON.stringify(recipe),revision:'compiled-check'});assert(replayedSettlement.replay?.match);assert.deepEqual(replayedSettlement.snapshot,integrated.snapshot());integrated.verifyReload();assert((await send({kind:'reload'})).reload?.pass);assert.deepEqual((await send({kind:'report'})).report,integrated.report());
 checks.push(`settlement / regional rainfall and travel: emitted worker target actions, full 3600 s production replay, harvested meals, exact final ${recipe.finalFingerprint}, strict reload and source report parity`);
 const report={kind:'axiom-system-workbench-build-check',version:1,sourceRevision:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),dirty:!!execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim(),runtime:process.version,scope:'Local compiled server asset delivery plus actual emitted model worker in a Node worker-thread adapter. No browser rendering, DOM pixels, device, physics-controller, production Site or network test.',workerSha256:createHash('sha256').update(readFileSync(file)).digest('hex'),serverSha256:createHash('sha256').update(readFileSync(serverPath)).digest('hex'),assets,checks};const output=process.argv[2];if(output)writeFileSync(resolve(output),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{for(const pending of waiting.values())clearTimeout(pending.timer);await worker.terminate();}
