import assert from 'node:assert/strict';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import {TOWN_SUPPLY_ENGINE,type TownSupplyState,type TownSupplyCommand} from '../src/town-supply.ts';
import {TOWN_LIFE_ENGINE,assignTownWorkshopWorker,type TownLifeState} from '../src/town-life.ts';
import {WORKSHOP_CONSTRUCTION_ENGINE,WORKSHOP_PARCEL,WORKSHOP_BOARD} from '../src/workshop-construction.ts';
import {DEFAULT_WORKSHOP_DRAFT} from '../src/workshop-authoring.ts';
import {createRegionalState,enableStartingTown,worldTownSupplySources,applyAction,validateSave,serializeSave,parseSave,type State} from '../src/world.ts';
import {handleCoop} from '../server/coop-api.ts';
const root=resolve(import.meta.dirname,'..'),assets=resolve(root,'dist/client/assets'),files=readdirSync(assets),digest=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const modules=await Promise.all(files.filter(f=>/^(town-supply-engine|restoration-care-engine|restoration-engine|town-life|town-director|workshop-construction-engine)-.*\.js$/.test(f)).map(async file=>({file,module:await import(pathToFileURL(resolve(assets,file)).href),sha256:digest(readFileSync(resolve(assets,file),'utf8'))})));
function surface<T>(kind:string):{file:string;value:T;sha256:string}{const found=modules.flatMap(m=>Object.values(m.module).filter((v:any)=>v?.kind===kind).map(value=>({file:m.file,value:value as T,sha256:m.sha256})));assert.equal(found.length,1,`exactly one actual emitted ${kind} engine`);return found[0]!;}
const supplyAsset=surface<typeof TOWN_SUPPLY_ENGINE>('axiom-town-supply'),townAsset=surface<typeof TOWN_LIFE_ENGINE>('axiom-town-life'),constructionAsset=surface<typeof WORKSHOP_CONSTRUCTION_ENGINE>('axiom-workshop-construction');
const supplyEngine=supplyAsset.value,townEngine=townAsset.value,constructionEngine=constructionAsset.value,modelCases:any[]=[];
for(const seed of [0,73129,0xffffffff]){
 const world=enableStartingTown(createRegionalState(seed)),sources=worldTownSupplySources(world);assert.equal(sources.length,7);
 let life=TOWN_LIFE_ENGINE.scenario(seed,'lean-stores'),builtLife=townEngine.scenario(seed,'lean-stores'),supply:TownSupplyState|undefined,builtSupply:TownSupplyState|undefined,inventory={scrap:0,core:0,water:0},collected:string[]=[],actions=0;
 assert.deepEqual(builtLife,life);
 // Explicit disposable shortage fixture; campaign opening stocks are unchanged.
 life=structuredClone(life);builtLife=structuredClone(builtLife);life.resources.materials=0;life.ledger.initial.materials=0;builtLife.resources.materials=0;builtLife.ledger.initial.materials=0;
 assert(townEngine.validate(builtLife,seed));assert(TOWN_LIFE_ENGINE.validate(life,seed));
 const unavailableBuild={kind:'build' as const,expectedRevision:0,parcelId:WORKSHOP_PARCEL.id,parameters:{...DEFAULT_WORKSHOP_DRAFT,seed},workerId:life.residents[0]!.id},buildContext={seed,zone:'valley',player:{...WORKSHOP_BOARD,hp:75}};
 assert.match(WORKSHOP_CONSTRUCTION_ENGINE.blockReason(undefined,life,buildContext,unavailableBuild)!,/materials/);assert.equal(WORKSHOP_CONSTRUCTION_ENGINE.apply(undefined,life,buildContext,unavailableBuild),null);assert.equal(constructionEngine.apply(undefined,builtLife,buildContext,unavailableBuild),null);
 function command(kind:TownSupplyCommand['kind'],targetId:string){const command={kind,targetId,expectedRevision:supply?.revision??0},point=TOWN_SUPPLY_ENGINE.position(seed,sources,command)!;assert(point);const context={seed,zone:'valley',player:{x:point.x,z:point.z,hp:100,feetY:point.y},inventory,collected};
  assert.deepEqual(supplyEngine.position(seed,sources,command),point);const a=TOWN_SUPPLY_ENGINE.apply(supply,sources,life,context,command),b=supplyEngine.apply(builtSupply,sources,builtLife,context,command);assert(a);assert.deepEqual(b,a);supply=a.supply;builtSupply=b!.supply;life=a.life;builtLife=b!.life;inventory=a.inventory;collected=a.collected;actions++;
  assert(supplyEngine.validate(builtSupply,sources,collected,builtLife));assert(townEngine.validate(builtLife,seed));assert.deepEqual(supplyEngine.immutable(JSON.parse(JSON.stringify(builtSupply)),sources,collected,builtLife),builtSupply);
  assert.equal(supplyEngine.apply(builtSupply,sources,builtLife,{...context,inventory,collected},command),null,'exact packet cannot reload or redeliver');
  assert.equal(supply.sources.length,supply.carried+supply.unloaded+2*supply.deliveries);assert.equal(collected.length,supply.sources.length);assert.equal(inventory.scrap+supply.carried+life.playerSpent.scrap,collected.length);
 }
 for(let batch=0;batch<3;batch++){
  command('load',sources[batch*2]!.id);command('load',sources[batch*2+1]!.id);const before=life.resources.materials;command('deliver','workshop');assert.equal(life.resources.materials,before+12);assert.equal(life.supplyDeliveries,batch+1);assert.equal(inventory.scrap,0);
  if(batch<2){life=TOWN_LIFE_ENGINE.advance(life,10);builtLife=townEngine.advance(builtLife,10);assert.deepEqual(builtLife,life);}
 }
 command('load',sources[6]!.id);command('unload','workshop');assert.equal(inventory.scrap,1);assert.equal(supply!.deliveries,3);assert.equal(supply!.carried,0);
 const loaded=JSON.parse(JSON.stringify(life));assert.deepEqual(townEngine.advance(loaded,.5),TOWN_LIFE_ENGINE.advance(life,.5));
 for(const edit of [(v:any)=>v.carried++,(v:any)=>v.sources.pop(),(v:any)=>v.deliveries--,(v:any)=>v.sources[0]='forged-cache']){const bad=structuredClone(supply);edit(bad);assert.equal(supplyEngine.validate(bad,sources,collected,life),false);assert.equal(TOWN_SUPPLY_ENGINE.validate(bad,sources,collected,life),false);}
 const worker=life.residents.find(r=>assignTownWorkshopWorker(life,r.id));assert(worker);const build={kind:'build' as const,expectedRevision:0,parcelId:WORKSHOP_PARCEL.id,parameters:{...DEFAULT_WORKSHOP_DRAFT,seed},workerId:worker.id},context={seed,zone:'valley',player:{...WORKSHOP_BOARD,hp:75}},before=life.resources.materials;
 const a=WORKSHOP_CONSTRUCTION_ENGINE.apply(undefined,life,context,build),b=constructionEngine.apply(undefined,builtLife,context,build);assert(a);assert.deepEqual(b,a);assert.equal(a.life.resources.materials,before-WORKSHOP_CONSTRUCTION_ENGINE.quote(build.parameters).materials);assert.equal(a.life.workshopSpent,a.construction.materialsPaid);assert.equal(a.life.supplyDeliveries,3);assert.equal(a.life.ledger.donated.materials,36);assert(townEngine.validate(b!.life,seed));
 assert.equal(constructionEngine.apply(b!.construction,b!.life,context,build),null);modelCases.push({seed,initialMaterials:0,constructionBlockedBeforeDelivery:true,actions,caches:collected.length,supply,ordinaryInventory:inventory,donatedMaterials:life.ledger.donated.materials,constructionPaid:a.construction.materialsPaid,materialsAfterConstruction:a.life.resources.materials,sha256:digest({supply,life:a.life,construction:a.construction})});console.error(`town supply emitted finite sources, delivery and construction seed ${seed} passed`);
}
const builtServer=(await import(pathToFileURL(resolve(root,'dist/server/index.js')).href)).default;
function at(state:State,kind:TownSupplyCommand['kind'],targetId:string):State{const point=TOWN_SUPPLY_ENGINE.position(state.seed,worldTownSupplySources(state),{kind,targetId})!;assert(point);return {...state,player:{...state.player,x:point.x,z:point.z}};}
function intent(state:State,kind:TownSupplyCommand['kind'],targetId:string){return {type:'town-supply' as const,command:{kind,targetId,expectedRevision:state.townSupply?.revision??0}};}
async function serverCase(emitted:boolean){const db=new DatabaseSync(':memory:');for(const file of readdirSync(resolve(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(resolve(root,'drizzle',file),'utf8'));const DB={prepare(sql:string){let values:any[]=[];return {bind(...next:any[]){values=next;return this;},async first(){return db.prepare(sql).get(...values)??null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){const result=db.prepare(sql).run(...values);return {success:true,meta:{changes:Number(result.changes)}};}};}};const now=1900000000000,originalNow=Date.now;Date.now=()=>now;
 async function request(path:string,body:unknown,expected=200,user='town-supply-host',preview=true){const req=new Request('https://fixture.invalid/api/coop'+path,{method:'POST',headers:{Origin:'https://fixture.invalid','oai-authenticated-user-id':user,'Content-Type':'application/json'},body:JSON.stringify(body)}),response=emitted?await builtServer.fetch(req,preview?{AXIOM_PREVIEW_DB:DB}:{DB}):await handleCoop(req,preview?{DB}:{},now);assert.equal(response?.status,expected,await response?.clone().text());return await response!.json() as any;}
 try{
  const base=enableStartingTown(createRegionalState(73129)),sources=worldTownSupplySources(base),ready=at(base,'load',sources[0]!.id);assert(validateSave(ready));await request('/rooms',{name:'Missing binding',world:ready},503,'town-supply-host',false);
  let current=await request('/rooms',{name:'Finite load',world:ready},201);const packet={seq:1,sessionId:current.sessionId,actions:[intent(current.world,'load',sources[0]!.id)]},roomId=current.roomId;
  const guest=await request('/join',{name:'Supply guest',code:current.code},200,'town-supply-guest'),denied=await request(`/rooms/${roomId}/sync`,{seq:1,sessionId:guest.sessionId,actions:packet.actions},200,'town-supply-guest');assert.equal(denied.world.townSupply,undefined,'shared cargo is host-authoritative');
  current=await request(`/rooms/${roomId}/sync`,packet);assert.equal(current.world.townSupply.carried,1);assert.deepEqual(current.world.inventory,base.inventory);assert.deepEqual((await request(`/rooms/${roomId}/sync`,packet)).world,current.world);assert.equal(current.world.collected.filter((id:string)=>id===sources[0]!.id).length,1);
  // Import a second real load at the workshop: source receipts and tombstones
  // are preserved. This numerical fixture does not claim player travel QA.
  let loaded=at(current.world,'load',sources[1]!.id);loaded=applyAction(loaded,intent(loaded,'load',sources[1]!.id));assert.equal(loaded.townSupply!.carried,2);loaded=at(loaded,'deliver','workshop');assert.deepEqual(parseSave(serializeSave(loaded)),loaded);
  const imported=await request('/rooms',{name:'Loaded cargo import',world:loaded},201),delivery={seq:1,sessionId:imported.sessionId,actions:[intent(imported.world,'deliver','workshop')]};current=await request(`/rooms/${imported.roomId}/sync`,delivery);assert.equal(current.world.townSupply.carried,0);assert.equal(current.world.townSupply.deliveries,1);assert.equal(current.world.townLife.resources.materials,loaded.townLife!.resources.materials+12);assert.deepEqual(current.world.inventory,loaded.inventory);assert.deepEqual((await request(`/rooms/${imported.roomId}/sync`,delivery)).world,current.world);assert(validateSave(current.world));
  const buildWorld={...current.world,player:{...current.world.player,x:WORKSHOP_BOARD.x,z:WORKSHOP_BOARD.z}},worker=buildWorld.townLife.residents.find((r:any)=>assignTownWorkshopWorker(buildWorld.townLife,r.id));assert(worker);const builtRoom=await request('/rooms',{name:'Supply funded construction',world:buildWorld},201),build={seq:1,sessionId:builtRoom.sessionId,actions:[{type:'workshop-construction',command:{kind:'build',expectedRevision:0,parcelId:WORKSHOP_PARCEL.id,parameters:{...DEFAULT_WORKSHOP_DRAFT},workerId:worker.id}}]};
  const paid=await request(`/rooms/${builtRoom.roomId}/sync`,build);assert(paid.world.workshopConstruction);assert.equal(paid.world.townLife.resources.materials,current.world.townLife.resources.materials-paid.world.workshopConstruction.materialsPaid);assert.deepEqual((await request(`/rooms/${builtRoom.roomId}/sync`,build)).world,paid.world);assert(validateSave(paid.world));
  for(const edit of [(v:any)=>v.townSupply.carried++,(v:any)=>v.townSupply.sources.pop(),(v:any)=>v.townLife.supplyDeliveries++,(v:any)=>v.inventory.scrap++]){const forged=structuredClone(paid.world);edit(forged);await request('/rooms',{name:'Forged supply import',world:forged},400);}
  await request(`/rooms/${imported.roomId}/sync`,{seq:2,sessionId:imported.sessionId,actions:[{...intent(current.world,'deliver','workshop'),carried:2}]},400);
  return {supply:paid.world.townSupply,construction:paid.world.workshopConstruction,materials:paid.world.townLife.resources.materials,supplyDeliveries:paid.world.townLife.supplyDeliveries,inventory:paid.world.inventory,collected:paid.world.collected,guestRejected:true,exactRetries:true,forgedImportsRejected:4,paidImport:true,previewOnlyBinding:true};
 }finally{Date.now=originalNow;db.close();}}
const sourceServer=await serverCase(false),emittedServer=await serverCase(true);assert.deepEqual(emittedServer,sourceServer);console.error('town supply emitted HTTP finite loading, delivery and construction passed');
const sourceFiles=['src/town-supply.ts','src/town-life.ts','src/workshop-construction.ts','src/world.ts','src/main.ts','server/coop-api.ts','server/coop-authority.ts','server/coop-validation.ts','server/index.ts'];
const report={kind:'axiom-town-supply-emitted-verification',version:1,verifiedAt:new Date().toISOString(),scope:'Actual emitted supply, town and construction model engines; seven finite canonical sources, cargo accounting, unchanged normal donations, construction material payment, source/emitted HTTP and disposable SQLite. No browser/GPU/device or live-save claim.',sourceHashes:Object.fromEntries(sourceFiles.map(file=>[file,digest(readFileSync(resolve(root,file),'utf8'))])),engines:[supplyAsset,townAsset,constructionAsset].map(({file,value,sha256})=>({kind:value.kind,file,sha256})),modelCases,server:{assetSha256:digest(readFileSync(resolve(root,'dist/server/index.js'),'utf8')),sha256:digest(emittedServer),...emittedServer}};
if(process.argv[2])writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
