import assert from 'node:assert/strict';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Worker} from 'node:worker_threads';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import {RESTORATION_ENGINE,RESTORATION_DEFAULTS,type RestorationCommand} from '../src/restoration.ts';
import {RESTORATION_VIEW_ENGINE} from '../src/restoration-view.ts';
import {restorationPracticeDescriptors,RESTORATION_PRACTICE_SPAWN,RestorationPractice} from '../src/restoration-practice.ts';
import {restorationBodyObstacle} from '../src/restoration-collision.ts';
import {RESTORATION_PARTS} from '../src/restoration-body.ts';
import {createRegionalState,enableRestoration,enableStartingTown,applyAction,worldRestorationPlan,validateSave} from '../src/world.ts';
import {startingTown} from '../src/starting-town.ts';
import {handleCoop} from '../server/coop-api.ts';
import {TOWN_DIRECTOR_ENGINE,TOWN_DIRECTOR_SCENARIOS,createTownDirectorScenario} from '../src/town-director.ts';
import {advanceTownLife} from '../src/town-life.ts';
const root=resolve(import.meta.dirname,'..'),assets=resolve(root,'dist/client/assets'),files=readdirSync(assets),digest=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
async function surface(prefix:string,kind:string){const found:{file:string;value:unknown;sha256:string}[]=[];for(const file of files.filter(f=>f.startsWith(prefix+'-')&&f.endsWith('.js')||/^(restoration-care-engine|campaign-guidance-engine)-.*\.js$/.test(f))){const module=await import(pathToFileURL(resolve(assets,file)).href);for(const value of Object.values(module))if((value as any)?.kind===kind)found.push({file,value,sha256:digest(readFileSync(resolve(assets,file),'utf8'))});}assert.equal(found.length,1,`exactly one actual emitted ${kind} surface`);return found[0]!;}
const emitted=await surface('restoration-engine','axiom-restoration'),engine=emitted.value as typeof RESTORATION_ENGINE,projection=await surface('restoration-view','axiom-restoration-view'),viewEngine=projection.value as typeof RESTORATION_VIEW_ENGINE;
const zero={waterMl:0,contaminant:0,energy:0,smoke:0,scent:0,organic:0,filter:0};
const scene=(root:any)=>{root.updateMatrixWorld(true);const out:any[]=[];root.traverse((o:any)=>{out.push({name:o.name,type:o.type,visible:o.visible,matrix:o.matrixWorld.toArray(),...(o.isMesh||o.isLine?{geometry:Array.from(o.geometry.attributes.position.array),color:Array.isArray(o.material)?o.material.map((m:any)=>m.color?.toArray()):o.material.color?.toArray()}:{ }),...(o.isInstancedMesh?{count:o.count,instances:Array.from(o.instanceMatrix.array),colors:o.instanceColor?Array.from(o.instanceColor.array):null}:{})});});return out;};
const modelCases:any[]=[],viewHashes:string[]=[];let viewFrames=0,bodyFrames=0;
for(const seed of [0,73129,0xffffffff])for(const organ of RESTORATION_PARTS.organ){
 const plan=RESTORATION_ENGINE.plan(seed,restorationPracticeDescriptors()),builtPlan=engine.plan(seed,restorationPracticeDescriptors());assert.deepEqual(builtPlan,plan);const site=plan.sites[0]!,player={x:site.x,z:site.z-2.5,hp:70};let source=RESTORATION_ENGINE.create(plan),built=engine.create(builtPlan),inventory={scrap:16,core:1,water:2};assert.deepEqual(built,source);
 const sourceView=RESTORATION_VIEW_ENGINE.create(plan),builtView=viewEngine.create(builtPlan);const hash=createHash('sha256');
 const command=(extra:Record<string,unknown>)=>{const c={targetId:site.id,...extra,expectedRevision:source.revision} as RestorationCommand,ctx={seed,zone:'valley',player,inventory};const a=RESTORATION_ENGINE.command(source,plan,ctx,c),b=engine.command(built,builtPlan,ctx,c);assert.deepEqual(b,a);source=a.state;built=b.state;inventory=a.inventory;assert(engine.commandValid(c));assert(engine.validate(built,builtPlan));assert.deepEqual(engine.balances(built,builtPlan),zero);};
 try{
  command({kind:'refit',recipe:{version:1,seed,support:'nimble',shell:'reed',organ},ability:{version:1,organ,strength:1,tempo:'steady'}});assert(source.machine);command({kind:'service'});command({kind:'deploy'});assert.equal(source.machine!.status,'idle');command({kind:'start',sourceId:site.cells[1]!.id,targetId:organ==='pump'?'tank':site.cells[1]!.id});assert.equal(source.machine!.status,'working');
  for(let n=0;n<80;n++){
   const context={player,actors:[{x:player.x,y:0,z:player.z}]};source=RESTORATION_ENGINE.advance(source,plan,.25,context,RESTORATION_DEFAULTS);built=engine.advance(built,builtPlan,.25,context,RESTORATION_DEFAULTS);assert.deepEqual(built,source);assert(engine.validate(JSON.parse(JSON.stringify(built)),builtPlan));assert.deepEqual(engine.balances(built,builtPlan),zero);assert.deepEqual(engine.machinePosition(built,builtPlan),RESTORATION_ENGINE.machinePosition(source,plan));hash.update(JSON.stringify(built));
   for(let frame=0;frame<3;frame++){const point=RESTORATION_ENGINE.machinePosition(source,plan),args=[source,player,()=>true,true,1/60,point] as const;sourceView.update(...args);builtView.update(built,player,()=>true,true,1/60,point);assert.deepEqual(scene(builtView.root),scene(sourceView.root));assert.deepEqual(builtView.stats,sourceView.stats);viewFrames++;}
  }
  assert(source.machine!.charge<100);command({kind:'stop'});const cost=engine.playerCost(built);assert.equal(inventory.scrap+cost.scrap,16);assert.equal(inventory.core+cost.core,1);const invalid=structuredClone(built);invalid.sites[0]!.cells[0]!.waterMl++;assert.equal(engine.validate(invalid,builtPlan),false);assert.equal(RESTORATION_ENGINE.validate(invalid,plan),false);modelCases.push({seed,organ,ticks:80,revision:built.revision,cost,sha256:hash.digest('hex')});viewHashes.push(digest(scene(builtView.root)));
 }finally{sourceView.dispose();builtView.dispose();}
}
for(const seed of [0,73129,0xffffffff])for(const support of RESTORATION_PARTS.support)for(const shell of RESTORATION_PARTS.shell)for(const organ of RESTORATION_PARTS.organ){const recipe={version:1 as const,seed,support,shell,organ},a=RESTORATION_VIEW_ENGINE.body(recipe),b=viewEngine.body(recipe);try{assert.deepEqual(b.plan,a.plan);for(let f=0;f<60;f++){const p={x:Math.sin(f/40),y:.25,z:Math.cos(f/40)},args=[p,'same-habitat',1/60,true] as const;a.update(...args);b.update(...args);assert.deepEqual(scene(b.root),scene(a.root));bodyFrames++;}}finally{a.dispose();b.dispose();}}

async function bridge(file:string){const worker=new Worker(`const{parentPort}=require('node:worker_threads');globalThis.self=globalThis;self.postMessage=m=>parentPort.postMessage(m);parentPort.on('message',m=>self.onmessage({data:m}));import(${JSON.stringify(pathToFileURL(file).href)}).then(()=>parentPort.postMessage({type:'boot'}));`,{eval:true,execArgv:['--experimental-strip-types']});const messages:any[]=[];let error:Error|undefined;worker.on('message',m=>{messages.push(m);if(m.type==='error')error=Error(m.message);});worker.on('error',e=>error=e);async function take(type:string,match:(m:any)=>boolean=()=>true){const until=Date.now()+20000;for(;;){if(error)throw error;const i=messages.findIndex(m=>m.type===type&&match(m));if(i>=0)return messages.splice(i,1)[0];assert(Date.now()<until,'Worker deadline '+type);await new Promise(r=>setTimeout(r,2));}}await take('boot');return {worker,take,messages,send:(m:unknown)=>worker.postMessage(m)};}
async function physical(file:string){const b=await bridge(file);try{
 const practice=new RestorationPractice(73129,'emitted-verification'),site=practice.plan.sites[0]!,player={x:site.x,z:site.z-2.5};for(const extra of [{kind:'refit',recipe:{version:1,seed:73129,support:'nimble',shell:'reed',organ:'filter'},ability:{version:1,organ:'filter',strength:1,tempo:'steady'}},{kind:'service'},{kind:'deploy'}])practice.command({targetId:site.id,...extra,expectedRevision:practice.state.revision} as RestorationCommand,player);
 b.send({type:'init',epoch:0,...RESTORATION_PRACTICE_SPAWN,obstacles:[],initialCells:[{key:'restoration-automaton',revision:1,obstacles:[restorationBodyObstacle(practice.state,practice.plan)!]}],bound:48,sandbox:true,startPaused:true,manual:true});await b.take('ready');const overlap={...restorationBodyObstacle(practice.state,practice.plan)!,x:RESTORATION_PRACTICE_SPAWN.x,z:RESTORATION_PRACTICE_SPAWN.z};b.send({type:'cell-load',epoch:0,key:'restoration-automaton',revision:2,obstacles:[overlap]});const rejected=await b.take('cell-rejected',m=>m.key==='restoration-automaton');assert.equal(rejected.reason,'player-overlap');assert.equal(rejected.loaded,true);const trace:any[]=[];
 async function tick(count:number,input?:{x:number;z:number}){if(input)b.send({type:'input',epoch:0,...input,paused:false});b.send({type:'step',epoch:0,ticks:count});await b.take('stepped');const frames=b.messages.filter(m=>m.type==='snapshot');b.messages.splice(0,b.messages.length,...b.messages.filter(m=>m.type!=='snapshot'));for(const f of frames){practice.step(f);trace.push({x:f.x,y:f.y,z:f.z,feetY:f.feetY,grounded:f.grounded,step:f.step,vx:f.vx,vz:f.vz});}return frames.at(-1);}
 const stopped=await tick(120,{x:0,z:1});assert(stopped.z<site.z-1.25);const retreat=await tick(30,{x:0,z:-1});assert(retreat.z<stopped.z-1);const again=await tick(120,{x:0,z:1});assert(Math.abs(again.z-stopped.z)<.03);await tick(25,{x:0,z:-1});const clear=await tick(15,{x:0,z:0});
 practice.command({kind:'start',targetId:site.cells[1]!.id,sourceId:site.cells[1]!.id,expectedRevision:practice.state.revision},clear);assert.equal(practice.state.machine!.status,'working');let revision=1,changed=0,previous=RESTORATION_ENGINE.machinePosition(practice.state,practice.plan)!;
 for(let i=0;i<12;i++){await tick(15);const point=RESTORATION_ENGINE.machinePosition(practice.state,practice.plan)!;if(point.x!==previous.x||point.z!==previous.z){b.send({type:'cell-load',epoch:0,key:'restoration-automaton',revision:++revision,obstacles:[restorationBodyObstacle(practice.state,practice.plan)!]});const ack=await b.take('cell-ack',m=>m.key==='restoration-automaton'&&m.revision===revision);assert.equal(ack.count,1);changed++;}previous=point;}
 assert(changed>=3);assert.equal(previous.x,site.cells[1]!.x);assert(practice.state.machine!.waste>0);assert.deepEqual(practice.report().balances,zero);return {trace,movingCollisionRevisions:changed,overlapRejectedAndRetried:true,restoration:practice.state};
 }finally{await b.worker.terminate();}}
const physicsFile=files.find(f=>/^physics\.worker-.*\.js$/.test(f));assert(physicsFile);const sourcePhysical=await physical(resolve(root,'src/physics.worker.ts')),builtPhysical=await physical(resolve(assets,physicsFile));assert.deepEqual(builtPhysical,sourcePhysical);

const builtServer=(await import(pathToFileURL(resolve(root,'dist/server/index.js')).href)).default;
async function serverCase(emitted:boolean){const db=new DatabaseSync(':memory:');for(const f of readdirSync(resolve(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(resolve(root,'drizzle',f),'utf8'));const DB={prepare(sql:string){let values:any[]=[];return {bind(...next:any[]){values=next;return this;},async first(){return db.prepare(sql).get(...values)??null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){const result=db.prepare(sql).run(...values);return {success:true,meta:{changes:Number(result.changes)}};}};}};let now=1900000000000;const originalNow=Date.now;Date.now=()=>now;
 async function request(path:string,body:unknown,expected=200,preview=true){const req=new Request('https://fixture.invalid/api/coop'+path,{method:'POST',headers:{Origin:'https://fixture.invalid','oai-authenticated-user-id':'restoration-build-host','Content-Type':'application/json'},body:JSON.stringify(body)});const response=emitted?await builtServer.fetch(req,preview?{AXIOM_PREVIEW_DB:DB}:{DB}):await handleCoop(req,preview?{DB}:{},now);assert.equal(response?.status,expected,await response?.clone().text());return await response!.json() as any;}
 try{
  let world=createRegionalState(73129);world={...world,player:{...world.player,...startingTown(73129).shops[0]!.entry}};world=applyAction(world,{type:'town-purchase',command:{offerId:'arrival-kit',expectedRevision:0}});assert.equal(world.inventory.scrap,3);world=enableRestoration(enableStartingTown(world));const site=worldRestorationPlan(world.seed).sites[0]!;world={...world,player:{x:site.x,z:site.z-2.5,hp:100}};
  const absent=await request('/rooms',{name:'Binding check',world},503,false);assert.equal(absent.error,'service_unavailable');for(const forge of [(v:any)=>v.inventory.scrap++,(v:any)=>v.restoration.tuning={...RESTORATION_DEFAULTS,machineSpeedPercent:150}]){const invalid=structuredClone(world);forge(invalid);const rejected=await request('/rooms',{name:'Forged import check',world:invalid},400);assert.equal(rejected.error,'invalid_world');}let current=await request('/rooms',{name:'Restoration source check',world},201),seq=0;const id=current.roomId,sessionId=current.sessionId;
  async function command(extra:Record<string,unknown>){const payload={seq:++seq,sessionId,actions:[{type:'restoration',command:{targetId:site.id,...extra,expectedRevision:current.world.restoration.revision}}]};current=await request(`/rooms/${id}/sync`,payload);assert(validateSave(current.world));const retry=await request(`/rooms/${id}/sync`,payload);assert.deepEqual(retry.world.restoration,current.world.restoration);assert.deepEqual(retry.world.inventory,current.world.inventory);return current;}
  await command({kind:'refit',recipe:{version:1,seed:73129,support:'nimble',shell:'reed',organ:'filter'},ability:{version:1,organ:'filter',strength:1,tempo:'steady'}});assert.equal(current.world.inventory.scrap,0);await command({kind:'service'});await command({kind:'deploy'});await command({kind:'start',sourceId:site.dockCellId,targetId:site.dockCellId});assert.equal(current.world.restoration.machine.status,'working');const revision=current.world.restoration.revision;
  for(let i=0;i<5;i++){now+=1000;current=await request(`/rooms/${id}/sync`,{seq:++seq,sessionId,actions:[]});}assert.equal(current.world.restoration.revision,revision);assert(current.world.restoration.machine.waste>0);assert(validateSave(current.world));assert.deepEqual(RESTORATION_ENGINE.balances(current.world.restoration,worldRestorationPlan(73129)),zero);const forged=await request(`/rooms/${id}/sync`,{seq:seq+1,sessionId,actions:[{type:'restoration',command:{kind:'service',targetId:site.id,expectedRevision:revision},state:current.world.restoration}]},400);assert(forged.error);
  return {inventory:current.world.inventory,restoration:current.world.restoration,previewOnlyBinding:true,repeatedPackets:'idempotent',forgedStateStatus:400};
 }finally{Date.now=originalNow;db.close();}}
const sourceServer=await serverCase(false),emittedServer=await serverCase(true);assert.deepEqual(emittedServer,sourceServer);

const directorAsset=await surface('town-director','axiom-town-director'),director=directorAsset.value as typeof TOWN_DIRECTOR_ENGINE;const directorCases:any[]=[];
for(const seed of [0,73129,0xffffffff])for(const descriptor of TOWN_DIRECTOR_SCENARIOS){let {life,director:source}=createTownDirectorScenario(seed,descriptor.id),built=director.create(life,source.tuning);assert.deepEqual(built,source);for(let n=0;n<20;n++){life=advanceTownLife(life,.5);source=TOWN_DIRECTOR_ENGINE.advance(source,life,.5);built=director.advance(built,life,.5);assert.deepEqual(built,source);assert(director.validate(built,life));assert.deepEqual(director.candidates(life),TOWN_DIRECTOR_ENGINE.candidates(life));}directorCases.push({seed,scenario:descriptor.id,sha256:digest(built)});}
const sourceFiles=['src/restoration.ts','src/restoration-plan.ts','src/restoration-body.ts','src/restoration-view.ts','src/restoration-practice.ts','src/restoration-collision.ts','src/habitat-motion.ts','src/physics.worker.ts','src/world.ts','src/town-director.ts','server/coop-api.ts','server/coop-authority.ts','server/coop-validation.ts','server/index.ts'];const sourceHashes=Object.fromEntries(sourceFiles.map(file=>[file,digest(readFileSync(resolve(root,file),'utf8'))]));
const report={kind:'axiom-restoration-emitted-verification',version:1,verifiedAt:new Date().toISOString(),sourceHashes,scope:'Actual built production restoration engine and view chunks; actual source/emitted Three object matrices and Rapier WASM workers; actual source/emitted HTTP authority with in-memory SQLite and preview-only binding. Numerical/Node evidence; no browser/GPU/device or live-state claim.',engine:{file:emitted.file,sha256:emitted.sha256,cases:modelCases},view:{file:projection.file,sha256:projection.sha256,fieldFrames:viewFrames,bodyFrames,fieldHashes:viewHashes},physics:{file:physicsFile,assetSha256:digest(readFileSync(resolve(assets,physicsFile),'utf8')),sha256:digest(builtPhysical),frames:builtPhysical.trace.length,movingCollisionRevisions:builtPhysical.movingCollisionRevisions,overlapRejectedAndRetried:builtPhysical.overlapRejectedAndRetried},server:{assetSha256:digest(readFileSync(resolve(root,'dist/server/index.js'),'utf8')),sha256:digest(sourceServer),inventory:sourceServer.inventory,revision:sourceServer.restoration.revision,filterWaste:sourceServer.restoration.machine.waste,previewOnlyBinding:true,forgedStateStatus:400},director:{file:directorAsset.file,sha256:directorAsset.sha256,cases:directorCases}};
if(process.argv[2])writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
