import assert from 'node:assert/strict';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Worker} from 'node:worker_threads';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import {TOWN_LIFE_ENGINE,TOWN_LIFE_DEFAULTS,townLifeFacilities,createTownLife,type TownLifeState} from '../src/town-life.ts';
import {townLifePoses} from '../src/town-life-runtime.ts';
import {createTownView} from '../src/town-view.ts';
import {generateRegionalChunk} from '../src/regional-world.ts';
import {createRegionalState,enableStartingTown,applyAction,validateSave} from '../src/world.ts';
import {startingTown,TOWN_CENTER} from '../src/starting-town.ts';
import {handleCoop} from '../server/coop-api.ts';
const root=resolve(import.meta.dirname,'..'),assets=resolve(root,'dist/client/assets'),files=readdirSync(assets);
// Rolldown may place the life authority in the shared director dependency chunk.
// Inspect the actual emitted surface, never a test-only substitute or a filename claim.
let file:string|undefined,engine:typeof TOWN_LIFE_ENGINE|undefined;
for(const candidate of files.filter(f=>/^(?:town-life|town-director|restoration-care-engine|campaign-guidance-engine)-.*\.js$/.test(f))){const module=await import(pathToFileURL(resolve(assets,candidate)).href),surface=Object.values(module).find((v:any)=>v?.kind==='axiom-town-life') as typeof TOWN_LIFE_ENGINE|undefined;if(surface){assert(!engine,'one emitted town-life authority');file=candidate;engine=surface;}}
assert(file&&engine?.create&&engine?.advance&&engine?.command,'the actual game ships the shared life authority');
const modelCases=[];for(const seed of [0,73129,0xffffffff])for(const scenario of ['balanced','lean-stores','urgent-needs']){
 let source=TOWN_LIFE_ENGINE.scenario(seed,scenario),built=engine.scenario(seed,scenario);assert.deepEqual(built,source);const hash=createHash('sha256');
 for(let n=0;n<8;n++){source=TOWN_LIFE_ENGINE.advance(source,15,TOWN_LIFE_DEFAULTS);built=engine.advance(built,15,TOWN_LIFE_DEFAULTS);assert.deepEqual(built,source);assert(engine.validate(built,seed));for(const index of [0,37,99]){assert.deepEqual(engine.pose(built,index),TOWN_LIFE_ENGINE.pose(source,index));assert.deepEqual(engine.summary(built,index),TOWN_LIFE_ENGINE.summary(source,index));}hash.update(JSON.stringify(built));}
 const target=townLifeFacilities(seed).find(f=>f.id==='well')!,command={kind:'donate-water' as const,targetId:'well',expectedRevision:source.revision},context={seed,zone:'valley',player:{x:target.x,z:target.z,hp:100},inventory:{scrap:4,core:0,water:2}};assert.deepEqual(engine.command(built,context,command),TOWN_LIFE_ENGINE.command(source,context,command));modelCases.push({seed,scenario,seconds:120,sha256:hash.digest('hex')});
}
const projection=files.find(f=>/^town-projection-.*\.js$/.test(f));assert(projection);const pm=await import(pathToFileURL(resolve(assets,projection)).href),factory=Object.values(pm).find(v=>typeof v==='function'&&v.toString().includes('hearthmere-residents')) as typeof createTownView;assert(factory);
const sourceView=createTownView(73129),builtView=factory(73129);const matrix=(view:typeof sourceView)=>view.root.children.map((p:any)=>({count:p.count,m:Array.from(p.instanceMatrix.array.slice(0,p.count*16))}));let poseComparisons=0;try{let life=createTownLife(73129);for(let n=0;n<5;n++){life=TOWN_LIFE_ENGINE.advance(life,20);for(let frame=0;frame<12;frame++){const args=[life.tick*.5,TOWN_CENTER,()=>true,true,undefined,frame===0,1/60,[],false,townLifePoses(life)] as const;sourceView.update(...args);builtView.update(...args);assert.deepEqual(builtView.poses,sourceView.poses);assert.deepEqual(matrix(builtView),matrix(sourceView));poseComparisons++;}}}finally{sourceView.dispose();builtView.dispose();}
async function bridge(file:string){const worker=new Worker(`const{parentPort}=require('node:worker_threads');globalThis.self=globalThis;globalThis.setInterval=()=>0;self.postMessage=m=>parentPort.postMessage(m);parentPort.on('message',m=>self.onmessage({data:m}));import(${JSON.stringify(pathToFileURL(file).href)}).then(()=>parentPort.postMessage({type:'boot'}));`,{eval:true,execArgv:['--experimental-strip-types']});const messages:any[]=[];let error:Error|undefined;worker.on('message',m=>{messages.push(m);if(m.type==='error')error=Error(m.message);});worker.on('error',e=>error=e);async function take(type:string){const until=Date.now()+20000;for(;;){if(error)throw error;const i=messages.findIndex(m=>m.type===type);if(i>=0)return messages.splice(i,1)[0];assert(Date.now()<until,'Worker deadline '+type);await new Promise(r=>setTimeout(r,2));}}await take('boot');return {worker,take,messages,send:(m:unknown)=>worker.postMessage(m)};}
const chunks=[];for(let cz=-4;cz<=-2;cz++)for(let cx=-4;cx<=-2;cx++)chunks.push(generateRegionalChunk(73129,cx,cz));const cells=chunks.map(c=>({key:'region:'+c.key,revision:1,bounds:c.bounds,terrain:c.terrain,obstacles:[...c.structures.filter(s=>s.solid).map(s=>({x:s.center.x,y:s.center.y,z:s.center.z,hx:s.half.x,hy:s.half.y,hz:s.half.z})),...c.features.flatMap(f=>f.solids)]}));
async function physical(file:string){const b=await bridge(file);try{const life=createTownLife(73129),p=life.residents[0]!;b.send({type:'init',epoch:0,x:p.x-2,z:p.z,y:6,obstacles:[],initialCells:cells,streamedTerrain:true,bound:Math.sqrt(10000000)/2,startPaused:true,manual:true,town:{seed:73129,time:0,selfId:'solo',actors:[],lifePoses:townLifePoses(life)}});await b.take('ready');b.send({type:'input',epoch:0,x:1,z:0,paused:false});b.send({type:'step',epoch:0,ticks:120});await b.take('stepped');const trace=b.messages.filter(m=>m.type==='snapshot').map(({x,z,feetY,step,town})=>({x,z,feetY,step,town}));assert(trace.length>100);assert(trace.every(p=>p.town.source==='life'));const later=TOWN_LIFE_ENGINE.advance(life,30);b.send({type:'input',epoch:0,x:0,z:0,paused:false,townTime:0,townLifePoses:townLifePoses(later)});b.send({type:'step',epoch:0,ticks:10});await b.take('stepped');const final=b.messages.filter(m=>m.type==='snapshot').at(-1);return {trace,final:{x:final.x,z:final.z,feetY:final.feetY,step:final.step,town:final.town}};}finally{await b.worker.terminate();}}
const physicsFile=files.find(f=>/^physics\.worker-.*\.js$/.test(f));assert(physicsFile);const sourcePhysical=await physical(resolve(root,'src/physics.worker.ts')),builtPhysical=await physical(resolve(assets,physicsFile));assert.deepEqual(builtPhysical,sourcePhysical);
const builtServer=(await import(pathToFileURL(resolve(root,'dist/server/index.js')).href)).default;
async function serverCase(emitted:boolean){const db=new DatabaseSync(':memory:');for(const f of readdirSync(resolve(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(resolve(root,'drizzle',f),'utf8'));const DB={prepare(sql:string){let values:any[]=[];return {bind(...next:any[]){values=next;return this;},async first(){return db.prepare(sql).get(...values)??null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){const result=db.prepare(sql).run(...values);return {success:true,meta:{changes:Number(result.changes)}};}};}};async function request(path:string,body:unknown){const req=new Request('https://fixture.invalid/api/coop'+path,{method:'POST',headers:{Origin:'https://fixture.invalid','oai-authenticated-user-id':'life-build-host','Content-Type':'application/json'},body:JSON.stringify(body)});const response=emitted?await builtServer.fetch(req,{AXIOM_PREVIEW_DB:DB}):await handleCoop(req,{DB},Date.now());assert(response?.ok);return await response.json() as any;}
 try{let world=createRegionalState(73129);world={...world,player:{...world.player,...startingTown(73129).shops[0]!.entry}};world=applyAction(world,{type:'town-purchase',command:{offerId:'arrival-kit',expectedRevision:0}});world=enableStartingTown(world);const well=townLifeFacilities(73129).find(f=>f.id==='well')!;world={...world,player:{x:well.x,z:well.z,hp:100}};const first=await request('/rooms',{name:'Life source check',world}),payload={seq:1,sessionId:first.sessionId,actions:[{type:'town-life',command:{kind:'donate-water',targetId:'well',expectedRevision:first.world.townLife.revision}}]},next=await request(`/rooms/${first.roomId}/sync`,payload),retry=await request(`/rooms/${first.roomId}/sync`,payload);assert(validateSave(next.world));assert.equal(next.world.townLife.playerSpent.water,1);assert.equal(retry.world.townLife.playerSpent.water,1);assert.equal(next.world.townLife.revision,1);return {inventory:next.world.inventory,spent:next.world.townLife.playerSpent,revision:next.world.townLife.revision};}finally{db.close();}}
const sourceServer=await serverCase(false),emittedServer=await serverCase(true);assert.deepEqual(emittedServer,sourceServer);
const report={kind:'axiom-town-life-emitted-verification',scope:'Local actual production engine, pose matrices, Rapier WASM worker and in-memory SQLite server. No browser/GPU/device/production-state probe.',file,modelCases,poseComparisons,physics:{file:physicsFile,matchingFrames:sourcePhysical.trace.length+10,sha256:createHash('sha256').update(JSON.stringify(sourcePhysical)).digest('hex')},server:sourceServer};if(process.argv[2])writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
