import assert from 'node:assert/strict';
import {readFileSync,readdirSync,statSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve,dirname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {applyAction,validateSave,parseSave,createRegionalState,enableRegionalSupply,enableRegionalTrade,enableRegionalFood} from '../src/world.ts';
import {regionalTradePlan,regionalTradeReplayTimeline,regionalTradeDrainTicks,REGIONAL_TRADE_MAX_TICKS} from '../src/regional-trade.ts';
import {foodHttpFixture,foodExpedition,foodInput,foodCurrent} from '../tests/helpers/regional-food-http.ts';
import {readyFoodCampaign,foodCommand} from '../tests/helpers/regional-food-campaign.ts';
const root=resolve(import.meta.dirname,'..'),workerPath=resolve(root,'dist/server/index.js'),worker=(await import(pathToFileURL(workerPath).href)).default;
assert.equal(typeof worker.fetch,'function');
const f=await foodHttpFixture((request,env)=>worker.fetch(request,env)),originalNow=Date.now;Date.now=()=>f.time();
const checks:string[]=[];
try{
 const clientAssets:{path:string;bytes:number;sha256:string}[]=[];
 async function verifyAssets(folder:string,relative=''){for(const entry of readdirSync(folder,{withFileTypes:true})){const path=resolve(folder,entry.name),url=relative+'/'+entry.name;if(entry.isDirectory())await verifyAssets(path,url);else if(entry.isFile()){const bytes=readFileSync(path),hash=createHash('sha256').update(bytes).digest('hex'),response=await worker.fetch(new Request('https://fixture.invalid'+url),{});assert.equal(response.status,200,url);assert.deepEqual(Buffer.from(await response.arrayBuffer()),bytes,url);assert.equal(response.headers.get('etag'),'"'+hash+'"');clientAssets.push({path:url,bytes:bytes.length,sha256:hash});}}}
 await verifyAssets(resolve(root,'dist/client'));assert(clientAssets.some(a=>a.path==='/index.html'));checks.push('Every built client asset is served byte-for-byte by the compiled Worker');
 let world=readyFoodCampaign(),peers=await foodExpedition(f,world),host=peers[0]!,id=host.s.roomId;
 const command=foodCommand(host.s.world),expected=applyAction(host.s.world,command),hold=f.hold(),pending=foodInput(f,peers[1]!,[command]);await hold.waiting;try{await foodInput(f,host,[command]);}finally{hold.release();}await pending;await Promise.all(peers.slice(2).map(p=>foodInput(f,p,[command])));await Promise.all(peers.map(p=>foodCurrent(f,p)));assert(f.conflicts()>0);
 for(const p of peers){assert.deepEqual(p.s.world.frontierFood,expected.frontierFood);assert.deepEqual(p.s.world.frontierSupply,world.frontierSupply);assert.deepEqual(p.s.world.frontierTrade,world.frontierTrade);assert.deepEqual(p.s.world.inventory,world.inventory);assert(validateSave(p.s.world));}
 checks.push('Compiled Worker actual TCP HTTP with trusted platform identity','Four-player farm-start SQLite CAS race commits once','Unchanged drinking water, finite freight and inventory ledgers');
 const replay=await f.raw(host.user,`/rooms/${id}/sync`,{seq:host.s.ack,sessionId:host.s.sessionId,actions:[command]});assert.equal(replay.status,200);assert.deepEqual(replay.body.world.frontierFood,expected.frontierFood);checks.push('Lost-response sequence replay cannot reset farm or duplicate food');
 const tickExpected=applyAction(host.s.world,{type:'tick',dt:1});f.advance(1000);await Promise.all(peers.map(p=>foodInput(f,p)));await Promise.all(peers.map(p=>foodCurrent(f,p)));for(const p of peers){assert.deepEqual(p.s.world.frontierFood,tickExpected.frontierFood);assert.deepEqual(p.s.world.frontierSupply,tickExpected.frontierSupply);assert(validateSave(p.s.world));}checks.push('Single accepted active room dt across four polls');
 const food=structuredClone(host.s.world.frontierFood);await f.raw(host.user,`/rooms/${id}/leave`,{sessionId:host.s.sessionId});f.advance(3_600_000);await foodInput(f,peers[1]!);assert(peers[1]!.s.paused);assert.deepEqual(peers[1]!.s.world.frontierFood,food);const resume=await f.raw(host.user,`/rooms/${id}/resume`,{});assert.equal(resume.status,200);assert.deepEqual(resume.body.world.frontierFood,food);checks.push('Host absence and resume never catch up or refill food');
 assert.equal((await f.raw('unrelated',`/rooms/${id}`)).status,404);assert.equal((await f.raw('',`/rooms/${id}`)).status,401);checks.push('Unrelated and unauthenticated accounts denied');
 for(const field of ['water','cargo','meals','stewardship','userId'])assert.equal((await f.raw(host.user,`/rooms/${id}/sync`,{seq:resume.body.ack+1,sessionId:resume.body.sessionId,actions:[{...command,command:{...command.command,[field]:100}}]})).status,400);checks.push('Food, water, reward, cargo and actor injection rejected');
 const invalid=structuredClone(world);invalid.frontierSupply!.outposts[0]!.spilled++;assert.equal((await f.raw('bad-import','/rooms',{name:'Bad',world:invalid})).status,400);checks.push('Forged external collector water fails compiled import validation');
 world=applyAction(readyFoodCampaign(),foodCommand(readyFoodCampaign()));let tendFound=false;for(let i=0;i<1800;i++){if(applyAction(world,foodCommand(world,'tend-crop'))!==world){tendFound=true;break;}world=applyAction(world,{type:'tick',dt:.25});}assert(tendFound);
 peers=await foodExpedition(f,world);host=peers[0]!;const tend=foodCommand(host.s.world,'tend-crop'),tended=applyAction(host.s.world,tend),tendHold=f.hold(),tendPending=foodInput(f,peers[1]!,[tend]);await tendHold.waiting;try{await foodInput(f,host,[tend]);}finally{tendHold.release();}await tendPending;await Promise.all(peers.slice(2).map(p=>foodInput(f,p,[tend])));await Promise.all(peers.map(p=>foodCurrent(f,p)));for(const p of peers){assert.deepEqual(p.s.world.frontierFood,tended.frontierFood);assert.deepEqual(p.s.world.frontierSupply,world.frontierSupply);assert.deepEqual(p.s.world.frontierTrade,world.frontierTrade);assert(validateSave(p.s.world));}await foodInput(f,host,[foodCommand(host.s.world,'tend-crop')]);assert.deepEqual(host.s.world.frontierFood,tended.frontierFood);checks.push('Compiled four-player useful-tend CAS race pays stewardship once per crop');
 const stored=f.stored(host.s.roomId);stored.world.frontierFood!.farms[0]!.cargo++;f.replace(stored);assert.equal((await f.raw(host.user,`/rooms/${host.s.roomId}`)).status,503);assert.equal((await f.raw(host.user,`/rooms/${host.s.roomId}/resume`,{})).status,503);assert.deepEqual(f.stored(host.s.roomId),stored);checks.push('Malformed stored food cannot be silently reset by read or resume');
 let witnessWorld=enableRegionalFood(enableRegionalTrade(enableRegionalSupply(createRegionalState(42))));const witnessSource=regionalTradePlan(42).sources[0]!;witnessWorld={...witnessWorld,player:{...witnessWorld.player,x:witnessSource.interactionPosition.x,z:witnessSource.interactionPosition.z}};
 const witnessPeers=await foodExpedition(f,witnessWorld),wh=witnessPeers[0]!,tradeCommand={type:'regional-trade' as const,command:{type:'start-source' as const,targetId:witnessSource.id,expectedRevision:0}},witnessExpected=applyAction(wh.s.world,tradeCommand),witnessHold=f.hold(),witnessPending=foodInput(f,witnessPeers[1]!,[tradeCommand]);await witnessHold.waiting;try{await foodInput(f,wh,[tradeCommand]);}finally{witnessHold.release();}await witnessPending;await Promise.all(witnessPeers.slice(2).map(p=>foodInput(f,p,[tradeCommand])));await Promise.all(witnessPeers.map(p=>foodCurrent(f,p)));for(const p of witnessPeers){assert.deepEqual(p.s.world.frontierFood,witnessExpected.frontierFood);assert.equal(p.s.world.frontierFood!.tradeEvents.length,1);assert.deepEqual(p.s.world.frontierFood!.tradeSnapshot,p.s.world.frontierTrade);assert.equal(p.s.world.frontierFood!.ticks,0);assert.equal(p.s.world.frontierFood!.revision,0);assert(validateSave(p.s.world));}const witnessReplay=await f.raw(wh.user,`/rooms/${wh.s.roomId}/sync`,{seq:wh.s.ack,sessionId:wh.s.sessionId,actions:[tradeCommand]});assert.equal(witnessReplay.status,200);assert.deepEqual(witnessReplay.body.world.frontierFood,witnessExpected.frontierFood);checks.push('Compiled four-player V32 command atomically adds one V33 temporal witness across CAS and replay');
 const futureWitness=structuredClone(wh.s.world);futureWitness.frontierFood!.tradeEvents[0]!.ticks=1;assert.equal((await f.raw('future-witness','/rooms',{name:'Future witness',world:futureWitness})).status,400);checks.push('Compiled temporal witness cannot claim a future accepted action');
 let terminal=enableRegionalTrade(enableRegionalSupply(createRegionalState(42))),terminalSupply=structuredClone(terminal.frontierSupply!);terminalSupply.ticks=REGIONAL_TRADE_MAX_TICKS;for(const o of terminalSupply.outposts)for(const resident of o.residents){resident.thirst=100;resident.thirstOverflow=60+terminalSupply.ticks*.03-100;}terminal=parseSave(JSON.stringify({...terminal,frontierSupply:terminalSupply}))!;assert(terminal);terminal=enableRegionalFood(terminal);const frozenFood=structuredClone(terminal.frontierFood!);frozenFood.ticks=REGIONAL_TRADE_MAX_TICKS;for(const farm of frozenFood.farms)for(const resident of [farm.farmer,farm.carrier]){resident.hunger=100;resident.hungerOverflow=Math.floor(frozenFood.ticks/12)-40;}frozenFood.tradeEvents=[{type:'rebase',ticks:REGIONAL_TRADE_MAX_TICKS-regionalTradeDrainTicks(42),remainder:0}];frozenFood.tradeSnapshot=regionalTradeReplayTimeline(frozenFood.tradeBaseline,frozenFood.tradeEvents,{ticks:frozenFood.ticks,remainder:0})!;assert(frozenFood.tradeSnapshot);terminal=parseSave(JSON.stringify({...terminal,frontierTrade:frozenFood.tradeSnapshot,frontierFood:frozenFood}))!;assert(terminal);terminal={...terminal,player:{...terminal.player,x:witnessSource.interactionPosition.x,z:witnessSource.interactionPosition.z}};const [terminalHost]=await foodExpedition(f,terminal,1);assert(terminalHost);await foodInput(f,terminalHost,[tradeCommand]);assert.equal(terminalHost.s.world.frontierTrade!.revision,1);assert.deepEqual(terminalHost.s.world.frontierFood,frozenFood);f.advance(1000);await foodInput(f,terminalHost);assert.deepEqual(terminalHost.s.world.frontierFood,frozenFood);assert(validateSave(terminalHost.s.world));checks.push('Compiled terminal food remains frozen and saveable while normal freight continues');
 const report={version:1,status:'verified',scope:'Built ESM production Worker over actual TCP HTTP and real SQLite CAS. Disposable worlds only; no browser, visual, device, production Site or internet multiplayer claim.',runtime:process.version,workerBytes:statSync(workerPath).size,workerSha256:createHash('sha256').update(readFileSync(workerPath)).digest('hex'),players:4,casConflicts:f.conflicts(),clientAssets,sourceSha256:Object.fromEntries(['src/world.ts','src/session.ts','src/coop.ts','src/regional-food.ts','src/regional-supply.ts','src/regional-trade.ts','src/regional-clock.ts','server/coop-api.ts','server/coop-authority.ts','server/coop-validation.ts'].map(file=>[file,createHash('sha256').update(readFileSync(resolve(root,file))).digest('hex')])),checks};
 const path=process.argv[2]?resolve(process.argv[2]):resolve(root,'evidence/regional-food-compiled-build.json');mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{Date.now=originalNow;await f.stop();}
