import assert from 'node:assert/strict';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {CAMPAIGN_GUIDANCE_ENGINE} from '../src/campaign-guidance.ts';
import {CAMPAIGN_GUIDANCE_SCENARIO_ENGINE,type CampaignGuidanceScenario} from '../src/campaign-guidance-scenarios.ts';
import {parseSave,serializeSave,validateSave} from '../src/world.ts';
const root=resolve(import.meta.dirname,'..'),assets=resolve(root,'dist/client/assets'),digest=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const modules=await Promise.all(readdirSync(assets).filter(f=>/^(campaign-guidance-engine|campaign-guidance-scenarios|restoration-care-engine|town-supply-engine|town-life|town-director|workshop-construction-engine|restoration-engine)-.*\.js$/.test(f)).map(async file=>({file,module:await import(pathToFileURL(resolve(assets,file)).href),sha256:digest(readFileSync(resolve(assets,file),'utf8'))})));
function surface<T>(kind:string){const found=modules.flatMap(m=>Object.values(m.module).filter((v:any)=>v?.kind===kind).map(value=>({file:m.file,value:value as T,sha256:m.sha256})));assert.equal(found.length,1,`one actual emitted ${kind} engine`);return found[0]!;}
const guidanceAsset=surface<typeof CAMPAIGN_GUIDANCE_ENGINE>('axiom-campaign-guidance'),scenarioAsset=surface<typeof CAMPAIGN_GUIDANCE_SCENARIO_ENGINE>('axiom-campaign-guidance-scenarios'),guidance=guidanceAsset.value,scenarios=scenarioAsset.value,cases:any[]=[];
for(const seed of [0,73129,0xffffffff])for(const scenario of ['opening','supply-to-workshop','care-delivered','workshop-complete'] as CampaignGuidanceScenario[]){
 let source=CAMPAIGN_GUIDANCE_SCENARIO_ENGINE.create(seed,scenario),built=scenarios.create(seed,scenario);assert.deepEqual(built,source);const initialHash=digest(source),before=JSON.stringify(source);
 function compare(){for(const host of [true,false]){const a=CAMPAIGN_GUIDANCE_ENGINE.project(source.state,{host}),b=guidance.project(built.state,{host});assert.deepEqual(b,a);assert.equal(a.length,6);assert.equal(new Set(a.map(c=>c.id)).size,6);assert.deepEqual(guidance.project(JSON.parse(JSON.stringify(built.state)),{host}),b);for(const c of b)if(c.target)assert.deepEqual(guidance.direction(built.state.player,c.target),CAMPAIGN_GUIDANCE_ENGINE.direction(source.state.player,c.target));}assert.deepEqual(built,source);}
 compare();assert.equal(JSON.stringify(source),before,'guidance cannot change its source scenario');
 if(scenario!=='care-delivered'){assert(validateSave(source.state),'canonical finite supply/construction fixture remains a valid campaign save');assert.deepEqual(parseSave(serializeSave(source.state)),source.state);}
 if(scenario==='opening'){assert.equal(source.state.townLife!.resources.materials,0);assert.equal(guidance.project(built.state).find(c=>c.id==='construction')!.status,'blocked');}
 if(scenario==='supply-to-workshop'){
  assert.equal(source.state.townSupply!.deliveries,3);assert.equal(source.state.townLife!.ledger.donated.materials,36);assert.equal(source.state.workshopConstruction!.materialsPaid,31);assert.equal(source.state.workshopConstruction!.work,0);assert.equal(guidance.project(built.state).find(c=>c.id==='construction')!.status,'waiting');
  for(let i=0;i<20&&source.state.workshopConstruction!.status!=='complete';i++){source=CAMPAIGN_GUIDANCE_SCENARIO_ENGINE.step(source,20);built=scenarios.step(built,20);compare();assert(validateSave(source.state));}
  assert.equal(source.state.workshopConstruction!.status,'complete');assert.equal(source.state.workshopConstruction!.work,source.state.workshopConstruction!.workRequired);const stock=source.state.townLife!.resources.materials,paid=source.state.workshopConstruction!.materialsPaid;
  source=CAMPAIGN_GUIDANCE_SCENARIO_ENGINE.act(source,'repair');built=scenarios.act(built,'repair');compare();assert.equal(source.state.player.hp,100);assert.equal(source.state.townLife!.resources.materials,stock-4);assert.equal(source.state.workshopConstruction!.materialsPaid,paid+4);assert.equal(guidance.project(built.state).find(c=>c.id==='construction')!.status,'complete');assert(validateSave(source.state));assert.deepEqual(parseSave(serializeSave(source.state)),source.state);
 }
 if(scenario==='workshop-complete'){assert.equal(source.state.player.hp,100);assert.equal(source.state.workshopConstruction!.repairs,1);assert.equal(source.state.townSupply!.unloaded,1);assert.equal(source.state.inventory.scrap,1);assert.equal(guidance.project(built.state).find(c=>c.id==='supply')!.status,'complete');}
 if(scenario==='care-delivered'){assert.equal(source.state.restorationCare!.delivered,5);assert.equal(source.state.townLife!.habitatCare!.stock,5);assert.equal(guidance.project(built.state).find(c=>c.id==='care')!.status,'waiting');source=CAMPAIGN_GUIDANCE_SCENARIO_ENGINE.step(source,60);built=scenarios.step(built,60);compare();}
 cases.push({seed,scenario,initialSha256:initialHash,finalSha256:digest(source),preparationSeconds:source.preparationSeconds,manualSeconds:source.elapsed,preparedCommands:source.preparation.length,finiteSupply:source.state.townSupply,construction:source.state.workshopConstruction,care:source.state.restorationCare,clinic:source.state.townLife?.habitatCare,ordinaryInventory:source.state.inventory,hp:source.state.player.hp,materials:source.state.townLife?.resources.materials,guidance:guidance.project(built.state),canonicalSaveChecked:scenario!=='care-delivered'});console.error(`emitted guidance and earned rehearsal passed ${seed}/${scenario}`);
}
const sourceFiles=['src/campaign-guidance.ts','src/campaign-guidance-scenarios.ts','src/campaign-guidance-storage.ts','src/campaign-guidance-ui.ts','src/campaign-guidance-lab.ts','src/campaign-guidance-map.ts','src/main.ts','src/world-map-view.ts'];
const report={kind:'axiom-campaign-guidance-emitted-verification',version:1,verifiedAt:new Date().toISOString(),scope:'Actual emitted read-only guidance and earned scenario engines, source parity, canonical finite supply/construction save roundtrips, achieved worker progress and paid repairs. Care preparation uses its declared finite disposable fixture, not an importable campaign save. No browser/GPU/device or full main startup claim.',sourceHashes:Object.fromEntries(sourceFiles.map(f=>[f,digest(readFileSync(resolve(root,f),'utf8'))])),engines:[guidanceAsset,scenarioAsset].map(({file,value,sha256})=>({kind:value.kind,file,sha256})),cases};
if(process.argv[2])writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
