/** Node-only actual emitted controller and rig replay; never a browser/GPU check. */
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const folder=resolve('dist/client/assets'),files=readdirSync(folder),worker=files.find(f=>/^physics\.worker-.*\.js$/.test(f));assert(worker);
const avatarFile=files.find(f=>/^guard-view-.*\.js$/.test(f));assert(avatarFile);const module=await import(pathToFileURL(resolve(folder,avatarFile)).href);
const avatar=Object.entries(module).find(([,value])=>typeof value==='function'&&value.toString().includes('avatarRoot')&&value.toString().includes('getPoseEvidence'));assert(avatar,'discover actual emitted avatar factory');
const result=spawnSync(process.execPath,['--experimental-strip-types','--test','tests/town-contact-extension.test.ts'],{encoding:'utf8',env:{...process.env,AXIOM_CONTACT_WORKER:pathToFileURL(resolve(folder,worker)).href,AXIOM_CONTACT_AVATAR:pathToFileURL(resolve(folder,avatarFile)).href,AXIOM_CONTACT_AVATAR_EXPORT:avatar[0]},maxBuffer:10_000_000});
const output=process.argv[2]??'evidence/town-contact/emitted-contact.json';writeFileSync(output+'.tap',result.stdout+result.stderr);assert.equal(result.status,0,'emitted worker and rig tests: '+result.stdout+result.stderr);assert.match(result.stdout,/# skipped 0/);assert.match(result.stdout,/# cancelled 0/);
const hash=(file:string)=>createHash('sha256').update(readFileSync(file)).digest('hex');const report={kind:'axiom-town-contact-emitted',scope:'Actual emitted Rapier worker and Three rig; source main course harness and save model. No browser/GPU/device or shared traversal claim.',worker:{file:worker,sha256:hash(resolve(folder,worker))},avatar:{file:avatarFile,export:avatar[0],sha256:hash(resolve(folder,avatarFile))},tests:Number(result.stdout.match(/^# tests (\d+)$/m)?.[1]),pass:Number(result.stdout.match(/^# pass (\d+)$/m)?.[1]),fail:0,skipped:0,cancelled:0};writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
