import assert from 'node:assert/strict';
import {readFileSync,readdirSync,statSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import {createRegionalState,enableRegionalSupply,enableRegionalTrade,applyAction,validateSave} from '../src/world.ts';
import {advanceRegionalTrade,regionalTradeCommandPosition,regionalTradePlan,regionalTradeWithdrawn,type RegionalTradeCommand} from '../src/regional-trade.ts';
import {regionalSupplyPlan,regionalSupplyAvailable} from '../src/regional-supply.ts';

/** Calls the built ESM Worker and real SQLite. No browser, network, production
 * URL, deployment, or visual claim. Only the server's test clock is controlled. */
const root=resolve(import.meta.dirname,'..'),workerPath=resolve(root,'dist/server/index.js'),worker=(await import(pathToFileURL(workerPath).href)).default;
assert.equal(typeof worker.fetch,'function');
const sqlite=new DatabaseSync(':memory:');for(const file of readdirSync(resolve(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync(resolve(root,'drizzle',file),'utf8'));
let conflicts=0,pause:undefined|{arrived:()=>void;gate:Promise<void>};
const DB={prepare(sql:string){let values:any[]=[];return {bind(...next:any[]){values=next;return this;},async first(){return sqlite.prepare(sql).get(...values)??null;},async all(){return {results:sqlite.prepare(sql).all(...values)};},async run(){if(sql.startsWith('UPDATE axiom_coop_rooms')&&pause){const p=pause;pause=undefined;p.arrived();await p.gate;}const result=sqlite.prepare(sql).run(...values),changes=Number(result.changes);if(sql.startsWith('UPDATE axiom_coop_rooms')&&!changes)conflicts++;return {success:true,meta:{changes}};}};}};
async function request(path:string,body?:unknown,user='trade-build-host'){
 const response=await worker.fetch(new Request('https://fixture.invalid/api/coop'+path,{method:body===undefined?'GET':'POST',headers:{Origin:'https://fixture.invalid','oai-authenticated-user-id':user,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})}),{DB});return {status:response.status,body:await response.json() as any};
}
const originalNow=Date.now;let now=1_800_000_000_000;Date.now=()=>now;
try{
 let world=enableRegionalTrade(enableRegionalSupply(createRegionalState(73129)));const source=regionalTradePlan(world.seed).sources[0]!;world={...world,player:{...world.player,x:source.interactionPosition.x,z:source.interactionPosition.z}};
 const created=await request('/rooms',{name:'Compiled freight',world});assert.equal(created.status,201,JSON.stringify(created.body));const peers=[{user:'trade-build-host',snapshot:created.body}];
 for(let i=1;i<4;i++){const user=`trade-build-guest-${i}`,joined=await request('/join',{name:`Guest ${i}`,code:created.body.code},user);assert.equal(joined.status,200);peers.push({user,snapshot:joined.body});}
 const host=peers[0]!,id=host.snapshot.roomId,command={type:'regional-trade' as const,command:{type:'start-source' as const,targetId:source.id,expectedRevision:0}},expected=applyAction(host.snapshot.world,command);
 async function sync(peer:typeof host,actions:any[]=[]){const result=await request(`/rooms/${id}/sync`,{seq:peer.snapshot.ack+1,sessionId:peer.snapshot.sessionId,actions},peer.user);assert.equal(result.status,200,JSON.stringify(result.body));peer.snapshot=result.body;return result.body;}
 let release=()=>{},arrived=()=>{};const gate=new Promise<void>(r=>release=r),waiting=new Promise<void>(r=>arrived=r);pause={gate,arrived};const pending=sync(peers[1]!,[command]);await waiting;try{await sync(host,[command]);}finally{release();}await pending;await Promise.all(peers.slice(2).map(p=>sync(p,[command])));assert(conflicts>0);
 for(const peer of peers){const result=await request(`/rooms/${id}`,undefined,peer.user);assert.equal(result.status,200);peer.snapshot=result.body;assert.deepEqual(result.body.world.frontierTrade,expected.frontierTrade);assert.deepEqual(result.body.world.frontierSupply,world.frontierSupply);assert.deepEqual(result.body.world.wilderness,world.wilderness);assert(validateSave(result.body.world));}
 const replay=await request(`/rooms/${id}/sync`,{seq:host.snapshot.ack,sessionId:host.snapshot.sessionId,actions:[command]});assert.equal(replay.status,200);assert.deepEqual(replay.body.world.frontierTrade,expected.frontierTrade);
 now+=1000;const tickExpected=applyAction(host.snapshot.world,{type:'tick',dt:1});await Promise.all(peers.map(p=>sync(p)));for(const p of peers)assert.deepEqual(p.snapshot.world.frontierTrade,tickExpected.frontierTrade);
 const leave=await request(`/rooms/${id}/leave`,{sessionId:host.snapshot.sessionId});assert.equal(leave.status,200);now+=3_600_000;await sync(peers[1]!);assert(peers[1]!.snapshot.paused);assert.deepEqual(peers[1]!.snapshot.world.frontierTrade,tickExpected.frontierTrade);
 const resume=await request(`/rooms/${id}/resume`,{});assert.equal(resume.status,200);assert.deepEqual(resume.body.world.frontierTrade,tickExpected.frontierTrade);
 assert.equal((await request(`/rooms/${id}`,undefined,'unrelated-user')).status,404);
 const invalid={...world,frontierTrade:{...world.frontierTrade,remaining:123}};assert.equal((await request('/rooms',{name:'Invalid',world:invalid},'bad-import')).status,400);
 // A second compiled room starts with model-earned completed finite sources.
 let reserve=enableRegionalTrade(enableRegionalSupply(createRegionalState(73129)));
 function perform(type:RegionalTradeCommand['type'],index:number){const p=regionalTradePlan(reserve.seed),targetId=(type==='start-source'?p.sources:type==='clear-route'?p.routes:p.projects)[index]!.id,c={type,targetId,expectedRevision:reserve.frontierTrade!.revision},position=regionalTradeCommandPosition(reserve.seed,c)!;reserve={...reserve,player:{...reserve.player,x:position.x,z:position.z}};reserve=applyAction(reserve,{type:'regional-trade',command:c});}
 for(const index of [0,1]){perform('start-source',index);perform('clear-route',index);const p=regionalTradePlan(reserve.seed),limit=Math.ceil(p.routes[index]!.travelSeconds+120);for(let i=0;i<limit&&reserve.frontierTrade!.routes[index]!.destinationStock<4;i++)reserve={...reserve,frontierTrade:advanceRegionalTrade(reserve.frontierTrade!,1)};perform('build-store',index);for(let i=0;i<limit*6&&reserve.frontierTrade!.routes[index]!.activity!=='finished';i++)reserve={...reserve,frontierTrade:advanceRegionalTrade(reserve.frontierTrade!,1)};assert.equal(reserve.frontierTrade!.routes[index]!.destinationStock,8);}
 perform('withdraw-reserve',1);const rp=regionalTradePlan(reserve.seed).projects[0]!;reserve={...reserve,player:{...reserve.player,x:rp.interactionPosition.x,z:rp.interactionPosition.z}};
 const reserveRoom=await request('/rooms',{name:'Compiled reserves',world:reserve});assert.equal(reserveRoom.status,201);const rpeers=[{user:'trade-build-host',snapshot:reserveRoom.body}];for(let i=1;i<4;i++){const user=`trade-reserve-guest-${i}`,joined=await request('/join',{name:`Reserve ${i}`,code:reserveRoom.body.code},user);assert.equal(joined.status,200);rpeers.push({user,snapshot:joined.body});}
 const rh=rpeers[0]!,rid=rh.snapshot.roomId,withdraw={type:'regional-trade',command:{type:'withdraw-reserve',targetId:rp.id,expectedRevision:rh.snapshot.world.frontierTrade.revision}};
 async function rsync(peer:typeof rh,actions:any[]){const response=await request(`/rooms/${rid}/sync`,{seq:peer.snapshot.ack+1,sessionId:peer.snapshot.sessionId,actions},peer.user);assert.equal(response.status,200,JSON.stringify(response.body));peer.snapshot=response.body;}
 let releaseReserve=()=>{},arriveReserve=()=>{};const reserveGate=new Promise<void>(r=>releaseReserve=r),reserveWaiting=new Promise<void>(r=>arriveReserve=r);pause={gate:reserveGate,arrived:arriveReserve};const reservePending=rsync(rpeers[1]!,[withdraw]);await reserveWaiting;try{await rsync(rh,[withdraw]);}finally{releaseReserve();}await reservePending;await Promise.all(rpeers.slice(2).map(p=>rsync(p,[withdraw])));
 for(const p of rpeers){const response=await request(`/rooms/${rid}`,undefined,p.user);assert.equal(response.status,200);p.snapshot=response.body;assert.deepEqual(regionalTradeWithdrawn(p.snapshot.world.frontierTrade),{wood:8,stone:8});assert.equal(p.snapshot.world.frontierTrade.routes[0].destinationStock,0);assert.deepEqual(p.snapshot.world.wilderness,reserve.wilderness);assert(validateSave(p.snapshot.world));}
 const credited=JSON.stringify(rh.snapshot.world.frontierTrade);await rsync(rh,[withdraw]);assert.equal(JSON.stringify(rh.snapshot.world.frontierTrade),credited);
 const outpost=regionalSupplyPlan(reserve.seed).outposts[0]!,row=sqlite.prepare('SELECT body FROM axiom_coop_rooms WHERE id=?').get(rid)!,stored=JSON.parse(String(row.body));for(const p of stored.players){p.player={...p.player,x:outpost.deliveryPosition.x,z:outpost.deliveryPosition.z};delete p.motion;delete p.wildernessCollisionVersion;}stored.world={...stored.world,player:{...stored.players[0].player}};sqlite.prepare('UPDATE axiom_coop_rooms SET body=? WHERE id=?').run(JSON.stringify(stored),rid);
 const delivery={type:'regional-supply',command:{type:'deliver',outpostId:outpost.id,expectedRevision:rh.snapshot.world.frontierSupply.revision}};await Promise.all(rpeers.map(p=>rsync(p,[delivery])));for(const p of rpeers){assert.deepEqual(p.snapshot.world.frontierSupply.outposts[0].delivered,outpost.cost);assert.deepEqual(regionalSupplyAvailable(p.snapshot.world.frontierSupply,p.snapshot.world.wilderness,p.snapshot.world.frontierTrade),{wood:8-outpost.cost.wood,stone:8-outpost.cost.stone});assert.deepEqual(p.snapshot.world.wilderness,reserve.wilderness);assert(validateSave(p.snapshot.world));}
 const report={version:1,status:'verified',scope:'Actual compiled Worker invoked with Request/Response and real SQLite; no browser, live network, visual review, device or production-site test.',runtime:process.version,workerBytes:statSync(workerPath).size,workerSha256:createHash('sha256').update(readFileSync(workerPath)).digest('hex'),players:4,casConflicts:conflicts,checks:['compiled authenticated regional room creation','four simultaneous source activations','real SQLite compare-and-swap conflict retry','sequence and ledger revision replay exactly once','one bounded clock across four polls','unchanged V31 and wilderness ledgers','host leave/resume no offline catchup','malformed trade import rejected','unrelated account denied','compiled four-player reserve withdrawal CAS replay','compiled V31 delivery spends credited reserve once with unchanged wilderness']};
 writeFileSync(process.argv[2]?resolve(process.argv[2]):resolve(root,'evidence/regional-trade-compiled-build.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{Date.now=originalNow;sqlite.close();}
