import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {WorkbenchSession,DEFAULT_WORKBENCH_CONFIG,replayWorkbench,parseWorkbenchReport,WORKBENCH_MAX_TICKS,type WorkbenchSnapshot} from '../src/system-workbench-model.ts';
import type {RegionalTradeRouteState} from '../src/regional-trade.ts';
import type {RegionalSupplyOutpost} from '../src/regional-supply.ts';
import type {RegionalFoodFarm} from '../src/regional-food.ts';
import {settlementPlan} from '../src/regional-settlement-workbench.ts';
/** Exact ordinary one-hour scenario. No browser, network, live save, terminal
 * clock exercise, time skipping, setup grants or simulation speed changes. */
const travel=process.argv[3]==='--travel'?(process.argv[4]??'invalid'):'regional';assert(['legacy','regional'].includes(travel),'Travel must be regional or legacy');assert(process.argv.length<4||(process.argv[3]==='--travel'&&process.argv.length===5),'Usage: verify-settlement-workbench.mts [output-folder] [--travel regional|legacy]');
const folder=resolve(process.argv[2]??'/tmp/axiom-settlement-evidence');mkdirSync(folder,{recursive:true});
let revision=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();const dirty=!!execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim();if(dirty)revision+='-working';
const s=new WorkbenchSession({...DEFAULT_WORKBENCH_CONFIG,system:'settlement',rainfall:'regional',...(travel==='regional'?{travel:'regional' as const}:{})},revision),plan=settlementPlan(s.config.seed),milestones:Record<string,number>={},reloads:{stage:string;tick:number;fingerprint:string;saveBytes:number}[]=[],phases=new Set<string>(),travelConditions=new Set<string>(),travelReloads:{condition:string;tick:number;fingerprint:string}[]=[],routeTravel=plan.routes.map(r=>({routeId:r.id,baseSpeed:r.speed,minSpeed:r.speed,maxWetness:0}));
let maxReportBytes=0,maxSaveBytes=0,maxBalanceError=0,firstRecovery:number|null=null,firstRecoveryDrink:number|null=null,firstOverflow:number|null=null,dryShortage=false,recoveryBeforeOverflow=false,previous=s.snapshot();
const seen=(name:string,condition:boolean,time:number)=>{if(condition&&milestones[name]===undefined)milestones[name]=time;};
const reload=(stage:string,condition:boolean)=>{if(!condition||reloads.some(r=>r.stage===stage))return;const fingerprint=s.digest();assert(s.verifyReload().pass,stage);assert.equal(s.digest(),fingerprint);const footprint=s.storageFootprint();reloads.push({stage,tick:s.tick,fingerprint,saveBytes:footprint.saveBytes});maxSaveBytes=Math.max(maxSaveBytes,footprint.saveBytes);maxReportBytes=Math.max(maxReportBytes,footprint.reportBytes);};
assert.equal(s.setupSeconds,0);assert.equal(previous.inventory.productionStarterMeals,0);assert.equal(previous.inventory.harvested,0);assert.equal(previous.inventory.rainCaptured,0);assert.equal(previous.inventory.rawWood,0);assert.equal(previous.inventory.rawStone,0);
while(s.tick<WORKBENCH_MAX_TICKS){
 if(s.tick%4===0)s.assist();const snap=s.advance(1),ledger=snap.ledger as {trade:RegionalTradeRouteState[];collector:RegionalSupplyOutpost;farm:RegionalFoodFarm;productionReceipts:{trade:{type:string;targetId:string;tick:number}[]}},o=ledger.collector,f=ledger.farm;
 assert.equal(snap.firstFailure,null);assert(snap.checks.every(c=>c.pass));maxBalanceError=Math.max(maxBalanceError,...snap.checks.map(c=>c.error));phases.add(snap.weather!.phase);
 for(const [i,road] of (snap.freight??[]).entries()){travelConditions.add(road.travelCondition);routeTravel[i]!.minSpeed=Math.min(routeTravel[i]!.minSpeed,road.travelSpeed);routeTravel[i]!.maxWetness=Math.max(routeTravel[i]!.maxWetness,road.roadWetness);assert(road.travelSpeed>0&&road.travelSpeed<=routeTravel[i]!.baseSpeed);if(road.etaKind==='repair-required')assert.equal(road.etaSeconds,null);if(!travelReloads.some(r=>r.condition===road.travelCondition)){const fingerprint=s.digest();assert(s.verifyReload().pass);assert.equal(s.digest(),fingerprint);travelReloads.push({condition:road.travelCondition,tick:s.tick,fingerprint});}}
 for(const [i,r] of ledger.trade.entries()){
  const prefix=i===0?'stone':'wood';seen(prefix+'FirstReservation',r.reserved>0,snap.seconds);seen(prefix+'FirstLoadedTravel',r.activity==='outbound'&&r.cargo>0,snap.seconds);seen(prefix+'Blocked',r.activity==='blocked',snap.seconds);seen(prefix+'RepairCompleted',r.clearedAt!==null,snap.seconds);seen(prefix+'FirstDelivery',r.delivered>=4,snap.seconds);seen(prefix+'StoreCompleted',r.builtAt!==null,snap.seconds);seen(prefix+'ReserveWithdrawn',r.withdrawn>0,ledger.productionReceipts.trade.find(e=>e.type==='withdraw-reserve'&&e.targetId===plan.stores[i]!.id)?.tick!*.25);
  reload(prefix+'-loading',r.activity==='loading'&&r.reserved>0);reload(prefix+'-transit',r.activity==='outbound'&&r.cargo>0);reload(prefix+'-unloading',r.activity==='unloading');reload(prefix+'-construction',r.buildStartedAt!==null&&r.builtAt===null);
 }
 seen('farmStarted',f.startedAt!==null,(f.startedAt??0)*.25);seen('collectorStarted',o.buildStartedAt!==null,(o.buildStartedAt??0)*.25);seen('collectorBuilt',o.builtAt!==null,snap.seconds);seen('firstCapture',o.captured>0,snap.seconds);seen('firstDrink',o.consumed>0,snap.seconds);seen('firstOverflow',o.spilled>0,snap.seconds);seen('firstPlanting',f.crop==='growing',snap.seconds);seen('firstHarvest',f.harvested>0,snap.seconds);seen('firstHarvestDelivered',f.delivered>0,snap.seconds);seen('firstGuaranteedHarvestedMeal',f.meals>f.starterGranted,snap.seconds);
 if(o.builtAt!==null&&snap.weather!.intensity===0&&o.water<1&&o.residents.some(r=>r.thirst>=45&&r.carrying===0))dryShortage=true;
 if(dryShortage&&firstRecovery===null&&snap.weather!.intensity>0&&o.captured>previous.inventory.rainCaptured!)firstRecovery=snap.seconds;
 if(firstRecovery!==null&&firstRecoveryDrink===null&&o.consumed>previous.inventory.waterDrunk!)firstRecoveryDrink=snap.seconds;
 if(firstOverflow===null&&o.spilled>0)firstOverflow=snap.seconds;
 if(firstRecoveryDrink!==null&&o.spilled===0&&f.waterCaptured===0)recoveryBeforeOverflow=true;
 if(snap.weather!.intensity===0&&previous.weather!.intensity===0)assert.equal(o.captured,previous.inventory.rainCaptured,'Dry quarter ticks cannot collect rain');
 reload('collector-construction',o.buildStartedAt!==null&&o.builtAt===null&&o.workTicks>0);reload('crop-growing',f.crop==='growing'&&f.growth>0);reload('crop-harvesting',f.crop==='ripe'&&f.harvestWork>0);reload('food-loading',f.activity==='loading'&&f.reserved>0);reload('food-transit',f.activity==='outbound'&&f.cargo>0);reload('food-unloading',f.activity==='unloading'&&f.cargo>0);reload('food-eating',f.activity==='eating'&&f.carrierMeal>0&&f.delivered>0);
 if(s.tick%40===0){const measured=s.storageFootprint();maxSaveBytes=Math.max(maxSaveBytes,measured.saveBytes);maxReportBytes=Math.max(maxReportBytes,measured.reportBytes);}
 previous=snap;
}
if(travel==='regional'){assert(travelConditions.has('wet'));assert(travelConditions.has('drying'));assert(travelConditions.has('dry'));assert(routeTravel.every(r=>r.maxWetness>0&&r.minSpeed<r.baseSpeed));}
assert(dryShortage);assert(recoveryBeforeOverflow);assert(firstRecovery!==null&&firstRecoveryDrink!==null&&firstOverflow!==null&&firstRecovery<=firstRecoveryDrink&&firstRecoveryDrink<firstOverflow);assert(s.snapshot().inventory.harvestedMealsMinimum!>0);
for(const stage of ['stone-loading','stone-transit','stone-unloading','stone-construction','wood-loading','wood-transit','wood-unloading','wood-construction','collector-construction','crop-growing','crop-harvesting','food-loading','food-transit','food-unloading','food-eating'])assert(reloads.some(r=>r.stage===stage),stage);
assert(s.verifyReload().pass);const report=s.report(),footprint=s.storageFootprint(),replay=replayWorkbench(parseWorkbenchReport(JSON.stringify(report)),revision);assert(replay.result.match);assert.equal(replay.session.digest(),s.digest());assert.equal(report.version,2);assert.equal(report.eventEncoding,'target-v1');
const divergent=structuredClone(report);divergent.checkpoints[4]!.fingerprint='00000000';divergent.finalFingerprint='00000000';const divergence=replayWorkbench(divergent,revision).result;assert.equal(divergence.firstDifference,'State first differs at sampled tick 160');
assert(footprint.saveBytes<80_000);assert(footprint.reportBytes<100_000);assert.equal(footprint.geometryChunks,0);assert(report.events.length<=128);assert.equal(report.checkpoints.length,361);
const evidence={kind:'axiom-integrated-settlement-check',sourceRevision:revision,dirty,runtime:process.version,scope:report.scope,seed:s.config.seed,travel,travelConditions:[...travelConditions],travelReloads,routeTravel,seconds:3600,setupSeconds:s.setupSeconds,routeMetres:plan.routes.map(r=>r.surfaceMetres),dryCarrierMetresPerSecond:plan.routes.map(r=>r.speed),milestones,dryShortage,recovery:{firstRainCapture:firstRecovery,firstDrink:firstRecoveryDrink,firstOverflow,drinkingBeforeOverflow:recoveryBeforeOverflow},weatherPhases:[...phases],reloads,maxBalanceError,footprint:{...footprint,maxSampledSaveBytes:Math.max(maxSaveBytes,footprint.saveBytes),maxSampledReportBytes:Math.max(maxReportBytes,footprint.reportBytes)},finalInventory:report.snapshot.inventory,finalFingerprint:report.finalFingerprint,exactReplay:replay.result.match,earliestDifferenceProbe:divergence.firstDifference};
writeFileSync(resolve(folder,'settlement-report.json'),JSON.stringify(report,null,2)+'\n');writeFileSync(resolve(folder,'settlement-measurements.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify(evidence,null,2));
