import assert from 'node:assert/strict';import {readFileSync,readdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
import {createTownView} from '../src/town-view.ts';import {TOWN_LIFE_ENGINE} from '../src/town-life.ts';import {TOWN_ACTIVITY_ENGINE} from '../src/town-activity.ts';import {startupMatrixCase} from '../tests/helpers/town-startup-cases.ts';
const root=resolve(import.meta.dirname,'..'),assets=resolve(root,'dist/client/assets'),files=readdirSync(assets),projection=files.find(f=>/^town-projection-.*\.js$/.test(f));assert(projection);const pm=await import(pathToFileURL(resolve(assets,projection)).href),factory=Object.values(pm).find(v=>typeof v==='function'&&v.toString().includes('hearthmere-residents')) as typeof createTownView;assert(factory);
let life:typeof TOWN_LIFE_ENGINE|undefined,activity:typeof TOWN_ACTIVITY_ENGINE|undefined;for(const f of files.filter(f=>/^(?:town-life|town-director|town-activity|campaign-guidance-engine)-.*\.js$/.test(f))){const m=await import(pathToFileURL(resolve(assets,f)).href);for(const v of Object.values(m) as any[]){if(v?.kind==='axiom-town-life')life=v;if(v?.kind==='axiom-town-activity-watchdog')activity=v;}}assert(life&&activity);
for(const seed of [0,7,42,73129,0xffffffff]){let a=TOWN_LIFE_ENGINE.create(seed),b=life.create(seed);assert.deepEqual(a,b);for(let n=0;n<240;n++){a=TOWN_LIFE_ENGINE.advance(a,.5);b=life.advance(b,.5);assert.deepEqual(b,a);assert(life.validate(b,seed));}}
const cases=[];for(const [seed,online] of [[73129,false],[73129,true],[0,false],[0xffffffff,true]] as const){const source=startupMatrixCase(createTownView,seed,30,online),emitted=startupMatrixCase(factory,seed,30,online);assert.deepEqual(emitted,source);cases.push(emitted);}const legacy=JSON.parse(readFileSync(resolve(root,'tests/fixtures/town-motion-v11/15.json'),'utf8'));const a=startupMatrixCase(createTownView,73129,30,true,legacy),b=startupMatrixCase(factory,73129,30,true,legacy);assert.deepEqual(a,b);cases.push(b);
const sm=new TOWN_ACTIVITY_ENGINE.Monitor(),bm=new activity.Monitor();let state=life.create(73129);for(let f=0;f<=60;f++){if(f<49)state=life.advance(state,.25);const input={now:f*250,seed:73129,life:state,matrices:[],expectedDrawn:100,physicsStep:f*15,renderFrames:1,renderTime:f*.25,paused:false,mode:'solo' as const,camera:[]};sm.sample(input,'parity');bm.sample(input,'parity');}assert.deepEqual(bm.report(),sm.report());const warnings=bm.report().recentSummary!.warnings;assert(warnings.some(w=>w.includes('authority is stalled')));assert(warnings.some(w=>w.includes('missing')));assert(warnings.some(w=>w.includes('Render-frame')));
const main=files.find(f=>/^main-.*\.js$/.test(f))!;assert(readFileSync(resolve(assets,main),'utf8').includes('town-activity-'));
const report={kind:'axiom-town-startup-emitted',scope:'Source and actual emitted opening authority, resident matrices, portrait/landscape/wide camera frustum candidates, retained-save recovery and watchdog fault-injection parity. Node22 CPU only; no browser/GPU, occlusion or device approval.',projection,cases,watchdogWarnings:warnings};if(process.argv[2])writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
