import assert from 'node:assert/strict';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {Worker} from 'node:worker_threads';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import {WORKSHOP_CONSTRUCTION_ENGINE,WORKSHOP_PARCEL,WORKSHOP_BOARD,type WorkshopConstructionState,type WorkshopConstructionCommand} from '../src/workshop-construction.ts';
import {WORKSHOP_CONSTRUCTION_VIEW_ENGINE} from '../src/workshop-construction-view.ts';
import {DEFAULT_WORKSHOP_DRAFT,compileWorkshopDraft} from '../src/workshop-authoring.ts';
import {TOWN_LIFE_ENGINE,createTownLife,advanceTownLifeWithWorkshopWork,assignTownWorkshopWorker,validTownLife} from '../src/town-life.ts';
import {createRegionalState,enableStartingTown,applyAction,validateSave,parseSave,serializeSave,type State} from '../src/world.ts';
import {handleCoop} from '../server/coop-api.ts';
const root=resolve(import.meta.dirname,'..'),assets=resolve(root,'dist/client/assets'),files=readdirSync(assets);
const digest=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
async function surface(prefix:string,kind:string){const matches=files.filter(f=>new RegExp(`^${prefix}-.*\\.js$`).test(f));assert.equal(matches.length,1,`exactly one fresh ${prefix} chunk`);const file=matches[0]!,module=await import(pathToFileURL(resolve(assets,file)).href),value=Object.values(module).find((v:any)=>v?.kind===kind);assert(value,`${file} exports ${kind}`);return {file,value,sha256:digest(readFileSync(resolve(assets,file),'utf8'))};}
const emitted=await surface('workshop-construction-engine','axiom-workshop-construction'),engine=emitted.value as typeof WORKSHOP_CONSTRUCTION_ENGINE;
// Vite may coalesce mutually dependent manual chunks; identify the actual retained
// engine object among the relevant emitted modules, not a presumed file name.
async function townSurface(){const found:{file:string;value:unknown;sha256:string}[]=[];for(const file of files.filter(f=>/^(town-life|town-director|workshop-construction-engine|restoration-care-engine)-.*\.js$/.test(f))){const module=await import(pathToFileURL(resolve(assets,file)).href);for(const value of Object.values(module))if((value as any)?.kind==='axiom-town-life')found.push({file,value,sha256:digest(readFileSync(resolve(assets,file),'utf8'))});}assert.equal(found.length,1,'exactly one exported actual axiom-town-life engine');return found[0]!;}
const townAsset=await townSurface(),townEngine=townAsset.value as typeof TOWN_LIFE_ENGINE;
const projection=await surface('workshop-construction-view','axiom-workshop-construction-view'),viewEngine=projection.value as typeof WORKSHOP_CONSTRUCTION_VIEW_ENGINE;
function scene(root:any){root.updateMatrixWorld(true);const out:any[]=[];root.traverse((o:any)=>out.push({name:o.name,type:o.type,visible:o.visible,matrix:o.matrixWorld.toArray(),...(o.isMesh||o.isLine?{geometry:Array.from(o.geometry.attributes.position.array),color:o.material.color?.toArray()}:{})}));return out;}
const modelCases:any[]=[],viewHashes:string[]=[];let viewFrames=0;
for(const seed of [0,73129,0xffffffff]){
 const parameters={...DEFAULT_WORKSHOP_DRAFT,seed},base=createTownLife(seed),workerId=base.residents[0]!.id,context={seed,zone:'valley',player:{...WORKSHOP_BOARD,hp:45}},command:WorkshopConstructionCommand={kind:'build',expectedRevision:0,parcelId:WORKSHOP_PARCEL.id,parameters,workerId};
 assert.deepEqual(engine.quote(parameters),WORKSHOP_CONSTRUCTION_ENGINE.quote(parameters));assert(engine.command(command));
 let source=WORKSHOP_CONSTRUCTION_ENGINE.apply(undefined,base,context,command)!,built=engine.apply(undefined,base,context,command)!;assert(source);assert.deepEqual(built,source);assert.equal(engine.apply(built.construction,built.life,context,command),null);
 const a=WORKSHOP_CONSTRUCTION_VIEW_ENGINE.create(),b=viewEngine.create(),pa=new WORKSHOP_CONSTRUCTION_VIEW_ENGINE.Projection(),pb=new viewEngine.Projection();
 try{
  assert.deepEqual(pb.stage(built.construction,0,true),pa.stage(source.construction,0,true));assert.equal(pa.acknowledge(999,true),false);assert.equal(pb.acknowledge(999,true),false);pa.ready();pb.ready();
  let ticks=0,total=0;
  while(source.construction.status!=='complete'&&ticks++<600){
   const sa=advanceTownLifeWithWorkshopWork(source.life,.5,workerId),sb=townEngine.advanceWorkshop(built.life,.5,workerId);assert.deepEqual(sb,sa);total+=sa.workSeconds;
   source={...source,life:sa.life,construction:WORKSHOP_CONSTRUCTION_ENGINE.advance(source.construction,sa.workSeconds)};built={...built,life:sb.life,construction:engine.advance(built.construction,sb.workSeconds)};assert.deepEqual(built,source);assert(engine.validate(built.construction,seed));assert(validTownLife(built.life,seed));
   if(ticks%20===0||source.construction.status==='complete')for(const player of [WORKSHOP_BOARD,WORKSHOP_PARCEL]){a.update(source.construction,pa.confirmed,player,true,true);b.update(built.construction,pb.confirmed,player,true,true);assert.deepEqual(scene(b.root),scene(a.root));viewHashes.push(digest(scene(b.root)));viewFrames++;}
  }
  assert.equal(source.construction.status,'complete');assert(total>=source.construction.workRequired);assert.deepEqual(engine.immutable(JSON.parse(JSON.stringify(built.construction)),seed),built.construction);
  const repair:WorkshopConstructionCommand={kind:'repair',expectedRevision:1},before=built;source=WORKSHOP_CONSTRUCTION_ENGINE.apply(source.construction,source.life,context,repair)!;built=engine.apply(built.construction,built.life,context,repair)!;assert.deepEqual(built,source);assert.equal(built.hp,70);assert.equal(built.life.resources.materials,before.life.resources.materials-4);assert.equal(engine.apply(built.construction,built.life,context,repair),null);
  for(const change of [(v:any)=>v.materialsPaid--,(v:any)=>v.workerId='forged',(v:any)=>v.parameters.width=100,(v:any)=>v.work=-1]){const bad=structuredClone(built.construction);change(bad);assert.equal(engine.validate(bad,seed),false);assert.equal(WORKSHOP_CONSTRUCTION_ENGINE.validate(bad,seed),false);}
  assert.deepEqual(viewEngine.obstacles(built.construction),WORKSHOP_CONSTRUCTION_VIEW_ENGINE.obstacles(source.construction));modelCases.push({seed,ticks,achievedSeconds:total,paid:built.construction.materialsPaid,sha256:digest(built)});
 }finally{a.dispose();b.dispose();}console.error(`workshop emitted model/view seed ${seed} passed`);
}
async function bridge(file:string){const worker=new Worker(`const{parentPort}=require('node:worker_threads');globalThis.self=globalThis;self.postMessage=m=>parentPort.postMessage(m);parentPort.on('message',m=>self.onmessage({data:m}));import(${JSON.stringify(pathToFileURL(file).href)}).then(()=>parentPort.postMessage({type:'boot'}));`,{eval:true,execArgv:['--experimental-strip-types']});const messages:any[]=[];let error:Error|undefined;worker.on('message',m=>{messages.push(m);if(m.type==='error')error=Error(m.message);});worker.on('error',e=>error=e);async function take(type:string,match:(m:any)=>boolean=()=>true){const until=Date.now()+20000;for(;;){if(error)throw error;const i=messages.findIndex(m=>m.type===type&&match(m));if(i>=0)return messages.splice(i,1)[0];assert(Date.now()<until,`worker deadline ${type}: ${JSON.stringify(messages.filter(m=>m.type!=='snapshot').slice(-5))}`);await new Promise(r=>setTimeout(r,2));}}await take('boot');return {worker,messages,take,send:(m:unknown)=>worker.postMessage(m)};}
async function physical(file:string){const b=await bridge(file),trace:any[]=[],routes:string[]=[];let epoch=0,latest:any;
 const terrain={bound:48,step:64,vertices:[-32,6,-32,32,6,-32,-32,6,32,32,6,32],indices:[0,2,1,1,2,3]};
 const ground={key:'workshop-ground',revision:1,obstacles:[],terrain,bounds:{minX:-32,maxX:32,minZ:-32,maxZ:32}};
 async function tick(ticks:number,x=0,z=0){b.send({type:'input',epoch,x,z,paused:false});b.send({type:'step',epoch,ticks});await b.take('stepped');const frames=b.messages.filter(m=>m.type==='snapshot');b.messages.splice(0,b.messages.length,...b.messages.filter(m=>m.type!=='snapshot'));assert(frames.length);latest=frames.at(-1);for(const f of frames)trace.push({epoch,step:f.step,x:f.x,z:f.z,feetY:f.feetY,grounded:f.grounded});return latest;}
 async function travel(target:{x:number;z:number}){for(let i=0;i<300;i++){const dx=target.x-latest.x,dz=target.z-latest.z,d=Math.hypot(dx,dz);if(d<.13){await tick(8);assert(Math.hypot(target.x-latest.x,target.z-latest.z)<.35);assert(Math.abs(latest.feetY-6)<.25);return;}await tick(1,dx/d,dz/d);}throw Error(`Worker route blocked ${JSON.stringify({target,latest})}`);}
 try{for(const rearRooms of [2,3] as const){const parameters={...DEFAULT_WORKSHOP_DRAFT,rearRooms},compiled=compileWorkshopDraft(parameters),state={parameters} as WorkshopConstructionState,obstacles=WORKSHOP_CONSTRUCTION_VIEW_ENGINE.obstacles(state).map(o=>({...o,x:o.x-WORKSHOP_PARCEL.x,z:o.z-WORKSHOP_PARCEL.z}));
  b.send({type:epoch?'zone':'init',epoch,x:compiled.workshop.spawn.x,z:compiled.workshop.spawn.z,y:6,streamedTerrain:true,obstacles:[],initialCells:[ground,{key:'campaign-workshop',revision:1,obstacles}],bound:48,sandbox:true,startPaused:true,manual:true});await b.take('ready');await tick(5);
  for(const route of compiled.routes){for(const p of route.points)await travel(p);routes.push(`${rearRooms}/${route.key}`);for(const p of [...route.points].reverse())await travel(p);}
  const overlap={featureId:'probe-overlap',x:latest.x,y:7,z:latest.z,hx:1,hy:1,hz:1};b.send({type:'cell-load',epoch,key:'campaign-workshop',revision:2,obstacles:[...obstacles,overlap]});const rejected=await b.take('cell-rejected');assert.equal(rejected.reason,'player-overlap');assert.equal(rejected.loaded,true);b.send({type:'cell-load',epoch,key:'campaign-workshop',revision:3,obstacles});const ack=await b.take('cell-ack',m=>m.revision===3);assert.equal(ack.loaded,true);
  epoch++;b.send({type:'zone',epoch,x:parameters.width/2+2,z:0,y:6,streamedTerrain:true,obstacles:[],initialCells:[ground,{key:'campaign-workshop',revision:1,obstacles}],bound:48,sandbox:true,manual:true});await b.take('ready');await tick(120,-1,0);assert(latest.x>parameters.width/2+.2,'solid east wall stops actual capsule');assert(latest.x<parameters.width/2+1);epoch++;
 }return {routes,trace,collisionRetry:true};}finally{await b.worker.terminate();}}
const physicsFiles=files.filter(f=>/^physics\.worker-.*\.js$/.test(f));assert.equal(physicsFiles.length,1);const physicsFile=physicsFiles[0]!,sourcePhysical=await physical(resolve(root,'src/physics.worker.ts')),emittedPhysical=await physical(resolve(assets,physicsFile));assert.deepEqual(emittedPhysical,sourcePhysical);console.error('workshop emitted physical workers passed');
function setup(){let state=enableStartingTown(createRegionalState(73129));state={...state,player:{...state.player,...WORKSHOP_BOARD,hp:45}};return state;}
function buildCommand(state:State):WorkshopConstructionCommand{const worker=state.townLife!.residents.find(r=>assignTownWorkshopWorker(state.townLife!,r.id));assert(worker);return {kind:'build',expectedRevision:0,parcelId:WORKSHOP_PARCEL.id,parameters:{...DEFAULT_WORKSHOP_DRAFT},workerId:worker.id};}
let completed=applyAction(setup(),{type:'workshop-construction',command:buildCommand(setup())}),resumed=parseSave(serializeSave(completed))!;assert(resumed);
for(let i=0;i<600&&completed.workshopConstruction!.status!=='complete';i++){completed=applyAction(completed,{type:'tick',dt:.5});resumed=applyAction(resumed,{type:'tick',dt:.5});}assert.equal(completed.workshopConstruction!.status,'complete');assert.deepEqual(resumed,completed);assert(validateSave(completed));
const builtServer=(await import(pathToFileURL(resolve(root,'dist/server/index.js')).href)).default;
async function serverCase(emitted:boolean){const db=new DatabaseSync(':memory:');for(const f of readdirSync(resolve(root,'drizzle')).filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync(resolve(root,'drizzle',f),'utf8'));const DB={prepare(sql:string){let values:any[]=[];return {bind(...next:any[]){values=next;return this;},async first(){return db.prepare(sql).get(...values)??null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){const result=db.prepare(sql).run(...values);return {success:true,meta:{changes:Number(result.changes)}};}};}};let now=1900000000000;const originalNow=Date.now;Date.now=()=>now;
 async function request(path:string,body:unknown,expected=200,user='workshop-build-host',preview=true){const req=new Request('https://fixture.invalid/api/coop'+path,{method:'POST',headers:{Origin:'https://fixture.invalid','oai-authenticated-user-id':user,'Content-Type':'application/json'},body:JSON.stringify(body)}),response=emitted?await builtServer.fetch(req,preview?{AXIOM_PREVIEW_DB:DB}:{DB}):await handleCoop(req,preview?{DB}:{},now);assert.equal(response?.status,expected,await response?.clone().text());return await response!.json() as any;}
 try{
  await request('/rooms',{name:'Missing binding',world:setup()},503,'workshop-build-host',false);
  for(const change of [(v:any)=>v.workshopConstruction.materialsPaid--,(v:any)=>v.townLife.workshopSpent--,(v:any)=>v.inventory.scrap++]){const forged=structuredClone(completed);change(forged);await request('/rooms',{name:'Forged workshop',world:forged},400);}
  let current=await request('/rooms',{name:'Workshop construction gate',world:setup()},201),id=current.roomId,sessionId=current.sessionId;
  const payload={seq:1,sessionId,actions:[{type:'workshop-construction',command:buildCommand(current.world)}]};current=await request(`/rooms/${id}/sync`,payload);assert(current.world.workshopConstruction);const retry=await request(`/rooms/${id}/sync`,payload);assert.deepEqual(retry.world,current.world);assert(validateSave(current.world));
  let seq=1;for(let poll=0;poll<120&&current.world.workshopConstruction.work===0;poll++){now+=1000;const packet={seq:++seq,sessionId,actions:[]};current=await request(`/rooms/${id}/sync`,packet);assert.deepEqual((await request(`/rooms/${id}/sync`,packet)).world,current.world);}assert(current.world.workshopConstruction.work>0,'HTTP authority credits achieved resident work');
  await request(`/rooms/${id}/sync`,{seq:seq+1,sessionId,actions:[{type:'workshop-construction',command:{kind:'repair',expectedRevision:1},state:current.world.workshopConstruction}]},400);
  const paidImport=await request('/rooms',{name:'Paid imported workshop',world:completed},201);assert.equal(paidImport.world.workshopConstruction.status,'complete');
  const before=paidImport.world,repair={seq:1,sessionId:paidImport.sessionId,actions:[{type:'workshop-construction',command:{kind:'repair',expectedRevision:1}}]};const repaired=await request(`/rooms/${paidImport.roomId}/sync`,repair);assert.equal(repaired.world.player.hp,Math.min(100,before.player.hp+25));assert.equal(repaired.world.townLife.resources.materials,before.townLife.resources.materials-4);assert.equal(repaired.world.workshopConstruction.repairs,1);assert.deepEqual((await request(`/rooms/${paidImport.roomId}/sync`,repair)).world,repaired.world);assert(validateSave(repaired.world));
  return {construction:current.world.workshopConstruction,paidImport:before.workshopConstruction,repaired:repaired.world.workshopConstruction,materials:repaired.world.townLife.resources.materials,hp:repaired.world.player.hp,exactRetries:true,forgedImportsRejected:3,previewOnlyBinding:true};
 }finally{Date.now=originalNow;db.close();}}
const sourceServer=await serverCase(false),emittedServer=await serverCase(true);assert.deepEqual(emittedServer,sourceServer);console.error('workshop emitted HTTP/SQLite authority passed');
const sourceFiles=['src/workshop-construction.ts','src/workshop-construction-view.ts','src/workshop-construction-ui.ts','src/main.ts','src/workshop-authoring.ts','src/town-life.ts','src/world.ts','src/physics.worker.ts','server/coop-api.ts','server/coop-authority.ts','server/coop-validation.ts','server/index.ts'],sourceHashes=Object.fromEntries(sourceFiles.map(file=>[file,digest(readFileSync(resolve(root,file),'utf8'))]));
const report={kind:'axiom-workshop-construction-emitted-verification',version:1,verifiedAt:new Date().toISOString(),sourceHashes,scope:'Actual production engine/view chunks, Three object matrices, source/emitted Rapier WASM workers and HTTP with disposable in-memory SQLite. No browser/GPU/device/live-save claim.',engine:{file:emitted.file,sha256:emitted.sha256,townFile:townAsset.file,townSha256:townAsset.sha256,cases:modelCases},view:{file:projection.file,sha256:projection.sha256,frames:viewFrames,sha256Frames:digest(viewHashes)},physics:{file:physicsFile,assetSha256:digest(readFileSync(resolve(assets,physicsFile),'utf8')),sha256:digest(emittedPhysical),frames:emittedPhysical.trace.length,routes:emittedPhysical.routes,collisionRetry:true},server:{assetSha256:digest(readFileSync(resolve(root,'dist/server/index.js'),'utf8')),sha256:digest(emittedServer),...emittedServer},saveReplaySha256:digest(completed)};
if(process.argv[2])writeFileSync(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
