/** Disposable rehearsal using canonical sources, paid commands and achieved town labor. */
import {createRegionalState,commitTownSupply,commitWorkshopConstruction,applyAction,worldTownSupplySources,worldRestorationPlan,type State} from './world.ts';
import {createTownLife,immutableTownLife,assignTownWorkshopWorker,TOWN_LIFE_ENGINE} from './town-life.ts';
import {townSupplyPosition,type TownSupplyCommand} from './town-supply.ts';
import {WORKSHOP_BOARD,WORKSHOP_PARCEL} from './workshop-construction.ts';
import {DEFAULT_WORKSHOP_DRAFT} from './workshop-authoring.ts';
import {RESTORATION_ENGINE} from './restoration.ts';
import {createRestorationCareScenario} from './restoration-care-scenarios.ts';
export const CAMPAIGN_GUIDANCE_SCENARIOS=Object.freeze(['opening','supply-to-workshop','care-delivered','workshop-complete'] as const);
export type CampaignGuidanceScenario=typeof CAMPAIGN_GUIDANCE_SCENARIOS[number];
export interface CampaignGuidanceScenarioModel {seed:number;scenario:CampaignGuidanceScenario;state:State;initialInventory:{scrap:number;core:number;water:number};preparation:unknown[];preparationSeconds:number;elapsed:number;actions:unknown[];actionsTruncated:boolean}
function stepState(state:State,seconds:number){let next=state;for(let left=seconds;left>1e-8;left-=.5)next=applyAction(next,{type:'tick',dt:Math.min(.5,left)},[{x:next.player.x,z:next.player.z,y:6}]);return next;}
export function createCampaignGuidanceScenario(seed:number,scenario:CampaignGuidanceScenario='opening'):CampaignGuidanceScenarioModel {
 if(!CAMPAIGN_GUIDANCE_SCENARIOS.includes(scenario))throw Error('Unknown guidance rehearsal scenario.');let state=createRegionalState(seed),life=structuredClone(createTownLife(seed));life.resources.materials=0;life.ledger.initial.materials=0;if(!TOWN_LIFE_ENGINE.validate(life,seed))throw Error('Invalid zero-stock guidance town fixture.');state={...state,townLife:immutableTownLife(life,seed),player:{...state.player,hp:75}};const preparation:unknown[]=[];let preparationSeconds=0,initialInventory={scrap:0,core:0,water:0};
 function advance(seconds:number){if(preparationSeconds+seconds>1200)throw Error('Scenario preparation exceeded its 1200-second bound.');state=stepState(state,seconds);preparationSeconds+=seconds;const last=preparation.at(-1) as {kind?:string;seconds?:number}|undefined;if(last?.kind==='advance')last.seconds=(last.seconds??0)+seconds;else preparation.push({kind:'advance',seconds});}
 function supply(kind:TownSupplyCommand['kind'],targetId:string){const command={kind,targetId,expectedRevision:state.townSupply?.revision??0},point=townSupplyPosition(seed,worldTownSupplySources(state),command)!;state={...state,player:{...state.player,x:point.x,z:point.z}};const next=commitTownSupply(state,command,point.y);if(next===state)throw Error('Guidance rehearsal supply command failed.');preparation.push({kind:'supply-command',command,player:{...state.player},feetY:point.y});state=next;}
 if(scenario==='care-delivered'){const fixture=createRestorationCareScenario(seed,'delivered');if(!RESTORATION_ENGINE.validate(fixture.restoration,worldRestorationPlan(seed)))throw Error('Earned care fixture does not match the canonical habitat plan.');state={...state,townLife:fixture.life,restoration:fixture.restoration,...(fixture.care?{restorationCare:fixture.care}:{}),player:fixture.player,inventory:fixture.inventory};initialInventory={...fixture.initialInventory};preparation.push({kind:'earned-care-preparation',actions:fixture.preparationActions,ticks:fixture.preparationTicks,initialInventory:fixture.initialInventory});preparationSeconds=fixture.preparationTicks*.25;}
 if(scenario==='supply-to-workshop'||scenario==='workshop-complete'){
  const sources=worldTownSupplySources(state);for(let i=0;i<6;i+=2){supply('load',sources[i]!.id);supply('load',sources[i+1]!.id);if(state.townLife!.cooldowns.donate>0){state={...state,player:{...state.player,x:WORKSHOP_BOARD.x,z:WORKSHOP_BOARD.z}};preparation.push({kind:'model-operator-placement',player:{...state.player}});advance(state.townLife!.cooldowns.donate);}supply('deliver','workshop');}
  const worker=state.townLife!.residents.find(r=>assignTownWorkshopWorker(state.townLife!,r.id));if(!worker)throw Error('No eligible actual construction worker in rehearsal.');state={...state,player:{...state.player,x:WORKSHOP_BOARD.x,z:WORKSHOP_BOARD.z}};const command={kind:'build' as const,expectedRevision:0,parcelId:WORKSHOP_PARCEL.id,parameters:{...DEFAULT_WORKSHOP_DRAFT,seed},workerId:worker.id};const next=commitWorkshopConstruction(state,command);if(next===state)throw Error('Finite deliveries did not fund the actual workshop quote.');preparation.push({kind:'construction-command',command,player:{...state.player}});state=next;
  if(scenario==='workshop-complete'){
   while(state.workshopConstruction!.status!=='complete')advance(.5);
   const repair={kind:'repair' as const,expectedRevision:state.workshopConstruction!.revision},repaired=commitWorkshopConstruction(state,repair);if(repaired===state)throw Error('Completed rehearsal workshop could not fund its paid repair.');preparation.push({kind:'construction-command',command:repair,player:{...state.player}});state=repaired;
   supply('load',sources[6]!.id);supply('unload','workshop');
  }
 }
 return {seed,scenario,state,initialInventory,preparation,preparationSeconds,elapsed:0,actions:[],actionsTruncated:false};
}
function record(model:CampaignGuidanceScenarioModel,action:unknown):Pick<CampaignGuidanceScenarioModel,'actions'|'actionsTruncated'>{return model.actions.length<128?{actions:[...model.actions,action],actionsTruncated:model.actionsTruncated}:{actions:model.actions,actionsTruncated:true};}
export function stepCampaignGuidanceScenario(model:CampaignGuidanceScenarioModel,seconds:number):CampaignGuidanceScenarioModel {if(!Number.isSafeInteger(seconds)||seconds<1||seconds>60)throw RangeError('Use 1–60 whole seconds.');const dt=Math.min(seconds,1200-model.elapsed);return {...model,state:stepState(model.state,dt),elapsed:model.elapsed+dt,...record(model,{kind:'advance',seconds:dt})};}
/** Only a paid repair is exposed here; initial scenarios prepare the earlier real actions. */
export function actCampaignGuidanceScenario(model:CampaignGuidanceScenarioModel,action:'repair'):CampaignGuidanceScenarioModel {if(action!=='repair')throw Error('Unsupported rehearsal action.');const placed={...model.state,player:{...model.state.player,x:WORKSHOP_BOARD.x,z:WORKSHOP_BOARD.z}},command={kind:'repair' as const,expectedRevision:placed.workshopConstruction?.revision??0},next=commitWorkshopConstruction(placed,command);return {...model,state:next,...record(model,{kind:'construction-command',command,player:placed.player,accepted:next!==placed})};}
export const CAMPAIGN_GUIDANCE_SCENARIO_ENGINE=Object.freeze({kind:'axiom-campaign-guidance-scenarios' as const,create:createCampaignGuidanceScenario,step:stepCampaignGuidanceScenario,act:actCampaignGuidanceScenario});
