/** Read-only campaign projections. Models remain the sole owners of actions, costs and progress. */
import {worldTownSupplySources,worldRestorationPlan,type State} from './world.ts';
import {townSupplyPosition} from './town-supply.ts';
import {WORKSHOP_BOARD,workshopConstructionQuote} from './workshop-construction.ts';
import {DEFAULT_WORKSHOP_DRAFT} from './workshop-authoring.ts';
import {restorationCareHarvestable,restorationCellViable} from './restoration.ts';
import {restorationCarePosition} from './restoration-care.ts';
import {townLifeFacilities} from './town-life.ts';
import {townLifeSituation} from './town-life-dialogue.ts';
import {townResidents} from './town-residents.ts';
import {selectRegionalObjective} from './regional-objective.ts';
export const CAMPAIGN_GOAL_IDS=Object.freeze(['supply','construction','restoration','care','regional','town'] as const);
export type CampaignGoalId=(typeof CAMPAIGN_GOAL_IDS)[number];
export type CampaignGuidanceStatus='actionable'|'blocked'|'waiting'|'complete'|'available';
export interface CampaignGuidanceTarget {id:string;label:string;x:number;y:number;z:number;panel:'town-supply'|'workshop-construction'|'restoration'|'restoration-care'|'town-life'|'regional-supply'|'regional-trade'|'regional-food';selectionId?:string}
export interface CampaignGuidanceCard {id:CampaignGoalId;title:string;status:CampaignGuidanceStatus;summary:string;progress:string;requirements:readonly string[];target:CampaignGuidanceTarget|null}
export interface CampaignGuidanceOptions {sourceId?:string;siteId?:string;host?:boolean}
const distance=(a:{x:number;z:number},b:{x:number;z:number})=>Math.hypot(a.x-b.x,a.z-b.z);
const nearest=<T extends {id:string;x:number;z:number}>(all:readonly T[],player:State['player'],id?:string)=>all.find(v=>v.id===id)??[...all].sort((a,b)=>distance(a,player)-distance(b,player)||a.id.localeCompare(b.id))[0];
const unavailable=(id:CampaignGoalId,title:string,summary:string):CampaignGuidanceCard=>({id,title,status:'blocked',summary,progress:'Not initialized',requirements:['This guidance does not initialize or reset campaign systems.'],target:null});
function freeze<T>(v:T):T {if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.values(v).forEach(freeze);Object.freeze(v);}return v;}
export function campaignTargetDirection(player:{x:number;z:number},target:{x:number;z:number}){const dx=target.x-player.x,dz=target.z-player.z,metres=Math.hypot(dx,dz),names=['N','NE','E','SE','S','SW','W','NW'];return {distance:metres,bearing:metres<.01?'Here':names[(Math.round(Math.atan2(dx,dz)/(Math.PI/4))+8)%8]!};}
export function projectCampaignGuidance(state:State,options:CampaignGuidanceOptions={}):CampaignGuidanceCard[]{
 const cards:CampaignGuidanceCard[]=[],life=state.townLife,regional=!!state.regional&&state.generation===2;
 if(!regional){return freeze(CAMPAIGN_GOAL_IDS.map(id=>unavailable(id,({supply:'Town supply',construction:'West workshop',restoration:'Habitat restoration',care:'Habitat care',regional:'Regional projects',town:'Hearthmere'}as const)[id],'This connection belongs to a regional frontier. Existing valley progress is unchanged.')));}
 const host=options.host===false?['The host performs shared cargo, construction and habitat-care transactions; you can inspect and navigate.']:[];
 const supply=state.townSupply,cargo=supply?.carried??0,sources=worldTownSupplySources(state),remaining=sources.filter(s=>!state.collected.includes(s.id)),source=nearest(remaining,state.player,options.sourceId),destination=townSupplyPosition(state.seed,sources,{kind:'deliver',targetId:'workshop'})!;
 const supplyTarget:CampaignGuidanceTarget={id:'town-supply/workshop',label:'Second Life Salvage delivery station',...destination,panel:'town-supply',selectionId:'workshop'};
 if(!life)cards.push(unavailable('supply','Bring materials to town','Visit Hearthmere to initialize the existing town economy.'));
 else {
  let status:CampaignGuidanceStatus='actionable',title='Load finite valley scrap',summary='Choose a remaining cache. Loading reserves one real scrap as cargo; ordinary pickup remains a separate choice.',target:CampaignGuidanceTarget|null=source?{id:`town-supply/${source.id}`,label:source.label??'Valley salvage cache',x:source.x,y:source.y??0,z:source.z,panel:'town-supply',selectionId:source.id}:null;
  const requirements=['Four-piece cargo capacity. Deliver two cargo for twelve shared materials; unload one at the same workshop into ordinary inventory.',...host];
  if(cargo>=2){title='Deliver carried scrap to town';target=supplyTarget;summary='Two carried scrap become twelve shared materials through the existing donation station; ordinary inventory is not charged again.';if(life.cooldowns.donate>0){status='waiting';summary=`The shared donation station has ${life.cooldowns.donate.toFixed(1)} seconds of cooldown. Close solo menus to let active time pass.`;}else if(life.resources.materials>588){status='blocked';summary='The town store needs room for twelve material portions. Keep the cargo or unload it into ordinary inventory.';}}
  else if(!source&&cargo===1){title='Unload the last cargo scrap';summary='No eligible cache remains to make a two-piece delivery. Unload this one piece at Second Life Salvage into ordinary inventory.';target=supplyTarget;}
  else if(!source){status='complete';title='Finite supply route exhausted';summary='All seven canonical valley caches are collected. Ordinary inventory donations and residents’ existing salvage work remain available; caches do not respawn.';target=supplyTarget;}
  else if(cargo===1)summary='One more remaining cache makes a delivery pair. You can also unload the carried piece at Second Life Salvage.';
  cards.push({id:'supply',title,status,summary,progress:`${cargo}/4 cargo · ${remaining.length}/${sources.length} caches remain · ${supply?.deliveries??0} deliveries · ${life.resources.materials.toFixed(1)}/600 materials`,requirements,target});
 }
 const built=state.workshopConstruction,quote=workshopConstructionQuote(built?.parameters??{...DEFAULT_WORKSHOP_DRAFT,seed:state.seed}),constructionTarget:CampaignGuidanceTarget={id:'workshop-board',label:'Northwest workshop board',...WORKSHOP_BOARD,panel:'workshop-construction'};
 if(!life)cards.push(unavailable('construction','A place to repair','Visit Hearthmere before reviewing a permanent workshop commission.'));
 else if(!built){const short=Math.max(0,quote.materials-life.resources.materials);cards.push({id:'construction',title:'Commission the west workshop',status:short>0?'blocked':'available',summary:short>0?`The default plan needs ${short.toFixed(1)} more shared materials. Supply deliveries, ordinary donations and resident salvage feed the same store.`:'The default plan is funded. Review the bounded recipe and an available resident at the northwest board before committing.',progress:`Default quote ${quote.materials} materials · ${life.resources.materials.toFixed(1)} available`,requirements:['The construction panel owns the exact applied recipe and quote. No demolition or refunds. Materials remain shared until paid.',...host],target:constructionTarget});}
 else if(built.status==='building'){const r=life.residents.find(r=>r.id===built.workerId),name=townResidents(state.seed).find(r=>r.id===built.workerId)?.name??'Assigned resident',f=townLifeFacilities(state.seed).find(f=>f.id==='workshop')!;cards.push({id:'construction',title:'Workshop prefabrication underway',status:'waiting',summary:`${name}: ${r?.reason??'Inspect the assigned worker.'} Work counts only after achieved arrival at Second Life Salvage. The commission is already paid.`,progress:`${built.work.toFixed(1)}/${built.workRequired} achieved craft seconds · ${built.materialsPaid} materials paid`,requirements:['Urgent needs and other paid activities take priority. Close solo menus for simulation to advance. No extra construction payment is needed.',...host],target:{...constructionTarget,id:'workshop-prefabrication',label:'Second Life Salvage prefabrication',x:f.x,y:6,z:f.z}});}
 else cards.push({id:'construction',title:state.player.hp>=100?'Workshop complete · repair service ready':'Repair your suit at the new workshop',status:state.player.hp>=100?'complete':life.resources.materials>=4&&built.repairs<1000?'actionable':'blocked',summary:state.player.hp>=100?'The permanent workshop is complete. Your suit is undamaged; its paid repair service remains available when needed.':built.repairs>=1000?'The bounded service ledger is full.':life.resources.materials<4?'Suit repair needs four shared town materials.':'Four shared materials restore up to 25 suit HP. Review and pay at the northwest board.',progress:`${built.repairs} repairs · ${Math.round(state.player.hp)}/100 suit HP · ${life.resources.materials.toFixed(1)} materials`,requirements:['The completed building and its collision remain part of this saved world.',...host],target:constructionTarget});
 const plan=state.restoration?worldRestorationPlan(state.seed):null,site=plan?nearest(plan.sites,state.player,options.siteId):undefined,siteState=site?state.restoration!.sites.find(s=>s.id===site.id):undefined;
 if(!plan||!site||!siteState)cards.push(unavailable('restoration','Restore a habitat','Habitat restoration is not initialized in this saved world. Open the existing restoration controls when available.'));
 else {const harvest=restorationCareHarvestable(state.restoration!,site.id),point=restorationCarePosition(plan,{kind:'collect',targetId:site.id})!;cards.push({id:'restoration',title:siteState.completedAtTick===null?`Restore ${site.label}`:`${site.label} · restoration recorded`,status:siteState.completedAtTick===null?state.restoration!.machine?.siteId===site.id&&state.restoration!.machine?.status==='working'||siteState.activatedAtTick!==null&&siteState.cells.some(c=>restorationCellViable(c)&&c.nutrient>0)?'waiting':'available':'complete',summary:siteState.completedAtTick===null?'Use the actual automaton controls to improve water, contamination, heat and smoke. Vegetation must grow and remain healthy before restoration completes.':harvest>=5?'This restored habitat currently has a collectible surplus for Greenlight care.':'Restoration was achieved; current viable surplus is insufficient for a five-portion care bundle. Historical completion does not promise current harvestability.',progress:`${siteState.cells.filter(restorationCellViable).length}/${siteState.cells.length} viable cells · ${siteState.cells.filter(c=>c.health>=70).length}/${siteState.cells.length} cells at 70 health · ${harvest} collectible biomass`,requirements:['Refits and servicing use existing finite inventory and dock reserves. Inspect exact current machine and cell blockers in restoration.',...host],target:{id:site.id,label:site.label,...point,panel:'restoration',selectionId:site.id}});}
 const care=state.restorationCare,carried=care?.carried??0,stock=life?.habitatCare;
 if(!life||!plan||!state.restoration)cards.push(unavailable('care','Bring restoration home','Town life and habitat restoration must both be initialized before care deliveries.'));
 else {const harvestSites=plan.sites.filter(p=>restorationCareHarvestable(state.restoration!,p.id)>=5),selected=plan.sites.find(s=>s.id===options.siteId),pick=selected??nearest(harvestSites,state.player)??site!,harvest=restorationCareHarvestable(state.restoration,pick.id),point=restorationCarePosition(plan,{kind:'collect',targetId:pick.id})!;let target:CampaignGuidanceTarget={id:pick.id,label:pick.label,...point,panel:'restoration-care',selectionId:pick.id},title='Collect restored habitat surplus',status:CampaignGuidanceStatus=harvest>=5?'actionable':'blocked',summary=harvest>=5?'Collect five real surplus biomass portions at this dock, retaining two per cell. Carry them to Greenlight Apothecary.':'The selected habitat needs recorded restoration, current viability and health of at least 70 in every cell, plus five surplus biomass.';
  if(carried>0){const p=restorationCarePosition(plan,{kind:'deliver',targetId:'apothecary'})!;target={id:'habitat-care/apothecary',label:'Greenlight care station',...p,panel:'restoration-care',selectionId:'apothecary'};title='Deliver habitat care to Greenlight';status=(stock?.stock??0)+carried>20?'waiting':'actionable';summary=status==='waiting'?'Greenlight needs room for the whole carried bundle. Residents consume portions only when they actually arrive to begin care; close solo menus to let them act.':`Deliver the ${carried} carried portions. No additional biomass is created and ordinary town care costs remain.`;}
  else if((stock?.stock??0)>0){status='waiting';title=stock!.stock>=20?'Greenlight care stock is full':'Care delivered · awaiting resident use';summary=`${stock!.stock} portions remain at Greenlight. Residents must choose care and physically arrive before a portion is committed. Stock does not guarantee a visit or a completed treatment.`;const p=restorationCarePosition(plan,{kind:'deliver',targetId:'apothecary'})!;target={id:'habitat-care/apothecary',label:'Greenlight care station',...p,panel:'restoration-care',selectionId:'apothecary'};}
  else if((stock?.used??0)>0){status='complete';title='Care delivery cycle supplied';summary=`Your delivered stock has been committed on ${stock!.used} actual care arrivals. This records supplied treatments, not completed healing. Replenishment is optional${harvest>=5?' at this viable habitat.':'; no viable five-portion surplus is currently selected.'}`;}
  cards.push({id:'care',title,status,summary,progress:`${carried}/10 carried · ${care?.delivered??0} delivered · ${stock?.stock??0}/20 stocked · ${stock?.used??0} portions committed on actual care arrival`,requirements:['One portion supports 1.5× energy, hygiene and comfort recovery only during achieved care work. Waiting and travel receive no bonus.',...host],target});
 }
 const objective=selectRegionalObjective(state);
 cards.push(objective?{id:'regional',title:objective.title,status:objective.status==='completed'?'complete':objective.status,summary:objective.copy,progress:objective.progress,requirements:['Existing regional guidance is read-only; its source systems and authoritative actions are unchanged.'],target:{id:objective.inspect.targetId,label:objective.inspect.label,...objective.position,panel:objective.inspect.kind==='trade'?'regional-trade':objective.inspect.kind==='food'?'regional-food':'regional-supply',selectionId:objective.inspect.targetId}}:unavailable('regional','Regional projects','No regional objective is currently selected. Existing waterworks and town tasks remain available.'));
 if(!life)cards.push(unavailable('town','Life in Hearthmere','Visit Hearthmere to initialize its existing residents and services.'));
 else {const situation=townLifeSituation(life),resident=situation.residentId?life.residents.find(r=>r.id===situation.residentId):undefined,square=townLifeFacilities(state.seed).find(f=>f.id==='square')!;cards.push({id:'town',title:situation.title,status:'available',summary:situation.detail,progress:`${life.residents.length} residents · ${life.resources.materials.toFixed(1)} shared materials`,requirements:['Needs, routines, requests and their costs remain owned by the living-town model.'],target:{id:resident?.id??'square',label:resident?townResidents(state.seed)[resident.index]!.name:'Hearthmere meeting square',x:resident?.x??square.x,y:6,z:resident?.z??square.z,panel:'town-life',...(resident?{selectionId:resident.id}:{})}});}
 if(state.zone!=='valley')return freeze(cards.map(c=>({...c,status:'blocked' as const,summary:'Return to the surface to follow this campaign connection. '+c.summary,target:null,requirements:['Surface destinations cannot be reached from this underground position.',...c.requirements]})));
 if(state.player.hp<=0)return freeze(cards.map(c=>({...c,status:'blocked' as const,summary:'Recover your explorer before acting. '+c.summary})));
 return freeze(cards);
}
export const CAMPAIGN_GUIDANCE_ENGINE=Object.freeze({kind:'axiom-campaign-guidance' as const,project:projectCampaignGuidance,direction:campaignTargetDirection});
