import {mountCampaignGuidance} from './campaign-guidance-ui.ts';
import {projectCampaignGuidance} from './campaign-guidance.ts';
import type {CampaignGuidanceSelection} from './campaign-guidance-storage.ts';
import {CAMPAIGN_GUIDANCE_SCENARIO_ENGINE as ENGINE,CAMPAIGN_GUIDANCE_SCENARIOS,type CampaignGuidanceScenario} from './campaign-guidance-scenarios.ts';
import {DEVELOPER_BUILD} from './developer-tools.ts';
export const CAMPAIGN_GUIDANCE_LAB_FIELDS=Object.freeze([{key:'seed',min:0,max:4294967295,step:1,default:73129,unit:'uint32',consumer:'Canonical sources, habitats and 100 residents',timing:'Apply setup & reset'},{key:'seconds',min:1,max:60,step:1,default:10,unit:'active seconds',consumer:'Actual world tick and achieved construction work',timing:'Step real model'}] as const);
export interface CampaignGuidancePreset {format:'axiom-campaign-guidance-preset';version:1;scope:'disposable-model';seed:number;scenario:CampaignGuidanceScenario;source:string}
const provenance=(v:unknown):v is string=>typeof v==='string'&&v.length>0&&v.length<=160&&/^[a-zA-Z0-9][a-zA-Z0-9._:/ -]*$/.test(v);
export function createCampaignGuidancePreset(seed:number,source:string):CampaignGuidancePreset{return parseCampaignGuidancePreset(JSON.stringify({format:'axiom-campaign-guidance-preset',version:1,scope:'disposable-model',seed,scenario:'opening',source:provenance(source)?source:'source-unavailable'}));}
export function parseCampaignGuidancePreset(raw:string):CampaignGuidancePreset {if(typeof raw!=='string'||raw.length>4096||new TextEncoder().encode(raw).length>4096)throw Error('Guidance preset exceeds 4 KB.');let v:unknown;try{v=JSON.parse(raw);}catch{throw Error('Enter a JSON guidance preset.');}const fields=[...raw.matchAll(/"((?:\\.|[^"\\])*)"\s*:/g)].map(m=>JSON.parse('"'+m[1]+'"'));if(new Set(fields).size!==fields.length)throw Error('Duplicate guidance preset field.');const keys=['format','version','scope','seed','scenario','source'];if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||!keys.every(k=>Object.hasOwn(v,k)))throw Error('Unexpected guidance preset fields.');const p=v as Record<string,unknown>;if(p.format!=='axiom-campaign-guidance-preset'||p.version!==1||p.scope!=='disposable-model'||!Number.isSafeInteger(p.seed)||Number(p.seed)<0||Number(p.seed)>0xffffffff||!CAMPAIGN_GUIDANCE_SCENARIOS.includes(p.scenario as CampaignGuidanceScenario)||!provenance(p.source))throw Error('Unsupported guidance preset bounds, version or scenario.');return structuredClone(p) as unknown as CampaignGuidancePreset;}
const labels:Record<CampaignGuidanceScenario,string>={opening:'Opening · no materials or fabricated progress','supply-to-workshop':'Six caches → three deliveries → paid workshop commission','care-delivered':'Earn habitat restoration → collect → deliver care','workshop-complete':'Achieved construction → paid repair → final cache unloaded'};
/** This owner never receives campaign state or storage. Tracking exists only in local memory. */
export function mountCampaignGuidanceLab(panel:HTMLElement,options:{seed:number;source?:string;onClose:()=>void}){
 const defaults=createCampaignGuidancePreset(options.seed,options.source??'source-unavailable');let applied=structuredClone(defaults),model=ENGINE.create(applied.seed,applied.scenario),selection:CampaignGuidanceSelection={goalId:null},disposed=false,generation=0;let journal:ReturnType<typeof mountCampaignGuidance>;
 panel.innerHTML=`<button id="cgl-close" class="close" aria-label="Close guidance rehearsal">×</button><span class="eyebrow">Developer · disposable campaign rehearsal</span><h2>Follow the connected loop</h2><p>This memory-only model never reads campaign saves or personal tracking storage. It uses canonical sources and actual paid commands. The workshop scenario begins with zero shared materials, loads six finite caches, delivers three pairs for 36 materials, then pays the default 31-material commission. All 100 residents keep their actual needs and navigation. Further salvage production and spending change the balance during work.</p><p>The completed scenario waits for achieved worker arrival and 72 seconds of real crafting, pays four shared materials to repair a 75-HP suit, and unloads the seventh cache. No completion flag, free stock or worker teleport is inserted. The care scenario earns restoration using the existing finite rig preparation. Every operator placement is explicit model setup; physical travel and device visuals are not certified.</p><label for="cgl-seed">Seed · uint32, reset-time</label><input id="cgl-seed" type="number" min="0" max="4294967295" step="1"><label for="cgl-scenario">Actual preparation · reset-time</label><select id="cgl-scenario">${CAMPAIGN_GUIDANCE_SCENARIOS.map(id=>`<option value="${id}">${labels[id]}</option>`).join('')}</select><div class="row"><button id="cgl-reset-draft" type="button">Apply setup & reset</button><button id="cgl-reset" type="button">Reset applied model</button><button id="cgl-discard" type="button">Discard edits</button><button id="cgl-defaults" type="button">Stage defaults</button></div><p id="cgl-status" role="status"></p><label for="cgl-seconds">Step · 1–60 whole active seconds</label><input id="cgl-seconds" type="number" min="1" max="60" step="1" value="10"><button id="cgl-step" type="button">Step real model</button><button id="cgl-repair" type="button">Place model operator at board & request paid repair</button><p>Preparation is bounded to 1,200 seconds and recorded separately. Manual simulation is bounded to 1,200 seconds per reset with no timer or offline catch-up. Rules, costs, finite source counts and progress thresholds are fixed; no resource multipliers are exposed.</p><div id="cgl-journal"></div><h3>Reproduce and inspect</h3><button id="cgl-preset" type="button">Export applied preset to text</button><button id="cgl-report" type="button">Export evidence to text</button><button id="cgl-import" type="button">Stage preset text</button><label for="cgl-text">JSON text fallback · preset import limit 4 KB</label><textarea id="cgl-text" rows="10"></textarea><label for="cgl-file">Stage preset file</label><input id="cgl-file" type="file" accept="application/json,.json">`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#cgl-'+id)!;const marker=q('status'),current=()=>!disposed&&panel.querySelector('#cgl-status')===marker;
 function status(message='Paused; only explicit Step advances the model.'){if(current())marker.textContent=`Applied seed ${applied.seed} · ${labels[applied.scenario]} · ${model.preparationSeconds.toFixed(1)} preparation seconds · ${model.elapsed}/1200 manual seconds. ${message}`;}
 function fill(p:CampaignGuidancePreset){q<HTMLInputElement>('seed').value=String(p.seed);q<HTMLSelectElement>('scenario').value=p.scenario;}
 function draft(){return parseCampaignGuidancePreset(JSON.stringify({...applied,seed:q<HTMLInputElement>('seed').value.trim()?Number(q<HTMLInputElement>('seed').value):NaN,scenario:q<HTMLSelectElement>('scenario').value}));}
 function mount(){journal?.dispose();journal=mountCampaignGuidance(q('journal'),{getState:()=>model.state,getSelection:()=>selection,onTrack:s=>{if(current()){selection=structuredClone(s);generation++;status('Tracked only in this disposable rehearsal.');}},onUntrack:()=>{if(current()){selection={goalId:null};generation++;status('Disposable tracking cleared.');}},onInspect:t=>status(`Read-only model target: ${t.label}; real panel ${t.panel}. Use the campaign panel after closing this lab.`),onMap:t=>status(`Model map target: ${t.label}, x ${t.x.toFixed(1)}, z ${t.z.toFixed(1)}. No campaign map was changed.`),onClose:()=>{dispose();options.onClose();},disposable:true});}
 function reset(p:CampaignGuidancePreset){const next=ENGINE.create(p.seed,p.scenario);model=next;applied=structuredClone(p);selection={goalId:null};generation++;fill(applied);mount();status('Reset replaced only disposable state and tracking.');}
 function guarded(fn:()=>void){return ()=>{if(current()){generation++;try{fn();}catch(e){status(e instanceof Error?e.message:String(e));}}};}
 function staged(){if(current()){generation++;status('Setup edits staged. Apply setup & reset to use them.');}}
 function step(seconds:number){if(!current())return;model=ENGINE.step(model,seconds);generation++;journal.refresh();status(model.elapsed===1200?'Manual time limit reached; reset to repeat.':'Actual town work and existing world kernels advanced.');}
 q<HTMLInputElement>('seed').oninput=staged;q<HTMLSelectElement>('scenario').onchange=staged;q('reset-draft').onclick=guarded(()=>reset(draft()));q('reset').onclick=guarded(()=>reset(applied));q('discard').onclick=guarded(()=>{fill(applied);status('Unapplied edits discarded.');});q('defaults').onclick=guarded(()=>{fill(defaults);staged();});q('step').onclick=guarded(()=>step(Number(q<HTMLInputElement>('seconds').value)));q('repair').onclick=guarded(()=>{const before=model.state;model=ENGINE.act(model,'repair');journal.refresh();status(model.state.workshopConstruction?.repairs!==before.workshopConstruction?.repairs?'Paid workshop repair accepted by the real kernel.':'Repair blocked: complete construction, need suit damage and retain four shared materials. Model operator placement is recorded.');});
 function report(){return {format:'axiom-campaign-guidance-evidence',version:1,scope:'disposable-model',build:DEVELOPER_BUILD,source:defaults.source,visualReview:'not-reviewed',applied,intended:{seed:q<HTMLInputElement>('seed').value,scenario:q<HTMLSelectElement>('scenario').value},selection,cards:projectCampaignGuidance(model.state,{...(selection.sourceId?{sourceId:selection.sourceId}:{}),...(selection.siteId?{siteId:selection.siteId}:{})}),initialInventory:model.initialInventory,preparation:model.preparation,preparationSeconds:model.preparationSeconds,elapsed:model.elapsed,actual:model.state,actions:model.actions,actionsTruncated:model.actionsTruncated};}
 q('preset').onclick=guarded(()=>{q<HTMLTextAreaElement>('text').value=JSON.stringify(applied,null,2);status('Applied preset prepared in text.');});q('report').onclick=guarded(()=>{q<HTMLTextAreaElement>('text').value=JSON.stringify(report(),null,2);status('Reproducible model evidence prepared in text.');});function stage(raw:string){fill(parseCampaignGuidancePreset(raw));staged();}q('import').onclick=guarded(()=>stage(q<HTMLTextAreaElement>('text').value));q<HTMLTextAreaElement>('text').oninput=()=>{generation++;};q<HTMLInputElement>('file').onchange=async()=>{if(!current())return;const ticket=++generation,file=q<HTMLInputElement>('file').files?.[0];if(!file)return;try{if(file.size>4096)throw Error('Guidance preset exceeds 4 KB.');const raw=await file.text();if(current()&&ticket===generation)stage(raw);}catch(e){if(current()&&ticket===generation)status(String(e));}};
 function dispose(){if(disposed)return;disposed=true;generation++;journal?.dispose();}q('close').onclick=guarded(()=>{dispose();options.onClose();});fill(applied);mount();status();return {dispose,step,report,getState:()=>model.state};
}
