import {CAMPAIGN_GOAL_IDS,projectCampaignGuidance,campaignTargetDirection,type CampaignGoalId,type CampaignGuidanceTarget} from './campaign-guidance.ts';
import type {CampaignGuidanceSelection} from './campaign-guidance-storage.ts';
import {worldTownSupplySources,worldRestorationPlan,type State} from './world.ts';
export interface CampaignGuidanceUIOptions {getState:()=>State;getSelection:()=>CampaignGuidanceSelection;onTrack:(selection:CampaignGuidanceSelection)=>void;onUntrack:()=>void;onInspect:(target:CampaignGuidanceTarget)=>void;onMap:(target:CampaignGuidanceTarget)=>void;onClose:()=>void;host?:()=>boolean;disposable?:boolean}
const labels:Record<CampaignGoalId,string>={supply:'Bring materials to town',construction:'Build the west workshop',restoration:'Restore a habitat',care:'Bring habitat care home',regional:'Regional projects',town:'Hearthmere needs'};
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
/** Journal projections never execute gameplay commands. Tracking owns only personal pointers. */
export function mountCampaignGuidance(panel:HTMLElement,options:CampaignGuidanceUIOptions){
 let disposed=false;const selection=options.getSelection();let goal:CampaignGoalId=selection.goalId??'supply',sourceId=selection.sourceId,siteId=selection.siteId;
 panel.innerHTML=`<button id="cg-close" class="close" aria-label="Close field plan">×</button><span class="eyebrow">Field plan · ${options.disposable?'disposable model':'campaign journal'}</span><h2>Choose your next step</h2><p>These six connections read the existing world. Choosing a goal never spends materials, assigns a worker, collects a cache or starts a restoration command. Track one personal pointer, then inspect the existing controls to act.</p><p>Distance and compass bearing point directly toward the target; they are not a checked walking route. Terrain, doors, collisions and interaction range still apply. ${options.disposable?'This panel observes only the disposable rehearsal. Tracking never uses device storage.':'Solo menus pause work. Close the journal to let residents, prefabrication and habitat work continue.'}</p><div id="cg-cards"></div><label for="cg-goal">Choose a goal</label><select id="cg-goal">${CAMPAIGN_GOAL_IDS.map(id=>`<option value="${id}">${labels[id]}</option>`).join('')}</select><label for="cg-source">Preferred supply source</label><select id="cg-source"></select><label for="cg-site">Preferred habitat</label><select id="cg-site"></select><h3 id="cg-title"></h3><p id="cg-summary"></p><p id="cg-progress"></p><pre id="cg-requirements"></pre><p id="cg-direction"></p><p id="cg-tracked"></p><div class="row"><button id="cg-track" type="button">Track this goal</button><button id="cg-untrack" type="button">Stop tracking</button><button id="cg-inspect" type="button">Inspect existing controls</button><button id="cg-map" type="button">Show target on map</button></div><p id="cg-status" role="status"></p>`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#cg-'+id)!;const marker=q('status'),current=()=>!disposed&&panel.querySelector('#cg-status')===marker;
 const state=options.getState(),sources=worldTownSupplySources(state),sites=state.regional?worldRestorationPlan(state.seed).sites:[];
 q('source').innerHTML='<option value="">Nearest remaining source</option>'+sources.map(s=>`<option value="${esc(s.id)}">${esc(s.label??s.id)}</option>`).join('');q('site').innerHTML='<option value="">Nearest habitat</option>'+sites.map(s=>`<option value="${esc(s.id)}">${esc(s.label)}</option>`).join('');q<HTMLSelectElement>('goal').value=goal;q<HTMLSelectElement>('source').value=sourceId??'';q<HTMLSelectElement>('site').value=siteId??'';
 const draft=():CampaignGuidanceSelection=>({goalId:goal,...(sourceId?{sourceId}:{}),...(siteId?{siteId}:{})});
 function cards(){return projectCampaignGuidance(options.getState(),{...(sourceId?{sourceId}:{}),...(siteId?{siteId}:{}),host:options.host?.()??true});}
 function selected(){return cards().find(c=>c.id===goal)!;}
 function refresh(){if(!current())return;const all=cards(),card=all.find(c=>c.id===goal)!,tracked=options.getSelection();q('cards').innerHTML=all.map(c=>`<article><strong>${esc(labels[c.id])}</strong> · ${esc(c.status)}<p>${esc(c.progress)}</p></article>`).join('');q('title').textContent=`${card.title} · ${card.status}`;q('summary').textContent=card.summary;q('progress').textContent=card.progress;q('requirements').textContent=card.requirements.map(r=>'• '+r).join('\n');const target=card.target,direction=target?campaignTargetDirection(options.getState().player,target):null;q('direction').textContent=target&&direction?`${target.label} · ${direction.distance.toFixed(1)} m ${direction.bearing} · x ${target.x.toFixed(1)}, y ${target.y.toFixed(1)}, z ${target.z.toFixed(1)}. Direct bearing only; no safe path is asserted.`:'No surface target is available for this goal in the current state.';q('tracked').textContent=tracked.goalId?`Currently tracked: ${labels[tracked.goalId]}. Choosing another goal stays pending until Track.`:'No goal tracked. Choose freely; nothing is accepted automatically.';q<HTMLButtonElement>('map').disabled=!target;q<HTMLButtonElement>('inspect').disabled=!target;q<HTMLButtonElement>('untrack').disabled=tracked.goalId===null;q<HTMLSelectElement>('source').disabled=goal!=='supply';q<HTMLSelectElement>('site').disabled=goal!=='restoration'&&goal!=='care';}
 q<HTMLSelectElement>('goal').onchange=()=>{if(!current())return;const value=q<HTMLSelectElement>('goal').value;if(CAMPAIGN_GOAL_IDS.includes(value as CampaignGoalId)){goal=value as CampaignGoalId;refresh();}};q<HTMLSelectElement>('source').onchange=()=>{if(current()){const value=q<HTMLSelectElement>('source').value;sourceId=sources.some(s=>s.id===value)?value:undefined;refresh();}};q<HTMLSelectElement>('site').onchange=()=>{if(current()){const value=q<HTMLSelectElement>('site').value;siteId=sites.some(s=>s.id===value)?value:undefined;refresh();}};
 q('track').onclick=()=>{if(current()){options.onTrack(draft());marker.textContent='Personal goal pointer updated. No gameplay action was requested.';refresh();}};q('untrack').onclick=()=>{if(current()){options.onUntrack();marker.textContent='Tracking cleared. Campaign progress is unchanged.';refresh();}};q('inspect').onclick=()=>{if(current()){const target=selected().target;if(target)options.onInspect(target);}};q('map').onclick=()=>{if(current()){const target=selected().target;if(target)options.onMap(target);}};
 function dispose(){disposed=true;}q('close').onclick=()=>{if(current()){dispose();options.onClose();}};refresh();return {refresh,dispose};
}
