import {caveSupplyView,type CaveSupplyState} from './cave-supply';
import {caveDepth,caveRouteOpen,caveWaterBalance,type CaveWaterCommand,type CaveWaterState} from './cave-water';
export function mountCavePanel(panel:HTMLElement,ctx:{state:CaveWaterState;inventory:{scrap:number;core:number};near:string|null;continuesInMenus?:boolean;supply?:CaveSupplyState;connect?:()=>void;act:(command:CaveWaterCommand)=>void;close:()=>void}){
 const s=ctx.state,supply=ctx.supply?caveSupplyView(ctx.supply):null;panel.innerHTML=`<button class="close" aria-label="Close river cave panel">×</button><span class="eyebrow">NATURAL RIVER CAVE · CONSERVED WATER</span><h2>${caveRouteOpen(s)?'The narrows are open':'Water blocks the narrows'}</h2><p>Three connected compartments exchange real water. The passage opens below 0.45 m in every compartment. A strong current prevents entering deeper water; either dry bank has a return line.</p><p>Upper rill ${caveDepth(s,0).toFixed(2)} m · narrows ${caveDepth(s,1).toFixed(2)} m · lower sump ${caveDepth(s,2).toFixed(2)} m</p><p>Pack: ${ctx.inventory.scrap} scrap · ${ctx.inventory.core} cores. Repair once. ${ctx.continuesInMenus?'The online world continues while this panel is open.':'Leave this panel to let water move; solo menus pause simulation.'}</p><h3>CHOOSE A REAL SOLUTION</h3><button id="cave-valve" ${ctx.near!=='valve'?'disabled':''}>${s.valveRepaired?(s.sourceOpen?'Close source gate':'Open source gate'):'Repair source valve · 2 scrap'}</button><p>Closes the inflow. The natural sump then drains the cave slowly.</p><button id="cave-pump" ${ctx.near!=='pump'?'disabled':''}>${s.pumpRepaired?(s.pumpOn?'Stop drainage pump':'Start drainage pump'):'Repair drainage pump · 1 scrap + 1 core'}</button><p>Discharges water outside the cave, even while the source flows.</p><button id="cave-drain" ${ctx.near!=='drain'||s.drainCleared?'disabled':''}>${s.drainCleared?'Sump drain cleared':'Clear sump drain · 1 scrap'}</button><p>Opening the drain increases outflow without consuming power.</p>${supply?`<h3>HOUSEHOLD OUTFALL DIVERSION</h3><button id="cave-connect" ${ctx.near!=='drain'||supply.connected||ctx.inventory.scrap<2?'disabled':''}>${supply.connected?'Outfall connected':'Connect outfall · 2 scrap'}</button><p>Use the dry-bank drain control. Meters new pumped or drained water into the existing household loading depot at up to 0.5 L/s. Carriers must deliver it along safe roads. This connection does not clear the flooded passage.</p><p>${supply.capturedLitres.toFixed(2)} L captured · ${supply.discardedCubicMetres.toFixed(2)} m³ discarded · ${supply.historicalCubicMetres.toFixed(2)} m³ historical output excluded. Excess is discarded immediately; no canisters or backlog are created.</p>`:''}<h3>WATER LEDGER</h3><p>${s.volume.reduce((n,v)=>n+v,0).toFixed(2)} m³ in cave · ${s.extracted.toFixed(2)} m³ from source · ${(s.pumped+s.drained+s.spilled).toFixed(2)} m³ discharged · balance error ${Math.abs(caveWaterBalance(s)).toExponential(1)} m³</p><p>This is a bounded conservative compartment model. It does not claim pressure, mixtures or full three-dimensional fluid dynamics.</p>`;
 panel.querySelector<HTMLButtonElement>('.close')!.onclick=ctx.close;
 const connect=panel.querySelector<HTMLButtonElement>('#cave-connect');if(connect)connect.onclick=()=>ctx.connect?.();
 panel.querySelector<HTMLButtonElement>('#cave-valve')!.onclick=()=>ctx.act(s.valveRepaired?{type:'set-source',on:!s.sourceOpen}:{type:'repair-valve'});
 panel.querySelector<HTMLButtonElement>('#cave-pump')!.onclick=()=>ctx.act(s.pumpRepaired?{type:'set-pump',on:!s.pumpOn}:{type:'repair-pump'});
 panel.querySelector<HTMLButtonElement>('#cave-drain')!.onclick=()=>ctx.act({type:'clear-drain'});
}
