import {applyCommonsTrade,commonsTradeView,COMMONS_TRADE_RULES,type CommonsTradeCommand} from './commons-trade.ts';
import type {CausalContext,CausalState} from './causal.ts';
export interface CommonsTradePanelOptions {state:()=>{causal:CausalState;context:CausalContext};act:(command:CommonsTradeCommand)=>void}
function element<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string,className?:string){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
/** Append this section to the frontier/workshop board; all effects remain reducer-owned. */
export function mountCommonsTradeSection(panel:HTMLElement,options:CommonsTradePanelOptions){
 const open=panel.querySelector<HTMLDetailsElement>('[data-commons-history]')?.open??false,focused=panel.contains(document.activeElement)?(document.activeElement as HTMLElement)?.dataset.commonsHousehold:undefined;
 const {causal,context}=options.state(),view=commonsTradeView(causal,context.seed);panel.replaceChildren();panel.className='frontier-section';panel.setAttribute('aria-label','Household barter and exchange history');
 panel.append(element('h3','HOUSEHOLD WATER BARTER'),element('p',`${view.materials} communal repair scrap remaining · ${view.exports} / ${COMMONS_TRADE_RULES.maxExchanges} lifetime exchanges`,'machine-status'),element('p','A household below 6 L offers 1 existing communal repair scrap for your canister. Its actual reserve receives 4 L. This removes scrap from the stock builders use to repair workshops, so trading can leave a workshop broken. Visit the household’s gold flag to exchange.','frontier-notice'));
 for(const h of view.households){const command:CommonsTradeCommand={type:'water-for-scrap',settlementId:h.id,expectedRevision:view.revision},row=element('div',undefined,'frontier-town'),b=element('button','Exchange 1 canister → 1 communal scrap','frontier-action');b.type='button';b.dataset.commonsHousehold=h.id;b.disabled=applyCommonsTrade(causal,context,command).state===causal;b.onclick=()=>{options.act(command);mountCommonsTradeSection(panel,options);};row.append(element('h4',h.name),element('p',`${h.reserve.toFixed(1)} L household reserve`),b);if(h.reserve>=6)row.append(element('p','No current offer: reserve is at least 6 L.','frontier-small'));else if(!view.materials)row.append(element('p','Communal repair stock is exhausted. Donations still work through the frontier board.','frontier-small'));else if(b.disabled)row.append(element('p',context.player.hp<=0?'Recover your suit before trading.':context.inventory.water<1?'Gather one water canister before trading.':'Visit this household’s gold flag in the valley to exchange.','frontier-small'));panel.append(row);}
 const history=element('details',undefined,'frontier-explainer');history.dataset.commonsHistory='true';history.open=open;history.append(element('summary','Recorded household exchanges'));if(!view.history.length)history.append(element('p','No exchanges since this record was opened. Earlier deliveries earn no scrap.'));else{const list=element('ol');for(const item of [...view.history].reverse())list.append(element('li',`${item.at.toFixed(1)}s · ${item.text}`));history.append(list);}panel.append(history);if(focused)for(const button of panel.querySelectorAll<HTMLButtonElement>('[data-commons-household]'))if(button.dataset.commonsHousehold===focused&&!button.disabled)button.focus({preventScroll:true});
}
