import {guardPoseFromState} from './avatar-combat';
import {createGuardView,confirmedGuardView} from './guard-view';
import * as THREE from 'three/webgpu';import {createAvatar} from './avatar';import {idleAnimation,stepAnimation,stepGroundSupport} from './locomotion';import type {CoopSnapshot,CoopPeer} from './coop';import type {EquipmentPlan} from './equipment';
export function createCoopView(){const root=new THREE.Group();root.name='online-explorers';const peers=new Map<string,{root:THREE.Group;avatar:ReturnType<typeof createAvatar>;animation:ReturnType<typeof idleAnimation>;target:THREE.Vector3;lastX:number;lastZ:number;vx:number;vz:number;stamp:number;landingId:number;guard:ReturnType<typeof createGuardView>;guardAge:number;guardStamp:string}>();
 const remove=(id:string)=>{const p=peers.get(id);if(!p)return;p.guard.dispose();p.root.removeFromParent();const materials=new Set<THREE.Material>();p.root.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Sprite){if(o instanceof THREE.Mesh)o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m);}});for(const m of materials){if('map'in m&&(m as THREE.MeshStandardMaterial).map)(m as THREE.MeshStandardMaterial).map!.dispose();m.dispose();}peers.delete(id);};
 return {root,update(snapshot:CoopSnapshot|null,zone:string,dt:number,equipment:EquipmentPlan|null){const present=new Set(snapshot?.peers.filter(p=>p.id!==snapshot.selfId).map(p=>p.id)??[]);for(const id of peers.keys())if(!present.has(id))remove(id);if(!snapshot)return;
 for(const peer of snapshot.peers){if(peer.id===snapshot.selfId)continue;let v=peers.get(peer.id);if(!v){const group=new THREE.Group(),avatar=createAvatar(),guard=createGuardView();group.add(avatar.root,guard.root);root.add(group);const c=document.createElement('canvas');c.width=256;c.height=64;const ctx=c.getContext('2d')!;ctx.font='bold 24px sans-serif';ctx.textAlign='center';ctx.fillStyle=['#b8edda','#a2dafa','#f6cf8c','#e7b8f6'][peer.slot]??'#fff';ctx.fillText(peer.name,128,38,242);const label=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),depthTest:false,transparent:true}));label.position.y=2.6;label.scale.set(3.7,.93,1);group.add(label);group.position.set(peer.player.x,peer.pose.y,peer.player.z);v={root:group,avatar,animation:idleAnimation(),target:group.position.clone(),lastX:peer.player.x,lastZ:peer.player.z,vx:0,vz:0,stamp:snapshot.serverTime,landingId:peer.motion?.landingId??0,guard,guardAge:0,guardStamp:''};peers.set(peer.id,v);}
 const guardStamp=peer.guard?`${peer.guard.time}:${peer.guard.castId}:${peer.guard.phase}:${peer.guard.spent}`:'';if(v.guardStamp!==guardStamp){v.guardStamp=guardStamp;v.guardAge=0;}else v.guardAge+=dt;if(peer.guard){v.guard.update(confirmedGuardView(peer.guard,v.guardAge),{x:0,y:0,z:0},true);if(!peer.connected||snapshot.paused||snapshot.closed)v.guard.root.visible=false;}else v.guard.root.visible=false;
 v.root.visible=peer.zone===zone&&peer.player.hp>0;v.target.set(peer.player.x,peer.pose.y,peer.player.z);if(snapshot.serverTime!==v.stamp){const seconds=Math.max(.1,(snapshot.serverTime-v.stamp)/1000);v.vx=Math.max(-8,Math.min(8,(peer.player.x-v.lastX)/seconds));v.vz=Math.max(-8,Math.min(8,(peer.player.z-v.lastZ)/seconds));v.lastX=peer.player.x;v.lastZ=peer.player.z;v.stamp=snapshot.serverTime;}const before=v.root.position.clone();v.root.position.lerp(v.target,1-Math.exp(-dt*14));if(peer.pose.grounded)v.root.position.y=v.target.y;const distance=Math.hypot(v.root.position.x-before.x,v.root.position.z-before.z);const vx=distance>.0001?v.vx:0,vz=distance>.0001?v.vz:0,landed=peer.motion&&peer.motion.landingId!==v.landingId?1:0;const previousAnimation=v.animation;v.animation=stepAnimation(v.animation,vx,vz,peer.pose.grounded,peer.pose.crouched,false,dt,distance,peer.pose.crouched?1:0,peer.motion?.vy??0,landed);v.landingId=peer.motion?.landingId??0;v.animation.heading=peer.pose.facing;v.animation=stepGroundSupport(previousAnimation,v.animation,v.root.position,'none',dt);v.avatar.setEquipment(equipment);const c=peer.combo;v.avatar.update(v.animation,null,0,c.attack&&c.stage?{stage:c.stage,phase:c.phase,progress:c.phaseElapsed/(c.phase==='prep'?c.attack.prep:c.phase==='active'?c.attack.active:c.attack.recovery)}:undefined,undefined,peer.guard&&peer.connected&&!snapshot.paused&&!snapshot.closed?guardPoseFromState(confirmedGuardView(peer.guard,v.guardAge)):undefined);
 }},dispose(){for(const id of peers.keys())remove(id);}};
}
