import {parseSave,serializeSave,type State} from './world.ts';
export interface SessionStore {getItem(key:string):string|null;setItem(key:string,value:string):void;removeItem(key:string):void}
export interface CoopBoot {version:1;roomId:string;world:State;solo:State;soloRevision?:number}
const BOOT='axiom-coop-bootstrap-v1',RETURN='axiom-coop-return-v1';
/** Session-only transport bootstrap; durable room authority remains in D1. */
export function readCoopBoot(store:SessionStore):CoopBoot|null {try{const raw=store.getItem(BOOT);if(!raw||raw.length>24_000_000)return null;const b=JSON.parse(raw);if(b?.version!==1||typeof b.roomId!=='string'||b.roomId.length<8||b.roomId.length>100)return null;const world=parseSave(JSON.stringify(b.world)),solo=parseSave(JSON.stringify(b.solo));const soloRevision=Number.isSafeInteger(b.soloRevision)&&b.soloRevision>=0?b.soloRevision:undefined;return world&&solo?{version:1,roomId:b.roomId,world,solo,...(soloRevision!==undefined?{soloRevision}:{})}:null;}catch{return null;}}
export function writeCoopBoot(store:SessionStore,roomId:string,world:State,solo:State,soloRevision?:number){if(!/^[a-zA-Z0-9_-]{8,100}$/.test(roomId))throw Error('Invalid room identity');store.setItem(BOOT,JSON.stringify({version:1,roomId,world:JSON.parse(serializeSave(world)),solo:JSON.parse(serializeSave(solo)),...(soloRevision!==undefined?{soloRevision}:{})}));}
export function queueSoloReturn(store:SessionStore,solo:State,soloRevision?:number){store.setItem(RETURN,soloRevision===undefined?serializeSave(solo):JSON.stringify({version:1,solo:JSON.parse(serializeSave(solo)),soloRevision}));store.removeItem(BOOT);}
export function consumeSoloReturnCheckpoint(store:SessionStore):{state:State;soloRevision?:number}|null {try{const raw=store.getItem(RETURN);if(!raw)return null;const value=JSON.parse(raw),wrapped=value?.version===1&&value.solo&&Number.isSafeInteger(value.soloRevision)&&value.soloRevision>=0;const state=parseSave(wrapped?JSON.stringify(value.solo):raw);if(!state)return null;store.removeItem(RETURN);return {state,...(wrapped?{soloRevision:value.soloRevision}:{})};}catch{return null;}}
export function consumeSoloReturn(store:SessionStore):State|null {return consumeSoloReturnCheckpoint(store)?.state??null;}
