import * as THREE from 'three/webgpu';
import {compileQuadruped,quadrupedFoot,quadrupedCycleDistance} from './body.ts';
import {ENEMY_RULES,type EnemyState} from './encounters.ts';
export function createQuadruped(seed:number){
 const plan=compileQuadruped(seed),root=new THREE.Group(),body=new THREE.Group();root.add(body);
 const materials=new Map<string,THREE.MeshStandardMaterial>();
 const add=(geo:THREE.BufferGeometry,color:string,parent:THREE.Object3D,x=0,y=0,z=0)=>{let m=materials.get(color);if(!m){m=new THREE.MeshStandardMaterial({color,roughness:.8,flatShading:true});materials.set(color,m);}const mesh=new THREE.Mesh(geo,m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;};
 const shell=add(new THREE.IcosahedronGeometry(.65,1),'#b78367',body,0,.8,0);shell.scale.set(plan.body.width/1.3,plan.body.height/1.3,plan.body.length/1.3);
 add(new THREE.BoxGeometry(.25,.07,.65),'#ddbd7c',body,0,1.34,0);
 const head=new THREE.Group();head.position.set(0,.83,plan.body.length/2);body.add(head);add(new THREE.IcosahedronGeometry(.26,0),'#756854',head);
 for(const [name,position]of Object.entries(plan.sockets)){const socket=new THREE.Object3D();socket.name=name;socket.position.set(position.x,position.y-.83,position.z-plan.body.length/2);head.add(socket);}
 const eye=add(new THREE.OctahedronGeometry(.105),'#ffca79',head,0,.06,.23);const eyeMaterial=eye.material as THREE.MeshStandardMaterial;
 const legs=plan.legs.map(l=>{const upper=new THREE.Group(),lower=new THREE.Group(),foot=new THREE.Group();upper.position.set(l.side*plan.body.width*.46,.77,l.end*plan.body.length*.34);root.add(upper);upper.add(lower);lower.position.y=-l.upper;lower.add(foot);foot.position.y=-l.lower;add(new THREE.CylinderGeometry(.075,.065,l.upper,5),'#705f50',upper,0,-l.upper/2,0);add(new THREE.CylinderGeometry(.06,.075,l.lower,5),'#4c5852',lower,0,-l.lower/2,0);add(new THREE.BoxGeometry(.17,.08,.24),'#d5b987',foot,0,0,.045);return {definition:l,phase:l.phase,side:l.side,upper,lower,foot};});
 const warning=new THREE.Mesh(new THREE.RingGeometry(.95,1.02,40,1,-Math.PI/2-ENEMY_RULES.arc/2,ENEMY_RULES.arc),new THREE.MeshBasicMaterial({color:'#ffd58d',transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));warning.rotation.x=-Math.PI/2;warning.position.y=.035;root.add(warning);
 const hpBack=new THREE.Mesh(new THREE.PlaneGeometry(1.1,.075),new THREE.MeshBasicMaterial({color:'#344d46',depthTest:false})),hp=new THREE.Mesh(new THREE.PlaneGeometry(1.08,.055),new THREE.MeshBasicMaterial({color:'#f4bd83',depthTest:false}));hpBack.rotation.x=hp.rotation.x=-Math.PI/2;hpBack.position.set(0,1.8,0);hp.position.set(0,1.81,0);root.add(hpBack,hp);
 return {root,plan,update(e:EnemyState){root.position.set(e.x,e.y,e.z);root.rotation.y=e.heading;root.visible=e.hp>0;const moving=(e.phase==='pursuit'||e.phase==='return')&&e.blocked===0,speed=moving?(e.phase==='pursuit'?2.3:1.6):0,phase=e.distance/quadrupedCycleDistance(speed);const prep=e.phase==='prepare'?1-e.remaining/ENEMY_RULES.prepare:0,strike=e.phase==='strike'?Math.sin(Math.PI*(1-e.remaining/ENEMY_RULES.strike)):0;body.position.y=-prep*.13+strike*.04;body.rotation.x=prep*.12-strike*.2;head.rotation.x=prep*-.25+strike*.4;eyeMaterial.color.set(e.phase==='prepare'?'#fff0a8':e.phase==='strike'?'#ff8e64':e.phase==='stagger'?'#adf2dd':'#ffca79');
 for(const l of legs){const f=quadrupedFoot(phase+l.phase,speed),y=-.72+f.y+prep*.13,d=Math.min(l.definition.upper+l.definition.lower-.002,Math.max(.06,Math.hypot(f.z,y))),dir=Math.atan2(-f.z,-y),bend=Math.acos(THREE.MathUtils.clamp((l.definition.upper*l.definition.upper+d*d-l.definition.lower*l.definition.lower)/(2*l.definition.upper*d),-1,1));l.upper.position.y=.77-prep*.13;l.upper.rotation.set(dir-bend,0,0);l.lower.rotation.x=Math.PI-Math.acos(THREE.MathUtils.clamp((l.definition.upper*l.definition.upper+l.definition.lower*l.definition.lower-d*d)/(2*l.definition.upper*l.definition.lower),-1,1));l.foot.rotation.x=-l.upper.rotation.x-l.lower.rotation.x;}
 warning.visible=e.phase==='prepare'||e.phase==='strike';warning.scale.setScalar(ENEMY_RULES.reach*(e.phase==='prepare'?.55+prep*.45:1));(warning.material as THREE.MeshBasicMaterial).color.set(e.phase==='strike'?'#ff885f':'#ffe1a3');hp.visible=hpBack.visible=e.hp<100||e.phase==='prepare'||e.phase==='strike';hp.scale.x=e.hp/100;hp.position.x=-(1-e.hp/100)*.54;},dispose(){root.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});for(const m of materials.values())m.dispose();warning.material.dispose();hp.material.dispose();hpBack.material.dispose();}};
}
