import {LAB_SCRIPTS} from './lab-script.ts';
import {DEFAULT_TUNING,sanitizeTuning,TUNING_FIELDS,type LabTuning,type TuningKey} from './tuning.ts';
import {createConnectedState,createState,serializeSave,parseSave,applyAction,activeObjects} from './world.ts';
import {worldValley,worldDungeon} from './generation.ts';
export const LAB_VERSION=1;
export const LAB_OBSTACLES=[
 {x:0,y:2.85,z:0,hx:2.5,hy:.2,hz:2.5},
 {x:0,y:1.5,z:8,hx:5,hy:.2,hz:1.2},
 {x:8,y:1.5,z:9.5,hx:2,hy:1.5,hz:.18},
];
export interface LabInput{x:number;z:number;crouch?:boolean;jump?:boolean;attack?:boolean;stun?:boolean;cancel?:boolean}
export interface LabTarget{id:string;x:number;y:number;z:number;hp:number}
export interface LabSample{x:number;z:number;feetY:number;vx:number;vz:number;vy:number;grounded:boolean;crouched:boolean;sliding:boolean;stance:number}
export interface CombatMetrics{hits:number;stages:number[];whiffs:number;blockedHits:number;stuns:number;cancelled:number;damage:number;hp:number}
export interface CaseMetrics{samples:number;maxSpeed:number;maxY:number;minX:number;maxX:number;negativeVX:boolean;positiveVX:boolean;low:boolean;slide:boolean;landed:boolean;last:LabSample;combat:CombatMetrics}
export interface Check{name:string;pass:boolean;actual:string;expected:string}
export interface LabCase{id:string;name:string;seconds:number;spawn:{x:number;z:number};facing:number;targets:LabTarget[];lookFor:string;input:(tick:number)=>LabInput;checks:(m:CaseMetrics,t:LabTuning)=>Check[]}
const target=(x:number,z:number):LabTarget=>({id:'lab-dummy',x,y:0,z,hp:100});
const check=(name:string,pass:boolean,actual:string,expected:string):Check=>({name,pass,actual,expected});
const finite=(m:CaseMetrics)=>check('Finite authoritative position',[m.last.x,m.last.z,m.last.feetY,m.maxSpeed].every(Number.isFinite),`${m.samples} worker samples`,'All sampled values are finite');
export const LAB_CASES:LabCase[]=[
 {id:'run-brake',name:'01 · Run & brake',seconds:2.5,spawn:{x:-12,z:-13},facing:Math.PI/2,targets:[],lookFor:'Speed should build cleanly, feet should plant, and releasing movement should produce a short weighted stop without walking in place.',input:LAB_SCRIPTS['run-brake']!.input,checks:(m,t)=>[finite(m),check('Reached sprint',m.maxSpeed>=7.7*t.speedScale,`${m.maxSpeed.toFixed(2)} m/s`,`≥ ${(7.7*t.speedScale).toFixed(2)} m/s`),check('Stopped after release',Math.hypot(m.last.vx,m.last.vz)<.08,`${Math.hypot(m.last.vx,m.last.vz).toFixed(3)} m/s`,'< 0.08 m/s after 1 s braking')]},
 {id:'turn',name:'02 · Reverse direction',seconds:2.8,spawn:{x:-12,z:-7},facing:Math.PI/2,targets:[],lookFor:'Look for a readable deceleration, body counter-lean and quick turn. The character should not skate sideways or snap its whole body instantly.',input:LAB_SCRIPTS['turn']!.input,checks:m=>[finite(m),check('Both directions resolved',m.positiveVX&&m.negativeVX,String(m.positiveVX&&m.negativeVX),'Positive and negative authoritative X velocity'),check('Brake after reversal',Math.hypot(m.last.vx,m.last.vz)<.08,`${Math.hypot(m.last.vx,m.last.vz).toFixed(3)} m/s`,'< 0.08 m/s')]},
 {id:'jump',name:'03 · Jump & landing',seconds:2.5,spawn:{x:-10,z:0},facing:0,targets:[],lookFor:'The leap should respond immediately with leg extension, airborne tuck and a soft landing. Holding Jump must not make repeated jumps.',input:LAB_SCRIPTS['jump']!.input,checks:(m,t)=>{const peak=t.jumpSpeed*t.jumpSpeed/(2*t.gravity);return [finite(m),check('Ballistic apex',Math.abs(m.maxY-peak)<.22,`${m.maxY.toFixed(3)} m`,`Expected about ${peak.toFixed(3)} m ±0.22`),check('Returned to support',m.last.grounded&&m.last.feetY<.04,`${m.last.feetY.toFixed(3)} m; grounded ${m.last.grounded}`,'Grounded at floor at end')];}},
 {id:'ceiling',name:'04 · Jump ceiling',seconds:1.5,spawn:{x:0,z:0},facing:0,targets:[],lookFor:'The head/staff must stay inside the visible ceiling. Upward momentum should stop on the ceiling, then the character should land without hovering.',input:LAB_SCRIPTS['ceiling']!.input,checks:m=>[finite(m),check('Ceiling blocks body',m.maxY<.54,`${m.maxY.toFixed(3)} m feet height`,'< 0.54 m under the 2.65 m ceiling'),check('Landed',m.last.grounded,String(m.last.grounded),'Grounded after ceiling hit')]},
 {id:'slide-crawl',name:'05 · Slide into crawl',seconds:5,spawn:{x:-9,z:8},facing:Math.PI/2,targets:[],lookFor:'Running into crouch should slide with momentum, then settle into a slow crawl. Releasing under the amber roof must retain the low pose; neither hat nor staff may poke through.',input:LAB_SCRIPTS['slide-crawl']!.input,checks:m=>[finite(m),check('Momentum slide observed',m.slide,String(m.slide),'At least one collision-resolved slide sample'),check('Entered low passage',m.maxX>-4.5,`${m.maxX.toFixed(2)} m X`,'Crossed passage entrance at -5 m'),check('Blocked stand stays low',m.last.crouched&&m.last.stance>=.99,String(m.last.crouched),'Crouched after releasing under the roof')]},
 {id:'combo',name:'06 · 1–2–3 combo',seconds:3.6,spawn:{x:8,z:-8},facing:0,targets:[target(8,-5.5)],lookFor:'Observe the opening sweep, backhand and committed finisher. Each needs anticipation, a clear contact beat and recovery. Three contacts should disable the 100 HP dummy; held auto uses these same rules.',input:LAB_SCRIPTS['combo']!.input,checks:m=>[finite(m),check('All three stages',m.combat.stages.includes(1)&&m.combat.stages.includes(2)&&m.combat.stages.includes(3),m.combat.stages.join(' → '),'1 → 2 → 3'),check('One hit per stage',m.combat.hits===3,String(m.combat.hits),'Exactly 3 accepted contacts'),check('Dummy depleted',m.combat.hp<=0,`${m.combat.hp} HP`,'100 HP dummy defeated by one full chain')]},
 {id:'whiff',name:'07 · Whiff & recovery',seconds:3.6,spawn:{x:8,z:0},facing:0,targets:[target(8,4.4)],lookFor:'Missing should still spend stamina and complete recovery. Mashing cannot skip to an active hit or teleport the staff toward the dummy.',input:LAB_SCRIPTS['whiff']!.input,checks:m=>[finite(m),check('No out-of-range hits',m.combat.hits===0,String(m.combat.hits),'0 contacts beyond maximum staff range'),check('Whiffs reported',m.combat.whiffs>=3,String(m.combat.whiffs),'At least 3 completed miss events')]},
 {id:'occlusion',name:'08 · Solid-wall protection',seconds:3.6,spawn:{x:8,z:8},facing:0,targets:[target(8,11)],lookFor:'The target behind the solid wall must remain undamaged through all combo stages. The sweep can be seen, but hits cannot pass through solid movement geometry.',input:LAB_SCRIPTS['occlusion']!.input,checks:m=>[finite(m),check('Wall rejected damage',m.combat.hits===0&&m.combat.hp===100,`${m.combat.hits} hits / ${m.combat.hp} HP`,'0 contacts / 100 HP')]},
 {id:'interrupt',name:'09 · Cancel & stun',seconds:2.4,spawn:{x:8,z:-8},facing:0,targets:[target(8,-5.5)],lookFor:'An early cancel should pull the staff back without a hit. The later injected stun should interrupt the windup and clear the buffer. These are explicit lab commands, not campaign enemy attacks.',input:LAB_SCRIPTS['interrupt']!.input,checks:m=>[finite(m),check('Cancel accepted',m.combat.cancelled>=1,String(m.combat.cancelled),'At least 1 accepted early cancel'),check('Stun observed',m.combat.stuns>=1,String(m.combat.stuns),'At least 1 stun event'),check('Interrupted before contact',m.combat.hits===0,String(m.combat.hits),'0 hits from interrupted windups')]},
];
export function newMetrics(sample:LabSample):CaseMetrics{return {samples:0,maxSpeed:0,maxY:0,minX:sample.x,maxX:sample.x,negativeVX:false,positiveVX:false,low:false,slide:false,landed:false,last:sample,combat:{hits:0,stages:[],whiffs:0,blockedHits:0,stuns:0,cancelled:0,damage:0,hp:100}};}
export function sampleMetrics(m:CaseMetrics,s:LabSample){m.samples++;m.maxSpeed=Math.max(m.maxSpeed,Math.hypot(s.vx,s.vz));m.maxY=Math.max(m.maxY,s.feetY);m.minX=Math.min(m.minX,s.x);m.maxX=Math.max(m.maxX,s.x);m.negativeVX ||= s.vx<-.1;m.positiveVX ||= s.vx>.1;m.low ||=s.crouched;m.slide ||=s.sliding;m.landed ||=s.grounded;m.last={x:s.x,z:s.z,feetY:s.feetY,vx:s.vx,vz:s.vz,vy:s.vy,grounded:s.grounded,crouched:s.crouched,sliding:s.sliding,stance:s.stance};}
export function frameSummary(values:readonly number[]){const a=values.filter(n=>Number.isFinite(n)&&n>0).slice().sort((x,y)=>x-y),at=(p:number)=>a.length?a[Math.max(0,Math.ceil(p*a.length)-1)]!:null;return {sampleCount:a.length,p50Ms:at(.5),p95Ms:at(.95),p99Ms:at(.99),maxMs:a.at(-1)??null,over33ms:a.filter(n=>n>33.333).length};}
/** These execute real model code in disposable worlds, never the active campaign. */
export function modelChecks(seed:number):Check[]{const checks:Check[]=[];const run=(name:string,fn:()=>boolean,expected:string)=>{try{const pass=fn();checks.push(check(name,pass,pass?'Observed expected result':'Invariant failed',expected));}catch(e){checks.push(check(name,false,String(e),expected));}};
 run('Seed repeatability',()=>JSON.stringify(worldValley(seed))===JSON.stringify(worldValley(seed))&&JSON.stringify(worldDungeon({seed,generation:2}))===JSON.stringify(worldDungeon({seed,generation:2})),'Same seed gives identical valley and dungeon plans');
 run('Different-seed geometry',()=>{const a=worldValley(seed),b=worldValley((seed+1)>>>0);return JSON.stringify(a.terrain.vertices)!==JSON.stringify(b.terrain.vertices);},'Neighbour seed changes terrain vertices');
 run('Persistence round trip',()=>{const s=createConnectedState(seed),copy=parseSave(serializeSave(s));return !!copy&&serializeSave(copy)===serializeSave(s);},'Serialized disposable world survives validated load exactly');
 run('Exactly-once collection & progression',()=>{let s=createState(seed);const o=activeObjects(s).find(o=>o.kind==='scrap')!;s=applyAction(s,{type:'move',x:o.x,z:o.z});s=applyAction(s,{type:'collect',id:o.id});const before=serializeSave(s);return s.inventory.scrap===1&&serializeSave(applyAction(s,{type:'collect',id:o.id}))===before;},'A collected resource cannot be awarded twice');
 run('Causal replay & save validation',()=>{let a=createConnectedState(seed),b=createConnectedState(seed);for(let i=0;i<240;i++){a=applyAction(a,{type:'tick',dt:1/60});b=applyAction(b,{type:'tick',dt:1/60});}return serializeSave(a)===serializeSave(b)&&!!parseSave(serializeSave(a));},'240 equal simulation inputs produce identical valid causal state');
 return checks;}
export interface LabRunReport{iteration:number;caseId:string;name:string;checks:Check[];metrics:CaseMetrics;frames:ReturnType<typeof frameSummary>}
export interface LabReport{version:number;status:'running'|'completed'|'interrupted';startedAt:string;finishedAt?:string;seed:number;tuning:LabTuning;iterations:number;warmupStepsPerCase:number;workload:string;capabilities:Record<string,unknown>;runs:LabRunReport[];model:Check[];manual:Record<string,'not-reviewed'|'pass'|'needs-work'>;interruption?:string}
export function createReport(seed:number,tuning:LabTuning,iterations:number,capabilities:Record<string,unknown>):LabReport{return {version:LAB_VERSION,status:'running',startedAt:new Date().toISOString(),seed,tuning:{...sanitizeTuning(tuning)},iterations:Number.isFinite(iterations)?Math.max(1,Math.min(5,Math.trunc(iterations))):3,warmupStepsPerCase:60,workload:'9 scenarios; fresh Rapier arena, targets, combat, input and camera per case; Worker-clock scripted inputs, fixed 60 Hz authoritative simulation. Frame intervals are actual render callbacks, not GPU time.',capabilities,runs:[],model:[],manual:Object.fromEntries(LAB_CASES.map(c=>[c.id,'not-reviewed']))};}
export {tuningControlsHTML as tuningHTML,rememberLabScenario,labTuningScenario,developerNavigationHTML,bindDeveloperNavigation,createLabPreset,parseLabPreset,LAB_PRESET_KEY,LAB_PRESET_LIMIT,LAB_QUICK_PRESETS,DEVELOPER_BUILD,validateLabTuning,resetTuningGroup} from './developer-tools.ts';
export {DEFAULT_TUNING,sanitizeTuning};

export function matchingPose(actual:unknown,expected:unknown){if(!actual||!expected||typeof actual!=='object'||typeof expected!=='object')return false;const a=actual as Record<string,unknown>,b=expected as Record<string,unknown>;return ['x','z','feetY','vy','stance'].every(k=>typeof a[k]==='number'&&typeof b[k]==='number'&&Number.isFinite(a[k])&&Number.isFinite(b[k])&&Math.abs((a[k] as number)-(b[k] as number))<1e-5)&&a.grounded===b.grounded&&a.crouched===b.crouched;}
