import {applyEcologyCommand,ecologyView,ECOLOGY_CROPS,ECOLOGY_RULES,ECOLOGY_WATER_SCALE,type EcologyCommand,type EcologyContext,type EcologyState} from './ecology.ts';
export interface EcologyPanelSnapshot {ecology:EcologyState;context:EcologyContext}
export interface EcologyPanelOptions {state:()=>EcologyPanelSnapshot;act:(command:EcologyCommand)=>void;close:()=>void;selectedPlotId?:string;continuesInMenus?:boolean}
function element<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string,className?:string){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function button(label:string,run:()=>void){const b=element('button',label);b.type='button';b.onclick=run;return b;}
/** Snapshot-only field-panel DOM. No timers, hidden progression, goods mutation or invented events. */
export function mountEcologyPanel(panel:HTMLElement,options:EcologyPanelOptions){
 const {ecology,context}=options.state(),view=ecologyView(ecology),close=button('×',options.close);close.className='close';close.setAttribute('aria-label','Close climate and field ecology');panel.replaceChildren(close);
 panel.append(element('span','Weather · soil · living gardens','eyebrow'),element('h2','Field ecology'),element('p',`${view.weather.kind} · ${view.weather.temperature.toFixed(1)}°C air · change in ${view.weather.nextIn.toFixed(0)}s`,'machine-status'),element('p',`${ecology.seeds} / ${ECOLOGY_RULES.starterSeeds} seed packets · ${ecology.biomass} / ${ECOLOGY_RULES.biomassCapacity} biomass · ${ecology.bioGel} / ${ECOLOGY_RULES.bioGelCapacity} bio-gel · ${context.inventory.water} sealed water canisters`,'machine-status'));
 panel.append(element('p','Plant a finite seed packet, watch actual weather feed the soil, then harvest 2 biomass from a ripe crop. Mix 2 biomass into 1 bio-gel to restore up to 20 suit integrity. '+(options.continuesInMenus?'The online world keeps running while this panel is open.':'Close the panel to let the world run.'),'frontier-notice'));
 const action=(label:string,command:EcologyCommand)=>{const b=button(label,()=>{options.act(command);mountEcologyPanel(panel,options);});b.className='frontier-action';const result=applyEcologyCommand(ecology,context,command);b.disabled=result.state===ecology;if(b.disabled)b.title=result.message;return b;};
 const revision={expectedRevision:ecology.revision},goods=element('div',undefined,'row');goods.append(action('Mix bio-gel · 2 biomass',{type:'craft-gel',...revision}),action(`Apply bio-gel · suit ${context.player.hp.toFixed(0)} / 100`,{type:'use-gel',...revision}));panel.append(goods);
 const beds=element('section',undefined,'frontier-section');beds.setAttribute('aria-label','Seeded garden plots');
 for(const p of view.plots){
  const card=element('details',undefined,'frontier-workplace');card.dataset.ecologyPlotId=p.id;card.open=options.selectedPlotId===p.id||view.plots.length===1;
  card.append(element('summary',`${p.stage==='ripe'?'● Ready to harvest':p.stage==='empty'?'◇ Empty bed':`● ${p.stage}`} · ${p.name}`),element('p',`${p.habitat} habitat · ${p.temperature.toFixed(1)}°C · x ${p.position.x.toFixed(1)}, z ${p.position.z.toFixed(1)}`,'frontier-small'),element('p',`${p.crop?ECOLOGY_CROPS[p.crop.species].name:'No crop'} · soil ${p.soilLitres.toFixed(1)} / ${ECOLOGY_RULES.soilCapacity} L`,'machine-status'));
  const moisture=element('meter');moisture.min=0;moisture.max=ECOLOGY_RULES.soilCapacity;moisture.value=p.soilLitres;moisture.setAttribute('aria-label',`${p.name} soil moisture`);card.append(moisture);
  if(p.crop){const growth=element('meter');growth.min=0;growth.max=ECOLOGY_RULES.growthRequired;growth.value=p.crop.growth;growth.setAttribute('aria-label',`${p.name} crop growth`);card.append(growth,element('p',p.stage==='ripe'?'Mature crops wait safely for harvest. No overflow or invisible auto-harvesting.':`Growth ${(p.crop.growth/ECOLOGY_RULES.growthRequired*100).toFixed(0)}% · moisture ${(p.growthFactors.moisture*100).toFixed(0)}% · temperature ${(p.growthFactors.temperature*100).toFixed(0)}% · habitat ${(p.growthFactors.habitat*100).toFixed(0)}%`,'frontier-small'));}
  const row=element('div',undefined,'row');row.append(action('Plant sunleaf · 1 seed',{type:'plant',plotId:p.id,species:'sunleaf',...revision}),action('Plant reedmoss · 1 seed',{type:'plant',plotId:p.id,species:'reedmoss',...revision}),action('Water soil · 1 canister',{type:'water',plotId:p.id,...revision}),action('Harvest · 2 biomass',{type:'harvest',plotId:p.id,...revision}));card.append(row,element('p',`Sunleaf favors sunny beds; reedmoss favors shelter and wetter soil. Watering adds exactly ${ECOLOGY_RULES.canisterWater} L and needs room for the whole 4 L canister. Approach this bed to work here.`,'frontier-small'));beds.append(card);
 }
 panel.append(beds);
 const ledger=element('details',undefined,'frontier-explainer');ledger.append(element('summary','Water balance, finite goods and limits'),element('p',`Garden water (L): initial ${(ecology.water.initial/ECOLOGY_WATER_SCALE).toFixed(2)} + rain ${(ecology.water.rain/ECOLOGY_WATER_SCALE).toFixed(2)} + poured ${(ecology.water.irrigation/ECOLOGY_WATER_SCALE).toFixed(2)} = soil ${(ecology.plots.reduce((n,p)=>n+p.soilWater,0)/ECOLOGY_WATER_SCALE).toFixed(2)} + evaporation ${(ecology.water.evaporated/ECOLOGY_WATER_SCALE).toFixed(2)} + uptake ${(ecology.water.uptake/ECOLOGY_WATER_SCALE).toFixed(2)} + runoff ${(ecology.water.runoff/ECOLOGY_WATER_SCALE).toFixed(2)}.`),element('p',`${ECOLOGY_RULES.starterSeeds} starter packets support at most ${ECOLOGY_RULES.starterSeeds} harvests. This pack creates no scrap, cores or sealed water canisters. Plants never regrow after harvest. The field irrigation allowance is ${ecology.canistersSpent} / ${ECOLOGY_RULES.maxCanisters} spent canisters. Bio-gel is a fictional suit repair, not a medical item. Native trees and habitats are preserved. Time follows the shared world clock; no offline catch-up.`));panel.append(ledger);
 const history=element('section',undefined,'frontier-section');history.setAttribute('aria-label','Committed field ecology history');history.append(element('h3','RECORDED FIELD HISTORY'));
 if(!view.history.length)history.append(element('p','No field actions or planted growth stages have been committed.'));
 else{const list=element('ol');for(const r of view.history.slice(-12).reverse())list.append(element('li',`${r.at.toFixed(1)}s · ${r.text}`));history.append(list);}panel.append(history);
}
