import {restorationArray,restorationKeys,type HabitatPoint,type HabitatSitePlan,type RestorationTuning} from './restoration-plan.ts';
export interface HabitatMotion {cellId:string;targetId:string;route:string[];routeIndex:number;progressMm:number}
export interface HabitatActor {x:number;y?:number;z:number;radius?:number}
export function habitatRoute(site:HabitatSitePlan,from:string,to:string):string[]|null {const queue=[[from]],seen=new Set([from]);while(queue.length){const route=queue.shift()!,last=route.at(-1)!;if(last===to)return route;for(const edge of [...site.edges].sort((a,b)=>a.id.localeCompare(b.id))){const next=edge.a===last?edge.b:edge.b===last?edge.a:null;if(next&&!seen.has(next)){seen.add(next);queue.push([...route,next]);}}}return null;}
export function createHabitatMotion(site:HabitatSitePlan,cellId=site.dockCellId):HabitatMotion{return {cellId,targetId:cellId,route:[cellId],routeIndex:0,progressMm:0};}
export function targetHabitatMotion(site:HabitatSitePlan,m:HabitatMotion,targetId:string):HabitatMotion {if(m.targetId===targetId)return m;if(m.progressMm>0)return m;const route=habitatRoute(site,m.cellId,targetId);return route?{cellId:m.cellId,targetId,route,routeIndex:0,progressMm:0}:m;}
function segment(site:HabitatSitePlan,m:HabitatMotion){const from=m.route[m.routeIndex],to=m.route[m.routeIndex+1];if(!to)return null;const edge=site.edges.find(e=>e.a===from&&e.b===to||e.b===from&&e.a===to);if(!edge)return null;const path=edge.a===from?edge.path:[...edge.path].reverse(),lengths=path.slice(1).map((p,i)=>Math.max(1,Math.round(Math.hypot(p.x-path[i]!.x,p.y-path[i]!.y,p.z-path[i]!.z)*1000)));return {edge,path,lengths,total:lengths.reduce((a,b)=>a+b,0)};}
export function habitatMotionPosition(site:HabitatSitePlan,m:HabitatMotion):HabitatPoint {const edge=segment(site,m);if(!edge){const c=site.cells.find(c=>c.id===m.cellId)!;return {x:c.x,y:c.y,z:c.z};}let left=m.progressMm;for(let i=0;i<edge.lengths.length;i++){const length=edge.lengths[i]!;if(left<=length){const a=edge.path[i]!,b=edge.path[i+1]!,t=left/length;return {x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t};}left-=length;}return {...edge.path.at(-1)!};}
function nearSegment(a:HabitatPoint,b:HabitatPoint,p:HabitatActor,radius:number){if(p.y!==undefined&&Math.abs(p.y-(a.y+b.y)/2)>2)return false;const dx=b.x-a.x,dz=b.z-a.z,d=dx*dx+dz*dz,t=d?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.z-a.z)*dz)/d)):0;return Math.hypot(p.x-a.x-t*dx,p.z-a.z-t*dz)<radius+(p.radius??.34);}
export function advanceHabitatMotion(site:HabitatSitePlan,m:HabitatMotion,speed:number,tuning:RestorationTuning,blockers:{blockedEdgeIds?:readonly string[];actors?:readonly HabitatActor[]},radius=.35):{motion:HabitatMotion;blocked:boolean} {const edge=segment(site,m);if(!edge)return {motion:m,blocked:false};if(blockers.blockedEdgeIds?.includes(edge.edge.id))return {motion:m,blocked:true};const progress=Math.min(edge.total,m.progressMm+Math.max(1,Math.floor(speed*.25*1000*tuning.machineSpeedPercent/100))),candidate={...m,progressMm:progress};const sweep=[habitatMotionPosition(site,m)];let walked=0;for(let i=0;i<edge.lengths.length;i++){walked+=edge.lengths[i]!;if(walked>m.progressMm&&walked<progress)sweep.push({...edge.path[i+1]!});}sweep.push(habitatMotionPosition(site,candidate));if(blockers.actors?.some(p=>sweep.slice(1).some((to,i)=>nearSegment(sweep[i]!,to,p,radius))))return {motion:m,blocked:true};if(progress===edge.total){const index=m.routeIndex+1;return {motion:{...m,cellId:m.route[index]!,routeIndex:index,progressMm:0},blocked:false};}return {motion:candidate,blocked:false};}
export function validHabitatMotion(v:unknown,site:HabitatSitePlan):v is HabitatMotion {if(!restorationKeys(v,['cellId','progressMm','route','routeIndex','targetId']))return false;const m=v as unknown as HabitatMotion;if(Object.keys(m).sort().join(',')!=='cellId,progressMm,route,routeIndex,targetId'||!restorationArray(m.route,1,6)||new Set(m.route).size!==m.route.length||m.route.some(id=>!site.cells.some(c=>c.id===id))||!Number.isSafeInteger(m.routeIndex)||m.routeIndex<0||m.routeIndex>=m.route.length||m.cellId!==m.route[m.routeIndex]||m.targetId!==m.route.at(-1)||!Number.isSafeInteger(m.progressMm)||m.progressMm<0)return false;for(let i=1;i<m.route.length;i++)if(!site.edges.some(e=>e.a===m.route[i-1]&&e.b===m.route[i]||e.b===m.route[i-1]&&e.a===m.route[i]))return false;const edge=segment(site,m);return edge?m.progressMm<edge.total:m.progressMm===0;}
/** Stable tie-breaking and a two-point hysteresis avoid bouncing between neighboring scents. */
export function chooseHabitatScentTarget(site:HabitatSitePlan,fields:readonly {id:string;scent:number}[],motion:HabitatMotion,weight:number):string {const score=(id:string)=>{const route=habitatRoute(site,motion.cellId,id)!;return (fields.find(c=>c.id===id)?.scent??0)*weight-(route.length-1)*12;};const current=motion.targetId;let target=current,best=score(current);for(const c of [...fields].sort((a,b)=>a.id.localeCompare(b.id))){const candidate=score(c.id);if(candidate>best+2){target=c.id;best=candidate;}}return target;}
