/** Finite integer transport kernel. All transfers read the same snapshot, then commit together. */
export interface HabitatFields {waterMl:number;contaminant:number;heat:number;smoke:number;scent:number}
export interface HabitatFieldEdge {a:number;b:number}
export interface HabitatFieldTransfer {from:number;to:number;amount:number;contaminant:number}
export interface HabitatFieldResult {cells:HabitatFields[];waterTransfers:HabitatFieldTransfer[]}
export const HABITAT_FIELD_LIMIT=1_000_000;
export function validHabitatFields(v:unknown):v is HabitatFields {if(!v||typeof v!=='object'||Array.isArray(v))return false;const r=v as Record<string,unknown>,proto=Object.getPrototypeOf(v),own=Reflect.ownKeys(v);if((proto!==Object.prototype&&proto!==null)||own.some(k=>typeof k!=='string'||!Object.hasOwn(Object.getOwnPropertyDescriptor(v,k)!,'value')))return false;return Object.keys(r).sort().join(',')==='contaminant,heat,scent,smoke,waterMl'&&Object.values(r).every(x=>typeof x==='number'&&Number.isSafeInteger(x)&&x>=0&&x<=HABITAT_FIELD_LIMIT);}
/** Exact floor mixture, including the final drop: no contaminant vanishes in a dry transfer. */
export function habitatMixture(waterMl:number,contaminant:number,amount:number):number {if(![waterMl,contaminant,amount].every(Number.isSafeInteger)||waterMl<0||contaminant<0||amount<0||amount>waterMl)throw new Error('Invalid mixture');return amount===0?0:amount===waterMl?contaminant:waterMl===0?0:Math.floor(contaminant*amount/waterMl);}
interface Flow {from:number;to:number;amount:number}
/** Proportional largest-remainder allocation, stable by edge order. */
function apportion(flows:Flow[],ids:number[],available:number){const total=ids.reduce((n,i)=>n+flows[i]!.amount,0);if(total<=available)return;const shares=ids.map(i=>({i,amount:Math.floor(flows[i]!.amount*available/total),fraction:(flows[i]!.amount*available)%total}));let left=available-shares.reduce((n,s)=>n+s.amount,0);shares.sort((a,b)=>b.fraction-a.fraction||a.i-b.i);for(const s of shares){flows[s.i]!.amount=s.amount+(left-->0?1:0);}}
function transfer(cells:readonly HabitatFields[],edges:readonly HabitatFieldEdge[],key:keyof HabitatFields,divisor:number,limit:number,capacity:number):Flow[]{const flows:Flow[]=[];for(const e of edges){const a=cells[e.a]!,b=cells[e.b]!,diff=a[key]-b[key];if(diff===0)continue;const amount=Math.min(limit,Math.floor(Math.abs(diff)/divisor));if(amount)flows.push({from:diff>0?e.a:e.b,to:diff>0?e.b:e.a,amount});}for(let i=0;i<cells.length;i++)apportion(flows,flows.map((f,j)=>f.from===i?j:-1).filter(j=>j>=0),cells[i]![key]);for(let i=0;i<cells.length;i++)apportion(flows,flows.map((f,j)=>f.to===i?j:-1).filter(j=>j>=0),Math.max(0,capacity-cells[i]![key]));return flows;}
export function stepHabitatFields(cells:readonly HabitatFields[],edges:readonly HabitatFieldEdge[],options:{waterConductance:number;airConductance:number;cellCapacityMl:number}):HabitatFieldResult {
 if(cells.length<1||cells.length>18||!cells.every(validHabitatFields)||edges.length>40||edges.some(e=>!Number.isInteger(e.a)||!Number.isInteger(e.b)||e.a<0||e.b<0||e.a>=cells.length||e.b>=cells.length||e.a===e.b)||![options.waterConductance,options.airConductance,options.cellCapacityMl].every(n=>Number.isSafeInteger(n)&&n>0&&n<=HABITAT_FIELD_LIMIT))throw new Error('Invalid field graph');
 const ordered=edges.map(e=>e.a<e.b?e:{a:e.b,b:e.a}).sort((a,b)=>a.a-b.a||a.b-b.b);if(ordered.some((e,i)=>i>0&&ordered[i-1]!.a===e.a&&ordered[i-1]!.b===e.b))throw new Error('Duplicate field edge');const next=cells.map(c=>({...c})),flows=transfer(cells,ordered,'waterMl',4,options.waterConductance,options.cellCapacityMl),waterTransfers:HabitatFieldTransfer[]=flows.map(f=>({...f,contaminant:0}));
 for(let from=0;from<cells.length;from++){const outgoing=waterTransfers.filter(f=>f.from===from),water=outgoing.reduce((n,f)=>n+f.amount,0),mass=habitatMixture(cells[from]!.waterMl,cells[from]!.contaminant,water);let assigned=0;for(let j=0;j<outgoing.length;j++){const f=outgoing[j]!;f.contaminant=j===outgoing.length-1?mass-assigned:Math.floor(mass*f.amount/water);assigned+=f.contaminant;}}
 for(const f of waterTransfers){next[f.from]!.waterMl-=f.amount;next[f.to]!.waterMl+=f.amount;next[f.from]!.contaminant-=f.contaminant;next[f.to]!.contaminant+=f.contaminant;}
 for(const key of ['heat','smoke','scent'] as const)for(const f of transfer(cells,ordered,key,4,options.airConductance,HABITAT_FIELD_LIMIT)){next[f.from]![key]-=f.amount;next[f.to]![key]+=f.amount;}
 return {cells:next,waterTransfers};
}
export function habitatFieldTotals(cells:readonly HabitatFields[]):HabitatFields{return cells.reduce((n,c)=>({waterMl:n.waterMl+c.waterMl,contaminant:n.contaminant+c.contaminant,heat:n.heat+c.heat,smoke:n.smoke+c.smoke,scent:n.scent+c.scent}),{waterMl:0,contaminant:0,heat:0,smoke:0,scent:0});}
