import {townResidents} from './town-residents.ts';
import {causalPlan} from './causal.ts';
import {createConversationMemory,townConversationProfile,namedConversationProfile,openConversation,chooseConversation,conversationView,backConversation,CONVERSATION_VERSION,CONVERSATION_TOPICS,type ConversationProfile} from './npc-conversation.ts';
import {DEVELOPER_BUILD} from './developer-tools.ts';
export const CONVERSATION_LAB_FIELDS=Object.freeze({elapsed:{min:0,max:480,step:1,default:0,unit:'simulation seconds',description:'Select the real resident routine phase at this shared town time.',effect:'Apply scenario'},seed:{min:0,max:4294967295,step:1,default:73129,unit:'world seed',description:'Build the actual town roster and named valley workers for this seed.',effect:'Apply scenario'}});
export interface ConversationLabPreset {kind:'axiom-conversation-preset';version:1;seed:number;residentIndex:number;elapsed:number}
export function parseConversationLabPreset(raw:string):ConversationLabPreset|null{
 if(typeof raw!=='string'||raw.length>4000)return null;
 try{const v=JSON.parse(raw);if(!v||Object.keys(v).sort().join(',')!=='elapsed,kind,residentIndex,seed,version'||v.kind!=='axiom-conversation-preset'||v.version!==1||!Number.isInteger(v.seed)||v.seed<0||v.seed>0xffffffff||!Number.isInteger(v.residentIndex)||v.residentIndex<0||v.residentIndex>105||!Number.isInteger(v.elapsed)||v.elapsed<0||v.elapsed>480)return null;return v;}catch{return null;}
}
export function conversationLabProfiles(seed:number):ConversationProfile[]{
 const roster=townResidents(seed),plan=causalPlan(seed);
 return [...roster.map(r=>townConversationProfile(r,roster)),...plan.agents.map(agent=>{const workplace=plan.workplaces.find(w=>w.id===agent.workplaceId);return namedConversationProfile({...agent,homeName:plan.settlements.find(s=>s.id===agent.homeId)!.name,...(workplace?{workplaceName:workplace.name}:{})});})];
}
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function mountConversationLab(panel:HTMLElement,options:{seed:number;source:string;close:()=>void;visit:()=>void}){
 let alive=true,applied:ConversationLabPreset={kind:'axiom-conversation-preset',version:1,seed:options.seed,residentIndex:0,elapsed:0},profiles=conversationLabProfiles(options.seed),memory=createConversationMemory(options.seed),profile=profiles[0]!,context={seed:options.seed,elapsed:0},result=openConversation(profile,context,memory),actions:string[]=[];
 panel.innerHTML=`<button class="close" aria-label="Close conversation rehearsal">×</button><span class="eyebrow">Developer tools · disposable conversation model</span><h2>Conversation rehearsal</h2><p>Use the exact dialogue engine with every Hearthmere resident and named valley worker. No campaign state, device conversation memory, inventory, reward or online room is changed. This is a model rehearsal; visit a resident in the world to inspect the real presentation.</p><button id="dialogue-lab-visit">Visit real Hearthmere</button><label for="dialogue-lab-seed">Roster seed · unsigned integer</label><input id="dialogue-lab-seed" type="number" min="0" max="4294967295" step="1" value="${options.seed}"><label for="dialogue-lab-person">Conversation partner</label><select id="dialogue-lab-person"></select><label for="dialogue-lab-time">Routine context · 0–480 simulation seconds</label><input id="dialogue-lab-time" type="number" min="0" max="480" step="1" value="0"><p>Seed and time are drafts. Apply starts a fresh disposable memory. Named workers use their verified home and role; no invented relatives or biography.</p><div class="row"><button id="dialogue-lab-apply">Apply scenario</button><button id="dialogue-lab-discard">Discard draft</button><button id="dialogue-lab-defaults">Stage defaults</button></div><p id="dialogue-lab-status" role="status">Applied initial scenario. No pending edits.</p><div id="dialogue-lab-scene"></div><div class="row"><button id="dialogue-lab-topics">Change subject</button><button id="dialogue-lab-return">Leave & return · remember this visit</button><button id="dialogue-lab-reset">Reset conversation & memory</button></div><details><summary>Current branch & memory inspector</summary><pre id="dialogue-lab-inspect"></pre></details><h3>Reproduce & share</h3><div class="row"><button id="dialogue-lab-preset">Export applied preset</button><button id="dialogue-lab-report">Export evidence</button><button id="dialogue-lab-copy">Copy prepared text</button><button id="dialogue-lab-import">Import text into draft</button></div><label for="dialogue-lab-json">Preset / evidence JSON · text fallback</label><textarea id="dialogue-lab-json" rows="7" maxlength="100000" spellcheck="false"></textarea><p>Only the small versioned scenario preset can be imported. Reports include bounded model actions and memory, not saves, room IDs or credentials. Reactions change the conversation, with no reward or relationship score.</p>`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#'+id)!;
 const select=q<HTMLSelectElement>('dialogue-lab-person'),seed=q<HTMLInputElement>('dialogue-lab-seed'),time=q<HTMLInputElement>('dialogue-lab-time'),json=q<HTMLTextAreaElement>('dialogue-lab-json');
 const status=(s:string)=>{q('dialogue-lab-status').textContent=s;};
 function choices(roster=profiles,index=applied.residentIndex){select.innerHTML=roster.map((p,i)=>`<option value="${i}">${esc(p.name)} · ${esc(p.role)}${p.origin==='named'?' · valley':''}</option>`).join('');select.value=String(index);}
 function render(){if(!alive)return;memory=result.memory;const view=conversationView(profile,context,result.session,memory);q('dialogue-lab-scene').innerHTML=`<h3>${esc(view.name)} · ${esc(view.role)}</h3><p><em>${esc(view.subtitle)}</em></p><p>${esc(view.line)}</p><div class="lab-scenario-grid">${view.choices.map(c=>`<button data-dialogue-choice="${esc(c.id)}">${esc(c.text)}</button>`).join('')}</div>`;for(const button of panel.querySelectorAll<HTMLButtonElement>('[data-dialogue-choice]'))button.onclick=()=>{if(!alive)return;const id=button.dataset.dialogueChoice!;result=chooseConversation(profile,context,result.session,memory,id);actions=[...actions,id].slice(-128);render();};q('dialogue-lab-inspect').textContent=JSON.stringify({applied,profile,session:result.session,memory,topics:CONVERSATION_TOPICS,actionCount:actions.length},null,2);}
 function reset(){profile=profiles[applied.residentIndex]??profiles[0]!;context={seed:applied.seed,elapsed:applied.elapsed};memory=createConversationMemory(applied.seed);result=openConversation(profile,context,memory);actions=[];render();}
 function discard(){seed.value=String(applied.seed);time.value=String(applied.elapsed);choices();status('Applied scenario restored to draft. Nothing changed.');}
 panel.querySelector<HTMLButtonElement>('.close')!.onclick=options.close;q<HTMLButtonElement>('dialogue-lab-visit').onclick=options.visit;
 q<HTMLButtonElement>('dialogue-lab-apply').onclick=()=>{const candidate=parseConversationLabPreset(JSON.stringify({kind:'axiom-conversation-preset',version:1,seed:Number(seed.value),residentIndex:Number(select.value),elapsed:Number(time.value)}));if(!candidate||seed.value.trim()===''||time.value.trim()===''){status('Use a whole seed from 0–4294967295 and whole time from 0–480.');return;}const next=conversationLabProfiles(candidate.seed);if(!next[candidate.residentIndex]){status('That resident is unavailable for this seed; choose an existing resident.');return;}applied=candidate;profiles=next;choices();reset();status(`Applied seed ${applied.seed}, ${profile.name}, ${applied.elapsed} seconds. Disposable memory reset.`);};
 q<HTMLButtonElement>('dialogue-lab-discard').onclick=discard;
 q<HTMLButtonElement>('dialogue-lab-defaults').onclick=()=>{seed.value='73129';time.value='0';choices(conversationLabProfiles(73129),0);status('Defaults staged. Apply scenario to use them.');};
 for(const input of [time,select])input.onchange=()=>status('Pending draft. Apply scenario or discard.');
 seed.onchange=()=>{const n=Number(seed.value);if(seed.value.trim()!==''&&Number.isInteger(n)&&n>=0&&n<=0xffffffff)choices(conversationLabProfiles(n),0);status('Pending draft. Apply scenario or discard.');};
 q<HTMLButtonElement>('dialogue-lab-topics').onclick=()=>{result={...result,session:backConversation(result.session)};actions=[...actions,'topics'].slice(-128);render();};
 q<HTMLButtonElement>('dialogue-lab-return').onclick=()=>{result=openConversation(profile,context,memory);actions=[...actions,'reopen'].slice(-128);render();};
 q<HTMLButtonElement>('dialogue-lab-reset').onclick=()=>{reset();status('Conversation and disposable memory reset. Campaign untouched.');};
 q<HTMLButtonElement>('dialogue-lab-preset').onclick=()=>{json.value=JSON.stringify(applied,null,2);status('Applied preset prepared below. Copy the text to save it.');};
 q<HTMLButtonElement>('dialogue-lab-report').onclick=()=>{json.value=JSON.stringify({kind:'axiom-conversation-evidence',version:CONVERSATION_VERSION,mode:'disposable-model',build:DEVELOPER_BUILD,source:options.source,applied,draft:{seed:seed.value,residentIndex:select.value,elapsed:time.value},profileId:profile.id,context,session:result.session,memory,actions,actionsCapped:actions.length===128,limits:'Local authored/procedural dialogue. No rewards. Model evidence only; browser/GPU/touch not certified.'},null,2);status('Sanitized evidence prepared below. Copy the text to save it.');};
 q<HTMLButtonElement>('dialogue-lab-copy').onclick=()=>{const text=json.value;if(!text){status('Export a preset or evidence first.');return;}if(!navigator.clipboard){status('Clipboard unavailable. Select and copy the text below.');return;}void navigator.clipboard.writeText(text).then(()=>{if(alive)status('Copied prepared text.');},()=>{if(alive)status('Clipboard unavailable. Select and copy the text below.');});};
 q<HTMLButtonElement>('dialogue-lab-import').onclick=()=>{const v=parseConversationLabPreset(json.value);if(!v){status('Unsupported preset. Expected version 1 with only bounded seed, residentIndex and elapsed.');return;}const draftProfiles=conversationLabProfiles(v.seed);if(!draftProfiles[v.residentIndex]){status('That resident does not exist in the imported seed. Current draft retained.');return;}seed.value=String(v.seed);time.value=String(v.elapsed);choices(draftProfiles,v.residentIndex);status('Imported scenario staged only. Apply to run; discard to keep current scenario.');};
 choices();render();return ()=>{alive=false;};
}
