import {previewGeneration,CONNECTED_GENERATION_MANIFEST} from './generation.ts';
/** Read-only regional inspector; no world mutation, save writes or physics messages. */
export function mountRegionWorkbench(panel:HTMLElement,worldSeed:number,onClose:()=>void,generate=previewGeneration){
 panel.innerHTML=`<button class="close" aria-label="Close regional inspector">×</button><span class="eyebrow">AXIOM · connected plans v2</span><h2>Valley & vault plans</h2><p>Preview the exact data consumed by terrain, collision, roads, buildings, resources and maps. A preview never replaces your current world. Use Settings → New world / choose seed to play a different foundation.</p><form id="region-preview"><label for="region-seed">Preview seed</label><div class="row"><input id="region-seed" type="number" min="0" max="4294967295" step="1" required inputmode="numeric"><button type="submit">Generate preview</button></div><label for="region-kind">Domain</label><select id="region-kind"><option value="valley">Connected valley · v2</option><option value="dungeon">Vault graph · v2</option></select></form><p id="region-status" role="status"></p><canvas id="region-map" width="560" height="480" aria-label="Generated regional plan preview"></canvas><p id="region-summary"></p><div id="region-checks"></div><details><summary>Sites, routes and objective interfaces</summary><pre id="region-sites"></pre></details><details><summary>Generation manifest</summary><pre id="region-manifest"></pre></details>`;
 const get=<T extends HTMLElement>(id:string)=>panel.querySelector<T>(`#${id}`)!;const seed=get<HTMLInputElement>('region-seed'),kind=get<HTMLSelectElement>('region-kind'),canvas=get<HTMLCanvasElement>('region-map');seed.value=String(worldSeed);let disposed=false,ticket=0,controller:AbortController|undefined;
 const current=()=>!disposed&&panel.querySelector('#region-map')===canvas;
 function cancel(){ticket++;controller?.abort();controller=undefined;}
 function dispose(){if(disposed)return;disposed=true;cancel();}
 panel.querySelector<HTMLButtonElement>('.close')!.onclick=()=>{dispose();onClose();};
 async function render(){if(!current())return;cancel();const request=ticket,view=kind.value,seedText=seed.value,value=Number(seedText);if(!seed.value.trim()||!Number.isInteger(value)||value<0||value>4294967295){get('region-status').textContent='Enter a whole seed from 0 to 4294967295';return;}try{
  controller=new AbortController();get('region-status').textContent='Compiling the bounded plan…';const result=await generate({kind:'connected',seed:value},controller.signal);if(!current()||request!==ticket||seed.value!==seedText||kind.value!==view)return;if(result.plan.kind!=='connected')throw Error('Unexpected preview plan');const plan=result.plan.valley,dungeon=result.plan.dungeon;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#173b34';ctx.fillRect(0,0,560,480);const scale=2.7,X=(x:number)=>280+x*scale,Z=(z:number)=>240+z*scale;
  if(view==='valley'){
   const t=plan.terrain;for(let i=0;i<t.vertices.length;i+=3){const x=t.vertices[i]!,y=t.vertices[i+1]!,z=t.vertices[i+2]!;ctx.fillStyle=`hsl(132 18% ${27+y*2}%)`;ctx.fillRect(X(x),Z(z),t.step*scale+1,t.step*scale+1);}
   const path=(points:readonly {x:number;z:number}[],width:number,color:string)=>{ctx.strokeStyle=color;ctx.lineWidth=width*scale;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(X(p.x),Z(p.z)):ctx.moveTo(X(p.x),Z(p.z)));ctx.stroke();};path(plan.river.points,plan.river.width,'#589c9e');for(const road of plan.roads)path(road.points,road.width,'#c9ba8d');
   for(const b of plan.buildings){ctx.fillStyle='#ddcd9c';ctx.fillRect(X(b.origin.x-b.width/2),Z(b.origin.z-b.depth/2),b.width*scale,b.depth*scale);}for(const site of plan.sites){ctx.fillStyle=site.kind==='workplace'?'#7cf3c6':'#efd78f';ctx.beginPath();ctx.arc(X(site.position.x),Z(site.position.z),3,0,Math.PI*2);ctx.fill();}
   get('region-summary').textContent=`160 × 160 m bounded valley · ${t.vertices.length/3} shared vertices · ${t.indices.length/3} triangles\n${plan.settlements.length} settlements · ${plan.buildings.length} compiled workshops · ${plan.roads.length} road links · ${plan.decorations.length} reserved decorations\n${plan.objects.length} gameplay objects · ${plan.sites.length} work, supply and travel interfaces`;
   get('region-sites').textContent=JSON.stringify({endpoints:plan.endpoints,sites:plan.sites,routeGraph:plan.routeGraph,waterworksSupply:plan.waterworksSupply},null,2);
   get('region-checks').replaceChildren(...plan.constraints.map(c=>{const row=document.createElement('p');row.className=c.ok?'constraint-pass':'constraint-fail';row.textContent=`${c.ok?'✓':'✕'} ${c.key}: ${c.message}`;return row;}));get('region-status').textContent=plan.constraints.every(c=>c.ok)?'VALID CONNECTED VALLEY':'FAILED CONSTRAINT · not ready to install';
  }else{
   ctx.fillStyle='#546e73';for(const t of dungeon.tiles)ctx.fillRect(X(t.x-1),Z(t.z-1),2*scale,2*scale);ctx.strokeStyle='#bdebc8';ctx.lineWidth=2;for(const w of dungeon.walls)ctx.strokeRect(X(w.x-w.hx),Z(w.z-w.hz),2*w.hx*scale,2*w.hz*scale);for(const o of dungeon.objects){ctx.fillStyle=o.kind==='enemy'?'#d69781':o.kind==='core'?'#8bf5d2':'#ead092';ctx.beginPath();ctx.arc(X(o.x),Z(o.z),4,0,Math.PI*2);ctx.fill();}
   get('region-summary').textContent=`${dungeon.rooms.length} chambers · ${dungeon.tiles.length} floor cells · ${dungeon.walls.length} walls · ${dungeon.objects.length} interactable objectives and encounters`;
   get('region-sites').textContent=JSON.stringify({rooms:dungeon.rooms,edges:'edges' in dungeon?dungeon.edges:[],objectives:'objectives' in dungeon?dungeon.objectives:[]},null,2);get('region-checks').replaceChildren();get('region-status').textContent='VERSIONED VAULT GRAPH · exact floor and wall plan';
  }
  get('region-manifest').textContent=JSON.stringify(CONNECTED_GENERATION_MANIFEST,null,2);get('region-status').textContent+=result.backend==='worker'?' · worker compilation':` · synchronous${result.fallback?' fallback ('+result.fallback+')':''}`;
 }catch(error){if(!current()||request!==ticket||(error instanceof Error&&error.name==='AbortError'))return;get('region-status').textContent=error instanceof Error?error.message:'Could not generate this preview';}}
 get<HTMLFormElement>('region-preview').onsubmit=e=>{e.preventDefault();render();};kind.onchange=render;seed.oninput=()=>{if(!current())return;cancel();get('region-status').textContent='Seed edited · generate a new preview';};void render();return dispose;
}
