import {createRegionalState,enableRegionalTrade,enableRegionalFood,applyAction,type State} from './world.ts';
import {createRegionalSupply,regionalSupplyPlan,regionalSupplyAvailable,regionalSupplyActorPoses,regionalSupplySummary,regionalSupplyWeather,type RegionalSupplyCommand} from './regional-supply.ts';
import {regionalTradePlan,regionalTradeInteractions,regionalTradeActorPoses,regionalTradeSummary,type RegionalTradeCommand} from './regional-trade.ts';
import {regionalFoodPlan,regionalFoodInteractions,regionalFoodActorPoses,regionalFoodSummary,type RegionalFoodCommand} from './regional-food.ts';
import type {Vec3} from './procedural.ts';
import {projectWorkbenchFreight,type WorkbenchActor,type WorkbenchCheck,type WorkbenchGeometry,type WorkbenchSnapshot} from './system-workbench-model.ts';

export type SettlementDomain='trade'|'supply'|'food';
export interface SettlementAction {id:string;domain:SettlementDomain;targetId:string;kind:string;label:string;enabled:boolean;reason:string;position:Vec3;command:RegionalTradeCommand|RegionalSupplyCommand|RegionalFoodCommand}
/** The existing Alder–Pine pair, with the Alder collector and its local garden.
 * Both natural deposits and reusable seed portions are production-defined; no
 * extracted goods, water, food, infrastructure or elapsed time is staged here. */
export function settlementPlan(seed:number){const trade=regionalTradePlan(seed),farm=regionalFoodPlan(seed).farms[1]!,collector=regionalSupplyPlan(seed).outposts.find(p=>p.id===farm.siteId)!;return {routes:trade.routes.slice(0,2),sources:trade.sources.slice(0,2),stores:trade.projects.slice(0,2),collector,farm};}
export function createSettlementWorkbench(seed:number,rainfall?:'regional',travel?:'legacy'|'regional'):State {return enableRegionalFood(enableRegionalTrade({...createRegionalState(seed),frontierSupply:createRegionalSupply(seed,rainfall==='regional'?2:1)},travel==='regional'?2:1),1);}
export function settlementActionId(domain:SettlementDomain,targetId:string,kind:string){return `${domain}/${targetId}/${kind}`;}
export function settlementInteractions(state:State):SettlementAction[]{
 const p=settlementPlan(state.seed),routes=new Set(p.routes.map(r=>r.id)),supply=state.frontierSupply!,outpost=supply.outposts.find(o=>o.id===p.collector.id)!,available=regionalSupplyAvailable(supply,state.wilderness,state.frontierTrade),missing={wood:p.collector.cost.wood-outpost.delivered.wood,stone:p.collector.cost.stone-outpost.delivered.stone};
 const trade=regionalTradeInteractions(state.seed,state.frontierTrade).filter(a=>routes.has(a.routeId)).map(a=>({...a,id:settlementActionId('trade',a.targetId,a.kind),domain:'trade' as const,label:`${regionalTradePlan(state.seed).routes.find(r=>r.id===a.routeId)!.name} · ${a.label}`}));
 const collector=(['deliver','build'] as const).map(kind=>{const enabled=outpost.buildStartedAt===null&&(kind==='deliver'?Math.min(missing.wood,available.wood)+Math.min(missing.stone,available.stone)>0:missing.wood+missing.stone===0);return {id:settlementActionId('supply',p.collector.id,kind),domain:'supply' as const,targetId:p.collector.id,kind,label:`${kind==='deliver'?'Deliver reserve to':'Build'} ${p.collector.name} collector`,enabled,reason:enabled?'':outpost.buildStartedAt!==null?'Collector already started':kind==='deliver'?'Withdraw actually delivered wood or stone from its completed freight store':`Stage ${missing.wood} wood and ${missing.stone} stone first`,position:p.collector.deliveryPosition,command:{type:kind,outpostId:p.collector.id,expectedRevision:supply.revision}};});
 const food=regionalFoodInteractions(state.seed,state.frontierFood,state).filter(a=>a.farmId===p.farm.id).map(a=>({...a,id:settlementActionId('food',a.targetId,a.kind),domain:'food' as const,label:`${p.farm.name} · ${a.label}`}));
 return [...trade,...collector,...food];
}
/** Approach poses use ordinary move actions; this is not controller traversal. */
export function applySettlementAction(state:State,action:SettlementAction):State {
 const moved=applyAction(state,{type:'move',x:action.position.x,z:action.position.z});
 const next=action.domain==='trade'?applyAction(moved,{type:'regional-trade',command:action.command as RegionalTradeCommand}):action.domain==='supply'?applyAction(moved,{type:'regional-supply',command:action.command as RegionalSupplyCommand}):applyAction(moved,{type:'regional-food',command:action.command as RegionalFoodCommand});
 return next===moved?state:next;
}
export function settlementChecks(state:State):WorkbenchCheck[]{
 const p=settlementPlan(state.seed),trade=state.frontierTrade!,supply=state.frontierSupply!,food=state.frontierFood!,o=supply.outposts.find(o=>o.id===p.collector.id)!,f=food.farms.find(f=>f.id===p.farm.id)!,available=regionalSupplyAvailable(supply,state.wilderness,trade);
 const check=(id:string,label:string,error:number):WorkbenchCheck=>({id,label,error:Math.abs(error),pass:Math.abs(error)<.00001});
 const result=p.routes.map((r,i)=>{const route=trade.routes[i]!,material=r.material==='quarry-stone'?'stone':'wood';return check(r.id+'/integrated-material',`${material} deposit → freight → stores → raw pack → collector`,p.sources[i]!.deposit-route.remaining-route.stock-route.reserved-route.cargo-route.destinationStock-route.embodied-available[material]-o.delivered[material]);});
 result.push(check(p.farm.id+'/new-overflow','Collector overflow → new farm capture + discarded overflow',o.spilled-f.waterCaptured-f.waterLost));
 result.push(check(p.collector.id+'/integrated-water','Captured rain → drinking + collector + crop water + discarded overflow',o.captured-o.water-o.consumed-o.residents.reduce((n,r)=>n+r.carrying,0)-f.water-f.waterUsed-f.waterLost));
 result.push(check('settlement/clocks','No hidden setup time: all three production clocks agree',Math.max(Math.abs(trade.ticks-supply.ticks),Math.abs(food.ticks-supply.ticks),food.supplyStartTick)));
 return result;
}
export function settlementSnapshot(state:State):Pick<WorkbenchSnapshot,'name'|'phase'|'job'|'cause'|'inventory'|'actors'|'ledger'|'weather'|'causes'|'freight'> {
 const p=settlementPlan(state.seed),trade=state.frontierTrade!,supply=state.frontierSupply!,food=state.frontierFood!,o=supply.outposts.find(o=>o.id===p.collector.id)!,f=food.farms.find(f=>f.id===p.farm.id)!,available=regionalSupplyAvailable(supply,state.wilderness,trade),cs=regionalSupplySummary(supply,state.seed,p.collector.id,state.wilderness,trade)!,fs=regionalFoodSummary(food,state.seed,p.farm.id,state)!;
 const causes=[...p.routes.map(r=>{const s=regionalTradeSummary(trade,state.seed,r.id)!;return {id:r.id,name:r.name,phase:s.phase,cause:s.cause};}),{id:o.id,name:`${p.collector.name} collector`,phase:cs.phase,cause:cs.cause},{id:f.id,name:p.farm.name,phase:fs.phase,cause:fs.cause}];
 const inventory:Record<string,number>={rawWood:available.wood,rawStone:available.stone,collectorWood:o.delivered.wood,collectorStone:o.delivered.stone,collectorWork:o.workTicks,drinkingWater:o.water,rainCaptured:o.captured,waterCarried:o.residents.reduce((n,r)=>n+r.carrying,0),waterDrunk:o.consumed,newOverflow:o.spilled,cropWater:f.water,cropWaterCaptured:f.waterCaptured,cropWaterUsed:f.waterUsed,discardedOverflow:f.waterLost,seeds:f.seeds,growth:f.growth,harvests:f.harvests,harvested:f.harvested,foodStock:f.stock,foodReserved:f.reserved,foodCargo:f.cargo,pantry:f.store,heldMeals:f.returnMeal+f.farmerMeal+f.carrierMeal,meals:f.meals,productionStarterMeals:f.starterGranted,harvestedMealsMinimum:Math.max(0,f.meals-f.starterGranted)};
 p.routes.forEach((r,i)=>{const s=trade.routes[i]!,prefix=r.material==='quarry-stone'?'stone':'wood';for(const field of ['remaining','stock','reserved','cargo','destinationStock','embodied','withdrawn','delivered','distance'] as const)inventory[prefix+field[0]!.toUpperCase()+field.slice(1)]=s[field];inventory[prefix+'RouteMetres']=r.surfaceMetres;});
 const ids=new Set(p.routes.map(r=>r.id));const actors:WorkbenchActor[]=[...regionalTradeActorPoses(state.seed,trade).filter(a=>ids.has(a.routeId)).map(a=>({id:a.id,name:a.name,activity:a.activity,position:a.position,carrying:a.carrying,distance:a.distance,need:0,needLabel:'none'})),...regionalSupplyActorPoses(state.seed,supply).filter(a=>a.outpostId===o.id).map(a=>({id:a.id,name:a.name,activity:a.activity,position:a.position,carrying:a.carrying,distance:o.residents.find(r=>r.id===a.id)!.routeProgress,need:a.thirst,needLabel:'thirst'})),...regionalFoodActorPoses(state.seed,food).filter(a=>a.farmId===f.id).map(a=>({id:a.id,name:a.name,activity:a.activity,position:a.position,carrying:a.carrying,distance:a.distance,need:a.hunger,needLabel:'hunger'}))];
 const active=causes.find(c=>c.phase==='blocked'||c.phase==='repairing')??(o.builtAt===null?causes.find(c=>!['operational','exhausted'].includes(c.phase))??causes[2]!:causes[3]!);
 return {name:'Alder–Pine settlement',phase:f.meals>f.starterGranted?'harvested-meals':active.phase,job:f.meals>f.starterGranted?'Harvested meals reached the residents':active.name,cause:f.meals>f.starterGranted?`At least ${f.meals-f.starterGranted} eaten portions came from actual crops. The production start-farm action supplied ${f.starterGranted} separately counted starter portions. ${cs.cause}`:active.cause,inventory,actors,causes,...(trade.version===2?{freight:p.routes.map(r=>projectWorkbenchFreight(regionalTradeSummary(trade,state.seed,r.id)!))}:{}),weather:regionalSupplyWeather(supply,p.collector.id)!,ledger:{trade:trade.routes.slice(0,2),collector:o,farm:f,clocks:{trade:trade.ticks,supply:supply.ticks,food:food.ticks,foodSupplyBaseline:food.supplyStartTick},productionReceipts:{trade:trade.receipts,supply:supply.receipts,food:food.receipts},rawAvailable:available,collectorCost:p.collector.cost,foodPathMetres:p.farm.surfaceMetres}};
}
export function settlementGeometryParts(seed:number):Pick<WorkbenchGeometry,'paths'|'markers'> {
 const p=settlementPlan(seed);return {paths:[...p.routes.map((r,i)=>({id:r.id,name:r.name,points:r.points,color:i?'#d8b387':'#e5bc73'})),...p.collector.residents.map(r=>({id:r.id,name:r.name,points:r.path,color:'#87cecb'})),{id:p.farm.id,name:'Alder garden → pantry',points:p.farm.path,color:'#a5dc85'}],markers:[...p.sources,...p.stores].map(s=>({id:s.id,name:s.name,position:s.position})).concat([{id:p.collector.id,name:`${p.collector.name} collector`,position:p.collector.position},{id:p.farm.id,name:p.farm.name,position:p.farm.position}])};
}
