import * as THREE from 'three/webgpu';
import {ConvexGeometry} from 'three/addons/geometries/ConvexGeometry.js';
import type {RegionalChunk} from './regional-world.ts';
import {wildernessFeatureRemaining,wildernessFeatureDepleted,type WildernessFeature} from './wilderness.ts';
import type {WildernessState} from './wilderness-state.ts';
/** Acknowledged chunks own GPU buffers. Wilderness is instanced, not thousands of draw calls. */
export function createRegionalView(){
 const root=new THREE.Group();root.name='streamed-frontier';const groups=new Map<string,THREE.Group>();let debugEnabled=false;
 const materials=new Map<string,THREE.MeshStandardMaterial>();const matrix=new THREE.Matrix4(),quaternion=new THREE.Quaternion();
 const material=(color:string)=>{let m=materials.get(color);if(!m){m=new THREE.MeshStandardMaterial({color,flatShading:true,roughness:1});materials.set(color,m);}return m;};
 const terrainMaterial=new THREE.MeshStandardMaterial({vertexColors:true,flatShading:true,roughness:1});
 const waterMaterial=new THREE.MeshStandardMaterial({color:'#67b5af',roughness:.28,metalness:.14,transparent:true,opacity:.84});
 function geometry(vertices:readonly number[],indices:readonly number[]){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex([...indices]);g.computeVertexNormals();return g;}
 function disposeGroup(group:THREE.Group){group.removeFromParent();group.traverse(o=>{if(o instanceof THREE.Sprite){o.material.map?.dispose();o.material.dispose();}if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])if(m instanceof THREE.MeshBasicMaterial||m instanceof THREE.LineBasicMaterial)m.dispose();if(o instanceof THREE.InstancedMesh)o.dispose();}});}
 function batch(group:THREE.Group,geometry:THREE.BufferGeometry,color:string,items:{x:number;y:number;z:number;sx:number;sy:number;sz:number}[]){if(!items.length){geometry.dispose();return;}const m=new THREE.InstancedMesh(geometry,material(color),items.length);for(const [i,p]of items.entries()){matrix.compose(new THREE.Vector3(p.x,p.y,p.z),quaternion,new THREE.Vector3(p.sx,p.sy,p.sz));m.setMatrixAt(i,matrix);}m.instanceMatrix.needsUpdate=true;m.computeBoundingSphere();m.castShadow=true;m.receiveShadow=true;group.add(m);}
 function debug(group:THREE.Group){let debug=group.getObjectByName('regional-collision-debug');if(debug){debug.visible=debugEnabled;return;}if(!debugEnabled)return;debug=new THREE.Group();debug.name='regional-collision-debug';group.add(debug);const vertices:number[]=[];for(const s of group.userData.solids as {x:number;y?:number;z:number;hx:number;hy:number;hz:number;convexVertices?:readonly number[]}[]){const shape=s.convexVertices?new ConvexGeometry(Array.from({length:s.convexVertices.length/3},(_,i)=>new THREE.Vector3(...s.convexVertices!.slice(i*3,i*3+3) as [number,number,number]))):new THREE.BoxGeometry(s.hx*2,s.hy*2,s.hz*2);const edges=new THREE.EdgesGeometry(shape),p=edges.getAttribute('position');for(let i=0;i<p.count;i++)vertices.push(s.x+p.getX(i),(s.y??s.hy)+p.getY(i),s.z+p.getZ(i));shape.dispose();edges.dispose();}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));const line=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:'#ffe08c',depthTest:false,transparent:true,opacity:.65}));line.renderOrder=4;debug.add(line);}
 function make(chunk:RegionalChunk,state?:WildernessState){const group=new THREE.Group();group.name=`regional-chunk:${chunk.key}`;const g=geometry(chunk.terrain.vertices,chunk.terrain.indices);if(chunk.terrain.normals)g.setAttribute('normal',new THREE.Float32BufferAttribute(chunk.terrain.normals,3));const colors:number[]=[];
 for(let i=0;i<chunk.terrain.vertices.length;i+=3){const y=chunk.terrain.vertices[i+1]!,c=new THREE.Color(y>40?'#889581':y>20?'#7b956e':y<1?'#8caa90':'#7ca576');colors.push(c.r,c.g,c.b);}g.setAttribute('color',new THREE.Float32BufferAttribute(('colors' in chunk.terrain?chunk.terrain.colors:colors) as number[],3));const ground=new THREE.Mesh(g,terrainMaterial);ground.receiveShadow=true;group.add(ground);
 for(const patch of chunk.roads){const mesh=new THREE.Mesh(geometry(patch.vertices,patch.indices),material(patch.color));mesh.receiveShadow=true;group.add(mesh);}
 for(const patch of chunk.water){const mesh=new THREE.Mesh(geometry(patch.vertices,patch.indices),waterMaterial);group.add(mesh);}
 for(const s of chunk.structures){const mesh=new THREE.Mesh(new THREE.BoxGeometry(s.half.x*2,s.half.y*2,s.half.z*2),material(s.material.includes('town-roof')?['#466c67','#6e626d','#8f6a4d'][Number(s.material.split('-').at(-1))%3]!:s.material.includes('roof')?'#456a62':s.material.includes('timber')?'#997c59':s.material.includes('marker')?'#dac27f':'#889782'));mesh.position.set(s.center.x,s.center.y,s.center.z);mesh.name=s.id;mesh.castShadow=true;mesh.receiveShadow=true;if(s.id.endsWith('/structure/roof')){mesh.userData.roofCutaway={x:s.center.x,z:s.center.z,hx:s.half.x+2,hz:s.half.z+2,underside:s.center.y-s.half.y};(group.userData.roofs??=[]).push(mesh);}group.add(mesh);}
 const features=chunk.features.filter(f=>wildernessFeatureRemaining(f,state));const trees=features.filter(f=>f.kind==='tree'),rocks=features.filter(f=>f.kind==='rock');
 batch(group,new THREE.BoxGeometry(1,1,1),'#6c6950',trees.map(f=>({x:f.x,y:f.y+f.treeScale!*.8,z:f.z,sx:.35,sy:f.treeScale!*1.6,sz:.35})));
 for(let j=0;j<3;j++)batch(group,new THREE.ConeGeometry(1,1,5),j===0?'#356b57':j===1?'#487c5d':'#588961',trees.map(f=>({x:f.x,y:f.y+f.treeScale!*(1.8+j*.65),z:f.z,sx:f.treeScale!*(1.1-j*.22),sy:f.treeScale!*1.7,sz:f.treeScale!*(1.1-j*.22)})));
 for(const color of new Set(rocks.map(f=>f.color)))batch(group,new THREE.DodecahedronGeometry(1,0),color,rocks.filter(f=>f.color===color).map(f=>({x:f.x,y:f.y,z:f.z,sx:f.radius!*f.scale.x,sy:f.radius!*f.scale.y,sz:f.radius!*f.scale.z})));
 batch(group,new THREE.BoxGeometry(1,1,1),'#dbc698',features.filter(f=>wildernessFeatureDepleted(f,state)).map(f=>({x:f.x,y:f.y+(f.kind==='tree'?.55:f.radius!*f.scale.y+.05),z:f.z+(f.kind==='tree'?.18:0),sx:.08,sy:.1,sz:.025})));
 group.userData.features=features;group.userData.solids=[...features.flatMap(f=>f.solids),...chunk.structures.filter(s=>s.solid).map(s=>({x:s.center.x,y:s.center.y,z:s.center.z,hx:s.half.x,hy:s.half.y,hz:s.half.z}))];debug(group);return group;}
 return {root,make,has(key:string){return groups.has(key);},commit(key:string,group:THREE.Group){const old=groups.get(key);if(old)disposeGroup(old);groups.set(key,group);root.add(group);debug(group);},discard:disposeGroup,unload(key:string){const old=groups.get(key);if(old)disposeGroup(old);groups.delete(key);},clear(){for(const g of groups.values())disposeGroup(g);groups.clear();},update(_dt:number,_reduced:boolean,observer?:{x:number;y:number;z:number}){for(const group of groups.values())for(const roof of (group.userData.roofs??[]) as THREE.Mesh[]){const b=roof.userData.roofCutaway;roof.visible=!observer||observer.y>=b.underside-.1||Math.abs(observer.x-b.x)>=b.hx||Math.abs(observer.z-b.z)>=b.hz;}},hit(_id:string){},setDebug(v:boolean){debugEnabled=v;for(const g of groups.values())debug(g);},get debugEnabled(){return debugEnabled;},get count(){return groups.size;},get featureCount(){return [...groups.values()].reduce((n,g)=>n+(g.userData.features as WildernessFeature[]).length,0);}};
}
