import {CHUNK_SIZE,REGION_BOUND,regionalChunkBounds,generateRegionalChunk,type RegionalChunk} from './regional-world.ts';
export const REGIONAL_STREAM_LIMITS=Object.freeze({loadRadius:2,retainRadius:3,maxResident:49,maxQueued:49,timeoutMs:15000});
export const regionalCellKey=(cx:number,cz:number)=>`region:${cx}:${cz}`;
export const regionalCoordinates=(x:number,z:number)=>({cx:Math.floor(x/CHUNK_SIZE),cz:Math.floor(z/CHUNK_SIZE)});
/** Initial radius-one coverage needs a safety margin; active radius-two streaming can tolerate a full chunk correction. */
export function regionalRelocationNeeded(loading:{x:number;z:number}|null,local:{x:number;z:number},destination:{x:number;z:number}){const anchor=loading??local;return Math.hypot(anchor.x-destination.x,anchor.z-destination.z)>(loading?CHUNK_SIZE/2:CHUNK_SIZE);}
export interface RegionalPort {postMessage(v:unknown):void;terminate():unknown;onmessage:((e:MessageEvent)=>void)|null;onerror:((e:ErrorEvent)=>void)|null;onmessageerror:((e:MessageEvent)=>void)|null}
export interface RegionalGenerator {request(seed:number,cx:number,cz:number,signal?:AbortSignal):Promise<RegionalChunk>;dispose():void;readonly backend:string}
const abortError=()=>Object.assign(new Error('Regional generation cancelled'),{name:'AbortError'});
/** Bounded transport acceptance. Physics independently validates every collision packet. */
export function validRegionalChunk(value:unknown,seed:number,cx:number,cz:number):value is RegionalChunk {
 if(!value||typeof value!=='object')return false;const c=value as RegionalChunk,b=regionalChunkBounds(cx,cz),t=c.terrain;
 if(c.version!==1||c.seed!==seed||c.cx!==cx||c.cz!==cz||c.key!==`${cx}:${cz}`||!c.bounds||Object.keys(b).some(k=>c.bounds[k as keyof typeof b]!==b[k as keyof typeof b]))return false;
 const numbers=(a:unknown,max:number,multiple=3)=>Array.isArray(a)&&a.length<=max&&a.length%multiple===0&&a.every(Number.isFinite);
 if(!t||t.bound!==REGION_BOUND||t.step!==2||!numbers(t.vertices,3267)||t.vertices.length<12||!numbers(t.indices,6144)||!numbers(t.colors,3267)||t.colors.length!==t.vertices.length||!numbers(t.normals,3267)||t.normals.length!==t.vertices.length||t.indices.some(i=>!Number.isInteger(i)||i<0||i>=t.vertices.length/3))return false;
 if(!Array.isArray(c.features)||c.features.length>44||!Array.isArray(c.structures)||c.structures.length>128||!Array.isArray(c.roads)||c.roads.length>64||!Array.isArray(c.water)||c.water.length>64)return false;
 if([...c.roads,...c.water].some(m=>!m||!numbers(m.vertices,12000)||!numbers(m.indices,24000)||m.indices.some(i=>!Number.isInteger(i)||i<0||i>=m.vertices.length/3)))return false;
 if(c.features.some(f=>!f||typeof f.id!=='string'||!['tree','rock'].includes(f.kind)||![f.x,f.y,f.z].every(Number.isFinite)||!Array.isArray(f.solids)||f.solids.length>8)||c.structures.some(s=>!s||!s.center||!s.half||![s.center.x,s.center.y,s.center.z,s.half.x,s.half.y,s.half.z].every(Number.isFinite)))return false;
 return true;
}
/** One compile in flight. The stream owns priority/cancellation instead of queueing a planet. */
export function createRegionalGenerator(factory?:()=>RegionalPort):RegionalGenerator {
 let port:RegionalPort|null=null,sequence=0,disposed=false,backend='worker';
 let active:{id:number;seed:number;cx:number;cz:number;resolve:(c:RegionalChunk)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>;signal?:AbortSignal;abort:()=>void}|null=null;
 const stop=()=>{if(port){port.onmessage=null;port.onerror=null;port.onmessageerror=null;port.terminate();port=null;}};
 function clear(){const a=active;active=null;if(a){clearTimeout(a.timer);a.signal?.removeEventListener('abort',a.abort);}return a;}
 function fail(message:string){const a=clear();stop();a?.reject(new Error(message));}
 function setup(){if(port)return;try{port=factory?factory():new Worker(new URL('./regional.worker.ts',import.meta.url),{type:'module'});const owned=port;owned.onmessage=e=>{if(owned!==port||!active)return;const m=e.data;if(m?.id!==active.id)return;if(m.type!=='chunk'||m.seed!==active.seed||m.cx!==active.cx||m.cz!==active.cz||!validRegionalChunk(m.chunk,active.seed,active.cx,active.cz)){fail(m?.message??'Invalid regional worker result');return;}const a=clear();a?.resolve(m.chunk);};owned.onerror=()=>fail('Regional generation worker stopped');owned.onmessageerror=()=>fail('Regional generation message failed');}catch{backend='yielded-main-thread';port=null;}}
 return {request(seed,cx,cz,signal){if(disposed||signal?.aborted)return Promise.reject(abortError());if(active)return Promise.reject(new Error('Regional generator already busy'));if(!Number.isInteger(seed)||seed<0||seed>0xffffffff||!Number.isInteger(cx)||!Number.isInteger(cz)||Math.abs(cx)>25||Math.abs(cz)>25)return Promise.reject(new RangeError('Invalid regional chunk address'));setup();return new Promise((resolve,reject)=>{const id=++sequence;const abort=()=>{if(active?.id!==id)return;const a=clear();stop();a?.reject(abortError());};active={id,seed,cx,cz,resolve,reject,timer:setTimeout(()=>fail('Regional chunk generation timed out'),REGIONAL_STREAM_LIMITS.timeoutMs),...(signal?{signal}:{}),abort};signal?.addEventListener('abort',abort,{once:true});if(port){try{port.postMessage({type:'generate',id,seed,cx,cz});}catch{fail('Could not send regional generation request');}}else{setTimeout(()=>{if(active?.id!==id)return;try{const chunk=generateRegionalChunk(seed,cx,cz),a=clear();a?.resolve(chunk);}catch(e){fail(e instanceof Error?e.message:'Regional generation failed');}},0);}});},dispose(){disposed=true;const a=clear();stop();a?.reject(abortError());},get backend(){return backend;}};
}
export interface RegionalEntry {key:string;cx:number;cz:number;revision:number;chunk:RegionalChunk;signature:string;confirmed:boolean;confirmedRevision?:number;confirmedSignature?:string;unloadingRevision?:number}
/** Render and physics have one acknowledged ownership epoch. Persistent deltas live in State. */
export class RegionalStreamer {
 readonly entries=new Map<string,RegionalEntry>();
 private queued:{key:string;cx:number;cz:number;distance:number}[]=[];
 private active:{key:string;controller:AbortController}|null=null;
 private epoch=0;private revision=0;private wanted=new Set<string>();private center={cx:0,cz:0};private disposed=false;
 generated=0;cancelled=0;peakResident=0;peakFeatures=0;peakStructures=0;failures=0;lastError='';private retryAt=0;
 readonly seed:number;private generator:RegionalGenerator;private stage:(entry:RegionalEntry,initial:boolean)=>void;private unload:(key:string,revision:number)=>void;private signature:()=>string;
 constructor(seed:number,generator:RegionalGenerator,stage:(entry:RegionalEntry,initial:boolean)=>void,unload:(key:string,revision:number)=>void,signature:()=>string){this.seed=seed;this.generator=generator;this.stage=stage;this.unload=unload;this.signature=signature;}
 private candidates(x:number,z:number,radius:number){const c=regionalCoordinates(x,z),a:{key:string;cx:number;cz:number;distance:number}[]=[];for(let dz=-radius;dz<=radius;dz++)for(let dx=-radius;dx<=radius;dx++){const cx=c.cx+dx,cz=c.cz+dz;if(cx*CHUNK_SIZE>=REGION_BOUND||(cx+1)*CHUNK_SIZE<=-REGION_BOUND||cz*CHUNK_SIZE>=REGION_BOUND||(cz+1)*CHUNK_SIZE<=-REGION_BOUND)continue;a.push({key:regionalCellKey(cx,cz),cx,cz,distance:Math.hypot(dx,dz)});}return a.sort((a,b)=>a.distance-b.distance||a.key.localeCompare(b.key));}
 async initial(x:number,z:number,progress?:(done:number,total:number)=>void){const epoch=++this.epoch;this.clear();this.center=regionalCoordinates(x,z);const candidates=this.candidates(x,z,1);this.wanted=new Set(candidates.map(c=>c.key));progress?.(0,candidates.length);for(const c of candidates){const controller=new AbortController();this.active={key:c.key,controller};const chunk=await this.generator.request(this.seed,c.cx,c.cz,controller.signal);if(epoch!==this.epoch||this.disposed)throw abortError();this.active=null;const entry={...c,chunk,revision:++this.revision,signature:this.signature(),confirmed:false};this.entries.set(c.key,entry);this.generated++;this.peakResident=Math.max(this.peakResident,this.entries.size);this.peakFeatures=Math.max(this.peakFeatures,[...this.entries.values()].reduce((n,e)=>n+e.chunk.features.length,0));this.peakStructures=Math.max(this.peakStructures,[...this.entries.values()].reduce((n,e)=>n+e.chunk.structures.length,0));this.stage(entry,true);progress?.(this.entries.size,candidates.length);}return [...this.entries.values()];}
 update(x:number,z:number){if(this.disposed)return;this.center=regionalCoordinates(x,z);const targets=this.candidates(x,z,REGIONAL_STREAM_LIMITS.loadRadius);this.wanted=new Set(targets.map(c=>c.key));const signature=this.signature();for(const e of this.entries.values()){const distance=Math.max(Math.abs(e.cx-this.center.cx),Math.abs(e.cz-this.center.cz));if(distance>REGIONAL_STREAM_LIMITS.retainRadius){if(!e.unloadingRevision){e.unloadingRevision=++this.revision;this.unload(e.key,e.unloadingRevision);}continue;}if(e.unloadingRevision){delete e.unloadingRevision;e.revision=++this.revision;e.confirmed=false;e.signature=signature;this.stage(e,false);}if(e.signature!==signature&&e.confirmed&&Date.now()>=this.retryAt){e.signature=signature;e.revision=++this.revision;e.confirmed=false;this.stage(e,false);}}
 this.queued=targets.filter(c=>!this.entries.has(c.key)&&this.active?.key!==c.key).slice(0,REGIONAL_STREAM_LIMITS.maxQueued);
 if(this.active&&!this.wanted.has(this.active.key)){this.active.controller.abort();this.active=null;this.cancelled++;}
 void this.drain();}
 private async drain(){if(this.active||this.disposed||Date.now()<this.retryAt)return;const next=this.queued.shift();if(!next)return;if(this.entries.size>=REGIONAL_STREAM_LIMITS.maxResident)return;const controller=new AbortController(),epoch=this.epoch;this.active={key:next.key,controller};try{const chunk=await this.generator.request(this.seed,next.cx,next.cz,controller.signal);if(epoch!==this.epoch||this.disposed||controller.signal.aborted||!this.wanted.has(next.key))return;const entry={...next,chunk,revision:++this.revision,signature:this.signature(),confirmed:false};this.entries.set(entry.key,entry);this.generated++;this.peakResident=Math.max(this.peakResident,this.entries.size);this.peakFeatures=Math.max(this.peakFeatures,[...this.entries.values()].reduce((n,e)=>n+e.chunk.features.length,0));this.peakStructures=Math.max(this.peakStructures,[...this.entries.values()].reduce((n,e)=>n+e.chunk.structures.length,0));this.stage(entry,false);this.lastError='';}catch(e){if((e as Error).name!=='AbortError'){this.failures++;this.lastError=(e as Error).message;this.retryAt=Date.now()+1000;}}finally{if(this.active?.controller===controller)this.active=null;if(epoch===this.epoch)void this.drain();}}
 acknowledge(key:string,revision:number,loaded:boolean){const entry=this.entries.get(key);if(!entry)return false;if(loaded){if(entry.revision!==revision)return false;entry.confirmed=true;entry.confirmedRevision=revision;entry.confirmedSignature=entry.signature;}else{if(revision!==entry.unloadingRevision)return false;this.entries.delete(key);void this.drain();}return true;}
 initialReady(){for(const entry of this.entries.values()){entry.confirmed=true;entry.confirmedRevision=entry.revision;entry.confirmedSignature=entry.signature;}}
 reject(key:string,revision:number,loaded:boolean){const e=this.entries.get(key);if(!e||e.revision!==revision)return false;if(loaded&&e.confirmedRevision!==undefined){e.revision=e.confirmedRevision;e.signature=e.confirmedSignature??'';e.confirmed=true;}else this.entries.delete(key);this.failures++;this.lastError='Physics rejected '+key;this.retryAt=Date.now()+1000;return true;}
 clear(){this.active?.controller.abort();this.active=null;this.queued=[];this.entries.clear();this.wanted.clear();}
 reset(){this.epoch++;this.clear();}
 dispose(){this.disposed=true;this.reset();this.generator.dispose();}
 get stats(){return {resident:this.entries.size,confirmed:[...this.entries.values()].filter(e=>e.confirmed).length,queued:this.queued.length,inFlight:this.active?1:0,generated:this.generated,cancelled:this.cancelled,peakResident:this.peakResident,features:[...this.entries.values()].reduce((n,e)=>n+e.chunk.features.length,0),structures:[...this.entries.values()].reduce((n,e)=>n+e.chunk.structures.length,0),peakFeatures:this.peakFeatures,peakStructures:this.peakStructures,failures:this.failures,error:this.lastError,backend:this.generator.backend,vertices:[...this.entries.values()].reduce((n,e)=>n+e.chunk.terrain.vertices.length/3,0)};}
}
