import {ECOLOGY_RULES} from './ecology.ts';
import {regionalClockAdvance,regionalClockDifference} from './regional-clock.ts';
import {regionalPlan,regionalHeight,type RegionalBox,type RegionalSite} from './regional-world.ts';
import {regionalSupplyWeatherPeriod,regionalSupplyPlan,regionalSupplyOutpostAt,validRegionalSupply,immutableRegionalSupply,type RegionalSupplyState,type RegionalSupplyOutpost} from './regional-supply.ts';
import {regionalTradePlan,validRegionalTrade,regionalTradeReplayTimeline,regionalTradeCanonical,regionalTradeDrainTicks,type RegionalTradeState,type RegionalTradeCommand,type RegionalTradeTimelineEvent} from './regional-trade.ts';
import type {WildernessIdentity,WildernessState} from './wilderness-state.ts';
import type {Vec3} from './procedural.ts';

/** Autonomous, bounded local agriculture. This ledger never edits V31 water or V32 freight. */
export const REGIONAL_FOOD_STEP=.25,REGIONAL_FOOD_MAX_DT=1,REGIONAL_FOOD_REACH=3,REGIONAL_FOOD_MAX_TICKS=1_000_000_000,REGIONAL_FOOD_MAX_REVISION=15;
export const REGIONAL_FOOD_STEWARDSHIP_POOL=12;
/** One emergency transfer per farm keeps replay finite: three starts, twelve tends,
 * three canisters. V1 retains its exact 15-receipt schema and production rules. */
export const REGIONAL_FOOD_IRRIGATION_LITRES=ECOLOGY_RULES.canisterWater,REGIONAL_FOOD_V2_MAX_REVISION=18;
/** Version-aware command budget; the pinned v1 geometry plan retains its legacy budget. */
export const regionalFoodReceiptLimit=(version:1|2)=>version===2?REGIONAL_FOOD_V2_MAX_REVISION:REGIONAL_FOOD_MAX_REVISION;
export type RegionalFoodActivity='idle'|'loading'|'outbound'|'unloading'|'eating'|'returning';
export interface RegionalFoodFarmPlan {id:string;siteId:string;name:string;ownerChunk:string;position:Vec3;interactionPosition:Vec3;workerPosition:Vec3;cisternPosition:Vec3;collectorPosition:Vec3;storeId:string;storeName:string;storePosition:Vec3;storeInteractionPosition:Vec3;path:Vec3[];surfaceMetres:number;speed:number;farmerId:string;farmerName:string;carrierId:string;carrierName:string;capacity:{water:number;source:number;store:number;cargo:number};waterPerCrop:number;yield:number;growWork:number}
export interface RegionalFoodPlan {version:1;seed:number;farms:RegionalFoodFarmPlan[];budget:{farms:3;actors:6;maxReceipts:15;stewardshipPool:12;maxSavedBytes:45000}}
export interface RegionalFoodResident {hunger:number;hungerOverflow:number;meals:number;service:number}
export interface RegionalFoodFarm {id:string;startedAt:number|null;sourceBuildStartedAt:number|null;sourceSpilled:number;waterIrrigated?:number;starterGranted:number;water:number;waterCaptured:number;waterUsed:number;waterLost:number;seeds:number;seedsSown:number;seedsReturned:number;crop:'empty'|'growing'|'ripe';growth:number;harvestWork:number;stock:number;reserved:number;cargo:number;store:number;delivered:number;harvested:number;meals:number;farmer:RegionalFoodResident;carrier:RegionalFoodResident;activity:RegionalFoodActivity;distance:number;actionWork:number;returnMeal:number;farmerMeal:number;carrierMeal:number;farmerEating:number;harvests:number;shipments:number;tended:number;lastTendedHarvest:number;stewardship:number}
export type RegionalFoodCommand={type:'start-farm'|'tend-crop'|'irrigate-farm';targetId:string;expectedRevision:number};
export interface RegionalFoodReceipt {revision:number;tick:number;remainder:number;type:RegionalFoodCommand['type'];targetId:string}
export interface RegionalFoodState {version:1|2;seed:number;revision:number;ticks:number;remainder:number;supplyStartTick:number;supplyStartRemainder:number;tradeBaseline:RegionalTradeState;tradeSnapshot:RegionalTradeState;tradeEvents:RegionalTradeTimelineEvent[];farms:RegionalFoodFarm[];receipts:RegionalFoodReceipt[]}
export interface RegionalFoodDependencies extends WildernessIdentity {frontierSupply?:RegionalSupplyState;frontierTrade?:RegionalTradeState;wilderness?:WildernessState;inventory?:{water:number}}
export interface RegionalFoodContext extends RegionalFoodDependencies {zone:string;player:{x:number;z:number;hp:number};feetY?:number;grounded?:boolean}
export interface RegionalFoodSummary {farmId:string;siteId:string;name:string;storeId:string;storeName:string;phase:'planned'|'needs-water'|'growing'|'harvesting'|'in-transit'|'feeding'|'stocked'|'paused';cause:string;benefit:string;jobId:string;jobTitle:string;water:number;waterCapacity:number;waterCaptured:number;waterUsed:number;waterLost:number;waterIrrigated:number;sourceSpilled:number;starterGranted:number;stock:number;sourceCapacity:number;reserved:number;cargo:number;store:number;storeCapacity:number;harvested:number;delivered:number;meals:number;seeds:number;seedsSown:number;seedsReturned:number;growthProgress:number;harvestProgress:number;farmerHunger:number;carrierHunger:number;farmerWorkRate:number;carrierWorkRate:number;service:number;stewardship:number;remainingStewardship:number;carrierActivity:RegionalFoodActivity;distance:number;surfaceMetres:number;etaSeconds:number|null;returnMeal:number;farmerMeal:number;carrierMeal:number}
export interface RegionalFoodInteraction {id:string;targetId:string;farmId:string;kind:RegionalFoodCommand['type'];label:string;description:string;position:Vec3;enabled:boolean;reason:string;command:RegionalFoodCommand}
export interface RegionalFoodActorPose {id:string;farmId:string;siteId:string;name:string;kind:'farmer'|'carrier';position:Vec3;yaw:number;activity:string;carrying:number;hunger:number;workRate:number;progress:number;distance:number;direction:number;speed:number;pathId:string}
const EPS=1e-6,MAX_REPLAY_STEPS=1_200_000;
const q=(n:number)=>Math.round(n*1e6)/1e6;
const copy=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
function freeze<T>(v:T):T {if(v&&typeof v==='object'&&!Object.isFrozen(v)){for(const x of Object.values(v))freeze(x);Object.freeze(v);}return v;}
const certified=new WeakSet<RegionalFoodState>(),plans=new Map<number,RegionalFoodPlan>();
// Only model-generated/fully replayed immutable snapshots enter this bounded cache.
// Both dependency model versions and source build histories identify replay;
// imported inventories never seed it. The full trade baseline remains authoritative.
const expectedCache=new Map<string,RegionalFoodState>();
function replayKey(s:RegionalFoodState,supply:RegionalSupplyState){return `${s.version}:${supply.version}:${s.tradeBaseline.version}:${s.seed}:${s.supplyStartTick}:${s.supplyStartRemainder}:${supply.outposts.map(o=>o.buildStartedAt).join(',')}:${JSON.stringify(s.tradeBaseline)}:${JSON.stringify(s.tradeEvents)}:${JSON.stringify(s.receipts)}`;}
function cacheExpected(key:string,s:RegionalFoodState){const previous=expectedCache.get(key);if(previous&&previous.ticks>s.ticks)return;expectedCache.delete(key);if(expectedCache.size>=8)expectedCache.delete(expectedCache.keys().next().value!);expectedCache.set(key,freeze(s));}
function seal(s:RegionalFoodState){freeze(s);certified.add(s);return s;}
const horizontal=(a:Vec3,b:Vec3)=>Math.hypot(a.x-b.x,a.z-b.z);
const distance=(a:Vec3,b:Vec3)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
function segmentDistance(p:Vec3,a:Vec3,b:Vec3){const dx=b.x-a.x,dz=b.z-a.z,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.z-a.z)*dz)/(dx*dx+dz*dz||1)));return Math.hypot(p.x-a.x-t*dx,p.z-a.z-t*dz);}
function sample(seed:number,a:Vec3,b:Vec3){const n=Math.max(1,Math.ceil(horizontal(a,b)));return Array.from({length:n+1},(_,i)=>{const t=i/n,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;return {x,y:regionalHeight(seed,x,z),z};});}
function safePad(seed:number,site:RegionalSite){
 const region=regionalPlan(seed),trade=regionalTradePlan(seed),supply=regionalSupplyPlan(seed).outposts.find(o=>o.id===site.id)!,shelter=supply.position,freight=[...trade.sources,...trade.projects].filter(p=>p.siteId===site.id),roads=region.roads.flatMap(r=>r.points.slice(1).map((b,i)=>({a:r.points[i]!,b,width:r.width}))).filter(r=>segmentDistance(site.position,r.a,r.b)<42);
 let best:{score:number;position:Vec3;interactionPosition:Vec3;workerPosition:Vec3;cisternPosition:Vec3}|undefined;
 for(let i=0;i<144;i++){
  const a=i*Math.PI*2/144,dx=Math.cos(a),dz=Math.sin(a),point=(r:number):Vec3=>({x:q(site.position.x+dx*r),y:site.position.y,z:q(site.position.z+dz*r)}),position=point(18),interactionPosition=point(14.3),workerPosition=point(16.6),cisternPosition={x:q(position.x-dz*2.1),y:position.y,z:q(position.z+dx*2.1)};
  const roadClear=Math.min(...roads.map(r=>segmentDistance(position,r.a,r.b)-r.width/2)),oldClear=Math.hypot(Math.max(0,Math.abs(position.x-shelter.x)-5.7),Math.max(0,Math.abs(position.z-shelter.z)-4.8)),freightClear=Math.min(...freight.map(p=>horizontal(position,p.position))),routeClear=segmentDistance(shelter,site.position,interactionPosition);
  if(roadClear<3||oldClear<3.8||freightClear<6||routeClear<8||horizontal(cisternPosition,supply.storagePosition)<3)continue;
  if(freight.some(p=>segmentDistance(p.position,site.position,interactionPosition)<3.7||segmentDistance(position,site.position,p.interactionPosition)<3.7))continue;
  const score=Math.min(roadClear,oldClear,freightClear/1.4,routeClear)-i*1e-8;
  if(!best||score>best.score)best={score,position,interactionPosition,workerPosition,cisternPosition};
 }
 if(!best)throw new Error(`No free regional food pad at ${site.id}`);return best;
}
export function regionalFoodPlan(seed:number):RegionalFoodPlan {
 const prior=plans.get(seed);if(prior)return prior;const region=regionalPlan(seed),trade=regionalTradePlan(seed);
 const farms=trade.projects.map((store,i)=>{const site=region.sites.find(s=>s.id===store.siteId)!,pad=safePad(seed,site),id=`region:1:${seed}/food/${i}`,path=[...sample(seed,pad.interactionPosition,site.position),...sample(seed,site.position,store.interactionPosition).slice(1)],surfaceMetres=q(path.slice(1).reduce((n,b,i)=>n+distance(path[i]!,b),0));
 return {id,siteId:site.id,name:`${site.name.split(' ')[0]} Garden`,ownerChunk:site.ownerChunk,position:pad.position,interactionPosition:pad.interactionPosition,workerPosition:pad.workerPosition,cisternPosition:pad.cisternPosition,collectorPosition:regionalSupplyPlan(seed).outposts.find(o=>o.id===site.id)!.storagePosition,storeId:store.id,storeName:store.name,storePosition:store.position,storeInteractionPosition:store.interactionPosition,path,surfaceMetres,speed:1.4,farmerId:`${id}/gardener`,farmerName:['Sage','Rowan','Ivo'][i]!,carrierId:`${id}/carrier`,carrierName:['Fern','Tess','Wren'][i]!,capacity:{water:6,source:8,store:8,cargo:4},waterPerCrop:2,yield:4,growWork:120};});
 const result:RegionalFoodPlan=freeze({version:1,seed,farms,budget:{farms:3,actors:6,maxReceipts:15,stewardshipPool:12,maxSavedBytes:45000}});if(plans.size>=4)plans.delete(plans.keys().next().value!);plans.set(seed,result);return result;
}
const resident=():RegionalFoodResident=>({hunger:60,hungerOverflow:0,meals:0,service:0});
function pristineFarm(p:RegionalFoodFarmPlan,spilled:number):RegionalFoodFarm{return {id:p.id,startedAt:null,sourceBuildStartedAt:null,sourceSpilled:spilled,starterGranted:0,water:0,waterCaptured:0,waterUsed:0,waterLost:0,seeds:2,seedsSown:0,seedsReturned:0,crop:'empty',growth:0,harvestWork:0,stock:0,reserved:0,cargo:0,store:0,delivered:0,harvested:0,meals:0,farmer:resident(),carrier:resident(),activity:'idle',distance:0,actionWork:0,returnMeal:0,farmerMeal:0,carrierMeal:0,farmerEating:0,harvests:0,shipments:0,tended:0,lastTendedHarvest:-1,stewardship:0};}
function pristine(seed:number,supply:RegionalSupplyState,trade:RegionalTradeState,start=supply.ticks,startRemainder=supply.remainder,version:1|2=1):RegionalFoodState {return {version,seed,revision:0,ticks:0,remainder:0,supplyStartTick:start,supplyStartRemainder:startRemainder,tradeBaseline:copy(trade),tradeSnapshot:copy(trade),tradeEvents:[],farms:regionalFoodPlan(seed).farms.map(p=>{const source=regionalSupplyOutpostAt(supply,p.siteId,start);if(!source)throw new Error('Missing regional food overflow baseline');const farm=pristineFarm(p,source.spilled);if(version===2)farm.waterIrrigated=0;farm.sourceBuildStartedAt=source.buildStartedAt===start?null:source.buildStartedAt;return farm;}),receipts:[]};}
/** New food owns zero elapsed time; old collector spill is a watermark, never an inventory. */
export function createRegionalFood(seed:number,frontierSupply:RegionalSupplyState,frontierTrade:RegionalTradeState,version:1|2=1):RegionalFoodState {if((version!==1&&version!==2)||frontierSupply.seed!==seed||!validRegionalTrade(frontierTrade,{generation:2,seed,regional:{version:1}}))throw new Error('Food dependency mismatch');return seal(pristine(seed,frontierSupply,frontierTrade,frontierSupply.ticks,frontierSupply.remainder,version));}
export function enableRegionalFood<T extends RegionalFoodDependencies&{frontierFood?:RegionalFoodState}>(state:T,version:1|2=2):T {if(state.generation!==2||state.regional?.version!==1||Object.hasOwn(state,'frontierFood')||!dependencies(state))return state;return {...state,frontierFood:createRegionalFood(state.seed,state.frontierSupply!,state.frontierTrade!,version)};}
export function regionalFoodWorkRate(hunger:number){return hunger>=75?.5:hunger>=50?.75:1;}
function activity(f:RegionalFoodFarm,a:RegionalFoodActivity){f.activity=a;f.actionWork=0;}
function eat(a:RegionalFoodResident,f:RegionalFoodFarm){a.hunger=Math.max(0,a.hunger-35);a.meals++;f.meals++;}
function prepareReturn(f:RegionalFoodFarm){if(f.farmer.hunger>=40&&f.farmerMeal===0&&f.store>0){f.store--;f.returnMeal=1;}activity(f,'returning');}
function tickFarm(f:RegionalFoodFarm,p:RegionalFoodFarmPlan,tick:number,source:RegionalSupplyOutpost,sourceTick:number){
 const spilled=source.spilled;f.sourceBuildStartedAt=source.buildStartedAt===sourceTick?null:source.buildStartedAt;const input=q(spilled-f.sourceSpilled);if(input<-EPS)throw new Error('Collector overflow moved backwards');f.sourceSpilled=spilled;
 if(tick%12===0)for(const a of [f.farmer,f.carrier]){if(a.hunger===100)a.hungerOverflow++;else a.hunger++;}
 if(f.startedAt===null){f.waterLost=q(f.waterLost+input);return;}
 const accepted=Math.min(input,q(p.capacity.water-f.water));f.water=q(f.water+accepted);f.waterCaptured=q(f.waterCaptured+accepted);f.waterLost=q(f.waterLost+input-accepted);
 if(f.farmerMeal){f.farmerEating++;if(f.farmerEating>=8){f.farmerMeal=0;f.farmerEating=0;eat(f.farmer,f);}}
 else{
  const rate=regionalFoodWorkRate(f.farmer.hunger);
  if(f.crop==='empty'&&f.seeds>0&&f.water>=p.waterPerCrop&&f.stock+p.yield<=p.capacity.source){f.farmer.service=q(f.farmer.service+rate*REGIONAL_FOOD_STEP);f.water=q(f.water-p.waterPerCrop);f.waterUsed=q(f.waterUsed+p.waterPerCrop);f.seeds--;f.seedsSown++;f.crop='growing';f.growth=0;}
  else if(f.crop==='growing'){f.farmer.service=q(f.farmer.service+Math.min(rate,p.growWork-f.growth)*REGIONAL_FOOD_STEP);f.growth=Math.min(p.growWork,f.growth+rate);if(f.growth===p.growWork){f.crop='ripe';f.harvestWork=0;}}
  else if(f.crop==='ripe'){f.farmer.service=q(f.farmer.service+Math.min(rate,16-f.harvestWork)*REGIONAL_FOOD_STEP);f.harvestWork=Math.min(16,f.harvestWork+rate);if(f.harvestWork===16){f.stock+=p.yield;f.harvested+=p.yield;f.seeds++;f.seedsReturned++;f.harvests++;f.crop='empty';f.growth=0;f.harvestWork=0;}}
 }
 const rate=regionalFoodWorkRate(f.carrier.hunger);
 if(f.activity==='idle'){
  const amount=Math.min(p.capacity.cargo,f.stock,p.capacity.store-f.store);
  if(amount===p.capacity.cargo){f.stock-=amount;f.reserved=amount;activity(f,'loading');}
  else if(f.store>0&&(f.carrier.hunger>=40||f.farmer.hunger>=40&&f.farmerMeal===0))activity(f,'outbound');
 }else if(f.activity==='loading'){f.carrier.service=q(f.carrier.service+rate*REGIONAL_FOOD_STEP);f.actionWork=Math.min(8,f.actionWork+rate);if(f.actionWork===8){f.cargo=f.reserved;f.reserved=0;activity(f,'outbound');}}
 else if(f.activity==='outbound'){f.distance=q(Math.min(p.surfaceMetres,f.distance+p.speed*REGIONAL_FOOD_STEP));if(f.distance===p.surfaceMetres)activity(f,'unloading');}
 else if(f.activity==='unloading'){f.carrier.service=q(f.carrier.service+rate*REGIONAL_FOOD_STEP);f.actionWork=Math.min(8,f.actionWork+rate);if(f.actionWork===8){if(f.cargo){f.store+=f.cargo;f.delivered+=f.cargo;f.shipments++;f.cargo=0;}if(f.carrier.hunger>=40&&f.store>0){f.store--;f.carrierMeal=1;activity(f,'eating');}else prepareReturn(f);}}
 else if(f.activity==='eating'){f.actionWork++;if(f.actionWork>=8){f.carrierMeal=0;eat(f.carrier,f);prepareReturn(f);}}
 else if(f.activity==='returning'){f.distance=q(Math.max(0,f.distance-p.speed*REGIONAL_FOOD_STEP));if(f.distance===0){f.farmerMeal=f.returnMeal;f.returnMeal=0;activity(f,'idle');}}
}
function dynamicSource(o:RegionalSupplyOutpost){return [o.buildStartedAt===null?0:1,o.builtAt===null?0:1,o.workTicks,o.water,...o.residents.flatMap(a=>[a.activity,a.routeProgress,a.actionTicks,a.thirst,a.carrying])].join(',');}
function dynamicFarm(f:RegionalFoodFarm){return [f.startedAt===null?0:1,f.water,f.seeds,f.crop,f.growth,f.harvestWork,f.stock,f.reserved,f.cargo,f.store,f.farmer.hunger,f.carrier.hunger,f.activity,f.distance,f.actionWork,f.returnMeal,f.farmerMeal,f.carrierMeal,f.farmerEating,f.lastTendedHarvest===f.harvests].join(',');}
const cumulative=['sourceSpilled','waterCaptured','waterUsed','waterLost','seedsSown','seedsReturned','delivered','harvested','meals','harvests','shipments'] as const;
/** Each farm replay is independent. Repeated finite actor/crop/water state skips exact
 * cycles with cumulative conserved counters. No per-tick history enters the save. */
function runFarm(f:RegionalFoodFarm,p:RegionalFoodFarmPlan,supply:RegionalSupplyState,startTick:number,from:number,end:number){
 if(end<=from)return;
 if(f.startedAt===null){const source=regionalSupplyOutpostAt(supply,p.siteId,Math.min(REGIONAL_FOOD_MAX_TICKS,startTick+end));if(!source)throw new Error('Unavailable food source time');const increments=Math.floor(end/12)-Math.floor(from/12);for(const a of [f.farmer,f.carrier]){a.hungerOverflow+=Math.max(0,a.hunger+increments-100);a.hunger=Math.min(100,a.hunger+increments);}f.waterLost=q(f.waterLost+source.spilled-f.sourceSpilled);f.sourceSpilled=source.spilled;f.sourceBuildStartedAt=source.buildStartedAt===Math.min(REGIONAL_FOOD_MAX_TICKS,startTick+end)?null:source.buildStartedAt;return;}
 const seen=new Map<string,{tick:number;farm:RegionalFoodFarm}>();let tick=from,steps=0;
 while(tick<end){
  if(tick%120===0){const source=regionalSupplyOutpostAt(supply,p.siteId,Math.min(REGIONAL_FOOD_MAX_TICKS,startTick+tick));if(!source)throw new Error('Unavailable food source time');const key=(startTick+tick>=REGIONAL_FOOD_MAX_TICKS?'capped|':`live:${(startTick+tick)%regionalSupplyWeatherPeriod(supply)}|`)+dynamicSource(source)+'|'+dynamicFarm(f),prior=seen.get(key);
   if(prior){const period=tick-prior.tick,futureBuild=supply.outposts.find(o=>o.id===p.siteId)!.buildStartedAt,buildFence=source.buildStartedAt===null&&futureBuild!==null?Math.min(end,Math.max(tick,futureBuild-startTick)):end,skipEnd=tick<REGIONAL_FOOD_MAX_TICKS-startTick?Math.min(buildFence,REGIONAL_FOOD_MAX_TICKS-startTick):buildFence,count=Math.floor((skipEnd-tick)/period);if(count>0){for(const k of cumulative)f[k]=q(f[k]+(f[k]-prior.farm[k])*count);for(const who of ['farmer','carrier'] as const)for(const k of ['hungerOverflow','meals','service'] as const)f[who][k]=q(f[who][k]+(f[who][k]-prior.farm[who][k])*count);tick+=period*count;continue;}}
   else seen.set(key,{tick,farm:copy(f)});
  }
  if(++steps>MAX_REPLAY_STEPS)throw new Error('Regional food replay budget exceeded');tick++;const source=regionalSupplyOutpostAt(supply,p.siteId,Math.min(REGIONAL_FOOD_MAX_TICKS,startTick+tick));if(!source)throw new Error('Unavailable food source time');tickFarm(f,p,tick,source,Math.min(REGIONAL_FOOD_MAX_TICKS,startTick+tick));
 }
}
function runTo(s:RegionalFoodState,supply:RegionalSupplyState,end:number){const plan=regionalFoodPlan(s.seed);for(let i=0;i<s.farms.length;i++)runFarm(s.farms[i]!,plan.farms[i]!,supply,s.supplyStartTick,s.ticks,end);s.ticks=end;}
function sourceGap(s:RegionalFoodState,supply:RegionalSupplyState){const elapsed=regionalClockDifference(supply,{ticks:s.supplyStartTick,remainder:s.supplyStartRemainder}),gap=regionalClockDifference(elapsed,s);return gap.ticks*REGIONAL_FOOD_STEP+gap.remainder;}
function dependencies(ctx:RegionalFoodDependencies){return ctx.generation===2&&integer(ctx.seed,0,0xffffffff)&&exact(ctx.regional,['version'])&&ctx.regional.version===1&&ctx.frontierTrade!==undefined&&validRegionalTrade(ctx.frontierTrade,ctx)&&ctx.frontierSupply!==undefined&&validRegionalSupply(ctx.frontierSupply,ctx);}
function sameTrade(a:RegionalTradeState,b:RegionalTradeState){return a.version===b.version&&a.seed===b.seed&&a.revision===b.revision&&a.ticks===b.ticks&&Math.abs(a.remainder-b.remainder)<=1e-12&&a.routes.length===b.routes.length&&a.receipts.length===b.receipts.length&&a.routes.every((r,i)=>Object.keys(r).every(k=>r[k as keyof typeof r]===b.routes[i]![k as keyof typeof r]))&&a.receipts.every((r,i)=>Object.keys(r).every(k=>r[k as keyof typeof r]===b.receipts[i]![k as keyof typeof r]));}
function terminalTradeDescendant(past:RegionalTradeState,current:RegionalTradeState){
 const prefix=(a:RegionalTradeState,b:RegionalTradeState)=>b.seed===a.seed&&b.revision>=a.revision&&a.receipts.every((r,i)=>{const c=b.receipts[i];return !!c&&r.revision===c.revision&&r.type===c.type&&r.targetId===c.targetId&&r.tick===c.tick;});
 const newCommandsAfter=(a:RegionalTradeState,b:RegionalTradeState,tick:number)=>b.receipts.slice(a.receipts.length).every(r=>r.tick>=tick);
 const plan=regionalTradePlan(past.seed),carrierProgress=(r:RegionalTradeState['routes'][number],i:number)=>r.shipments*3+(r.activity==='returning'?-r.distance/plan.routes[i]!.surfaceMetres:r.activity==='loading'?.1:r.activity==='outbound'||r.activity==='blocked'?.2+r.distance/plan.routes[i]!.surfaceMetres:r.activity==='unloading'?1.3:0);
 const progressed=(a:RegionalTradeState,b:RegionalTradeState)=>a.routes.every((r,i)=>{const c=b.routes[i]!;return (r.sourceStartedAt===null||c.sourceStartedAt!==null)&&(r.clearedAt===null||c.clearedAt!==null)&&(r.builtAt===null||c.builtAt!==null)&&c.delivered>=r.delivered&&c.withdrawn>=r.withdrawn&&c.embodied>=r.embodied&&c.remaining<=r.remaining&&carrierProgress(c,i)+EPS>=carrierProgress(r,i);});
 // Direct continuation retains the exact old command times and cannot append a
 // new command before the frozen checkpoint. Existing V32 validation proves its dynamics.
 if(prefix(past,current)&&newCommandsAfter(past,current,past.ticks)&&(current.ticks>past.ticks||current.ticks===past.ticks&&current.remainder>=past.remainder-1e-12)&&progressed(past,current))return true;
 // Canonicalizing pending work immediately is NOT a future rebase. First let all
 // already scheduled finite work reach the earliest threshold-eligible rebase.
 const wait={ticks:Math.max(0,REGIONAL_FOOD_MAX_TICKS-regionalTradeDrainTicks(past.seed)-past.ticks),remainder:0},future=regionalTradeReplayTimeline(past,[{type:'rebase',...wait}],wait),a=regionalTradeCanonical(past),b=regionalTradeCanonical(current);
 return !!future&&!!a&&!!b&&prefix(future,b)&&newCommandsAfter(a,b,a.ticks)&&b.ticks>=future.ticks&&progressed(future,b);
}
function tradeTime(s:RegionalFoodState){return {ticks:s.ticks,remainder:s.remainder};}
function needsTradeRebase(s:RegionalTradeState){return s.ticks>=REGIONAL_FOOD_MAX_TICKS-regionalTradeDrainTicks(s.seed,s.version);}
export function advanceRegionalFood(state:RegionalFoodState,dt:number,ctx:RegionalFoodDependencies):RegionalFoodState {
 if(!Number.isFinite(dt)||dt<=0||!object(state))return state;const tickDescriptor=Object.getOwnPropertyDescriptor(state,'ticks');if(!tickDescriptor||!Object.hasOwn(tickDescriptor,'value')||!integer(tickDescriptor.value)||tickDescriptor.value>=REGIONAL_FOOD_MAX_TICKS)return state;
 const descriptor=Object.getOwnPropertyDescriptor(state,'tradeSnapshot');if(!descriptor||!Object.hasOwn(descriptor,'value'))return state;
 const priorTrade=descriptor.value as RegionalTradeState;if(!validateFood(state,{...ctx,frontierTrade:priorTrade},Math.min(dt,REGIONAL_FOOD_MAX_DT)))return state;
 const supply=immutableRegionalSupply(ctx.frontierSupply,ctx);
 const point=supply.ticks<REGIONAL_FOOD_MAX_TICKS?regionalClockDifference(supply,{ticks:state.supplyStartTick,remainder:state.supplyStartRemainder}):regionalClockAdvance(state,dt,REGIONAL_FOOD_MAX_TICKS),endTicks=point.ticks,remainder=point.remainder,steps=endTicks-state.ticks;
 if(steps<0||steps>4||remainder>=REGIONAL_FOOD_STEP)return state;
 if(steps===0&&remainder===state.remainder&&ctx.frontierTrade&&sameTrade(priorTrade,ctx.frontierTrade))return state;const s=copy(state);
 if(needsTradeRebase(priorTrade))s.tradeEvents.push({type:'rebase',...tradeTime(state)});
 const end={ticks:state.ticks+steps,remainder},expected=regionalTradeReplayTimeline(s.tradeBaseline,s.tradeEvents,end);if(!ctx.frontierTrade||!expected||!sameTrade(expected,ctx.frontierTrade))return state;
 runTo(s,supply,end.ticks);s.remainder=remainder;s.tradeSnapshot=copy(ctx.frontierTrade);return seal(s);
}
/** Called atomically after an accepted finite V32 command. Its exact food-time
 * witness binds later completed-store gates without changing V32 persistence. */
export function observeRegionalFoodTrade(state:RegionalFoodState,ctx:RegionalFoodDependencies,command:RegionalTradeCommand):RegionalFoodState|undefined {
 if(state.ticks===REGIONAL_FOOD_MAX_TICKS)return validateFood(state,ctx,0)?seal(copy(state)):undefined;
 if(!validateFood(state,{...ctx,frontierTrade:state.tradeSnapshot},0)||!ctx.frontierTrade||!validRegionalTrade(ctx.frontierTrade,ctx)||command.expectedRevision!==state.tradeSnapshot.revision||ctx.frontierTrade.revision!==state.tradeSnapshot.revision+1)return undefined;
 const s=copy(state);if(needsTradeRebase(state.tradeSnapshot))s.tradeEvents.push({type:'rebase',...tradeTime(state)});
 s.tradeEvents.push({type:'command',...tradeTime(state),command:{type:command.type,targetId:command.targetId}});
 const expected=regionalTradeReplayTimeline(s.tradeBaseline,s.tradeEvents,tradeTime(s));if(!expected||!sameTrade(expected,ctx.frontierTrade))return undefined;s.tradeSnapshot=copy(ctx.frontierTrade);return seal(s);
}
function object(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==='object'&&!Array.isArray(v);}
function exact(v:unknown,names:readonly string[]):v is Record<string,unknown>{if(!object(v)||![Object.prototype,null].includes(Object.getPrototypeOf(v)))return false;const keys=Reflect.ownKeys(v);return keys.length===names.length&&keys.every(k=>typeof k==='string'&&names.includes(k)&&Object.hasOwn(Object.getOwnPropertyDescriptor(v,k)!,'value'));}
function array(v:unknown,length:number):v is unknown[]{return Array.isArray(v)&&Object.getPrototypeOf(v)===Array.prototype&&v.length===length&&Reflect.ownKeys(v).length===length+1&&Array.from({length},(_,i)=>Object.getOwnPropertyDescriptor(v,String(i))).every(d=>!!d&&Object.hasOwn(d,'value'));}
function number(v:unknown,min=0,max=REGIONAL_FOOD_MAX_TICKS):v is number{return typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;}
function integer(v:unknown,min=0,max=REGIONAL_FOOD_MAX_TICKS):v is number{return number(v,min,max)&&Number.isSafeInteger(v);}
export function validRegionalFoodCommand(v:unknown):v is RegionalFoodCommand{return exact(v,['type','targetId','expectedRevision'])&&(v.type==='start-farm'||v.type==='tend-crop'||v.type==='irrigate-farm')&&typeof v.targetId==='string'&&v.targetId.length>0&&v.targetId.length<=120&&!/[\u0000-\u001f\u007f]/.test(v.targetId)&&integer(v.expectedRevision,0,REGIONAL_FOOD_V2_MAX_REVISION);}
export function regionalFoodCommandPosition(seed:number,command:Pick<RegionalFoodCommand,'type'|'targetId'>):Vec3|undefined{return regionalFoodPlan(seed).farms.find(f=>f.id===command.targetId)?.interactionPosition;}
function storeIndex(p:RegionalFoodFarmPlan,trade:RegionalTradeState){return regionalTradePlan(trade.seed).projects.findIndex(s=>s.id===p.storeId);}
function storeReady(p:RegionalFoodFarmPlan,trade:RegionalTradeState){const i=storeIndex(p,trade);return i>=0&&trade.routes[i]!.builtAt!==null;}
function legal(f:RegionalFoodFarm,p:RegionalFoodFarmPlan,type:RegionalFoodCommand['type'],trade:RegionalTradeState){return type==='irrigate-farm'?f.startedAt!==null&&f.waterIrrigated===0&&p.capacity.water-f.water>=REGIONAL_FOOD_IRRIGATION_LITRES:type==='start-farm'?f.startedAt===null&&storeReady(p,trade):f.startedAt!==null&&f.crop==='growing'&&f.growth<p.growWork-16&&f.tended<4&&f.lastTendedHarvest!==f.harvests;}
function execute(f:RegionalFoodFarm,p:RegionalFoodFarmPlan,tick:number,type:RegionalFoodCommand['type']){if(type==='irrigate-farm'){f.water+=REGIONAL_FOOD_IRRIGATION_LITRES;f.waterIrrigated=REGIONAL_FOOD_IRRIGATION_LITRES;}else if(type==='start-farm'){f.startedAt=tick;f.starterGranted=4;f.store=4;}else{f.growth+=16;f.tended++;f.stewardship++;f.lastTendedHarvest=f.harvests;}}
export function applyRegionalFoodCommand(state:RegionalFoodState,ctx:RegionalFoodContext,command:RegionalFoodCommand):{state:RegionalFoodState;message:string}{
 const unchanged={state,message:''};if(!validRegionalFoodCommand(command)||!validRegionalFood(state,ctx)||command.expectedRevision!==state.revision||state.ticks>=REGIONAL_FOOD_MAX_TICKS||state.revision>=regionalFoodReceiptLimit(state.version)||command.type==='irrigate-farm'&&(!Number.isSafeInteger(ctx.inventory?.water)||ctx.inventory!.water<1)||ctx.zone!=='valley'||ctx.grounded!==true||!ctx.player||![ctx.player.x,ctx.player.z,ctx.player.hp,ctx.feetY].every(v=>typeof v==='number'&&Number.isFinite(v))||ctx.player.hp<=0)return unchanged;
 const plan=regionalFoodPlan(state.seed),i=plan.farms.findIndex(f=>f.id===command.targetId),p=plan.farms[i],f=state.farms[i];if(!p||!f||Math.abs(ctx.feetY!-p.interactionPosition.y)>.45||Math.hypot(ctx.player.x-p.interactionPosition.x,ctx.player.z-p.interactionPosition.z)>REGIONAL_FOOD_REACH||!legal(f,p,command.type,ctx.frontierTrade!))return unchanged;
 const s=copy(state);execute(s.farms[i]!,p,s.ticks,command.type);s.revision++;
 s.receipts.push({revision:s.revision,tick:s.ticks,remainder:s.remainder,type:command.type,targetId:p.id});
 return {state:seal(s),message:command.type==='irrigate-farm'?`${p.name}: spent one earned sealed canister, transferring all ${REGIONAL_FOOD_IRRIGATION_LITRES} L into irrigation. This garden’s one emergency transfer is now used. The canister is no longer available for valley gardens, household barter or Mossbank.`:command.type==='start-farm'?`${p.name}: two seed portions and four packed starter meals are allocated once. ${state.version===2?'Future collector overflow and one optional earned emergency canister can irrigate crops':'Only future collector overflow can irrigate crops'}; ${p.carrierName} carries every harvest to the completed ${p.storeName}.`:`${p.name}: you tended this crop, contributing sixteen units of real work and earning one of its four finite stewardship marks.`};
}
const FARM_KEYS=['id','startedAt','sourceBuildStartedAt','sourceSpilled','starterGranted','water','waterCaptured','waterUsed','waterLost','seeds','seedsSown','seedsReturned','crop','growth','harvestWork','stock','reserved','cargo','store','delivered','harvested','meals','farmer','carrier','activity','distance','actionWork','returnMeal','farmerMeal','carrierMeal','farmerEating','harvests','shipments','tended','lastTendedHarvest','stewardship'] as const;
const RESIDENT_KEYS=['hunger','hungerOverflow','meals','service'] as const;
function sameFarm(a:RegionalFoodFarm,b:RegionalFoodFarm){return a.waterIrrigated===b.waterIrrigated&&FARM_KEYS.every(k=>k==='farmer'||k==='carrier'?RESIDENT_KEYS.every(r=>a[k][r]===b[k][r]):a[k]===b[k]);}
/** Strict structural boundary then deterministic replay; serialized counters, hunger,
 * harvests, carried meals and active clocks are never authority by themselves. */
export function validRegionalFood(value:unknown,ctx:RegionalFoodDependencies):value is RegionalFoodState {return validateFood(value,ctx,0);}
function validateFood(value:unknown,ctx:RegionalFoodDependencies,lag:number):value is RegionalFoodState {try{
 if(!dependencies(ctx)||!object(value))return false;
 if(!exact(value,['version','seed','revision','ticks','remainder','supplyStartTick','supplyStartRemainder','tradeBaseline','tradeSnapshot','tradeEvents','farms','receipts'])||(value.version!==1&&value.version!==2)||value.seed!==ctx.seed||!integer(value.revision,0,regionalFoodReceiptLimit(value.version as 1|2))||!integer(value.ticks)||!number(value.remainder,0,REGIONAL_FOOD_STEP)||value.remainder===REGIONAL_FOOD_STEP||!integer(value.supplyStartTick,0,ctx.frontierSupply!.ticks)||!number(value.supplyStartRemainder,0,REGIONAL_FOOD_STEP)||value.supplyStartRemainder===REGIONAL_FOOD_STEP||!array(value.farms,3)||!array(value.receipts,value.revision))return false;
 const s=value as unknown as RegionalFoodState,supply=immutableRegionalSupply(ctx.frontierSupply,ctx);if(supply.ticks===REGIONAL_FOOD_MAX_TICKS?sourceGap(s,supply)>lag+EPS:s.supplyStartTick+s.ticks>supply.ticks||Math.abs(sourceGap(s,supply)-lag)>EPS)return false;
 const plan=regionalFoodPlan(ctx.seed);
 if(!validRegionalTrade(s.tradeBaseline,ctx)||!validRegionalTrade(s.tradeSnapshot,ctx)||!Array.isArray(s.tradeEvents)||!array(s.tradeEvents,s.tradeEvents.length)||s.tradeEvents.length>18||(s.ticks===REGIONAL_FOOD_MAX_TICKS?!terminalTradeDescendant(s.tradeSnapshot,ctx.frontierTrade!):!sameTrade(s.tradeSnapshot,ctx.frontierTrade!)))return false;
 const actualTrade=regionalTradeReplayTimeline(s.tradeBaseline,s.tradeEvents,tradeTime(s));if(!actualTrade||!sameTrade(actualTrade,s.tradeSnapshot))return false;
 for(let i=0;i<3;i++){const f=s.farms[i]!,p=plan.farms[i]!;if(!exact(f,s.version===2?[...FARM_KEYS,'waterIrrigated']:FARM_KEYS)||s.version===2&&f.waterIrrigated!==0&&f.waterIrrigated!==REGIONAL_FOOD_IRRIGATION_LITRES||f.id!==p.id||!exact(f.farmer,RESIDENT_KEYS)||!exact(f.carrier,RESIDENT_KEYS))return false;for(const k of FARM_KEYS){const v=f[k];if(typeof v==='number'&&!number(v,k==='lastTendedHarvest'?-1:0,REGIONAL_FOOD_MAX_TICKS*4))return false;}for(const a of [f.farmer,f.carrier])if(!RESIDENT_KEYS.every(k=>number(a[k],0,REGIONAL_FOOD_MAX_TICKS*4)))return false;}
 let previous={ticks:0,remainder:0};
 for(let i=0;i<s.receipts.length;i++){const r=s.receipts[i]!;if(!exact(r,['revision','tick','remainder','type','targetId'])||r.revision!==i+1||!integer(r.tick,previous.ticks,s.ticks)||!number(r.remainder,0,REGIONAL_FOOD_STEP)||r.remainder===REGIONAL_FOOD_STEP||r.tick===previous.ticks&&r.remainder<previous.remainder-EPS||r.tick===s.ticks&&r.remainder>s.remainder+EPS||!validRegionalFoodCommand({type:r.type,targetId:r.targetId,expectedRevision:i}))return false;previous={ticks:r.tick,remainder:r.remainder};const p=plan.farms.find(p=>p.id===r.targetId);if(!p)return false;if(r.type==='start-farm'){const at=regionalTradeReplayTimeline(s.tradeBaseline,s.tradeEvents.filter(e=>e.ticks<r.tick||e.ticks===r.tick&&e.remainder<=r.remainder),{ticks:r.tick,remainder:r.remainder});if(!at||!storeReady(p,at))return false;}}
 const key=replayKey(s,supply);if(certified.has(s)){for(let i=0;i<3;i++){const current=regionalSupplyOutpostAt(supply,plan.farms[i]!.siteId,Math.min(REGIONAL_FOOD_MAX_TICKS,s.supplyStartTick+s.ticks));if(!current||current.spilled!==s.farms[i]!.sourceSpilled||(current.buildStartedAt===Math.min(REGIONAL_FOOD_MAX_TICKS,s.supplyStartTick+s.ticks)?null:current.buildStartedAt)!==s.farms[i]!.sourceBuildStartedAt)return false;}cacheExpected(key,s);return true;}
 const cached=expectedCache.get(key),replay=cached&&cached.ticks<=s.ticks?copy(cached):pristine(ctx.seed,supply,s.tradeBaseline,s.supplyStartTick,s.supplyStartRemainder,s.version);
 for(const r of (cached&&cached.ticks<=s.ticks?[]:s.receipts)){runTo(replay,supply,r.tick);const i=plan.farms.findIndex(p=>p.id===r.targetId),p=plan.farms[i]!,f=replay.farms[i]!;if(!legal(f,p,r.type,ctx.frontierTrade!))return false;execute(f,p,r.tick,r.type);}
 runTo(replay,supply,s.ticks);replay.receipts=copy(s.receipts);replay.tradeEvents=copy(s.tradeEvents);replay.tradeSnapshot=copy(s.tradeSnapshot);replay.revision=s.revision;replay.remainder=s.remainder;cacheExpected(key,replay);return s.farms.every((f,i)=>sameFarm(f,replay.farms[i]!));
 }catch{return false;}}
export function immutableRegionalFood(value:unknown,ctx:RegionalFoodDependencies):RegionalFoodState{if(!validRegionalFood(value,ctx))throw new Error('Invalid regional food ledger');return certified.has(value)?value:seal(copy(value));}
/** Receipt-derived water cost is included in world-level collected-resource conservation. */
export function regionalFoodCost(state:RegionalFoodState|undefined):{water:number}{return {water:state?.version===2?state.receipts.filter(r=>r.type==='irrigate-farm').length:0};}
export function regionalFoodInteractions(seed:number,state:RegionalFoodState|undefined,ctx?:RegionalFoodDependencies):RegionalFoodInteraction[]{
 if(!state||state.seed!==seed)return [];
 return regionalFoodPlan(seed).farms.flatMap((p,i)=>{const f=state.farms[i]!;return (state.version===2?['start-farm','tend-crop','irrigate-farm'] as const:['start-farm','tend-crop'] as const).map(kind=>{
  const paused=state.ticks>=REGIONAL_FOOD_MAX_TICKS,water=ctx?.inventory?.water??0;
  const enabled=!paused&&(kind==='irrigate-farm'?!!ctx?.frontierTrade&&legal(f,p,kind,ctx.frontierTrade)&&Number.isSafeInteger(water)&&water>=1:ctx?.frontierTrade?legal(f,p,kind,ctx.frontierTrade):kind==='tend-crop'&&f.startedAt!==null&&f.crop==='growing'&&f.growth<p.growWork-16&&f.tended<4&&f.lastTendedHarvest!==f.harvests);
  const reason=enabled?'':paused?'Food clock limit reached; simulation paused':kind==='irrigate-farm'?f.startedAt===null?'Start this garden first':f.waterIrrigated!==0?'This garden’s one emergency canister is already used':p.capacity.water-f.water<REGIONAL_FOOD_IRRIGATION_LITRES?'The cistern needs room for all 4 L':water<1?'Carry one earned sealed water canister':'A valid local farm is required':kind==='start-farm'?f.startedAt!==null?'Garden already started':'Complete the local freight store first':f.tended>=4?'All four stewardship marks awarded':f.crop!=='growing'?'Wait for a watered, planted crop':f.lastTendedHarvest===f.harvests?'This crop is already tended':'This crop is almost ready';
  return {id:`${p.id}/${kind}`,targetId:p.id,farmId:p.id,kind,label:kind==='irrigate-farm'?'Use one emergency canister · 4 L · once per garden':kind==='start-farm'?`Start ${p.name}`:'Tend this crop',description:kind==='irrigate-farm'?'Spend one earned sealed canister permanently. One use per garden; all 4 L must fit. This water cannot also serve valley gardens, household barter or Mossbank. No canister refill or drinking-water withdrawal.':kind==='start-farm'?'Start two reusable seed portions and a finite overflow cistern. Drinking water keeps priority.':'Contribute sixteen growing-work units once per crop. Four finite stewardship marks per garden; residents continue without repeated help.',position:p.interactionPosition,enabled,reason,command:{type:kind,targetId:p.id,expectedRevision:state.revision}};
 });});
}
export function regionalFoodSummary(state:RegionalFoodState,seed:number,farmId:string,_ctx?:RegionalFoodDependencies):RegionalFoodSummary|undefined{
 const i=regionalFoodPlan(seed).farms.findIndex(p=>p.id===farmId);if(state.seed!==seed||i<0)return undefined;const p=regionalFoodPlan(seed).farms[i]!,f=state.farms[i]!;
 const phase:RegionalFoodSummary['phase']=state.ticks>=REGIONAL_FOOD_MAX_TICKS?'paused':f.startedAt===null?'planned':f.carrierMeal||f.farmerMeal?'feeding':['outbound','returning','unloading'].includes(f.activity)?'in-transit':f.crop==='ripe'?'harvesting':f.crop==='growing'?'growing':f.water<p.waterPerCrop&&f.stock<p.capacity.source?'needs-water':'stocked';
 const cause=phase==='paused'?'The food clock has reached its one-billion-tick limit (about 7.9 active years). Food balances and workers are paused; freight can continue.':phase==='planned'?'Finish this community’s freight store, then start its garden locally.':phase==='needs-water'?state.version===2?(f.waterIrrigated===0?'Wait for new collector overflow, or spend one earned 4 L emergency canister here. This garden can accept that emergency transfer once.':'This garden’s one emergency transfer is used. Wait for new collector overflow; drinking water stays with residents.'):'The cistern recovers only newly spilled collector overflow. Residents keep all drinking water first.':phase==='growing'?'A planted seed portion and two conserved litres are growing four food portions. Hunger changes the gardener’s actual work rate.':phase==='harvesting'?'The gardener is harvesting the ripe crop; food enters the source stock only when this work finishes.':phase==='in-transit'?`${p.carrierName} follows the local ${p.surfaceMetres.toFixed(0)} m path. Food is available only after unloading.`:phase==='feeding'?'A real delivered food portion is being eaten. It reduces hunger and improves productive work.':'Finite shelves are stocked; the gardener and carrier resume when there is space or a meal is needed.';
 return {farmId,siteId:p.siteId,name:p.name,storeId:p.storeId,storeName:p.storeName,phase,cause,benefit:`${f.meals} portions eaten; fed residents work up to twice as fast as hungry residents. Two seed portions are reused, and no resident starves or requires constant player input.`,jobId:`${p.id}/${f.startedAt===null?'start':'tend-'+f.harvests}`,jobTitle:phase==='paused'?'Food simulation paused':f.startedAt===null?'Start a local garden':f.tended<4?'Help tend the next crop':'Garden stewardship completed',water:f.water,waterCapacity:p.capacity.water,waterCaptured:f.waterCaptured,waterUsed:f.waterUsed,waterLost:f.waterLost,waterIrrigated:f.waterIrrigated??0,sourceSpilled:f.sourceSpilled,starterGranted:f.starterGranted,stock:f.stock,sourceCapacity:p.capacity.source,reserved:f.reserved,cargo:f.cargo,store:f.store,storeCapacity:p.capacity.store,harvested:f.harvested,delivered:f.delivered,meals:f.meals,seeds:f.seeds,seedsSown:f.seedsSown,seedsReturned:f.seedsReturned,growthProgress:f.growth/p.growWork,harvestProgress:f.harvestWork/16,farmerHunger:f.farmer.hunger,carrierHunger:f.carrier.hunger,farmerWorkRate:regionalFoodWorkRate(f.farmer.hunger),carrierWorkRate:regionalFoodWorkRate(f.carrier.hunger),service:f.farmer.service+f.carrier.service,stewardship:f.stewardship,remainingStewardship:4-f.stewardship,carrierActivity:f.activity,distance:f.distance,surfaceMetres:p.surfaceMetres,etaSeconds:phase==='paused'?null:f.activity==='outbound'?(p.surfaceMetres-f.distance)/p.speed+2:f.activity==='unloading'?(8-f.actionWork)/regionalFoodWorkRate(f.carrier.hunger)*REGIONAL_FOOD_STEP:null,returnMeal:f.returnMeal,farmerMeal:f.farmerMeal,carrierMeal:f.carrierMeal};
}
function poseOnPath(path:Vec3[],at:number,direction:number){let remaining=at;for(let i=1;i<path.length;i++){const a=path[i-1]!,b=path[i]!,length=distance(a,b);if(remaining<=length+EPS||i===path.length-1){const t=Math.max(0,Math.min(1,remaining/(length||1)));return {position:{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t},yaw:Math.atan2((b.x-a.x)*direction,(b.z-a.z)*direction)};}remaining-=length;}return {position:{...path[0]!},yaw:0};}
export function regionalFoodActorPoses(seed:number,state:RegionalFoodState|undefined):RegionalFoodActorPose[]{if(!state||state.seed!==seed)return [];return regionalFoodPlan(seed).farms.flatMap((p,i)=>{const f=state.farms[i]!,direction=f.activity==='returning'?-1:1,pose=poseOnPath(p.path,f.distance,direction);return [{id:p.farmerId,farmId:p.id,siteId:p.siteId,name:p.farmerName,kind:'farmer' as const,position:p.workerPosition,yaw:Math.atan2(p.position.x-p.workerPosition.x,p.position.z-p.workerPosition.z),activity:state.ticks>=REGIONAL_FOOD_MAX_TICKS?'paused':f.startedAt===null?'waiting':f.farmerMeal?'eating':f.crop==='growing'?'tending':f.crop==='ripe'?'harvesting':'waiting',carrying:f.farmerMeal,hunger:f.farmer.hunger,workRate:regionalFoodWorkRate(f.farmer.hunger),progress:f.crop==='ripe'?f.harvestWork/16:f.growth/p.growWork,distance:0,direction:1,speed:0,pathId:`${p.id}/garden`},{id:p.carrierId,farmId:p.id,siteId:p.siteId,name:p.carrierName,kind:'carrier' as const,...pose,activity:state.ticks>=REGIONAL_FOOD_MAX_TICKS?'paused':f.activity,carrying:f.cargo+f.returnMeal+f.carrierMeal,hunger:f.carrier.hunger,workRate:regionalFoodWorkRate(f.carrier.hunger),progress:f.distance/p.surfaceMetres,distance:f.distance,direction,speed:state.ticks<REGIONAL_FOOD_MAX_TICKS&&(f.activity==='outbound'||f.activity==='returning')?p.speed:0,pathId:`${p.id}/delivery`}];});}
/** Food terrain marks are shallow and non-solid; activation cannot trap a mature save. */
export function regionalFoodSiteBoxes(seed:number,state:RegionalFoodState|undefined):RegionalBox[]{return regionalFoodPlan(seed).farms.map((p,i)=>({id:`${p.id}/plot`,center:{x:p.position.x,y:p.position.y+.025,z:p.position.z},half:{x:1.5,y:.025,z:1.2},material:state?.farms[i]?.startedAt!==null&&state?.farms[i]?.startedAt!==undefined?'regional-food-soil':'regional-food-blueprint',solid:false}));}
export function regionalFoodConservation(state:RegionalFoodState){const plan=regionalFoodPlan(state.seed);return state.farms.map((f,i)=>{const p=plan.farms[i]!,food=f.stock+f.reserved+f.cargo+f.store+f.returnMeal+f.farmerMeal+f.carrierMeal+f.meals,seed=f.seeds+(f.crop==='empty'?0:1),water=q(f.water+f.waterUsed);return {farmId:f.id,harvested:f.harvested,starterGranted:f.starterGranted,food,seed,water,captured:f.waterCaptured,...(state.version===2?{irrigated:f.waterIrrigated!}:{}),balanced:food===f.harvested+f.starterGranted&&seed===2&&Math.abs(water-f.waterCaptured-(f.waterIrrigated??0))<EPS&&f.water<=p.capacity.water&&f.stock<=p.capacity.source&&f.store+f.reserved+f.cargo<=p.capacity.store};});}
