import {habitatMixture,stepHabitatFields,type HabitatFields} from './habitat-fields.ts';
import {advanceHabitatMotion,chooseHabitatScentTarget,createHabitatMotion,habitatMotionPosition,targetHabitatMotion,validHabitatMotion,type HabitatActor,type HabitatMotion} from './habitat-motion.ts';
import {compileRestorationBody,validRestorationBodyRecipe,type RestorationBodyRecipe} from './restoration-body.ts';
import {compileUtilityAbility,createUtilityState,interruptUtility,requestUtility,stepUtility,validUtilityState,validUtilityRecipeInput,type UtilityRecipeInput,type UtilityState,type UtilityPulse} from './utility-ability.ts';
import {RESTORATION_DEFAULTS,RESTORATION_RULES,restorationArray,restorationFreeze,restorationInteger,restorationKeys,restorationPlan,validRestorationTuning,type HabitatSitePlan,type RestorationPlan,type RestorationTuning} from './restoration-plan.ts';
export * from './restoration-plan.ts';
export type {HabitatMotion,HabitatActor} from './habitat-motion.ts';
export interface RestorationInventory {scrap:number;core:number;water:number}
export interface RestorationCell extends HabitatFields {id:string;nutrient:number;biomass:number;health:number}
export interface RestorationSite {id:string;activatedAtTick:number|null;cells:RestorationCell[];chargeReserve:number;filterReserve:number;scentReserve:number;sealedWaste:number;stableTicks:number;completedAtTick:number|null;repairUsed:number;pollinator:HabitatMotion;pollinatorVisits:number}
export interface RestorationOrder {sourceId:string;targetId:string}
export interface RestorationMachine {recipe:RestorationBodyRecipe;ability:UtilityRecipeInput;status:'packed'|'idle'|'working'|'returning';siteId:string|null;motion:HabitatMotion|null;charge:number;filter:number;waste:number;scentCharge:number;heat:number;tank:{waterMl:number;contaminant:number};utility:UtilityState;order:RestorationOrder|null;blocked:boolean}
export interface RestorationRecord {tick:number;kind:'activate'|'refit'|'deploy'|'recall'|'start'|'stop'|'service'|'restore'|'repair'|'interrupt';targetId:string;amount:number}
export interface RestorationState {version:1;seed:number;planId:string;revision:number;tick:number;remainder:number;sites:RestorationSite[];machine:RestorationMachine|null;sinks:{waterMl:number;heat:number;smoke:number;scent:number;organic:number;filter:number};spent:RestorationInventory;records:RestorationRecord[]}
export interface RestorationContext {seed:number;zone:string;player:{x:number;z:number;hp:number};inventory:RestorationInventory;blockedEdgeIds?:readonly string[];actors?:readonly HabitatActor[]}
interface CommandBase {targetId:string;expectedRevision:number}
export type RestorationCommand=
 | CommandBase&{kind:'refit';recipe:RestorationBodyRecipe;ability:UtilityRecipeInput}
 | CommandBase&{kind:'deploy'|'recall'|'stop'|'service'|'repair'}
 | CommandBase&{kind:'start';sourceId:string};
const STATE_KEYS=['version','seed','planId','revision','tick','remainder','sites','machine','sinks','spent','records'];
const trusted=new WeakSet<object>();
const commit=(s:RestorationState)=>{restorationFreeze(s);trusted.add(s);return s;};
const freshInventory=():RestorationInventory=>({scrap:0,core:0,water:0});
const inventoryOK=(v:unknown):v is RestorationInventory=>restorationKeys(v,['scrap','core','water'])&&Object.values(v).every(n=>restorationInteger(n));
export function createRestoration(plan:RestorationPlan):RestorationState {return commit({version:1,seed:plan.seed,planId:plan.id,revision:0,tick:0,remainder:0,sites:plan.sites.map(s=>({id:s.id,activatedAtTick:null,cells:s.cells.map(c=>({id:c.id,...c.initial,nutrient:c.initialNutrient,biomass:c.initialBiomass,health:c.initialHealth})),chargeReserve:s.initialCharge,filterReserve:s.initialFilter,scentReserve:s.initialScent,sealedWaste:0,stableTicks:0,completedAtTick:null,repairUsed:0,pollinator:createHabitatMotion(s),pollinatorVisits:0})),machine:null,sinks:{waterMl:0,heat:0,smoke:0,scent:0,organic:0,filter:0},spent:freshInventory(),records:[]});}
function record(s:RestorationState,kind:RestorationRecord['kind'],targetId:string,amount=0){s.records.push({tick:s.tick,kind,targetId,amount});if(s.records.length>RESTORATION_RULES.maxRecords)s.records.shift();}
export function restorationPlayerCost(s:RestorationState|undefined):RestorationInventory {const c=s?.machine?compileRestorationBody(s.machine.recipe).cost:{scrap:0,core:0};return {scrap:c.scrap+(s?.spent.scrap??0),core:c.core+(s?.spent.core??0),water:s?.spent.water??0};}
export function restorationBalances(s:RestorationState,plan:RestorationPlan){const totals={waterMl:s.sinks.waterMl,contaminant:0,energy:s.sinks.heat,smoke:s.sinks.smoke,scent:s.sinks.scent,organic:s.sinks.organic,filter:s.sinks.filter};for(const site of s.sites){totals.energy+=site.chargeReserve;totals.filter+=site.filterReserve;totals.scent+=site.scentReserve;totals.contaminant+=site.sealedWaste;for(const c of site.cells){totals.waterMl+=c.waterMl;totals.contaminant+=c.contaminant;totals.energy+=c.heat;totals.smoke+=c.smoke;totals.scent+=c.scent;totals.organic+=c.nutrient+c.biomass;}}if(s.machine){totals.waterMl+=s.machine.tank.waterMl;totals.contaminant+=s.machine.tank.contaminant+s.machine.waste;totals.energy+=s.machine.charge+s.machine.heat;totals.filter+=s.machine.filter;totals.scent+=s.machine.scentCharge;}return Object.fromEntries(Object.entries(totals).map(([key,value])=>[key,plan.totals[key as keyof typeof totals]-value])) as typeof totals;}
export function validRestorationCommand(v:unknown):v is RestorationCommand {try{if(!v||typeof v!=='object'||Array.isArray(v))return false;const c=v as RestorationCommand,base=['kind','targetId','expectedRevision'];if(!['refit','deploy','recall','stop','service','repair','start'].includes(c.kind)||typeof c.targetId!=='string'||c.targetId.length>64||!restorationInteger(c.expectedRevision))return false;if(c.kind==='refit')return restorationKeys(v,[...base,'recipe','ability'])&&validRestorationBodyRecipe(c.recipe)&&validUtilityRecipeInput(c.ability)&&c.ability.organ===c.recipe.organ;if(c.kind==='start')return restorationKeys(v,[...base,'sourceId'])&&typeof c.sourceId==='string'&&c.sourceId.length<=64;return restorationKeys(v,base);}catch{return false;}}
function actorOK(ctx:RestorationContext,s:RestorationState){return ctx.seed===s.seed&&ctx.zone==='valley'&&Number.isFinite(ctx.player.hp)&&ctx.player.hp>0&&Number.isFinite(ctx.player.x)&&Number.isFinite(ctx.player.z)&&inventoryOK(ctx.inventory);}
function near(ctx:RestorationContext,p:{x:number;z:number}){return Math.hypot(ctx.player.x-p.x,ctx.player.z-p.z)<=RESTORATION_RULES.serviceRange;}
export function restorationCommandPosition(s:RestorationState,plan:RestorationPlan,c:RestorationCommand):{x:number;y:number;z:number}|null {if(c.kind==='stop'||c.kind==='recall'||c.kind==='start'){const site=plan.sites.find(site=>site.id===s.machine?.siteId);return site&&s.machine?.motion?habitatMotionPosition(site,s.machine.motion):null;}const site=plan.sites.find(site=>site.id===c.targetId),dock=site?.cells.find(c=>c.id===site.dockCellId);return dock?{x:dock.x,y:dock.y,z:dock.z}:null;}
export function applyRestorationCommand(state:RestorationState,plan:RestorationPlan,ctx:RestorationContext,command:RestorationCommand):{state:RestorationState;inventory:RestorationInventory;hp:number;message:string} {const fail=(message:string)=>({state,inventory:ctx.inventory,hp:ctx.player.hp,message});if(!validRestoration(state,plan)||!validRestorationCommand(command)||command.expectedRevision!==state.revision||!actorOK(ctx,state))return fail('Restoration intent is stale, invalid, or unavailable while incapacitated.');const position=restorationCommandPosition(state,plan,command);if(!position||!near(ctx,position))return fail('Move within 3.5 m of the restoration control.');const s=structuredClone(state),m=s.machine,siteIndex=plan.sites.findIndex(p=>p.id===command.targetId),site=s.sites[siteIndex],sitePlan=plan.sites[siteIndex];let inventory={...ctx.inventory},hp=ctx.player.hp,message='';
 if(command.kind==='refit'){
  if(m&&m.status!=='packed')return fail('Recall and pack the automaton before refitting.');const body=compileRestorationBody(command.recipe),old=m?compileRestorationBody(m.recipe).cost:{scrap:0,core:0};if(inventory.scrap+old.scrap<body.cost.scrap||inventory.core+old.core<body.cost.core)return fail(`This body needs ${body.cost.scrap} scrap and ${body.cost.core} core in structural parts.`);if(m&&(m.charge>body.stats.chargeCapacity||m.filter>body.stats.filtrationCapacity||m.waste>body.stats.filtrationCapacity||m.tank.waterMl>body.stats.tankCapacityMl))return fail('Service or empty stored contents before reducing capacity.');inventory.scrap+=old.scrap-body.cost.scrap;inventory.core+=old.core-body.cost.core;if(m){m.recipe=structuredClone(command.recipe);m.ability=structuredClone(command.ability);m.utility=interruptUtility(m.utility,'refit').state;m.order=null;}else s.machine={recipe:structuredClone(command.recipe),ability:structuredClone(command.ability),status:'packed',siteId:null,motion:null,charge:0,filter:0,waste:0,scentCharge:0,heat:0,tank:{waterMl:0,contaminant:0},utility:createUtilityState(),order:null,blocked:false};message='Structural refit complete. Stored charge, water, waste, and habitat progress are preserved.';
 }else if(command.kind==='deploy'){
  if(!m||m.status!=='packed'||!sitePlan)return fail('Pack a configured automaton before deploying at a habitat dock.');const dock=sitePlan.cells.find(c=>c.id===sitePlan.dockCellId)!,body=compileRestorationBody(m.recipe),radius=body.bounds.radius+.05,actors:readonly HabitatActor[]=[ctx.player,...(ctx.actors??[])];if(actors.some(a=>!Number.isFinite(a.x)||!Number.isFinite(a.z)||a.y!==undefined&&!Number.isFinite(a.y)||a.radius!==undefined&&(!Number.isFinite(a.radius)||a.radius<0)||(a.y===undefined||Math.abs(a.y-dock.y)<=2)&&Math.hypot(a.x-dock.x,a.z-dock.z)<radius+(a.radius??.34)))return fail('Step outside the full body footprint before deploying; keep nearby explorers clear.');m.status='idle';m.siteId=sitePlan.id;m.motion=createHabitatMotion(sitePlan);m.blocked=false;message='Automaton deployed on the certified habitat route.';
 }else if(command.kind==='service'){
  if(!m||m.status!=='packed'||!site||!sitePlan)return fail('Recall and pack the automaton beside this dock to service.');const body=compileRestorationBody(m.recipe),charge=Math.min(body.stats.chargeCapacity-m.charge,site.chargeReserve),filter=Math.min(body.stats.filtrationCapacity-m.filter,site.filterReserve),scent=Math.min(200-m.scentCharge,site.scentReserve),waste=Math.min(m.waste,sitePlan.wasteCapacity-site.sealedWaste);if(charge+filter+scent+waste===0)return fail('No cartridge transfer is available at this finite dock.');m.charge+=charge;site.chargeReserve-=charge;m.filter+=filter;site.filterReserve-=filter;m.scentCharge+=scent;site.scentReserve-=scent;m.waste-=waste;site.sealedWaste+=waste;message=`Transferred ${charge} charge, ${filter} filter, ${scent} scent; sealed ${waste} contaminant units.`;
 }else if(command.kind==='repair'){
  if(!site||site.completedAtTick===null)return fail('Restore this habitat before using its recovered biomass.');const need=Math.min(100-hp,20),available=site.cells.reduce((n,c)=>n+Math.max(0,c.biomass-2),0),used=Math.min(Math.ceil(need/2),available);if(used<=0)return fail('No suit damage or recoverable biomass is available.');let left=used;for(const c of site.cells){const take=Math.min(left,Math.max(0,c.biomass-2));c.biomass-=take;left-=take;}site.repairUsed+=used;s.sinks.organic+=used;hp=Math.min(100,hp+used*2);message=`Suit repaired by ${hp-ctx.player.hp} HP using ${used} recovered biomass.`;
 }else if(command.kind==='recall'){
  if(!m||!m.motion||m.status==='packed'||command.targetId!==m.siteId)return fail('No deployed automaton belongs to this site.');m.utility=interruptUtility(m.utility,'stop').state;m.order=null;m.status='returning';message='Automaton is returning along the certified path; it packs only at the dock.';
 }else if(command.kind==='stop'){
  if(!m||m.status==='packed'||command.targetId!==m.siteId)return fail('No deployed automaton belongs to this site.');m.utility=interruptUtility(m.utility,'stop').state;m.status='idle';m.order=null;message='Utility interrupted. Paid energy and captured mass stay accounted for.';
 }else if(command.kind==='start'){
  if(!m||!m.motion||m.status==='packed'||m.status==='returning')return fail('Deploy the automaton before starting utility work.');const p=plan.sites.find(p=>p.id===m.siteId)!,ids=p.cells.map(c=>c.id),source=command.sourceId,target=command.targetId;if(m.recipe.organ==='pump'){if(source===target||!(source==='tank'||ids.includes(source))||!(target==='tank'||ids.includes(target))||(source!=='tank'&&target!=='tank'&&!p.edges.some(e=>e.a===source&&e.b===target||e.b===source&&e.a===target)))return fail('Pump between adjacent cells or a habitat cell and the onboard tank.');}else if(source!==target||!ids.includes(source))return fail('Select one habitat cell for this organ.');const travel=source==='tank'?target:source,cell=p.cells.find(c=>c.id===travel)!;const ambient=s.sites.find(site=>site.id===m.siteId)!.cells.find(c=>c.id===m.motion!.cellId)!.smoke;if(Math.hypot(cell.x-position.x,cell.z-position.z)>compileRestorationBody(m.recipe).stats.sensorRange/(1+ambient/40))return fail('The target is outside this body sensor range.');m.utility=interruptUtility(m.utility,'stop').state;m.utility=interruptUtility(m.utility,'stop').state;m.order={sourceId:source,targetId:target};m.status='working';m.blocked=false;message='Utility order accepted. Any previous cast keeps its cooldown; the automaton reaches the source before a fresh windup.';
 }
 if(site&&['refit','service','deploy'].includes(command.kind)&&site.activatedAtTick===null){site.activatedAtTick=s.tick;record(s,'activate',site.id);}s.revision++;record(s,command.kind,command.targetId,command.kind==='repair'?hp-ctx.player.hp:0);return {state:commit(s),inventory,hp,message};
}
function activeSite(s:RestorationState,plan:RestorationPlan){const index=plan.sites.findIndex(p=>p.id===s.machine?.siteId);return index<0?null:{site:s.sites[index]!,plan:plan.sites[index]!};}
function usablePulse(s:RestorationState,p:HabitatSitePlan,site:RestorationSite,m:RestorationMachine,pulse:UtilityPulse):boolean {const source=pulse.sourceId==='tank'?m.tank:site.cells.find(c=>c.id===pulse.sourceId),target=pulse.targetId==='tank'?m.tank:site.cells.find(c=>c.id===pulse.targetId);if(!source||!target)return false;const amount=pulse.effectUnits,body=compileRestorationBody(m.recipe);let effect=0;
 if(pulse.organ==='pump'){const capacity=pulse.targetId==='tank'?body.stats.tankCapacityMl:RESTORATION_RULES.cellCapacityMl;effect=Math.min(amount,source.waterMl,capacity-target.waterMl);if(effect>0){const mass=habitatMixture(source.waterMl,source.contaminant,effect);source.waterMl-=effect;source.contaminant-=mass;target.waterMl+=effect;target.contaminant+=mass;}}
 else if(pulse.organ==='filter'){effect=Math.min(amount,source.contaminant,m.filter,body.stats.filtrationCapacity-m.waste,pulse.consumedFiltration);if(effect>0){source.contaminant-=effect;m.waste+=effect;m.filter-=effect;s.sinks.filter+=effect;}}
 else if(pulse.organ==='vent'&&'heat'in source){const heat=Math.min(amount,(source as RestorationCell).heat),smoke=Math.min(Math.max(1,Math.floor(amount/10)),(source as RestorationCell).smoke);(source as RestorationCell).heat-=heat;(source as RestorationCell).smoke-=smoke;s.sinks.heat+=heat;s.sinks.smoke+=smoke;effect=heat+smoke;}
 else if(pulse.organ==='beacon'&&'scent'in target){effect=Math.min(amount,m.scentCharge);(target as RestorationCell).scent+=effect;m.scentCharge-=effect;}
 // Even a source depleted during windup dissipates the committed utility energy as heat.
 m.charge-=pulse.consumedEnergy;m.heat+=pulse.consumedEnergy;return effect>0;
}
function workPossible(site:RestorationSite,m:RestorationMachine):boolean {const order=m.order;if(!order)return false;const a=order.sourceId==='tank'?m.tank:site.cells.find(c=>c.id===order.sourceId),b=order.targetId==='tank'?m.tank:site.cells.find(c=>c.id===order.targetId);if(!a||!b)return false;const body=compileRestorationBody(m.recipe);switch(m.recipe.organ){case'pump':return a.waterMl>0&&b.waterMl<(order.targetId==='tank'?body.stats.tankCapacityMl:RESTORATION_RULES.cellCapacityMl);case'filter':return a.contaminant>0&&m.filter>0&&m.waste<body.stats.filtrationCapacity;case'vent':return 'heat'in a&&((a as RestorationCell).heat>0||(a as RestorationCell).smoke>0);case'beacon':return m.scentCharge>0;}}
function stopMachine(s:RestorationState,m:RestorationMachine,reason:'blocked'|'heat'|'depleted'){m.utility=interruptUtility(m.utility,reason).state;m.status='idle';m.order=null;record(s,'interrupt',m.siteId??'packed');}
function stepMachine(s:RestorationState,plan:RestorationPlan,tuning:RestorationTuning,ctx:Pick<RestorationContext,'blockedEdgeIds'|'actors'>&{player?:RestorationContext['player']}){const m=s.machine;if(!m)return;const cooled=Math.min(2,m.heat);m.heat-=cooled;s.sinks.heat+=cooled;const active=activeSite(s,plan);if(!active||!m.motion){m.utility=stepUtility(m.utility,{energyAvailable:m.charge,filtrationAvailable:m.filter,interrupted:true,occluded:false,overheated:false}).state;return;}const p=active.plan,site=active.site,body=compileRestorationBody(m.recipe);let desired=m.status==='idle'?m.motion.cellId:m.motion.targetId;if(m.status==='returning')desired=p.dockCellId;else if(m.status==='working'&&m.order)desired=m.order.sourceId==='tank'?m.order.targetId:m.order.sourceId;
 m.motion=targetHabitatMotion(p,m.motion,desired);if(m.motion.cellId!==m.motion.targetId||m.motion.progressMm>0){if(m.charge<=0){const at=habitatMotionPosition(p,m.motion);if(m.status!=='returning'||!ctx.player||ctx.player.hp<=0||Math.hypot(ctx.player.x-at.x,ctx.player.z-at.z)>3.5){m.blocked=true;return;}}const moved=advanceHabitatMotion(p,m.motion,body.stats.maxSpeed,tuning,ctx,body.bounds.radius+.05);m.blocked=moved.blocked;if(moved.motion!==m.motion){m.motion=moved.motion;if(m.charge>0){m.charge--;m.heat++;}}return;}m.blocked=false;
 if(m.status==='returning'){m.status='packed';m.siteId=null;m.motion=null;return;}
 const cell=site.cells.find(c=>c.id===m.motion!.cellId)!;const overheat=m.heat>body.stats.heatTolerance||cell.heat>body.stats.heatTolerance*12;
 if(m.status==='working'&&!workPossible(site,m)){stopMachine(s,m,'depleted');return;}
 if(m.status==='working'&&overheat){stopMachine(s,m,'heat');return;}
 const target=m.order?.targetId,source=m.order?.sourceId,edge=p.edges.find(e=>e.a===source&&e.b===target||e.b===source&&e.a===target),sourceCell=site.cells.find(c=>c.id===source),targetCell=site.cells.find(c=>c.id===target),sourcePos=p.cells.find(c=>c.id===source),targetPos=p.cells.find(c=>c.id===target),smokeOccluded=!!sourcePos&&!!targetPos&&Math.hypot(sourcePos.x-targetPos.x,sourcePos.z-targetPos.z)>body.stats.reach/(1+Math.max(sourceCell?.smoke??0,targetCell?.smoke??0)/40),occluded=(!!edge&&!!ctx.blockedEdgeIds?.includes(edge.id))||smokeOccluded;
 if(m.status==='working'&&occluded){stopMachine(s,m,'blocked');return;}
 if(m.status==='working'&&m.utility.phase==='idle'&&m.order){const ability=compileUtilityAbility(m.ability);if(m.charge<ability.energyCost){stopMachine(s,m,'depleted');return;}const request=requestUtility(m.utility,m.ability,{intentId:m.utility.lastIntentId+1,...m.order},{energyAvailable:m.charge,filtrationAvailable:m.filter,workSpeed:body.stats.workSpeed});m.utility=request.state;}
 const result=stepUtility(m.utility,{energyAvailable:m.charge,filtrationAvailable:m.filter,interrupted:false,occluded,overheated:overheat});m.utility=result.state;if(result.pulse)usablePulse(s,p,site,m,result.pulse);
}
export function restorationCellViable(c:RestorationCell){return c.waterMl>=RESTORATION_RULES.healthyWaterMl&&c.contaminant<=RESTORATION_RULES.healthyContaminant&&c.heat<=RESTORATION_RULES.healthyHeat&&c.smoke<=RESTORATION_RULES.healthySmoke;}
function stepRestoration(s:RestorationState,plan:RestorationPlan,tuning:RestorationTuning,ctx:Pick<RestorationContext,'blockedEdgeIds'|'actors'>&{player?:RestorationContext['player']}){s.tick++;for(let i=0;i<s.sites.length;i++){const site=s.sites[i]!,p=plan.sites[i]!;if(site.activatedAtTick===null)continue;const edges=p.edges.filter(e=>!ctx.blockedEdgeIds?.includes(e.id)).map(e=>({a:p.cells.findIndex(c=>c.id===e.a),b:p.cells.findIndex(c=>c.id===e.b)})),fields=stepHabitatFields(site.cells.map(({waterMl,contaminant,heat,smoke,scent})=>({waterMl,contaminant,heat,smoke,scent})),edges,{waterConductance:tuning.waterConductance,airConductance:tuning.airConductance,cellCapacityMl:RESTORATION_RULES.cellCapacityMl});site.cells.forEach((c,j)=>Object.assign(c,fields.cells[j]));
  for(const c of site.cells){const heat=Math.min(c.heat,1),smoke=s.tick%4===0?Math.min(c.smoke,1):0,scent=Math.min(c.scent,1);c.heat-=heat;c.smoke-=smoke;c.scent-=scent;s.sinks.heat+=heat;s.sinks.smoke+=smoke;s.sinks.scent+=scent;}
  const target=chooseHabitatScentTarget(p,site.cells,site.pollinator,tuning.scentWeight);site.pollinator=targetHabitatMotion(p,site.pollinator,target);const before=site.pollinator;site.pollinator=advanceHabitatMotion(p,site.pollinator,.75,{...tuning,machineSpeedPercent:100},{blockedEdgeIds:ctx.blockedEdgeIds??[]},.1).motion;if(before.cellId!==site.pollinator.cellId)site.pollinatorVisits++;
  if(s.tick%tuning.growthIntervalTicks===0)for(const c of site.cells){if(restorationCellViable(c)&&c.nutrient>0&&c.waterMl>=RESTORATION_RULES.healthyWaterMl+2){const growth=site.pollinator.cellId===c.id&&site.pollinator.progressMm===0&&c.scent>0?2:1,amount=Math.min(growth,c.nutrient,Math.floor((c.waterMl-RESTORATION_RULES.healthyWaterMl)/2));c.nutrient-=amount;c.biomass+=amount;c.waterMl-=amount*2;s.sinks.waterMl+=amount*2;c.health=Math.min(100,c.health+amount*3);}else if(!restorationCellViable(c))c.health=Math.max(0,c.health-2);}
  if(site.cells.every(c=>restorationCellViable(c)&&c.health>=RESTORATION_RULES.completionHealth))site.stableTicks=Math.min(RESTORATION_RULES.completionTicks,site.stableTicks+1);else site.stableTicks=0;if(site.stableTicks===RESTORATION_RULES.completionTicks&&site.completedAtTick===null){site.completedAtTick=s.tick;record(s,'restore',site.id);}
 }stepMachine(s,plan,tuning,ctx);}
/** Active-play time only. Excess frame time is dropped; no wall-clock or offline catch-up. */
export function advanceRestoration(state:RestorationState,plan:RestorationPlan,dt:number,ctx:Pick<RestorationContext,'blockedEdgeIds'|'actors'>&{player?:RestorationContext['player']}={},tuning:RestorationTuning=RESTORATION_DEFAULTS):RestorationState {if(!validRestoration(state,plan)||!Number.isFinite(dt)||dt<=0||state.tick>=RESTORATION_RULES.maxTicks||!validRestorationTuning(tuning))return state;const sum=state.remainder+Math.min(RESTORATION_RULES.maxDelta,dt),steps=Math.min(4,Math.floor((sum+1e-10)/.25),RESTORATION_RULES.maxTicks-state.tick);let remainder=Math.max(0,sum-steps*.25);if(remainder<1e-10||state.tick+steps===RESTORATION_RULES.maxTicks)remainder=0;if(!steps)return commit({...state,remainder});if(!state.machine&&state.sites.every(site=>site.activatedAtTick===null))return commit({...state,tick:state.tick+steps,remainder});const s=structuredClone(state);s.remainder=remainder;for(let i=0;i<steps;i++)stepRestoration(s,plan,tuning,ctx);return commit(s);}
/** Conservative feasibility across any supported Apply-time interval changes; no history is invented. */
function earliestGrowthTick(events:number,startTick:number):number {let seen=0;for(let tick=startTick+1;tick<=startTick+256;tick++){if(Array.from({length:37},(_,i)=>i+4).some(interval=>tick%interval===0)&&++seen>=events)return tick;}return Infinity;}
export function validRestoration(v:unknown,plan:RestorationPlan):v is RestorationState {try{
 if(!restorationKeys(v,STATE_KEYS)||v.version!==1||v.seed!==plan.seed||v.planId!==plan.id)return false;if(trusted.has(v))return true;
 const s=v as unknown as RestorationState;if(!restorationInteger(s.revision)||!restorationInteger(s.tick,RESTORATION_RULES.maxTicks)||!(typeof s.remainder==='number'&&Number.isFinite(s.remainder)&&s.remainder>=0&&s.remainder<.25)||!restorationArray(s.sites,3,3)||!inventoryOK(s.spent)||Object.values(s.spent).some(n=>n!==0)||!restorationKeys(s.sinks,['waterMl','heat','smoke','scent','organic','filter'])||!Object.values(s.sinks).every(n=>restorationInteger(n))||!restorationArray(s.records,0,24))return false;
 for(let i=0;i<s.sites.length;i++){const site=s.sites[i]!,p=plan.sites[i]!;if(!restorationKeys(site,['id','activatedAtTick','cells','chargeReserve','filterReserve','scentReserve','sealedWaste','stableTicks','completedAtTick','repairUsed','pollinator','pollinatorVisits'])||site.id!==p.id||site.activatedAtTick!==null&&!restorationInteger(site.activatedAtTick,s.tick)||!restorationArray(site.cells,p.cells.length,p.cells.length)||!restorationInteger(site.chargeReserve,p.initialCharge)||!restorationInteger(site.filterReserve,p.initialFilter)||!restorationInteger(site.scentReserve,p.initialScent)||!restorationInteger(site.sealedWaste,p.wasteCapacity)||!restorationInteger(site.stableTicks,16)||site.completedAtTick!==null&&(!restorationInteger(site.completedAtTick,s.tick)||site.completedAtTick<16)||!restorationInteger(site.repairUsed,plan.totals.organic)||site.completedAtTick===null&&site.repairUsed!==0||!validHabitatMotion(site.pollinator,p)||!restorationInteger(site.pollinatorVisits,s.tick))return false;
  for(let j=0;j<site.cells.length;j++){const c=site.cells[j]!,initial=p.cells[j]!;if(!restorationKeys(c,['id','waterMl','contaminant','heat','smoke','scent','nutrient','biomass','health'])||c.id!==initial.id||!restorationInteger(c.waterMl,2000)||!restorationInteger(c.contaminant,plan.totals.contaminant)||!restorationInteger(c.heat,plan.totals.energy)||!restorationInteger(c.smoke,plan.totals.smoke)||!restorationInteger(c.scent,plan.totals.scent)||!restorationInteger(c.nutrient,initial.initialNutrient)||!restorationInteger(c.biomass,initial.initialNutrient+initial.initialBiomass)||!restorationInteger(c.health,100))return false;}
 }
 if(s.machine!==null){const m=s.machine;if(!restorationKeys(m,['recipe','ability','status','siteId','motion','charge','filter','waste','scentCharge','heat','tank','utility','order','blocked'])||!validRestorationBodyRecipe(m.recipe)||!validUtilityRecipeInput(m.ability)||m.ability.organ!==m.recipe.organ||!['packed','idle','working','returning'].includes(m.status)||typeof m.blocked!=='boolean'||!validUtilityState(m.utility))return false;const body=compileRestorationBody(m.recipe);if(!restorationInteger(m.charge,body.stats.chargeCapacity)||!restorationInteger(m.filter,body.stats.filtrationCapacity)||!restorationInteger(m.waste,body.stats.filtrationCapacity)||!restorationInteger(m.scentCharge,200)||!restorationInteger(m.heat,plan.totals.energy)||!restorationKeys(m.tank,['waterMl','contaminant'])||!restorationInteger(m.tank.waterMl,body.stats.tankCapacityMl)||!restorationInteger(m.tank.contaminant,plan.totals.contaminant))return false;
  const p=plan.sites.find(p=>p.id===m.siteId);if(m.status==='packed'?(m.siteId!==null||m.motion!==null||m.order!==null):(!p||s.sites.find(site=>site.id===p.id)?.activatedAtTick===null||!validHabitatMotion(m.motion,p)))return false;if(m.status==='working'){if(!restorationKeys(m.order,['sourceId','targetId']))return false;const ids=p!.cells.map(c=>c.id),a=m.order.sourceId,b=m.order.targetId;if(m.recipe.organ==='pump'){if(a===b||!(a==='tank'||ids.includes(a))||!(b==='tank'||ids.includes(b))||a!=='tank'&&b!=='tank'&&!p!.edges.some(e=>e.a===a&&e.b===b||e.b===a&&e.a===b))return false;}else if(a!==b||!ids.includes(a))return false;}else if(m.order!==null)return false;
  if(m.utility.target){const ids=[...plan.sites.flatMap(p=>p.cells.map(c=>c.id)),'tank'];if(!ids.includes(m.utility.target.sourceId)||!ids.includes(m.utility.target.targetId))return false;if(['prep','active','recovery'].includes(m.utility.phase)&&(m.status!=='working'||m.utility.target.sourceId!==m.order?.sourceId||m.utility.target.targetId!==m.order?.targetId||m.utility.recipe?.recipe.organ!==m.recipe.organ||m.utility.recipe.recipe.strength!==m.ability.strength||m.utility.recipe.recipe.tempo!==m.ability.tempo||m.utility.workSpeed!==body.stats.workSpeed))return false;}
 }
 let last=-1;for(const r of s.records){if(!restorationKeys(r,['tick','kind','targetId','amount'])||!restorationInteger(r.tick,s.tick)||r.tick<last||!['activate','refit','deploy','recall','start','stop','service','restore','repair','interrupt'].includes(r.kind)||typeof r.targetId!=='string'||r.targetId.length<1||r.targetId.length>64||!restorationInteger(r.amount,1000))return false;last=r.tick;}
 if(s.sites.reduce((n,site)=>n+site.repairUsed,0)!==s.sinks.organic)return false;const captured=s.sites.reduce((n,site)=>n+site.sealedWaste,0)+(s.machine?.waste??0);if(captured!==s.sinks.filter)return false;let grown=0;for(let i=0;i<s.sites.length;i++){const site=s.sites[i]!,p=plan.sites[i]!;if(site.activatedAtTick===null&&(site.chargeReserve!==p.initialCharge||site.filterReserve!==p.initialFilter||site.scentReserve!==p.initialScent||site.sealedWaste!==0||site.stableTicks!==0||site.completedAtTick!==null||site.repairUsed!==0||site.pollinatorVisits!==0||site.pollinator.cellId!==p.dockCellId||site.pollinator.targetId!==p.dockCellId||site.pollinator.route.length!==1||site.pollinator.route[0]!==p.dockCellId||site.pollinator.routeIndex!==0||site.pollinator.progressMm!==0||site.cells.some((c,j)=>{const initial=p.cells[j]!;return Object.entries(initial.initial).some(([key,value])=>c[key as keyof HabitatFields]!==value)||c.nutrient!==initial.initialNutrient||c.biomass!==initial.initialBiomass||c.health!==initial.initialHealth;})))return false;const growth=site.cells.reduce((n,c,j)=>n+p.cells[j]!.initialNutrient-c.nutrient,0);grown+=growth;if(site.cells.reduce((n,c)=>n+c.biomass,0)+site.repairUsed!==p.cells.reduce((n,c)=>n+c.initialBiomass,0)+growth)return false;for(let j=0;j<site.cells.length;j++){const c=site.cells[j]!,initial=p.cells[j]!;if(c.health>Math.min(100,initial.initialHealth+3*(initial.initialNutrient-c.nutrient)))return false;if(site.completedAtTick!==null&&initial.initialNutrient-c.nutrient<Math.ceil((RESTORATION_RULES.completionHealth-initial.initialHealth)/3))return false;}if(site.completedAtTick!==null){const required=p.cells.map(c=>Math.max(0,Math.ceil((RESTORATION_RULES.completionHealth-c.initialHealth)/3))),events=Math.max(Math.ceil(Math.max(...required)/2),Math.ceil(required.reduce((a,b)=>a+b,0)/(p.cells.length+1)));if(site.completedAtTick<earliestGrowthTick(events,site.activatedAtTick??s.tick)+RESTORATION_RULES.completionTicks-1)return false;}if(site.stableTicks>0&&!site.cells.every(c=>restorationCellViable(c)&&c.health>=70))return false;}if(s.sinks.waterMl!==grown*2)return false;
 return Object.values(restorationBalances(s,plan)).every(n=>n===0);
 }catch{return false;}}
const imported=new WeakMap<object,{signature:string;state:RestorationState}>();
export function immutableRestoration(v:unknown,plan:RestorationPlan):RestorationState {if(!validRestoration(v,plan))throw new Error('Invalid restoration save');if(trusted.has(v))return v;const signature=JSON.stringify(v),old=imported.get(v);if(old?.signature===signature)return old.state;const s=commit(structuredClone(v));imported.set(v,{signature,state:s});return s;}
export function restorationMachinePosition(s:RestorationState,plan:RestorationPlan){const active=activeSite(s,plan);return active&&s.machine?.motion?habitatMotionPosition(active.plan,s.machine.motion):null;}

/** Named immutable runtime surface for source/emitted authoritative parity probes. */
export const RESTORATION_ENGINE=Object.freeze({kind:'axiom-restoration' as const,version:1 as const,create:createRestoration,advance:advanceRestoration,command:applyRestorationCommand,validate:validRestoration,immutable:immutableRestoration,balances:restorationBalances,plan:restorationPlan,commandValid:validRestorationCommand,playerCost:restorationPlayerCost,machinePosition:restorationMachinePosition,cellViable:restorationCellViable});
