import {applyRestorationCommand,createRestoration,restorationBalances,restorationPlan,RESTORATION_DEFAULTS,validRestorationTuning,type HabitatSiteDescriptor,type RestorationContext,type RestorationPlan,type RestorationState,type RestorationTuning} from './restoration.ts';
import type {RestorationOrgan} from './restoration-body.ts';
export const RESTORATION_SCENARIOS=Object.freeze([{id:'filter-mass',label:'Filter polluted habitat',organ:'filter'},{id:'vent-heat',label:'Cool heat and clear smoke',organ:'vent'},{id:'pump-mixture',label:'Move a conservative water mixture',organ:'pump'},{id:'beacon-route',label:'Attract a pollinator along a finite route',organ:'beacon'}] as const);
export type RestorationScenarioId=typeof RESTORATION_SCENARIOS[number]['id'];
/** Synthetic flat fixtures, never campaign placement. The world owner provides real ground-certified sites. */
export function restorationScenarioDescriptors():readonly HabitatSiteDescriptor[]{return [0,1,2].map(n=>{const id=`lab-habitat-${n}`,cells=[0,1,2,3].map(i=>({id:`${id}-cell-${i}`,x:n*20+(i%2)*2,y:0,z:Math.floor(i/2)*2}));return {id,label:`Disposable habitat ${n+1}`,x:n*20,y:0,z:0,dockCellId:cells[0]!.id,cells,edges:[[0,1],[0,2],[1,3],[2,3]].map(([a,b],i)=>({id:`${id}-edge-${i}`,a:cells[a!]!.id,b:cells[b!]!.id,path:[cells[a!]!,cells[b!]!].map(({x,y,z})=>({x,y,z}))}))};});}
export interface RestorationScenario {mode:'disposable-model';id:RestorationScenarioId;plan:RestorationPlan;state:RestorationState;context:RestorationContext;tuning:RestorationTuning;authorizedFixtureInventory:{scrap:number;core:number;water:number}}
/** Reset is construction from initial finite stores, with explicit lab-only paid fixture stock. */
export function createRestorationScenario(seed:number,id:RestorationScenarioId='filter-mass',tuning:RestorationTuning={...RESTORATION_DEFAULTS},descriptors=restorationScenarioDescriptors()):RestorationScenario {const scenario=RESTORATION_SCENARIOS.find(s=>s.id===id);if(!scenario||!validRestorationTuning(tuning))throw new Error('Invalid restoration scenario');const plan=restorationPlan(seed,descriptors),dock=plan.sites[0]!,authorizedFixtureInventory={scrap:20,core:2,water:0};let state=createRestoration(plan),context:RestorationContext={seed,zone:'valley',player:{x:dock.x,z:dock.z-2.5,hp:70},inventory:{...authorizedFixtureInventory}};const refit=applyRestorationCommand(state,plan,context,{kind:'refit',targetId:dock.id,expectedRevision:state.revision,recipe:{version:1,seed,support:'nimble',shell:'reed',organ:scenario.organ as RestorationOrgan},ability:{version:1,organ:scenario.organ,strength:1,tempo:'steady'}});state=refit.state;context={...context,inventory:refit.inventory};for(const kind of ['service','deploy'] as const)state=applyRestorationCommand(state,plan,context,{kind,targetId:dock.id,expectedRevision:state.revision}).state;return {mode:'disposable-model',id,plan,state,context,tuning:{...tuning},authorizedFixtureInventory};}
export function restorationEvidence(scenario:RestorationScenario){return {version:1,source:'restoration-engine/v1',mode:scenario.mode,scenario:scenario.id,seed:scenario.plan.seed,planId:scenario.plan.id,tuning:{...scenario.tuning},tick:scenario.state.tick,revision:scenario.state.revision,balances:restorationBalances(scenario.state,scenario.plan),sites:scenario.state.sites.map(s=>({id:s.id,activatedAtTick:s.activatedAtTick,completedAtTick:s.completedAtTick,repairUsed:s.repairUsed,pollinatorVisits:s.pollinatorVisits,cells:s.cells.map(c=>({...c}))})),machine:scenario.state.machine?{status:scenario.state.machine.status,recipe:scenario.state.machine.recipe,ability:scenario.state.machine.ability,charge:scenario.state.machine.charge,waste:scenario.state.machine.waste,tank:{...scenario.state.machine.tank},phase:scenario.state.machine.utility.phase}:null,actions:scenario.state.records.map(r=>({...r}))};}
