import {restorationPlan,restorationCareHarvestable,type RestorationPlan,type RestorationState} from './restoration.ts';
import {habitatSiteDescriptors} from './habitat-sites.ts';
import {restorationCareBlockReason,restorationCarePosition,type RestorationCareCommand,type RestorationCareState} from './restoration-care.ts';
import {townResidents} from './town-residents.ts';
import type {TownLifeState} from './town-life.ts';
export interface RestorationCareViewState {seed:number;zone:string;player:{x:number;z:number;hp:number;y?:number;feetY?:number};restoration?:RestorationState;townLife?:TownLifeState;restorationCare?:RestorationCareState}
export interface RestorationCareUIOptions {getState:()=>RestorationCareViewState;getPlan?:()=>RestorationPlan;send:(command:RestorationCareCommand)=>void|false|string;blockedReason?:(command:RestorationCareCommand)=>string|null;onClose:()=>void;ready?:(command:RestorationCareCommand)=>boolean;visit?:()=>void;habitats?:()=>void;map?:(targetId:string)=>void;disposable?:boolean;initialSiteId?:string;onSelection?:(id:string)=>void}
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
/** Read-only state projection; only an explicit collect/deliver click emits a command. */
export function mountRestorationCare(panel:HTMLElement,options:RestorationCareUIOptions){
 let disposed=false;const initial=options.getState(),plan=options.getPlan?.()??restorationPlan(initial.seed,habitatSiteDescriptors(initial.seed));
 panel.innerHTML=`<button id="rc-close" class="close" aria-label="Close habitat care">×</button><span class="eyebrow">Habitat care · Greenlight Apothecary</span><h2>Bring restoration home</h2><p>Restore a habitat, collect 5 surplus biomass portions, then carry them back to Greenlight. Every cell must remain viable with at least 70 health; collection leaves two biomass per cell. The shared satchel holds 10 portions, and Greenlight holds 20.</p><p>In shared worlds, the host collects and delivers the shared satchel. ${options.disposable?'This is a disposable model; the lab explicitly places its test operator at a target. It does not simulate the player’s journey.':'You must physically reach each dock and return to Greenlight. Solo menus pause time: close this panel to let residents travel and receive care. Online time continues.'}</p><div class="row"><button id="rc-habitats" type="button">Habitat restoration</button><button id="rc-map" type="button">Map selected habitat</button><button id="rc-destination-map" type="button">Map delivery station</button><button id="rc-town" type="button">Visit Hearthmere</button></div><label for="rc-site">Habitat source · three existing sites</label><select id="rc-site">${plan.sites.map(s=>`<option value="${esc(s.id)}">${esc(s.label)}</option>`).join('')}</select><p id="rc-source"></p><p id="rc-location"></p><p id="rc-collect-gate"></p><button id="rc-collect" type="button">Collect 5 surplus biomass</button><h3>Return to Greenlight</h3><p id="rc-stock"></p><p id="rc-destination"></p><p id="rc-deliver-gate"></p><button id="rc-deliver" type="button">Deliver carried bundle</button><h3>Care in progress</h3><p>One portion is committed only when a resident actually arrives to begin recovery. Normal town water and material costs still apply. Energy, hygiene and comfort recover at 1.5× only during achieved, unobstructed work. Walking, waiting and blocked work gain no bonus; this is not a passive town buff.</p><p id="rc-active"></p><p id="rc-status" role="status"></p>`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#rc-'+id)!;const marker=q('status'),current=()=>!disposed&&panel.querySelector('#rc-status')===marker;
 const nearest=()=>plan.sites.slice().sort((a,b)=>Math.hypot(a.x-options.getState().player.x,a.z-options.getState().player.z)-Math.hypot(b.x-options.getState().player.x,b.z-options.getState().player.z)||a.id.localeCompare(b.id))[0]!.id;
 q<HTMLSelectElement>('site').value=options.initialSiteId===undefined?plan.sites[0]!.id:plan.sites.some(s=>s.id===options.initialSiteId)?options.initialSiteId:nearest();
 let lastSelection:string|undefined;function resolveSelection(){const select=q<HTMLSelectElement>('site');if(!plan.sites.some(s=>s.id===select.value))select.value=nearest();if(lastSelection!==select.value){lastSelection=select.value;options.onSelection?.(select.value);}}
 function command(kind:'collect'|'deliver'):RestorationCareCommand{return {kind,targetId:kind==='collect'?q<HTMLSelectElement>('site').value:'apothecary',expectedRevision:options.getState().restorationCare?.revision??0};}
 function reason(c:RestorationCareCommand){const s=options.getState();if(!s.restoration||!s.townLife)return 'Visit Hearthmere and open habitat restoration to initialize these existing systems.';const readiness=options.blockedReason?.(c);if(readiness)return readiness;if(options.ready&&!options.ready(c))return 'The host must reach this target on foot; wait for terrain and authority readiness.';return restorationCareBlockReason(s.restorationCare,s.restoration,plan,s.townLife,s,c);}
 const at=(p:{x:number;y:number;z:number}|null)=>p?`x ${p.x.toFixed(1)}, y ${p.y.toFixed(1)}, z ${p.z.toFixed(1)} · ${Math.hypot(options.getState().player.x-p.x,options.getState().player.z-p.z).toFixed(1)} m away`:'Location unavailable';
 function refresh(){if(!current())return;resolveSelection();const s=options.getState(),id=q<HTMLSelectElement>('site').value,site=s.restoration?.sites.find(v=>v.id===id),harvest=s.restoration?restorationCareHarvestable(s.restoration,id):0;
 q('source').textContent=site?`${site.activatedAtTick===null?'Dormant · not restored':site.completedAtTick===null?'Restoring · not restored':`Restored at tick ${site.completedAtTick}`} · currently harvestable ${harvest} biomass. ${site.cells.map(c=>`${c.id}: ${c.health}/100 health, ${c.biomass} biomass`).join(' · ')}`:'Habitat data unavailable.';
 q('location').textContent='Source dock: '+at(restorationCarePosition(plan,command('collect')));q('destination').textContent='Greenlight care station: '+at(restorationCarePosition(plan,command('deliver')));
 const care=s.restorationCare,stock=s.townLife?.habitatCare;q('stock').textContent=`Exported ${s.restoration?.sites.reduce((n,site)=>n+(site.careExported??0),0)??0} lifetime portions · shared satchel ${care?.carried??0}/10 · Greenlight stock ${stock?.stock??0}/20 · delivered ${care?.delivered??0} lifetime portions. ${stock?`Consumed ${stock.used} portions on actual recovery arrival.`:'No care portions delivered yet.'}`;
 const roster=townResidents(s.seed),recover=s.townLife?.residents.filter(r=>r.action==='recover')??[];q('active').textContent=recover.length?recover.map(r=>`${roster[r.index]?.name??r.id}: ${r.status}${r.habitatCare?' · active habitat portion, 1.5× energy/hygiene/comfort':' · no habitat portion committed'}, energy ${r.needs.energy.toFixed(1)}, hygiene ${r.needs.hygiene.toFixed(1)}, comfort ${r.needs.comfort.toFixed(1)} / 100; x ${r.x.toFixed(1)}, z ${r.z.toFixed(1)}; ${r.reason}`).join('\n'):'No resident is currently seeking or receiving recovery. Residents choose care through their existing needs; delivered stock does not force a journey.';
 for(const kind of ['collect','deliver'] as const){const blocked=reason(command(kind));q(kind+'-gate').textContent=blocked??(kind==='collect'?'Ready to collect one finite bundle.':'Ready to deliver the entire carried bundle.');q<HTMLButtonElement>(kind).disabled=!!blocked;}
 }
 for(const kind of ['collect','deliver'] as const)q(kind).onclick=()=>{if(!current())return;const c=command(kind),blocked=reason(c);if(blocked){refresh();if(current())marker.textContent=blocked;return;}const result=options.send(c);if(!current())return;if(result===false||typeof result==='string'){marker.textContent=typeof result==='string'?result:'Request not sent. Recheck connection and readiness, then try again.';refresh();return;}marker.textContent='Request sent. Authority rechecks position, stock and the transfer revision.';refresh();};
 q<HTMLSelectElement>('site').onchange=()=>{if(current())refresh();};function dispose(){disposed=true;}q('close').onclick=()=>{if(current()){dispose();options.onClose();}};
 // Navigation can be rejected; its owner disposes only after an accepted transition.
 for(const [id,fn] of [['habitats',options.habitats],['map',options.map?()=>options.map!(q<HTMLSelectElement>('site').value):undefined],['destination-map',options.map?()=>options.map!('apothecary'):undefined],['town',options.visit]] as const){q<HTMLButtonElement>(id).disabled=!fn;q(id).onclick=()=>{if(current()&&fn)fn();};}
 refresh();return {refresh,dispose};
}
