import * as THREE from 'three/webgpu';
import {compileRestorationBody,type RestorationBodyRecipe} from './restoration-body.ts';
import {quadrupedFoot,quadrupedCycleDistance} from './body.ts';
import {habitatMotionPosition} from './habitat-motion.ts';
import {restorationMachinePosition,type RestorationState,type RestorationPlan} from './restoration.ts';
const PALETTE:Record<string,string>={'restoration-frame':'#a3ada1','restoration-drive':'#697874','restoration-core':'#b2eac4','restoration-support':'#6d7974','restoration-foot':'#b5b490','restoration-reed':'#abac71','restoration-alloy':'#93bbc0','restoration-pump':'#659fa9','restoration-filter':'#82a56d','restoration-vent':'#bd9974','restoration-beacon':'#b99bc1','restoration-metal':'#819294','restoration-cartridge':'#d6c89c'};
/** Separate neutral adapter. It never consumes EnemyState, authorizes work, or changes fields. */
export function createRestorationBodyView(recipe:RestorationBodyRecipe){
 const plan=compileRestorationBody(recipe),root=new THREE.Group();root.name='neutral-restoration-automaton';const materials=new Map<string,THREE.MeshStandardMaterial>(),geometry=new THREE.BoxGeometry(1,1,1);
 const material=(id:string)=>{let m=materials.get(id);if(!m){m=new THREE.MeshStandardMaterial({color:PALETTE[id]??'#8caca1',roughness:.85,flatShading:true});materials.set(id,m);}return m;};
 const groups=new Map<string,{parent:THREE.Group;origin:{x:number;y:number;z:number}}>();
 const legs=plan.legs.map(l=>{const upper=new THREE.Group(),lower=new THREE.Group(),foot=new THREE.Group();upper.position.set(l.hip.x,l.hip.y,l.hip.z);lower.position.set(0,-l.upper,0);foot.position.set(0,-l.lower,0);root.add(upper);upper.add(lower);lower.add(foot);for(const [key,parent,origin] of [[l.nodes.upper,upper,l.hip],[l.nodes.lower,lower,l.knee],[l.nodes.foot,foot,l.foot]] as const)groups.set(key,{parent,origin});return {definition:l,upper,lower,foot};});
 for(const node of plan.plan.nodes){const parent=groups.get(node.key);for(const shape of node.shapes){const m=new THREE.Mesh(geometry,material(shape.material));m.name=shape.id;m.scale.set(shape.half.x*2,shape.half.y*2,shape.half.z*2);m.position.set(shape.center.x-(parent?.origin.x??0),shape.center.y-(parent?.origin.y??0),shape.center.z-(parent?.origin.z??0));m.castShadow=true;(parent?.parent??root).add(m);}}
 let located=false,lastSite='',distance=0;const target=new THREE.Vector3();
 return {root,plan,update(point:{x:number;y:number;z:number},siteId:string,dt:number,enabled:boolean){root.visible=enabled;if(!enabled){located=false;return;}target.set(point.x,point.y,point.z);const before=root.position.clone();if(!located||siteId!==lastSite||dt<=0){root.position.copy(target);located=true;lastSite=siteId;}else root.position.lerp(target,1-Math.exp(-Math.min(dt,.1)*11));const moved=Math.hypot(root.position.x-before.x,root.position.z-before.z),speed=dt>0&&moved<2?Math.min(plan.stats.maxSpeed*1.5,moved/dt):0;if(speed>.02)root.rotation.y=Math.atan2(root.position.x-before.x,root.position.z-before.z);distance+=speed*dt;
   for(const l of legs){if(speed<.02){l.upper.rotation.x=l.lower.rotation.x=l.foot.rotation.x=0;continue;}const f=quadrupedFoot(distance/quadrupedCycleDistance(speed)+l.definition.phase,speed),y=-l.definition.upper-l.definition.lower+.012+f.y,d=Math.min(l.definition.upper+l.definition.lower-.001,Math.max(.04,Math.hypot(f.z,y))),dir=Math.atan2(-f.z,-y),bend=Math.acos(THREE.MathUtils.clamp((l.definition.upper*l.definition.upper+d*d-l.definition.lower*l.definition.lower)/(2*l.definition.upper*d),-1,1));l.upper.rotation.x=dir-bend;l.lower.rotation.x=Math.PI-Math.acos(THREE.MathUtils.clamp((l.definition.upper*l.definition.upper+l.definition.lower*l.definition.lower-d*d)/(2*l.definition.upper*l.definition.lower),-1,1));l.foot.rotation.x=-l.upper.rotation.x-l.lower.rotation.x;}
   root.updateMatrixWorld(true);
  },dispose(){geometry.dispose();for(const m of materials.values())m.dispose();root.removeFromParent();},get distance(){return distance;}};
}

/** Small field plots render only beside confirmed nearby terrain. Water shading shows saturation, not deep-water collision. */
export function createRestorationView(plan:RestorationPlan){
 const root=new THREE.Group();root.name='restoration-habitats';const box=new THREE.BoxGeometry(1,1,1),cylinder=new THREE.CylinderGeometry(1,1,1,8),orb=new THREE.OctahedronGeometry(1,0),ring=new THREE.TorusGeometry(1,.035,4,20);
 const solid=new THREE.MeshStandardMaterial({color:0xffffff,roughness:1,flatShading:true}),waterMaterial=new THREE.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:.72,roughness:.3}),airMaterial=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.14,depthWrite:false}),scentMaterial=new THREE.MeshBasicMaterial({color:0xc7a9e3,transparent:true,opacity:.4,depthWrite:false});
 const sites=plan.sites.map(p=>{const group=new THREE.Group();group.name=p.id;root.add(group);const instances=(geo:THREE.BufferGeometry,mat:THREE.Material,n:number)=>{const m=new THREE.InstancedMesh(geo,mat,n);m.frustumCulled=false;group.add(m);return m;};const dirt=instances(cylinder,solid,p.cells.length),water=instances(cylinder,waterMaterial,p.cells.length),plants=instances(box,solid,p.cells.length*3),smoke=instances(orb,airMaterial,p.cells.length),scent=instances(ring,scentMaterial,p.cells.length),pollinator=new THREE.Mesh(orb,solid);pollinator.scale.set(.14,.1,.18);group.add(pollinator);const dock=new THREE.Mesh(cylinder,solid);dock.position.set(p.x,p.y+.04,p.z);dock.scale.set(.95,.04,.95);group.add(dock);return {group,dirt,water,plants,smoke,scent,pollinator,dock};});
 const matrix=new THREE.Matrix4(),position=new THREE.Vector3(),scale=new THREE.Vector3(),rotation=new THREE.Quaternion(),color=new THREE.Color();let body:ReturnType<typeof createRestorationBodyView>|null=null,bodyHash='',lastTick=-1,visibleSites=0;
 const beamGeometry=new THREE.BufferGeometry().setAttribute('position',new THREE.BufferAttribute(new Float32Array(6),3)),beamMaterial=new THREE.LineBasicMaterial({color:0xb0e8db,transparent:true,opacity:.8}),beam=new THREE.Line(beamGeometry,beamMaterial);beam.frustumCulled=false;root.add(beam);
 function set(m:THREE.InstancedMesh,i:number,p:{x:number;y:number;z:number},size:{x:number;y:number;z:number},hex:string,rotate=false){position.set(p.x,p.y,p.z);scale.set(size.x,size.y,size.z);rotation.setFromAxisAngle(new THREE.Vector3(1,0,0),rotate?Math.PI/2:0);matrix.compose(position,rotation,scale);m.setMatrixAt(i,matrix);m.setColorAt(i,color.set(hex));}
 function update(state:RestorationState|undefined,player:{x:number;z:number},confirmed:(x:number,z:number)=>boolean,enabled:boolean,dt:number,confirmedMachine?:{x:number;y:number;z:number}|null){
  root.visible=enabled&&!!state;if(!root.visible||!state)return;visibleSites=0;
  for(let i=0;i<sites.length;i++){const view=sites[i]!,p=plan.sites[i]!,s=state.sites[i]!,visible=Math.hypot(player.x-p.x,player.z-p.z)<90&&p.cells.every(c=>confirmed(c.x,c.z));view.group.visible=visible;if(!visible)continue;visibleSites++;
   if(state.tick!==lastTick||view.group.userData.revision!==state.revision){view.group.userData.revision=state.revision;for(let j=0;j<p.cells.length;j++){const c=s.cells[j]!,q=p.cells[j]!,wet=Math.min(1,c.waterMl/2000),healthy=c.health/100;
    set(view.dirt,j,{...q,y:q.y+.008},{x:.86,y:.016,z:.86},c.heat>360?'#9e7954':'#776e52');set(view.water,j,{...q,y:q.y+.022+c.waterMl/1_500_000},{x:.18+wet*.62,y:.014,z:.18+wet*.62},c.contaminant>4?'#9b9860':'#75bdbb');
    for(let n=0;n<3;n++){const height=.1+Math.min(1,c.biomass/24)*(.3+n*.13);set(view.plants,j*3+n,{x:q.x+(n-1)*.3,y:q.y+height/2+.025,z:q.z+.38},{x:.1+healthy*.12,y:height,z:.13},healthy>.65?'#9ac778':healthy>.3?'#839564':'#918260');}
    set(view.smoke,j,{...q,y:q.y+.65},{x:.15+Math.min(1,c.smoke/60)*.6,y:Math.min(.9,c.smoke/50),z:.15+Math.min(1,c.smoke/60)*.6},'#bdb7a3');set(view.scent,j,{...q,y:q.y+.075},{x:Math.min(.8,c.scent/80),y:Math.min(.8,c.scent/80),z:Math.min(.8,c.scent/80)},'#c7a9e3',true);
   }for(const m of [view.dirt,view.water,view.plants,view.smoke,view.scent]){m.instanceMatrix.needsUpdate=true;if(m.instanceColor)m.instanceColor.needsUpdate=true;}}
   const pollinator=habitatMotionPosition(p,s.pollinator);view.pollinator.position.set(pollinator.x,pollinator.y+.14,pollinator.z);view.dock.material=solid;
  }
  lastTick=state.tick;const machine=state.machine,point=confirmedMachine===undefined?restorationMachinePosition(state,plan):confirmedMachine,hash=machine?compileRestorationBody(machine.recipe).ref.recipeHash:'';
  if(hash!==bodyHash){body?.dispose();body=machine?createRestorationBodyView(machine.recipe):null;bodyHash=hash;if(body)root.add(body.root);}
  const bodyVisible=!!machine&&!!point&&Math.hypot(point.x-player.x,point.z-player.z)<90&&confirmed(point.x,point.z);
  if(body)body.update(point??{x:0,y:0,z:0},machine?.siteId??'',dt,bodyVisible);
  beam.visible=bodyVisible&&machine!.utility.phase==='active'&&!!machine!.utility.target;
  if(beam.visible&&body){const site=plan.sites.find(p=>p.id===machine!.siteId)!,id=machine!.utility.target!.targetId==='tank'?machine!.utility.target!.sourceId:machine!.utility.target!.targetId,target=site.cells.find(c=>c.id===id);if(target){const start=new THREE.Vector3(...[body.plan.sockets.emitter.x,body.plan.sockets.emitter.y,body.plan.sockets.emitter.z] as [number,number,number]);body.root.localToWorld(start);const values=beamGeometry.getAttribute('position') as THREE.BufferAttribute;values.setXYZ(0,start.x,start.y,start.z);values.setXYZ(1,target.x,target.y+.05,target.z);values.needsUpdate=true;}else beam.visible=false;}
 }
 return {root,update,get stats(){return {sites:3,visibleSites,cells:18,maxFieldInstances:126,bodyShapes:body?.plan.budget.shapes??0,bodyVisible:body?.root.visible??false};},dispose(){body?.dispose();for(const v of sites)for(const m of [v.dirt,v.water,v.plants,v.smoke,v.scent])m.dispose();for(const g of [box,cylinder,orb,ring,beamGeometry])g.dispose();for(const m of [solid,waterMaterial,airMaterial,scentMaterial,beamMaterial])m.dispose();root.removeFromParent();}};
}

export const RESTORATION_VIEW_ENGINE=Object.freeze({kind:'axiom-restoration-view',create:createRestorationView,body:createRestorationBodyView});
