import type {HabitatFields} from './habitat-fields.ts';
export interface HabitatPoint {x:number;y:number;z:number}
export interface HabitatCellDescriptor extends HabitatPoint {id:string}
export interface HabitatEdgeDescriptor {id:string;a:string;b:string;path:readonly HabitatPoint[]}
export interface HabitatSiteDescriptor extends HabitatPoint {id:string;label:string;dockCellId:string;cells:readonly HabitatCellDescriptor[];edges:readonly HabitatEdgeDescriptor[]}
export interface RestorationTuning {waterConductance:number;airConductance:number;growthIntervalTicks:number;machineSpeedPercent:number;scentWeight:number}
export const RESTORATION_DEFAULTS:Readonly<RestorationTuning>=Object.freeze({waterConductance:20,airConductance:6,growthIntervalTicks:12,machineSpeedPercent:100,scentWeight:4});
export const RESTORATION_TUNING_REGISTRY=Object.freeze([
 {key:'waterConductance',label:'Water transfer',min:1,max:60,default:20,step:1,unit:'ml/edge/tick',effect:'apply',consumer:'stepHabitatFields',description:'Caps simultaneous conservative surface-water transfer.'},
 {key:'airConductance',label:'Heat, smoke and scent transfer',min:1,max:20,default:6,step:1,unit:'units/edge/tick',effect:'apply',consumer:'stepHabitatFields',description:'Caps local air-field diffusion; never creates or destroys mass.'},
 {key:'growthIntervalTicks',label:'Vegetation growth interval',min:4,max:40,default:12,step:1,unit:'quarter-second ticks',effect:'apply',consumer:'stepRestoration',description:'Viable vegetation consumes two ml water and one nutrient per biomass unit.'},
 {key:'machineSpeedPercent',label:'Automaton travel speed',min:50,max:150,default:100,step:1,unit:'percent of body speed',effect:'apply',consumer:'advanceHabitatMotion',description:'Changes finite route walking, including recall; swept actor checks still apply.'},
 {key:'scentWeight',label:'Pollinator scent preference',min:1,max:8,default:4,step:1,unit:'score per scent unit',effect:'apply',consumer:'chooseHabitatScentTarget',description:'Relative scent weight against route distance controls actual stable pollinator target selection.'},
] as const);
export const RESTORATION_RULES=Object.freeze({version:1,step:.25,maxDelta:1,maxSites:3,maxCells:6,maxRecords:24,cellCapacityMl:2000,waterPerGrowth:2,nutrientPerGrowth:1,healthyWaterMl:80,healthyContaminant:4,healthyHeat:360,healthySmoke:15,completionHealth:70,completionTicks:16,maxTicks:10_000_000,serviceRange:3.5});
export interface HabitatCellPlan extends HabitatCellDescriptor {initial:HabitatFields;initialNutrient:number;initialBiomass:number;initialHealth:number}
export interface HabitatSitePlan extends HabitatSiteDescriptor {cells:readonly HabitatCellPlan[];initialCharge:number;initialFilter:number;initialScent:number;wasteCapacity:number}
export interface RestorationPlan {version:1;seed:number;id:string;sites:readonly HabitatSitePlan[];totals:{waterMl:number;contaminant:number;energy:number;smoke:number;scent:number;organic:number;filter:number}}
export const restorationHash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return(h>>>0).toString(16).padStart(8,'0');};
export function restorationFreeze<T>(v:T):T {if(v&&typeof v==='object'&&!Object.isFrozen(v)){for(const child of Object.values(v))restorationFreeze(child);Object.freeze(v);}return v;}
export function restorationKeys(v:unknown,expected:readonly string[]):v is Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))return false;const proto=Object.getPrototypeOf(v),own=Reflect.ownKeys(v);return (proto===Object.prototype||proto===null)&&own.length===expected.length&&own.every(k=>typeof k==='string'&&expected.includes(k)&&Object.hasOwn(Object.getOwnPropertyDescriptor(v,k)!,'value'));}
export function restorationArray(v:unknown,min=0,max=1_000):v is any[]{try{if(!Array.isArray(v)||Object.getPrototypeOf(v)!==Array.prototype||v.length<min||v.length>max)return false;const own=Reflect.ownKeys(v);return own.length===v.length+1&&own.every(k=>typeof k==='string'&&(k==='length'||/^(0|[1-9][0-9]*)$/.test(k)&&Number(k)<v.length)&&Object.hasOwn(Object.getOwnPropertyDescriptor(v,k)!,'value'));}catch{return false;}}
export const restorationInteger=(v:unknown,max=1_000_000_000):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0&&v<=max;
export const restorationId=(v:unknown):v is string=>typeof v==='string'&&/^[a-z][a-z0-9-]{0,63}$/.test(v);
const point=(v:unknown)=>restorationKeys(v,['x','y','z'])&&Object.values(v).every(n=>typeof n==='number'&&Number.isFinite(n)&&Math.abs(n)<100_000);
export function validRestorationTuning(v:unknown):v is RestorationTuning{return restorationKeys(v,RESTORATION_TUNING_REGISTRY.map(r=>r.key))&&RESTORATION_TUNING_REGISTRY.every(r=>restorationInteger(v[r.key],r.max)&&Number(v[r.key])>=r.min);}
export function validHabitatSiteDescriptors(v:unknown):v is readonly HabitatSiteDescriptor[] {try{
 if(!restorationArray(v,3,3))return false;const ids=new Set<string>();for(const s of v){if(!restorationKeys(s,['id','label','x','y','z','dockCellId','cells','edges'])||!restorationId(s.id)||ids.has(s.id)||typeof s.label!=='string'||s.label.length<1||s.label.length>100||!point({x:s.x,y:s.y,z:s.z})||!restorationArray(s.cells,3,6)||!restorationArray(s.edges,s.cells.length-1,12))return false;ids.add(s.id);const cells=new Map<string,HabitatCellDescriptor>();for(const c of s.cells){if(!restorationKeys(c,['id','x','y','z'])||!restorationId(c.id)||ids.has(c.id)||!point({x:c.x,y:c.y,z:c.z})||Math.hypot(Number(c.x)-Number(s.x),Number(c.z)-Number(s.z))>20)return false;ids.add(c.id);cells.set(c.id,c as unknown as HabitatCellDescriptor);}if(!cells.has(String(s.dockCellId)))return false;const pairs=new Set<string>();for(const e of s.edges){if(!restorationKeys(e,['id','a','b','path'])||!restorationId(e.id)||ids.has(e.id)||e.a===e.b||!cells.has(String(e.a))||!cells.has(String(e.b))||!restorationArray(e.path,2,16)||!e.path.every(point))return false;ids.add(e.id);const pair=[String(e.a),String(e.b)].sort().join(':');if(pairs.has(pair))return false;pairs.add(pair);const a=cells.get(String(e.a))!,b=cells.get(String(e.b))!,first=e.path[0]!,last=e.path.at(-1)!;if(first.x!==a.x||first.y!==a.y||first.z!==a.z||last.x!==b.x||last.y!==b.y||last.z!==b.z)return false;let length=0;for(let i=1;i<e.path.length;i++)length+=Math.hypot(e.path[i]!.x-e.path[i-1]!.x,e.path[i]!.y-e.path[i-1]!.y,e.path[i]!.z-e.path[i-1]!.z);if(length<=0||length>30)return false;}
 const seen=new Set([String(s.dockCellId)]);for(let j=0;j<s.cells.length;j++)for(const e of s.edges)if(seen.has(String(e.a))||seen.has(String(e.b))){seen.add(String(e.a));seen.add(String(e.b));}if(seen.size!==s.cells.length)return false;}return true;
 }catch{return false;}}
const plans=new Map<string,RestorationPlan>();
/** Geometry is certified by the authoritative world owner. No runtime terrain query or relocation. */
export function restorationPlan(seed:number,descriptors:readonly HabitatSiteDescriptor[]):RestorationPlan {if(!restorationInteger(seed,0xffffffff)||!validHabitatSiteDescriptors(descriptors))throw new Error('Invalid bounded habitat plan');const signature=JSON.stringify({seed,descriptors}),key=restorationHash(signature),cached=plans.get(key);if(cached&&JSON.stringify(cached.sites.map(s=>({id:s.id,label:s.label,x:s.x,y:s.y,z:s.z,dockCellId:s.dockCellId,cells:s.cells.map(({id,x,y,z})=>({id,x,y,z})),edges:s.edges})))===JSON.stringify(descriptors)&&cached.seed===seed)return cached;
 const sites=descriptors.map((s,siteIndex)=>{const variation=parseInt(restorationHash(`${seed}/${s.id}`),16)%7;return {...structuredClone(s),initialCharge:2400+variation*80,initialFilter:180+variation*10,initialScent:500+variation*20,wasteCapacity:600,cells:s.cells.map((c,i)=>({...c,initial:{waterMl:i===0?1500+variation*30:140+variation*10,contaminant:i===0?45+variation*3:10+siteIndex*3,heat:500+variation*20+siteIndex*220,smoke:35+variation*3,scent:0},initialNutrient:24+variation,initialBiomass:2,initialHealth:24+variation}))};});
 const totals=sites.reduce((t,s)=>{t.energy+=s.initialCharge;t.scent+=s.initialScent;t.filter+=s.initialFilter;for(const c of s.cells){t.waterMl+=c.initial.waterMl;t.contaminant+=c.initial.contaminant;t.energy+=c.initial.heat;t.smoke+=c.initial.smoke;t.scent+=c.initial.scent;t.organic+=c.initialNutrient+c.initialBiomass;}return t;},{waterMl:0,contaminant:0,energy:0,smoke:0,scent:0,organic:0,filter:0});const contentHash=restorationHash(JSON.stringify({version:1,seed,sites,totals,rules:RESTORATION_RULES,fields:'integer-snapshot-face-transfer-v1',motion:'full-footprint-polyline-v1'}));const result=restorationFreeze({version:1 as const,seed,id:`habitat-v1-${contentHash}`,sites,totals});plans.set(key,result);while(plans.size>4)plans.delete(plans.keys().next().value!);return result;}
