import {mountRestorationCare,type RestorationCareViewState} from './restoration-care-ui.ts';
import {createRestorationCareScenario} from './restoration-care-scenarios.ts';
import {applyRestorationCare,restorationCarePosition} from './restoration-care.ts';
import {advanceRestoration,restorationBalances} from './restoration.ts';
import {advanceTownLife} from './town-life.ts';
import {RESTORATION_DEFAULTS,RESTORATION_TUNING_REGISTRY,validRestorationTuning,restorationKeys,type RestorationTuning} from './restoration-plan.ts';
import {DEVELOPER_BUILD} from './developer-tools.ts';
export const RESTORATION_CARE_SCENARIOS=Object.freeze([{id:'unopened',label:'Unopened habitats · collection blocked'},{id:'restored',label:'Earn a restored source through real rig work'},{id:'delivered',label:'Earn restoration, collect and deliver to Greenlight'}] as const);
export interface RestorationCarePreset {format:'axiom-restoration-care-preset';version:1;scope:'disposable-model';source:string;seed:number;scenario:'unopened'|'restored'|'delivered';tuning:RestorationTuning}
const provenance=(v:unknown):v is string=>typeof v==='string'&&v.length>0&&v.length<=160&&/^[a-zA-Z0-9][a-zA-Z0-9._:/ -]*$/.test(v);
export function createRestorationCarePreset(seed:number,source:string):RestorationCarePreset{return parseRestorationCarePreset(JSON.stringify({format:'axiom-restoration-care-preset',version:1,scope:'disposable-model',source:provenance(source)?source:'source-unavailable',seed,scenario:'unopened',tuning:{...RESTORATION_DEFAULTS}}));}
export function parseRestorationCarePreset(raw:string):RestorationCarePreset{
 if(typeof raw!=='string'||raw.length>4096||new TextEncoder().encode(raw).length>4096)throw Error('Care preset exceeds 4 KB.');let v:unknown;try{v=JSON.parse(raw);}catch{throw Error('Enter a JSON care preset.');}
 // Reject repeated keys, including escaped spellings, before accepting the parsed object.
 const tokens=raw.match(/"(?:\\[\s\S]|[^"\\])*"|[{}\[\],:]|true|false|null|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/g)!;let index=0;
 function scan(){const token=tokens[index++];if(token==='{'){const keys=new Set<string>();while(tokens[index]!=='}'){const key=JSON.parse(tokens[index++]!);if(keys.has(key))throw Error('Duplicate care preset field.');keys.add(key);index++;scan();if(tokens[index]!==',')break;index++;}index++;}else if(token==='['){while(tokens[index]!==']'){scan();if(tokens[index]!==',')break;index++;}index++;}}scan();
 if(!restorationKeys(v,['format','version','scope','source','seed','scenario','tuning'])||v.format!=='axiom-restoration-care-preset'||v.version!==1||v.scope!=='disposable-model'||!provenance(v.source)||!Number.isSafeInteger(v.seed)||Number(v.seed)<0||Number(v.seed)>0xffffffff||!RESTORATION_CARE_SCENARIOS.some(s=>s.id===v.scenario)||!validRestorationTuning(v.tuning))throw Error('Unsupported care preset fields, version, scenario or bounded settings.');return structuredClone(v) as unknown as RestorationCarePreset;
}
export function serializeRestorationCarePreset(p:RestorationCarePreset){return JSON.stringify(parseRestorationCarePreset(JSON.stringify(p)),null,2);}
/** Disposable memory-only owner. It has no campaign getter, persistence writer, room or background timer. */
export function mountRestorationCareLab(panel:HTMLElement,options:{seed:number;source?:string;onClose:()=>void}){
 let disposed=false,generation=0,elapsed=0,actions:unknown[]=[],truncated=false;const defaults=createRestorationCarePreset(options.seed,options.source??'source-unavailable');let applied=structuredClone(defaults),initialPreset=structuredClone(defaults),fixture=createRestorationCareScenario(applied.seed,applied.scenario,applied.tuning);
 let state:RestorationCareViewState={seed:applied.seed,zone:'valley',player:fixture.player,restoration:fixture.restoration,townLife:fixture.life,...(fixture.care?{restorationCare:fixture.care}:{})};
 panel.innerHTML=`<button id="rcl-close" class="close" aria-label="Close care lab">×</button><span class="eyebrow">Developer · disposable habitat care model</span><h2>Restoration to care rehearsal</h2><p>Memory-only, solo-only model. No campaign, ordinary save slot, room, inventory grant or offline catch-up. Prepared scenarios earn restoration using real paid rig commands and achieved ticks; they never forge a restored flag. The test operator can be explicitly placed at a source or clinic to exercise transfers. This does not simulate or certify player travel; NPC movement remains the real town model.</p><label for="rcl-seed">Seed · uint32, reset-time</label><input id="rcl-seed" type="number" min="0" max="4294967295" step="1"><label for="rcl-scenario">Repeatable scenario · reset-time</label><select id="rcl-scenario">${RESTORATION_CARE_SCENARIOS.map(s=>`<option value="${s.id}">${s.label}</option>`).join('')}</select><h3>Supported habitat settings</h3>${RESTORATION_TUNING_REGISTRY.map(f=>`<label for="rcl-${f.key}">${f.label} · ${f.unit}</label><input id="rcl-${f.key}" type="number" min="${f.min}" max="${f.max}" step="${f.step}"><small>${f.description} Consumer: ${f.consumer}; applied by explicit Apply or reset.</small><button id="rcl-default-${f.key}" type="button">Stage default ${f.label.toLowerCase()}</button>`).join('')}<div class="row"><button id="rcl-apply" type="button">Apply settings</button><button id="rcl-reset-draft" type="button">Apply setup & reset</button><button id="rcl-reset" type="button">Reset applied model</button><button id="rcl-discard" type="button">Discard edits</button><button id="rcl-defaults" type="button">Stage all defaults</button></div><p id="rcl-status" role="status"></p><label for="rcl-seconds">Explicit step · 1–60 whole seconds</label><input id="rcl-seconds" type="number" min="1" max="60" step="1" value="10"><button id="rcl-step" type="button">Step real models</button><p>Hard limit 1,200 manual seconds per reset. Preparation ticks are reported separately. Settings alter habitat fields, growth, rig speed and pollinator choices; care portion size, stock caps, costs and 1.5× recovery remain fixed.</p><label for="rcl-target">Explicit test operator location</label><select id="rcl-target"></select><button id="rcl-move" type="button">Place model operator at target</button><div id="rcl-board"></div><h3>Presets and evidence</h3><button id="rcl-preset" type="button">Export applied preset to text</button><button id="rcl-report" type="button">Export evidence to text</button><button id="rcl-import" type="button">Stage preset text</button><label for="rcl-text">JSON text fallback · preset import limit 4 KB</label><textarea id="rcl-text" rows="10"></textarea><label for="rcl-file">Stage preset file</label><input id="rcl-file" type="file" accept="application/json,.json">`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#rcl-'+id)!;const marker=q('status'),current=()=>!disposed&&panel.querySelector('#rcl-status')===marker;let board:ReturnType<typeof mountRestorationCare>;
 function record(a:unknown){if(actions.length<128)actions.push(structuredClone(a));else truncated=true;}
 function status(message='Paused; only explicit Step advances the model.'){if(current())marker.textContent=`Applied seed ${applied.seed} · ${applied.scenario} · ${elapsed}/1200 manual seconds · ${fixture.preparationTicks} earned preparation ticks. ${message}`;}
 function fill(p:RestorationCarePreset){q<HTMLInputElement>('seed').value=String(p.seed);q<HTMLSelectElement>('scenario').value=p.scenario;for(const f of RESTORATION_TUNING_REGISTRY)q<HTMLInputElement>(f.key).value=String(p.tuning[f.key]);}
 function draft(){const n=(id:string)=>q<HTMLInputElement>(id).value.trim()?Number(q<HTMLInputElement>(id).value):NaN;return parseRestorationCarePreset(JSON.stringify({...applied,seed:n('seed'),scenario:q<HTMLSelectElement>('scenario').value,tuning:Object.fromEntries(RESTORATION_TUNING_REGISTRY.map(f=>[f.key,n(f.key)]))}));}
 function mount(){board?.dispose();board=mountRestorationCare(q('board'),{getState:()=>state,getPlan:()=>fixture.plan,disposable:true,onClose:()=>{dispose();options.onClose();},send:command=>{if(!current())return;const result=applyRestorationCare(state.restorationCare,state.restoration!,fixture.plan,state.townLife!,state,command);record({kind:'command',command,player:state.player,accepted:!!result});if(result)state={...state,restorationCare:result.care,restoration:result.restoration,townLife:result.life};status(result?.message??'Real transfer rules rejected this request.');}});q('target').innerHTML=fixture.plan.sites.map(s=>`<option value="${s.id}">${s.label} dock</option>`).join('')+'<option value="apothecary">Greenlight care station</option>';q<HTMLSelectElement>('target').value=fixture.plan.sites[0]!.id;}
 function reset(p:RestorationCarePreset){const next=createRestorationCareScenario(p.seed,p.scenario,p.tuning);fixture=next;applied=structuredClone(p);initialPreset=structuredClone(p);state={seed:p.seed,zone:'valley',player:fixture.player,restoration:fixture.restoration,townLife:fixture.life,...(fixture.care?{restorationCare:fixture.care}:{})};elapsed=0;actions=[];truncated=false;generation++;fill(applied);mount();status('Reset replaced only the disposable model.');}
 function guarded(fn:()=>void){return ()=>{if(current()){generation++;try{fn();}catch(e){status(e instanceof Error?e.message:String(e));}}};}
 function staged(){if(current()){generation++;status('Edits staged. Apply settings or Apply setup & reset to consume them.');}}
 function step(seconds:number){if(!current())return;if(!Number.isSafeInteger(seconds)||seconds<1||seconds>60)throw RangeError('Step requires 1–60 whole seconds.');generation++;const dt=Math.min(seconds,1200-elapsed);for(let remaining=dt;remaining>0;remaining-=.25)state={...state,restoration:advanceRestoration(state.restoration!,fixture.plan,.25,{player:state.player},applied.tuning),townLife:advanceTownLife(state.townLife!,.25)};elapsed+=dt;record({kind:'advance',seconds:dt});board.refresh();status(dt?'Real habitat and town kernels advanced.':'Time limit reached; reset to repeat.');}
 for(const f of RESTORATION_TUNING_REGISTRY){q<HTMLInputElement>(f.key).oninput=staged;q('default-'+f.key).onclick=guarded(()=>{q<HTMLInputElement>(f.key).value=String(f.default);staged();});}q<HTMLInputElement>('seed').oninput=staged;q<HTMLSelectElement>('scenario').onchange=staged;
 q('apply').onclick=guarded(()=>{const tuning=draft().tuning;applied={...applied,tuning};record({kind:'tuning',tuning});status('Habitat settings applied. Seed and scenario still require explicit reset.');});q('reset-draft').onclick=guarded(()=>reset(draft()));q('reset').onclick=guarded(()=>reset(applied));q('discard').onclick=guarded(()=>{fill(applied);status('Unapplied edits discarded.');});q('defaults').onclick=guarded(()=>{fill(defaults);staged();});q('step').onclick=guarded(()=>step(Number(q<HTMLInputElement>('seconds').value)));
 q('move').onclick=guarded(()=>{const targetId=q<HTMLSelectElement>('target').value,p=restorationCarePosition(fixture.plan,{kind:targetId==='apothecary'?'deliver':'collect',targetId});if(!p)throw Error('Choose a supported model target.');state={...state,player:{...p,hp:100}};record({kind:'model-operator-placement',targetId,position:p});board.refresh();status('Only the disposable operator moved. No NPC relocation or physical journey is claimed.');});
 function report(){return {format:'axiom-restoration-care-evidence',version:1,scope:'disposable-model',build:DEVELOPER_BUILD,source:defaults.source,visualReview:'not-reviewed',initialPreset,initialInventory:fixture.initialInventory,applied,intended:{seed:q<HTMLInputElement>('seed').value,scenario:q<HTMLSelectElement>('scenario').value,tuning:Object.fromEntries(RESTORATION_TUNING_REGISTRY.map(f=>[f.key,q<HTMLInputElement>(f.key).value]))},elapsed,preparationTicks:fixture.preparationTicks,preparationActions:fixture.preparationActions,preparationRemainingInventory:fixture.inventory,actual:{player:state.player,restoration:state.restoration,care:state.restorationCare??null,life:state.townLife},balances:restorationBalances(state.restoration!,fixture.plan),actions,actionsTruncated:truncated};}
 q('preset').onclick=guarded(()=>{q<HTMLTextAreaElement>('text').value=serializeRestorationCarePreset(applied);status('Applied preset prepared in text.');});q('report').onclick=guarded(()=>{q<HTMLTextAreaElement>('text').value=JSON.stringify(report(),null,2);status('Evidence prepared in text. Copy to retain it.');});
 function stage(raw:string){fill(parseRestorationCarePreset(raw));staged();}q('import').onclick=guarded(()=>stage(q<HTMLTextAreaElement>('text').value));q<HTMLTextAreaElement>('text').oninput=()=>{generation++;};q<HTMLInputElement>('file').onchange=async()=>{if(!current())return;const ticket=++generation,file=q<HTMLInputElement>('file').files?.[0];if(!file)return;try{if(file.size>4096)throw Error('Care preset exceeds 4 KB.');const raw=await file.text();if(current()&&ticket===generation)stage(raw);}catch(e){if(current()&&ticket===generation)status(String(e));}};
 function dispose(){if(disposed)return;disposed=true;generation++;board?.dispose();}q('close').onclick=guarded(()=>{dispose();options.onClose();});fill(applied);mount();status();return {dispose,step,report,getPreset:()=>structuredClone(applied),getState:()=>state};
}
