import {SAVE_DIFF_RAW_MAX_BYTES,captureSaveSnapshot,parseSaveSnapshot,exportSaveSnapshot,diffSaveSnapshots,type SaveSnapshot,type SaveDifference} from './save-diff.ts';
export interface SaveDiffOptions {onClose:()=>void;capture?:()=>unknown;download?:(name:string,text:string)=>void}
/** Explicit input/capture only; does not enumerate storage or call parseSave/load/save. */
export function mountSaveDiff(panel:HTMLElement,options:SaveDiffOptions){
 panel.innerHTML=`<button id="sd-close" class="close" aria-label="Close save differences">×</button><span class="eyebrow">AXIOM · read-only save inspection v1</span><h2>Save differences</h2><p>Compare two explicitly supplied schema-6 save files, sanitized inspection snapshots, or captures of the current world. This never loads or changes a campaign. Raw imported text stays in this panel; exports contain only allowlisted game records.</p><p>Coverage: seed and exact generation domains; inventory; Mossbank water/commissions; causal materials, needs and jobs; town-life resources, needs and revisions; town-director episode causes and outcomes. Restoration and other regional systems, free-form events and room/session credentials are excluded.</p>${(['before','after'] as const).map(side=>`<h3>${side==='before'?'Before':'After'}</h3><label for="sd-${side}-text">${side} JSON (up to 2 MiB raw / 256 KiB inspection)</label><textarea id="sd-${side}-text" rows="5" spellcheck="false"></textarea><button id="sd-${side}-stage" type="button">Use ${side} text</button><button id="sd-${side}-capture" type="button">Capture current as ${side}</button><label for="sd-${side}-file">Choose ${side} file</label><input id="sd-${side}-file" type="file" accept="application/json,.json"><p id="sd-${side}-status"></p>`).join('')}<div class="row"><button id="sd-compare" type="button">Compare selected snapshots</button><button id="sd-clear" type="button">Discard both</button><button id="sd-export" type="button">Export difference report</button></div><p id="sd-status" role="status" aria-live="polite"></p><pre id="sd-summary"></pre><details><summary>Exact changed records and generation identities</summary><pre id="sd-report"></pre></details><label for="sd-output">Sanitized report text fallback</label><textarea id="sd-output" rows="8" readonly></textarea>`;
 const get=<T extends HTMLElement>(id:string)=>panel.querySelector<T>(`#${id}`)!;const sentinel=get('sd-report'),status=get('sd-status');const selected:Partial<Record<'before'|'after',SaveSnapshot>>={};const tickets={before:0,after:0};let disposed=false,report:SaveDifference|undefined;
 const current=()=>!disposed&&panel.querySelector('#sd-report')===sentinel;
 function invalidate(){report=undefined;get('sd-summary').textContent='';get('sd-report').textContent='';get<HTMLTextAreaElement>('sd-output').value='';status.textContent='Inputs changed. Compare selected snapshots to refresh the report.';}
 function accepted(side:'before'|'after',snapshot:SaveSnapshot){tickets[side]++;selected[side]=snapshot;get<HTMLTextAreaElement>(`sd-${side}-text`).value=exportSaveSnapshot(snapshot);get(`sd-${side}-status`).textContent=`Selected seed ${snapshot.state.seed}, generation ${snapshot.state.generation}, revision ${snapshot.state.revision}. Sanitized projection only.`;invalidate();}
 function error(side:'before'|'after',e:unknown){get(`sd-${side}-status`).textContent=e instanceof Error?e.message:'Could not inspect snapshot';}
 for(const side of ['before','after'] as const){const text=get<HTMLTextAreaElement>(`sd-${side}-text`),capture=get<HTMLButtonElement>(`sd-${side}-capture`);capture.disabled=!options.capture;
  text.oninput=()=>{if(!current())return;tickets[side]++;delete selected[side];invalidate();get(`sd-${side}-status`).textContent='Text edited. Use this text explicitly before comparison.';};
  get(`sd-${side}-stage`).onclick=()=>{if(!current())return;tickets[side]++;delete selected[side];invalidate();try{accepted(side,parseSaveSnapshot(text.value));}catch(e){error(side,e);}};
  capture.onclick=()=>{if(!current()||!options.capture)return;tickets[side]++;delete selected[side];invalidate();try{accepted(side,captureSaveSnapshot(options.capture()));}catch(e){error(side,e);}};
  get<HTMLInputElement>(`sd-${side}-file`).onchange=async()=>{if(!current())return;const request=++tickets[side],file=get<HTMLInputElement>(`sd-${side}-file`).files?.[0];if(!file)return;delete selected[side];invalidate();get(`sd-${side}-status`).textContent='Reading explicitly selected file…';try{if(file.size>SAVE_DIFF_RAW_MAX_BYTES)throw new Error('Raw snapshot exceeds 2 MiB');const content=await file.text();if(!current()||request!==tickets[side])return;accepted(side,parseSaveSnapshot(content));}catch(e){if(current()&&request===tickets[side])error(side,e);}};
 }
 get('sd-compare').onclick=()=>{if(!current())return;if(!selected.before||!selected.after){status.textContent='Select both before and after snapshots first.';return;}try{report=diffSaveSnapshots(selected.before,selected.after);get('sd-summary').textContent=`${report.changes.length} inspected records changed. ${report.comparable?'Same world identity.':'Different world identities; no gameplay attribution.'}\n\n${report.explanations.join('\n')}\n\n${report.limits.join('\n')}`;get('sd-report').textContent=JSON.stringify(report,null,2);status.textContent='Read-only comparison ready. No campaign was loaded or changed.';}catch(e){report=undefined;status.textContent=e instanceof Error?e.message:'Could not compare';}};
 get('sd-export').onclick=()=>{if(!current())return;if(!report){status.textContent='Compare both snapshots before exporting.';return;}const text=JSON.stringify(report,null,2);get<HTMLTextAreaElement>('sd-output').value=text;if(!options.download){status.textContent='Sanitized difference report ready in the text fallback.';return;}try{options.download('axiom-save-difference-v1.json',text);status.textContent='Sanitized report exported; text fallback retained.';}catch{status.textContent='Download unavailable. Copy the sanitized report from the text fallback.';}};
 function clear(){for(const side of ['before','after'] as const){tickets[side]++;delete selected[side];get<HTMLTextAreaElement>(`sd-${side}-text`).value='';get(`sd-${side}-status`).textContent='';get<HTMLInputElement>(`sd-${side}-file`).value='';}invalidate();status.textContent='Both snapshots discarded.';}
 get('sd-clear').onclick=()=>{if(current())clear();};
 function dispose(){if(disposed)return;if(current())clear();disposed=true;tickets.before++;tickets.after++;delete selected.before;delete selected.after;report=undefined;}
 get('sd-close').onclick=()=>{if(!current())return;clear();dispose();options.onClose();};
 return {dispose,getReport:()=>report};
}
