import {waterRequestSystemCheck} from './water-requests-fixtures.ts';
import {commonsTradeSystemCheck} from './commons-trade-fixtures.ts';
import {guardSystemChecks} from './guard-fixtures.ts';
import {caveSettlementWaterBalance} from './cave-supply.ts';
import {ecologyPlan,ecologyStage,ecologyWaterBalance,type EcologyCommand} from './ecology.ts';
import {createConnectedState,enableEconomy,enableEcology,applyAction,worldObjects,worldEndpoints,validateSave,serializeSave,parseSave,causalContext} from './world.ts';
import {causalPlan} from './causal.ts';import {createEncounters,advanceEncounters,ENEMY_RULES} from './encounters.ts';import {naturalCave} from './natural-cave.ts';import {createCaveWater,applyCaveWaterCommand,advanceCaveWater,caveRouteOpen,caveWaterBalance,validCaveWater} from './cave-water.ts';
export interface SystemCheck {name:string;pass:boolean;actual:string;expected:string}
/** Disposable production-reducer checks. These are neither rendered frames nor device benchmarks. */
export function systemsChecks(seed:number):SystemCheck[]{const checks:SystemCheck[]=[];const run=(name:string,expected:string,fn:()=>{pass:boolean;actual:string})=>{try{checks.push({name,expected,...fn()});}catch(error){checks.push({name,expected,pass:false,actual:error instanceof Error?error.message:String(error)});}};
 run('Quadruped warning, dodge and single contact','Windup deals zero damage; locked strike contacts once; side step avoids contact',()=>{const seeds=[{id:'probe',zone:'valley',x:0,z:0}],ctx={zone:'valley',players:[{id:'probe-player',x:0,y:0,z:2,hp:100}],obstacles:[],height:()=>0,defeated:[]};const start=createEncounters(seeds),windup=advanceEncounters(start,.5,ctx),contact=advanceEncounters(windup.state,.5,ctx),dodge=advanceEncounters(windup.state,.5,{...ctx,players:[{id:'probe-player',x:3,y:0,z:0,hp:100}]});const hits=contact.events.filter(e=>e.type==='damage').length,misses=dodge.events.filter(e=>e.type==='damage').length;return {pass:windup.events.every(e=>e.type!=='damage')&&hits===1&&misses===0,actual:`${windup.state.enemies[0]!.phase}; ${hits} contact; ${misses} contacts after dodge; ${ENEMY_RULES.prepare}s warning`};});
 for(const [device,command]of [['valve','repair-valve'],['pump','repair-pump'],['drain','clear-drain']] as const)run('Cave route by '+device,'A paid repair opens the actual flood-access predicate with conserved water and valid state',()=>{const plan=naturalCave(seed),inventory={scrap:2,core:1,water:0};const repaired=applyCaveWaterCommand(createCaveWater(seed),{inventory,player:plan.anchors[device],zone:'cave',hp:100},{type:command});let water=repaired.state,steps=0;while(!caveRouteOpen(water)&&steps<1200){water=advanceCaveWater(water,.25);steps++;}const error=Math.abs(caveWaterBalance(water));return {pass:caveRouteOpen(water)&&validCaveWater(water,seed)&&error<1e-6&&repaired.inventory.scrap<inventory.scrap,actual:`${(steps*.25).toFixed(2)} simulation seconds; error ${error.toExponential(2)} m³; route ${caveRouteOpen(water)?'open':'blocked'}`};});
 run('Water-supported manufacture and exact save ledger','Real carriers and caretaker work make one paid kit; no duplicate output; validated save restores it',()=>{let s=enableEconomy(createConnectedState(seed));for(const o of worldObjects(s)){if(['scrap','core','water'].includes(o.kind)){s=applyAction(s,{type:'move',x:o.x,z:o.z});s=applyAction(s,{type:'collect',id:o.id});}else if(o.kind==='enemy'){s=applyAction(s,{type:'move',x:o.x,z:o.z});s=applyAction(s,{type:'attack',id:o.id});}}const p=causalPlan(seed);s=applyAction(s,{type:'move',...p.source.position});s=applyAction(s,{type:'causal',command:{type:'repair-source'}});const place=p.workplaces.find(w=>s.economy!.workshops.some(c=>c.id===w.id))!;s=applyAction(s,{type:'move',...place.position});s=applyAction(s,{type:'causal',command:{type:'repair-workplace',workplaceId:place.id}});const before=s.inventory.scrap;s=applyAction(s,{type:'economy',command:{type:'commission-kit',workplaceId:place.id}});let steps=0;while(!s.economy!.workshops.some(w=>w.stock>0)&&steps<2400){s=applyAction(s,{type:'tick',dt:.25});steps++;}s=applyAction(s,{type:'economy',command:{type:'collect-kit',workplaceId:place.id}});const duplicate=applyAction(s,{type:'economy',command:{type:'collect-kit',workplaceId:place.id}});const saved=validateSave(s)?parseSave(serializeSave(s)):null;return {pass:before-s.inventory.scrap===2&&s.economy!.kits===1&&duplicate===s&&!!saved&&saved.economy!.kits===1,actual:`${steps*.25}s simulation; ${before-s.inventory.scrap} scrap spent; ${s.economy!.kits} carried kit; valid save ${!!saved}`};});
 run('Climate-grown material recipe and consumed suit repair','A canonical canister feeds real soil; climate grows a finite seed; harvest/crafting consumes goods and repairs actual damage once',()=>{let s=enableEcology(createConnectedState(seed));const water=worldObjects(s).find(o=>o.kind==='water')!,enemy=worldObjects(s).find(o=>o.kind==='enemy')!;s=applyAction(s,{type:'move',...water});s=applyAction(s,{type:'collect',id:water.id});s=applyAction(s,{type:'move',...enemy});s=applyAction(s,{type:'tick',dt:1});const damaged=s.player.hp,plot=ecologyPlan(seed).plots[0]!;s=applyAction(s,{type:'move',...plot.position});const act=(command:Omit<Extract<EcologyCommand,{type:'plant'}>,'expectedRevision'>|{type:'water'|'harvest';plotId:string}|{type:'craft-gel'|'use-gel'})=>{s=applyAction(s,{type:'ecology',command:{...command,expectedRevision:s.ecology!.revision} as EcologyCommand});};act({type:'plant',plotId:plot.id,species:plot.habitat==='sunny'?'sunleaf':'reedmoss'});act({type:'water',plotId:plot.id});let steps=0;while(ecologyStage(s.ecology!.plots[0]!.crop)!=='ripe'&&steps++<3600)s=applyAction(s,{type:'tick',dt:.25});act({type:'harvest',plotId:plot.id});act({type:'craft-gel'});act({type:'use-gel'});const roundtrip=validateSave(s)?parseSave(serializeSave(s)):null;return {pass:damaged<100&&s.player.hp===100&&s.ecology!.seeds===11&&s.ecology!.used===1&&s.ecology!.restoredHP===100-damaged&&s.inventory.water===0&&ecologyWaterBalance(s.ecology!)===0&&!!roundtrip,actual:`${steps*.25}s growth; 1 canister; ${s.ecology!.harvested} harvest; ${s.ecology!.used} gel consumed; ${(s.player.hp-damaged).toFixed(0)} suit integrity restored; water imbalance ${ecologyWaterBalance(s.ecology!)} mL`};});
 run('Cave outfall reaches actual households','Paid diversion meters new physical drainage; real carriers deliver it with conserved cross-unit receipts and no original quest payment',()=>{let s=createConnectedState(seed);for(const o of worldObjects(s)){if(['scrap','core','water'].includes(o.kind)||o.kind==='enemy'){s=applyAction(s,{type:'move',...o});s=applyAction(s,o.kind==='enemy'?{type:'attack',id:o.id}:{type:'collect',id:o.id});}}for(const job of s.causal!.jobs.filter(j=>j.kind==='water')){const home=causalPlan(seed).settlements.find(h=>h.id===job.targetId)!;s=applyAction(s,{type:'move',...home.position});s=applyAction(s,{type:'causal',command:{type:'accept',id:job.id}});}s=applyAction(s,{type:'move',...worldEndpoints(s).entrance});s=applyAction(s,{type:'enter-cave'});s=applyAction(s,{type:'move',...naturalCave(seed).anchors.drain});const scrap=s.inventory.scrap;s=applyAction(s,{type:'cave-supply',command:{type:'connect-outfall'}});for(let i=0;i<1600;i++)s=applyAction(s,{type:'tick',dt:.25});const received=s.causal!.caveReceipts?.received??0,delivered=s.causal!.caveReceipts?.households.reduce((n,h)=>n+h.litres,0)??0,error=Math.abs(caveSettlementWaterBalance(s.caveWater!,s.causal!)),roundtrip=validateSave(s)?parseSave(serializeSave(s)):null;return {pass:scrap-s.inventory.scrap===2&&received>0&&received<=200+1e-7&&delivered>0&&error<1e-4&&!s.waterRestored&&s.causal!.jobs.filter(j=>j.kind==='water').every(j=>j.status==='completed'&&j.playerEvidence.includes('cave'))&&!!roundtrip,actual:`2 scrap; ${received.toFixed(2)} L captured; ${delivered.toFixed(2)} L physically delivered; combined residual ${error.toExponential(2)} L; original quest unchanged`};});
 try{checks.push(commonsTradeSystemCheck());}catch(error){checks.push({name:'Household barter changes actual repair ownership · seed 1',expected:'Conserved transfer and real repair consequence',pass:false,actual:error instanceof Error?error.message:String(error)});}
 try{checks.push(waterRequestSystemCheck());}catch(error){checks.push({name:'Recurring relief follows real consumption · seed 1',expected:'Two conserved need cycles',pass:false,actual:error instanceof Error?error.message:String(error)});}
 checks.push(...guardSystemChecks());return checks;}
export function repeatedSystemsReport(seed:number,iterations=3){const repeats=Math.max(1,Math.min(5,Math.trunc(iterations)||1));return {version:6,seed,iterations:repeats,scope:'Disposable production models only. No active campaign changes, visual approval, online transport test or device performance claim.',runs:Array.from({length:repeats},(_,i)=>({iteration:i+1,checks:systemsChecks(seed)}))};}
