import type {WorkbenchGeometry,WorkbenchSnapshot} from './system-workbench-model.ts';
/** A plan view of actual generated vertices and authoritative actor poses, not a second simulation. */
export function drawWorkbenchMap(canvas:HTMLCanvasElement,geometry:WorkbenchGeometry,snapshot:WorkbenchSnapshot){
 const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.width,h=canvas.height,b=geometry.bounds,pad=34,scale=Math.min((w-pad*2)/(b.maxX-b.minX),(h-pad*2)/(b.maxZ-b.minZ)),ox=(w-(b.maxX-b.minX)*scale)/2,oz=(h-(b.maxZ-b.minZ)*scale)/2,X=(x:number)=>ox+(x-b.minX)*scale,Z=(z:number)=>oz+(z-b.minZ)*scale;
 ctx.fillStyle='#162c2c';ctx.fillRect(0,0,w,h);ctx.save();ctx.beginPath();ctx.rect(ox,oz,(b.maxX-b.minX)*scale,(b.maxZ-b.minZ)*scale);ctx.clip();
 const path=(points:{x:number;z:number}[],color:string,width:number)=>{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(X(p.x),Z(p.z)):ctx.moveTo(X(p.x),Z(p.z)));ctx.stroke();};
 for(const chunk of geometry.chunks){const t=chunk.terrain;for(let i=0;i<t.vertices.length;i+=3){ctx.fillStyle=`hsl(143 20% ${Math.max(20,Math.min(48,28+t.vertices[i+1]!*.4))}%)`;ctx.fillRect(X(t.vertices[i]!),Z(t.vertices[i+2]!),t.step*scale+1,t.step*scale+1);}for(const mesh of [...chunk.roads,...chunk.water]){ctx.fillStyle=mesh.color;for(let i=0;i<mesh.indices.length;i+=3){ctx.beginPath();for(let k=0;k<3;k++){const n=mesh.indices[i+k]!*3;k?ctx.lineTo(X(mesh.vertices[n]!),Z(mesh.vertices[n+2]!)):ctx.moveTo(X(mesh.vertices[n]!),Z(mesh.vertices[n+2]!));}ctx.closePath();ctx.fill();}}for(const feature of chunk.features){ctx.fillStyle=feature.kind==='tree'?'#244a37':'#b0ad91';ctx.beginPath();ctx.arc(X(feature.x),Z(feature.z),Math.max(1.2,scale*.5),0,Math.PI*2);ctx.fill();}for(const box of chunk.structures){ctx.fillStyle='#ad9672';ctx.fillRect(X(box.center.x-box.half.x),Z(box.center.z-box.half.z),box.half.x*2*scale,box.half.z*2*scale);}}
 for(const p of geometry.paths)path(p.points,p.color,3);
 for(const marker of geometry.markers){ctx.fillStyle='#e9d7a9';ctx.fillRect(X(marker.position.x)-4,Z(marker.position.z)-4,8,8);}
 snapshot.actors.forEach((a,i)=>{ctx.fillStyle=a.carrying>0?'#ffc269':'#b0ebe2';ctx.strokeStyle='#09201e';ctx.lineWidth=2;ctx.beginPath();ctx.arc(X(a.position.x),Z(a.position.z),6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.fillText(String(i+1),X(a.position.x)+9,Z(a.position.z)-7);});ctx.restore();
 ctx.fillStyle='#bed6cc';ctx.font='12px system-ui';ctx.fillText('N ↑',14,20);ctx.fillText(`x ${b.minX.toFixed(0)} → ${b.maxX.toFixed(0)} m · z ${b.minZ.toFixed(0)} → ${b.maxZ.toFixed(0)} m`,14,h-14);
}
