import {townSupplyBlockReason,townSupplyPosition,type TownSupplyCommand,type TownSupplyState,type TownSupplySource} from './town-supply.ts';
import {worldTownSupplySources} from './world.ts';
import type {TownLifeState} from './town-life.ts';
import {workshopConstructionQuote,type WorkshopConstructionState} from './workshop-construction.ts';
import {DEFAULT_WORKSHOP_DRAFT} from './workshop-authoring.ts';
export interface TownSupplyViewState {seed:number;generation?:1|2;regional?:{version:1};zone:string;player:{x:number;z:number;hp:number;y?:number;feetY?:number};inventory:{scrap:number;core:number;water:number};collected:string[];townLife?:TownLifeState;townSupply?:TownSupplyState;workshopConstruction?:WorkshopConstructionState}
export interface TownSupplyUIOptions {getState:()=>TownSupplyViewState;getSources?:()=>readonly TownSupplySource[];send:(command:TownSupplyCommand)=>void;ready?:(command:TownSupplyCommand)=>boolean;onClose:()=>void;visit?:()=>void;map?:(targetId:string)=>void;construction?:()=>void;disposable?:boolean;initialSourceId?:string;onSelection?:(id:string)=>void}
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
export function mountTownSupply(panel:HTMLElement,options:TownSupplyUIOptions){
 let disposed=false;const initial=options.getState(),sources=options.getSources?.()??(initial.generation===2&&initial.regional?worldTownSupplySources({generation:2,regional:initial.regional,seed:initial.seed}):[]);
 panel.innerHTML=`<button id="ts-close" class="close" aria-label="Close town supply">×</button><span class="eyebrow">Hearthmere · Second Life Salvage</span><h2>Bring materials to town</h2><p>Load finite valley scrap caches into a shared four-piece cargo satchel. Return to Second Life Salvage and deliver two pieces for 12 shared town materials, or unload one piece into ordinary inventory. Loading marks that cache collected immediately; it cannot also be picked up.</p><p>In shared worlds the host manages cargo. Ordinary nearby pickup remains available outside this board. ${options.disposable?'This disposable model explicitly places its test operator at sources and the workshop; no physical journey is claimed.':'Reach each selected cache and the workshop on foot. Solo menus pause time; close this board to let residents work and the delivery cooldown pass.'}</p><div class="row"><button id="ts-map" type="button">Map selected source</button><button id="ts-destination-map" type="button">Map delivery station</button><button id="ts-town" type="button">Visit Hearthmere</button><button id="ts-construction" type="button">Workshop construction</button></div><label for="ts-source-select">Finite valley source</label><select id="ts-source-select"></select><p id="ts-source"></p><p id="ts-location"></p><p id="ts-load-gate"></p><button id="ts-load" type="button">Load 1 scrap into cargo</button><h3>Workshop delivery</h3><p id="ts-destination"></p><p id="ts-cargo"></p><p id="ts-stock"></p><p id="ts-consequence"></p><p id="ts-deliver-gate"></p><button id="ts-deliver" type="button">Deliver 2 cargo → 12 town materials</button><p id="ts-unload-gate"></p><button id="ts-unload" type="button">Unload 1 cargo into inventory</button><p>Finite caches never respawn. When exhausted, ordinary inventory donations and residents’ existing salvage work remain the material supply routes. Delivery funds the existing shared town store; it does not reserve materials for your future build.</p><p id="ts-status" role="status"></p>`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#ts-'+id)!;const marker=q('status'),current=()=>!disposed&&panel.querySelector('#ts-status')===marker;
 q('source-select').innerHTML=sources.map(s=>`<option value="${esc(s.id)}">${esc(s.label??s.id)} · ${esc(s.id)}</option>`).join('');const nearest=()=>sources.filter(s=>!options.getState().collected.includes(s.id)).slice().sort((a,b)=>Math.hypot(a.x-options.getState().player.x,a.z-options.getState().player.z)-Math.hypot(b.x-options.getState().player.x,b.z-options.getState().player.z)||a.id.localeCompare(b.id))[0]?.id??'';
 q<HTMLSelectElement>('source-select').value=options.initialSourceId===undefined?sources.find(s=>!initial.collected.includes(s.id))?.id??'':sources.some(s=>s.id===options.initialSourceId&&!initial.collected.includes(s.id))?options.initialSourceId:nearest();
 let lastSelection:string|undefined;function resolveSelection(){const select=q<HTMLSelectElement>('source-select');if(!sources.some(s=>s.id===select.value&&!options.getState().collected.includes(s.id)))select.value=nearest();if(lastSelection!==select.value){lastSelection=select.value;options.onSelection?.(select.value);}}
 function command(kind:TownSupplyCommand['kind']):TownSupplyCommand{return {kind,targetId:kind==='load'?q<HTMLSelectElement>('source-select').value:'workshop',expectedRevision:options.getState().townSupply?.revision??0};}
 function reason(c:TownSupplyCommand){const state=options.getState();if(!state.townLife)return 'Visit Hearthmere to initialize the existing town economy.';if(options.ready&&!options.ready(c))return 'The host must reach the target on foot; wait for terrain and authority readiness.';return townSupplyBlockReason(state.townSupply,sources,state.townLife,state,c);}
 const location=(p:{x:number;y:number;z:number}|null)=>p?`x ${p.x.toFixed(1)}, y ${p.y.toFixed(1)}, z ${p.z.toFixed(1)} · ${Math.hypot(options.getState().player.x-p.x,options.getState().player.z-p.z).toFixed(1)} m away`:'No source location available.';
 function refresh(){if(!current())return;resolveSelection();const state=options.getState(),supply=state.townSupply,source=sources.find(s=>s.id===q<HTMLSelectElement>('source-select').value),remaining=sources.filter(s=>!state.collected.includes(s.id)).length;
 q('source').textContent=`${remaining}/${sources.length} finite sources remain. ${source?`${source.label??source.id}: ${state.collected.includes(source.id)?'already collected; unavailable':'one scrap available'}.`:'No source available; the finite source list is exhausted.'}`;q('location').textContent=location(townSupplyPosition(state.seed,sources,command('load')));q('destination').textContent='Second Life Salvage: '+location(townSupplyPosition(state.seed,sources,command('deliver')));
 q('cargo').textContent=`Shared cargo ${supply?.carried??0}/4 · ${supply?.sources.length??0} sources loaded · ${supply?.deliveries??0} deliveries · ${supply?.unloaded??0} pieces unloaded. Ordinary inventory: ${state.inventory.scrap} scrap.`;
 const materials=state.townLife?.resources.materials??0;q('stock').textContent=`Town materials ${materials}/600 · delivery cooldown ${(state.townLife?.cooldowns.donate??0).toFixed(1)} seconds. Each accepted delivery uses the normal two-scrap / twelve-material donation conversion.`;
 const built=state.workshopConstruction,cost=workshopConstructionQuote({...DEFAULT_WORKSHOP_DRAFT,seed:state.seed}).materials;q('consequence').textContent=built?(built.status==='complete'?`Completed workshop suit service costs 4 shared materials. ${Math.max(0,4-materials)} more currently needed.`:`Construction underway: ${built.work.toFixed(1)}/${built.workRequired} achieved work seconds. Extra deliveries fund the shared town economy; the original build is already paid.`):`Default workshop plan costs ${cost} shared materials; current shortage ${Math.max(0,cost-materials)}. Open construction to review the exact applied plan and commit separately.`;
 for(const kind of ['load','deliver','unload'] as const){const blocked=reason(command(kind));q(kind+'-gate').textContent=blocked??'Ready for an explicit authoritative transfer.';q<HTMLButtonElement>(kind).disabled=!!blocked;}
 }
 for(const kind of ['load','deliver','unload'] as const)q(kind).onclick=()=>{if(!current())return;const c=command(kind),blocked=reason(c);if(blocked){marker.textContent=blocked;return;}options.send(c);marker.textContent='Request sent. Authority rechecks source, cargo, location and revision.';refresh();};q<HTMLSelectElement>('source-select').onchange=()=>{if(current())refresh();};
 function dispose(){disposed=true;}q('close').onclick=()=>{if(current()){dispose();options.onClose();}};// Navigation can be rejected; its owner disposes only after an accepted transition.
 for(const [id,fn] of [['map',options.map?()=>options.map!(q<HTMLSelectElement>('source-select').value):undefined],['destination-map',options.map?()=>options.map!('workshop'):undefined],['town',options.visit],['construction',options.construction]] as const){q<HTMLButtonElement>(id).disabled=!fn;q(id).onclick=()=>{if(current()&&fn)fn();};}
 refresh();return {refresh,dispose};
}
