import {sameTownLayout,type TownLayout} from './starting-town.ts';
/** Read-only population watchdog. Measures real authority AND emitted matrices.
 * No saves, timers, networking, recovery mutations or second simulation. */
import type {TownLifeState} from './town-life.ts';
export const TOWN_ACTIVITY_CHECK={version:2,sampleSeconds:.25,windowSeconds:15,maxSamples:61,modelStallSeconds:3,jamSeconds:5,lagSeconds:3,lagMetres:3,lowRenderFps:20,movementMetresPerSecond:.2} as const;
export interface TownMatrixEvidence {index:number;x:number;z:number;matrixHash:number;instances:number;inFrustum:boolean;screenX:number;screenY:number;handOffsets?:readonly number[]}
export interface TownActivityInput {now:number;seed:number;life:TownLifeState;matrices:readonly TownMatrixEvidence[];physicsStep:number;renderFrames:number;renderTime:number;paused:boolean;expectedDrawn?:number;mode:'solo'|'online';camera:number[]}
export interface TownActivityResident {index:number;status:string;action:string|null;facility:string|null;remaining:number;completed:number;authorityX:number;authorityZ:number;distance:number;targetX:number|null;targetZ:number|null;modelChanged:boolean;matrixChanged:boolean;drawn:boolean;inFrustum:boolean;displayX:number;displayZ:number;matrixHash:number;lag:number;handOffsets?:readonly number[];blockedSeconds?:number;taskStage?:number;taskMoving?:boolean}
export interface TownActivitySample {segment:number;motionMeasured:boolean;activeCounters:{authoritySteps:number;physicsSteps:number;renderFrames:number};seconds:number;tick:number;physicsStep:number;renderFrames:number;renderTime:number;mode:'solo'|'online';camera:number[];counts:{traveling:number;acting:number;queued:number;idle:number;atHome:number;publicActing:number;expectedDrawn:number;drawn:number;inFrustum:number;frustumTravelers:number;frustumMoving:number;matrixChanged:number;modelChanged:number};residents:TownActivityResident[]}
export interface TownActivitySummary {duration:number;authoritySteps:number;physicsSteps:number;renderFrames:number;renderFps:number;authorityHz:number;physicsHz:number;travelersMin:number;travelersMax:number;frustumTravelersMin:number;frustumTravelersMax:number;frustumMovingMin:number|null;frustumMovingMax:number|null;residentsMoved:number;residentsWalking:number;residentsAnimated:number;bodyMatricesChanged:number;residentsWorking:number;residentsResting:number;residentsWaiting:number;blockedResidents:number[];quietAtStations:number[];cameraActive:number;modelProgressed:number;publicFacilities:number;maxHome:number;maxLag:number;modelStalled:number[];renderStalled:number[];routeStalled:number[];lagging:number[];warnings:string[]}
export interface TownActivityReport {townLayout?:TownLayout;kind:'axiom-town-activity';version:2;seed:number;source:string;status:'waiting'|'measuring'|'ready';callbackAgeSeconds:number;callbackGaps:number[];paused:boolean;opening:TownActivitySample[];recent:TownActivitySample[];openingSummary:TownActivitySummary|null;recentSummary:TownActivitySummary|null;scope:string}
const round=(n:number)=>Math.round(n*100000)/100000;
const signature=(r:TownLifeState['residents'][number])=>[r.status,r.action,r.facilityId,r.remaining,r.distance,r.completed,r.pathIndex,...Object.values(r.needs)].join('|');
const distance=(a:{displayX:number;displayZ:number},b:{displayX:number;displayZ:number})=>Math.hypot(a.displayX-b.displayX,a.displayZ-b.displayZ);
export function summarizeTownActivity(samples:readonly TownActivitySample[]):TownActivitySummary|null{
 const first=samples[0],last=samples.at(-1);if(!first||!last)return null;
 const window=(seconds:number)=>{let at=0;for(let n=0;n<samples.length;n++)if(samples[n]!.seconds<=last.seconds-seconds)at=n;return samples.slice(at);};const duration=last.seconds-first.seconds,modelTail=window(TOWN_ACTIVITY_CHECK.modelStallSeconds).filter(s=>s.segment===last.segment),modelFirst=modelTail[0]!,modelAge=last.seconds-modelFirst.seconds,moved=new Set<number>(),walking=new Set<number>(),working=new Set<number>(),quietAtStations:number[]=[],animated=new Set<number>(),progressed=new Set<number>(),facilities=new Set<string>(),modelStalled:number[]=[],renderStalled:number[]=[],routeStalled:number[]=[],lagging:number[]=[];
 for(const s of samples)for(const r of s.residents){if(r.matrixChanged)animated.add(r.index);if(r.modelChanged)progressed.add(r.index);if(r.facility&&!r.facility.startsWith('home-')&&r.status==='acting')facilities.add(r.facility);}
 for(const r of last.residents){const history=samples.map(s=>s.residents[r.index]!).filter(Boolean),a=history[0]!;let displayTravel=0;for(let n=1;n<history.length;n++)if(samples[n]!.segment===samples[n-1]!.segment&&history[n]!.drawn&&history[n-1]!.drawn)displayTravel+=distance(history[n-1]!,history[n]!);if(displayTravel>.5)moved.add(r.index);
  const tail=window(TOWN_ACTIVITY_CHECK.jamSeconds).filter(s=>s.segment===last.segment),rs=tail.map(s=>s.residents[r.index]!);if(rs.length<2)continue;const age=tail.at(-1)!.seconds-tail[0]!.seconds;
  if(age>=1&&rs.every(q=>q.drawn)&&(rs.some(q=>q.status==='traveling')||r.distance-rs[0]!.distance>.1)&&distance(rs[0]!,r)>=TOWN_ACTIVITY_CHECK.movementMetresPerSecond*age)walking.add(r.index);
  // Read actual emitted hand tips, with root translation/yaw removed. Breathing,
  // camera motion, and progress counters cannot satisfy the work-motion check.
  const sameTask=rs.every(q=>q.drawn&&q.status==='acting'&&q.action===r.action),taskProgress=r.remaining<rs[0]!.remaining||r.completed>rs[0]!.completed;
  if(age>=1&&sameTask&&taskProgress&&!['rest','recover'].includes(r.action??'')){
   let excursion=0;for(let a=0;a<rs.length;a++)for(let b=a+1;b<rs.length;b++){const x=rs[a]!.handOffsets,y=rs[b]!.handOffsets;if(!x||!y||x.length!==6||y.length!==6)continue;for(const k of [0,3])excursion=Math.max(excursion,Math.hypot(x[k]!-y[k]!,x[k+1]!-y[k+1]!,x[k+2]!-y[k+2]!));}
   if(excursion>=.18)working.add(r.index);
  }
  if(age>=4.75&&sameTask&&!walking.has(r.index)&&!working.has(r.index)&&!['rest','recover'].includes(r.action??''))quietAtStations.push(r.index);
  const lagTail=window(TOWN_ACTIVITY_CHECK.lagSeconds).filter(s=>s.segment===last.segment);
  if(last.seconds-lagTail[0]!.seconds>=TOWN_ACTIVITY_CHECK.lagSeconds-TOWN_ACTIVITY_CHECK.sampleSeconds&&lagTail.every(s=>{const p=s.residents[r.index]!;return p.drawn&&p.lag>TOWN_ACTIVITY_CHECK.lagMetres;}))lagging.push(r.index);
  if(modelAge>=2.75&&modelTail.every(s=>s.residents[r.index]!.status==='acting')&&r.remaining===modelFirst.residents[r.index]!.remaining&&r.completed===modelFirst.residents[r.index]!.completed&&(!r.taskMoving||(r.blockedSeconds??0)>=3))modelStalled.push(r.index);
  if(age>=4.75&&rs.every(q=>q.status==='traveling'||q.taskMoving)&&r.distance-rs[0]!.distance<.05)routeStalled.push(r.index);
  const actuallyVisible=rs.every(q=>q.drawn&&q.inFrustum);
  if(age>=4.75&&actuallyVisible&&rs.every(q=>q.matrixHash===rs[0]!.matrixHash)&&rs.some(q=>q.modelChanged))renderStalled.push(r.index);
  else if(age>=4.75&&rs.every(q=>q.drawn&&q.status==='traveling'&&q.lag>3)&&distance(rs[0]!,r)<.1&&r.distance-rs[0]!.distance>1)renderStalled.push(r.index);
 }
 const counts=samples.map(s=>s.counts),movingCounts=samples.filter(s=>s.motionMeasured).map(s=>s.counts.frustumMoving),warnings:string[]=[];
 if(modelAge>=2.75&&last.tick===modelFirst.tick)warnings.push(last.physicsStep>modelFirst.physicsStep?'Physics callbacks advance but town authority is stalled.':'Town authority has not advanced; inspect pause/worker or online snapshot delivery.');
 if(duration>=5&&counts.every(c=>c.atHome>=80&&c.traveling<10))warnings.push('Synchronized home cohort: too little street activity.');
 if(modelAge>=2.75&&last.renderFrames===modelFirst.renderFrames&&modelTail.some(s=>s.counts.expectedDrawn>0))warnings.push('Render-frame counter is stalled while activity samples continue.');
 if(modelAge>=2.75&&modelTail.every(s=>s.counts.expectedDrawn>0&&s.counts.drawn<s.counts.expectedDrawn))warnings.push('Confirmed resident bodies are missing from emitted matrices.');
 if(modelStalled.length)warnings.push(`${modelStalled.length} occupied activities have not progressed.`);
 if(routeStalled.length)warnings.push(`${routeStalled.length} reserved routes have not progressed.`);
 if(renderStalled.length)warnings.push(`${renderStalled.length} visible bodies are stalled despite model progress.`);
 if(lagging.length)warnings.push(`${lagging.length} drawn bodies remain more than ${TOWN_ACTIVITY_CHECK.lagMetres} m behind authority, including bodies that are still moving.`);
 const renderFrames=last.activeCounters.renderFrames-first.activeCounters.renderFrames,authoritySteps=last.activeCounters.authoritySteps-first.activeCounters.authoritySteps,physicsSteps=last.activeCounters.physicsSteps-first.activeCounters.physicsSteps;
 const renderFps=duration>0?renderFrames/duration:0,authorityHz=duration>0?authoritySteps/duration:0,physicsHz=duration>0?physicsSteps/duration:0;
 if(duration>=5&&counts.every(c=>c.expectedDrawn>0)&&renderFps<TOWN_ACTIVITY_CHECK.lowRenderFps)warnings.push(`Low render cadence: ${round(renderFps)} town frames/s. Matrix changes alone do not establish smooth visible movement.`);
 if(duration>=5&&authorityHz<1.6)warnings.push(`Town authority advances at ${round(authorityHz)} steps/s; expected about 2 during active play.`);
 if(duration>=5&&counts.every(c=>c.inFrustum>4&&c.frustumTravelers<2))warnings.push('This camera has fewer than two travelers; inspect its framing and the population distribution.');
 return {duration:round(duration),authoritySteps,physicsSteps,renderFrames,renderFps:round(renderFps),authorityHz:round(authorityHz),physicsHz:round(physicsHz),travelersMin:Math.min(...counts.map(c=>c.traveling)),travelersMax:Math.max(...counts.map(c=>c.traveling)),frustumTravelersMin:Math.min(...counts.map(c=>c.frustumTravelers)),frustumTravelersMax:Math.max(...counts.map(c=>c.frustumTravelers)),frustumMovingMin:movingCounts.length?Math.min(...movingCounts):null,frustumMovingMax:movingCounts.length?Math.max(...movingCounts):null,residentsMoved:moved.size,residentsWalking:walking.size,residentsAnimated:animated.size,bodyMatricesChanged:animated.size,residentsWorking:working.size,residentsResting:last.residents.filter(r=>r.drawn&&r.status==='acting'&&['rest','recover'].includes(r.action??'')).length,residentsWaiting:last.residents.filter(r=>r.drawn&&['queued','idle'].includes(r.status)).length,blockedResidents:last.residents.filter(r=>(r.blockedSeconds??0)>=3).map(r=>r.index),quietAtStations,cameraActive:last.residents.filter(r=>r.drawn&&r.inFrustum&&(walking.has(r.index)||working.has(r.index))).length,modelProgressed:progressed.size,publicFacilities:facilities.size,maxHome:Math.max(...counts.map(c=>c.atHome)),maxLag:round(Math.max(0,...samples.flatMap(s=>s.residents.filter(r=>r.drawn).map(r=>r.lag)))),modelStalled,renderStalled,routeStalled,lagging,warnings};
}
export class TownActivityMonitor {
 private layout:TownLayout|undefined;private seed=-1;private opening:TownActivitySample[]=[];private recent:TownActivitySample[]=[];private previousSignatures:string[]=[];private lastNow:number|null=null;private seconds=0;private lastSample=-Infinity;private source='not-recorded';private callbackGaps:number[]=[];private paused=true;private segment=0;private previousCounters:{tick:number;physicsStep:number;renderFrames:number}|undefined;private activeCounters={authoritySteps:0,physicsSteps:0,renderFrames:0};
 reset(){this.layout=undefined;this.seed=-1;this.opening=[];this.recent=[];this.previousSignatures=[];this.lastNow=null;this.seconds=0;this.lastSample=-Infinity;this.callbackGaps=[];this.paused=true;this.segment=0;this.previousCounters=undefined;this.activeCounters={authoritySteps:0,physicsSteps:0,renderFrames:0};}
 pause(now:number){if(Number.isFinite(now)){this.lastNow=now;this.paused=true;}}
 sample(input:TownActivityInput,source='not-recorded'){
  if(!Number.isFinite(input.now)||input.seed!==input.life.seed)return;
  if(input.seed!==this.seed||!sameTownLayout(input.life.townLayout,this.layout)||this.recent.at(-1)&&input.life.tick<this.recent.at(-1)!.tick){this.reset();this.seed=input.seed;this.layout=input.life.townLayout;this.source=/^[\w.-]{1,100}$/.test(source)?source:'not-recorded';}
  const resumed=this.paused,gap=this.lastNow===null?0:Math.max(0,(input.now-this.lastNow)/1000);if(gap>1&&!resumed&&!input.paused){this.callbackGaps.push(round(gap));if(this.callbackGaps.length>16)this.callbackGaps.shift();}
  const priorCounters=this.previousCounters;if(priorCounters&&!resumed&&!input.paused){this.activeCounters.authoritySteps+=Math.max(0,input.life.tick-priorCounters.tick);this.activeCounters.physicsSteps+=Math.max(0,input.physicsStep-priorCounters.physicsStep);this.activeCounters.renderFrames+=Math.max(0,input.renderFrames-priorCounters.renderFrames);}
  this.previousCounters={tick:input.life.tick,physicsStep:input.physicsStep,renderFrames:input.renderFrames};this.lastNow=input.now;this.paused=input.paused;if(input.paused)return;
  if(resumed){this.segment++;this.previousSignatures=[];}else this.seconds+=gap;
  if(!resumed&&this.seconds-this.lastSample<TOWN_ACTIVITY_CHECK.sampleSeconds-1e-8)return;this.lastSample=this.seconds;
  const lastRecorded=this.recent.at(-1),prev=lastRecorded?.segment===this.segment?lastRecorded:undefined,byIndex=new Map(input.matrices.map(m=>[m.index,m])),counts={traveling:0,acting:0,queued:0,idle:0,atHome:0,publicActing:0,expectedDrawn:input.expectedDrawn??input.matrices.length,drawn:input.matrices.length,inFrustum:0,frustumTravelers:0,frustumMoving:0,matrixChanged:0,modelChanged:0};
  const residents=input.life.residents.map(r=>{const m=byIndex.get(r.index),prior=prev?.residents[r.index],sig=signature(r),modelChanged=this.previousSignatures[r.index]!==undefined&&this.previousSignatures[r.index]!==sig,matrixChanged=!!m&&!!prior?.drawn&&m.matrixHash!==prior.matrixHash,next=r.path[r.pathIndex];this.previousSignatures[r.index]=sig;counts[r.status]++;if(r.facilityId?.startsWith('home-'))counts.atHome++;else if(r.status==='acting')counts.publicActing++;if(m?.inFrustum){counts.inFrustum++;if(r.status==='traveling')counts.frustumTravelers++;}if(modelChanged)counts.modelChanged++;if(matrixChanged)counts.matrixChanged++;
   if(m?.inFrustum&&(r.status==='traveling'||r.distance>(prior?.distance??r.distance))&&prior?.drawn&&prev&&this.seconds>prev.seconds&&Math.hypot(m.x-prior.displayX,m.z-prior.displayZ)/(this.seconds-prev.seconds)>=TOWN_ACTIVITY_CHECK.movementMetresPerSecond)counts.frustumMoving++;
   return {index:r.index,...(input.life.navigation?{blockedSeconds:round(input.life.navigation.residents[r.index]!.blocked),taskStage:input.life.navigation.residents[r.index]!.stage,taskMoving:!!input.life.navigation.residents[r.index]!.goal&&Math.hypot(r.x-input.life.navigation.residents[r.index]!.goal!.x,r.z-input.life.navigation.residents[r.index]!.goal!.z)>.05}:{}),status:r.status,action:r.action,facility:r.facilityId,remaining:round(r.remaining),completed:r.completed,authorityX:round(r.x),authorityZ:round(r.z),distance:round(r.distance),targetX:next?round(next.x):null,targetZ:next?round(next.z):null,modelChanged,matrixChanged,drawn:!!m,inFrustum:m?.inFrustum??false,displayX:round(m?.x??r.x),displayZ:round(m?.z??r.z),matrixHash:m?.matrixHash??0,...(m?.handOffsets?.length===6&&m.handOffsets.every(Number.isFinite)?{handOffsets:m.handOffsets.map(round)}:{}),lag:round(m?Math.hypot(m.x-r.x,m.z-r.z):0)} satisfies TownActivityResident;
  });
  const sample={segment:this.segment,motionMeasured:!!prev,activeCounters:{...this.activeCounters},seconds:round(this.seconds),tick:input.life.tick,physicsStep:input.physicsStep,renderFrames:input.renderFrames,renderTime:round(input.renderTime),mode:input.mode,camera:input.camera.slice(0,16).map(round),counts,residents};
  this.recent.push(sample);while(this.recent.length>TOWN_ACTIVITY_CHECK.maxSamples||this.recent.length>1&&this.seconds-this.recent[0]!.seconds>TOWN_ACTIVITY_CHECK.windowSeconds+1e-8)this.recent.shift();if(this.opening.length<TOWN_ACTIVITY_CHECK.maxSamples&&this.seconds<=15.01)this.opening.push(sample);
 }
 report(now?:number):TownActivityReport{return structuredClone({kind:'axiom-town-activity',version:2,...(this.layout?{townLayout:this.layout}:{}),seed:this.seed,source:this.source,callbackAgeSeconds:now===undefined||this.lastNow===null?0:round(Math.max(0,(now-this.lastNow)/1000)),callbackGaps:this.callbackGaps,paused:this.paused,status:!this.opening.length?'waiting':this.seconds<15?'measuring':'ready',opening:this.opening,recent:this.recent,openingSummary:summarizeTownActivity(this.opening),recentSummary:summarizeTownActivity(this.recent),scope:'Read-only 4 Hz population-wide authority, routes and emitted-instance matrices. Active wall-clock seconds include callback stalls; known pauses and absent-town intervals do not count. Raw tick/step/frame counters are retained, while active-only deltas and segment IDs prevent paused callbacks or hidden online progress from inflating rates or apparent travel. Rates are observed town-view updates and authority/physics steps per second, not GPU throughput. residentsAnimated is retained as a legacy alias of bodyMatricesChanged: even tiny breathing changes it; neither means visible animation or bustle. residentsWalking requires at least 0.2 m/s net root displacement in the latest up-to-5-second span and achieved travel, including a purposeful work substage. residentsWorking additionally requires advancing same-task work and at least 0.18 m excursion of an actual emitted hand tip relative to its body. Resting, waiting and quiet station bodies are reported separately; missing hand evidence never implies visible work. frustumMoving measures actual root displacement since the preceding sample. Frustum candidates are mathematical inclusion, not GPU pixels or occlusion certification. No simulation, save edits, recovery teleports, inventory, room credentials, networking or automatic upload.'});}
}

export const TOWN_ACTIVITY_ENGINE=Object.freeze({kind:'axiom-town-activity-watchdog',Monitor:TownActivityMonitor,summarize:summarizeTownActivity,config:TOWN_ACTIVITY_CHECK});
