import {createTownDirectorScenario,TOWN_DIRECTOR_ENGINE,applyTownDirectorCommand,noteTownDirectorContribution,importTownDirectorPreset,exportTownDirectorPreset,TOWN_DIRECTOR_DEFAULTS,TOWN_DIRECTOR_TUNING_REGISTRY,TOWN_DIRECTOR_SCENARIOS,type TownDirectorTuning,type TownDirectorPreset,type TownEpisode} from './town-director.ts';
import {advanceTownLife,applyTownLifeCommand,townLifeFacilities,townLifeCommandPosition,type TownLifeCommand} from './town-life.ts';
import {townLifeActionOptions,escapeTownLifeText as esc} from './town-life-ui.ts';
import {townEpisodeTitle} from './town-director-ui.ts';

/** Disposable director/town kernel rehearsal. No world/session/storage imports or automatic writes. */
export function mountTownDirectorLab(panel:HTMLElement,options:{seed:number;source:string;close:()=>void}){
 let alive=true,generation=0,elapsed=0,inventory={scrap:20,core:0,water:10},actions:unknown[]=[],truncated=false;
 let applied:TownDirectorPreset={kind:'axiom-town-director-preset',version:1,seed:options.seed,scenario:'balanced',tuning:{...TOWN_DIRECTOR_DEFAULTS}};
 let model=createTownDirectorScenario(applied.seed,applied.scenario,applied.tuning);
 panel.innerHTML=`<div class="town-life"><button type="button" class="close" aria-label="Close request rehearsal">×</button><span class="eyebrow">Disposable numerical rehearsal</span><h2>Town request director</h2><p>This independent town can be reset, stepped and helped without touching your campaign, inventory, conversation memory or online room. Intervention buttons position a test context at the target; this is not playable explorer movement.</p><label>Seed <input id="director-lab-seed" type="number" min="0" max="4294967295" step="1"></label><label>Scenario <select id="director-lab-scenario"></select></label><div id="director-lab-fields"></div><div class="row"><button type="button" id="director-lab-apply">Apply timing draft</button><button type="button" id="director-lab-reset">Reset with draft</button><button type="button" id="director-lab-repeat">Repeat applied setup</button><button type="button" id="director-lab-discard">Discard draft</button><button type="button" id="director-lab-defaults">Stage defaults</button></div><p id="director-lab-status" role="status"></p><label>Step active seconds <input id="director-lab-seconds" type="number" min="1" max="60" step="1" value="10"></label><button type="button" id="director-lab-step">Step model</button><p id="director-lab-summary"></p><div id="director-lab-episodes"></div><h3>Real model interventions</h3><label>Resident <select id="director-lab-person"></select></label><label>Service <select id="director-lab-service"></select></label><div id="director-lab-actions"></div><details><summary>Exact state and causal record</summary><pre id="director-lab-state"></pre></details><div class="row"><button type="button" id="director-lab-preset">Export applied preset</button><button type="button" id="director-lab-evidence">Export evidence</button><button type="button" id="director-lab-copy">Copy text</button></div><textarea id="director-lab-json" rows="8" maxlength="1000000" spellcheck="false" aria-label="Director preset or evidence text"></textarea><button type="button" id="director-lab-import">Stage imported preset</button><p>No automatic visual approval. All steps use the same bounded model, but this panel cannot establish browser, device, network or rendering behavior.</p></div>`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#director-lab-'+id)!;
 const status=(value:string)=>{if(alive)q('status').textContent=value;};
 const scenarioIds=['balanced','lean-stores','service-outage','social-strain'] as const;
 q<HTMLSelectElement>('scenario').innerHTML=scenarioIds.map(id=>`<option value="${id}">${id.replaceAll('-',' ')}</option>`).join('');
 q('fields').innerHTML=TOWN_DIRECTOR_TUNING_REGISTRY.map(f=>`<label>${esc(f.label)} <input type="number" id="director-lab-${f.key}" min="${f.min}" max="${f.max}" step="1"><small>${esc(f.description)} · ${esc(f.unit)} · apply while paused</small></label>`).join('');
 const record=(action:unknown)=>{if(actions.length<128)actions.push(action);else truncated=true;generation++;};
 function stage(p:TownDirectorPreset){q<HTMLInputElement>('seed').value=String(p.seed);q<HTMLSelectElement>('scenario').value=p.scenario;for(const f of TOWN_DIRECTOR_TUNING_REGISTRY)q<HTMLInputElement>(f.key).value=String(p.tuning[f.key]);}
 function read(){if(!q<HTMLInputElement>('seed').value.trim()||TOWN_DIRECTOR_TUNING_REGISTRY.some(f=>!q<HTMLInputElement>(f.key).value.trim()))throw Error('Enter every numeric seed and timing value.');const tuning=Object.fromEntries(TOWN_DIRECTOR_TUNING_REGISTRY.map(f=>[f.key,Number(q<HTMLInputElement>(f.key).value)]));return importTownDirectorPreset(JSON.stringify({kind:'axiom-town-director-preset',version:1,seed:Number(q<HTMLInputElement>('seed').value),scenario:q<HTMLSelectElement>('scenario').value,tuning}));}
 function rebuild(){q<HTMLSelectElement>('person').innerHTML=model.life.residents.map(r=>`<option value="${r.index}">Resident ${r.index+1} · ${esc(r.id)}</option>`).join('');q<HTMLSelectElement>('service').innerHTML=townLifeFacilities(applied.seed).filter(f=>f.kind!=='home').map(f=>`<option value="${esc(f.id)}">${esc(f.label)}</option>`).join('');}
 function reset(p:TownDirectorPreset){applied=p;model=createTownDirectorScenario(p.seed,p.scenario,p.tuning);elapsed=0;inventory={scrap:20,core:0,water:10};actions=[];truncated=false;generation++;rebuild();render();}
 function offerCommand(e:TownEpisode,kind:'accept'|'decline'){return {kind,episodeId:e.id,expectedRevision:model.director.revision,expectedLifeRevision:model.life.revision};}
 function optionsForActions(){const index=Number(q<HTMLSelectElement>('person').value)||0,facility=q<HTMLSelectElement>('service').value,context={seed:applied.seed,zone:'valley',player:{x:0,z:0,hp:100},inventory};return townLifeActionOptions(model.life,context,index,facility).map(a=>{const c={...context,player:{...a.target,hp:100}};return {...a,available:!!applyTownLifeCommand(model.life,c,a.command),context:c};});}
 function render(){if(!alive)return;
  q('summary').textContent=`Seed ${applied.seed} · ${applied.scenario} · ${elapsed} / 1200 active seconds · ${model.director.episodes.length} / 24 episodes · test stock ${inventory.scrap} scrap, ${inventory.water} canisters. Applied timing: ${applied.tuning.restSeconds}s rest, ${applied.tuning.deadlineSeconds}s deadline, ${applied.tuning.maxActive} active.`;
  q('episodes').innerHTML=model.director.episodes.map(e=>`<article class="frontier-job"><h3>${esc(townEpisodeTitle(e))}</h3><p>${esc(e.status)} · ${(e.remainingSteps*.5).toFixed(0)}s · ${esc(e.targetId)}</p>${e.status==='offered'?`<button type="button" data-director-lab-accept="${esc(e.id)}">Accept at actual service test context</button>`:''}${e.status==='offered'||e.status==='accepted'?`<button type="button" data-director-lab-decline="${esc(e.id)}">Decline at service test context</button>`:''}<pre>${esc(JSON.stringify({cause:e.evidence,outcome:e.outcome},null,2))}</pre></article>`).join('')||'<p>No eligible real need. The healthy model creates no artificial emergency.</p>';
  for(const kind of ['accept','decline'] as const)for(const b of q('episodes').querySelectorAll<HTMLButtonElement>('[data-director-lab-'+kind+']'))b.onclick=()=>{if(!alive)return;const e=model.director.episodes.find(e=>e.id===b.getAttribute('data-director-lab-'+kind));if(!e)return;const f=townLifeFacilities(applied.seed).find(f=>f.id===e.serviceId)!;const c=offerCommand(e,kind),next=applyTownDirectorCommand(model.director,model.life,{seed:applied.seed,zone:'valley',player:{x:f.x,z:f.z,hp:100}},c);record({kind:'episode',command:c,accepted:!!next});if(next)model={...model,director:next};render();};
  const choices=optionsForActions();q('actions').innerHTML=choices.map((a,i)=>`<div class="life-action"><button type="button" data-director-lab-help="${i}" ${a.available?'':'disabled'}>${esc(a.label)} · ${esc(a.cost)}</button><small>${esc(a.effect)}</small></div>`).join('');
  for(const b of q('actions').querySelectorAll<HTMLButtonElement>('[data-director-lab-help]'))b.onclick=()=>{if(!alive)return;const a=optionsForActions()[Number(b.dataset.directorLabHelp)];if(!a)return;const next=applyTownLifeCommand(model.life,a.context,a.command);record({kind:'help',command:a.command,accepted:!!next});if(next){model={life:next.life,director:noteTownDirectorContribution(model.director,model.life,next.life,a.command)};inventory=next.inventory;status(next.message);}render();};
  q('state').textContent=JSON.stringify({director:model.director,resources:model.life.resources,facilities:model.life.facilities.map(f=>({id:f.id,condition:f.condition,closedFor:f.closedFor})),inventory},null,2);
 }
 q<HTMLButtonElement>('apply').onclick=()=>{if(!alive)return;try{const draft=read();model={...model,director:TOWN_DIRECTOR_ENGINE.advance(model.director,model.life,0,draft.tuning)};applied={...applied,tuning:draft.tuning};record({kind:'tuning',tuning:draft.tuning});render();status('Timing applied to new offers. Existing deadlines remain latched. Seed and scenario require Reset with draft.');}catch(e){status(String(e));}};
 q<HTMLButtonElement>('reset').onclick=()=>{if(!alive)return;try{reset(read());stage(applied);status('Fresh disposable model created.');}catch(e){status(String(e));}};
 q<HTMLButtonElement>('repeat').onclick=()=>{if(alive){reset(applied);status('Applied setup repeated with fresh test stock. Draft retained.');}};
 q<HTMLButtonElement>('discard').onclick=()=>{if(alive){stage(applied);generation++;status('Pending edits discarded.');}};
 q<HTMLButtonElement>('defaults').onclick=()=>{if(alive){stage({...applied,tuning:{...TOWN_DIRECTOR_DEFAULTS}});status('Default timing staged. Apply to use it.');}};
 q<HTMLButtonElement>('step').onclick=()=>{if(!alive)return;const seconds=Number(q<HTMLInputElement>('seconds').value);if(!Number.isInteger(seconds)||seconds<1||seconds>60){status('Choose 1–60 whole active seconds.');return;}const amount=Math.min(seconds,1200-elapsed);for(let n=0;n<amount*2;n++){const life=advanceTownLife(model.life,.5);model={life,director:TOWN_DIRECTOR_ENGINE.advance(model.director,life,.5,applied.tuning)};}elapsed+=amount;record({kind:'step',seconds:amount});render();status(elapsed>=1200?'Model time bound reached. Reset for another rehearsal.':'Model stepped.');};
 q<HTMLSelectElement>('person').onchange=render;q<HTMLSelectElement>('service').onchange=render;
 q<HTMLButtonElement>('preset').onclick=()=>{if(alive){generation++;q<HTMLTextAreaElement>('json').value=exportTownDirectorPreset(applied);status('Applied preset prepared below.');}};
 q<HTMLButtonElement>('evidence').onclick=()=>{if(!alive)return;generation++;let intended:unknown;try{intended=read();}catch{intended={valid:false};}q<HTMLTextAreaElement>('json').value=JSON.stringify({kind:'axiom-town-director-evidence',version:1,mode:'disposable-model',source:options.source,seed:applied.seed,intended,applied,elapsed,actions,actionsTruncated:truncated,director:model.director,resources:model.life.resources,inventory,limits:['No campaign or online state','No browser or visual certification']},null,2);status('Exact bounded evidence prepared below.');};
 q<HTMLButtonElement>('import').onclick=()=>{if(!alive)return;try{stage(importTownDirectorPreset(q<HTMLTextAreaElement>('json').value));generation++;status('Preset staged. Reset with draft to use it.');}catch(e){status(String(e));}};
 q<HTMLButtonElement>('copy').onclick=()=>{if(!alive)return;const ticket=++generation,text=q<HTMLTextAreaElement>('json').value;if(!text)return;if(!globalThis.navigator?.clipboard){status('Select and copy the prepared text below.');return;}try{void navigator.clipboard.writeText(text).then(()=>{if(alive&&ticket===generation)status('Prepared text copied.');},()=>{if(alive&&ticket===generation)status('Copy unavailable. Select the text below.');});}catch{status('Copy unavailable. Select the text below.');}};
 const dispose=()=>{alive=false;generation++;};panel.querySelector<HTMLButtonElement>('.close')!.onclick=()=>{if(!alive)return;dispose();options.close();};stage(applied);rebuild();render();status('Independent model ready, paused.');return dispose;
}
