import {mountTownSupply,type TownSupplyViewState} from './town-supply-ui.ts';
import {applyTownSupply,townSupplyPosition,type TownSupplyCommand} from './town-supply.ts';
import {worldTownSupplySources} from './world.ts';
import {createTownLife,immutableTownLife,advanceTownLife} from './town-life.ts';
import {DEVELOPER_BUILD} from './developer-tools.ts';
export const TOWN_SUPPLY_SCENARIOS=Object.freeze([{id:'fresh',label:'Seven untouched finite caches'},{id:'shortage',label:'Empty initial town material store'},{id:'loaded',label:'Two caches genuinely loaded'},{id:'delivered',label:'Two caches delivered through normal donation'},{id:'exhausted',label:'Every cache loaded and unloaded into inventory'}] as const);
export const TOWN_SUPPLY_LAB_FIELDS=Object.freeze([{key:'seed',min:0,max:4294967295,step:1,default:73129,unit:'uint32',consumer:'Canonical valley sources and town identity',timing:'Apply setup & reset'},{key:'seconds',min:1,max:60,step:1,default:10,unit:'seconds',consumer:'Actual town navigation and donation cooldown',timing:'Step real model'}] as const);
export interface TownSupplyPreset {format:'axiom-town-supply-preset';version:1;scope:'disposable-model';source:string;seed:number;scenario:typeof TOWN_SUPPLY_SCENARIOS[number]['id']}
const provenance=(v:unknown):v is string=>typeof v==='string'&&v.length>0&&v.length<=160&&/^[a-zA-Z0-9][a-zA-Z0-9._:/ -]*$/.test(v);
export function createTownSupplyPreset(seed:number,source:string):TownSupplyPreset{return parseTownSupplyPreset(JSON.stringify({format:'axiom-town-supply-preset',version:1,scope:'disposable-model',source:provenance(source)?source:'source-unavailable',seed,scenario:'fresh'}));}
export function parseTownSupplyPreset(raw:string):TownSupplyPreset {
 if(typeof raw!=='string'||raw.length>4096||new TextEncoder().encode(raw).length>4096)throw Error('Supply preset exceeds 4 KB.');let v:unknown;try{v=JSON.parse(raw);}catch{throw Error('Enter a JSON supply preset.');}
 // Only a flat primitive-valued object is supported. This also rejects duplicate and escaped duplicate fields.
 const pairs=[...raw.matchAll(/"((?:\\.|[^"\\])*)"\s*:/g)].map(m=>JSON.parse('"'+m[1]+'"'));
 if(new Set(pairs).size!==pairs.length)throw Error('Duplicate supply preset field.');
 const keys=['format','version','scope','source','seed','scenario'];if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||!keys.every(k=>Object.hasOwn(v,k)))throw Error('Unexpected supply preset fields.');const p=v as Record<string,unknown>;
 if(p.format!=='axiom-town-supply-preset'||p.version!==1||p.scope!=='disposable-model'||!provenance(p.source)||!Number.isSafeInteger(p.seed)||Number(p.seed)<0||Number(p.seed)>0xffffffff||!TOWN_SUPPLY_SCENARIOS.some(s=>s.id===p.scenario))throw Error('Unsupported supply preset version, seed, source or scenario.');return structuredClone(p) as unknown as TownSupplyPreset;
}
/** Disposable finite-source exercise. There are no campaign getters, persistence writes or running timers. */
export function mountTownSupplyLab(panel:HTMLElement,options:{seed:number;source?:string;onClose:()=>void}){
 const defaults=createTownSupplyPreset(options.seed,options.source??'source-unavailable');let applied=structuredClone(defaults),sources=worldTownSupplySources({generation:2,seed:applied.seed,regional:{version:1}}),elapsed=0,disposed=false,generation=0,actions:unknown[]=[],preparation:unknown[]=[],truncated=false;
 let state:TownSupplyViewState={seed:applied.seed,zone:'valley',player:{x:0,z:0,hp:100},inventory:{scrap:0,core:0,water:0},collected:[],townLife:createTownLife(applied.seed)};
 panel.innerHTML=`<button id="tsl-close" class="close" aria-label="Close supply lab">×</button><span class="eyebrow">Developer · disposable supply model</span><h2>Finite supply rehearsal</h2><p>Solo-only, memory-only model. No normal saves, campaign rewards, room mutations or background catch-up. Every cache is the actual seed’s canonical valley scrap source. Loaded, delivered and exhausted setups execute real transfer commands. The shortage setup starts a validated zero-material ledger, without fake spending or credit.</p><label for="tsl-seed">Seed · uint32, reset-time</label><input id="tsl-seed" type="number" min="0" max="4294967295" step="1"><label for="tsl-scenario">Repeatable scenario · reset-time</label><select id="tsl-scenario">${TOWN_SUPPLY_SCENARIOS.map(s=>`<option value="${s.id}">${s.label}</option>`).join('')}</select><div class="row"><button id="tsl-reset-draft" type="button">Apply setup & reset</button><button id="tsl-reset" type="button">Reset applied model</button><button id="tsl-discard" type="button">Discard edits</button><button id="tsl-defaults" type="button">Stage defaults</button></div><p>Fixed rules: seven finite sources, cargo capacity four, two scrap → twelve materials, town capacity 600, donation cooldown ten seconds. No stock, currency, yield or reward multiplier is supported.</p><label for="tsl-seconds">Explicit step · 1–60 whole seconds</label><input id="tsl-seconds" type="number" min="1" max="60" step="1" value="10"><button id="tsl-step" type="button">Step real town model</button><p id="tsl-status" role="status"></p><p>Manual time stops at 1,200 seconds. The ordinary 100-resident needs, navigation, salvage and donation cooldown use the real kernel.</p><label for="tsl-target">Explicit model operator location</label><select id="tsl-target"></select><button id="tsl-move" type="button">Place model operator at target</button><p>Placement exercises exact proximity gates in this model. It is not a physical journey and never relocates any resident.</p><div id="tsl-board"></div><h3>Reproduce and inspect</h3><button id="tsl-preset" type="button">Export applied preset to text</button><button id="tsl-report" type="button">Export evidence to text</button><button id="tsl-import" type="button">Stage preset text</button><label for="tsl-text">JSON text fallback · preset imports at most 4 KB</label><textarea id="tsl-text" rows="10"></textarea><label for="tsl-file">Stage preset file</label><input id="tsl-file" type="file" accept="application/json,.json">`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#tsl-'+id)!;const marker=q('status'),current=()=>!disposed&&panel.querySelector('#tsl-status')===marker;let board:ReturnType<typeof mountTownSupply>;
 function record(a:unknown){if(actions.length<128)actions.push(structuredClone(a));else truncated=true;}
 function status(message='Paused; advance only through explicit Step.'){if(current())marker.textContent=`Applied seed ${applied.seed} · ${applied.scenario} · ${elapsed}/1200 seconds. ${message}`;}
 function fill(p:TownSupplyPreset){q<HTMLInputElement>('seed').value=String(p.seed);q<HTMLSelectElement>('scenario').value=p.scenario;}
 function draft(){return parseTownSupplyPreset(JSON.stringify({...applied,seed:q<HTMLInputElement>('seed').value.trim()?Number(q<HTMLInputElement>('seed').value):NaN,scenario:q<HTMLSelectElement>('scenario').value}));}
 function transfer(command:TownSupplyCommand){const result=applyTownSupply(state.townSupply,sources,state.townLife!,state,command);if(result)state={...state,townSupply:result.supply,townLife:result.life,inventory:result.inventory,collected:result.collected};return result;}
 function mount(){board?.dispose();board=mountTownSupply(q('board'),{getState:()=>state,getSources:()=>sources,disposable:true,onClose:()=>{dispose();options.onClose();},send:command=>{if(!current())return;const player={...state.player},result=transfer(command);record({kind:'command',command,player,accepted:!!result});generation++;status(result?.message??'The real supply kernel rejected the request.');}});q('target').innerHTML=sources.map(s=>`<option value="${s.id}">${s.label??s.id}</option>`).join('')+'<option value="workshop">Second Life Salvage</option>';q<HTMLSelectElement>('target').value=sources[0]?.id??'workshop';}
 function reset(p:TownSupplyPreset){const nextSources=worldTownSupplySources({generation:2,seed:p.seed,regional:{version:1}});let life=createTownLife(p.seed);if(p.scenario==='shortage'){const fixture=structuredClone(life);fixture.resources.materials=0;fixture.ledger.initial.materials=0;life=immutableTownLife(fixture,p.seed);}const point=nextSources[0];state={seed:p.seed,zone:'valley',player:{x:point?.x??0,z:point?.z??0,feetY:point?.y??0,hp:100},inventory:{scrap:0,core:0,water:0},collected:[],townLife:life};sources=nextSources;preparation=[];
  function run(kind:TownSupplyCommand['kind'],targetId:string){const command={kind,targetId,expectedRevision:state.townSupply?.revision??0},position=townSupplyPosition(p.seed,sources,command);if(!position)throw Error('Scenario has no canonical transfer position.');state={...state,player:{x:position.x,z:position.z,feetY:position.y,hp:100}};const result=transfer(command);if(!result)throw Error('Scenario transfer failed real supply gates.');preparation.push({command,player:{...state.player}});}
  if(p.scenario==='loaded'||p.scenario==='delivered'){for(const source of sources.slice(0,2))run('load',source.id);if(p.scenario==='delivered')run('deliver','workshop');}if(p.scenario==='exhausted')for(const source of sources){run('load',source.id);run('unload','workshop');}
  applied=structuredClone(p);elapsed=0;actions=[];truncated=false;generation++;fill(applied);mount();status('Reset only the disposable model; preparation uses real finite transfers.');
 }
 function guarded(fn:()=>void){return ()=>{if(current()){generation++;try{fn();}catch(e){status(e instanceof Error?e.message:String(e));}}};}
 function stage(){if(current()){generation++;status('Setup edits staged. Apply setup & reset to use them.');}}
 function step(seconds:number){if(!current())return;if(!Number.isSafeInteger(seconds)||seconds<1||seconds>60)throw RangeError('Step requires 1–60 whole seconds.');generation++;const dt=Math.min(seconds,1200-elapsed);if(dt>0)state={...state,townLife:advanceTownLife(state.townLife!,dt)};elapsed+=dt;record({kind:'advance',seconds:dt});board.refresh();status(dt?'Real resident work and cooldown advanced.':'Time limit reached; reset to repeat.');}
 q<HTMLInputElement>('seed').oninput=stage;q<HTMLSelectElement>('scenario').onchange=stage;q('reset-draft').onclick=guarded(()=>reset(draft()));q('reset').onclick=guarded(()=>reset(applied));q('discard').onclick=guarded(()=>{fill(applied);status('Unapplied setup discarded.');});q('defaults').onclick=guarded(()=>{fill(defaults);stage();});q('step').onclick=guarded(()=>step(Number(q<HTMLInputElement>('seconds').value)));
 q('move').onclick=guarded(()=>{const targetId=q<HTMLSelectElement>('target').value,position=townSupplyPosition(state.seed,sources,{kind:targetId==='workshop'?'deliver':'load',targetId});if(!position)throw Error('Choose a canonical source or workshop.');state={...state,player:{x:position.x,z:position.z,feetY:position.y,hp:100}};record({kind:'model-operator-placement',targetId,position});board.refresh();status('Only the model operator moved; no physical journey or NPC relocation is claimed.');});
 function report(){return {format:'axiom-town-supply-evidence',version:1,scope:'disposable-model',build:DEVELOPER_BUILD,source:defaults.source,visualReview:'not-reviewed',applied,intended:{seed:q<HTMLInputElement>('seed').value,scenario:q<HTMLSelectElement>('scenario').value},initialInventory:{scrap:0,core:0,water:0},sources,preparation,elapsed,actual:state,actions,actionsTruncated:truncated};}
 q('preset').onclick=guarded(()=>{q<HTMLTextAreaElement>('text').value=JSON.stringify(applied,null,2);status('Applied preset ready in text.');});q('report').onclick=guarded(()=>{q<HTMLTextAreaElement>('text').value=JSON.stringify(report(),null,2);status('Evidence ready in text; copy to retain it.');});function importText(raw:string){fill(parseTownSupplyPreset(raw));stage();}q('import').onclick=guarded(()=>importText(q<HTMLTextAreaElement>('text').value));q<HTMLTextAreaElement>('text').oninput=()=>{generation++;};q<HTMLInputElement>('file').onchange=async()=>{if(!current())return;const ticket=++generation,file=q<HTMLInputElement>('file').files?.[0];if(!file)return;try{if(file.size>4096)throw Error('Supply preset exceeds 4 KB.');const raw=await file.text();if(current()&&ticket===generation)importText(raw);}catch(e){if(current()&&ticket===generation)status(String(e));}};
 function dispose(){if(disposed)return;disposed=true;generation++;board?.dispose();}q('close').onclick=guarded(()=>{dispose();options.onClose();});reset(applied);return {dispose,step,report,getPreset:()=>structuredClone(applied),getState:()=>state};
}
