import * as THREE from 'three/webgpu';
import {guardPoseFromState} from './avatar-combat.ts';
import {createAvatar,rigProfile} from './avatar.ts';
import {compileEquipment,EQUIPMENT_MANIFEST} from './equipment.ts';
import {createVisualCapture} from './visual-capture.ts';
import {VISUAL_FIXTURES,QUADRUPED_VISUAL_FIXTURES,CAVE_VISUAL_FIXTURES,ECOLOGY_VISUAL_FIXTURES,ecologyReviewStates,ecologyReviewEvidence,ecologyReviewTerrain,ecologyReviewCamera,REVIEW_SEED,VISUAL_FIXTURE_VERSION,caveReviewWater,labReplayFixture,LAB_CAPTURE_TICKS,type VisualFixture,type QuadrupedVisualFixture,type CaveVisualFixture,type EcologyVisualFixture} from './visual-fixtures.ts';
import {createQuadruped} from './creature-view';
import {createCaveView} from './cave-view';
import {ENEMY_RULES} from './encounters.ts';
import {caveDepth} from './cave-water.ts';
import {createEcologyView} from './ecology-view.ts';
import {ECOLOGY_RULES} from './ecology.ts';
import {idleAnimation} from './locomotion.ts';
import {GUARD_VISUAL_FIXTURES,guardReviewStates,guardReviewCamera,type GuardReviewFrame,type GuardReviewSubject} from './guard-fixtures.ts';
import {createGuardView,guardStatusText} from './guard-view.ts';
import {ANIMATION_CLIPS,animationClip,animationSampleTicks,advanceAnimationPlayback,createAnimationReviewRunner,type AnimationClip,type AnimationReviewRun,type AnimationReviewFrame,type AnimationPlayback,type ReviewWorker} from './animation-review.ts';
import './visual-review.css';

type GuardVisualFixture=typeof GUARD_VISUAL_FIXTURES[number];
/** Detached evidence from fixed production clocks, never a fabricated combat pose. */
export function guardReviewEvidence(review:ReturnType<typeof guardReviewStates>,id:GuardReviewSubject){
 const frame=review.states[id],mode=id==='guard-too-early'?'early':id==='guard-rear'?'rear':'timed',run=review.runs[mode];
 const contacts=frame.events.filter(e=>e.type==='damage').map(event=>{
  const blocked=frame.guardEvents.some(e=>e.type==='blocked'&&e.block.enemyId===event.enemyId&&e.block.attackId===event.attackId);
  return {...event,blocked,appliedDamage:blocked?0:event.damage};
 });
 return structuredClone({fixtureId:id,version:run.version,mode,clock:'Production fixed-step snapshot; capture tick is only the fixture index',stepSeconds:run.stepSeconds,pressTick:run.pressTick,maximumTicks:run.maximumTicks,tick:frame.tick,seconds:frame.seconds,hp:frame.hp,hpBefore:run.frames[frame.tick-1]?.hp??100,sharedStamina:frame.combo.stamina,phase:frame.guard.phase,spent:frame.guard.spent,receipt:frame.guard.receipt,lastBlock:frame.guard.lastBlock,contacts,player:{x:0,y:0,z:0,facing:frame.guard.facing,hp:frame.hp,grounded:true,crouched:false},frame,scope:run.scope});
}
/** Reuses the production avatar, sentry and field; renderer sync cannot advance the fixture. */
export function createGuardReviewModel(seed=REVIEW_SEED){
 const root=new THREE.Group(),avatar=createAvatar(),sentry=createQuadruped(seed),field=createGuardView();root.name='guard-review-production-models';root.add(avatar.root,sentry.root,field.root);
 return {root,avatar,sentry,field,update(frame:GuardReviewFrame){
  avatar.update({...idleAnimation(),heading:frame.guard.facing},null,0,undefined,undefined,guardPoseFromState(frame.guard));avatar.root.position.set(0,0,0);
  sentry.update(structuredClone(frame.enemy));field.update(frame.guard,{x:0,y:0,z:0},true);root.updateMatrixWorld(true);
 },dispose(){field.dispose();sentry.dispose();const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();avatar.root.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);for(const material of Array.isArray(o.material)?o.material:[o.material])materials.add(material);}});for(const geometry of geometries)geometry.dispose();for(const material of materials)material.dispose();root.clear();root.removeFromParent();}};
}
/** Bounds contain visible production vertices only; hidden failed/expired fields are excluded. */
export function guardReviewMeshEvidence(model:ReturnType<typeof createGuardReviewModel>){
 model.root.updateMatrixWorld(true);
 const bounds=(root:THREE.Object3D)=>{const box=new THREE.Box3(),point=new THREE.Vector3();root.traverseVisible(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){const positions=o.geometry.getAttribute('position');if(positions)for(let i=0;i<positions.count;i++)box.expandByPoint(point.fromBufferAttribute(positions,i).applyMatrix4(o.matrixWorld));}});return box.isEmpty()?null:{min:box.min.toArray(),max:box.max.toArray()};};
 const all=bounds(model.root)!,avatar=bounds(model.avatar.root)!,sentry=bounds(model.sentry.root)!;
 return {scope:'Visible production mesh vertices, not visual approval',...all,feetPlane:0,belowFeetPlaneMeters:Math.max(0,-Math.min(avatar.min[1]!,sentry.min[1]!)),actors:{avatar,sentry},field:bounds(model.field.root)};
}

/** Numerical production model inspection requires neither a canvas nor a game boot. */
export function createAnimationReviewModel(){
 const root=new THREE.Group(),avatar=createAvatar(),fixture=new THREE.Group(),crates=new Map<string,THREE.Mesh>();root.name='animation-review-production-rig';root.add(avatar.root,fixture);
 const disposeFixture=()=>{fixture.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});fixture.clear();crates.clear();};
 const box=(o:{x:number;z:number;y?:number;hx:number;hy:number;hz:number},color:string)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(o.hx*2,o.hy*2,o.hz*2),new THREE.MeshStandardMaterial({color,roughness:1,flatShading:true}));mesh.position.set(o.x,o.y??o.hy,o.z);mesh.castShadow=true;mesh.receiveShadow=true;fixture.add(mesh);return mesh;};
 return {root,avatar,configure(run:AnimationReviewRun){disposeFixture();for(const obstacle of run.fixture.obstacles)box(obstacle,'#64868a');for(const crate of run.fixture.movable){const mesh=box(crate,'#ad8857');mesh.name=crate.id;crates.set(crate.id,mesh);}},update(frame:AnimationReviewFrame){const p=frame.physics;avatar.root.position.set(p.x,p.feetY,p.z);avatar.update({...frame.animation},null,0,undefined,structuredClone(p.contact));for(const crate of p.movable)crates.get(crate.id)?.position.set(crate.x,crate.y,crate.z);root.updateMatrixWorld(true);},evidence(){return avatar.getPoseEvidence();},dispose(){disposeFixture();const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();avatar.root.traverse(o=>{if(o instanceof THREE.Mesh){geometries.add(o.geometry);for(const material of Array.isArray(o.material)?o.material:[o.material])materials.add(material);}});for(const geometry of geometries)geometry.dispose();for(const material of materials)material.dispose();root.clear();root.removeFromParent();}};
}

// The module's pure guard adapters can be checked without creating a DOM or graphics renderer.
export function startVisualReview(root:HTMLElement){
root.innerHTML=`<header><a href="/" class="back">← Back to AXIOM</a><span class="eyebrow">PRODUCTION MODELS · ISOLATED REVIEW</span><h1>Inspect the frontier</h1><p>Compare character poses, creature actions, the river cave, field ecology, resonant guard and real physics-driven animation. Capture real rendered pixels for review. Nothing here changes your campaign.</p></header>
<div class="review-grid"><section class="stage"><canvas id="review-world" aria-label="Production AXIOM model review"></canvas><div class="stage-label"><span id="pose-name">Preparing renderer</span><span id="renderer-status">Not rendered</span></div><p id="watch-for" class="watch">Waiting for a supported renderer.</p><p id="guard-frame" class="watch" hidden></p></section>
<aside class="tools"><h2>Review controls</h2><label for="subject">Subject</label><select id="subject"><option value="humanoid">Humanoid · 24 poses</option><option value="quadruped">Quadruped · 13 poses</option><option value="cave">River cave · 4 views</option><option value="ecology">Field ecology · 7 views</option><option value="guard">Resonant guard · 6 views</option><option value="animation">Animation · real worker timeline</option></select><label for="fixture">Pose or view</label><select id="fixture"></select><div class="row"><button id="previous">Previous</button><button id="next">Next</button></div><section id="animation-controls" hidden aria-label="Animation timeline"><h2>Fixed-step timeline</h2><p id="animation-status" role="status">Choose a clip to run the isolated physics worker.</p><label for="animation-tick">Exact frame · 60 Hz</label><input id="animation-tick" type="range" min="1" max="1" value="1" step="1"><output id="animation-time" for="animation-tick">No worker frame</output><div class="row"><button id="animation-prev" aria-label="Previous animation frame">−1 frame</button><button id="animation-next" aria-label="Next animation frame">+1 frame</button></div><div class="row"><button id="animation-play">Play</button><button id="animation-reset">Reset</button></div><label for="animation-speed">Playback speed</label><select id="animation-speed"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select><label class="check"><input id="animation-repeat" type="checkbox" checked> Repeat clip</label><label for="animation-count">Contact sheet frames</label><select id="animation-count"><option value="12">12 exact ticks</option><option value="24" selected>24 exact ticks</option><option value="36">36 exact ticks</option></select><div class="row"><button id="animation-png">Snapshot PNG</button><button id="animation-json">Frame JSON</button></div><button id="animation-trace" class="trace">Download numerical timeline</button><p>Playback reads immutable, real worker snapshots. The physics worker stops after generation. JSON remains available when graphics are unsupported.</p></section><label for="view">Camera</label><select id="view"><option value="three-quarter">Three-quarter</option><option value="front">Front</option><option value="side">Side</option><option value="back">Back</option></select>
<label for="equipment">Equipment</label><select id="equipment"><option value="baseline">Original survey staff</option><option value="light">Reed prism · two-hand grip</option><option value="heavy">Ironwood crown · two-hand grip</option></select><label for="backend">Rendering backend</label><select id="backend"><option value="auto">WebGPU preferred</option><option value="webgl">Force WebGL2</option></select><label class="check"><input id="guides" type="checkbox" checked> Floor and clearance guides</label>
<h2>Rendered evidence</h2><button id="capture" class="primary" disabled>Capture all 24 poses</button><p id="capture-status" role="status">No frames captured</p><div class="row"><button id="save-png" disabled>Download PNG</button><button id="save-json" disabled>Download report</button></div><label for="rating">Your review of this set</label><select id="rating"><option value="not-reviewed">Not reviewed</option><option value="needs-work">Needs work</option><option value="acceptable">Acceptable for this view</option></select><label for="notes">Review notes</label><textarea id="notes" rows="3" placeholder="Which pose, silhouette or grip needs changing?"></textarea><details><summary>Deterministic replay inputs</summary><p>For the in-game developer lab. These inputs alone do not prove visual quality or physics results.</p><select id="replay" aria-label="Replay scenario"></select><button id="save-replay">Download replay fixture</button></details></aside></div>
<section class="evidence"><h2>Contact sheet</h2><p id="scope">This page renders production character, creature, cave, ecology and guard models with their real materials. These are fixed probes, not a recording of live gameplay. Low water comes from the production repair commands and water reducer in a disposable world. Garden stages come from finite seed/canister inputs, production commands and bounded weather/growth steps; the same bed is shown on actual sampled terrain, without native scenery. Guard snapshots replay fixed-step production guard and sentry reducers, including real intercepted and damaging contacts; failed guards stay expired or interrupted. Use the game to judge continuous motion, collision, combat and controls. A successful PNG export is not visual approval.</p><div id="sheet"><p>Capture a set to create an image sheet here.</p></div></section>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const source=$<HTMLCanvasElement>('review-world'),subjectSelect=$<HTMLSelectElement>('subject'),fixtureSelect=$<HTMLSelectElement>('fixture'),equipmentSelect=$<HTMLSelectElement>('equipment'),viewSelect=$<HTMLSelectElement>('view'),backendSelect=$<HTMLSelectElement>('backend');
type ReviewItem={kind:'humanoid';data:VisualFixture}|{kind:'quadruped';data:QuadrupedVisualFixture}|{kind:'cave';data:CaveVisualFixture}|{kind:'ecology';data:EcologyVisualFixture}|{kind:'guard';data:GuardVisualFixture}|{kind:'animation';data:AnimationClip};
function items():ReviewItem[]{return subjectSelect.value==='animation'?ANIMATION_CLIPS.map(data=>({kind:'animation',data})):subjectSelect.value==='guard'?GUARD_VISUAL_FIXTURES.map(data=>({kind:'guard',data})):subjectSelect.value==='ecology'?ECOLOGY_VISUAL_FIXTURES.map(data=>({kind:'ecology',data})):subjectSelect.value==='quadruped'?QUADRUPED_VISUAL_FIXTURES.map(data=>({kind:'quadruped',data})):subjectSelect.value==='cave'?CAVE_VISUAL_FIXTURES.map(data=>({kind:'cave',data})):VISUAL_FIXTURES.map(data=>({kind:'humanoid',data}));}
function populate(){fixtureSelect.replaceChildren();for(const item of items()){const option=document.createElement('option');option.value=item.data.id;option.textContent=item.data.label;fixtureSelect.append(option);}$('capture').textContent=subjectSelect.value==='animation'?'Capture exact timeline ticks':`Capture all ${items().length} ${['cave','ecology','guard'].includes(subjectSelect.value)?'views':'poses'}`;}
const initialQuery=new URLSearchParams(location.search);if(['humanoid','quadruped','cave','ecology','guard','animation'].includes(initialQuery.get('subject')??''))subjectSelect.value=initialQuery.get('subject')!;
populate();if(subjectSelect.value==='animation')fixtureSelect.value=animationClip(initialQuery.get('clip')??'').id;
for(const id of Object.keys(LAB_CAPTURE_TICKS)){const option=document.createElement('option');option.value=id;option.textContent=id;$('replay').append(option);}
backendSelect.value=new URLSearchParams(location.search).get('backend')==='webgl'?'webgl':'auto';
let backend='not-initialized',busy=false,ready=false,renderer:THREE.WebGPURenderer;
const scene=new THREE.Scene();scene.background=new THREE.Color('#a7c8b4');
scene.add(new THREE.HemisphereLight('#eaffda','#385c58',2.1));const sun=new THREE.DirectionalLight('#fff0c3',3.5);sun.position.set(-3.5,6.5,2.5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-4;sun.shadow.camera.right=4;sun.shadow.camera.top=4;sun.shadow.camera.bottom=-4;sun.shadow.normalBias=.02;scene.add(sun);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.MeshStandardMaterial({color:'#6e9870',roughness:1,flatShading:true}));floor.rotation.x=-Math.PI/2;floor.position.y=-.01;floor.receiveShadow=true;scene.add(floor);
const guides=new THREE.Group(),grid=new THREE.GridHelper(10,20,'#264d48','#527e68');grid.position.y=.002;guides.add(grid);
for(const [y,color] of [[1.1,'#dba858'],[2.16,'#539ca4']] as const){const geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-1.9,y,0),new THREE.Vector3(1.9,y,0)]);guides.add(new THREE.Line(geometry,new THREE.LineBasicMaterial({color,transparent:true,opacity:.8})));}scene.add(guides);
const avatar=createAvatar(),quadruped=createQuadruped(REVIEW_SEED);scene.add(avatar.root,quadruped.root);quadruped.root.visible=false;const camera=new THREE.PerspectiveCamera(38,16/10,.01,240);scene.add(sun.target);
let cave:ReturnType<typeof createCaveView>|null=null,caveWater:ReturnType<typeof caveReviewWater>|null=null;
function ensureCave(){if(!cave){cave=createCaveView(REVIEW_SEED);scene.add(cave.root);caveWater=caveReviewWater(REVIEW_SEED);}return cave;}
let ecology:ReturnType<typeof createEcologyView>|null=null,ecologyStates:ReturnType<typeof ecologyReviewStates>|null=null,ecologyTerrain:THREE.Mesh<THREE.BufferGeometry,THREE.MeshStandardMaterial>|null=null;
function ensureEcology(){if(!ecology){const states=ecologyReviewStates(REVIEW_SEED),support=ecologyReviewTerrain(REVIEW_SEED),geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(support.positions,3));geometry.setIndex(support.indices);geometry.computeVertexNormals();ecology=createEcologyView(REVIEW_SEED);ecologyStates=states;ecologyTerrain=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:'#6e9870',roughness:1,flatShading:true}));ecologyTerrain.name='ecology-review-production-surface-support';ecologyTerrain.receiveShadow=true;scene.add(ecology.root,ecologyTerrain);}return ecology;}
let guardModel:ReturnType<typeof createGuardReviewModel>|null=null,guardStates:ReturnType<typeof guardReviewStates>|null=null;
function ensureGuard(){if(!guardModel){guardStates=guardReviewStates();guardModel=createGuardReviewModel();scene.add(guardModel.root);}return guardModel;}
let animationModel:ReturnType<typeof createAnimationReviewModel>|null=null,animationRun:AnimationReviewRun|null=null,animationLoading=false,animationGeneration=0,animationRAF=0,animationLast=0,animationDisposed=false;
let playback:AnimationPlayback={tick:1,playing:false,remainder:0};
type RenderedAnimationFrame={clip:string;tick:number;view:string;equipment:string;guides:boolean;width:number;height:number;backend:string;renderedAt:string};
let animationRendered:RenderedAnimationFrame|null=null;
let capturedAnimationRun:AnimationReviewRun|null=null;
const animationCache=new Map<string,AnimationReviewRun>(),animationRunner=createAnimationReviewRunner(()=>new Worker(new URL('./physics.worker.ts',import.meta.url),{type:'module'}) as unknown as ReviewWorker);
function ensureAnimation(){if(!animationModel){animationModel=createAnimationReviewModel();scene.add(animationModel.root);}return animationModel;}
const animationFrame=()=>animationRun?.frames[playback.tick-1]??null;
function pauseAnimation(){playback={...playback,playing:false,remainder:0};cancelAnimationFrame(animationRAF);animationRAF=0;$('animation-play').textContent='Play';}
function animationControls(){
 const active=subjectSelect.value==='animation',available=active&&!!animationRun&&!animationLoading&&!busy;
 $('animation-controls').hidden=!active;
 $('scope').textContent=active?'This timeline is generated on demand by the actual production physics worker and Rapier in a tiny flat collider fixture. Every displayed frame reuses a recorded collision-resolved snapshot and the production animation reducer and avatar. Play, pause, scrub and repeat never advance campaign state. Contact sheets use exact selected worker ticks and real canvas pixels. JSON contains actual local/world rig transforms, hand-anchor errors, intended/resolved motion, inputs and source timing even if graphics are unsupported. No full valley, network, mobile, continuous gameplay or performance approval is implied. Pixels remain unreviewed.':defaultScope;
 for(const id of ['animation-tick','animation-prev','animation-next','animation-play','animation-reset','animation-json','animation-trace'])$<HTMLInputElement>(id).disabled=!available;
 $<HTMLButtonElement>('animation-png').disabled=!available||!ready;
 $<HTMLInputElement>('animation-tick').max=String(animationRun?.maximumTicks??1);$<HTMLInputElement>('animation-tick').value=String(playback.tick);
 const frame=animationFrame();$('animation-time').textContent=frame?`Tick ${frame.tick} / ${animationRun!.maximumTicks} · ${frame.seconds.toFixed(3)} s · ${frame.physics.contact.mode}${frame.physics.contact.mantle?` · ${frame.physics.contact.mantle.phase} · supports: ${[frame.physics.contact.mantle.leftHandSupport?'left palm':'',frame.physics.contact.mantle.rightHandSupport?'right palm':'',frame.physics.contact.mantle.leftKnee?'left knee':'',frame.physics.contact.mantle.leftFootSupport?'left boot':'',frame.physics.contact.mantle.rightFootSupport?'right boot':''].filter(Boolean).join(', ')}`:''}`:'No worker frame';
 $('animation-play').textContent=playback.playing?'Pause':'Play';
 if(active)$<HTMLButtonElement>('capture').disabled=!available||!ready;
}
async function loadAnimation(){
 pauseAnimation();const generation=++animationGeneration;animationRunner.cancel();animationRun=null;animationRendered=null;
 if(subjectSelect.value!=='animation'){animationLoading=false;animationControls();return;}
 animationLoading=true;const clip=animationClip(fixtureSelect.value);$('animation-status').textContent=`Generating ${clip.ticks} exact 60 Hz ticks in the isolated production physics worker…`;animationControls();draw();
 try{
  const run=animationCache.get(clip.id)??await animationRunner.load(clip);
  if(animationDisposed||generation!==animationGeneration||subjectSelect.value!=='animation')return;
  animationCache.set(clip.id,run);animationRun=run;ensureAnimation().configure(run);playback={tick:1,playing:false,remainder:0};
  const modes=[...new Set(run.frames.map(f=>f.physics.contact.mode))];$('animation-status').textContent=`${run.frames.length} actual Rapier ${run.rapierVersion} snapshots · ${modes.join(', ')} · worker stopped`;
 }catch(error){if(generation===animationGeneration){$('animation-status').textContent=error instanceof Error?error.message:String(error);$('capture-status').textContent='No animation frames or pixels were fabricated.';}}
 finally{if(generation===animationGeneration){animationLoading=false;animationControls();draw();}}
}
const loadouts={light:compileEquipment(73129,{grip:'linen',shaft:'reed',head:'prism'}),heavy:compileEquipment(73130,{grip:'braced',shaft:'ironwood',head:'crown'})};
const metadata=()=>({fixtureVersion:VISUAL_FIXTURE_VERSION,sampleClock:subjectSelect.value==='animation'?'Exact production physics worker tick at 60 Hz':'fixture index, not worker time',sourceRevision:import.meta.env.VITE_AXIOM_SOURCE_REVISION||'not-recorded',subject:subjectSelect.value,seed:REVIEW_SEED,rigProfile,equipmentManifest:EQUIPMENT_MANIFEST,equipment:['humanoid','animation'].includes(subjectSelect.value)?equipmentSelect.value:null,quadrupedPlan:subjectSelect.value==='quadruped'?quadruped.plan:null,enemyRules:['quadruped','guard'].includes(subjectSelect.value)?ENEMY_RULES:null,cavePlan:subjectSelect.value==='cave'?{hash:cave?.plan.hash,tiles:cave?.plan.tiles.length,walls:cave?.plan.walls.length,waterReductionSteps:caveWater?.steps}:null,ecologyPlan:subjectSelect.value==='ecology'?ecology?.plan:null,ecologyInputs:subjectSelect.value==='ecology'?{initialContext:ecologyStates?.initialContext,stepSeconds:ecologyStates?.stepSeconds,maxSteps:ecologyStates?.maxSteps}:null,ecologyTerrain:subjectSelect.value==='ecology'?'Inspection patch sampled from actual valley surface; native scenery omitted':null,guardPlan:subjectSelect.value==='guard'?{fixtureVersion:guardStates?.runs.timed.version,recipe:guardStates?.runs.timed.recipe,sentryPlan:guardModel?.sentry.plan,avatarPose:'Production grounded idle, locked guard facing, baseline survey staff',playerPosition:[0,0,0],enemyStartPosition:[0,0,2],stepSeconds:guardStates?.runs.timed.stepSeconds,maximumTicks:guardStates?.runs.timed.maximumTicks,pressTicks:{timed:guardStates?.runs.timed.pressTick,early:guardStates?.runs.early.pressTick,rear:guardStates?.runs.rear.pressTick}}:null,view:viewSelect.value,backend,sourceWidth:source.width,sourceHeight:source.height,pixelRatio:renderer?.getPixelRatio()??null,guides:guides.visible,frameCount:subjectSelect.value==='animation'?animationRun?.frames.length??0:items().length,animationPlan:subjectSelect.value==='animation'&&animationRun?{version:animationRun.version,clip:animationRun.clip,stepSeconds:animationRun.stepSeconds,maximumTicks:animationRun.maximumTicks,startedAt:animationRun.startedAt,completedAt:animationRun.completedAt,rapierVersion:animationRun.rapierVersion,fixture:animationRun.fixture,source:animationRun.source}:null,userAgent:navigator.userAgent,source:'Production createAvatar + createQuadruped + createCaveView + createEcologyView + createGuardView; isolated probes',lighting:'Production hemisphere/sun colors and intensity; inspection-sized shadow camera',limitations:subjectSelect.value==='animation'?animationRun?.scope??['Physics not generated']:['No campaign state','No runtime worker playback','No live gameplay or network authority run; guard uses disposable production reducers','No mobile touch test','No animation continuity approval','No performance benchmark']});
const capture=createVisualCapture(source,{metadata,width:480,height:300});
const defaultScope=$('scope').textContent??'';
function selected():ReviewItem{return items().find(f=>f.data.id===fixtureSelect.value)??items()[0]!;}
function meshEvidence(item:ReviewItem){if(item.kind==='guard')return guardReviewMeshEvidence(guardModel!);const object=item.kind==='animation'?ensureAnimation().avatar.root:item.kind==='humanoid'?avatar.root:item.kind==='quadruped'?quadruped.root:item.kind==='cave'?cave!.root:ecology!.root;if(item.kind==='ecology')object.traverse(o=>{if(o instanceof THREE.InstancedMesh)o.computeBoundingBox();});object.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(object,true),feetPlane=item.kind==='animation'?(animationFrame()?.physics.contact.mantle?null:animationFrame()?.physics.feetY??0):item.kind==='humanoid'?item.data.floorY:item.kind==='quadruped'?0:null;return {scope:'Numeric mesh envelope, not visual approval',min:bounds.min.toArray(),max:bounds.max.toArray(),feetPlane,belowFeetPlaneMeters:feetPlane===null?null:Math.max(0,feetPlane-bounds.min.y)};}
function pose(item:ReviewItem){
 avatar.root.visible=item.kind==='humanoid';quadruped.root.visible=item.kind==='quadruped';if(cave)cave.root.visible=item.kind==='cave';if(ecology)ecology.root.visible=item.kind==='ecology';if(ecologyTerrain)ecologyTerrain.visible=item.kind==='ecology';if(guardModel)guardModel.root.visible=item.kind==='guard';if(animationModel)animationModel.root.visible=item.kind==='animation';floor.visible=['humanoid','quadruped','guard','animation'].includes(item.kind);floor.material.color.set(item.kind==='guard'?'#71817c':'#6e9870');$('guard-frame').hidden=item.kind!=='guard';guides.visible=floor.visible&&$<HTMLInputElement>('guides').checked;
 const target=new THREE.Vector3(0,item.kind==='quadruped'?.9:1.1,0),distance=item.kind==='quadruped'?7.8:6.8;let pos=viewSelect.value==='front'?[0,2,distance]:viewSelect.value==='side'?[distance,2,0]:viewSelect.value==='back'?[0,2,-distance]:item.kind==='humanoid'?[4.6,2.7,5.7]:[5.2,3.1,6.4];let shadowExtent=4;
 if(item.kind==='animation'){const frame=animationFrame();if(!frame){$('pose-name').textContent=item.data.label;$('watch-for').textContent='Waiting for real worker snapshots. No animation pose is shown.';if(animationModel)animationModel.root.visible=false;return;}const model=ensureAnimation(),p=frame.physics;model.root.visible=true;model.avatar.setEquipment(equipmentSelect.value==='light'?loadouts.light:equipmentSelect.value==='heavy'?loadouts.heavy:null);model.update(frame);target.set(p.x,p.feetY+1.1,p.z);pos=viewSelect.value==='front'?[p.x,p.feetY+2,p.z+6.8]:viewSelect.value==='side'?[p.x-6.8,p.feetY+2,p.z]:viewSelect.value==='back'?[p.x,p.feetY+2,p.z-6.8]:[p.x-4.6,p.feetY+2.7,p.z+5.7];shadowExtent=5;}
 else if(item.kind==='humanoid'){const f=item.data,equipment=equipmentSelect.value;avatar.setEquipment(equipment==='light'?loadouts.light:equipment==='heavy'?loadouts.heavy:null);avatar.update({...f.animation},f.action,f.progress,f.combo);avatar.root.position.y=f.floorY;avatar.root.updateMatrixWorld(true);}
 else if(item.kind==='quadruped')quadruped.update(structuredClone(item.data.enemy));
 else if(item.kind==='guard'){const model=ensureGuard(),frame=guardStates!.states[item.data.id],framing=guardReviewCamera(viewSelect.value);model.root.visible=true;model.update(frame);target.set(...framing.target);pos=framing.position;shadowExtent=5;const evidence=guardReviewEvidence(guardStates!,item.data.id);$('guard-frame').textContent=`Tick ${frame.tick} · ${frame.hp} HP · ${frame.combo.stamina} shared stamina · phase ${frame.guard.phase} · ${guardStatusText(frame.guard,frame.combo.stamina)} · receipt ${frame.guard.receipt?.intentId??'none'} (${frame.guard.receipt?.status??'none'}) · block receipt ${frame.guard.lastBlock?.id??'none'} · sentry ${frame.enemy.phase}, attack ${frame.enemy.attackId} · ${evidence.contacts.length?evidence.contacts.map(c=>c.blocked?'contact intercepted':`${c.appliedDamage} contact damage`).join(', '):'no contact on this tick'}`;}
 else if(item.kind==='ecology'){const model=ensureEcology(),frame=ecologyReviewCamera(REVIEW_SEED,viewSelect.value);model.sync(ecologyStates!.states[item.data.stage].state);ecologyTerrain!.visible=true;target.set(...frame.target);pos=frame.position;shadowExtent=7;}
 else{const f=item.data,model=ensureCave();model.root.visible=true;model.sync(caveWater![f.water],[]);const full=f.framing==='overview',middle=model.plan.basins[1],center=middle.tiles.reduce((a,p)=>({x:a.x+p.x/middle.tiles.length,z:a.z+p.z/middle.tiles.length}),{x:0,z:0});target.set(full?0:center.x,0,full?0:center.z);const distance=full?78:17,height=full?87:19;pos=viewSelect.value==='front'?[0,height,distance]:viewSelect.value==='side'?[distance,height,0]:viewSelect.value==='back'?[0,height,-distance]:[distance*.65,height,distance*.72];pos=[pos[0]!+target.x,pos[1]!,pos[2]!+target.z];shadowExtent=full?42:24;}
 camera.near=item.kind==='guard'?guardReviewCamera(viewSelect.value).near:.01;camera.far=item.kind==='guard'?guardReviewCamera(viewSelect.value).far:item.kind==='ecology'?ecologyReviewCamera(REVIEW_SEED,viewSelect.value).far:240;camera.updateProjectionMatrix();sun.position.set(target.x-(item.kind==='cave'?35:3.5),item.kind==='cave'?65:item.kind==='ecology'?target.y+6.5:6.5,target.z+(item.kind==='cave'?25:2.5));sun.target.position.copy(target);sun.shadow.camera.left=-shadowExtent;sun.shadow.camera.right=shadowExtent;sun.shadow.camera.top=shadowExtent;sun.shadow.camera.bottom=-shadowExtent;sun.shadow.camera.updateProjectionMatrix();camera.position.set(pos[0]!,pos[1]!,pos[2]!);camera.lookAt(target);$('pose-name').textContent=item.data.label+(item.kind==='animation'?` · tick ${playback.tick}`:'');const penetration=meshEvidence(item).belowFeetPlaneMeters;$('watch-for').textContent=item.data.watch+(penetration!==null&&penetration>.02?` Numeric warning: mesh reaches ${(penetration*100).toFixed(1)} cm below its feet plane. Inspect floor contact.`:'');
}
function draw(){if(busy)return;try{if(subjectSelect.value==='animation'){animationRendered=null;pose(selected());animationControls();if(!ready||!animationFrame())return;}else{if(!ready)return;pose(selected());}renderer.render(scene,camera);if(subjectSelect.value==='animation')animationRendered={clip:animationRun!.clip,tick:playback.tick,view:viewSelect.value,equipment:equipmentSelect.value,guides:guides.visible,width:source.width,height:source.height,backend,renderedAt:new Date().toISOString()};}catch(error){$('capture-status').textContent='Preview failed: '+(error instanceof Error?error.message:String(error));}}
function resize(){if(!ready||busy)return;const width=Math.max(320,Math.floor(source.parentElement!.clientWidth));renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(width,Math.round(width*.625),false);camera.aspect=16/10;camera.updateProjectionMatrix();draw();}
function toggleBusy(value:boolean){busy=value;for(const id of ['subject','fixture','view','equipment','backend','guides','previous','next','capture'])($<HTMLInputElement>(id)).disabled=value||(!ready&&!['subject','fixture','backend'].includes(id)&&subjectSelect.value!=='animation');equipmentSelect.disabled=value||!['humanoid','animation'].includes(subjectSelect.value);$<HTMLInputElement>('guides').disabled=value||['cave','ecology'].includes(subjectSelect.value);animationControls();}
function downloadJSON(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function animationEvidence(){
 const frame=animationFrame();if(!frame||!animationRun)return null;pose(selected());
 const rendered=animationRendered?.clip===animationRun.clip&&animationRendered.tick===frame.tick&&animationRendered.view===viewSelect.value&&animationRendered.equipment===equipmentSelect.value&&animationRendered.guides===guides.visible&&animationRendered.width===source.width&&animationRendered.height===source.height?animationRendered:null;
 return {version:animationRun.version,exportedAt:new Date().toISOString(),source:metadata(),tick:frame.tick,seconds:frame.seconds,frame:structuredClone(frame),rig:ensureAnimation().evidence(),rendered:rendered!==null,renderedFrame:rendered,visualReview:'not-reviewed',scope:'Exact production rig matrices and worker snapshot. Numerical evidence is available without graphics and is never pixel approval.'};
}
async function captureAnimation(){
 if(!ready||busy||!animationRun)return;pauseAnimation();const before=playback.tick,run=animationRun,ticks=animationSampleTicks(run.frames.length,Number($<HTMLSelectElement>('animation-count').value));toggleBusy(true);animationRendered=null;
 capturedAnimationRun=run;capture.arm({scenario:`production-animation-${run.clip}-${equipmentSelect.value}-${viewSelect.value}`,ticks});
 try{for(const tick of ticks){
  if(document.hidden||animationDisposed)throw new Error('Animation capture interrupted while page was hidden or closed');
  playback={tick,playing:false,remainder:0};pose(selected());renderer.render(scene,camera);animationRendered={clip:run.clip,tick,view:viewSelect.value,equipment:equipmentSelect.value,guides:guides.visible,width:source.width,height:source.height,backend,renderedAt:new Date().toISOString()};
  capture.afterRender({scenario:capture.report().scenario,tick,label:`${run.label} · tick ${tick} · ${(tick/60).toFixed(3)}s`,details:{animation:animationEvidence(),camera:camera.position.toArray(),cameraNear:camera.near,cameraFar:camera.far,geometry:meshEvidence(selected())}});
  $('capture-status').textContent=`Rendered ${capture.report().entries.length}/${ticks.length} exact timeline ticks`;await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
 }}catch(error){capture.cancel(error instanceof Error?error.message:String(error));}
 finally{const report=capture.report(),good=report.entries.filter(e=>e.status==='captured').length;$('capture-status').textContent=`${good} exact rendered ticks · ${report.entries.length-good} need attention · ${report.status}`;try{const sheet=capture.contactSheet();sheet.setAttribute('aria-label','Actual rendered animation contact sheet at exact worker ticks');$('sheet').replaceChildren(sheet);}catch(error){$('capture-status').textContent+=' · Sheet unavailable: '+String(error);}$<HTMLButtonElement>('save-png').disabled=!report.entries.some(e=>e.status==='captured'||e.status==='suspect');$<HTMLButtonElement>('save-json').disabled=false;playback={tick:before,playing:false,remainder:0};toggleBusy(false);if(!animationDisposed)resize();}
}
$('animation-tick').oninput=()=>{pauseAnimation();playback={tick:Number($<HTMLInputElement>('animation-tick').value),playing:false,remainder:0};draw();};
for(const [id,offset]of [['animation-prev',-1],['animation-next',1]]as const)$(id).onclick=()=>{if(!animationRun)return;pauseAnimation();playback={tick:Math.max(1,Math.min(animationRun.maximumTicks,playback.tick+offset)),playing:false,remainder:0};draw();};
$('animation-reset').onclick=()=>{pauseAnimation();playback={tick:1,playing:false,remainder:0};draw();};
function animateTimeline(now:number){
 if(!playback.playing||!animationRun||animationDisposed||subjectSelect.value!=='animation')return;
 playback=advanceAnimationPlayback(playback,(now-animationLast)/1000,Number($<HTMLSelectElement>('animation-speed').value),$<HTMLInputElement>('animation-repeat').checked,animationRun.maximumTicks);animationLast=now;draw();
 if(playback.playing)animationRAF=requestAnimationFrame(animateTimeline);
}
$('animation-play').onclick=()=>{if(!animationRun||busy)return;if(playback.playing){pauseAnimation();return;}if(playback.tick>=animationRun.maximumTicks)playback.tick=1;playback={...playback,playing:true,remainder:0};animationLast=performance.now();animationControls();animationRAF=requestAnimationFrame(animateTimeline);};
$('animation-json').onclick=()=>{if(!animationFrame())return;pauseAnimation();draw();downloadJSON(`axiom-animation-${animationRun!.clip}-tick-${playback.tick}.json`,animationEvidence());};
$('animation-trace').onclick=()=>{if(!animationRun)return;pauseAnimation();downloadJSON(`axiom-animation-${animationRun.clip}-timeline.json`,{...structuredClone(animationRun),metadata:metadata(),selectedFrame:animationEvidence(),visualReview:'not-reviewed',renderedCapture:false,scope:'Numerical production worker timeline. This file does not claim every frame was rendered or captured.'});};
$('animation-png').onclick=()=>{
 if(!ready||busy||!animationFrame())return;pauseAnimation();draw();const evidence=animationEvidence();if(!evidence?.rendered){$('animation-status').textContent='The exact requested frame was not rendered; no PNG exported.';return;}
 try{const copy=document.createElement('canvas');copy.width=source.width;copy.height=source.height;const context=copy.getContext('2d');if(!context)throw new Error('2D capture unavailable');context.drawImage(source,0,0);const clip=animationRun!.clip,tick=playback.tick;copy.toBlob(blob=>{if(!blob){$('animation-status').textContent='PNG encoding failed; no pixel evidence exported.';return;}const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`axiom-animation-${clip}-tick-${tick}.png`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('animation-status').textContent=`Exported actual canvas PNG at tick ${tick}; pixels remain unreviewed.`;},'image/png');}catch(error){$('animation-status').textContent='Snapshot failed: '+String(error);}
};
addEventListener('visibilitychange',()=>{if(document.hidden){pauseAnimation();animationControls();}});
$('capture').onclick=async()=>{if(!ready||busy)return;if(subjectSelect.value==='animation'){await captureAnimation();return;}if(['cave','ecology','guard'].includes(subjectSelect.value)){try{if(subjectSelect.value==='cave')ensureCave();else if(subjectSelect.value==='ecology')ensureEcology();else ensureGuard();}catch(error){$('capture-status').textContent='Production fixture failed: '+(error instanceof Error?error.message:String(error));return;}}toggleBusy(true);capturedAnimationRun=null;const previous=fixtureSelect.value,set=items();capture.arm({scenario:'production-'+subjectSelect.value+(subjectSelect.value==='humanoid'?'-'+equipmentSelect.value:'')+'-'+viewSelect.value,ticks:set.map((_,i)=>i)});try{for(let i=0;i<set.length;i++){if(document.hidden)throw new Error('Page hidden during capture');const f=set[i]!;pose(f);renderer.render(scene,camera);capture.afterRender({scenario:capture.report().scenario,tick:i,label:f.data.label,details:{fixture:structuredClone(f),camera:camera.position.toArray(),cameraNear:camera.near,cameraFar:camera.far,geometry:meshEvidence(f),...(f.kind==='guard'?{guard:guardReviewEvidence(guardStates!,f.data.id),framing:guardReviewCamera(viewSelect.value)}:f.kind==='cave'?{water:structuredClone(caveWater![f.data.water]),depths:cave!.plan.basins.map(b=>caveDepth(caveWater![f.data.water],b.index,cave!.plan))}:f.kind==='ecology'?{ecology:ecologyReviewEvidence(ecologyStates!,f.data),framing:ecologyReviewCamera(REVIEW_SEED,viewSelect.value),soilSurfaceOffset:.022,soilCapacityLitres:ECOLOGY_RULES.soilCapacity}:{})}});$('capture-status').textContent=`Rendered ${i+1}/${set.length} frames`;await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));}
 }catch(error){capture.cancel(error instanceof Error?error.message:String(error));}finally{const report=capture.report(),good=report.entries.filter(e=>e.status==='captured').length,attention=report.entries.filter(e=>e.status!=='captured').length;$('capture-status').textContent=`${good} rendered frames · ${attention} need attention · ${report.status}`;const sheet=capture.contactSheet();sheet.setAttribute('aria-label','Actual rendered pose contact sheet');$('sheet').replaceChildren(sheet);$<HTMLButtonElement>('save-png').disabled=report.entries.length===0;$<HTMLButtonElement>('save-json').disabled=false;fixtureSelect.value=previous;toggleBusy(false);resize();}};
$('save-png').onclick=()=>capture.download('png');$('save-json').onclick=()=>downloadJSON('axiom-visual-review.json',{...capture.report(),...(capturedAnimationRun?{animation:structuredClone(capturedAnimationRun)}:{}),userReview:{rating:$<HTMLSelectElement>('rating').value,notes:$<HTMLTextAreaElement>('notes').value}});
$('save-replay').onclick=()=>{const id=$<HTMLSelectElement>('replay').value;downloadJSON('axiom-replay-'+id+'.json',labReplayFixture(id));};
for(const select of [equipmentSelect,viewSelect])select.onchange=draw;fixtureSelect.onchange=()=>{if(subjectSelect.value==='animation')void loadAnimation();else draw();};$('guides').onchange=draw;
subjectSelect.onchange=()=>{populate();void loadAnimation();toggleBusy(false);draw();};
for(const [id,direction] of [['previous',-1],['next',1]] as const)$(id).onclick=()=>{const set=items(),index=set.findIndex(f=>f.data.id===fixtureSelect.value);fixtureSelect.value=set[(index+direction+set.length)%set.length]!.data.id;if(subjectSelect.value==='animation')void loadAnimation();else draw();};
backendSelect.onchange=()=>{const url=new URL(location.href);url.searchParams.set('backend',backendSelect.value);location.href=url.toString();};
addEventListener('resize',resize);addEventListener('pagehide',()=>{capture.cancel('Page closed');animationDisposed=true;animationGeneration++;pauseAnimation();animationRunner.dispose();animationModel?.dispose();quadruped.dispose();guardModel?.dispose();cave?.dispose();ecology?.dispose();ecologyTerrain?.geometry.dispose();ecologyTerrain?.material.dispose();renderer?.dispose();},{once:true});
async function start(){try{renderer=new THREE.WebGPURenderer({canvas:source,antialias:true,forceWebGL:backendSelect.value==='webgl'});renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;await renderer.init();backend=(renderer.backend as unknown as {isWebGPUBackend?:boolean}).isWebGPUBackend?'WebGPU':'WebGL2';ready=true;$('renderer-status').textContent=backend+' · real renderer';toggleBusy(false);resize();}catch(error){$('renderer-status').textContent='Renderer failed';$('watch-for').textContent='No visual evidence was captured. Try Force WebGL2 or open in a compatible browser.';$('capture-status').textContent=error instanceof Error?error.message:String(error);backendSelect.disabled=false;toggleBusy(false);if(subjectSelect.value==='animation')draw();console.error(error);}}
animationControls();if(subjectSelect.value==='animation')void loadAnimation();void start();
}
if(typeof document!=='undefined'){const root=document.querySelector<HTMLElement>('#visual-review');if(root)startVisualReview(root);}
