import {createConnectedState,enableWaterRequests,enableCommonsTrade,applyAction,worldObjects,validateSave,parseSave,serializeSave} from './world.ts';import {causalPlan} from './causal.ts';import {waterRequestView} from './water-requests.ts';import type {SystemCheck} from './systems-lab.ts';
/** Two production-earned cycles with exactly three finite canisters; no active world input. */
export function waterRequestSystemCheck():SystemCheck {
 const seed=1,home=causalPlan(seed).settlements[1]!;let s=enableWaterRequests(enableCommonsTrade(createConnectedState(seed)));for(const o of worldObjects(s)){if(o.kind==='enemy'||o.kind==='water'){s=applyAction(s,{type:'move',...o});s=applyAction(s,o.kind==='enemy'?{type:'attack',id:o.id}:{type:'collect',id:o.id});}}s=applyAction(s,{type:'move',...home.position});
 const episodes=()=>waterRequestView(s.causal!,seed).episodes.filter(e=>e.settlementId===home.id),deliver=()=>{s=applyAction(s,{type:'causal',command:{type:'deliver-water',settlementId:home.id}});};let commands=0;
 for(let cycle=0;cycle<2;cycle++){if(cycle)deliver();for(let n=0;n<2400&&!episodes().some(e=>e.status==='offered');n++)s=applyAction(s,{type:'tick',dt:.25});const e=episodes().find(e=>e.status==='offered');if(!e)break;s=applyAction(s,{type:'water-request',command:{type:'accept',id:e.id,expectedRevision:s.causal!.waterRequests!.revision}});deliver();s=applyAction(s,{type:'water-request',command:{type:'claim',id:e.id,expectedRevision:s.causal!.waterRequests!.revision}});commands++;}
 const done=episodes(),roundtrip=validateSave(s)?parseSave(serializeSave(s)):null;
 return {name:'Recurring relief follows real consumption · seed 1',expected:'Two distinct relief/consumption/shortage cycles consume three canisters, pay only8 existing-budget renown and round-trip',pass:commands===2&&done.length===2&&done.every(e=>e.status==='claimed')&&done[0]!.id!==done[1]!.id&&s.causal!.renown===8&&s.inventory.water===0&&s.causal!.playerSpent.water===3&&!!roundtrip,actual:`${done.length} episodes; ${done.map(e=>e.status).join(', ')}; ${s.causal!.playerSpent.water} canisters; ${s.causal!.renown} renown; valid save ${!!roundtrip}`};
}
