import {DEFAULT_WORKSHOP_DRAFT,WORKSHOP_AUTHORING_FIELDS,WORKSHOP_PRESET_MAX_BYTES,compileWorkshopDraft,validateWorkshopDraft,importWorkshopPreset,exportWorkshopPreset,type WorkshopDraft} from './workshop-authoring.ts';
import {WORKSHOP_PARCEL,WORKSHOP_BOARD,workshopConstructionQuote,workshopConstructionBlockReason,type WorkshopConstructionState,type WorkshopConstructionCommand} from './workshop-construction.ts';
import {assignTownWorkshopWorker,type TownLifeState} from './town-life.ts';
import {townResidents} from './town-residents.ts';
export interface WorkshopConstructionViewState {seed:number;zone:string;player:{x:number;z:number;hp:number};townLife?:TownLifeState;workshopConstruction?:WorkshopConstructionState}
export interface WorkshopConstructionUIOptions {getState:()=>WorkshopConstructionViewState;send:(command:WorkshopConstructionCommand)=>void;onClose:()=>void;ready?:()=>boolean;visit?:()=>void;disposable?:boolean}
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
/** The only campaign mutation is an explicit command; editing/importing never pays or builds. */
export function mountWorkshopConstruction(panel:HTMLElement,options:WorkshopConstructionUIOptions){
 let disposed=false,generation=0;const initial=options.getState();let applied=validateWorkshopDraft(initial.workshopConstruction?.parameters??{...DEFAULT_WORKSHOP_DRAFT,seed:initial.seed});
 panel.innerHTML=`<button id="wc-close" class="close" aria-label="Close workshop board">×</button><span class="eyebrow">Hearthmere · west workshop commission</span><h2>A place to repair</h2><p>One approved parcel, with protected town access and an existing flat foundation. In shared worlds, the host manages construction and spends town materials on repairs. Commit finite shared town materials to a permanent workshop. No demolition, cancellation or refunds.</p><p>${options.disposable?'Use the model Step button above to advance work.':'Solo play pauses while this board is open. Close it to let residents travel and work; reopen to inspect progress.'}</p><p>From Hearthmere square, follow the west lane north beyond the last homes to the northwest board. Frames are prefabricated by your assigned resident at Second Life Salvage. Work counts only after arrival at its workbench. This board does not summon a worker onto the new parcel. Urgent needs and existing paid activities take priority; the resident resumes the commission when available.</p><button id="wc-visit" type="button">Visit Hearthmere</button><p id="wc-parcel"></p><details open><summary>Prepare the bounded building plan</summary>${WORKSHOP_AUTHORING_FIELDS.map(f=>`<label for="wc-${f.key}">${esc(f.label)} (${f.unit})</label><input id="wc-${f.key}" type="number" min="${f.min}" max="${f.max}" step="${f.step}"><small>${esc(f.effect)} Applies to the next explicit plan Apply.</small><button id="wc-default-${f.key}" type="button">Stage ${esc(f.label)} default</button>`).join('')}<div class="row"><button id="wc-apply" type="button">Apply plan</button><button id="wc-discard" type="button">Discard edits</button><button id="wc-defaults" type="button">Stage defaults</button></div><p id="wc-applied"></p><canvas id="wc-plan" width="560" height="360" aria-label="Applied workshop floor plan"></canvas><pre id="wc-cost"></pre></details><label for="wc-worker">Assign a resident · all 100 identities</label><select id="wc-worker"></select><p id="wc-worker-detail"></p><progress id="wc-progress" max="100" value="0" aria-label="Achieved construction work"></progress><p id="wc-current"></p><p id="wc-blocked"></p><div class="row"><button id="wc-build" type="button">Commit materials & build</button><button id="wc-repair" type="button">Repair suit · 4 town materials / up to 25 HP</button></div><p id="wc-status" role="status"></p><details><summary>Portable building recipe</summary><label for="wc-text">Recipe text · imports stage edits only</label><textarea id="wc-text" rows="7"></textarea><button id="wc-import" type="button">Stage recipe text</button><button id="wc-export" type="button">Export applied recipe to text</button><label for="wc-file">Stage recipe file · maximum 4 KB</label><input id="wc-file" type="file" accept="application/json,.json"></details>`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#wc-'+id)!;const marker=q('status');const current=()=>!disposed&&panel.querySelector('#wc-status')===marker;
 function message(s:string){if(current())marker.textContent=s;}
 function fill(d:WorkshopDraft){for(const f of WORKSHOP_AUTHORING_FIELDS)q<HTMLInputElement>(f.key).value=String(d[f.key]);}
 function staged(){generation++;message('Edits staged. Apply plan updates the quote; only Commit materials & build pays.');}
 function command():WorkshopConstructionCommand{return {kind:'build',expectedRevision:0,parcelId:WORKSHOP_PARCEL.id,parameters:applied,workerId:q<HTMLSelectElement>('worker').value};}
 function reason(c:WorkshopConstructionCommand){const state=options.getState();if(options.ready&&!options.ready())return 'Reach the west board on foot; wait for terrain and shared-world authority to be ready.';if(!state.townLife)return 'Visit Hearthmere to start town life before commissioning.';return workshopConstructionBlockReason(state.workshopConstruction,state.townLife,state,c);}
 function draw(){const ctx=q<HTMLCanvasElement>('plan').getContext('2d');if(!ctx)return;ctx.clearRect(0,0,560,360);ctx.fillStyle='#173c34';ctx.fillRect(0,0,560,360);for(const s of compileWorkshopDraft(applied).workshop.plan.shapes){if(s.center.y-s.half.y>2.2)continue;ctx.fillStyle=s.center.y+s.half.y<.1?'#405e52':'#c9bda1';ctx.fillRect(280+(s.center.x-s.half.x)*32,170+(s.center.z-s.half.z)*32,s.half.x*64,s.half.z*64);}ctx.fillStyle='#eacb86';ctx.font='14px sans-serif';ctx.fillText('N ↑  ·  Entry from south / board',12,340);}
 function refresh(){if(!current())return;const state=options.getState(),built=state.workshopConstruction,life=state.townLife;if(built&&applied!==built.parameters){applied=built.parameters;fill(applied);draw();}for(const f of WORKSHOP_AUTHORING_FIELDS){q<HTMLInputElement>(f.key).disabled=!!built;q<HTMLButtonElement>('default-'+f.key).disabled=!!built;}for(const id of ['apply','defaults','discard','import','file'])q<HTMLInputElement>(id).disabled=!!built;const quote=workshopConstructionQuote(applied),roster=townResidents(state.seed);const select=q<HTMLSelectElement>('worker');const selected=select.value||life?.residents.find(r=>assignTownWorkshopWorker(life,r.id))?.id||roster[0]!.id;
 if(select.dataset?.seed!==String(state.seed)){select.innerHTML=roster.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · ${esc(r.role)}</option>`).join('');if(select.dataset)select.dataset.seed=String(state.seed);}select.value=built?.workerId??selected;select.disabled=!!built;
 const worker=life?.residents.find(r=>r.id===select.value),identity=roster.find(r=>r.id===select.value);q('worker-detail').textContent=worker?`${identity?.name??worker.id}: ${worker.status} / ${worker.action??'no activity'} at x ${worker.x.toFixed(1)}, z ${worker.z.toFixed(1)}. ${worker.reason}`:'Town resident activity will appear after visiting Hearthmere.';
 q('parcel').textContent=`${WORKSHOP_PARCEL.label} · x ${WORKSHOP_PARCEL.x}, z ${WORKSHOP_PARCEL.z}; board x ${WORKSHOP_BOARD.x}, z ${WORKSHOP_BOARD.z}. Protected footprint ${WORKSHOP_PARCEL.hx*2} × ${WORKSHOP_PARCEL.hz*2} m.`;
 q('applied').textContent=`Applied plan: ${applied.width} × ${applied.depth} m, ${applied.rearRooms} rear rooms; hall ${applied.hallDepth} m, door ${applied.doorwayWidth} m; seed ${applied.seed}.`;
 q('cost').textContent=`Build payment: ${quote.materials} shared town materials. Available: ${life?.resources.materials??0}.\nAchieved prefabrication: ${quote.workSeconds} seconds. Recipe quantities: ${JSON.stringify(quote.recipeCosts)}.\nCompleted service: repair up to 25 suit HP for 4 shared materials.`;
 q('current').textContent=built?`${built.status.toUpperCase()} · ${built.work.toFixed(1)} / ${built.workRequired} achieved work seconds · ${built.materialsPaid} total materials paid · ${built.repairs} repairs. ${built.status==='building'?'Watch the assigned resident at Second Life Salvage; recovery and travel do not count as labor.':'Suit repair is now available at this board.'}`:'Unbuilt parcel. Applying a plan leaves the campaign unchanged.';
 q<HTMLProgressElement>('progress').value=built?100*built.work/built.workRequired:0;const blocked=reason(command()),repairBlocked=reason({kind:'repair',expectedRevision:built?.revision??0});q('blocked').textContent=built?(built.status==='complete'?repairBlocked??'Ready for paid suit repair.':'Prefabrication underway. Preserve the town workshop, water and resident needs; work resumes automatically.') :blocked??'Ready to commit the quoted town materials.';q<HTMLButtonElement>('build').disabled=!!blocked;q<HTMLButtonElement>('repair').disabled=!!repairBlocked;
 }
 function guard(action:()=>void){return ()=>{if(current()){generation++;try{action();}catch(e){message(e instanceof Error?e.message:String(e));}}};}
 for(const f of WORKSHOP_AUTHORING_FIELDS){q<HTMLInputElement>(f.key).oninput=staged;q('default-'+f.key).onclick=guard(()=>{q<HTMLInputElement>(f.key).value=String(f.default);staged();});}
 q('apply').onclick=guard(()=>{if(options.getState().workshopConstruction){message('This permanent workshop already has its committed plan.');return;}const next=validateWorkshopDraft(Object.fromEntries(WORKSHOP_AUTHORING_FIELDS.map(f=>[f.key,q<HTMLInputElement>(f.key).value.trim()?Number(q<HTMLInputElement>(f.key).value):NaN])));compileWorkshopDraft(next);applied=next;draw();refresh();message('Plan applied. No payment made. Commit explicitly at the board to build.');});
 q('discard').onclick=guard(()=>{fill(applied);message('Unapplied edits discarded.');});q('defaults').onclick=guard(()=>{fill({...DEFAULT_WORKSHOP_DRAFT,seed:options.getState().seed});staged();});q<HTMLSelectElement>('worker').onchange=async()=>{if(current()){generation++;refresh();}};
 q('build').onclick=guard(()=>{const c=command(),blocked=reason(c);if(blocked){message(blocked);return;}options.send(c);message('Build request sent. Authoritative campaign state determines acceptance and payment.');refresh();});
 q('repair').onclick=guard(()=>{const c:WorkshopConstructionCommand={kind:'repair',expectedRevision:options.getState().workshopConstruction?.revision??0},blocked=reason(c);if(blocked){message(blocked);return;}options.send(c);message('Paid repair request sent.');refresh();});
 function stage(text:string){if(options.getState().workshopConstruction)throw Error('This permanent workshop already has its committed plan.');fill(importWorkshopPreset(text));staged();}
 q('import').onclick=guard(()=>stage(q<HTMLTextAreaElement>('text').value));q('export').onclick=guard(()=>{q<HTMLTextAreaElement>('text').value=exportWorkshopPreset(applied);message('Applied recipe exported to text. Copy to retain it.');});q<HTMLTextAreaElement>('text').oninput=()=>{generation++;};
 q<HTMLInputElement>('file').onchange=async()=>{if(!current())return;const ticket=++generation,file=q<HTMLInputElement>('file').files?.[0];if(!file)return;try{if(file.size>WORKSHOP_PRESET_MAX_BYTES)throw Error('Preset exceeds 4 KB');const value=await file.text();if(current()&&ticket===generation)stage(value);}catch(e){if(current()&&ticket===generation)message(String(e));}};
 function dispose(){disposed=true;generation++;}q('close').onclick=guard(()=>{dispose();options.onClose();});q<HTMLButtonElement>('visit').disabled=!options.visit;q('visit').onclick=guard(()=>{dispose();options.visit?.();});fill(applied);draw();refresh();return {refresh,dispose,getApplied:()=>applied};
}
