import {mountWorkshopConstruction,type WorkshopConstructionViewState} from './workshop-construction-ui.ts';
import {createTownLife,createTownLifeOpening,advanceTownLife,advanceTownLifeWithWorkshopWork,debitTownWorkshopMaterials} from './town-life.ts';
import {WORKSHOP_BOARD,applyWorkshopConstruction,advanceWorkshopConstruction} from './workshop-construction.ts';
import {DEVELOPER_BUILD} from './developer-tools.ts';
export const WORKSHOP_CONSTRUCTION_SCENARIOS=Object.freeze([{id:'opening',label:'Active town opening'},{id:'ready',label:'Cold roster · available workers'},{id:'shortage',label:'Materials shortage'}] as const);
export const WORKSHOP_CONSTRUCTION_LAB_FIELDS=Object.freeze([{key:'seed',min:0,max:4294967295,step:1,default:73129,unit:'uint32',consumer:'Disposable town identity and recipe',timing:'Reset with draft'},{key:'seconds',min:1,max:60,step:1,default:10,unit:'seconds',consumer:'Achieved town work advance',timing:'Step model'}] as const);
/** Independent memory-only model: no campaign getter, storage, room, inventory or normal-slot API. */
export function mountWorkshopConstructionLab(panel:HTMLElement,options:{seed:number;source?:string;onClose:()=>void}){
 let disposed=false,elapsed=0,seed=options.seed,scenario='ready',actions:unknown[]=[],truncated=false;
 let state:WorkshopConstructionViewState={seed,zone:'valley',player:{...WORKSHOP_BOARD,hp:50},townLife:createTownLife(seed)};
 panel.innerHTML=`<button id="wcl-close" class="close" aria-label="Close construction lab">×</button><span class="eyebrow">Developer · disposable construction model</span><h2>Workshop construction rehearsal</h2><p>Solo-only, memory-only simulation. No campaign saves, rewards, room state, clock catch-up or live tuning. The nested board runs the real bounded recipe, payment and worker rules. It is a schematic model, not device visual verification.</p><label for="wcl-seed">Model seed · uint32, reset-time</label><input id="wcl-seed" type="number" min="0" max="4294967295" step="1"><label for="wcl-scenario">Repeatable setup · reset-time</label><select id="wcl-scenario">${WORKSHOP_CONSTRUCTION_SCENARIOS.map(s=>`<option value="${s.id}">${s.label}</option>`).join('')}</select><button id="wcl-reset-draft" type="button">Apply setup & reset model</button><button id="wcl-reset" type="button">Reset applied model</button><button id="wcl-discard" type="button">Discard setup edits</button><label for="wcl-seconds">Explicit step · 1–60 whole seconds</label><input id="wcl-seconds" type="number" min="1" max="60" step="1" value="10"><button id="wcl-step" type="button">Step real model</button><p id="wcl-status" role="status"></p><p>Hard limit: 1,200 model seconds per reset; 128 recorded actions. Reset restores finite scenario stock and suit health only in this disposable model. Recipe presets use the board’s strict v1 format; this setup is exported as evidence, never loaded as a campaign.</p><div id="wcl-board"></div><button id="wcl-report" type="button">Export model evidence to text</button><label for="wcl-text">Evidence text fallback</label><textarea id="wcl-text" rows="10"></textarea>`;
 const q=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#wcl-'+id)!;const marker=q('status'),current=()=>!disposed&&panel.querySelector('#wcl-status')===marker;
 const source=typeof options.source==='string'&&options.source.length<=160&&!/[\u0000-\u001f<>]/.test(options.source)?options.source:'source-unavailable';
 function record(action:unknown){if(actions.length<128)actions.push(action);else truncated=true;}
 let board:ReturnType<typeof mountWorkshopConstruction>;
 function mount(){board?.dispose();board=mountWorkshopConstruction(q('board'),{getState:()=>state,disposable:true,onClose:()=>{dispose();options.onClose();},send:command=>{if(!current()||!state.townLife)return;const result=applyWorkshopConstruction(state.workshopConstruction,state.townLife,state,command);record({kind:'command',command,accepted:!!result});if(result)state={...state,townLife:result.life,workshopConstruction:result.construction,player:{...state.player,hp:result.hp}};render(result?.message??'The real model rejected this request.');}});}
 function render(message='Model paused. Only explicit steps advance work.'){if(current())marker.textContent=`Applied seed ${seed} · ${scenario} · ${elapsed}/1200 seconds · ${state.townLife?.resources.materials} town materials · suit ${state.player.hp} HP. ${message}`;}
 function fill(){q<HTMLInputElement>('seed').value=String(seed);q<HTMLSelectElement>('scenario').value=scenario;}
 function reset(){elapsed=0;actions=[];truncated=false;let life=scenario==='opening'?createTownLifeOpening(seed):createTownLife(seed);if(scenario==='shortage')while(life.resources.materials>0){const next=debitTownWorkshopMaterials(life,Math.min(100,life.resources.materials));if(!next)throw Error('Could not debit disposable shortage stock.');life=next;}state={seed,zone:'valley',player:{...WORKSHOP_BOARD,hp:50},townLife:life};fill();mount();render('Reset restored only disposable test state.');}
 function step(seconds:number){if(!current())return;if(!Number.isInteger(seconds)||seconds<1||seconds>60)throw RangeError('Step requires 1–60 whole seconds.');const dt=Math.min(seconds,1200-elapsed);if(dt===0){render('Time limit reached. Reset for another run.');return;}let achievedWork=0;for(let remaining=dt;remaining>0;){const slice=Math.min(.5,remaining),built=state.workshopConstruction;if(built?.status==='building'){const result=advanceTownLifeWithWorkshopWork(state.townLife!,slice,built.workerId);state={...state,townLife:result.life,workshopConstruction:advanceWorkshopConstruction(built,result.workSeconds)};achievedWork+=result.workSeconds;}else state={...state,townLife:advanceTownLife(state.townLife!,slice)};remaining-=slice;}record({kind:'advance',seconds:dt,achievedWork});elapsed+=dt;board.refresh();render();}
 function guarded(fn:()=>void){return ()=>{if(current())try{fn();}catch(e){render(String(e));}};}
 q('reset-draft').onclick=guarded(()=>{const raw=q<HTMLInputElement>('seed').value,n=raw.trim()?Number(raw):NaN,s=q<HTMLSelectElement>('scenario').value;if(!Number.isSafeInteger(n)||n<0||n>0xffffffff||!WORKSHOP_CONSTRUCTION_SCENARIOS.some(c=>c.id===s))throw Error('Choose a uint32 seed and a listed scenario.');seed=n;scenario=s;reset();});q('reset').onclick=guarded(reset);q('discard').onclick=guarded(()=>{fill();render('Setup edits discarded.');});q('step').onclick=guarded(()=>step(Number(q<HTMLInputElement>('seconds').value)));
 function report(){return {format:'axiom-workshop-construction-evidence',version:1,scope:'disposable-model',build:DEVELOPER_BUILD,source,visualReview:'not-reviewed',seed,scenario,intended:{seed:q<HTMLInputElement>('seed').value,scenario:q<HTMLSelectElement>('scenario').value},elapsed,appliedRecipe:board.getApplied(),construction:state.workshopConstruction??null,playerHP:state.player.hp,resources:state.townLife!.resources,sources:state.townLife!.sources,ledger:state.townLife!.ledger,sourceLedger:state.townLife!.sourceLedger,worker:state.townLife!.residents.find(r=>r.id===state.workshopConstruction?.workerId)??null,actions,actionsTruncated:truncated};}
 q('report').onclick=guarded(()=>{q<HTMLTextAreaElement>('text').value=JSON.stringify(report(),null,2);render('Evidence ready to copy from text.');});function dispose(){if(disposed)return;disposed=true;board?.dispose();}q('close').onclick=guarded(()=>{dispose();options.onClose();});fill();mount();render();return {dispose,step,getState:()=>state,report};
}
