import {previewGeneration} from './generation.ts';
import {compileWaterworks,waterworksRecipe,type Waterworks} from './waterworks.ts';
import {compileWorkshop,workshopRecipe} from './building.ts';
import type {SemanticPlan,Recipe} from './procedural.ts';
export type WorkbenchRecipe='waterworks'|'workshop';
export function workbenchModel(kind:WorkbenchRecipe,seed:number,machine:Waterworks):{plan:SemanticPlan;recipe:Recipe} {
 if(kind==='waterworks')return {plan:compileWaterworks(machine,seed),recipe:waterworksRecipe(machine)};
 const workshop=compileWorkshop(seed);return {plan:workshop.plan,recipe:workshopRecipe(seed)};
}
/** Inspector only. Changing preview seeds never changes the live world or its saved manifest. */
export function mountWorkbench(panel:HTMLElement,machine:Waterworks,worldSeed:number,onClose:()=>void,generate=previewGeneration){
 panel.innerHTML=`<button class="close" aria-label="Close workbench">×</button><span class="eyebrow">AXIOM · semantic compiler v1</span><h2>Procedural workbench</h2><p>Inspect the exact plan behind your waterworks, or explore a bounded workshop recipe. The workshop view previews a recipe. Use the valley & vault inspector for placed buildings and routes.</p><form id="workbench-form"><label for="workbench-recipe">Recipe</label><select id="workbench-recipe"><option value="workshop">Frontier workshop · v1</option><option value="waterworks">Your waterworks · v1</option></select><label for="workbench-seed">Preview seed (0–4294967295)</label><div class="row"><input id="workbench-seed" type="number" min="0" max="4294967295" step="1" inputmode="numeric" required><button type="submit">Compile</button><button type="button" id="workbench-next" aria-label="Compile next seed">+1</button></div></form><p class="workbench-notice">Preview seeds leave your saved world unchanged. The deployed plan uses world seed ${worldSeed}. Waterworks geometry follows your installed modules.</p><p id="workbench-status" role="status" aria-live="polite"></p><canvas id="workbench-plan" width="560" height="380" aria-label="Top-down semantic plan. Solid walls, passable door gaps, exposed interfaces and connections."></canvas><p class="workbench-legend">Solid footprints · gold access/work ports · blue fluid ports · green connections. Roofs are outlined.</p><div id="workbench-summary"></div><label for="workbench-node">Inspect a semantic node</label><select id="workbench-node"></select><div id="workbench-inspection"></div><details><summary>Constraints and connection checks</summary><div id="workbench-constraints"></div></details><details><summary>Version manifest and connections</summary><pre id="workbench-manifest"></pre></details><details><summary>Bounded JSON recipe</summary><pre id="workbench-expression"></pre></details>`;
 const get=<T extends HTMLElement>(id:string)=>panel.querySelector<T>(`#${id}`)!;
 const seed=get<HTMLInputElement>('workbench-seed'),kind=get<HTMLSelectElement>('workbench-recipe'),nodes=get<HTMLSelectElement>('workbench-node'),canvas=get<HTMLCanvasElement>('workbench-plan');seed.value=String(worldSeed);
 let disposed=false,ticket=0,controller:AbortController|undefined;
 const current=()=>!disposed&&panel.querySelector('#workbench-plan')===canvas;
 function cancel(){ticket++;controller?.abort();controller=undefined;}
 function dispose(){if(disposed)return;disposed=true;cancel();}
 panel.querySelector<HTMLButtonElement>('.close')!.onclick=()=>{dispose();onClose();};
 let model:ReturnType<typeof workbenchModel>;
 function draw(){const ctx=canvas.getContext('2d');if(!ctx)return;const plan=model.plan;ctx.fillStyle='#153b35';ctx.fillRect(0,0,560,380);const shapes=plan.shapes;const minX=Math.min(-1,...shapes.map(s=>s.center.x-s.half.x)),maxX=Math.max(1,...shapes.map(s=>s.center.x+s.half.x)),minZ=Math.min(-1,...shapes.map(s=>s.center.z-s.half.z)),maxZ=Math.max(1,...shapes.map(s=>s.center.z+s.half.z));
  // Keep a remote workshop centered in its own plan instead of including world origin.
  const loX=shapes.length?Math.min(...shapes.map(s=>s.center.x-s.half.x)):minX,hiX=shapes.length?Math.max(...shapes.map(s=>s.center.x+s.half.x)):maxX,loZ=shapes.length?Math.min(...shapes.map(s=>s.center.z-s.half.z)):minZ,hiZ=shapes.length?Math.max(...shapes.map(s=>s.center.z+s.half.z)):maxZ;
  const scale=Math.min(500/Math.max(4,hiX-loX),320/Math.max(4,hiZ-loZ)),cx=(loX+hiX)/2,cz=(loZ+hiZ)/2,X=(x:number)=>280+(x-cx)*scale,Z=(z:number)=>190+(z-cz)*scale;
  for(const s of [...shapes].sort((a,b)=>a.center.y-b.center.y)){const x=X(s.center.x-s.half.x),z=Z(s.center.z-s.half.z),w=s.half.x*2*scale,h=s.half.z*2*scale;ctx.strokeStyle='#88a897';ctx.lineWidth=1;if(s.center.y-s.half.y>=2.5){ctx.strokeRect(x,z,w,h);continue;}ctx.fillStyle=s.nodeId===nodes.value?'#eccc87':s.center.y+s.half.y<.1?'#426256':s.material.includes('timber')?'#b39b75':'#a4b6a0';ctx.fillRect(x,z,w,h);ctx.strokeRect(x,z,w,h);}
  const ports=plan.nodes.flatMap(n=>n.ports);for(const c of plan.connections){const a=ports.find(p=>p.id===c.from),b=ports.find(p=>p.id===c.to);if(!a||!b)continue;ctx.strokeStyle='#74e8bd';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(X(a.position.x),Z(a.position.z));ctx.lineTo(X(b.position.x),Z(b.position.z));ctx.stroke();}
  for(const p of ports){ctx.fillStyle=p.type==='fluid'?'#91caec':'#f4ce8a';ctx.beginPath();ctx.arc(X(p.position.x),Z(p.position.z),4,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#d9e8d7';ctx.font='12px sans-serif';ctx.fillText('N ↑',14,20);ctx.fillText(`${(50/scale).toFixed(1)} m`,450,365);ctx.fillRect(450,349,50,2);if(!shapes.length)ctx.fillText('Install modules in the waterworks yard to inspect their plan',90,190);
 }
 function inspect(){if(!current()||!model)return;const n=model.plan.nodes.find(n=>n.id===nodes.value);get('workbench-inspection').textContent=n?`${n.key}\n${n.axiom}@${n.version}\n${n.id}\nParameters: ${JSON.stringify(n.params)}\nCosts: ${JSON.stringify(n.costs)}\nProperties: ${JSON.stringify(n.properties)}\n${n.ports.map(p=>`${p.key}: ${p.type}/${p.protocol} ${p.direction} · ${p.capacity} ${p.unit} · (${p.position.x.toFixed(2)}, ${p.position.y.toFixed(2)}, ${p.position.z.toFixed(2)})`).join('\n')}`:'No installed nodes';draw();}
 async function compile(){if(!current())return;cancel();const request=ticket,view=kind.value,seedText=seed.value,value=Number(seedText);if(!Number.isInteger(value)||value<0||value>4294967295||!seed.value.trim()){get('workbench-status').textContent='Enter a whole seed from 0 to 4294967295';return;}try{let mode='';if(view==='workshop'){controller=new AbortController();get('workbench-status').textContent='Compiling the bounded workshop…';const result=await generate({kind:'workshop',seed:value},controller.signal);if(!current()||request!==ticket||seed.value!==seedText||kind.value!==view)return;if(result.plan.kind!=='workshop')throw Error('Unexpected workshop preview');model={plan:result.plan.workshop.plan,recipe:workshopRecipe(value)};mode=result.backend==='worker'?' · worker compilation':` · synchronous${result.fallback?' fallback ('+result.fallback+')':''}`;}else model=workbenchModel('waterworks',value,machine);const p=model.plan;get('workbench-status').textContent=p.valid?'VALID PLAN · all enforced constraints passed':'INVALID PLAN · inspect the failed constraints';get('workbench-status').textContent+=mode;get('workbench-status').className=p.valid?'plan-valid':'plan-invalid';
  get('workbench-summary').textContent=`${p.nodes.length} nodes · ${p.shapes.length} shapes · ${p.connections.length} connections\nCost: ${Object.entries(p.costs).map(([k,v])=>`${v} ${k}`).join(' · ')||'none'}\n${p.operations} / ${model.recipe.limits.operations} operations · ${p.nodes.length} / ${model.recipe.limits.nodes} nodes · depth limit ${model.recipe.limits.depth}\nChoices: ${Object.entries(p.choices).map(([k,v])=>`${k} → ${v}`).join(' · ')||'player-authored assembly'}`;
  nodes.replaceChildren(...p.nodes.map(n=>{const o=document.createElement('option');o.value=n.id;o.textContent=n.key;return o;}));const checks=get('workbench-constraints');checks.replaceChildren(...p.constraints.map(c=>{const row=document.createElement('p');row.className=c.ok?'constraint-pass':'constraint-fail';row.textContent=`${c.ok?'✓':'✕'} ${c.key}: ${c.message}`;return row;}));
  get('workbench-manifest').textContent=JSON.stringify({framework:p.framework,recipe:p.recipe,seed:p.seed,owner:p.owner,axioms:p.manifest,exposed:p.exposed,connections:p.connections},null,2);get('workbench-expression').textContent=JSON.stringify(model.recipe,null,2);inspect();
 }catch(error){if(!current()||request!==ticket||(error instanceof Error&&error.name==='AbortError'))return;get('workbench-status').textContent=error instanceof Error?error.message:'Could not compile this preview';}}
 get<HTMLFormElement>('workbench-form').onsubmit=e=>{e.preventDefault();compile();};kind.onchange=compile;seed.oninput=()=>{if(!current())return;cancel();get('workbench-status').textContent='Seed edited · compile a new preview';};nodes.onchange=inspect;get('workbench-next').onclick=()=>{if(!current())return;seed.value=String((Number(seed.value)+1)>>>0);compile();};void compile();return dispose;
}
